import {randomUUID} from "node:crypto";
import type {Pool,PoolClient} from "pg";
import {deduplicationKey,notificationCopy,preferenceAllows} from "../../domain/notification/notification-rules.js";
import {notificationEventTypes,type NotificationEventType,type NotificationPreferences} from "../../domain/notification/notification-types.js";
import {inWorkerTransaction} from "../../infrastructure/transaction.js";

export type WorkerClock=()=>Date;
export interface WorkerSummary{claimed:number;completed:number;failed:number;deadLettered:number;notifications:number;reminders:number}
const allowed=new Set<string>(notificationEventTypes);
const actionUrl=(type:string,id:string)=>`/${type==="document"?"documents":`${type}s`}/${id}`;
const preferenceSelect=`tenant_id AS "tenantId",user_id AS "userId",in_app_enabled AS "inAppEnabled",task_events_enabled AS "taskEventsEnabled",project_events_enabled AS "projectEventsEnabled",finance_events_enabled AS "financeEventsEnabled",document_events_enabled AS "documentEventsEnabled",due_soon_enabled AS "dueSoonEnabled",overdue_enabled AS "overdueEnabled",self_notifications_enabled AS "selfNotificationsEnabled",version::int,created_at AS "createdAt",updated_at AS "updatedAt"`;

export class NotificationWorker{
 constructor(private readonly pool:Pool,private readonly options:{workerId?:string;batchSize?:number;maxAttempts?:number;dueSoonDays?:number;clock?:WorkerClock}={}){}
 private get workerId(){return this.options.workerId??`worker-${process.pid}`;} private get clock(){return this.options.clock??(()=>new Date());}
 private async tenants(){return (await this.pool.query<{id:string}>("SELECT id FROM tenants ORDER BY id")).rows.map(x=>x.id);}
 private async recipients(db:PoolClient,event:{event_type:string;entity_type:string;entity_id:string;actor_user_id:string|null;payload:Record<string,unknown>}){
  let rows:{id:string}[]=[];
  if(typeof event.payload.recipientUserId==="string")rows=[{id:event.payload.recipientUserId}];
  else if(event.event_type==="task.assigned"&&typeof event.payload.userId==="string")rows=[{id:event.payload.userId}];
  else if(event.entity_type==="task")rows=(await db.query<{id:string}>("SELECT u.id FROM task_assignments a JOIN users u ON u.id=a.user_id AND u.tenant_id=a.tenant_id WHERE a.task_id=$1 AND u.is_disabled=false AND u.deleted_at IS NULL",[event.entity_id])).rows;
  else if(event.entity_type==="project")rows=(await db.query<{id:string}>("SELECT u.id FROM projects p JOIN users u ON u.id=p.project_manager_id AND u.tenant_id=p.tenant_id WHERE p.id=$1 AND u.is_disabled=false AND u.deleted_at IS NULL",[event.entity_id])).rows;
  else if(["invoice","payment","expense"].includes(event.entity_type))rows=(await db.query<{id:string}>("SELECT DISTINCT u.id FROM users u JOIN user_roles ur ON ur.user_id=u.id AND ur.tenant_id=u.tenant_id JOIN role_permissions rp ON rp.role_id=ur.role_id JOIN permissions p ON p.id=rp.permission_id WHERE u.tenant_id=NULLIF(current_setting('app.tenant_id',true),'')::uuid AND p.code='finance.read' AND u.is_disabled=false AND u.deleted_at IS NULL")).rows;
  else if(event.entity_type==="document")rows=(await db.query<{id:string}>(`SELECT DISTINCT u.id FROM users u WHERE u.tenant_id=NULLIF(current_setting('app.tenant_id',true),'')::uuid AND u.is_disabled=false AND u.deleted_at IS NULL AND (u.id=(SELECT created_by FROM documents WHERE id=$1) OR u.id IN (SELECT p.project_manager_id FROM document_links l JOIN projects p ON l.entity_type='project' AND p.id=l.entity_id WHERE l.document_id=$1) OR u.id IN (SELECT a.user_id FROM document_links l JOIN task_assignments a ON l.entity_type='task' AND a.task_id=l.entity_id WHERE l.document_id=$1))`,[event.entity_id])).rows;
  if(!rows.length)return [];const valid=(await db.query<{id:string}>("SELECT id FROM users WHERE tenant_id=NULLIF(current_setting('app.tenant_id',true),'')::uuid AND id=ANY($1::uuid[]) AND is_disabled=false AND deleted_at IS NULL",[[...new Set(rows.map(x=>x.id))]])).rows;return valid.map(x=>x.id);
 }
 private async preferences(db:PoolClient,userId:string){await db.query("INSERT INTO notification_preferences(tenant_id,user_id) VALUES(NULLIF(current_setting('app.tenant_id',true),'')::uuid,$1) ON CONFLICT DO NOTHING",[userId]);return (await db.query<NotificationPreferences>(`SELECT ${preferenceSelect} FROM notification_preferences WHERE user_id=$1`,[userId])).rows[0];}
 private async consume(db:PoolClient,event:any){if(!allowed.has(event.event_type))throw new Error(`Unsupported notification event: ${event.event_type}`);const eventType=event.event_type as NotificationEventType,copy=notificationCopy(eventType),recipients=await this.recipients(db,event);let created=0;for(const userId of recipients){const preferences=await this.preferences(db,userId);if(!preferenceAllows(preferences,eventType,userId===event.actor_user_id))continue;const key=deduplicationKey(eventType,event.entity_id,userId,String(event.payload.windowKey??event.id));const inserted=await db.query<{id:string}>(`INSERT INTO notifications(tenant_id,recipient_user_id,event_type,title,body,severity,entity_type,entity_id,action_url,deduplication_key,source_event_id,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) ON CONFLICT(tenant_id,recipient_user_id,deduplication_key) DO NOTHING RETURNING id`,[event.tenant_id,userId,eventType,copy.title,copy.body,copy.severity,event.entity_type,event.entity_id,actionUrl(event.entity_type,event.entity_id),key,event.id,{correlationId:event.correlation_id}]);if(inserted.rows[0]){await db.query("INSERT INTO notification_deliveries(tenant_id,notification_id,recipient_user_id,delivered_at) VALUES($1,$2,$3,$4)",[event.tenant_id,inserted.rows[0].id,userId,this.clock()]);created++;}}
  return created;
 }
 async processTenant(tenantId:string):Promise<WorkerSummary>{const summary:WorkerSummary={claimed:0,completed:0,failed:0,deadLettered:0,notifications:0,reminders:0},limit=this.options.batchSize??25,max=this.options.maxAttempts??5;for(let i=0;i<limit;i++){const didWork=await inWorkerTransaction(this.pool,tenantId,async db=>{const event=(await db.query(`UPDATE outbox_events SET state='processing',locked_at=$1,locked_by=$2 WHERE id=(SELECT id FROM outbox_events WHERE tenant_id=$3 AND ((state IN ('pending','failed') AND next_attempt_at<=$1) OR (state='processing' AND locked_at<$1-interval '5 minutes')) ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT 1) RETURNING *`,[this.clock(),this.workerId,tenantId])).rows[0];if(!event)return false;summary.claimed++;try{summary.notifications+=await this.consume(db,event);await db.query("UPDATE outbox_events SET state='completed',processed_at=$1,locked_at=NULL,locked_by=NULL,last_error=NULL WHERE id=$2",[this.clock(),event.id]);summary.completed++;}catch(error){const attempts=event.attempt_count+1,dead=attempts>=max;await db.query("UPDATE outbox_events SET state=$1,attempt_count=$2,next_attempt_at=$3,locked_at=NULL,locked_by=NULL,last_error=$4 WHERE id=$5",[dead?"dead_letter":"failed",attempts,new Date(this.clock().getTime()+Math.min(60_000,1000*2**attempts)),error instanceof Error?error.message.slice(0,2000):"Unknown worker error",event.id]);dead?summary.deadLettered++:summary.failed++;}return true;});if(!didWork)break;}return summary;}
 async generateReminders(tenantId:string):Promise<number>{return inWorkerTransaction(this.pool,tenantId,async db=>{const now=this.clock(),today=now.toISOString().slice(0,10),days=this.options.dueSoonDays??Number(process.env.NOTIFICATION_DUE_SOON_DAYS??3);let count=0;const taskRows=(await db.query<{id:string;dueDate:string;userId:string}>(`SELECT t.id,t.due_date::text AS "dueDate",a.user_id AS "userId" FROM tasks t JOIN task_assignments a ON a.task_id=t.id AND a.tenant_id=t.tenant_id JOIN users u ON u.id=a.user_id AND u.tenant_id=a.tenant_id WHERE t.tenant_id=$1 AND t.deleted_at IS NULL AND t.status NOT IN ('completed','cancelled') AND t.due_date IS NOT NULL AND t.due_date<=$2::date+$3::int AND u.is_disabled=false AND u.deleted_at IS NULL`,[tenantId,today,days])).rows;const financeUsers=(await db.query<{id:string}>("SELECT DISTINCT u.id FROM users u JOIN user_roles ur ON ur.user_id=u.id AND ur.tenant_id=u.tenant_id JOIN role_permissions rp ON rp.role_id=ur.role_id JOIN permissions p ON p.id=rp.permission_id WHERE u.tenant_id=$1 AND p.code='finance.read' AND u.is_disabled=false AND u.deleted_at IS NULL",[tenantId])).rows;const invoiceRows=(await db.query<{id:string;dueDate:string}>(`SELECT id,due_date::text AS "dueDate" FROM invoices WHERE tenant_id=$1 AND deleted_at IS NULL AND status IN ('issued','partially_paid') AND due_date IS NOT NULL AND due_date<=$2::date+$3::int`,[tenantId,today,days])).rows;for(const row of [...taskRows.map(x=>({...x,entityType:"task" as const})),...invoiceRows.flatMap(x=>financeUsers.map(u=>({...x,userId:u.id,entityType:"invoice" as const})))]){const overdue=row.dueDate<today,type=`${row.entityType}.${overdue?"overdue":"due_soon"}` as NotificationEventType,windowKey=overdue?"first-overdue":`due-${row.dueDate}`,source=randomUUID();const inserted=await db.query("INSERT INTO reminder_executions(tenant_id,reminder_type,entity_type,entity_id,recipient_user_id,due_date,window_key,source_event_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(tenant_id,reminder_type,entity_id,recipient_user_id,window_key) DO NOTHING RETURNING id",[tenantId,type,row.entityType,row.id,row.userId,row.dueDate,windowKey,source]);if(inserted.rowCount){await db.query("INSERT INTO outbox_events(id,tenant_id,event_type,entity_type,entity_id,payload,correlation_id) VALUES($1,$2,$3,$4,$5,$6,$7)",[source,tenantId,type,row.entityType,row.id,{windowKey,recipientUserId:row.userId},randomUUID()]);count++;}}return count;});}
 async runCycle(){const aggregate:WorkerSummary={claimed:0,completed:0,failed:0,deadLettered:0,notifications:0,reminders:0};for(const tenant of await this.tenants()){aggregate.reminders+=await this.generateReminders(tenant);const x=await this.processTenant(tenant);for(const key of Object.keys(aggregate) as (keyof WorkerSummary)[])if(key!=="reminders")aggregate[key]+=x[key];}return aggregate;}
}
