import {randomUUID} from "node:crypto";
import type {Pool,PoolClient} from "pg";
import {assertCanCreateMeasurementUnits,assertCanReadMeasurementUnits,assertCanUpdateMeasurementUnits} from "../../authorization/measurement-unit-policy.js";
import {domainErrors} from "../../domain/errors.js";
import {assertConvertible,validateCreate,validateUpdate} from "../../domain/measurement-unit/measurement-unit-rules.js";
import type {CreateMeasurementUnit,MeasurementUnitListQuery,UpdateMeasurementUnit} from "../../domain/measurement-unit/measurement-unit-types.js";
import {MeasurementUnitRepository} from "../../infrastructure/measurement-unit/measurement-unit-repository.js";
import {inTenantTransaction} from "../../infrastructure/transaction.js";
export type MeasurementUnitActor={id:string;tenantId:string;permissions:readonly string[];correlationId:string};
export class MeasurementUnitService{
 constructor(private pool:Pool,private repo=new MeasurementUnitRepository()){}
 private audit(db:PoolClient,a:MeasurementUnitActor,action:string,id:string,metadata:Record<string,unknown>){return db.query("INSERT INTO audit_logs(tenant_id,actor_id,action,entity_type,entity_id,correlation_id,metadata) VALUES($1,$2,$3,'measurement_unit',$4,$5,$6)",[a.tenantId,a.id,action,id,/^[0-9a-f-]{36}$/i.test(a.correlationId)?a.correlationId:randomUUID(),metadata]);}
 async list(a:MeasurementUnitActor,q:MeasurementUnitListQuery){assertCanReadMeasurementUnits(a);return inTenantTransaction(this.pool,a.tenantId,db=>this.repo.list(db,a.tenantId,q));}
 async get(a:MeasurementUnitActor,id:string){assertCanReadMeasurementUnits(a);const x=await inTenantTransaction(this.pool,a.tenantId,db=>this.repo.findById(db,a.tenantId,id));if(!x)throw domainErrors.notFound();return x;}
 async create(a:MeasurementUnitActor,input:CreateMeasurementUnit){assertCanCreateMeasurementUnits(a);const x=validateCreate(input);try{return await inTenantTransaction(this.pool,a.tenantId,async db=>{const unit=await this.repo.create(db,a.tenantId,a.id,randomUUID(),x);await this.audit(db,a,"measurement_unit.created",unit.id,{code:unit.code,newVersion:unit.version});return unit;});}catch(e:any){if(e?.code==="23505")throw domainErrors.duplicate("Measurement unit code already exists");throw e;}}
 async update(a:MeasurementUnitActor,id:string,input:UpdateMeasurementUnit){assertCanUpdateMeasurementUnits(a);const x=validateUpdate(input);return inTenantTransaction(this.pool,a.tenantId,async db=>{const current=await this.repo.findById(db,a.tenantId,id);if(!current)throw domainErrors.notFound();if(current.version!==x.expectedVersion)throw domainErrors.conflict();const updated=await this.repo.update(db,a.tenantId,a.id,id,x);if(!updated)throw domainErrors.conflict();await this.audit(db,a,"measurement_unit.updated",id,{previousVersion:current.version,newVersion:updated.version,changes:x});return updated;});}
 async status(a:MeasurementUnitActor,id:string,status:"active"|"inactive",expectedVersion:number){assertCanUpdateMeasurementUnits(a);return inTenantTransaction(this.pool,a.tenantId,async db=>{const current=await this.repo.findById(db,a.tenantId,id);if(!current)throw domainErrors.notFound();if(current.version!==expectedVersion)throw domainErrors.conflict();if(current.status===status)throw domainErrors.transition();const updated=await this.repo.setStatus(db,a.tenantId,a.id,id,status,expectedVersion);if(!updated)throw domainErrors.conflict();await this.audit(db,a,`measurement_unit.${status==="active"?"activated":"deactivated"}`,id,{previousVersion:current.version,newVersion:updated.version});return updated;});}
 async convert(a:MeasurementUnitActor,fromId:string,toId:string,quantity:string,precision?:number){assertCanReadMeasurementUnits(a);return inTenantTransaction(this.pool,a.tenantId,async db=>{const from=await this.repo.findById(db,a.tenantId,fromId),to=await this.repo.findById(db,a.tenantId,toId);if(!from||!to)throw domainErrors.notFound();assertConvertible(from,to,quantity);const applied=precision??to.decimalPrecision;if(!Number.isInteger(applied)||applied<0||applied>12)throw domainErrors.validation("precision must be between 0 and 12");return {quantity,fromUnitId:from.id,toUnitId:to.id,result:await this.repo.convert(db,quantity,from,to,applied),precision:applied};});}
}
