import { randomUUID } from "node:crypto";
import type { Pool, PoolClient } from "pg";
import { assertCanArchiveClient,assertCanCreateClient,assertCanReadClient,assertCanUpdateClient } from "../../authorization/client-policy.js";
import { DomainError,domainErrors } from "../../domain/errors.js";
import { normalizeClient,normalizeClientUpdate } from "../../domain/client/client-rules.js";
import type { Client,ClientListQuery,ClientListResult,CreateClientCommand,UpdateClientCommand } from "../../domain/client/client-types.js";
import { ClientRepository } from "../../infrastructure/client/client-repository.js";
import { inTenantTransaction } from "../../infrastructure/transaction.js";

export type ClientActor={id:string;tenantId:string;permissions:readonly string[];correlationId:string};
const correlation=(value:string)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)?value:randomUUID();
export class ClientService {
  constructor(private readonly pool:Pool,private readonly repository=new ClientRepository()){}
  private async audit(db:PoolClient,actor:ClientActor,action:string,id:string|undefined,metadata:Record<string,unknown>={}){await db.query("INSERT INTO audit_logs(tenant_id,actor_id,action,entity_type,entity_id,correlation_id,metadata) VALUES($1,$2,$3,'client',$4,$5,$6)",[actor.tenantId,actor.id,action,id??null,correlation(actor.correlationId),metadata]);}
  private async authorize(actor:ClientActor,assertion:(actor:ClientActor)=>void,operation:string,id?:string){try{assertion(actor);}catch(error){await inTenantTransaction(this.pool,actor.tenantId,db=>this.audit(db,actor,"client.permission_denied",id,{operation}));throw error;}}
  private async recordFailure(actor:ClientActor,error:unknown,id?:string){if(!(error instanceof DomainError))return;const actions:Partial<Record<DomainError["code"],string>>={VERSION_CONFLICT:"client.version_conflict",DUPLICATE_RECORD:"client.duplicate_tax_id",ENTITY_ARCHIVED:"client.archived_mutation_denied"};const action=actions[error.code];if(action)await inTenantTransaction(this.pool,actor.tenantId,db=>this.audit(db,actor,action,id));}
  async createClient(actor:ClientActor,input:CreateClientCommand):Promise<Client>{await this.authorize(actor,assertCanCreateClient,"create");const value=normalizeClient(input);try{return await inTenantTransaction(this.pool,actor.tenantId,async db=>{if(value.taxId&&await this.repository.findDuplicateTaxId(db,actor.tenantId,value.taxId))throw domainErrors.duplicate("A client with this tax ID already exists");const entity=await this.repository.create(db,actor.tenantId,actor.id,randomUUID(),value);await this.audit(db,actor,"client.created",entity.id,{clientType:entity.clientType});return entity;});}catch(error){await this.recordFailure(actor,error);throw error;}}
  async getClient(actor:ClientActor,id:string):Promise<Client>{await this.authorize(actor,assertCanReadClient,"read",id);const entity=await inTenantTransaction(this.pool,actor.tenantId,db=>this.repository.findById(db,actor.tenantId,id));if(!entity)throw domainErrors.notFound();return entity;}
  async listClients(actor:ClientActor,query:ClientListQuery):Promise<ClientListResult>{await this.authorize(actor,assertCanReadClient,"list");if(!Number.isInteger(query.page)||query.page<1||!Number.isInteger(query.pageSize)||query.pageSize<1||query.pageSize>100)throw domainErrors.validation("Invalid pagination");if(!(["name","status","clientType","createdAt","updatedAt"] as string[]).includes(query.sortBy))throw domainErrors.validation("Invalid sort field");return inTenantTransaction(this.pool,actor.tenantId,db=>this.repository.list(db,actor.tenantId,query));}
  async updateClient(actor:ClientActor,id:string,input:UpdateClientCommand):Promise<Client>{await this.authorize(actor,assertCanUpdateClient,"update",id);const value=normalizeClientUpdate(input);try{return await inTenantTransaction(this.pool,actor.tenantId,async db=>{const current=await this.repository.findById(db,actor.tenantId,id);if(!current)throw domainErrors.notFound();if(current.archivedAt||current.status==="archived")throw domainErrors.archived();if(current.version!==value.expectedVersion)throw domainErrors.conflict();if(value.taxId&&await this.repository.findDuplicateTaxId(db,actor.tenantId,value.taxId,id))throw domainErrors.duplicate("A client with this tax ID already exists");const updated=await this.repository.update(db,actor.tenantId,actor.id,id,value);if(!updated)throw domainErrors.conflict();await this.audit(db,actor,"client.updated",id,{previousVersion:current.version,newVersion:updated.version});return updated;});}catch(error){await this.recordFailure(actor,error,id);throw error;}}
  async archiveClient(actor:ClientActor,id:string,expectedVersion:number):Promise<Client>{await this.authorize(actor,assertCanArchiveClient,"archive",id);if(!Number.isInteger(expectedVersion)||expectedVersion<1)throw domainErrors.validation("expectedVersion must be a positive integer");try{return await inTenantTransaction(this.pool,actor.tenantId,async db=>{const current=await this.repository.findById(db,actor.tenantId,id);if(!current)throw domainErrors.notFound();if(current.archivedAt||current.status==="archived")throw domainErrors.archived();if(current.version!==expectedVersion)throw domainErrors.conflict();const archived=await this.repository.archive(db,actor.tenantId,actor.id,id,expectedVersion);if(!archived)throw domainErrors.conflict();await this.audit(db,actor,"client.archived",id,{previousVersion:current.version,newVersion:archived.version});return archived;});}catch(error){await this.recordFailure(actor,error,id);throw error;}}
}
