import {randomUUID} from "node:crypto";
import type {Pool,PoolClient} from "pg";
import {assertCanCreatePriceList,assertCanReadPriceList,assertCanUpdatePriceList} from "../../authorization/price-list-policy.js";
import {DomainError,domainErrors} from "../../domain/errors.js";
import {validatePriceListCreate,validatePriceListItemCreate,validatePriceListItemUpdate,validatePriceListUpdate} from "../../domain/price-list/price-list-rules.js";
import type {CreatePriceList,CreatePriceListItem,PriceListItemQuery,PriceListQuery,UpdatePriceList,UpdatePriceListItem} from "../../domain/price-list/price-list-types.js";
import {PriceListRepository} from "../../infrastructure/price-list/price-list-repository.js";
import {inTenantTransaction} from "../../infrastructure/transaction.js";
export type PriceListActor={id:string;tenantId:string;permissions:readonly string[];correlationId:string};
export class PriceListService{
 constructor(private pool:Pool,private repo=new PriceListRepository()){}
 private audit(db:PoolClient,a:PriceListActor,entity:string,action:string,id:string,metadata:Record<string,unknown>){return db.query("INSERT INTO audit_logs(tenant_id,actor_id,action,entity_type,entity_id,correlation_id,metadata) VALUES($1,$2,$3,$4,$5,$6,$7)",[a.tenantId,a.id,action,entity,id,/^[0-9a-f-]{36}$/i.test(a.correlationId)?a.correlationId:randomUUID(),metadata]);}
 list(a:PriceListActor,q:PriceListQuery){assertCanReadPriceList(a);return inTenantTransaction(this.pool,a.tenantId,db=>this.repo.list(db,a.tenantId,q));}
 get(a:PriceListActor,id:string){assertCanReadPriceList(a);return inTenantTransaction(this.pool,a.tenantId,async db=>{const x=await this.repo.findList(db,a.tenantId,id);if(!x)throw domainErrors.notFound();return x;});}
 async create(a:PriceListActor,input:CreatePriceList){assertCanCreatePriceList(a);const x=validatePriceListCreate(input);try{return await inTenantTransaction(this.pool,a.tenantId,async db=>{const created=await this.repo.createList(db,a.tenantId,a.id,randomUUID(),x);await this.audit(db,a,"price_list","price_list.created",created.id,{code:created.code,newVersion:created.version});return created;});}catch(e:any){if(e?.code==="23505")throw domainErrors.duplicate("Price list code already exists");throw e;}}
 update(a:PriceListActor,id:string,input:UpdatePriceList){assertCanUpdatePriceList(a);return inTenantTransaction(this.pool,a.tenantId,async db=>{const current=await this.repo.findList(db,a.tenantId,id);if(!current)throw domainErrors.notFound();if(current.version!==input.expectedVersion)throw domainErrors.conflict();const x=validatePriceListUpdate(input,current),updated=await this.repo.updateList(db,a.tenantId,a.id,id,x);if(!updated)throw domainErrors.conflict();await this.audit(db,a,"price_list","price_list.updated",id,{previousVersion:current.version,newVersion:updated.version,changes:x});return updated;});}
 status(a:PriceListActor,id:string,status:"active"|"inactive",version:number){assertCanUpdatePriceList(a);return inTenantTransaction(this.pool,a.tenantId,async db=>{const current=await this.repo.findList(db,a.tenantId,id);if(!current)throw domainErrors.notFound();if(current.version!==version)throw domainErrors.conflict();if(current.status===status)throw domainErrors.transition();if(status==="inactive"&&await this.repo.activeItemCount(db,a.tenantId,id))throw new DomainError("INVALID_RELATIONSHIP",422,"Deactivate active price list items first");const updated=await this.repo.setListStatus(db,a.tenantId,a.id,id,status,version);if(!updated)throw domainErrors.conflict();await this.audit(db,a,"price_list",`price_list.${status==="active"?"activated":"deactivated"}`,id,{previousVersion:version,newVersion:updated.version});return updated;});}
 items(a:PriceListActor,q:PriceListItemQuery){assertCanReadPriceList(a);return inTenantTransaction(this.pool,a.tenantId,db=>this.repo.items(db,a.tenantId,q));}
 getItem(a:PriceListActor,id:string){assertCanReadPriceList(a);return inTenantTransaction(this.pool,a.tenantId,async db=>{const x=await this.repo.findItem(db,a.tenantId,id);if(!x)throw domainErrors.notFound();return x;});}
 async createItem(a:PriceListActor,input:CreatePriceListItem){assertCanCreatePriceList(a);const x=validatePriceListItemCreate(input);try{return await inTenantTransaction(this.pool,a.tenantId,async db=>{const list=await this.repo.findList(db,a.tenantId,x.priceListId),material=await this.repo.findMaterial(db,a.tenantId,x.materialId);if(!list||!material)throw domainErrors.notFound();if(list.status!=="active"||material.status!=="active")throw new DomainError("INVALID_RELATIONSHIP",422,"Price list and material must be active");if(x.currency!==list.currency)throw new DomainError("INVALID_RELATIONSHIP",422,"Item currency must match price list currency");if(x.validFrom<list.validFrom||(list.validTo&&(!x.validTo||x.validTo>list.validTo)))throw new DomainError("INVALID_RELATIONSHIP",422,"Item validity must be within price list validity");const created=await this.repo.createItem(db,a.tenantId,a.id,randomUUID(),x);await this.audit(db,a,"price_list_item","price_list_item.created",created.id,{priceListId:created.priceListId,materialId:created.materialId,newVersion:created.version});return created;});}catch(e:any){if(e?.code==="23505")throw domainErrors.duplicate("Price for this material and start date already exists");throw e;}}
 updateItem(a:PriceListActor,id:string,input:UpdatePriceListItem){assertCanUpdatePriceList(a);return inTenantTransaction(this.pool,a.tenantId,async db=>{const current=await this.repo.findItem(db,a.tenantId,id);if(!current)throw domainErrors.notFound();if(current.version!==input.expectedVersion)throw domainErrors.conflict();const list=await this.repo.findList(db,a.tenantId,current.priceListId),x=validatePriceListItemUpdate(input,current);if(!list)throw domainErrors.notFound();const currency=x.currency??current.currency,from=x.validFrom??current.validFrom,to=x.validTo===undefined?current.validTo:x.validTo;if(currency!==list.currency)throw new DomainError("INVALID_RELATIONSHIP",422,"Item currency must match price list currency");if(from<list.validFrom||(list.validTo&&(!to||to>list.validTo)))throw new DomainError("INVALID_RELATIONSHIP",422,"Item validity must be within price list validity");const updated=await this.repo.updateItem(db,a.tenantId,a.id,id,x);if(!updated)throw domainErrors.conflict();await this.audit(db,a,"price_list_item","price_list_item.updated",id,{previousVersion:current.version,newVersion:updated.version,changes:x});return updated;});}
 itemStatus(a:PriceListActor,id:string,status:"active"|"inactive",version:number){assertCanUpdatePriceList(a);return inTenantTransaction(this.pool,a.tenantId,async db=>{const current=await this.repo.findItem(db,a.tenantId,id);if(!current)throw domainErrors.notFound();if(current.version!==version)throw domainErrors.conflict();if(current.status===status)throw domainErrors.transition();if(status==="active"){const list=await this.repo.findList(db,a.tenantId,current.priceListId),material=await this.repo.findMaterial(db,a.tenantId,current.materialId);if(!list||!material||list.status!=="active"||material.status!=="active")throw new DomainError("INVALID_RELATIONSHIP",422,"Price list and material must be active");}const updated=await this.repo.setItemStatus(db,a.tenantId,a.id,id,status,version);if(!updated)throw domainErrors.conflict();await this.audit(db,a,"price_list_item",`price_list_item.${status==="active"?"activated":"deactivated"}`,id,{previousVersion:version,newVersion:updated.version});return updated;});}
}
