import{randomUUID}from"node:crypto";import type{RecognitionResult,SpeechRecognitionProvider,SpeechSynthesisProvider,SynthesisResult,TranslationProvider,TranslationResult,VoiceProviders}from"../../application/voice-bridge/voice-provider.js";
type Configuration={speechKey?:string;speechRegion?:string;translatorKey?:string;translatorRegion?:string;verified:boolean};type Fetch=typeof fetch;
export class AzureVoiceProvider implements SpeechRecognitionProvider,TranslationProvider,SpeechSynthesisProvider{readonly id="azure-speech";readonly truth:"REAL"|"PARTIAL";readonly reason:string;constructor(private config:Configuration,private fetcher:Fetch=fetch){this.truth=config.speechKey&&config.speechRegion&&config.translatorKey&&config.translatorRegion&&config.verified?"REAL":"PARTIAL";this.reason=this.truth==="REAL"?"Azure Speech and Translator credentials are configured and owner-verified.":"Azure official adapters are installed; credentials and live device verification are incomplete."}
 private ready(){if(this.truth!=="REAL")throw new Error("VOICE_PROVIDER_UNAVAILABLE")}
 async recognize(input:{audio:Buffer;contentType:string;language?:string}):Promise<RecognitionResult>{this.ready();const locale=input.language??"en-US",url=`https://${this.config.speechRegion}.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1?language=${encodeURIComponent(locale)}&format=detailed`,response=await this.fetcher(url,{method:"POST",headers:{"Ocp-Apim-Subscription-Key":this.config.speechKey!,"Content-Type":input.contentType,"Accept":"application/json"},body:new Uint8Array(input.audio)});if(!response.ok)throw providerError(response.status);const data=await response.json()as any,text=data.DisplayText??data.NBest?.[0]?.Display;if(!text)throw new Error("RECOGNITION_EMPTY");return{text,detectedLanguage:locale,providerReference:String(data.RecognitionStatus??"recognized")}}
 async translate(input:{text:string;sourceLanguage:string;targetLanguage:string}):Promise<TranslationResult>{this.ready();const url=`https://api.cognitive.microsofttranslator.com/translate?api-version=3.0&from=${encodeURIComponent(input.sourceLanguage)}&to=${encodeURIComponent(input.targetLanguage)}`,response=await this.fetcher(url,{method:"POST",headers:{"Ocp-Apim-Subscription-Key":this.config.translatorKey!,"Ocp-Apim-Subscription-Region":this.config.translatorRegion!,"Content-Type":"application/json","X-ClientTraceId":randomUUID()},body:JSON.stringify([{Text:input.text}])});if(!response.ok)throw providerError(response.status);const data=await response.json()as any[],text=data[0]?.translations?.[0]?.text;if(!text)throw new Error("TRANSLATION_EMPTY");return{text,sourceLanguage:input.sourceLanguage,targetLanguage:input.targetLanguage,providerReference:"azure-translator-v3",machineTranslation:true}}
 async synthesize(input:{text:string;language:string}):Promise<SynthesisResult>{this.ready();const voice=voiceFor(input.language),url=`https://${this.config.speechRegion}.tts.speech.microsoft.com/cognitiveservices/v1`,ssml=`<speak version="1.0" xml:lang="${escapeXml(input.language)}"><voice name="${voice}">${escapeXml(input.text)}</voice></speak>`,response=await this.fetcher(url,{method:"POST",headers:{"Ocp-Apim-Subscription-Key":this.config.speechKey!,"Content-Type":"application/ssml+xml","X-Microsoft-OutputFormat":"audio-24khz-48kbitrate-mono-mp3"},body:ssml});if(!response.ok)throw providerError(response.status);return{audio:Buffer.from(await response.arrayBuffer()),contentType:"audio/mpeg",providerReference:voice}}
}
function providerError(status:number){if(status===401||status===403)return new Error("INVALID_CREDENTIALS");if(status===429)return new Error("PROVIDER_RATE_LIMIT");if(status===408||status===504)return new Error("PROVIDER_TIMEOUT");return new Error(`VOICE_PROVIDER_ERROR:${status}`)}
function escapeXml(v:string){return v.replace(/[<>&'\"]/g,c=>({"<":"&lt;",">":"&gt;","&":"&amp;","'":"&apos;",'"':"&quot;"}[c]!))}
function voiceFor(language:string){const base=language.toLowerCase().split("-")[0];return base==="pl"?"pl-PL-ZofiaNeural":base==="ru"?"ru-RU-SvetlanaNeural":base==="de"?"de-DE-KatjaNeural":"en-US-AvaMultilingualNeural"}
export function createAzureVoiceProviders(environment:NodeJS.ProcessEnv=process.env):VoiceProviders{const provider=new AzureVoiceProvider({speechKey:environment.AZURE_SPEECH_KEY,speechRegion:environment.AZURE_SPEECH_REGION,translatorKey:environment.AZURE_TRANSLATOR_KEY,translatorRegion:environment.AZURE_TRANSLATOR_REGION,verified:environment.AZURE_VOICE_PROVIDER_VERIFIED==="true"});return{recognition:provider,translation:provider,synthesis:provider}}
