import{createHash}from"node:crypto";import{domainErrors}from"../errors.js";import type{ApprovedDesignProjectContent,DesignApplicability,DesignDecision,DesignProjectStatus,DesignReadinessInput}from"./design-project-types.js";
const transitions:Record<DesignProjectStatus,DesignProjectStatus[]>={draft:["collecting_information","review_required","cancelled"],collecting_information:["review_required","cancelled"],review_required:["changes_requested","ready_for_approval","cancelled"],changes_requested:["collecting_information","review_required","cancelled"],ready_for_approval:["approved","changes_requested","cancelled"],approved:["superseded"],cancelled:[],superseded:[]};
const error=(code:any,message:string,status=422)=>domainErrors.designProject(code,status,message);
export function assertDesignTransition(from:DesignProjectStatus,to:DesignProjectStatus){if(!transitions[from].includes(to))throw error("DESIGN_PROJECT_INVALID_TRANSITION",`Cannot transition from ${from} to ${to}`);}
export function assertDesignEditable(status:DesignProjectStatus){if(status==="approved")throw error("DESIGN_PROJECT_ALREADY_APPROVED","Approved design is immutable",409);if(status==="cancelled")throw error("DESIGN_PROJECT_CANCELLED","Cancelled design is immutable",409);if(status==="superseded")throw error("DESIGN_PROJECT_SUPERSEDED","Superseded design is immutable",409);if(status==="ready_for_approval")throw error("DESIGN_PROJECT_INVALID_TRANSITION","Request changes before editing");}
export function assertDesignVersion(version:number){if(!Number.isSafeInteger(version)||version<1)throw domainErrors.validation("expectedVersion must be a positive safe integer");}
export function validateDesignApplicability(a:DesignApplicability){const global=["entire_object","entire_design_project"].includes(a.targetType);if((global&&a.targetReference)||(!global&&!a.targetReference?.trim()))throw error("DESIGN_PROJECT_INVALID_APPLICABILITY","Applicability target is invalid");if(a.sourceType==="approved_room_scan"&&(!a.sourceSnapshotId||!/^[0-9a-f]{64}$/.test(a.sourceFingerprint??"")||!a.sourceSchemaVersion||!a.elementType))throw error("DESIGN_PROJECT_SOURCE_SNAPSHOT_INVALID","Approved Scanner provenance is incomplete");}
export function validateDesignDecision(d:DesignDecision){if(!d.title.trim()||!d.category.trim()||!d.orderingKey.trim())throw error("DESIGN_PROJECT_INVALID_DECISION","Decision identity is incomplete");d.applicability.forEach(validateDesignApplicability);const dimensions=[d.details.nominalWidth,d.details.nominalHeight,d.details.nominalDepth].filter(x=>x!==undefined);if(dimensions.some(x=>!Number.isFinite(x)||x!<=0)||dimensions.length&&!d.details.nominalUnit)throw error("DESIGN_PROJECT_INVALID_DECISION","Nominal dimensions are invalid");if(d.decisionType==="finish_selection"&&!d.details.family)throw error("DESIGN_PROJECT_INVALID_DECISION","Finish family is required");if(d.decisionType==="material_selection"&&!d.details.family)throw error("DESIGN_PROJECT_INVALID_DECISION","Material family is required");if(d.decisionType==="layout_decision"&&(!d.details.layoutType||!d.details.orientation))throw error("DESIGN_PROJECT_INVALID_DECISION","Layout type and orientation are required");if(d.decisionType==="color_decision"&&(!d.details.colorSystem||!d.details.colorCode))throw error("DESIGN_PROJECT_INVALID_DECISION","Typed color is required");if(d.decisionType==="fixture_selection"&&!d.details.fixtureCategory)throw error("DESIGN_PROJECT_INVALID_DECISION","Fixture category is required");if(d.decisionType==="design_exclusion"&&!d.details.exclusionKind)throw error("DESIGN_PROJECT_INVALID_DECISION","Exclusion kind is required");if(d.sourceType==="ai_suggestion")throw error("DESIGN_PROJECT_INVALID_DECISION","AI suggestion requires explicit human acceptance");}
export function evaluateDesignReadiness(input:DesignReadinessInput){if(!input.projectId)throw error("DESIGN_PROJECT_NOT_READY","Project reference is required");const active=input.decisions.filter(x=>x.reviewStatus!=="superseded").sort((a,b)=>a.orderingKey.localeCompare(b.orderingKey)||a.id.localeCompare(b.id)),accepted=active.filter(x=>x.reviewStatus==="accepted");if(!accepted.length)throw error("DESIGN_PROJECT_NOT_READY","At least one accepted design decision is required");accepted.forEach(validateDesignDecision);if(input.openItems.some(x=>x.blocking&&x.status==="open"))throw error("DESIGN_PROJECT_BLOCKING_ITEM_UNRESOLVED","Blocking item remains unresolved");for(const rejected of active.filter(x=>x.blocking&&x.reviewStatus==="rejected"))if(!accepted.some(x=>x.supersedesDecisionId===rejected.id))throw error("DESIGN_PROJECT_REJECTED_DECISION","Rejected blocking decision requires accepted replacement");if(active.some(x=>x.decisionType==="design_assumption"&&x.blocking&&x.details.assumptionRequiresConfirmation&&x.reviewStatus!=="accepted"))throw error("DESIGN_PROJECT_NOT_READY","Blocking assumption requires confirmation");if(active.some(x=>x.alternatives.filter(a=>a.state==="selected").length>1))throw error("DESIGN_PROJECT_AMBIGUOUS_SELECTION","Multiple selected alternatives");if(input.sourceIssues?.some(x=>x.blocking))throw error(input.sourceIssues[0].code as any,"Approved source snapshot consistency failed");return{ready:true,acceptedDecisions:accepted,openNonBlockingItems:input.openItems.filter(x=>!x.blocking&&x.status==="open").sort((a,b)=>a.id.localeCompare(b.id))};}
function canonical(v:unknown):unknown{if(Array.isArray(v))return v.map(canonical);if(v&&typeof v==="object")return Object.fromEntries(Object.entries(v as Record<string,unknown>).filter(([,x])=>x!==undefined).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>[k,canonical(x)]));return v;}
function orderDecision(d:DesignDecision):DesignDecision{return{...d,applicability:[...d.applicability].sort((a,b)=>a.orderingKey.localeCompare(b.orderingKey)),alternatives:[...d.alternatives].sort((a,b)=>a.orderingKey.localeCompare(b.orderingKey)||a.id.localeCompare(b.id))};}
export function canonicalDesignProject(c:ApprovedDesignProjectContent){return JSON.stringify(canonical({...c,decisions:[...c.decisions].map(orderDecision).sort((a,b)=>a.orderingKey.localeCompare(b.orderingKey)||a.id.localeCompare(b.id)),openNonBlockingItems:[...c.openNonBlockingItems].sort((a,b)=>a.id.localeCompare(b.id)),references:[...c.references].sort((a,b)=>a.id.localeCompare(b.id))}));}
export function fingerprintDesignProject(c:ApprovedDesignProjectContent){return createHash("sha256").update(canonicalDesignProject(c)).digest("hex");}
export function approvedDecisionBoundary(snapshotId:string,fingerprint:string,c:ApprovedDesignProjectContent){if(c.schemaVersion!=="design-project-v1"||!/^[0-9a-f]{64}$/.test(fingerprint)||fingerprintDesignProject(c)!==fingerprint)throw error("DESIGN_PROJECT_SNAPSHOT_INVALID","Approved snapshot is invalid");const decisions=c.decisions.filter(x=>x.reviewStatus==="accepted").map(orderDecision).sort((a,b)=>a.orderingKey.localeCompare(b.orderingKey)||a.id.localeCompare(b.id));return{snapshotId,snapshotFingerprint:fingerprint,schemaVersion:c.schemaVersion,designProjectId:c.designProjectId,revisionId:c.revisionId,revisionNumber:c.revisionNumber,projectId:c.projectId,propertyId:c.propertyId,decisions,exclusions:decisions.filter(x=>x.decisionType==="design_exclusion"),applicability:decisions.flatMap(x=>x.applicability).sort((a,b)=>a.orderingKey.localeCompare(b.orderingKey))};}
