import type {PoolClient} from "pg";
import type {ConstructionNorm,ConstructionNormItem,ConstructionNormItemQuery,ConstructionNormQuery,CreateConstructionNorm,CreateConstructionNormItem,NormPage,UpdateConstructionNorm,UpdateConstructionNormItem} from "../../domain/norm-catalog/norm-catalog-types.js";
const normSelect=`n.id,n.tenant_id "tenantId",n.code,n.display_name "displayName",n.work_id "workId",w.code "workCode",w.display_name "workName",n.description,n.status,n.is_system "isSystem",n.version::int,n.created_at "createdAt",n.updated_at "updatedAt",n.created_by "createdBy",n.updated_by "updatedBy"`;
const itemSelect=`i.id,i.tenant_id "tenantId",i.norm_id "normId",n.code "normCode",i.material_id "materialId",m.code "materialCode",m.display_name "materialName",i.quantity::text quantity,i.waste_percent::text "wastePercent",i.measurement_unit_id "measurementUnitId",u.code "measurementUnitCode",i.version::int,i.created_at "createdAt",i.updated_at "updatedAt",i.created_by "createdBy",i.updated_by "updatedBy"`;
const normSort={code:"n.code",displayName:"n.display_name",work:"w.display_name",status:"n.status",createdAt:"n.created_at",updatedAt:"n.updated_at"} as const;
const itemSort={material:"m.display_name",quantity:"i.quantity",wastePercent:"i.waste_percent",measurementUnit:"u.code",updatedAt:"i.updated_at"} as const;
export class NormCatalogRepository{
 findNorm(db:PoolClient,t:string,id:string){return db.query<ConstructionNorm>(`SELECT ${normSelect} FROM construction_norms n JOIN work_items w ON w.tenant_id=n.tenant_id AND w.id=n.work_id WHERE n.tenant_id=$1 AND n.id=$2`,[t,id]).then(r=>r.rows[0]);}
 findItem(db:PoolClient,t:string,id:string){return db.query<ConstructionNormItem>(`SELECT ${itemSelect} FROM construction_norm_items i JOIN construction_norms n ON n.tenant_id=i.tenant_id AND n.id=i.norm_id JOIN materials m ON m.tenant_id=i.tenant_id AND m.id=i.material_id JOIN measurement_units u ON u.tenant_id=i.tenant_id AND u.id=i.measurement_unit_id WHERE i.tenant_id=$1 AND i.id=$2`,[t,id]).then(r=>r.rows[0]);}
 findWork(db:PoolClient,t:string,id:string){return db.query<{id:string;status:string}>("SELECT id,status FROM work_items WHERE tenant_id=$1 AND id=$2",[t,id]).then(r=>r.rows[0]);}
 findMaterial(db:PoolClient,t:string,id:string){return db.query<{id:string;status:string;measurementUnitId:string}>('SELECT id,status,measurement_unit_id "measurementUnitId" FROM materials WHERE tenant_id=$1 AND id=$2',[t,id]).then(r=>r.rows[0]);}
 findUnit(db:PoolClient,t:string,id:string){return db.query<{id:string;status:string}>("SELECT id,status FROM measurement_units WHERE tenant_id=$1 AND id=$2",[t,id]).then(r=>r.rows[0]);}
 async norms(db:PoolClient,t:string,q:ConstructionNormQuery):Promise<NormPage<ConstructionNorm>>{const v:any[]=[t],f=["n.tenant_id=$1"];if(q.search){v.push(`%${q.search}%`);f.push(`(n.code ILIKE $${v.length} OR n.display_name ILIKE $${v.length} OR n.description ILIKE $${v.length} OR w.display_name ILIKE $${v.length})`);}if(q.workId){v.push(q.workId);f.push(`n.work_id=$${v.length}`);}if(q.active!==undefined){v.push(q.active?"active":"inactive");f.push(`n.status=$${v.length}`);}if(q.isSystem!==undefined){v.push(q.isSystem);f.push(`n.is_system=$${v.length}`);}const joins="construction_norms n JOIN work_items w ON w.tenant_id=n.tenant_id AND w.id=n.work_id",where=f.join(" AND "),total=Number((await db.query<{count:string}>(`SELECT count(*) FROM ${joins} WHERE ${where}`,v)).rows[0].count);v.push(q.pageSize,(q.page-1)*q.pageSize);const d=q.sortOrder==="asc"?"ASC":"DESC",items=(await db.query<ConstructionNorm>(`SELECT ${normSelect} FROM ${joins} WHERE ${where} ORDER BY ${normSort[q.sortBy]} ${d},n.id ${d} LIMIT $${v.length-1} OFFSET $${v.length}`,v)).rows;return {items,pagination:{page:q.page,pageSize:q.pageSize,total,totalPages:Math.ceil(total/q.pageSize)}};}
 async items(db:PoolClient,t:string,q:ConstructionNormItemQuery):Promise<NormPage<ConstructionNormItem>>{const v:any[]=[t],f=["i.tenant_id=$1"];if(q.search){v.push(`%${q.search}%`);f.push(`(m.code ILIKE $${v.length} OR m.display_name ILIKE $${v.length} OR n.code ILIKE $${v.length})`);}for(const[k,c]of [["normId","i.norm_id"],["materialId","i.material_id"],["measurementUnitId","i.measurement_unit_id"]] as const)if(q[k]){v.push(q[k]);f.push(`${c}=$${v.length}`);}const joins="construction_norm_items i JOIN construction_norms n ON n.tenant_id=i.tenant_id AND n.id=i.norm_id JOIN materials m ON m.tenant_id=i.tenant_id AND m.id=i.material_id JOIN measurement_units u ON u.tenant_id=i.tenant_id AND u.id=i.measurement_unit_id",where=f.join(" AND "),total=Number((await db.query<{count:string}>(`SELECT count(*) FROM ${joins} WHERE ${where}`,v)).rows[0].count);v.push(q.pageSize,(q.page-1)*q.pageSize);const d=q.sortOrder==="asc"?"ASC":"DESC",items=(await db.query<ConstructionNormItem>(`SELECT ${itemSelect} FROM ${joins} WHERE ${where} ORDER BY ${itemSort[q.sortBy]} ${d},i.id ${d} LIMIT $${v.length-1} OFFSET $${v.length}`,v)).rows;return {items,pagination:{page:q.page,pageSize:q.pageSize,total,totalPages:Math.ceil(total/q.pageSize)}};}
 createNorm(db:PoolClient,t:string,a:string,id:string,x:CreateConstructionNorm){return db.query<ConstructionNorm>(`WITH inserted AS (INSERT INTO construction_norms(id,tenant_id,code,display_name,work_id,description,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$7) RETURNING *) SELECT ${normSelect} FROM inserted n JOIN work_items w ON w.tenant_id=n.tenant_id AND w.id=n.work_id`,[id,t,x.code,x.displayName,x.workId,x.description??null,a]).then(r=>r.rows[0]);}
 updateNorm(db:PoolClient,t:string,a:string,id:string,x:UpdateConstructionNorm){const m=[["displayName","display_name"],["workId","work_id"],["description","description"]] as const,s:string[]=[],v:any[]=[];for(const[k,c]of m)if(x[k]!==undefined){v.push(x[k]);s.push(`${c}=$${v.length}`);}if(!s.length)return this.findNorm(db,t,id);v.push(a,id,t,x.expectedVersion);return db.query<ConstructionNorm>(`WITH updated AS (UPDATE construction_norms SET ${s.join(",")},updated_by=$${v.length-3},updated_at=now(),version=version+1 WHERE id=$${v.length-2} AND tenant_id=$${v.length-1} AND version=$${v.length} RETURNING *) SELECT ${normSelect} FROM updated n JOIN work_items w ON w.tenant_id=n.tenant_id AND w.id=n.work_id`,v).then(r=>r.rows[0]);}
 setStatus(db:PoolClient,t:string,a:string,id:string,status:string,version:number){return db.query<ConstructionNorm>(`WITH updated AS (UPDATE construction_norms SET status=$1,updated_by=$2,updated_at=now(),version=version+1 WHERE tenant_id=$3 AND id=$4 AND version=$5 RETURNING *) SELECT ${normSelect} FROM updated n JOIN work_items w ON w.tenant_id=n.tenant_id AND w.id=n.work_id`,[status,a,t,id,version]).then(r=>r.rows[0]);}
 itemCount(db:PoolClient,t:string,id:string){return db.query<{count:string}>("SELECT count(*) FROM construction_norm_items WHERE tenant_id=$1 AND norm_id=$2",[t,id]).then(r=>Number(r.rows[0].count));}
 createItem(db:PoolClient,t:string,a:string,id:string,x:CreateConstructionNormItem){return db.query<ConstructionNormItem>(`WITH inserted AS (INSERT INTO construction_norm_items(id,tenant_id,norm_id,material_id,quantity,waste_percent,measurement_unit_id,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$8) RETURNING *) SELECT ${itemSelect} FROM inserted i JOIN construction_norms n ON n.tenant_id=i.tenant_id AND n.id=i.norm_id JOIN materials m ON m.tenant_id=i.tenant_id AND m.id=i.material_id JOIN measurement_units u ON u.tenant_id=i.tenant_id AND u.id=i.measurement_unit_id`,[id,t,x.normId,x.materialId,x.quantity,x.wastePercent,x.measurementUnitId,a]).then(r=>r.rows[0]);}
 updateItem(db:PoolClient,t:string,a:string,id:string,x:UpdateConstructionNormItem){const m=[["quantity","quantity"],["wastePercent","waste_percent"],["measurementUnitId","measurement_unit_id"]] as const,s:string[]=[],v:any[]=[];for(const[k,c]of m)if(x[k]!==undefined){v.push(x[k]);s.push(`${c}=$${v.length}`);}if(!s.length)return this.findItem(db,t,id);v.push(a,id,t,x.expectedVersion);return db.query<ConstructionNormItem>(`WITH updated AS (UPDATE construction_norm_items SET ${s.join(",")},updated_by=$${v.length-3},updated_at=now(),version=version+1 WHERE id=$${v.length-2} AND tenant_id=$${v.length-1} AND version=$${v.length} RETURNING *) SELECT ${itemSelect} FROM updated i JOIN construction_norms n ON n.tenant_id=i.tenant_id AND n.id=i.norm_id JOIN materials m ON m.tenant_id=i.tenant_id AND m.id=i.material_id JOIN measurement_units u ON u.tenant_id=i.tenant_id AND u.id=i.measurement_unit_id`,v).then(r=>r.rows[0]);}
 deleteItem(db:PoolClient,t:string,id:string,version:number){return db.query<{id:string}>("DELETE FROM construction_norm_items WHERE tenant_id=$1 AND id=$2 AND version=$3 RETURNING id",[t,id,version]).then(r=>r.rows[0]);}
}
