import type {PoolClient} from "pg";
import type {Notification,NotificationListQuery,NotificationPreferences} from "../../domain/notification/notification-types.js";
const select=`id,tenant_id AS "tenantId",recipient_user_id AS "recipientUserId",event_type AS "eventType",title,body,severity,entity_type AS "entityType",entity_id AS "entityId",action_url AS "actionUrl",status,read_at AS "readAt",expires_at AS "expiresAt",deduplication_key AS "deduplicationKey",source_event_id AS "sourceEventId",metadata,version::int,created_at AS "createdAt",updated_at AS "updatedAt"`;
const preferenceSelect=`tenant_id AS "tenantId",user_id AS "userId",in_app_enabled AS "inAppEnabled",task_events_enabled AS "taskEventsEnabled",project_events_enabled AS "projectEventsEnabled",finance_events_enabled AS "financeEventsEnabled",document_events_enabled AS "documentEventsEnabled",due_soon_enabled AS "dueSoonEnabled",overdue_enabled AS "overdueEnabled",self_notifications_enabled AS "selfNotificationsEnabled",version::int,created_at AS "createdAt",updated_at AS "updatedAt"`;
export class NotificationRepository{
 async list(db:PoolClient,tenantId:string,userId:string,q:NotificationListQuery){const values:any[]=[tenantId,userId],filters=["tenant_id=$1","recipient_user_id=$2"];if(q.status){values.push(q.status);filters.push(`status=$${values.length}`);}if(q.severity){values.push(q.severity);filters.push(`severity=$${values.length}`);}if(q.eventType){values.push(q.eventType);filters.push(`event_type=$${values.length}`);}if(q.entityType){values.push(q.entityType);filters.push(`entity_type=$${values.length}`);}if(q.createdFrom){values.push(q.createdFrom);filters.push(`created_at>=$${values.length}::timestamptz`);}if(q.createdTo){values.push(q.createdTo);filters.push(`created_at<=$${values.length}::timestamptz`);}if(q.archived===false)filters.push("status<>'archived'");if(q.archived===true)filters.push("status='archived'");const where=filters.join(" AND "),total=Number((await db.query<{count:string}>(`SELECT count(*) FROM notifications WHERE ${where}`,values)).rows[0].count),sort={createdAt:"created_at",severity:"severity",status:"status"}[q.sortBy];values.push(q.pageSize,(q.page-1)*q.pageSize);const items=(await db.query<Notification>(`SELECT ${select} FROM notifications WHERE ${where} ORDER BY ${sort} ${q.sortOrder==="asc"?"ASC":"DESC"},created_at DESC LIMIT $${values.length-1} OFFSET $${values.length}`,values)).rows;return {items,pagination:{page:q.page,pageSize:q.pageSize,total,totalPages:Math.ceil(total/q.pageSize)}};}
 async find(db:PoolClient,tenantId:string,userId:string,id:string){return (await db.query<Notification>(`SELECT ${select} FROM notifications WHERE id=$1 AND tenant_id=$2 AND recipient_user_id=$3`,[id,tenantId,userId])).rows[0];}
 async unreadCount(db:PoolClient,tenantId:string,userId:string){return Number((await db.query<{count:string}>("SELECT count(*) FROM notifications WHERE tenant_id=$1 AND recipient_user_id=$2 AND status='unread'",[tenantId,userId])).rows[0].count);}
 async setStatus(db:PoolClient,tenantId:string,userId:string,id:string,status:"unread"|"read"|"archived",expectedVersion:number){return (await db.query<Notification>(`UPDATE notifications SET status=$1,read_at=CASE WHEN $1='read' THEN now() WHEN $1='unread' THEN NULL ELSE read_at END,updated_at=now(),version=version+1 WHERE id=$2 AND tenant_id=$3 AND recipient_user_id=$4 AND version=$5 RETURNING ${select}`,[status,id,tenantId,userId,expectedVersion])).rows[0];}
 async markAllRead(db:PoolClient,tenantId:string,userId:string){return (await db.query("UPDATE notifications SET status='read',read_at=now(),updated_at=now(),version=version+1 WHERE tenant_id=$1 AND recipient_user_id=$2 AND status='unread'",[tenantId,userId])).rowCount??0;}
 async preferences(db:PoolClient,tenantId:string,userId:string){await db.query("INSERT INTO notification_preferences(tenant_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING",[tenantId,userId]);return (await db.query<NotificationPreferences>(`SELECT ${preferenceSelect} FROM notification_preferences WHERE tenant_id=$1 AND user_id=$2`,[tenantId,userId])).rows[0];}
 async updatePreferences(db:PoolClient,tenantId:string,userId:string,input:Partial<NotificationPreferences>&{expectedVersion:number}){const mapping:Record<string,string>={inAppEnabled:"in_app_enabled",taskEventsEnabled:"task_events_enabled",projectEventsEnabled:"project_events_enabled",financeEventsEnabled:"finance_events_enabled",documentEventsEnabled:"document_events_enabled",dueSoonEnabled:"due_soon_enabled",overdueEnabled:"overdue_enabled",selfNotificationsEnabled:"self_notifications_enabled"},values:any[]=[],sets:string[]=[];for(const [key,column] of Object.entries(mapping))if(input[key as keyof typeof input]!==undefined){values.push(input[key as keyof typeof input]);sets.push(`${column}=$${values.length}`);}values.push(tenantId,userId,input.expectedVersion);return (await db.query<NotificationPreferences>(`UPDATE notification_preferences SET ${sets.join(",")},updated_at=now(),version=version+1 WHERE tenant_id=$${values.length-2} AND user_id=$${values.length-1} AND version=$${values.length} RETURNING ${preferenceSelect}`,values)).rows[0];}
 async audit(db:PoolClient,tenantId:string,actorId:string,action:string,id:string|undefined,correlationId:string,metadata:Record<string,unknown>={}){await db.query("INSERT INTO audit_logs(tenant_id,actor_id,action,entity_type,entity_id,correlation_id,metadata) VALUES($1,$2,$3,'notification',$4,$5,$6)",[tenantId,actorId,action,id??null,correlationId,metadata]);}
}
