import{randomUUID}from"node:crypto";
import{DomainError,domainErrors}from"../../domain/errors.js";
import type{RoomScanActor}from"../../authorization/room-scanner-policy.js";
import type{AddOpeningCommand,AddRoomCommand,AddSurfaceCommand,AssociateAttachmentCommand,CreateRoomScanCommand,ProcessingResult,RemoveAttachmentCommand,ReviewFactCommand,RoomScanEntityType,RoomScanWorkspace,UpdateAttachmentCommand}from"../../application/room-scanner/room-scan-commands.js";
import{RoomScanService as PostgresRoomScanStore}from"./postgres-room-scan-store.js";
import type{RoomScanRepositoryPort}from"./room-scan-unit-of-work.js";

/** Adds Phase 0 integrity behavior around the legacy-compatible PostgreSQL store. */
export class PostgresRoomScanPersistence extends PostgresRoomScanStore{
 constructor(private readonly unit:RoomScanRepositoryPort){super(unit);}
 override async create(actor:RoomScanActor,input:CreateRoomScanCommand){
  if(input.projectId){const valid=await this.unit.transaction(actor.tenantId,async db=>(await db.query("SELECT 1 FROM projects WHERE tenant_id=$1 AND id=$2 AND property_id=$3 AND deleted_at IS NULL",[actor.tenantId,input.projectId,input.propertyId])).rowCount===1);if(!valid)throw new DomainError("ROOM_SCAN_PROJECT_PROPERTY_MISMATCH",422,"Project does not belong to the selected property");}
  return super.create(actor,input);
 }
 private async editable(db:import("pg").PoolClient,actor:RoomScanActor,scanId:string,expectedVersion:number){const scan=(await db.query<{version:number;status:string}>("SELECT version::int,status FROM room_scan_sessions WHERE tenant_id=$1 AND id=$2 FOR UPDATE",[actor.tenantId,scanId])).rows[0];if(!scan)throw domainErrors.notFound();if(scan.version!==expectedVersion)throw domainErrors.conflict();if(!["capturing","review_required"].includes(scan.status))throw domainErrors.transition();return scan;}
 private async bumpScan(db:import("pg").PoolClient,actor:RoomScanActor,scanId:string,expectedVersion:number){if(!(await db.query("UPDATE room_scan_sessions SET version=version+1,updated_at=now(),updated_by=$1 WHERE tenant_id=$2 AND id=$3 AND version=$4",[actor.id,actor.tenantId,scanId,expectedVersion])).rowCount)throw domainErrors.conflict();}
override async addRoom(actor:RoomScanActor,scanId:string,input:AddRoomCommand){return this.unit.transaction(actor.tenantId,async db=>{await this.editable(db,actor,scanId,input.expectedVersion);const id=randomUUID();await db.query("INSERT INTO room_scan_rooms(id,tenant_id,scan_id,name,room_type,floor_number,created_by,updated_by)VALUES($1,$2,$3,$4,$5,$6,$7,$7)",[id,actor.tenantId,scanId,input.name,input.roomType,input.floorNumber??null,actor.id]);await this.bumpScan(db,actor,scanId,input.expectedVersion);await this.unit.audit(db,actor,"room_scan.room_added",scanId,{roomId:id});return{id};});}
 override async addSurface(actor:RoomScanActor,scanId:string,input:AddSurfaceCommand){return this.unit.transaction(actor.tenantId,async db=>{await this.editable(db,actor,scanId,input.expectedVersion);if(!(await db.query("SELECT 1 FROM room_scan_rooms WHERE tenant_id=$1 AND scan_id=$2 AND id=$3",[actor.tenantId,scanId,input.roomId])).rowCount)throw new DomainError("ROOM_SCAN_ENTITY_ASSOCIATION_INVALID",422,"Room does not belong to the scan");const id=randomUUID();await db.query("INSERT INTO room_scan_surfaces(id,tenant_id,scan_id,room_id,surface_type,label,polygon,orientation,confidence,created_by,updated_by)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$10)",[id,actor.tenantId,scanId,input.roomId,input.surfaceType,input.label,JSON.stringify(input.polygon),input.orientation??null,input.confidence??null,actor.id]);await this.bumpScan(db,actor,scanId,input.expectedVersion);await this.unit.audit(db,actor,"room_scan.surface_added",scanId,{surfaceId:id,roomId:input.roomId});return{id};});}
 override async addOpening(actor:RoomScanActor,scanId:string,input:AddOpeningCommand){return this.unit.transaction(actor.tenantId,async db=>{await this.editable(db,actor,scanId,input.expectedVersion);if(!(await db.query("SELECT 1 FROM room_scan_surfaces WHERE tenant_id=$1 AND scan_id=$2 AND room_id=$3 AND id=$4",[actor.tenantId,scanId,input.roomId,input.surfaceId])).rowCount)throw new DomainError("ROOM_SCAN_ENTITY_ASSOCIATION_INVALID",422,"Surface does not belong to the room and scan");const id=randomUUID();await db.query("INSERT INTO room_scan_openings(id,tenant_id,scan_id,room_id,surface_id,opening_type,width_m,height_m,sill_height_m,reveal_depth_m,source,verification_status,created_by,updated_by)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$13)",[id,actor.tenantId,scanId,input.roomId,input.surfaceId,input.openingType,input.widthM,input.heightM,input.sillHeightM??null,input.revealDepthM??null,input.source,input.source==="human_correction"?"verified":"requires_review",actor.id]);await this.bumpScan(db,actor,scanId,input.expectedVersion);await this.unit.audit(db,actor,"room_scan.opening_added",scanId,{openingId:id,roomId:input.roomId,surfaceId:input.surfaceId});return{id};});}
 async associateAttachment(actor:RoomScanActor,scanId:string,input:AssociateAttachmentCommand){
  return this.unit.transaction(actor.tenantId,async db=>{const scan=(await db.query<{version:number;propertyId:string;projectId:string|null}>("SELECT version::int,property_id AS \"propertyId\",project_id AS \"projectId\" FROM room_scan_sessions WHERE tenant_id=$1 AND id=$2 FOR UPDATE",[actor.tenantId,scanId])).rows[0];if(!scan)throw domainErrors.notFound();if(scan.version!==input.expectedVersion)throw domainErrors.conflict();
   if(input.roomId&&!(await db.query("SELECT 1 FROM room_scan_rooms WHERE tenant_id=$1 AND scan_id=$2 AND id=$3",[actor.tenantId,scanId,input.roomId])).rowCount)throw new DomainError("ROOM_SCAN_ENTITY_ASSOCIATION_INVALID",422,"Room does not belong to the scan");
   const file=(await db.query<{status:string;projectOk:boolean}>(`SELECT f.status,EXISTS(SELECT 1 FROM document_versions v JOIN documents d ON d.tenant_id=v.tenant_id AND d.id=v.document_id JOIN document_links l ON l.tenant_id=d.tenant_id AND l.document_id=d.id WHERE v.tenant_id=f.tenant_id AND v.file_object_id=f.id AND((l.entity_type='project'AND l.entity_id=$3)OR(l.entity_type='property'AND l.entity_id=$4)))AS "projectOk" FROM file_objects f WHERE f.tenant_id=$1 AND f.id=$2`,[actor.tenantId,input.fileObjectId,scan.projectId,scan.propertyId])).rows[0];
   if(!file||file.status!=="available"||!file.projectOk)throw new DomainError("ROOM_SCAN_ATTACHMENT_INVALID",422,"File is not owned by the scan project or property");
   const id=randomUUID();try{await db.query("INSERT INTO room_scan_attachments(id,tenant_id,scan_id,room_id,file_object_id,purpose,sort_order,associated_by)VALUES($1,$2,$3,$4,$5,$6,$7,$8)",[id,actor.tenantId,scanId,input.roomId??null,input.fileObjectId,input.purpose,input.sortOrder??0,actor.id]);}catch(error){if(error instanceof Error&&/unique|duplicate/i.test(error.message))throw new DomainError("ROOM_SCAN_ATTACHMENT_INVALID",422,"File is already attached to a scan");throw error;}
   await db.query("UPDATE room_scan_sessions SET version=version+1,updated_at=now(),updated_by=$1 WHERE tenant_id=$2 AND id=$3 AND version=$4",[actor.id,actor.tenantId,scanId,input.expectedVersion]);await this.unit.audit(db,actor,"room_scan.attachment_associated",scanId,{attachmentId:id,fileObjectId:input.fileObjectId,roomId:input.roomId??null,purpose:input.purpose});return{id};});
 }
 async removeAttachment(actor:RoomScanActor,scanId:string,attachmentId:string,input:RemoveAttachmentCommand){return this.unit.transaction(actor.tenantId,async db=>{const scan=(await db.query<{version:number}>("SELECT version::int FROM room_scan_sessions WHERE tenant_id=$1 AND id=$2 FOR UPDATE",[actor.tenantId,scanId])).rows[0];if(!scan)throw domainErrors.notFound();if(scan.version!==input.expectedVersion)throw domainErrors.conflict();const row=await db.query("UPDATE room_scan_attachments SET removed_at=now(),removed_by=$1,version=version+1 WHERE tenant_id=$2 AND scan_id=$3 AND id=$4 AND removed_at IS NULL RETURNING file_object_id",[actor.id,actor.tenantId,scanId,attachmentId]);if(!row.rowCount)throw domainErrors.notFound();await db.query("UPDATE room_scan_sessions SET version=version+1,updated_at=now(),updated_by=$1 WHERE tenant_id=$2 AND id=$3 AND version=$4",[actor.id,actor.tenantId,scanId,input.expectedVersion]);await this.unit.audit(db,actor,"room_scan.attachment_removed",scanId,{attachmentId});return{id:attachmentId};});}
 async updateAttachment(actor:RoomScanActor,scanId:string,attachmentId:string,input:UpdateAttachmentCommand){return this.unit.transaction(actor.tenantId,async db=>{await this.editable(db,actor,scanId,input.expectedVersion);if(input.roomId&&!(await db.query("SELECT 1 FROM room_scan_rooms WHERE tenant_id=$1 AND scan_id=$2 AND id=$3",[actor.tenantId,scanId,input.roomId])).rowCount)throw new DomainError("ROOM_SCAN_ENTITY_ASSOCIATION_INVALID",422,"Room does not belong to the scan");const row=await db.query(`UPDATE room_scan_attachments SET display_name=COALESCE($1,display_name),room_id=CASE WHEN $2::boolean THEN $3::uuid ELSE room_id END,sort_order=COALESCE($4,sort_order),version=version+1 WHERE tenant_id=$5 AND scan_id=$6 AND id=$7 AND removed_at IS NULL RETURNING id`,[input.displayName??null,Object.prototype.hasOwnProperty.call(input,"roomId"),input.roomId??null,input.sortOrder??null,actor.tenantId,scanId,attachmentId]);if(!row.rowCount)throw domainErrors.notFound();await this.bumpScan(db,actor,scanId,input.expectedVersion);await this.unit.audit(db,actor,"room_scan.attachment_updated",scanId,{attachmentId,displayName:input.displayName,roomId:input.roomId,sortOrder:input.sortOrder});return{id:attachmentId};});}
 async deleteEntity(actor:RoomScanActor,scanId:string,type:RoomScanEntityType,entityId:string,expectedVersion:number){return this.unit.transaction(actor.tenantId,async db=>{await this.editable(db,actor,scanId,expectedVersion);const table=({rooms:"room_scan_rooms",surfaces:"room_scan_surfaces",measurements:"room_scan_measurements",openings:"room_scan_openings",observations:"room_scan_observations"}as const)[type];try{const row=await db.query(`DELETE FROM ${table} WHERE tenant_id=$1 AND scan_id=$2 AND id=$3 RETURNING id`,[actor.tenantId,scanId,entityId]);if(!row.rowCount)throw domainErrors.notFound();}catch(error){if(error instanceof Error&&/foreign key|violates/i.test(error.message))throw domainErrors.validation("Remove dependent facts before deleting this item",{code:"ROOM_SCAN_ENTITY_IN_USE"});throw error;}await this.bumpScan(db,actor,scanId,expectedVersion);await this.unit.audit(db,actor,"room_scan.entity_deleted",scanId,{entityType:type,entityId});return{id:entityId};});}
 override async reviewEntity(actor:RoomScanActor,scanId:string,input:ReviewFactCommand){return this.unit.transaction(actor.tenantId,async db=>{const scan=await this.editable(db,actor,scanId,input.expectedVersion);if(scan.status!=="review_required")throw domainErrors.transition();const mapping={measurement:{table:"room_scan_measurements",column:"verification_status",confirmed:"verified"},surface:{table:"room_scan_surfaces",column:"review_status",confirmed:"verified"},opening:{table:"room_scan_openings",column:"verification_status",confirmed:"verified"},observation:{table:"room_scan_observations",column:"review_status",confirmed:"confirmed"}}as const,definition=mapping[input.entityType],status=input.decision==="confirmed"?definition.confirmed:input.decision==="rejected"?"rejected":"requires_review";if(!(await db.query(`UPDATE ${definition.table} SET ${definition.column}=$1,version=version+1,updated_at=now(),updated_by=$2 WHERE tenant_id=$3 AND scan_id=$4 AND id=$5`,[status,actor.id,actor.tenantId,scanId,input.entityId])).rowCount)throw domainErrors.notFound();await db.query("INSERT INTO room_scan_fact_reviews(tenant_id,scan_id,entity_type,entity_id,decision,comment,reviewed_by)VALUES($1,$2,$3,$4,$5,$6,$7)",[actor.tenantId,scanId,input.entityType,input.entityId,input.decision,input.comment??null,actor.id]);await db.query("UPDATE room_scan_quantities SET validity_status='invalidated',invalidated_at=now(),invalidated_by=$1,invalidation_reason='source_review_changed',version=version+1,updated_at=now(),updated_by=$1 WHERE tenant_id=$2 AND scan_id=$3 AND validity_status='valid'",[actor.id,actor.tenantId,scanId]);await this.bumpScan(db,actor,scanId,input.expectedVersion);await this.unit.audit(db,actor,"room_scan.review_item_changed",scanId,{entityType:input.entityType,entityId:input.entityId,decision:input.decision,comment:input.comment??null});return(await db.query<any>(`SELECT id,tenant_id "tenantId",property_id "propertyId",project_id "projectId",status,revision,ingestion_key "ingestionKey",notes,version::int,created_at "createdAt",created_by "createdBy",updated_at "updatedAt",updated_by "updatedBy" FROM room_scan_sessions WHERE tenant_id=$1 AND id=$2`,[actor.tenantId,scanId])).rows[0];});}
 async workspace(actor:RoomScanActor,scanId:string):Promise<RoomScanWorkspace>{return this.unit.transaction(actor.tenantId,async db=>{const scan=(await db.query<any>(`SELECT id,tenant_id "tenantId",property_id "propertyId",project_id "projectId",status,revision,notes,version::int,created_at "createdAt",created_by "createdBy",updated_at "updatedAt",updated_by "updatedBy" FROM room_scan_sessions WHERE tenant_id=$1 AND id=$2`,[actor.tenantId,scanId])).rows[0];if(!scan)throw domainErrors.notFound();const results=[];
 results.push(await db.query(`SELECT id,name,room_type "roomType",floor_number "floorNumber",version::int,created_at "createdAt",created_by "createdBy",updated_at "updatedAt",updated_by "updatedBy" FROM room_scan_rooms WHERE tenant_id=$1 AND scan_id=$2 ORDER BY name,id`,[actor.tenantId,scanId]));
 results.push(await db.query(`SELECT id,room_id "roomId",surface_type "surfaceType",label,polygon,orientation::float8,review_status "reviewStatus",version::int,created_at "createdAt",created_by "createdBy",updated_by "updatedBy" FROM room_scan_surfaces WHERE tenant_id=$1 AND scan_id=$2 ORDER BY room_id,label,id`,[actor.tenantId,scanId]));
 results.push(await db.query(`SELECT id,room_id "roomId",surface_id "surfaceId",measurement_type "measurementType",source,original_value::float8 "originalValue",original_unit "originalUnit",si_value::float8 "siValue",si_unit "siUnit",verification_status "verificationStatus",captured_at "capturedAt",captured_by "createdBy",provenance,version::int,updated_by "updatedBy" FROM room_scan_measurements WHERE tenant_id=$1 AND scan_id=$2 ORDER BY room_id,measurement_type,captured_at,id`,[actor.tenantId,scanId]));
 results.push(await db.query(`SELECT id,room_id "roomId",surface_id "surfaceId",opening_type "openingType",width_m::float8 "widthM",height_m::float8 "heightM",sill_height_m::float8 "sillHeightM",reveal_depth_m::float8 "revealDepthM",position,source,verification_status "verificationStatus",version::int,created_at "createdAt",created_by "createdBy",updated_by "updatedBy" FROM room_scan_openings WHERE tenant_id=$1 AND scan_id=$2 ORDER BY room_id,opening_type,id`,[actor.tenantId,scanId]));
 results.push(await db.query(`SELECT id,room_id "roomId",surface_id "surfaceId",observation_kind "observationKind",observation_type "observationType",details,source,review_status "reviewStatus",version::int,created_at "createdAt",created_by "createdBy",updated_by "updatedBy" FROM room_scan_observations WHERE tenant_id=$1 AND scan_id=$2 ORDER BY room_id,created_at,id`,[actor.tenantId,scanId]));
 results.push(await db.query(`SELECT a.id,a.room_id "roomId",a.file_object_id "fileObjectId",a.purpose,COALESCE(a.display_name,f.original_filename)"displayName",a.sort_order "sortOrder",a.version::int,a.associated_at "createdAt",a.associated_by "createdBy",f.mime_type "mimeType",f.size_bytes::int "sizeBytes",d.id "documentId",v.id "documentVersionId" FROM room_scan_attachments a JOIN file_objects f ON f.tenant_id=a.tenant_id AND f.id=a.file_object_id LEFT JOIN document_versions v ON v.tenant_id=a.tenant_id AND v.file_object_id=a.file_object_id LEFT JOIN documents d ON d.tenant_id=v.tenant_id AND d.id=v.document_id WHERE a.tenant_id=$1 AND a.scan_id=$2 AND a.removed_at IS NULL ORDER BY a.sort_order,a.associated_at,a.id`,[actor.tenantId,scanId]));
 results.push(await db.query(`SELECT id,room_id "roomId",surface_id "surfaceId",quantity_type type,value::float8,unit,formula_id "formulaId",input_references "inputReferences",source_versions "sourceVersions",calculation_version "calculationVersion",validity_status "validityStatus",version::int,calculated_at "calculatedAt" FROM room_scan_quantities WHERE tenant_id=$1 AND scan_id=$2 ORDER BY room_id,quantity_type,id`,[actor.tenantId,scanId]));
 results.push(await db.query(`SELECT r.id,r.entity_type "entityType",r.entity_id "entityId",r.decision,r.comment,r.reviewed_at "reviewedAt",r.reviewed_by "reviewedBy",u.display_name "reviewerName" FROM room_scan_fact_reviews r JOIN users u ON u.tenant_id=r.tenant_id AND u.id=r.reviewed_by WHERE r.tenant_id=$1 AND r.scan_id=$2 ORDER BY r.reviewed_at DESC,r.id`,[actor.tenantId,scanId]));
 results.push(await db.query(`SELECT a.id,a.action,a.metadata,a.occurred_at "occurredAt",a.actor_id "actorId",u.display_name "actorName" FROM audit_logs a LEFT JOIN users u ON u.tenant_id=a.tenant_id AND u.id=a.actor_id WHERE a.tenant_id=$1 AND a.entity_type='room_scan' AND a.entity_id=$2 ORDER BY a.occurred_at DESC,a.id LIMIT 250`,[actor.tenantId,scanId]));
 results.push(await db.query(`SELECT id,scan_version::int "scanVersion",content_fingerprint "contentFingerprint",calculation_version "calculationVersion",approved_at "approvedAt",approved_by "approvedBy" FROM approved_room_scan_snapshots WHERE tenant_id=$1 AND scan_id=$2 ORDER BY approved_at DESC,id`,[actor.tenantId,scanId]));const[rooms,surfaces,measurements,openings,observations,attachments,quantities,reviews,history,snapshots]=results;
 const issues:Record<string,unknown>[]=[];if(!rooms.rowCount)issues.push({code:"MISSING_ROOM",entityType:"scan",entityId:scanId,field:"rooms",severity:"error",messageKey:"room_scan.completeness.missing_room"});if(!attachments.rowCount)issues.push({code:"MISSING_PHOTOS",entityType:"scan",entityId:scanId,field:"attachments",severity:"error",messageKey:"room_scan.completeness.missing_photos"});for(const room of rooms.rows){const rm=measurements.rows.filter(x=>x.roomId===room.id&&x.verificationStatus!=="rejected"),types=new Set(rm.map(x=>x.measurementType));for(const type of["width","length","height"])if(!types.has(type))issues.push({code:"MISSING_MEASUREMENT",entityType:"room",entityId:room.id,field:type,severity:"error",messageKey:"room_scan.completeness.missing_measurement"});const rs=surfaces.rows.filter(x=>x.roomId===room.id&&x.reviewStatus!=="rejected");for(const type of["wall","floor","ceiling"])if(!rs.some(x=>x.surfaceType===type))issues.push({code:`MISSING_${type.toUpperCase()}`,entityType:"room",entityId:room.id,field:"surfaces",severity:"error",messageKey:`room_scan.completeness.missing_${type}`});if(!attachments.rows.some(x=>x.roomId===room.id||x.roomId===null))issues.push({code:"MISSING_ROOM_PHOTO",entityType:"room",entityId:room.id,field:"attachments",severity:"error",messageKey:"room_scan.completeness.missing_room_photo"});}
 for(const opening of openings.rows)if(!(opening.widthM>0&&opening.heightM>0)||!surfaces.rows.some(x=>x.id===opening.surfaceId&&x.roomId===opening.roomId))issues.push({code:"INVALID_OPENING",entityType:"opening",entityId:opening.id,field:"dimensions",severity:"error",messageKey:"room_scan.completeness.invalid_opening"});for(const [entityType,rows,status]of[["measurement",measurements.rows,"verificationStatus"],["surface",surfaces.rows,"reviewStatus"],["opening",openings.rows,"verificationStatus"],["observation",observations.rows,"reviewStatus"]]as const)for(const fact of rows)if(!["verified","confirmed","rejected"].includes(fact[status]))issues.push({code:"REVIEW_REQUIRED",entityType,entityId:fact.id,field:"status",severity:"error",messageKey:"room_scan.completeness.review_required"});
 if(!scan.projectId)issues.splice(0,issues.length,...issues.filter(x=>x.code==="REVIEW_REQUIRED"));return{scan,rooms:rooms.rows,surfaces:surfaces.rows,measurements:measurements.rows,openings:openings.rows,observations:observations.rows,attachments:attachments.rows,quantities:quantities.rows,reviews:reviews.rows,history:history.rows,snapshots:snapshots.rows,completeness:{status:issues.length?"incomplete":"complete",issues}};});}
 override async submit(actor:RoomScanActor,scanId:string,scanVersion:number){const workspace=await this.workspace(actor,scanId);if(workspace.scan.projectId&&workspace.completeness.issues.length)throw domainErrors.validation("Room Scan has unresolved commercial approval blockers",{issues:workspace.completeness.issues});return super.submit(actor,scanId,scanVersion);}
 override async approve(actor:RoomScanActor,scanId:string,scanVersion:number){const workspace=await this.workspace(actor,scanId);if(workspace.scan.projectId&&workspace.completeness.issues.length)throw domainErrors.validation("Room Scan has unresolved commercial approval blockers",{issues:workspace.completeness.issues});return super.approve(actor,scanId,scanVersion);}
 override async complete(actor:RoomScanActor,scanId:string,scanVersion:number){const workspace=await this.workspace(actor,scanId),structural=workspace.completeness.issues.filter((x:any)=>x.code!=="REVIEW_REQUIRED");if(structural.length)throw domainErrors.validation("Room Scan capture is incomplete",{issues:structural});const idempotencyKey=`calculate-v${scanVersion}`,requestId=await this.unit.transaction(actor.tenantId,async db=>{const existing=(await db.query<{id:string}>("SELECT id FROM room_scan_processing_requests WHERE tenant_id=$1 AND scan_id=$2 AND idempotency_key=$3",[actor.tenantId,scanId,idempotencyKey])).rows[0];if(existing)return existing.id;const id=randomUUID();await db.query("INSERT INTO room_scan_processing_requests(id,tenant_id,scan_id,scan_version,idempotency_key,requested_by)VALUES($1,$2,$3,$4,$5,$6)",[id,actor.tenantId,scanId,scanVersion,idempotencyKey,actor.id]);await this.unit.audit(db,actor,"room_scan.calculation_requested",scanId,{requestId:id,scanVersion});return id;});
  await this.unit.transaction(actor.tenantId,async db=>{await db.query("UPDATE room_scan_processing_requests SET status='processing',started_at=now(),attempt_count=attempt_count+1,version=version+1 WHERE tenant_id=$1 AND id=$2 AND status='queued'",[actor.tenantId,requestId]);});
  try{const output=await super.complete(actor,scanId,scanVersion);const processing=await this.unit.transaction(actor.tenantId,async db=>{const updated=(await db.query<{requestedAt:Date;startedAt:Date;completedAt:Date;attemptCount:number}>("UPDATE room_scan_processing_requests r SET status='completed',completed_at=now(),result=$1,version=version+1 WHERE r.tenant_id=$2 AND r.id=$3 AND r.status='processing' AND EXISTS(SELECT 1 FROM room_scan_sessions s WHERE s.tenant_id=r.tenant_id AND s.id=r.scan_id AND s.version=r.scan_version+2) RETURNING requested_at AS \"requestedAt\",started_at AS \"startedAt\",completed_at AS \"completedAt\",attempt_count AS \"attemptCount\"",[JSON.stringify({quantityCalculationVersion:"room-geometry-v1"}),actor.tenantId,requestId])).rows[0];if(!updated)throw new DomainError("ROOM_SCAN_PROCESSING_STALE",409,"Processing result is stale");await this.unit.audit(db,actor,"room_scan.calculation_completed",scanId,{requestId,scanVersion});return{requestId,scanId,scanVersion,status:"completed",...updated}as ProcessingResult;});return{...output,processing};}
  catch(error){await this.unit.transaction(actor.tenantId,async db=>{await db.query("UPDATE room_scan_processing_requests SET status='failed',failed_at=now(),failure_code=$1,version=version+1 WHERE tenant_id=$2 AND id=$3 AND status='processing'",[error instanceof DomainError?error.code:"CALCULATION_FAILED",actor.tenantId,requestId]);await this.unit.audit(db,actor,"room_scan.calculation_failed",scanId,{requestId,scanVersion,failureCode:error instanceof DomainError?error.code:"CALCULATION_FAILED"});});throw error;}
 }
}
