import{randomUUID}from"node:crypto";
import{DomainError,domainErrors}from"../../domain/errors.js";
import type{RoomScanActor}from"../../authorization/room-scanner-policy.js";
import type{AddOpeningCommand,AddRoomCommand,AddSurfaceCommand,AssociateAttachmentCommand,CreateRoomScanCommand,ProcessingResult,RemoveAttachmentCommand}from"../../application/room-scanner/room-scan-commands.js";
import{RoomScanService as PostgresRoomScanStore}from"./postgres-room-scan-store.js";
import type{RoomScanRepositoryPort}from"./room-scan-unit-of-work.js";

/** Adds Phase 0 integrity behavior around the legacy-compatible PostgreSQL store. */
export class PostgresRoomScanPersistence extends PostgresRoomScanStore{
 constructor(private readonly unit:RoomScanRepositoryPort){super(unit);}
 override async create(actor:RoomScanActor,input:CreateRoomScanCommand){
  if(input.projectId){const valid=await this.unit.transaction(actor.tenantId,async db=>(await db.query("SELECT 1 FROM projects WHERE tenant_id=$1 AND id=$2 AND property_id=$3 AND deleted_at IS NULL",[actor.tenantId,input.projectId,input.propertyId])).rowCount===1);if(!valid)throw new DomainError("ROOM_SCAN_PROJECT_PROPERTY_MISMATCH",422,"Project does not belong to the selected property");}
  return super.create(actor,input);
 }
 private async editable(db:import("pg").PoolClient,actor:RoomScanActor,scanId:string,expectedVersion:number){const scan=(await db.query<{version:number;status:string}>("SELECT version::int,status FROM room_scan_sessions WHERE tenant_id=$1 AND id=$2 FOR UPDATE",[actor.tenantId,scanId])).rows[0];if(!scan)throw domainErrors.notFound();if(scan.version!==expectedVersion)throw domainErrors.conflict();if(!["capturing","review_required"].includes(scan.status))throw domainErrors.transition();return scan;}
 private async bumpScan(db:import("pg").PoolClient,actor:RoomScanActor,scanId:string,expectedVersion:number){if(!(await db.query("UPDATE room_scan_sessions SET version=version+1,updated_at=now(),updated_by=$1 WHERE tenant_id=$2 AND id=$3 AND version=$4",[actor.id,actor.tenantId,scanId,expectedVersion])).rowCount)throw domainErrors.conflict();}
override async addRoom(actor:RoomScanActor,scanId:string,input:AddRoomCommand){return this.unit.transaction(actor.tenantId,async db=>{await this.editable(db,actor,scanId,input.expectedVersion);const id=randomUUID();await db.query("INSERT INTO room_scan_rooms(id,tenant_id,scan_id,name,room_type,floor_number,created_by,updated_by)VALUES($1,$2,$3,$4,$5,$6,$7,$7)",[id,actor.tenantId,scanId,input.name,input.roomType,input.floorNumber??null,actor.id]);await this.bumpScan(db,actor,scanId,input.expectedVersion);await this.unit.audit(db,actor,"room_scan.room_added",scanId,{roomId:id});return{id};});}
 override async addSurface(actor:RoomScanActor,scanId:string,input:AddSurfaceCommand){return this.unit.transaction(actor.tenantId,async db=>{await this.editable(db,actor,scanId,input.expectedVersion);if(!(await db.query("SELECT 1 FROM room_scan_rooms WHERE tenant_id=$1 AND scan_id=$2 AND id=$3",[actor.tenantId,scanId,input.roomId])).rowCount)throw new DomainError("ROOM_SCAN_ENTITY_ASSOCIATION_INVALID",422,"Room does not belong to the scan");const id=randomUUID();await db.query("INSERT INTO room_scan_surfaces(id,tenant_id,scan_id,room_id,surface_type,label,polygon,orientation,confidence,created_by,updated_by)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$10)",[id,actor.tenantId,scanId,input.roomId,input.surfaceType,input.label,JSON.stringify(input.polygon),input.orientation??null,input.confidence??null,actor.id]);await this.bumpScan(db,actor,scanId,input.expectedVersion);await this.unit.audit(db,actor,"room_scan.surface_added",scanId,{surfaceId:id,roomId:input.roomId});return{id};});}
 override async addOpening(actor:RoomScanActor,scanId:string,input:AddOpeningCommand){return this.unit.transaction(actor.tenantId,async db=>{await this.editable(db,actor,scanId,input.expectedVersion);if(!(await db.query("SELECT 1 FROM room_scan_surfaces WHERE tenant_id=$1 AND scan_id=$2 AND room_id=$3 AND id=$4",[actor.tenantId,scanId,input.roomId,input.surfaceId])).rowCount)throw new DomainError("ROOM_SCAN_ENTITY_ASSOCIATION_INVALID",422,"Surface does not belong to the room and scan");const id=randomUUID();await db.query("INSERT INTO room_scan_openings(id,tenant_id,scan_id,room_id,surface_id,opening_type,width_m,height_m,sill_height_m,reveal_depth_m,source,verification_status,created_by,updated_by)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$13)",[id,actor.tenantId,scanId,input.roomId,input.surfaceId,input.openingType,input.widthM,input.heightM,input.sillHeightM??null,input.revealDepthM??null,input.source,input.source==="human_correction"?"verified":"requires_review",actor.id]);await this.bumpScan(db,actor,scanId,input.expectedVersion);await this.unit.audit(db,actor,"room_scan.opening_added",scanId,{openingId:id,roomId:input.roomId,surfaceId:input.surfaceId});return{id};});}
 async associateAttachment(actor:RoomScanActor,scanId:string,input:AssociateAttachmentCommand){
  return this.unit.transaction(actor.tenantId,async db=>{const scan=(await db.query<{version:number;propertyId:string;projectId:string|null}>("SELECT version::int,property_id AS \"propertyId\",project_id AS \"projectId\" FROM room_scan_sessions WHERE tenant_id=$1 AND id=$2 FOR UPDATE",[actor.tenantId,scanId])).rows[0];if(!scan)throw domainErrors.notFound();if(scan.version!==input.expectedVersion)throw domainErrors.conflict();
   if(input.roomId&&!(await db.query("SELECT 1 FROM room_scan_rooms WHERE tenant_id=$1 AND scan_id=$2 AND id=$3",[actor.tenantId,scanId,input.roomId])).rowCount)throw new DomainError("ROOM_SCAN_ENTITY_ASSOCIATION_INVALID",422,"Room does not belong to the scan");
   const file=(await db.query<{status:string;projectOk:boolean}>(`SELECT f.status,EXISTS(SELECT 1 FROM document_versions v JOIN documents d ON d.tenant_id=v.tenant_id AND d.id=v.document_id JOIN document_links l ON l.tenant_id=d.tenant_id AND l.document_id=d.id WHERE v.tenant_id=f.tenant_id AND v.file_object_id=f.id AND((l.entity_type='project'AND l.entity_id=$3)OR(l.entity_type='property'AND l.entity_id=$4)))AS "projectOk" FROM file_objects f WHERE f.tenant_id=$1 AND f.id=$2`,[actor.tenantId,input.fileObjectId,scan.projectId,scan.propertyId])).rows[0];
   if(!file||file.status!=="available"||!file.projectOk)throw new DomainError("ROOM_SCAN_ATTACHMENT_INVALID",422,"File is not owned by the scan project or property");
   const id=randomUUID();try{await db.query("INSERT INTO room_scan_attachments(id,tenant_id,scan_id,room_id,file_object_id,purpose,associated_by)VALUES($1,$2,$3,$4,$5,$6,$7)",[id,actor.tenantId,scanId,input.roomId??null,input.fileObjectId,input.purpose,actor.id]);}catch(error){if(error instanceof Error&&/unique|duplicate/i.test(error.message))throw new DomainError("ROOM_SCAN_ATTACHMENT_INVALID",422,"File is already attached to a scan");throw error;}
   await db.query("UPDATE room_scan_sessions SET version=version+1,updated_at=now(),updated_by=$1 WHERE tenant_id=$2 AND id=$3 AND version=$4",[actor.id,actor.tenantId,scanId,input.expectedVersion]);await this.unit.audit(db,actor,"room_scan.attachment_associated",scanId,{attachmentId:id,fileObjectId:input.fileObjectId,roomId:input.roomId??null,purpose:input.purpose});return{id};});
 }
 async removeAttachment(actor:RoomScanActor,scanId:string,attachmentId:string,input:RemoveAttachmentCommand){return this.unit.transaction(actor.tenantId,async db=>{const scan=(await db.query<{version:number}>("SELECT version::int FROM room_scan_sessions WHERE tenant_id=$1 AND id=$2 FOR UPDATE",[actor.tenantId,scanId])).rows[0];if(!scan)throw domainErrors.notFound();if(scan.version!==input.expectedVersion)throw domainErrors.conflict();const row=await db.query("UPDATE room_scan_attachments SET removed_at=now(),removed_by=$1,version=version+1 WHERE tenant_id=$2 AND scan_id=$3 AND id=$4 AND removed_at IS NULL RETURNING file_object_id",[actor.id,actor.tenantId,scanId,attachmentId]);if(!row.rowCount)throw domainErrors.notFound();await db.query("UPDATE room_scan_sessions SET version=version+1,updated_at=now(),updated_by=$1 WHERE tenant_id=$2 AND id=$3 AND version=$4",[actor.id,actor.tenantId,scanId,input.expectedVersion]);await this.unit.audit(db,actor,"room_scan.attachment_removed",scanId,{attachmentId});return{id:attachmentId};});}
 override async complete(actor:RoomScanActor,scanId:string,scanVersion:number){const idempotencyKey=`calculate-v${scanVersion}`,requestId=await this.unit.transaction(actor.tenantId,async db=>{const existing=(await db.query<{id:string}>("SELECT id FROM room_scan_processing_requests WHERE tenant_id=$1 AND scan_id=$2 AND idempotency_key=$3",[actor.tenantId,scanId,idempotencyKey])).rows[0];if(existing)return existing.id;const id=randomUUID();await db.query("INSERT INTO room_scan_processing_requests(id,tenant_id,scan_id,scan_version,idempotency_key,requested_by)VALUES($1,$2,$3,$4,$5,$6)",[id,actor.tenantId,scanId,scanVersion,idempotencyKey,actor.id]);await this.unit.audit(db,actor,"room_scan.calculation_requested",scanId,{requestId:id,scanVersion});return id;});
  await this.unit.transaction(actor.tenantId,async db=>{await db.query("UPDATE room_scan_processing_requests SET status='processing',started_at=now(),attempt_count=attempt_count+1,version=version+1 WHERE tenant_id=$1 AND id=$2 AND status='queued'",[actor.tenantId,requestId]);});
  try{const output=await super.complete(actor,scanId,scanVersion);const processing=await this.unit.transaction(actor.tenantId,async db=>{const updated=(await db.query<{requestedAt:Date;startedAt:Date;completedAt:Date;attemptCount:number}>("UPDATE room_scan_processing_requests r SET status='completed',completed_at=now(),result=$1,version=version+1 WHERE r.tenant_id=$2 AND r.id=$3 AND r.status='processing' AND EXISTS(SELECT 1 FROM room_scan_sessions s WHERE s.tenant_id=r.tenant_id AND s.id=r.scan_id AND s.version=r.scan_version+2) RETURNING requested_at AS \"requestedAt\",started_at AS \"startedAt\",completed_at AS \"completedAt\",attempt_count AS \"attemptCount\"",[JSON.stringify({quantityCalculationVersion:"room-geometry-v1"}),actor.tenantId,requestId])).rows[0];if(!updated)throw new DomainError("ROOM_SCAN_PROCESSING_STALE",409,"Processing result is stale");await this.unit.audit(db,actor,"room_scan.calculation_completed",scanId,{requestId,scanVersion});return{requestId,scanId,scanVersion,status:"completed",...updated}as ProcessingResult;});return{...output,processing};}
  catch(error){await this.unit.transaction(actor.tenantId,async db=>{await db.query("UPDATE room_scan_processing_requests SET status='failed',failed_at=now(),failure_code=$1,version=version+1 WHERE tenant_id=$2 AND id=$3 AND status='processing'",[error instanceof DomainError?error.code:"CALCULATION_FAILED",actor.tenantId,requestId]);await this.unit.audit(db,actor,"room_scan.calculation_failed",scanId,{requestId,scanVersion,failureCode:error instanceof DomainError?error.code:"CALCULATION_FAILED"});});throw error;}
 }
}
