import type {PoolClient} from "pg";
import type {ExpenseContract,InvoiceContract,PaymentContract} from "@odls/contracts";
export const invoiceSelect=`i.id,i.tenant_id AS "tenantId",i.client_id AS "clientId",i.project_id AS "projectId",i.invoice_number AS "invoiceNumber",i.status,i.currency_code AS "currencyCode",i.issue_date::text AS "issueDate",i.due_date::text AS "dueDate",i.net_amount::text AS "netAmount",i.vat_rate::text AS "vatRate",i.vat_amount::text AS "vatAmount",i.gross_amount::text AS "grossAmount",i.paid_amount::text AS "paidAmount",(i.gross_amount-i.paid_amount)::text AS "outstandingAmount",i.notes,i.version::int,i.created_at AS "createdAt",i.updated_at AS "updatedAt",i.deleted_at AS "archivedAt"`;
export const paymentSelect=`p.id,p.tenant_id AS "tenantId",p.client_id AS "clientId",p.reference,p.status,p.currency_code AS "currencyCode",p.amount::text,p.payment_date::text AS "paymentDate",COALESCE(sum(a.amount),0)::text AS "allocatedAmount",(p.amount-COALESCE(sum(a.amount),0))::text AS "unallocatedAmount",p.version::int,p.created_at AS "createdAt",p.updated_at AS "updatedAt",p.deleted_at AS "archivedAt"`;
export const expenseSelect=`e.id,e.tenant_id AS "tenantId",e.project_id AS "projectId",e.supplier,e.category,e.expense_date::text AS "expenseDate",e.status,e.currency_code AS "currencyCode",e.net_amount::text AS "netAmount",e.vat_rate::text AS "vatRate",e.vat_amount::text AS "vatAmount",e.gross_amount::text AS "grossAmount",e.notes,e.version::int,e.created_at AS "createdAt",e.updated_at AS "updatedAt",e.deleted_at AS "archivedAt"`;
export class FinanceRepository{
  invoice(db:PoolClient,t:string,id:string){return db.query<InvoiceContract>(`SELECT ${invoiceSelect} FROM invoices i WHERE i.id=$1 AND i.tenant_id=$2`,[id,t]).then(r=>r.rows[0]);}
  payment(db:PoolClient,t:string,id:string){return db.query<PaymentContract>(`SELECT ${paymentSelect} FROM payments p LEFT JOIN payment_allocations a ON a.payment_id=p.id WHERE p.id=$1 AND p.tenant_id=$2 GROUP BY p.id`,[id,t]).then(r=>r.rows[0]);}
  expense(db:PoolClient,t:string,id:string){return db.query<ExpenseContract>(`SELECT ${expenseSelect} FROM expenses e WHERE e.id=$1 AND e.tenant_id=$2`,[id,t]).then(r=>r.rows[0]);}
  relationship(db:PoolClient,t:string,clientId:string,projectId?:string|null){return db.query<{clientId:string;clientArchived:boolean;projectId:string|null;projectArchived:boolean;currencyCode:string|null}>(`SELECT c.id AS "clientId",(c.deleted_at IS NOT NULL OR c.status='archived') AS "clientArchived",p.id AS "projectId",(p.deleted_at IS NOT NULL OR p.status='archived') AS "projectArchived",p.currency_code AS "currencyCode" FROM clients c LEFT JOIN projects p ON p.id=$3 AND p.tenant_id=c.tenant_id AND p.client_id=c.id WHERE c.id=$2 AND c.tenant_id=$1`,[t,clientId,projectId??null]).then(r=>r.rows[0]);}
  project(db:PoolClient,t:string,id:string){return db.query<{id:string;currencyCode:string;budget:string|null;archived:boolean}>(`SELECT id,currency_code AS "currencyCode",approved_budget::text AS budget,(deleted_at IS NOT NULL OR status='archived') AS archived FROM projects WHERE tenant_id=$1 AND id=$2`,[t,id]).then(r=>r.rows[0]);}
  audit(db:PoolClient,a:{tenantId:string;id:string;correlationId:string},action:string,type:string,id:string,metadata:Record<string,unknown>={}){return db.query("INSERT INTO audit_logs(tenant_id,actor_id,action,entity_type,entity_id,correlation_id,metadata) VALUES($1,$2,$3,$4,$5,CASE WHEN $6 ~ '^[0-9a-f-]{36}$' THEN $6::uuid ELSE gen_random_uuid() END,$7)",[a.tenantId,a.id,action,type,id,a.correlationId,metadata]);}
}
