import type { PoolClient } from "pg";
import type { Client, ClientListQuery, ClientListResult, CreateClientCommand, UpdateClientCommand } from "../../domain/client/client-types.js";
const select="id,tenant_id AS \"tenantId\",client_type AS \"clientType\",name,legal_name AS \"legalName\",tax_id AS \"taxId\",email,phone,status,notes,version::int,created_at AS \"createdAt\",updated_at AS \"updatedAt\",deleted_at AS \"archivedAt\"";
const sortColumns={name:"name",status:"status",clientType:"client_type",createdAt:"created_at",updatedAt:"updated_at"} as const;
export class ClientRepository {
  async findById(db:PoolClient,tenantId:string,id:string):Promise<Client|undefined>{return (await db.query<Client>(`SELECT ${select} FROM clients WHERE id=$1 AND tenant_id=$2`,[id,tenantId])).rows[0];}
  async findDuplicateTaxId(db:PoolClient,tenantId:string,taxId:string,id?:string){return (await db.query("SELECT id FROM clients WHERE tenant_id=$1 AND lower(tax_id)=lower($2) AND deleted_at IS NULL AND ($3::uuid IS NULL OR id<>$3)",[tenantId,taxId,id??null])).rows[0];}
  async create(db:PoolClient,tenantId:string,actorId:string,id:string,input:CreateClientCommand):Promise<Client>{const r=await db.query<Client>(`INSERT INTO clients(id,tenant_id,client_type,name,legal_name,tax_id,email,phone,notes,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$10) RETURNING ${select}`,[id,tenantId,input.clientType??"company",input.name,input.legalName??null,input.taxId??null,input.email??null,input.phone??null,input.notes??null,actorId]);return r.rows[0];}
  async list(db:PoolClient,tenantId:string,q:ClientListQuery):Promise<ClientListResult>{const values:any[]=[tenantId];const filters=["tenant_id=$1"];
    if(q.search){values.push(`%${q.search}%`);filters.push(`(name ILIKE $${values.length} OR legal_name ILIKE $${values.length} OR email ILIKE $${values.length})`);}
    if(q.status){values.push(q.status);filters.push(`status=$${values.length}`);}if(q.clientType){values.push(q.clientType);filters.push(`client_type=$${values.length}`);}
    const where=filters.join(" AND ");const total=Number((await db.query<{count:string}>(`SELECT count(*) FROM clients WHERE ${where}`,values)).rows[0].count);values.push(q.pageSize,(q.page-1)*q.pageSize);
    const items=(await db.query<Client>(`SELECT ${select} FROM clients WHERE ${where} ORDER BY ${sortColumns[q.sortBy]} ${q.sortOrder==="asc"?"ASC":"DESC"} LIMIT $${values.length-1} OFFSET $${values.length}`,values)).rows;
    return {items,pagination:{page:q.page,pageSize:q.pageSize,total,totalPages:Math.ceil(total/q.pageSize)}};}
  async update(db:PoolClient,tenantId:string,actorId:string,id:string,input:UpdateClientCommand):Promise<Client|undefined>{const fields:{key:keyof UpdateClientCommand;column:string}[]=[{key:"clientType",column:"client_type"},{key:"name",column:"name"},{key:"legalName",column:"legal_name"},{key:"taxId",column:"tax_id"},{key:"email",column:"email"},{key:"phone",column:"phone"},{key:"status",column:"status"},{key:"notes",column:"notes"}];const set: string[]=[];const values:any[]=[];for(const f of fields)if(input[f.key]!==undefined){values.push(input[f.key]);set.push(`${f.column}=$${values.length}`);}if(!set.length)return this.findById(db,tenantId,id);values.push(actorId,id,tenantId,input.expectedVersion);const r=await db.query<Client>(`UPDATE clients SET ${set.join(",")},updated_by=$${values.length-3},updated_at=now(),version=version+1 WHERE id=$${values.length-2} AND tenant_id=$${values.length-1} AND version=$${values.length} RETURNING ${select}`,values);return r.rows[0];}
  async archive(db:PoolClient,tenantId:string,actorId:string,id:string,version:number):Promise<Client|undefined>{return (await db.query<Client>(`UPDATE clients SET status='archived',deleted_at=now(),deleted_by=$1,updated_by=$1,updated_at=now(),version=version+1 WHERE id=$2 AND tenant_id=$3 AND version=$4 AND deleted_at IS NULL RETURNING ${select}`,[actorId,id,tenantId,version])).rows[0];}
}
