import type{RoomScanActor}from"../../authorization/room-scanner-policy.js";
import type{AddMeasurementCommand,AddObservationCommand,AddOpeningCommand,AddRoomCommand,AddSurfaceCommand,AssociateAttachmentCommand,CreateRoomScanCommand,IdResult,ProcessingResult,RemoveAttachmentCommand,ReviewFactCommand,RoomScanListQuery,RoomScanListResult,RoomScanRecord,SnapshotResult}from"./room-scan-commands.js";
export interface RoomScanPersistencePort{
 create(a:RoomScanActor,input:CreateRoomScanCommand):Promise<RoomScanRecord>;get(a:RoomScanActor,id:string):Promise<RoomScanRecord>;list(a:RoomScanActor,q:RoomScanListQuery):Promise<RoomScanListResult>;
 start(a:RoomScanActor,id:string,v:number):Promise<RoomScanRecord>;submit(a:RoomScanActor,id:string,v:number):Promise<RoomScanRecord>;reject(a:RoomScanActor,id:string,v:number):Promise<RoomScanRecord>;cancel(a:RoomScanActor,id:string,v:number):Promise<RoomScanRecord>;
 addRoom(a:RoomScanActor,id:string,input:AddRoomCommand):Promise<IdResult>;addSurface(a:RoomScanActor,id:string,input:AddSurfaceCommand):Promise<IdResult>;addMeasurement(a:RoomScanActor,id:string,input:AddMeasurementCommand):Promise<IdResult>;addOpening(a:RoomScanActor,id:string,input:AddOpeningCommand):Promise<IdResult>;addObservation(a:RoomScanActor,id:string,input:AddObservationCommand):Promise<IdResult>;
 reviewEntity(a:RoomScanActor,id:string,input:ReviewFactCommand):Promise<RoomScanRecord>;complete(a:RoomScanActor,id:string,v:number):Promise<{scan:RoomScanRecord;completeness:Record<string,unknown>;processing?:ProcessingResult}>;quantities(a:RoomScanActor,id:string):Promise<unknown[]>;approve(a:RoomScanActor,id:string,v:number):Promise<SnapshotResult>;snapshot(a:RoomScanActor,id:string):Promise<SnapshotResult>;
 associateAttachment(a:RoomScanActor,id:string,input:AssociateAttachmentCommand):Promise<IdResult>;removeAttachment(a:RoomScanActor,id:string,attachmentId:string,input:RemoveAttachmentCommand):Promise<IdResult>;
}
