import {randomUUID} from "node:crypto";
import {assertCanActivateLaborRate,assertCanCreateLaborRate,assertCanDeactivateLaborRate,assertCanManageSystemLaborRates,assertCanReadLaborRates,assertCanReadSystemLaborRates,assertCanUpdateLaborRate} from "../../authorization/labor-rate-policy.js";
import {domainErrors} from "../../domain/errors.js";
import {assertNoActivePeriodOverlap,assertSourceTypeAllowed,validateActivateLaborRate,validateDeactivateLaborRate,validateLaborRateCreate,validateLaborRateUpdate} from "../../domain/labor-rate-catalog/labor-rate-rules.js";
import type {ActivateLaborRate,CreateLaborRate,CreateSystemLaborRate,DeactivateLaborRate,LaborRate,LaborRateQuery,LaborRateResolutionParams,UpdateLaborRate} from "../../domain/labor-rate-catalog/labor-rate-types.js";
import type {LaborRateCatalogRepository,LaborRateOverlapCandidate} from "./labor-rate-catalog-repository.js";
import {ResolveLaborRateService} from "./resolve-labor-rate-service.js";

export type LaborRateActor={id:string;tenantId:string;permissions:readonly string[];correlationId:string;systemContextAllowed?:boolean};
export class LaborRateCatalogService{
 constructor(private repository:LaborRateCatalogRepository){}
 private correlationId(value:string){return /^[0-9a-f-]{36}$/i.test(value)?value:randomUUID();}
 private candidate(rate:Pick<LaborRate,"tenantId"|"workId"|"countryCode"|"region"|"currency"|"unitId"|"sourceType"|"effectiveFrom"|"effectiveTo"|"isActive">):LaborRateOverlapCandidate{return rate;}
 private async assertNoOverlap(repository:LaborRateCatalogRepository,tenantId:string,candidate:LaborRateOverlapCandidate,excludeId?:string){for(const existing of await repository.findOverlapping(tenantId,candidate,excludeId))assertNoActivePeriodOverlap(candidate,existing);}
 private audit(repository:LaborRateCatalogRepository,actor:LaborRateActor,action:string,rate:LaborRate,metadata:Record<string,unknown>){return repository.audit({tenantId:actor.tenantId,actorId:actor.id,action,entityType:"labor_rate",entityId:rate.id,correlationId:this.correlationId(actor.correlationId),metadata});}
 private assertMutationContext(actor:LaborRateActor,sourceType:LaborRate["sourceType"]){assertSourceTypeAllowed(sourceType,actor.systemContextAllowed===true);if(actor.systemContextAllowed===true&&sourceType!=="system_default")throw domainErrors.forbidden();}
 async systemActor(actor:LaborRateActor,manage=false){manage?assertCanManageSystemLaborRates(actor):assertCanReadSystemLaborRates(actor);if(!await this.repository.transaction(actor.tenantId,r=>r.isSystemActor(actor.id)))throw domainErrors.forbidden();return {...actor,systemContextAllowed:true};}
 list(actor:LaborRateActor,query:LaborRateQuery,systemOnly=false){systemOnly?assertCanReadSystemLaborRates(actor):assertCanReadLaborRates(actor);return this.repository.transaction(actor.tenantId,r=>r.list(actor.tenantId,query,systemOnly),systemOnly);}
 get(actor:LaborRateActor,id:string){actor.systemContextAllowed?assertCanReadSystemLaborRates(actor):assertCanReadLaborRates(actor);return this.repository.transaction(actor.tenantId,async r=>{const rate=await r.findById(actor.tenantId,id);if(!rate||(actor.systemContextAllowed&&rate.sourceType!=="system_default"))throw domainErrors.notFound();return rate;},actor.systemContextAllowed===true);}
 resolve(actor:LaborRateActor,input:Omit<LaborRateResolutionParams,"tenantId">){assertCanReadLaborRates(actor);return new ResolveLaborRateService(this.repository).resolve({...input,tenantId:actor.tenantId});}
 async createSystemDefault(actor:LaborRateActor,input:CreateSystemLaborRate){const systemActor=await this.systemActor(actor,true);const ids=await this.repository.transaction(actor.tenantId,r=>r.resolveCatalogCodes(actor.tenantId,input.workCode,input.unitCode));if(!ids)throw domainErrors.notFound();return this.create(systemActor,{...input,...ids,sourceType:"system_default"});}
 create(actor:LaborRateActor,input:CreateLaborRate){actor.systemContextAllowed?assertCanManageSystemLaborRates(actor):assertCanCreateLaborRate(actor);const value=validateLaborRateCreate(input,actor.systemContextAllowed===true);this.assertMutationContext(actor,value.sourceType);return this.repository.transaction(actor.tenantId,async repository=>{const candidate:LaborRateOverlapCandidate={tenantId:actor.tenantId,workId:value.workId,countryCode:value.countryCode,region:value.region??null,currency:value.currency,unitId:value.unitId,sourceType:value.sourceType,effectiveFrom:value.effectiveFrom,effectiveTo:value.effectiveTo??null,isActive:true};await this.assertNoOverlap(repository,actor.tenantId,candidate);const created=await repository.create(actor.tenantId,actor.id,randomUUID(),value);await this.audit(repository,actor,"labor_rate.created",created,{newVersion:created.version,workId:created.workId,sourceType:created.sourceType,systemContext:actor.systemContextAllowed===true});return created;},actor.systemContextAllowed===true);}
 update(actor:LaborRateActor,id:string,input:UpdateLaborRate){actor.systemContextAllowed?assertCanManageSystemLaborRates(actor):assertCanUpdateLaborRate(actor);return this.repository.transaction(actor.tenantId,async repository=>{const current=await repository.findById(actor.tenantId,id);if(!current)throw domainErrors.notFound();this.assertMutationContext(actor,current.sourceType);const value=validateLaborRateUpdate(input,current,actor.systemContextAllowed===true);if(value.sourceType!==undefined&&value.sourceType!==current.sourceType)throw domainErrors.validation("sourceType cannot be changed",{kind:"SOURCE_TYPE_IMMUTABLE"});if(current.version!==value.expectedVersion)throw domainErrors.conflict();const candidate:LaborRateOverlapCandidate={tenantId:current.tenantId,workId:value.workId??current.workId,countryCode:value.countryCode??current.countryCode,region:value.region===undefined?current.region:value.region,currency:value.currency??current.currency,unitId:value.unitId??current.unitId,sourceType:current.sourceType,effectiveFrom:value.effectiveFrom??current.effectiveFrom,effectiveTo:value.effectiveTo===undefined?current.effectiveTo:value.effectiveTo,isActive:current.isActive};if(candidate.isActive)await this.assertNoOverlap(repository,actor.tenantId,candidate,id);const updated=await repository.update(actor.tenantId,actor.id,id,{...value,sourceType:current.sourceType});if(!updated)throw domainErrors.conflict();await this.audit(repository,actor,"labor_rate.updated",updated,{previousVersion:current.version,newVersion:updated.version,changes:value,systemContext:actor.systemContextAllowed===true});return updated;},actor.systemContextAllowed===true);}
 activate(actor:LaborRateActor,id:string,input:ActivateLaborRate){actor.systemContextAllowed?assertCanManageSystemLaborRates(actor):assertCanActivateLaborRate(actor);const value=validateActivateLaborRate(input);return this.repository.transaction(actor.tenantId,async repository=>{const current=await repository.findById(actor.tenantId,id);if(!current)throw domainErrors.notFound();this.assertMutationContext(actor,current.sourceType);if(current.version!==value.expectedVersion)throw domainErrors.conflict();if(current.isActive)throw domainErrors.transition();const candidate={...this.candidate(current),isActive:true};await this.assertNoOverlap(repository,actor.tenantId,candidate,id);const activated=await repository.setActive(actor.tenantId,actor.id,id,true,value.expectedVersion,current.sourceType);if(!activated)throw domainErrors.conflict();await this.audit(repository,actor,"labor_rate.activated",activated,{previousVersion:current.version,newVersion:activated.version,systemContext:actor.systemContextAllowed===true});return activated;},actor.systemContextAllowed===true);}
 deactivate(actor:LaborRateActor,id:string,input:DeactivateLaborRate){actor.systemContextAllowed?assertCanManageSystemLaborRates(actor):assertCanDeactivateLaborRate(actor);const value=validateDeactivateLaborRate(input);return this.repository.transaction(actor.tenantId,async repository=>{const current=await repository.findById(actor.tenantId,id);if(!current)throw domainErrors.notFound();this.assertMutationContext(actor,current.sourceType);if(current.version!==value.expectedVersion)throw domainErrors.conflict();if(!current.isActive)throw domainErrors.transition();const deactivated=await repository.setActive(actor.tenantId,actor.id,id,false,value.expectedVersion,current.sourceType);if(!deactivated)throw domainErrors.conflict();await this.audit(repository,actor,"labor_rate.deactivated",deactivated,{previousVersion:current.version,newVersion:deactivated.version,systemContext:actor.systemContextAllowed===true});return deactivated;},actor.systemContextAllowed===true);}
}
