import type {Pool,PoolClient} from "pg";import {randomUUID} from "node:crypto";import type{DocumentAnalysisRepositoryPort}from"../../application/document-analysis/document-analysis-repository.js";import {enqueueDomainEvent} from "../notification/outbox.js";import{inTenantTransaction}from"../transaction.js";
export class DocumentAnalysisRepository implements DocumentAnalysisRepositoryPort{constructor(private pool:Pool){}
 transaction<T>(tenantId:string,work:(db:PoolClient)=>Promise<T>){return inTenantTransaction(this.pool,tenantId,work);}
 async document(db:PoolClient,tenantId:string,id:string){return (await db.query<any>("SELECT id FROM documents WHERE tenant_id=$1 AND id=$2 AND deleted_at IS NULL",[tenantId,id])).rows[0];}
 async pageCount(db:PoolClient,tenantId:string,documentId:string){return Number((await db.query<{count:string}>("SELECT count(*) FROM document_pages WHERE tenant_id=$1 AND document_id=$2",[tenantId,documentId])).rows[0].count);}
 async pages(db:PoolClient,tenantId:string,documentId:string,asOf?:Date|string){return (await db.query<any>(`SELECT DISTINCT ON(p.id) p.id "pageId",p.page_number "pageNumber",r.id "ocrResultId",r.normalized_text text,r.detected_language language FROM document_pages p JOIN ocr_results r ON r.tenant_id=p.tenant_id AND r.document_page_id=p.id JOIN ocr_jobs j ON j.tenant_id=r.tenant_id AND j.id=r.ocr_job_id AND j.status='completed' WHERE p.tenant_id=$1 AND p.document_id=$2 AND($3::timestamptz IS NULL OR r.created_at<=$3) ORDER BY p.id,r.created_at DESC`,[tenantId,documentId,asOf??null])).rows.sort((a,b)=>Number(a.pageNumber)-Number(b.pageNumber));}
 async job(db:PoolClient,t:string,id:string){return (await db.query<any>(`SELECT id,tenant_id "tenantId",document_id "documentId",ocr_result_id "ocrResultId",status,classifier,classifier_version "classifierVersion",attempts,max_attempts "maxAttempts",requested_at "requestedAt",started_at "startedAt",completed_at "completedAt",failed_at "failedAt",next_attempt_at "nextAttemptAt",error_code "errorCode",error_message_safe "errorMessageSafe",created_at "createdAt",created_by "createdBy",updated_at "updatedAt",version::int FROM document_analysis_jobs WHERE tenant_id=$1 AND id=$2`,[t,id])).rows[0];}
 async classification(db:PoolClient,t:string,d:string){return (await db.query<any>(`SELECT c.id,c.document_id "documentId",c.analysis_job_id "jobId",c.document_type "documentType",c.confidence::float8 confidence,c.matched_signals "matchedSignals",c.classifier,c.classifier_version "classifierVersion",c.created_at "createdAt",c.version::int FROM document_classifications c WHERE c.tenant_id=$1 AND c.document_id=$2 ORDER BY c.created_at DESC LIMIT 1`,[t,d])).rows[0];}
 async extraction(db:PoolClient,t:string,d:string){return (await db.query<any>(`SELECT e.id,e.document_id "documentId",e.classification_id "classificationId",e.schema_version "schemaVersion",e.fields,e.validation_summary "validationSummary",e.created_at "createdAt",e.version::int FROM document_extraction_results e WHERE e.tenant_id=$1 AND e.document_id=$2 ORDER BY e.created_at DESC LIMIT 1`,[t,d])).rows[0];}
 async audit(db:PoolClient,a:{tenantId:string;id:string;correlationId:string},action:string,d:string,metadata:Record<string,unknown>){const c=/^[0-9a-f-]{36}$/i.test(a.correlationId)?a.correlationId:randomUUID();await db.query("INSERT INTO audit_logs(tenant_id,actor_id,action,entity_type,entity_id,correlation_id,metadata) VALUES($1,$2,$3,'document',$4,$5,$6)",[a.tenantId,a.id,action,d,c,metadata]);await enqueueDomainEvent(db,{tenantId:a.tenantId,actorId:a.id,action,entityType:"document",entityId:d,correlationId:c,metadata});}
}
