import{createHash,randomUUID}from"node:crypto";import type{Pool}from"pg";import{domainErrors}from"../../domain/errors.js";import{assertExternalAddress,assertNoAudio,assertTransition,assertVersion}from"../../domain/communication/communication-rules.js";import type{CommunicationActor,MessageStatus}from"../../domain/communication/communication-types.js";import{inUserTransaction}from"../../infrastructure/transaction.js";import type{CommunicationProviderRegistry,InboundEnvelope}from"./communication-provider.js";import type{CommunicationRepository}from"./communication-repository.js";
export class CommunicationService{constructor(private pool:Pool,private repo:CommunicationRepository,private providers:CommunicationProviderRegistry){}
 private permission(a:CommunicationActor,p:string){if(!a.permissions.includes(p))throw domainErrors.forbidden()}
 providersStatus(a:CommunicationActor){this.permission(a,"communications.read");return this.providers.status()}
 list(a:CommunicationActor,projectId?:string){this.permission(a,"communications.read");return inUserTransaction(this.pool,a.tenantId,a.id,db=>this.repo.list(db,a,projectId))}
 get(a:CommunicationActor,id:string){this.permission(a,"communications.read");return inUserTransaction(this.pool,a.tenantId,a.id,async db=>{const x=await this.repo.get(db,a,id);if(!x)throw domainErrors.notFound();return x})}
 createConversation(a:CommunicationActor,x:any){this.permission(a,"communications.create");assertNoAudio(x);return inUserTransaction(this.pool,a.tenantId,a.id,async db=>{if(!await this.repo.access(db,a,x.projectId,x.clientId))throw domainErrors.notFound();const row=await this.repo.createConversation(db,a,x);await this.repo.audit(db,a,"communication.conversation_created",row.id,{projectId:x.projectId??null,clientId:x.clientId??null});return row})}
 createDraft(a:CommunicationActor,conversationId:string,x:any){this.permission(a,"communications.create");assertNoAudio(x);return inUserTransaction(this.pool,a.tenantId,a.id,async db=>{const conversation=await this.repo.get(db,a,conversationId);if(!conversation)throw domainErrors.notFound();if(!await this.repo.access(db,a,conversation.projectId,conversation.clientId))throw domainErrors.notFound();if(x.attachmentDocumentIds?.length&&!await this.repo.documentsExist(db,a,x.attachmentDocumentIds))throw domainErrors.notFound();const row=await this.repo.createMessage(db,a,{...x,conversationId,projectId:conversation.projectId,clientId:conversation.clientId,status:"DRAFT",direction:"outbound",provenance:{...(x.provenance??{}),preparedBy:a.id,humanReviewed:false}});for(const id of x.attachmentDocumentIds??[])await this.repo.attach(db,a,row.id,id);await this.repo.audit(db,a,"communication.draft_created",row.id,{channel:x.channel,recipient:x.to,projectId:conversation.projectId,relatedEntityType:x.relatedEntityType??null,attachmentDocumentIds:x.attachmentDocumentIds??[]});return row})}
 transition(a:CommunicationActor,id:string,to:MessageStatus,expectedVersion:number){const permission=to==="READY_FOR_REVIEW"?"communications.create":"communications.review";this.permission(a,permission);return inUserTransaction(this.pool,a.tenantId,a.id,async db=>{const row=await this.repo.message(db,a,id);if(!row)throw domainErrors.notFound();assertVersion(Number(row.version),expectedVersion);assertTransition(row.status,to);const next=await this.repo.updateStatus(db,a,id,row.status,to,expectedVersion,{provenance:{...row.provenance,...(to==="APPROVED_TO_SEND"?{approvedBy:a.id,approvedAt:new Date().toISOString(),humanReviewed:true}:{})}});if(!next)throw domainErrors.conflict();await this.repo.audit(db,a,`communication.${to.toLowerCase()}`,id,{from:row.status,to,channel:row.channel,projectId:row.projectId,recipient:row.recipientResolution});return next})}
 send(a:CommunicationActor,id:string,expectedVersion:number){this.permission(a,"communications.send");return inUserTransaction(this.pool,a.tenantId,a.id,async db=>{const row=await this.repo.message(db,a,id);if(!row)throw domainErrors.notFound();assertVersion(Number(row.version),expectedVersion);if(row.status!=="APPROVED_TO_SEND")throw domainErrors.transition();if(!await this.repo.access(db,a,row.projectId,row.clientId))throw domainErrors.notFound();const provider=this.providers.get(row.channel);if(!provider||provider.truth!=="REAL"){await this.repo.audit(db,a,"communication.send_blocked",id,{channel:row.channel,provider:provider?.id??null,reason:"PROVIDER_UNAVAILABLE"});throw domainErrors.validation("Provider is not connected; message remains APPROVED_TO_SEND",{code:"PROVIDER_UNAVAILABLE",truth:provider?.truth??"UNAVAILABLE"})}const to=(row.recipientResolution?.to??[])as string[];for(const value of to)assertExternalAddress(value);const result=await provider.send({idempotencyKey:id,channel:row.channel,to,cc:row.recipientResolution?.cc??[],subject:row.subject,body:row.body,documentIds:row.documentIds??[],threadReference:row.providerMessageId??undefined});const next=await this.repo.updateStatus(db,a,id,"APPROVED_TO_SEND","SENT",expectedVersion,{provider:provider.id,providerMessageId:result.providerMessageId});if(!next)throw domainErrors.conflict();await this.repo.audit(db,a,"communication.sent",id,{channel:row.channel,provider:provider.id,providerMessageId:result.providerMessageId});return next})}
 ingest(a:CommunicationActor,providerId:string,input:InboundEnvelope){this.permission(a,"communications.inbound.manage");assertNoAudio(input as any);return inUserTransaction(this.pool,a.tenantId,a.id,async db=>{const provider=this.providers.get(input.channel);if(!provider||provider.id!==providerId||provider.truth!=="REAL")throw domainErrors.validation("Inbound provider is not connected",{code:"PROVIDER_UNAVAILABLE"});const fingerprint=createHash("sha256").update(JSON.stringify(input)).digest("hex");const result=await this.repo.recordInbound(db,a,{...input,provider:providerId,payloadFingerprint:fingerprint,status:"DELIVERED",resolutionStatus:"unresolved"});if(!result.duplicate&&result.message)await this.repo.audit(db,a,"communication.inbound_received",result.message.id,{provider:providerId,providerEventId:input.providerEventId,resolutionStatus:"unresolved",humanResolutionRequired:true});return result})}
}
