import type{CommunicationChannel,ProviderTruth}from"../../domain/communication/communication-types.js";
export type EmailAttachment={documentId:string;documentVersionId:string;filename:string;contentType:string;content:Buffer};
export type OutboundEnvelope={idempotencyKey:string;channel:CommunicationChannel;to:string[];cc:string[];subject?:string;body:string;attachments:EmailAttachment[];threadReference?:string;tenantId:string;messageId:string};
export type InboundAttachment={providerAttachmentId:string;filename:string;contentType:string;content:Buffer};
export type InboundEnvelope={providerEventId:string;providerMessageId:string;providerThreadId?:string;replyToProviderMessageId?:string;channel:CommunicationChannel;from:string;to:string[];cc?:string[];subject?:string;body:string;originalLanguage?:string;attachmentReferences:string[];attachments?:InboundAttachment[];receivedAt:string};
export type ProviderSendResult={providerMessageId:string;acceptedAt:string};
export interface CommunicationProvider{id:string;channel:CommunicationChannel;truth:ProviderTruth;reason:string;send(input:OutboundEnvelope):Promise<ProviderSendResult>;mapInbound(payload:unknown):Promise<InboundEnvelope>}
export class UnavailableCommunicationProvider implements CommunicationProvider{truth="UNAVAILABLE"as const;constructor(public id:string,public channel:CommunicationChannel,public reason="Provider credentials and authorization are not configured."){}async send():Promise<ProviderSendResult>{throw new Error(`PROVIDER_UNAVAILABLE:${this.id}`)}async mapInbound():Promise<InboundEnvelope>{throw new Error(`PROVIDER_UNAVAILABLE:${this.id}`)}}
export class CommunicationProviderRegistry{private byChannel:Map<CommunicationChannel,CommunicationProvider>;constructor(providers:CommunicationProvider[]){this.byChannel=new Map(providers.map(x=>[x.channel,x]))}get(channel:CommunicationChannel){return this.byChannel.get(channel)}status(){return [...this.byChannel.values()].map(({id,channel,truth,reason})=>({id,channel,truth,reason}))}}
export const unavailableCommunicationProviders=()=>[new UnavailableCommunicationProvider("telegram","telegram"),new UnavailableCommunicationProvider("email","email"),new UnavailableCommunicationProvider("whatsapp","whatsapp"),new UnavailableCommunicationProvider("sms","sms","No SMS provider adapter is installed.")];
export const defaultCommunicationProviders=new CommunicationProviderRegistry(unavailableCommunicationProviders());
