import type{CommunicationActor}from"../../domain/communication/communication-types.js";import type{CommunicationService}from"./communication-service.js";import type{ResendEmailProvider,ResendWebhookEvent}from"../../infrastructure/communication/resend-email-provider.js";
type Route={address:string;tenantId:string;actorId:string};
export class InvalidWebhookSignatureError extends Error{constructor(){super("Invalid Resend webhook signature");this.name="InvalidWebhookSignatureError"}}
export function parseResendInboundRoutes(value?:string):Route[]{if(!value)return[];const routes=JSON.parse(value)as Route[],seen=new Set<string>();for(const route of routes){const address=route.address.trim().toLowerCase();if(!address||!route.tenantId||!route.actorId||seen.has(address))throw new Error("RESEND_INBOUND_ROUTES must contain unique exact addresses");seen.add(address);route.address=address}return routes}
export class ResendWebhookService{constructor(private provider:ResendEmailProvider,private communications:CommunicationService,private routes:Route[]){}
 private actor(route:Route):CommunicationActor{return{id:route.actorId,tenantId:route.tenantId,permissions:["communications.inbound.manage","documents.read","documents.download","documents.upload"],correlationId:"resend-webhook"}}
 async handle(payload:string,headers:{id:string;timestamp:string;signature:string}){let event:ResendWebhookEvent;try{event=this.provider.verifyWebhook(payload,headers)as ResendWebhookEvent}catch{throw new InvalidWebhookSignatureError()}event.id=headers.id;if(event.type==="email.received"){const addresses=[...(event.data.received_for??[]),...(event.data.to??[])].map((x:string)=>x.toLowerCase()),matches=this.routes.filter(route=>addresses.includes(route.address));if(matches.length!==1)return{accepted:true,resolutionStatus:matches.length?"ambiguous":"unresolved",humanResolutionRequired:true};const envelope=await this.provider.mapInbound(event),result=await this.communications.ingest(this.actor(matches[0]),this.provider.id,envelope);return{accepted:true,duplicate:result.duplicate,resolutionStatus:"unresolved",humanResolutionRequired:true}}
 if(["email.delivered","email.failed","email.bounced"].includes(event.type)){const tags=event.data.tags??{},tenantId=tags.tenant_id,messageId=tags.communication_message_id,route=this.routes.find(x=>x.tenantId===tenantId);if(!route||!messageId)return{accepted:true,resolutionStatus:"unresolved"};const result=await this.communications.processProviderEvent(this.actor(route),{provider:this.provider.id,providerEventId:headers.id,eventType:event.type,messageId,providerMessageId:event.data.email_id,occurredAt:event.data.created_at??event.created_at,errorCode:event.type==="email.delivered"?undefined:event.type.toUpperCase().replace(".","_"),errorMessage:event.data.failed?.reason??event.data.bounce?.message??event.type});return{accepted:true,duplicate:result.duplicate}}
 return{accepted:true,ignored:true}}
}
