import{randomUUID}from"node:crypto";import type{Pool,PoolClient}from"pg";import{domainErrors}from"../../domain/errors.js";import{normalizeClientRequest,validateClientDecision}from"../../domain/client-workspace/client-workspace-rules.js";import type{CreateClientRequest}from"../../domain/client-workspace/client-workspace-types.js";import{ClientWorkspaceRepository}from"../../infrastructure/client-workspace/client-workspace-repository.js";import{inUserTransaction}from"../../infrastructure/transaction.js";import{enqueueDomainEvent}from"../../infrastructure/notification/outbox.js";
export type ClientWorkspaceActor={id:string;tenantId:string;permissions:readonly string[];correlationId:string};
const need=(actor:ClientWorkspaceActor,permission:string)=>{if(!actor.permissions.includes(permission))throw domainErrors.forbidden()};
export class ClientWorkspaceService{constructor(private readonly pool:Pool,private readonly repository=new ClientWorkspaceRepository()){}
 private async member(db:PoolClient,actor:ClientWorkspaceActor,projectId:string){const membership=(await this.repository.membership(db,actor.tenantId,actor.id,projectId))[0];if(!membership)throw domainErrors.notFound();return membership}
 private async audit(db:PoolClient,actor:ClientWorkspaceActor,action:string,entityType:string,entityId:string,metadata:Record<string,unknown>){const correlationId=/^[0-9a-f-]{36}$/i.test(actor.correlationId)?actor.correlationId:randomUUID();await db.query("INSERT INTO audit_logs(tenant_id,actor_id,action,entity_type,entity_id,correlation_id,metadata)VALUES($1,$2,$3,$4,$5,$6,$7)",[actor.tenantId,actor.id,action,entityType,entityId,correlationId,metadata]);await enqueueDomainEvent(db,{tenantId:actor.tenantId,actorId:actor.id,action,entityType,entityId,correlationId,metadata})}
 async overview(actor:ClientWorkspaceActor){need(actor,"client_workspace.read");return inUserTransaction(this.pool,actor.tenantId,actor.id,db=>this.repository.overview(db,actor.tenantId,actor.id))}
 async project(actor:ClientWorkspaceActor,projectId:string){need(actor,"client_workspace.read");return inUserTransaction(this.pool,actor.tenantId,actor.id,async db=>{await this.member(db,actor,projectId);return this.repository.projectData(db,actor.tenantId,actor.id,projectId)})}
 async createRequest(actor:ClientWorkspaceActor,input:CreateClientRequest){need(actor,"client_requests.create");const value=normalizeClientRequest(input);return inUserTransaction(this.pool,actor.tenantId,actor.id,async db=>{const member=await this.member(db,actor,value.projectId),project=(await db.query<{projectManagerId:string|null}>(`SELECT project_manager_id AS "projectManagerId" FROM projects WHERE tenant_id=$1 AND id=$2`,[actor.tenantId,value.projectId])).rows[0];const request=await this.repository.createRequest(db,actor.tenantId,actor.id,member.clientId,project?.projectManagerId??null,randomUUID(),value);await this.audit(db,actor,"client.request_submitted","client_request",request.id,{projectId:value.projectId,requestType:value.requestType,recipientUserId:project?.projectManagerId});return request})}
 async decide(actor:ClientWorkspaceActor,id:string,input:{expectedVersion:number;decision:string;comment?:string}){need(actor,"client_approvals.decide");validateClientDecision(input.decision);if(!Number.isInteger(input.expectedVersion)||input.expectedVersion<1)throw domainErrors.validation("expectedVersion must be positive");return inUserTransaction(this.pool,actor.tenantId,actor.id,async db=>{const current=await this.repository.approval(db,actor.tenantId,id);if(!current)throw domainErrors.notFound();await this.member(db,actor,current.projectId);if(current.version!==input.expectedVersion)throw domainErrors.conflict();const updated=await this.repository.decide(db,actor.tenantId,actor.id,id,input.expectedVersion,input.decision,input.comment?.trim()||null);if(!updated)throw domainErrors.conflict();await this.audit(db,actor,`client.approval_${input.decision}`,"client_approval",id,{projectId:current.projectId,entityType:current.entityType,entityId:current.entityId,previousVersion:current.version,newVersion:updated.version});return updated})}
}
