import{randomUUID}from"node:crypto";import{domainErrors}from"../../domain/errors.js";import{assertAudioChunk,languageBase,requireVoice,validateVoiceSession}from"../../domain/voice-bridge/voice-bridge-rules.js";import type{VoiceActor,VoiceParticipant,VoiceSession}from"../../domain/voice-bridge/voice-bridge-types.js";import type{VoiceProviderRegistry}from"./voice-provider.js";
export interface VoiceAuditPort{record(actor:VoiceActor,action:string,sessionId:string,metadata:Record<string,unknown>):Promise<void>}
export interface VoiceCommandPort{execute(actor:VoiceActor,input:{text:string;inputMode:"voice";projectId?:string}):Promise<unknown>}
export interface VoiceEntitlementPort{enabled(tenantId:string,capability:"voice"):Promise<boolean>}
export interface VoiceParticipantAccessPort{allBelongToTenant(actor:VoiceActor,userIds:readonly string[]):Promise<boolean>}
export class EnabledVoiceEntitlement implements VoiceEntitlementPort{async enabled(){return true}}
export class SelfOnlyVoiceParticipantAccess implements VoiceParticipantAccessPort{async allBelongToTenant(actor:VoiceActor,userIds:readonly string[]){return userIds.every(id=>id===actor.id)}}
export class VoiceBridgeService{private sessions=new Map<string,VoiceSession>();constructor(private providers:VoiceProviderRegistry,private audit:VoiceAuditPort,private commands:VoiceCommandPort,private entitlement:VoiceEntitlementPort=new EnabledVoiceEntitlement(),private participantAccess:VoiceParticipantAccessPort=new SelfOnlyVoiceParticipantAccess(),private maxChunkBytes=2_000_000,private maxChunks=1_000,private maxSessionMs=15*60*1_000){}
 status(a:VoiceActor){requireVoice(a,"voice.use");return{architecture:"REAL",recording:"PROHIBITED_BY_ARCHITECTURE",providers:this.providers.status()}}
 async start(a:VoiceActor,input:{mode:"conversation_translation"|"voice_command";participants:VoiceParticipant[]}){requireVoice(a,"voice.use");requireVoice(a,input.mode==="voice_command"?"voice.command":"voice.translate");if(!await this.entitlement.enabled(a.tenantId,"voice"))throw domainErrors.forbidden();validateVoiceSession(input.mode,input.participants);if(!await this.participantAccess.allBelongToTenant(a,input.participants.map(x=>x.userId)))throw domainErrors.forbidden();const truth=this.providers.status().every(x=>x.truth==="REAL")?"REAL":"PARTIAL",session:VoiceSession={id:randomUUID(),tenantId:a.tenantId,ownerId:a.id,participants:input.participants,mode:input.mode,state:"active",createdAt:new Date().toISOString(),providerTruth:truth,chunkCount:0};this.sessions.set(session.id,session);await this.audit.record(a,"voice.session_started",session.id,{mode:session.mode,participantCount:session.participants.length,providerTruth:truth,recording:"PROHIBITED_BY_ARCHITECTURE"});return session}
 private session(a:VoiceActor,id:string){const s=this.sessions.get(id);if(!s||s.tenantId!==a.tenantId||s.ownerId!==a.id)throw domainErrors.notFound();if(Date.now()-Date.parse(s.createdAt)>this.maxSessionMs){this.sessions.delete(id);throw domainErrors.validation("SESSION_EXPIRED")}if(s.state!=="active")throw domainErrors.validation("Voice session has ended");if(s.chunkCount>=this.maxChunks)throw domainErrors.validation("PROVIDER_RATE_LIMIT");return s}
 async process(a:VoiceActor,id:string,input:{audioBase64:string;contentType:string;speakingLanguage?:string;listeningLanguage:string;projectId?:string}){requireVoice(a,"voice.use");const s=this.session(a,id),audio=Buffer.from(input.audioBase64,"base64");try{assertAudioChunk(audio,this.maxChunkBytes);const providers=this.providers.get(),recognition=await providers.recognition.recognize({audio,contentType:input.contentType,language:input.speakingLanguage}),source=languageBase(input.speakingLanguage??recognition.detectedLanguage),target=languageBase(input.listeningLanguage);s.chunkCount+=1;if(s.mode==="voice_command"){requireVoice(a,"voice.command");const command=await this.commands.execute(a,{text:recognition.text,inputMode:"voice",projectId:input.projectId});await this.audit.record(a,"voice.command_forwarded",s.id,{recognitionProvider:providers.recognition.id,sourceLanguage:source,projectId:input.projectId??null});return{mode:s.mode,recognizedText:recognition.text,detectedLanguage:recognition.detectedLanguage,command,recording:"PROHIBITED_BY_ARCHITECTURE"}}requireVoice(a,"voice.translate");const translation=source===target?{text:recognition.text,sourceLanguage:source,targetLanguage:target,providerReference:"identity",machineTranslation:true as const}:await providers.translation.translate({text:recognition.text,sourceLanguage:source,targetLanguage:target}),speech=await providers.synthesis.synthesize({text:translation.text,language:target}),audioBase64=speech.audio.toString("base64");speech.audio.fill(0);await this.audit.record(a,"voice.turn_processed",s.id,{sourceLanguage:source,targetLanguage:target,recognitionProvider:providers.recognition.id,translationProvider:providers.translation.id,synthesisProvider:providers.synthesis.id,machineTranslation:true});return{mode:s.mode,recognizedText:recognition.text,detectedLanguage:recognition.detectedLanguage,translatedText:translation.text,targetLanguage:target,machineTranslation:true,audioBase64,contentType:speech.contentType,recording:"PROHIBITED_BY_ARCHITECTURE"}}finally{audio.fill(0)}}
 async end(a:VoiceActor,id:string){requireVoice(a,"voice.use");const s=this.session(a,id);s.state="ended";s.endedAt=new Date().toISOString();this.sessions.delete(id);await this.audit.record(a,"voice.session_ended",id,{mode:s.mode,chunkCount:s.chunkCount});return{...s}}
}
