import type {PoolClient} from "pg";
import type {CreateEstimate,CreateEstimateItem,Estimate,EstimateChildQuery,EstimateItem,EstimateMaterial,EstimatePage,EstimateQuery,UpdateEstimate,UpdateEstimateItem,UpdateEstimateMaterial} from "../../domain/estimate-engine/estimate-engine-types.js";
const estimateSelect=`e.id,e.tenant_id "tenantId",e.project_id "projectId",p.name "projectName",e.code,e.display_name "displayName",e.currency,e.status,e.total_labor::text "totalLabor",e.total_materials::text "totalMaterials",e.total_cost::text "totalCost",e.notes,e.version::int,e.created_at "createdAt",e.updated_at "updatedAt",e.created_by "createdBy",e.updated_by "updatedBy"`;
const itemSelect=`i.id,i.tenant_id "tenantId",i.estimate_id "estimateId",i.work_id "workId",w.code "workCode",w.display_name "workName",i.quantity::text quantity,i.measurement_unit_id "measurementUnitId",u.code "measurementUnitCode",i.norm_id "normId",n.code "normCode",i.labor_cost::text "laborCost",i.material_cost::text "materialCost",i.total_cost::text "totalCost",i.version::int,i.created_at "createdAt",i.updated_at "updatedAt",i.created_by "createdBy",i.updated_by "updatedBy"`;
const materialSelect=`em.id,em.tenant_id "tenantId",em.estimate_item_id "estimateItemId",em.material_id "materialId",m.code "materialCode",m.display_name "materialName",em.quantity::text quantity,em.unit_price::text "unitPrice",em.total_price::text "totalPrice",em.price_list_id "priceListId",pl.code "priceListCode",em.version::int,em.created_at "createdAt",em.updated_at "updatedAt",em.created_by "createdBy",em.updated_by "updatedBy"`;
const estimateSort={code:"e.code",displayName:"e.display_name",status:"e.status",totalCost:"e.total_cost",createdAt:"e.created_at",updatedAt:"e.updated_at"} as const;
export class EstimateEngineRepository{
 findEstimate(db:PoolClient,t:string,id:string){return db.query<Estimate>(`SELECT ${estimateSelect} FROM estimates e JOIN projects p ON p.tenant_id=e.tenant_id AND p.id=e.project_id WHERE e.tenant_id=$1 AND e.id=$2`,[t,id]).then(r=>r.rows[0]);}
 findItem(db:PoolClient,t:string,id:string){return db.query<EstimateItem>(`SELECT ${itemSelect} FROM estimate_items i JOIN work_items w ON w.tenant_id=i.tenant_id AND w.id=i.work_id JOIN measurement_units u ON u.tenant_id=i.tenant_id AND u.id=i.measurement_unit_id JOIN construction_norms n ON n.tenant_id=i.tenant_id AND n.id=i.norm_id WHERE i.tenant_id=$1 AND i.id=$2`,[t,id]).then(r=>r.rows[0]);}
 findMaterial(db:PoolClient,t:string,id:string){return db.query<EstimateMaterial>(`SELECT ${materialSelect} FROM estimate_materials em JOIN materials m ON m.tenant_id=em.tenant_id AND m.id=em.material_id JOIN price_lists pl ON pl.tenant_id=em.tenant_id AND pl.id=em.price_list_id WHERE em.tenant_id=$1 AND em.id=$2`,[t,id]).then(r=>r.rows[0]);}
 itemPriceList(db:PoolClient,t:string,id:string){return db.query<{priceListId:string}>('SELECT price_list_id "priceListId" FROM estimate_materials WHERE tenant_id=$1 AND estimate_item_id=$2 ORDER BY id LIMIT 1',[t,id]).then(r=>r.rows[0]);}
 findProject(db:PoolClient,t:string,id:string){return db.query<{id:string;status:string}>("SELECT id,status FROM projects WHERE tenant_id=$1 AND id=$2",[t,id]).then(r=>r.rows[0]);}
 findWork(db:PoolClient,t:string,id:string){return db.query<{id:string;status:string;measurementUnitId:string}>('SELECT id,status,measurement_unit_id "measurementUnitId" FROM work_items WHERE tenant_id=$1 AND id=$2',[t,id]).then(r=>r.rows[0]);}
 findNormForWork(db:PoolClient,t:string,workId:string){return db.query<{id:string}>("SELECT id FROM construction_norms WHERE tenant_id=$1 AND work_id=$2 AND status='active' ORDER BY is_system DESC,code,id LIMIT 1",[t,workId]).then(r=>r.rows[0]);}
 normItemCount(db:PoolClient,t:string,normId:string){return db.query<{count:string}>("SELECT count(*) FROM construction_norm_items ni JOIN materials m ON m.tenant_id=ni.tenant_id AND m.id=ni.material_id AND m.status='active' WHERE ni.tenant_id=$1 AND ni.norm_id=$2",[t,normId]).then(r=>Number(r.rows[0].count));}
 async consumption(db:PoolClient,t:string,normId:string,priceListId:string,currency:string){const list=(await db.query<{id:string}>("SELECT id FROM price_lists WHERE tenant_id=$1 AND id=$2 AND currency=$3 AND status='active' AND valid_from<=current_date AND(valid_to IS NULL OR valid_to>=current_date)",[t,priceListId,currency])).rows[0];if(!list)return [];return db.query<{materialId:string;measurementUnitId:string;quantity:string;wastePercent:string;unitPrice:string;priceListId:string}>(`SELECT DISTINCT ON(ni.material_id) ni.material_id "materialId",ni.measurement_unit_id "measurementUnitId",ni.quantity::text,ni.waste_percent::text "wastePercent",pli.unit_price::text "unitPrice",pli.price_list_id "priceListId" FROM construction_norm_items ni JOIN materials m ON m.tenant_id=ni.tenant_id AND m.id=ni.material_id AND m.status='active' JOIN price_list_items pli ON pli.tenant_id=ni.tenant_id AND pli.price_list_id=$3 AND pli.material_id=ni.material_id AND pli.status='active' AND pli.valid_from<=current_date AND(pli.valid_to IS NULL OR pli.valid_to>=current_date) WHERE ni.tenant_id=$1 AND ni.norm_id=$2 ORDER BY ni.material_id,pli.valid_from DESC,pli.id DESC LIMIT 100`,[t,normId,priceListId]).then(r=>r.rows);}
 async estimates(db:PoolClient,t:string,q:EstimateQuery):Promise<EstimatePage<Estimate>>{const v:any[]=[t],f=["e.tenant_id=$1"];if(q.search){v.push(`%${q.search}%`);f.push(`(e.code ILIKE $${v.length} OR e.display_name ILIKE $${v.length})`);}if(q.projectId){v.push(q.projectId);f.push(`e.project_id=$${v.length}`);}if(q.status){v.push(q.status);f.push(`e.status=$${v.length}`);}const joins="estimates e JOIN projects p ON p.tenant_id=e.tenant_id AND p.id=e.project_id",where=f.join(" AND "),total=Number((await db.query<{count:string}>(`SELECT count(*) FROM ${joins} WHERE ${where}`,v)).rows[0].count);v.push(q.pageSize,(q.page-1)*q.pageSize);const d=q.sortOrder==="asc"?"ASC":"DESC",items=(await db.query<Estimate>(`SELECT ${estimateSelect} FROM ${joins} WHERE ${where} ORDER BY ${estimateSort[q.sortBy]} ${d},e.id ${d} LIMIT $${v.length-1} OFFSET $${v.length}`,v)).rows;return {items,pagination:{page:q.page,pageSize:q.pageSize,total,totalPages:Math.ceil(total/q.pageSize)}};}
 async items(db:PoolClient,t:string,q:EstimateChildQuery):Promise<EstimatePage<EstimateItem>>{const v:any[]=[t],f=["i.tenant_id=$1"];if(q.estimateId){v.push(q.estimateId);f.push(`i.estimate_id=$${v.length}`);}if(q.search){v.push(`%${q.search}%`);f.push(`(w.code ILIKE $${v.length} OR w.display_name ILIKE $${v.length})`);}const joins="estimate_items i JOIN work_items w ON w.tenant_id=i.tenant_id AND w.id=i.work_id JOIN measurement_units u ON u.tenant_id=i.tenant_id AND u.id=i.measurement_unit_id JOIN construction_norms n ON n.tenant_id=i.tenant_id AND n.id=i.norm_id",where=f.join(" AND "),total=Number((await db.query<{count:string}>(`SELECT count(*) FROM ${joins} WHERE ${where}`,v)).rows[0].count);v.push(q.pageSize,(q.page-1)*q.pageSize);const d=q.sortOrder==="asc"?"ASC":"DESC",items=(await db.query<EstimateItem>(`SELECT ${itemSelect} FROM ${joins} WHERE ${where} ORDER BY w.code ${d},i.id ${d} LIMIT $${v.length-1} OFFSET $${v.length}`,v)).rows;return {items,pagination:{page:q.page,pageSize:q.pageSize,total,totalPages:Math.ceil(total/q.pageSize)}};}
 async materials(db:PoolClient,t:string,q:EstimateChildQuery):Promise<EstimatePage<EstimateMaterial>>{const v:any[]=[t],f=["em.tenant_id=$1"];if(q.estimateItemId){v.push(q.estimateItemId);f.push(`em.estimate_item_id=$${v.length}`);}if(q.search){v.push(`%${q.search}%`);f.push(`(m.code ILIKE $${v.length} OR m.display_name ILIKE $${v.length})`);}const joins="estimate_materials em JOIN materials m ON m.tenant_id=em.tenant_id AND m.id=em.material_id JOIN price_lists pl ON pl.tenant_id=em.tenant_id AND pl.id=em.price_list_id",where=f.join(" AND "),total=Number((await db.query<{count:string}>(`SELECT count(*) FROM ${joins} WHERE ${where}`,v)).rows[0].count);v.push(q.pageSize,(q.page-1)*q.pageSize);const d=q.sortOrder==="asc"?"ASC":"DESC",items=(await db.query<EstimateMaterial>(`SELECT ${materialSelect} FROM ${joins} WHERE ${where} ORDER BY m.code ${d},em.id ${d} LIMIT $${v.length-1} OFFSET $${v.length}`,v)).rows;return {items,pagination:{page:q.page,pageSize:q.pageSize,total,totalPages:Math.ceil(total/q.pageSize)}};}
 createEstimate(db:PoolClient,t:string,a:string,id:string,x:CreateEstimate){return db.query<Estimate>(`WITH inserted AS (INSERT INTO estimates(id,tenant_id,project_id,code,display_name,currency,notes,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$8) RETURNING *) SELECT ${estimateSelect} FROM inserted e JOIN projects p ON p.tenant_id=e.tenant_id AND p.id=e.project_id`,[id,t,x.projectId,x.code,x.displayName,x.currency,x.notes??null,a]).then(r=>r.rows[0]);}
 updateEstimate(db:PoolClient,t:string,a:string,id:string,x:UpdateEstimate){const m=[["displayName","display_name"],["notes","notes"]] as const,s:string[]=[],v:any[]=[];for(const[k,c]of m)if(x[k]!==undefined){v.push(x[k]);s.push(`${c}=$${v.length}`);}if(!s.length)return this.findEstimate(db,t,id);v.push(a,id,t,x.expectedVersion);return db.query<Estimate>(`WITH updated AS (UPDATE estimates SET ${s.join(",")},updated_by=$${v.length-3},updated_at=now(),version=version+1 WHERE id=$${v.length-2} AND tenant_id=$${v.length-1} AND version=$${v.length} RETURNING *) SELECT ${estimateSelect} FROM updated e JOIN projects p ON p.tenant_id=e.tenant_id AND p.id=e.project_id`,v).then(r=>r.rows[0]);}
 setStatus(db:PoolClient,t:string,a:string,id:string,status:string,version:number){return db.query<Estimate>(`WITH updated AS (UPDATE estimates SET status=$1,updated_by=$2,updated_at=now(),version=version+1 WHERE tenant_id=$3 AND id=$4 AND version=$5 RETURNING *) SELECT ${estimateSelect} FROM updated e JOIN projects p ON p.tenant_id=e.tenant_id AND p.id=e.project_id`,[status,a,t,id,version]).then(r=>r.rows[0]);}
 createItem(db:PoolClient,t:string,a:string,id:string,x:CreateEstimateItem,normId:string){return db.query<EstimateItem>(`WITH inserted AS (INSERT INTO estimate_items(id,tenant_id,estimate_id,work_id,quantity,measurement_unit_id,norm_id,labor_cost,total_cost,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$8,$9,$9) RETURNING *) SELECT ${itemSelect} FROM inserted i JOIN work_items w ON w.tenant_id=i.tenant_id AND w.id=i.work_id JOIN measurement_units u ON u.tenant_id=i.tenant_id AND u.id=i.measurement_unit_id JOIN construction_norms n ON n.tenant_id=i.tenant_id AND n.id=i.norm_id`,[id,t,x.estimateId,x.workId,x.quantity,x.measurementUnitId,normId,x.laborCost,a]).then(r=>r.rows[0]);}
 updateItem(db:PoolClient,t:string,a:string,id:string,x:UpdateEstimateItem){const s:string[]=[],v:any[]=[];if(x.quantity!==undefined){v.push(x.quantity);s.push(`quantity=$${v.length}`);}if(x.laborCost!==undefined){v.push(x.laborCost);s.push(`labor_cost=$${v.length}`,`total_cost=material_cost+$${v.length}::numeric`);}if(!s.length)return this.findItem(db,t,id);v.push(a,id,t,x.expectedVersion);return db.query<EstimateItem>(`WITH updated AS (UPDATE estimate_items SET ${s.join(",")},updated_by=$${v.length-3},updated_at=now(),version=version+1 WHERE id=$${v.length-2} AND tenant_id=$${v.length-1} AND version=$${v.length} RETURNING *) SELECT ${itemSelect} FROM updated i JOIN work_items w ON w.tenant_id=i.tenant_id AND w.id=i.work_id JOIN measurement_units u ON u.tenant_id=i.tenant_id AND u.id=i.measurement_unit_id JOIN construction_norms n ON n.tenant_id=i.tenant_id AND n.id=i.norm_id`,v).then(r=>r.rows[0]);}
 replaceMaterials(db:PoolClient,t:string,a:string,itemId:string,rows:Array<{materialId:string;quantity:string;unitPrice:string;totalPrice:string;priceListId:string}>){return db.query("DELETE FROM estimate_materials WHERE tenant_id=$1 AND estimate_item_id=$2",[t,itemId]).then(async()=>{for(const x of rows)await db.query("INSERT INTO estimate_materials(tenant_id,estimate_item_id,material_id,quantity,unit_price,total_price,price_list_id,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$8)",[t,itemId,x.materialId,x.quantity,x.unitPrice,x.totalPrice,x.priceListId,a]);});}
 updateMaterial(db:PoolClient,t:string,a:string,id:string,x:UpdateEstimateMaterial){const s:string[]=[],v:any[]=[],p:Record<string,number>={};if(x.quantity!==undefined){v.push(x.quantity);p.quantity=v.length;s.push(`quantity=$${v.length}`);}if(x.unitPrice!==undefined){v.push(x.unitPrice);p.unitPrice=v.length;s.push(`unit_price=$${v.length}`);}if(!s.length)return this.findMaterial(db,t,id);s.push(`total_price=round(${p.quantity?`$${p.quantity}`:"quantity"}::numeric*${p.unitPrice?`$${p.unitPrice}`:"unit_price"}::numeric,4)`);v.push(a,id,t,x.expectedVersion);return db.query<EstimateMaterial>(`WITH updated AS (UPDATE estimate_materials SET ${s.join(",")},updated_by=$${v.length-3},updated_at=now(),version=version+1 WHERE id=$${v.length-2} AND tenant_id=$${v.length-1} AND version=$${v.length} RETURNING *) SELECT ${materialSelect} FROM updated em JOIN materials m ON m.tenant_id=em.tenant_id AND m.id=em.material_id JOIN price_lists pl ON pl.tenant_id=em.tenant_id AND pl.id=em.price_list_id`,v).then(r=>r.rows[0]);}
 deleteItem(db:PoolClient,t:string,id:string,version:number){return db.query("DELETE FROM estimate_materials WHERE tenant_id=$1 AND estimate_item_id=$2",[t,id]).then(()=>db.query<{id:string}>("DELETE FROM estimate_items WHERE tenant_id=$1 AND id=$2 AND version=$3 RETURNING id",[t,id,version])).then(r=>r.rows[0]);}
 deleteMaterial(db:PoolClient,t:string,id:string,version:number){return db.query<{id:string}>("DELETE FROM estimate_materials WHERE tenant_id=$1 AND id=$2 AND version=$3 RETURNING id",[t,id,version]).then(r=>r.rows[0]);}
 async refreshTotals(db:PoolClient,t:string,a:string,estimateId:string){await db.query("UPDATE estimate_items i SET material_cost=x.material,total_cost=i.labor_cost+x.material,updated_by=$3,updated_at=now(),version=version+1 FROM(SELECT estimate_item_id,COALESCE(sum(total_price),0) material FROM estimate_materials WHERE tenant_id=$1 GROUP BY estimate_item_id)x WHERE i.tenant_id=$1 AND i.estimate_id=$2 AND i.id=x.estimate_item_id",[t,estimateId,a]);await db.query("UPDATE estimate_items SET material_cost=0,total_cost=labor_cost,updated_by=$3,updated_at=now(),version=version+1 WHERE tenant_id=$1 AND estimate_id=$2 AND NOT EXISTS(SELECT 1 FROM estimate_materials em WHERE em.tenant_id=$1 AND em.estimate_item_id=estimate_items.id)",[t,estimateId,a]);await db.query(`UPDATE estimates e SET total_labor=x.labor,total_materials=x.material,total_cost=x.labor+x.material,updated_by=$3,updated_at=now(),version=version+1 FROM(SELECT COALESCE(sum(labor_cost),0) labor,COALESCE(sum(material_cost),0) material FROM estimate_items WHERE tenant_id=$1 AND estimate_id=$2)x WHERE e.tenant_id=$1 AND e.id=$2`,[t,estimateId,a]);return this.findEstimate(db,t,estimateId);}
}
