import {randomUUID} from "node:crypto";
import type {Pool,PoolClient} from "pg";
import {assertCanArchiveProject,assertCanCreateProject,assertCanReadProject,assertCanTransitionProject,assertCanUpdateProject} from "../../authorization/project-policy.js";
import {DomainError,domainErrors} from "../../domain/errors.js";
import {lifecycleTransition,normalizeProject,normalizeProjectUpdate} from "../../domain/project/project-rules.js";
import type {CreateProjectCommand,Project,ProjectLifecycleAction,ProjectListQuery,ProjectListResult,UpdateProjectCommand} from "../../domain/project/project-types.js";
import {ProjectRepository} from "../../infrastructure/project/project-repository.js";
import {inTenantTransaction} from "../../infrastructure/transaction.js";

export type ProjectActor={id:string;tenantId:string;permissions:readonly string[];correlationId:string};
const correlation=(value:string)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)?value:randomUUID();
export class ProjectService {
  constructor(private readonly pool:Pool,private readonly repository=new ProjectRepository()){}
  private async audit(db:PoolClient,actor:ProjectActor,action:string,id:string|undefined,metadata:Record<string,unknown>={}){await db.query("INSERT INTO audit_logs(tenant_id,actor_id,action,entity_type,entity_id,correlation_id,metadata) VALUES($1,$2,$3,'project',$4,$5,$6)",[actor.tenantId,actor.id,action,id??null,correlation(actor.correlationId),metadata]);}
  private async authorize(actor:ProjectActor,assertion:(actor:ProjectActor)=>void,operation:string,id?:string){try{assertion(actor);}catch(error){await inTenantTransaction(this.pool,actor.tenantId,db=>this.audit(db,actor,"project.permission_denied",id,{operation}));throw error;}}
  private async recordFailure(actor:ProjectActor,error:unknown,id?:string){if(!(error instanceof DomainError))return;const actions:Partial<Record<DomainError["code"],string>>={VERSION_CONFLICT:"project.version_conflict",ENTITY_ARCHIVED:"project.archived_mutation_denied",INVALID_STATUS_TRANSITION:"project.invalid_lifecycle_transition",DUPLICATE_RECORD:"project.duplicate_number"};const action=actions[error.code];if(action)await inTenantTransaction(this.pool,actor.tenantId,db=>this.audit(db,actor,action,id));}
  private async assertRelationships(db:PoolClient,tenantId:string,value:{clientId:string;propertyId:string;financialOwnerLegalEntityId:string;projectManagerId?:string|null},creating:boolean){
    const client=await this.repository.findClient(db,tenantId,value.clientId);if(!client)throw domainErrors.notFound();
    const property=await this.repository.findProperty(db,tenantId,value.propertyId);if(!property)throw domainErrors.notFound();
    if(property.clientId!==value.clientId)throw new DomainError("INVALID_RELATIONSHIP",422,"Property does not belong to the selected client");
    if(creating&&(property.archivedAt||property.status==="archived"))throw domainErrors.archived();
    if(!await this.repository.findLegalEntity(db,tenantId,value.financialOwnerLegalEntityId))throw domainErrors.notFound();
    if(value.projectManagerId&&!await this.repository.findUser(db,tenantId,value.projectManagerId))throw domainErrors.notFound();
  }
  async createProject(actor:ProjectActor,input:CreateProjectCommand):Promise<Project>{await this.authorize(actor,assertCanCreateProject,"create");const value=normalizeProject(input);try{return await inTenantTransaction(this.pool,actor.tenantId,async db=>{await this.assertRelationships(db,actor.tenantId,value,true);if(await this.repository.findDuplicateNumber(db,actor.tenantId,value.projectNumber))throw domainErrors.duplicate("A project with this project number already exists");const entity=await this.repository.create(db,actor.tenantId,actor.id,randomUUID(),value);await this.audit(db,actor,"project.created",entity.id,{clientId:entity.clientId,propertyId:entity.propertyId});return entity;});}catch(error){await this.recordFailure(actor,error);throw error;}}
  async getProject(actor:ProjectActor,id:string):Promise<Project>{await this.authorize(actor,assertCanReadProject,"read",id);const entity=await inTenantTransaction(this.pool,actor.tenantId,db=>this.repository.findById(db,actor.tenantId,id));if(!entity)throw domainErrors.notFound();return entity;}
  async listProjects(actor:ProjectActor,query:ProjectListQuery):Promise<ProjectListResult>{await this.authorize(actor,assertCanReadProject,"list");if(!Number.isInteger(query.page)||query.page<1||!Number.isInteger(query.pageSize)||query.pageSize<1||query.pageSize>100)throw domainErrors.validation("Invalid pagination");if(!(["projectNumber","name","status","startDate","expectedCompletionDate","createdAt","updatedAt"] as string[]).includes(query.sortBy))throw domainErrors.validation("Invalid sort field");return inTenantTransaction(this.pool,actor.tenantId,db=>this.repository.list(db,actor.tenantId,query));}
  async updateProject(actor:ProjectActor,id:string,input:UpdateProjectCommand):Promise<Project>{await this.authorize(actor,assertCanUpdateProject,"update",id);const value=normalizeProjectUpdate(input);try{return await inTenantTransaction(this.pool,actor.tenantId,async db=>{const current=await this.repository.findById(db,actor.tenantId,id);if(!current)throw domainErrors.notFound();if(current.archivedAt||current.status==="archived")throw domainErrors.archived();if(current.version!==value.expectedVersion)throw domainErrors.conflict();const relationships={clientId:value.clientId??current.clientId,propertyId:value.propertyId??current.propertyId,financialOwnerLegalEntityId:value.financialOwnerLegalEntityId??current.financialOwnerLegalEntityId,projectManagerId:value.projectManagerId===undefined?current.projectManagerId:value.projectManagerId};await this.assertRelationships(db,actor.tenantId,relationships,false);const start=value.startDate===undefined?current.startDate:value.startDate,end=value.expectedCompletionDate===undefined?current.expectedCompletionDate:value.expectedCompletionDate;if(start&&end&&end<start)throw domainErrors.validation("expectedCompletionDate cannot be before startDate");if(value.projectNumber&&await this.repository.findDuplicateNumber(db,actor.tenantId,value.projectNumber,id))throw domainErrors.duplicate("A project with this project number already exists");const updated=await this.repository.update(db,actor.tenantId,actor.id,id,value);if(!updated)throw domainErrors.conflict();await this.audit(db,actor,"project.updated",id,{previousVersion:current.version,newVersion:updated.version});return updated;});}catch(error){await this.recordFailure(actor,error,id);throw error;}}
  async archiveProject(actor:ProjectActor,id:string,expectedVersion:number):Promise<Project>{await this.authorize(actor,assertCanArchiveProject,"archive",id);if(!Number.isInteger(expectedVersion)||expectedVersion<1)throw domainErrors.validation("expectedVersion must be a positive integer");try{return await inTenantTransaction(this.pool,actor.tenantId,async db=>{const current=await this.repository.findById(db,actor.tenantId,id);if(!current)throw domainErrors.notFound();if(current.archivedAt||current.status==="archived")throw domainErrors.archived();if(current.version!==expectedVersion)throw domainErrors.conflict();const archived=await this.repository.archive(db,actor.tenantId,actor.id,id,expectedVersion);if(!archived)throw domainErrors.conflict();await this.audit(db,actor,"project.archived",id,{previousVersion:current.version,newVersion:archived.version,previousStatus:current.status});return archived;});}catch(error){await this.recordFailure(actor,error,id);throw error;}}
  async transitionProject(actor:ProjectActor,id:string,action:ProjectLifecycleAction,expectedVersion:number):Promise<Project>{await this.authorize(actor,assertCanTransitionProject,action,id);if(!Number.isInteger(expectedVersion)||expectedVersion<1)throw domainErrors.validation("expectedVersion must be a positive integer");try{return await inTenantTransaction(this.pool,actor.tenantId,async db=>{const current=await this.repository.findById(db,actor.tenantId,id);if(!current)throw domainErrors.notFound();if(current.archivedAt||current.status==="archived")throw domainErrors.archived();if(current.version!==expectedVersion)throw domainErrors.conflict();const next=lifecycleTransition(action,current.status);const updated=await this.repository.transition(db,actor.tenantId,actor.id,id,expectedVersion,current.status,next);if(!updated)throw domainErrors.conflict();const event={plan:"project.planned",start:"project.started",pause:"project.paused",resume:"project.resumed",complete:"project.completed",cancel:"project.cancelled"}[action];await this.audit(db,actor,event,id,{from:current.status,to:next,previousVersion:current.version,newVersion:updated.version});return updated;});}catch(error){await this.recordFailure(actor,error,id);throw error;}}
  planProject(actor:ProjectActor,id:string,expectedVersion:number){return this.transitionProject(actor,id,"plan",expectedVersion);}
  startProject(actor:ProjectActor,id:string,expectedVersion:number){return this.transitionProject(actor,id,"start",expectedVersion);}
  pauseProject(actor:ProjectActor,id:string,expectedVersion:number){return this.transitionProject(actor,id,"pause",expectedVersion);}
  resumeProject(actor:ProjectActor,id:string,expectedVersion:number){return this.transitionProject(actor,id,"resume",expectedVersion);}
  completeProject(actor:ProjectActor,id:string,expectedVersion:number){return this.transitionProject(actor,id,"complete",expectedVersion);}
  cancelProject(actor:ProjectActor,id:string,expectedVersion:number){return this.transitionProject(actor,id,"cancel",expectedVersion);}
}
