import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";
import {ApiError,api,apiErrorMessage,auth,mergeNotifications} from "./api.js";
import {ProjectFinancialSummarySchema} from "@odls/contracts";

const session={accessToken:"access",refreshToken:"refresh",user:{id:"user",email:"user@example.com",displayName:"User"},permissions:[]};
const ok=(data:unknown={id:"entity",version:2})=>new Response(JSON.stringify({data}),{status:200,headers:{"content-type":"application/json"}});
describe("Web API concurrency contracts",()=>{
  beforeEach(()=>{auth.set(session);vi.stubGlobal("fetch",vi.fn(async()=>ok()));});
  afterEach(()=>{auth.set(null);vi.unstubAllGlobals();});
  const body=()=>JSON.parse(String((vi.mocked(fetch).mock.calls.at(-1)?.[1] as RequestInit).body));
  it("includes expectedVersion in Client and Property archive requests",async()=>{await api.archive("clients","client",4);expect(body()).toEqual({expectedVersion:4});await api.archive("properties","property",5);expect(body()).toEqual({expectedVersion:5});});
  it("implements the Project archive contract",async()=>{await api.archive("projects","project",6);expect(vi.mocked(fetch).mock.calls.at(-1)?.[0]).toContain("/projects/project");expect(body()).toEqual({expectedVersion:6});});
  it("implements the Task archive contract",async()=>{await api.archive("tasks","task",7);expect(body()).toEqual({expectedVersion:7});});
  it("includes expectedVersion in lifecycle requests",async()=>{await api.projectLifecycle("project","start",8);expect(body()).toEqual({expectedVersion:8});await api.taskLifecycle("task","complete",9);expect(body()).toEqual({expectedVersion:9});});
  it("implements assignment and unassignment contracts",async()=>{await api.assign("task","user",10);expect(body()).toEqual({userId:"user",expectedVersion:10});await api.unassign("task","user",11);expect((vi.mocked(fetch).mock.calls.at(-1)?.[1] as RequestInit).method).toBe("DELETE");expect(body()).toEqual({expectedVersion:11});});
  it("parses structured conflicts and asks the user to reload",async()=>{vi.stubGlobal("fetch",vi.fn(async()=>new Response(JSON.stringify({error:{code:"VERSION_CONFLICT",correlationId:"correlation",details:{}}}),{status:409,headers:{"content-type":"application/json"}})));const error=await api.archive("tasks","task",1).catch(problem=>problem);expect(error).toBeInstanceOf(ApiError);expect(error).toMatchObject({status:409,code:"VERSION_CONFLICT",correlationId:"correlation"});expect(apiErrorMessage(error)).toContain("Reload");});
  it("sends Invoice create, update and lifecycle payloads",async()=>{const create={clientId:"00000000-0000-4000-8000-000000000041",invoiceNumber:"I-1",currencyCode:"EUR",netAmount:"1.0000",vatRate:"0.0000"};await api.createInvoice(create);expect(body()).toEqual(create);await api.updateInvoice("invoice",{expectedVersion:2,notes:"edit"});expect(body()).toEqual({expectedVersion:2,notes:"edit"});await api.invoiceAction("invoice","issue",3);expect(body()).toEqual({expectedVersion:3});await api.invoiceAction("invoice","cancel",4);expect(body()).toEqual({expectedVersion:4});await api.archiveInvoice("invoice",5);expect(body()).toEqual({expectedVersion:5});});
  it("sends Payment create, allocation, reverse and archive payloads",async()=>{const create={clientId:"client",reference:"P-1",currencyCode:"EUR",amount:"1.0000",paymentDate:"2026-01-01"};await api.createPayment(create);expect(body()).toEqual(create);await api.allocatePayment("payment","invoice","0.5000",2);expect(body()).toEqual({invoiceId:"invoice",amount:"0.5000",expectedVersion:2});await api.reversePayment("payment",3);expect(body()).toEqual({expectedVersion:3});await api.archivePayment("payment",4);expect(body()).toEqual({expectedVersion:4});});
  it("sends Expense create, update and lifecycle payloads",async()=>{const create={supplier:"Supplier",category:"x",expenseDate:"2026-01-01",currencyCode:"EUR",netAmount:"1.0000",vatRate:"0.0000"};await api.createExpense(create);expect(body()).toEqual(create);await api.updateExpense("expense",{expectedVersion:2,notes:"edit"});expect(body()).toEqual({expectedVersion:2,notes:"edit"});await api.expenseAction("expense","approve",3);expect(body()).toEqual({expectedVersion:3});await api.expenseAction("expense","reject",4);expect(body()).toEqual({expectedVersion:4});await api.archiveExpense("expense",5);expect(body()).toEqual({expectedVersion:5});});
  it("accepts signed margins and null zero-revenue percentage",()=>{const base={projectId:"00000000-0000-4000-8000-000000000071",currencyCode:"EUR",budget:null,invoicedNet:"0",invoicedVat:"0",invoicedGross:"0",paid:"0",outstanding:"0",expenses:"10.0000",grossMarginAmount:"-10.0000",grossMarginPercentage:null,overdueInvoiceCount:0,overdueInvoiceAmount:"0"};expect(ProjectFinancialSummarySchema.parse(base).grossMarginAmount).toBe("-10.0000");expect(()=>ProjectFinancialSummarySchema.parse({...base,invoicedGross:"10.0000",grossMarginPercentage:"-25.0000"})).not.toThrow();});
  it("sends protected Document metadata mutations",async()=>{await api.updateDocument("document",{expectedVersion:4,description:"changed"});expect(body()).toEqual({expectedVersion:4,description:"changed"});await api.archiveDocument("document",5);expect(body()).toEqual({expectedVersion:5});});
  it("uses multipart for Document uploads without forcing JSON content type",async()=>{const file=new File(["%PDF-1.4"],"safe.pdf",{type:"application/pdf"});await api.uploadDocument(file,{category:"contract",description:"safe",entityType:"project",entityId:"00000000-0000-4000-8000-000000000071"});const init=vi.mocked(fetch).mock.calls.at(-1)?.[1] as RequestInit;expect(init.body).toBeInstanceOf(FormData);expect(new Headers(init.headers).has("content-type")).toBe(false);await api.uploadDocumentVersion("document",file,6);const form=(vi.mocked(fetch).mock.calls.at(-1)?.[1] as RequestInit).body as FormData;expect(form.get("expectedVersion")).toBe("6");});
  it("sends read, unread, archive and preference concurrency payloads",async()=>{const notification={id:"00000000-0000-4000-8000-000000000101",tenantId:"00000000-0000-4000-8000-000000000001",recipientUserId:"00000000-0000-4000-8000-000000000012",eventType:"task.assigned",title:"Assigned",body:"Body",severity:"info",entityType:"task",entityId:"00000000-0000-4000-8000-000000000081",actionUrl:"/tasks/x",status:"read",readAt:"2026-01-01T00:00:00Z",expiresAt:null,deduplicationKey:"key",sourceEventId:"00000000-0000-4000-8000-000000000102",metadata:{},version:5,createdAt:"2026-01-01T00:00:00Z",updatedAt:"2026-01-01T00:00:00Z"},preferences={tenantId:notification.tenantId,userId:notification.recipientUserId,inAppEnabled:true,taskEventsEnabled:true,projectEventsEnabled:true,financeEventsEnabled:true,documentEventsEnabled:true,dueSoonEnabled:false,overdueEnabled:true,selfNotificationsEnabled:false,version:8,createdAt:notification.createdAt,updatedAt:notification.updatedAt};vi.stubGlobal("fetch",vi.fn(async(input)=>ok(String(input).includes("notification-preferences")?preferences:notification)));await api.notificationState(notification.id,"read",4);expect(body()).toEqual({expectedVersion:4});await api.notificationState(notification.id,"unread",5);expect(body()).toEqual({expectedVersion:5});await api.notificationState(notification.id,"archive",6);expect((vi.mocked(fetch).mock.calls.at(-1)?.[1] as RequestInit).method).toBe("DELETE");expect(body()).toEqual({expectedVersion:6});await api.updateNotificationPreferences({expectedVersion:7,dueSoonEnabled:false});expect(body()).toEqual({expectedVersion:7,dueSoonEnabled:false});});
  it("parses unread counts and rejects malformed notification lists",async()=>{vi.stubGlobal("fetch",vi.fn(async()=>ok({count:3})));await expect(api.unreadCount()).resolves.toEqual({count:3});vi.stubGlobal("fetch",vi.fn(async()=>ok([{id:"bad"}])));await expect(api.notifications()).rejects.toBeTruthy();});
  it("merges polling rows without duplicates and replaces response versions",()=>{const row:any={id:"00000000-0000-4000-8000-000000000101",createdAt:"2026-01-01T00:00:00Z",version:1},next={...row,version:2,status:"read"};expect(mergeNotifications([row],[next])).toEqual([next]);expect(mergeNotifications([row],[row,row])).toHaveLength(1);});
  it("requests dashboard ranges and allowlisted reports",async()=>{await api.dashboard(90);expect(vi.mocked(fetch).mock.calls.at(-1)?.[0]).toContain("/dashboard/executive?range=90");await api.projectHealth();expect(vi.mocked(fetch).mock.calls.at(-1)?.[0]).toContain("/dashboard/project-health");await api.report("workload","range=7&page=2");expect(vi.mocked(fetch).mock.calls.at(-1)?.[0]).toContain("/reports/workload?range=7&page=2");});
  it("downloads authenticated CSV and preserves disposition",async()=>{vi.stubGlobal("fetch",vi.fn(async()=>new Response("a,b\\r\\n1,2",{status:200,headers:{"content-type":"text/csv","content-disposition":'attachment; filename="workload.csv"'}})));const result=await api.exportReport("workload");expect(result.disposition).toContain("workload.csv");expect(await result.blob.text()).toContain("a,b");expect(new Headers(vi.mocked(fetch).mock.calls[0][1]?.headers).get("authorization")).toBe("Bearer access");});
});
