import {useEffect,useRef,useState,type JSX} from "react";
import type {DocumentContract,ExpenseContract,InvoiceContract,MaterialCategoryContract,MaterialCategoryNodeContract,MaterialContract,MeasurementUnitContract,NotificationContract,NotificationPreferencesContract,PaymentContract,PriceListContract,PriceListItemContract,ProjectContract,ProjectFinancialSummary,TaskContract,WorkCategoryContract,WorkCategoryNodeContract,WorkItemContract} from "@odls/contracts";
import {api,apiErrorMessage,auth,mergeNotifications,type EntityByResource,type ProjectAction,type ReportName,type Resource,type Session,type TaskAction} from "./api.js";

type Page=Resource|"dashboard"|"reports"|"finance"|"documents"|"notifications"|"measurement-units"|"work-catalog"|"material-catalog"|"price-lists";
const nav:Array<[string,Page]>=[["Dashboard","dashboard"],["Reports","reports"],["Measurement Units","measurement-units"],["Construction Work Catalog","work-catalog"],["Material Catalog","material-catalog"],["Price Lists","price-lists"],["Clients","clients"],["Properties","properties"],["Projects","projects"],["Tasks","tasks"],["Finance","finance"],["Documents","documents"]];
const can=(session:Session|null,permission:string)=>Boolean(session?.permissions.includes(permission));
const projectActions:Record<ProjectContract["status"],ProjectAction[]>={draft:["plan","cancel"],planned:["start","cancel"],active:["pause","complete","cancel"],paused:["resume","cancel"],completed:[],cancelled:[],archived:[]};
const taskActions:Record<TaskContract["status"],TaskAction[]>={todo:["start","block","cancel"],in_progress:["block","complete","cancel"],blocked:["resume","cancel"],completed:[],cancelled:[],archived:[]};
const titleCase=(value:string)=>value.charAt(0).toUpperCase()+value.slice(1);
const singular:Record<Resource,string>={clients:"client",properties:"property",projects:"project",tasks:"task"};

export function Brand({surface="light",compact=false}:{surface?:"light"|"dark";compact?:boolean}){
  const src=compact?"/brand/omnira-symbol.svg":`/brand/omnira-logo-${surface}.svg`;
  return <div className={`brand ${compact?"brand-compact":""}`}><img src={src} alt="OMNIRA"/>{!compact&&<span>AI Business Operating System</span>}</div>;
}

function PriceListsPage({session}:{session:Session}){
 const [lists,setLists]=useState<PriceListContract[]>([]),[items,setItems]=useState<PriceListItemContract[]>([]),[materials,setMaterials]=useState<MaterialContract[]>([]),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[currency,setCurrency]=useState(""),[validOn,setValidOn]=useState(""),[page,setPage]=useState(1),[totalPages,setTotalPages]=useState(1),[selectedList,setSelectedList]=useState(""),[error,setError]=useState("");
 const [code,setCode]=useState(""),[name,setName]=useState(""),[country,setCountry]=useState("PL"),[listCurrency,setListCurrency]=useState("EUR"),[region,setRegion]=useState(""),[from,setFrom]=useState("2026-01-01"),[to,setTo]=useState("2026-12-31");
 const [materialId,setMaterialId]=useState(""),[unitPrice,setUnitPrice]=useState("0.0000"),[vatRate,setVatRate]=useState("23.0000"),[discount,setDiscount]=useState("0.0000"),[selectedItem,setSelectedItem]=useState<PriceListItemContract|null>(null);
 const fail=(x:unknown)=>setError(apiErrorMessage(x)),query=()=>{const p=new URLSearchParams({page:String(page),pageSize:"10",sortBy:"code",sortOrder:"asc"});if(search)p.set("search",search);if(status)p.set("active",status);if(currency)p.set("currency",currency);if(validOn)p.set("validOn",validOn);return p.toString();};
 const load=async()=>{try{const [l,i]=await Promise.all([api.priceLists(query()),api.priceListItems(`page=1&pageSize=100&sortBy=material&sortOrder=asc${selectedList?`&priceListId=${selectedList}`:""}`)]);setLists(l.data);setItems(i.data);setTotalPages(l.pagination.totalPages);setError("");}catch(x){fail(x);}};
 useEffect(()=>{void api.materials("page=1&pageSize=100&active=true&sortBy=code&sortOrder=asc").then(r=>{setMaterials(r.data);setMaterialId(x=>x||r.data[0]?.id||"");}).catch(fail);},[]);
 useEffect(()=>{void load();},[page,search,status,currency,validOn,selectedList]);
 const createList=async(e:React.FormEvent)=>{e.preventDefault();try{await api.createPriceList({code,displayName:name,currency:listCurrency,country,region:region||undefined,validFrom:from,validTo:to||null});setCode("");setName("");await load();}catch(x){fail(x);}};
 const createItem=async(e:React.FormEvent)=>{e.preventDefault();try{await api.createPriceListItem({priceListId:selectedList,materialId,unitPrice,vatRate,discountPercent:discount,currency:lists.find(x=>x.id===selectedList)?.currency??listCurrency,validFrom:from,validTo:to||null});await load();}catch(x){fail(x);}};
 const saveItem=async(e:React.FormEvent)=>{e.preventDefault();if(!selectedItem)return;try{await api.updatePriceListItem(selectedItem.id,{expectedVersion:selectedItem.version,unitPrice,vatRate,discountPercent:discount,validFrom:from,validTo:to||null});setSelectedItem(null);await load();}catch(x){fail(x);}};
 const writable=can(session,"price_list.update");
 return <section><h2>Price Lists</h2>{error&&<p role="alert">{error}</p>}<div className="toolbar"><label>Search price lists<input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></label><label>Currency selector<select value={currency} onChange={e=>setCurrency(e.target.value)}><option value="">All currencies</option>{["EUR","PLN","USD","GBP"].map(x=><option key={x}>{x}</option>)}</select></label><label>Price list status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="true">Active</option><option value="false">Inactive</option></select></label><label>Valid on<input type="date" value={validOn} onChange={e=>setValidOn(e.target.value)}/></label></div>
 {lists.length?<table><thead><tr><th>Code</th><th>Name</th><th>Market</th><th>Currency</th><th>Validity</th><th>Status</th><th>Actions</th></tr></thead><tbody>{lists.map(x=><tr key={x.id}><td>{x.code}</td><td>{x.displayName}</td><td>{x.country}{x.region?` · ${x.region}`:""}</td><td>{x.currency}</td><td>{String(x.validFrom)} – {x.validTo?String(x.validTo):"Open"}</td><td>{x.status}</td><td><button onClick={()=>setSelectedList(x.id)}>View items</button>{writable&&<button onClick={()=>void api.priceListStatus(x.id,x.status==="active"?"inactive":"active",x.version).then(load).catch(fail)}>{x.status==="active"?"Deactivate":"Activate"}</button>}</td></tr>)}</tbody></table>:<p>No price lists found.</p>}
 <nav className="pagination" aria-label="Price list pagination"><button disabled={page<=1} onClick={()=>setPage(x=>x-1)}>Previous</button><span>Page {page} of {totalPages}</span><button disabled={page>=totalPages} onClick={()=>setPage(x=>x+1)}>Next</button></nav>
 {can(session,"price_list.create")&&<form onSubmit={createList}><h3>Create price list</h3><label>Price list code<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} required/></label><label>Price list name<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>Country<input value={country} maxLength={2} onChange={e=>setCountry(e.target.value.toUpperCase())} required/></label><label>Currency<select value={listCurrency} onChange={e=>setListCurrency(e.target.value)}>{["EUR","PLN","USD","GBP"].map(x=><option key={x}>{x}</option>)}</select></label><label>Region<input value={region} onChange={e=>setRegion(e.target.value)}/></label><label>Valid from<input type="date" value={from} onChange={e=>setFrom(e.target.value)} required/></label><label>Valid to<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button>Create price list</button></form>}
 <h3>Price List Items</h3><label>Price list selector<select value={selectedList} onChange={e=>setSelectedList(e.target.value)}><option value="">All price lists</option>{lists.map(x=><option key={x.id} value={x.id}>{x.code} — {x.displayName}</option>)}</select></label>
 {items.length?<table><thead><tr><th>Material</th><th>Unit price</th><th>VAT</th><th>Discount</th><th>Validity</th><th>Status</th><th>Actions</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.materialCode} — {x.materialName}</td><td>{x.unitPrice} {x.currency}</td><td>{x.vatRate}%</td><td>{x.discountPercent}%</td><td>{String(x.validFrom)} – {x.validTo?String(x.validTo):"Open"}</td><td>{x.status}</td><td>{writable&&<><button onClick={()=>{setSelectedItem(x);setUnitPrice(x.unitPrice);setVatRate(x.vatRate);setDiscount(x.discountPercent);setFrom(String(x.validFrom).slice(0,10));setTo(x.validTo?String(x.validTo).slice(0,10):"");}}>Edit price</button><button onClick={()=>void api.priceListItemStatus(x.id,x.status==="active"?"inactive":"active",x.version).then(load).catch(fail)}>{x.status==="active"?"Deactivate":"Activate"}</button></>}</td></tr>)}</tbody></table>:<p>No price list items found.</p>}
 {can(session,"price_list.create")&&selectedList&&<form onSubmit={createItem}><h4>Add price list item</h4><label>Material selector<select value={materialId} onChange={e=>setMaterialId(e.target.value)} required>{materials.map(x=><option key={x.id} value={x.id}>{x.code} — {x.displayName}</option>)}</select></label><label>Unit price<input inputMode="decimal" value={unitPrice} onChange={e=>setUnitPrice(e.target.value)} required/></label><label>VAT rate<input inputMode="decimal" value={vatRate} onChange={e=>setVatRate(e.target.value)} required/></label><label>Discount percent<input inputMode="decimal" value={discount} onChange={e=>setDiscount(e.target.value)} required/></label><button>Add price</button></form>}
 {selectedItem&&writable&&<form onSubmit={saveItem}><h4>Edit price for {selectedItem.materialCode}</h4><label>Edit unit price<input value={unitPrice} onChange={e=>setUnitPrice(e.target.value)} required/></label><label>Edit VAT rate<input value={vatRate} onChange={e=>setVatRate(e.target.value)} required/></label><label>Edit discount percent<input value={discount} onChange={e=>setDiscount(e.target.value)} required/></label><button>Save price</button></form>}</section>;
}

export function Login({onLogin}:{onLogin:(session:Session)=>void}){
  const [tenant,setTenant]=useState("demo"),[email,setEmail]=useState("admin@demo.odls"),[password,setPassword]=useState("DemoPassword!2026"),[error,setError]=useState("");
  const submit=async(event:React.FormEvent)=>{event.preventDefault();try{const result=await api.login(tenant,email,password);auth.set(result);onLogin(result);}catch{setError("Sign-in failed. Check tenant, email, and password.");}};
  return <main className="login"><form onSubmit={submit}><Brand/><p className="slogan">One platform. Every business.</p><h1 className="sr-only">Sign in to OMNIRA</h1><label>Tenant<input value={tenant} onChange={event=>setTenant(event.target.value)} required/></label><label>Email<input type="email" value={email} onChange={event=>setEmail(event.target.value)} required/></label><label>Password<input type="password" value={password} onChange={event=>setPassword(event.target.value)} required/></label>{error&&<p role="alert">{error}</p>}<button>Sign in</button></form></main>;
}

function ResourcePage<R extends Resource>({resource,session,focusId}:{resource:R;session:Session;focusId?:string}){
  const [items,setItems]=useState<EntityByResource[R][]>([]),[search,setSearch]=useState(""),[error,setError]=useState(""),[name,setName]=useState(""),[editValue,setEditValue]=useState(""),[assigneeId,setAssigneeId]=useState("00000000-0000-4000-8000-000000000012");
  const load=async()=>{try{const listed=await api.list(resource,search);setItems(current=>{const focused=current.find(item=>item.id===focusId);return focused&&!listed.some(item=>item.id===focused.id)?[focused,...listed]:listed;});setError("");}catch(problem){setError(apiErrorMessage(problem));}};
  useEffect(()=>{void load();},[resource]);
  const replace=(entity:EntityByResource[R])=>{setItems(current=>current.map(item=>item.id===entity.id?entity:item));setError("");};
  const fail=(problem:unknown)=>setError(apiErrorMessage(problem));
  useEffect(()=>{if(focusId)void api.get(resource,focusId).then(entity=>setItems(current=>current.some(item=>item.id===entity.id)?current:[entity,...current])).catch(fail);},[resource,focusId]);
  const create=async(event:React.FormEvent)=>{event.preventDefault();try{
    let created:EntityByResource[R];
    if(resource==="clients")created=await api.create("clients",{name}) as EntityByResource[R];
    else if(resource==="properties")created=await api.create("properties",{name,clientId:"00000000-0000-4000-8000-000000000041",propertyType:"commercial",address:{line1:"New address",city:"Warsaw",countryCode:"PL"}}) as EntityByResource[R];
    else if(resource==="projects")created=await api.create("projects",{projectNumber:`WEB-${Date.now()}`,name,clientId:"00000000-0000-4000-8000-000000000041",propertyId:"00000000-0000-4000-8000-000000000061",financialOwnerLegalEntityId:"00000000-0000-4000-8000-000000000021",currencyCode:"EUR"}) as EntityByResource[R];
    else created=await api.create("tasks",{title:name,projectId:"00000000-0000-4000-8000-000000000071"}) as EntityByResource[R];
    setItems(current=>[created,...current]);setName("");setError("");
  }catch(problem){fail(problem);}};
  const edit=async(item:EntityByResource[R])=>{const next=editValue.trim();if(!next){setError("Enter a new value before editing.");return;}try{
    if(resource==="clients")replace(await api.update("clients",item.id,{expectedVersion:item.version,name:next}) as EntityByResource[R]);
    else if(resource==="properties")replace(await api.update("properties",item.id,{expectedVersion:item.version,name:next}) as EntityByResource[R]);
    else if(resource==="projects")replace(await api.update("projects",item.id,{expectedVersion:item.version,name:next}) as EntityByResource[R]);
    else replace(await api.update("tasks",item.id,{expectedVersion:item.version,title:next}) as EntityByResource[R]);
    setEditValue("");
  }catch(problem){fail(problem);}};
  const archive=async(item:EntityByResource[R])=>{try{replace(await api.archive(resource,item.id,item.version));}catch(problem){fail(problem);}};
  const projectLifecycle=async(item:ProjectContract,action:ProjectAction)=>{try{replace(await api.projectLifecycle(item.id,action,item.version) as EntityByResource[R]);}catch(problem){fail(problem);}};
  const taskLifecycle=async(item:TaskContract,action:TaskAction)=>{try{replace(await api.taskLifecycle(item.id,action,item.version) as EntityByResource[R]);}catch(problem){fail(problem);}};
  const assign=async(item:TaskContract)=>{try{replace(await api.assign(item.id,assigneeId,item.version) as EntityByResource[R]);}catch(problem){fail(problem);}};
  const unassign=async(item:TaskContract,userId:string)=>{try{replace(await api.unassign(item.id,userId,item.version) as EntityByResource[R]);}catch(problem){fail(problem);}};
  return <section><h2>{titleCase(resource)}</h2><div className="toolbar"><input aria-label={`Search ${resource}`} placeholder="Search" value={search} onChange={event=>setSearch(event.target.value)}/><button onClick={()=>void load()}>Search</button><button onClick={()=>void load()}>Reload</button>{can(session,`${resource}.update`)&&<input aria-label="Edit value" placeholder="New name or title" value={editValue} onChange={event=>setEditValue(event.target.value)}/>} {resource==="tasks"&&can(session,"tasks.assign")&&<input aria-label="Assignee user ID" value={assigneeId} onChange={event=>setAssigneeId(event.target.value)}/>}</div>
    {can(session,`${resource}.create`)&&<form onSubmit={create}><label>New {singular[resource]}<input value={name} onChange={event=>setName(event.target.value)} required/></label><button>Create</button></form>}
    {error&&<p role="alert">{error}</p>}
    {items.length===0?<p>No {resource} found.</p>:<ul>{items.map(item=><li key={item.id} data-version={item.version} data-entity-id={item.id} aria-current={focusId===item.id?"true":undefined} className={focusId===item.id?"focused-record":undefined}><div><strong>{"title" in item?item.title:item.name}</strong> — {item.status} <small>version {item.version}</small></div><div className="actions">
      {item.status!=="archived"&&can(session,`${resource}.update`)&&<button onClick={()=>void edit(item)}>Edit</button>}
      {resource==="projects"&&can(session,"projects.update")&&projectActions[(item as ProjectContract).status].map(action=><button key={action} onClick={()=>void projectLifecycle(item as ProjectContract,action)}>{titleCase(action)} Project</button>)}
      {resource==="tasks"&&can(session,"tasks.update")&&taskActions[(item as TaskContract).status].map(action=><button key={action} onClick={()=>void taskLifecycle(item as TaskContract,action)}>{titleCase(action)} Task</button>)}
      {resource==="tasks"&&["todo","in_progress","blocked"].includes(item.status)&&can(session,"tasks.update")&&can(session,"tasks.assign")&&<button onClick={()=>void assign(item as TaskContract)}>Assign Task</button>}
      {resource==="tasks"&&["todo","in_progress","blocked"].includes(item.status)&&can(session,"tasks.update")&&can(session,"tasks.assign")&&(item as TaskContract).assignees?.map(assignee=><button key={assignee.userId} onClick={()=>void unassign(item as TaskContract,assignee.userId)}>Unassign {assignee.displayName}</button>)}
      {item.status!=="archived"&&can(session,`${resource}.delete`)&&<button onClick={()=>void archive(item)}>Archive</button>}
    </div></li>)}</ul>}
  </section>;
}

function Bars({title,rows}:{title:string;rows:Array<{label:string;value:number|string;series?:string}>}){
 const max=Math.max(0,...rows.map(x=>Math.abs(Number(x.value))));return <figure className="chart" aria-label={title}><figcaption><strong>{title}</strong></figcaption>{rows.length===0?<p>No chart data.</p>:rows.map((x,i)=><div className="bar-row" key={`${x.series}-${x.label}`}><span>{x.label}{x.series?` (${x.series})`:""}</span><span className="bar-track"><span className={`bar-fill bar-${i%4}`} style={{width:`${max?Math.max(2,Math.abs(Number(x.value))/max*100):0}%`}}/></span><strong>{x.value}</strong></div>)}</figure>;
}

function Dashboard({session}:{session:Session}){
  const [range,setRange]=useState(30),[data,setData]=useState<any>(null),[health,setHealth]=useState<any[]>([]),[revenue,setRevenue]=useState<any[]>([]),[expenses,setExpenses]=useState<any[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true);
  const load=async()=>{setLoading(true);try{const finance=can(session,"finance.read")&&can(session,"reports.read"),[summary,projects,revenueRows,expenseRows]=await Promise.all([api.dashboard(range),can(session,"projects.read")?api.projectHealth():Promise.resolve([]),finance?api.report("revenue",`range=${range}&groupBy=month&pageSize=100`):Promise.resolve({data:[]}),finance?api.report("expenses",`range=${range}&groupBy=month&pageSize=100`):Promise.resolve({data:[]})]);setData(summary);setHealth(projects);setRevenue(revenueRows.data);setExpenses(expenseRows.data);setError("");}catch(x){setError(apiErrorMessage(x));}finally{setLoading(false);}};
  useEffect(()=>{void load();},[range]);
  const healthCounts=Object.entries(health.reduce((a:any,x:any)=>({...a,[x.health.state]:(a[x.health.state]??0)+1}),{})).map(([label,value])=>({label,value:Number(value)})),tasks=data?.tasks?[["Todo",data.tasks.open],["In progress",data.tasks.in_progress],["Blocked",data.tasks.blocked],["Completed",data.tasks.completed]].map(([label,value])=>({label:String(label),value:Number(value)})):[];
  return <section><h2>Executive Dashboard</h2><div className="toolbar"><label>Date range<select aria-label="Dashboard date range" value={range} onChange={e=>setRange(Number(e.target.value))}>{[7,30,90].map(x=><option key={x} value={x}>{x} days</option>)}</select></label><button disabled={loading} onClick={()=>void load()}>Refresh dashboard</button></div>{error&&<p role="alert">{error}</p>}{loading?<p>Loading dashboard…</p>:!data?<p>No dashboard data.</p>:<><p>UTC reporting period: {data.range.start} to {data.range.endExclusive} (exclusive)</p><div className="cards">{data.projects&&<><p>Active projects: {data.projects.active}</p><p>Overdue projects: {data.projects.overdue}</p></>}{data.tasks&&<><p>Open tasks: {data.tasks.open}</p><p>Blocked tasks: {data.tasks.blocked}</p><p>Overdue tasks: {data.tasks.overdue}</p></>}<p>Unread notifications: {data.unread_notifications}</p></div><div className="chart-grid"><Bars title="Task status distribution" rows={tasks}/><Bars title="Project health distribution" rows={healthCounts}/><Bars title="Revenue by month and currency" rows={revenue.map(x=>({label:x.group,value:x.grossInvoiced,series:x.currencyCode}))}/><Bars title="Expenses by month and currency" rows={expenses.map(x=>({label:x.group,value:x.amount,series:x.currencyCode}))}/></div>{data.finance&&<><h3>Finance by currency</h3>{data.finance.length===0?<p>No finance activity.</p>:<table><thead><tr><th>Currency</th><th>Invoiced</th><th>Paid</th><th>Outstanding</th><th>Margin</th></tr></thead><tbody>{data.finance.map((x:any)=><tr key={x.currencyCode}><td>{x.currencyCode}</td><td>{x.invoicedGross}</td><td>{x.paid}</td><td>{x.outstanding}</td><td>{x.grossMargin}</td></tr>)}</tbody></table>}</>}<h3>Project health</h3>{health.length===0?<p>No authorized projects.</p>:<table><thead><tr><th>Project</th><th>State</th><th>Score</th><th>Reasons</th></tr></thead><tbody>{health.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.health.state}</td><td>{x.health.score}</td><td>{x.health.reasons.join(", ")}</td></tr>)}</tbody></table>}{data.documents&&<><h3>Documents and operations</h3><p>Recent uploads: {data.documents.recent}; created in period: {data.documents.created}</p></>}{data.operations&&<p>Operational warnings: {data.operations.dead_letters} dead letters, {data.operations.failed} failed deliveries.</p>}</>}</section>;
}

const reportSorts:Record<ReportName,string[]>={"accounts-receivable":["invoiceNumber","clientName","projectName","issueDate","dueDate","outstanding","status"],profitability:["projectName","margin","marginPercentage","outstanding"],deadlines:["title","projectName","dueDate","bucket"],workload:["displayName","openCount","overdueCount"],documents:["filename","category","createdAt"],activity:["occurredAt","action","actorName"]};
export const nextReportSort=(active:string,direction:"asc"|"desc",column:string)=>active===column?{sortBy:column,sortOrder:direction==="asc"?"desc" as const:"asc" as const}:{sortBy:column,sortOrder:"asc" as const};
export const chartSeries=(rows:any[],value:string)=>rows.map(x=>({label:String(x.group),value:String(x[value]),series:String(x.currencyCode)}));
export const relatedReportPage=(column:string):Page|null=>column==="invoiceNumber"?"finance":column==="clientName"?"clients":column==="projectName"?"projects":column==="title"?"tasks":column==="filename"?"documents":null;
function Reports({session,onNavigate}:{session:Session;onNavigate:(page:Page,id?:string)=>void}){
 const available:ReportName[]=[...(can(session,"finance.read")?["accounts-receivable","profitability"] as ReportName[]:[]),...(can(session,"tasks.read")?["deadlines","workload"] as ReportName[]:[]),...(can(session,"documents.read")?["documents"] as ReportName[]:[]),...(can(session,"operational_metrics.read")?["activity" as const]:[])],[name,setName]=useState<ReportName>(available[0]),[range,setRange]=useState(30),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(10),[sortBy,setSortBy]=useState(reportSorts[available[0]][0]),[sortOrder,setSortOrder]=useState<"asc"|"desc">("asc"),[clientId,setClientId]=useState(""),[projectId,setProjectId]=useState(""),[currency,setCurrency]=useState(""),[overdue,setOverdue]=useState(false),[clients,setClients]=useState<Array<{id:string;name:string}>>([]),[projects,setProjects]=useState<Array<{id:string;name:string}>>([]),[currencies,setCurrencies]=useState<string[]>([]),[result,setResult]=useState<any>({data:[],pagination:{page:1,pageSize:10,total:0,totalPages:0}}),[error,setError]=useState(""),[loading,setLoading]=useState(false);
 useEffect(()=>{void Promise.all([can(session,"clients.read")?api.list("clients"):Promise.resolve([]),can(session,"projects.read")?api.list("projects"):Promise.resolve([]),api.dashboard(30)]).then(([c,p,d])=>{setClients(c);setProjects(p);setCurrencies((d.finance??[]).map((x:any)=>x.currencyCode));}).catch(x=>setError(apiErrorMessage(x)));},[]);
 const supportsClient=name==="accounts-receivable",supportsProject=["accounts-receivable","profitability","deadlines","workload","documents"].includes(name),supportsCurrency=["accounts-receivable","profitability"].includes(name);
 const query=()=>{const params=new URLSearchParams({range:String(range),page:String(page),pageSize:String(pageSize),sortBy,sortOrder});if(supportsClient&&clientId)params.set("clientId",clientId);if(supportsProject&&projectId)params.set("projectId",projectId);if(supportsCurrency&&currency)params.set("currencyCode",currency);if(name==="accounts-receivable"&&overdue)params.set("overdue","true");return params.toString();};
 const load=async()=>{setLoading(true);try{setResult(await api.report(name,query()));setError("");}catch(x){setError(apiErrorMessage(x));}finally{setLoading(false);}};
 useEffect(()=>{void load();},[name,range,page,pageSize,sortBy,sortOrder,clientId,projectId,currency,overdue]);
 const reset=()=>setPage(1),changeReport=(next:ReportName)=>{setName(next);setSortBy(reportSorts[next][0]);setSortOrder("asc");setClientId("");setProjectId("");setCurrency("");setOverdue(false);reset();},sort=(column:string)=>{if(!reportSorts[name].includes(column))return;const next=nextReportSort(sortBy,sortOrder,column);setSortBy(next.sortBy);setSortOrder(next.sortOrder);reset();};
 const download=async()=>{try{const x=await api.exportReport(name,query()),url=URL.createObjectURL(x.blob),a=document.createElement("a");a.href=url;a.download=x.disposition?.match(/filename="([^"]+)"/)?.[1]??`${name}.csv`;a.click();URL.revokeObjectURL(url);}catch(x){setError(apiErrorMessage(x));}};
 const rows=result.data,columns=rows[0]?Object.keys(rows[0]).filter(x=>x!=="id"&&!["linkedEntities"].includes(x)&&(!x.endsWith("Id")||x==="userId")):[],link=(row:any,column:string)=>{const target=relatedReportPage(column),id=column==="invoiceNumber"?row.id:column==="clientName"?row.clientId:column==="projectName"?row.projectId:column==="title"?row.id:column==="filename"?row.id:null;return target&&id?<button className="link-button" data-entity-id={id} onClick={()=>onNavigate(target,id)}>{String(row[column])}</button>:row[column]===null?"—":String(row[column]);};
 return <section><h2>Operational Reports</h2><div className="toolbar"><label>Report<select aria-label="Report selector" value={name} onChange={e=>changeReport(e.target.value as ReportName)}>{available.map(x=><option key={x} value={x}>{x}</option>)}</select></label><label>Period<select aria-label="Report date range" value={range} onChange={e=>{setRange(Number(e.target.value));reset();}}>{[7,30,90].map(x=><option key={x} value={x}>{x} days</option>)}</select></label>{supportsClient&&<label>Client<select aria-label="Report client filter" value={clientId} onChange={e=>{setClientId(e.target.value);reset();}}><option value="">All clients</option>{clients.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}{supportsProject&&<label>Project<select aria-label="Report project filter" value={projectId} onChange={e=>{setProjectId(e.target.value);reset();}}><option value="">All projects</option>{projects.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}{supportsCurrency&&<label>Currency<select aria-label="Report currency filter" value={currency} onChange={e=>{setCurrency(e.target.value);reset();}}><option value="">All currencies</option>{currencies.map(x=><option key={x}>{x}</option>)}</select></label>}{name==="accounts-receivable"&&<label><input type="checkbox" checked={overdue} onChange={e=>{setOverdue(e.target.checked);reset();}}/>Overdue only</label>}<button disabled={loading} onClick={()=>void load()}>Refresh report</button><button onClick={()=>{setClientId("");setProjectId("");setCurrency("");setOverdue(false);reset();}}>Clear filters</button>{can(session,"reports.export")&&name!=="activity"&&<button disabled={loading} onClick={()=>void download()}>Download CSV</button>}</div>{error&&<p role="alert">{error}</p>}{loading?<p>Loading report…</p>:rows.length===0?<p>No report rows.</p>:<table><thead><tr>{columns.map(column=><th key={column}>{reportSorts[name].includes(column)?<button className="sort-button" aria-label={`Sort by ${column}`} aria-pressed={sortBy===column} onClick={()=>sort(column)}>{column}{sortBy===column?sortOrder==="asc"?" ↑":" ↓":""}</button>:column}</th>)}</tr></thead><tbody>{rows.map((row:any,i:number)=><tr key={row.id??row.projectId??row.userId??i}>{columns.map(column=><td key={column}>{link(row,column)}</td>)}</tr>)}</tbody></table>}{result.pagination.total>0&&<nav className="pagination" aria-label="Report pagination"><button disabled={loading||page<=1} onClick={()=>setPage(x=>x-1)}>Previous</button><span>Page {result.pagination.page} of {Math.max(1,result.pagination.totalPages)} · {result.pagination.total} rows</span><button disabled={loading||page>=result.pagination.totalPages} onClick={()=>setPage(x=>x+1)}>Next</button><label>Rows per page<select aria-label="Rows per page" value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));reset();}}>{[5,10,25,50].map(x=><option key={x}>{x}</option>)}</select></label></nav>}</section>;
}

function NotificationCenter({onNavigate,onUnread}:{onNavigate:(page:Page)=>void;onUnread:(count:number)=>void}){
 const [items,setItems]=useState<NotificationContract[]>([]),[status,setStatus]=useState(""),[severity,setSeverity]=useState(""),[error,setError]=useState(""),[preferences,setPreferences]=useState<NotificationPreferencesContract|null>(null);
 const query=`archived=${status==="archived"?"true":"false"}${status&&status!=="archived"?`&status=${status}`:""}${severity?`&severity=${severity}`:""}&pageSize=100`;
 const load=async(silent=false)=>{try{const [next,count,prefs]=await Promise.all([api.notifications(query),api.unreadCount(),preferences?Promise.resolve(preferences):api.notificationPreferences()]);setItems(current=>mergeNotifications(current.filter(x=>next.some(n=>n.id===x.id)),next));onUnread(count.count);setPreferences(prefs);setError("");}catch(problem){setError(`${silent?"Notification refresh failed. ":""}${apiErrorMessage(problem)}`);}};
 useEffect(()=>{void load();const interval=window.setInterval(()=>void load(true),Math.max(5000,Number(import.meta.env.VITE_NOTIFICATION_POLL_MS??15000)));return()=>window.clearInterval(interval);},[query]);
 const replace=(item:NotificationContract)=>{setItems(current=>current.map(x=>x.id===item.id?item:x).filter(x=>status==="archived"?x.status==="archived":x.status!=="archived"));void api.unreadCount().then(x=>onUnread(x.count));setError("");},change=(item:NotificationContract,state:"read"|"unread"|"archive")=>api.notificationState(item.id,state,item.version).then(replace).catch(x=>setError(apiErrorMessage(x)));
 const savePreferences=async()=>{if(!preferences)return;try{setPreferences(await api.updateNotificationPreferences({...preferences,expectedVersion:preferences.version}));setError("");}catch(x){setError(apiErrorMessage(x));}};
 return <section><h2>Notifications</h2>{error&&<p role="alert">{error}</p>}<div className="toolbar"><label>Status<select aria-label="Notification status filter" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Active</option><option value="unread">Unread</option><option value="read">Read</option><option value="archived">Archived</option></select></label><label>Severity<select aria-label="Notification severity filter" value={severity} onChange={e=>setSeverity(e.target.value)}><option value="">All</option>{["info","success","warning","critical"].map(x=><option key={x}>{x}</option>)}</select></label><button onClick={()=>void load()}>Refresh notifications</button><button onClick={()=>void api.markAllNotificationsRead().then(()=>load())}>Mark all read</button></div>
 {items.length===0?<p>No notifications found.</p>:<ul className="notifications">{items.map(item=><li key={item.id} className={item.status==="unread"?"notification-unread":""}><strong>{item.title}</strong><span>{item.body}</span><small>{item.eventType} · {item.severity} · {new Date(item.createdAt).toLocaleString()}</small><div className="actions">{item.status==="unread"?<button onClick={()=>void change(item,"read")}>Mark read</button>:item.status==="read"?<button onClick={()=>void change(item,"unread")}>Mark unread</button>:null}{item.status!=="archived"&&<button onClick={()=>void change(item,"archive")}>Archive</button>}<button onClick={()=>onNavigate((item.entityType==="invoice"||item.entityType==="payment"||item.entityType==="expense")?"finance":item.entityType==="document"?"documents":item.entityType==="task"?"tasks":"projects")}>Open related {item.entityType}</button></div></li>)}</ul>}
 {preferences&&<article><h3>Notification preferences</h3>{([["inAppEnabled","In-app notifications"],["taskEventsEnabled","Task events"],["projectEventsEnabled","Project events"],["financeEventsEnabled","Finance events"],["documentEventsEnabled","Document events"],["dueSoonEnabled","Due-soon reminders"],["overdueEnabled","Overdue reminders"],["selfNotificationsEnabled","Notify me about my own actions"]] as const).map(([key,label])=><label key={key}><input type="checkbox" checked={preferences[key]} onChange={e=>setPreferences({...preferences,[key]:e.target.checked})}/>{label}</label>)}<button onClick={()=>void savePreferences()}>Save notification preferences</button></article>}
 </section>;
}

function DocumentsPage({session,focusId}:{session:Session;focusId?:string}){
 const [items,setItems]=useState<DocumentContract[]>([]),[targets,setTargets]=useState<Record<string,Array<{id:string;label:string}>>>({}),[versions,setVersions]=useState<Array<{id:string;versionNo:number}>>([]),[selected,setSelected]=useState(""),[entityType,setEntityType]=useState("project"),[entityId,setEntityId]=useState(""),[category,setCategory]=useState("other"),[description,setDescription]=useState(""),[file,setFile]=useState<File|null>(null),[replacement,setReplacement]=useState<File|null>(null),[error,setError]=useState("");
 const load=async()=>{try{const [d,c,p,pr,t,i,pay,e]=await Promise.all([api.documents(),api.list("clients"),api.list("properties"),api.list("projects"),api.list("tasks"),api.invoices(),api.payments(),api.expenses()]),next={client:c.map(x=>({id:x.id,label:x.name})),property:p.map(x=>({id:x.id,label:x.name})),project:pr.map(x=>({id:x.id,label:x.name})),task:t.map(x=>({id:x.id,label:x.title})),invoice:i.map(x=>({id:x.id,label:x.invoiceNumber})),payment:pay.map(x=>({id:x.id,label:x.reference})),expense:e.map(x=>({id:x.id,label:x.supplier}))};setItems(current=>{const focused=current.find(item=>item.id===focusId);return focused&&!d.some(item=>item.id===focused.id)?[focused,...d]:d;});setTargets(next);setEntityId(x=>x||next.project[0]?.id||"");setError("");}catch(e){setError(apiErrorMessage(e));}};
 useEffect(()=>{void load();},[]);const document=items.find(x=>x.id===selected),replace=(x:DocumentContract)=>{setItems(v=>v.map(d=>d.id===x.id?x:d));setSelected(x.id);setError("");},fail=(e:unknown)=>setError(apiErrorMessage(e));
 useEffect(()=>{if(focusId)void Promise.all([api.document(focusId),api.documentVersions(focusId)]).then(([item,nextVersions])=>{setItems(current=>current.some(existing=>existing.id===item.id)?current:[item,...current]);setSelected(item.id);setVersions(nextVersions);}).catch(fail);},[focusId]);
 const upload=async(e:React.FormEvent)=>{e.preventDefault();if(!file){setError("Choose a file.");return;}try{const x=await api.uploadDocument(file,{category,description,entityType,entityId});setItems(v=>[x,...v]);setSelected(x.id);setVersions([{id:x.currentVersion.id,versionNo:1}]);setFile(null);setError("");}catch(x){fail(x);}};
 const download=async(versionId?:string)=>{try{const x=await api.downloadDocument(document!.id,versionId),url=URL.createObjectURL(x.blob),a=window.document.createElement("a");a.href=url;a.download=document!.currentVersion.originalFilename;a.click();URL.revokeObjectURL(url);}catch(x){fail(x);}};
 return <section><h2>Documents</h2>{error&&<p role="alert">{error}</p>}<button onClick={()=>void load()}>Reload Documents</button>{can(session,"documents.create")&&<form onSubmit={upload}><label>Target type<select aria-label="Document target type" value={entityType} onChange={e=>{setEntityType(e.target.value);setEntityId(targets[e.target.value]?.[0]?.id??"");}}>{["client","property","project","task","invoice","payment","expense"].map(x=><option key={x}>{x}</option>)}</select></label><label>Target entity<select aria-label="Document target" value={entityId} onChange={e=>setEntityId(e.target.value)}>{(targets[entityType]??[]).map(x=><option value={x.id} key={x.id}>{x.label}</option>)}</select></label><label>Document category<select value={category} onChange={e=>setCategory(e.target.value)}>{["contract","offer","invoice","receipt","project_plan","photo","protocol","permit","correspondence","other"].map(x=><option key={x}>{x}</option>)}</select></label><label>Document description<input value={description} onChange={e=>setDescription(e.target.value)}/></label><label>Document file<input aria-label="Document file" type="file" accept=".pdf,.png,.jpg,.jpeg" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><button disabled={!file||!entityId}>Upload document</button></form>}<ul>{items.map(d=><li key={d.id}><button onClick={()=>{setSelected(d.id);void api.documentVersions(d.id).then(setVersions).catch(fail);}}>{d.currentVersion.originalFilename}</button> — {d.category} — version {d.version}</li>)}</ul>{document&&<article><h3>Document detail {document.currentVersion.originalFilename}</h3><p>Category {document.category}; description {document.description??"none"}; file version {document.currentVersionNo}; record version {document.version}; checksum {document.currentVersion.checksum}</p><button onClick={()=>void download()}>Download document</button>{!document.archivedAt&&can(session,"documents.update")&&<><button onClick={()=>void api.updateDocument(document.id,{expectedVersion:document.version,description:"Edited in Web"}).then(replace).catch(fail)}>Edit document metadata</button><label>New document version<input aria-label="New document version" type="file" accept=".pdf,.png,.jpg,.jpeg" onChange={e=>setReplacement(e.target.files?.[0]??null)}/></label><button disabled={!replacement} onClick={()=>replacement&&void api.uploadDocumentVersion(document.id,replacement,document.version).then(x=>{replace(x);return api.documentVersions(x.id);}).then(setVersions).catch(fail)}>Upload new version</button></>}{!document.archivedAt&&can(session,"documents.delete")&&<button onClick={()=>void api.archiveDocument(document.id,document.version).then(replace).catch(fail)}>Archive document</button>}<h4>Versions</h4><ul>{versions.map(v=><li key={v.id}>Version {v.versionNo} <button onClick={()=>void download(v.id)}>Download version {v.versionNo}</button></li>)}</ul></article>}</section>;
}

function FinancePage({session,focusId}:{session:Session;focusId?:string}){
  const [invoices,setInvoices]=useState<InvoiceContract[]>([]),[payments,setPayments]=useState<PaymentContract[]>([]),[expenses,setExpenses]=useState<ExpenseContract[]>([]),[clients,setClients]=useState<EntityByResource["clients"][]>([]),[projects,setProjects]=useState<ProjectContract[]>([]);
  const [clientId,setClientId]=useState(""),[projectId,setProjectId]=useState(""),[number,setNumber]=useState(""),[net,setNet]=useState("0.0000"),[vat,setVat]=useState("23.0000"),[error,setError]=useState(""),[selectedInvoice,setSelectedInvoice]=useState(""),[selectedPayment,setSelectedPayment]=useState(""),[selectedExpense,setSelectedExpense]=useState(""),[reference,setReference]=useState(""),[paymentAmount,setPaymentAmount]=useState("0.0000"),[allocationAmount,setAllocationAmount]=useState("0.0000"),[supplier,setSupplier]=useState(""),[category,setCategory]=useState("materials"),[summary,setSummary]=useState<ProjectFinancialSummary|null>(null);
  const load=async()=>{try{const [i,pay,e,c,p]=await Promise.all([api.invoices(),api.payments(),api.expenses(),api.list("clients"),api.list("projects")]);setInvoices(current=>{const focused=current.find(invoice=>invoice.id===focusId);return focused&&!i.some(invoice=>invoice.id===focused.id)?[focused,...i]:i;});setPayments(pay);setExpenses(e);setClients(c);setProjects(p);if(focusId&&i.some(invoice=>invoice.id===focusId))setSelectedInvoice(focusId);setClientId(x=>x||c[0]?.id||"");setProjectId(x=>x||p[0]?.id||"");setError("");}catch(e){setError(apiErrorMessage(e));}};
  useEffect(()=>{void load();},[]);
  const fail=(x:unknown)=>setError(apiErrorMessage(x)),replaceInvoice=(x:InvoiceContract)=>{setInvoices(v=>v.map(i=>i.id===x.id?x:i));setSelectedInvoice(x.id);setError("");},replacePayment=(x:PaymentContract)=>{setPayments(v=>v.map(i=>i.id===x.id?x:i));setSelectedPayment(x.id);setError("");},replaceExpense=(x:ExpenseContract)=>{setExpenses(v=>v.map(i=>i.id===x.id?x:i));setSelectedExpense(x.id);setError("");};
  useEffect(()=>{if(focusId)void api.invoice(focusId).then(invoice=>{setInvoices(current=>current.some(item=>item.id===invoice.id)?current:[invoice,...current]);setSelectedInvoice(invoice.id);}).catch(fail);},[focusId]);
  const currency=projects.find(p=>p.id===projectId)?.currencyCode??"EUR",today=new Date().toISOString().slice(0,10);
  const createInvoice=async(e:React.FormEvent)=>{e.preventDefault();try{const x=await api.createInvoice({clientId,projectId:projectId||null,invoiceNumber:number,currencyCode:currency,issueDate:today,dueDate:new Date(Date.now()+1209600000).toISOString().slice(0,10),netAmount:net,vatRate:vat});setInvoices(v=>[x,...v]);setNumber("");setSelectedInvoice(x.id);}catch(x){fail(x);}};
  const createPayment=async(e:React.FormEvent)=>{e.preventDefault();try{const x=await api.createPayment({clientId,reference,currencyCode:currency,amount:paymentAmount,paymentDate:today});setPayments(v=>[x,...v]);setReference("");setSelectedPayment(x.id);}catch(x){fail(x);}};
  const createExpense=async(e:React.FormEvent)=>{e.preventDefault();try{const x=await api.createExpense({projectId:projectId||null,supplier,category,expenseDate:today,currencyCode:currency,netAmount:net,vatRate:vat});setExpenses(v=>[x,...v]);setSupplier("");setSelectedExpense(x.id);}catch(x){fail(x);}};
  const invoice=invoices.find(x=>x.id===selectedInvoice),payment=payments.find(x=>x.id===selectedPayment),expense=expenses.find(x=>x.id===selectedExpense);
  return <section><h2>Finance</h2>{error&&<p role="alert">{error}</p>}<div className="toolbar"><button onClick={()=>void load()}>Reload Finance</button><label>Client selector<select aria-label="Finance client" value={clientId} onChange={e=>setClientId(e.target.value)}>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Project selector<select aria-label="Finance project" value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">No project</option>{projects.filter(p=>!clientId||p.clientId===clientId).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div>
    <h3>Invoices</h3>{can(session,"finance.create")&&<form onSubmit={createInvoice}><label>Invoice number<input value={number} onChange={e=>setNumber(e.target.value)} required/></label><label>Invoice net amount<input value={net} onChange={e=>setNet(e.target.value)} required/></label><label>Invoice VAT rate<input value={vat} onChange={e=>setVat(e.target.value)} required/></label><button>Create invoice</button></form>}<ul>{invoices.map(i=><li key={i.id}><button onClick={()=>setSelectedInvoice(i.id)}>{i.invoiceNumber}</button> — {i.status} — paid {i.paidAmount}, outstanding {i.outstandingAmount}</li>)}</ul>
    {invoice&&<article><h4>Invoice detail {invoice.invoiceNumber}</h4><p>Status {invoice.status}; net {invoice.netAmount}; VAT {invoice.vatAmount}; gross {invoice.grossAmount}; paid {invoice.paidAmount}; outstanding {invoice.outstandingAmount}; version {invoice.version}</p>{invoice.status==="draft"&&can(session,"finance.update")&&<><button onClick={()=>void api.updateInvoice(invoice.id,{expectedVersion:invoice.version,notes:"Edited in Web"}).then(replaceInvoice).catch(fail)}>Edit invoice</button><button onClick={()=>void api.invoiceAction(invoice.id,"issue",invoice.version).then(replaceInvoice).catch(fail)}>Issue invoice</button></>}{["draft","issued"].includes(invoice.status)&&can(session,"finance.update")&&<button onClick={()=>void api.invoiceAction(invoice.id,"cancel",invoice.version).then(replaceInvoice).catch(fail)}>Cancel invoice</button>}{invoice.status!=="archived"&&can(session,"finance.delete")&&<button onClick={()=>void api.archiveInvoice(invoice.id,invoice.version).then(replaceInvoice).catch(fail)}>Archive invoice</button>}</article>}
    <h3>Payments</h3>{can(session,"finance.create")&&<form onSubmit={createPayment}><label>Payment reference<input value={reference} onChange={e=>setReference(e.target.value)} required/></label><label>Payment amount<input value={paymentAmount} onChange={e=>setPaymentAmount(e.target.value)} required/></label><button>Create payment</button></form>}<ul>{payments.map(p=><li key={p.id}><button onClick={()=>setSelectedPayment(p.id)}>{p.reference}</button> — {p.status} — allocated {p.allocatedAmount}, available {p.unallocatedAmount}</li>)}</ul>
    {payment&&<article><h4>Payment detail {payment.reference}</h4><p>Status {payment.status}; amount {payment.amount}; allocated {payment.allocatedAmount}; available {payment.unallocatedAmount}; version {payment.version}</p>{payment.status==="received"&&can(session,"finance.update")&&<><label>Invoice allocation<select aria-label="Allocation invoice" value={selectedInvoice} onChange={e=>setSelectedInvoice(e.target.value)}>{invoices.filter(i=>i.clientId===payment.clientId&&i.currencyCode===payment.currencyCode&&["issued","partially_paid"].includes(i.status)).map(i=><option key={i.id} value={i.id}>{i.invoiceNumber}</option>)}</select></label><label>Allocation amount<input value={allocationAmount} onChange={e=>setAllocationAmount(e.target.value)}/></label><button onClick={()=>selectedInvoice&&void api.allocatePayment(payment.id,selectedInvoice,allocationAmount,payment.version).then(replacePayment).then(()=>void load()).catch(fail)}>Allocate payment</button><button onClick={()=>void api.reversePayment(payment.id,payment.version).then(replacePayment).then(()=>void load()).catch(fail)}>Reverse payment</button></>}{payment.status!=="archived"&&can(session,"finance.delete")&&<button onClick={()=>void api.archivePayment(payment.id,payment.version).then(replacePayment).catch(fail)}>Archive payment</button>}</article>}
    <h3>Expenses</h3>{can(session,"finance.create")&&<form onSubmit={createExpense}><label>Expense supplier<input value={supplier} onChange={e=>setSupplier(e.target.value)} required/></label><label>Expense category<input value={category} onChange={e=>setCategory(e.target.value)} required/></label><button>Create expense</button></form>}<ul>{expenses.map(e=><li key={e.id}><button onClick={()=>setSelectedExpense(e.id)}>{e.supplier}</button> — {e.status} — {e.grossAmount} {e.currencyCode}</li>)}</ul>
    {expense&&<article><h4>Expense detail {expense.supplier}</h4><p>Status {expense.status}; category {expense.category}; gross {expense.grossAmount}; version {expense.version}</p>{expense.status==="draft"&&can(session,"finance.update")&&<><button onClick={()=>void api.updateExpense(expense.id,{expectedVersion:expense.version,notes:"Edited in Web"}).then(replaceExpense).catch(fail)}>Edit expense</button><button onClick={()=>void api.expenseAction(expense.id,"approve",expense.version).then(replaceExpense).catch(fail)}>Approve expense</button><button onClick={()=>void api.expenseAction(expense.id,"reject",expense.version).then(replaceExpense).catch(fail)}>Reject expense</button></>}{expense.status!=="archived"&&can(session,"finance.delete")&&<button onClick={()=>void api.archiveExpense(expense.id,expense.version).then(replaceExpense).catch(fail)}>Archive expense</button>}</article>}
    <h3>Project financial summary</h3><button disabled={!projectId} onClick={()=>projectId&&void api.projectFinancialSummary(projectId).then(setSummary).catch(fail)}>Load financial summary</button>{summary&&<article><p>Budget {summary.budget??"not set"} {summary.currencyCode}</p><p>Invoiced {summary.invoicedGross}; paid {summary.paid}; outstanding {summary.outstanding}; expenses {summary.expenses}</p><p>Margin amount {summary.grossMarginAmount}; margin percentage {summary.grossMarginPercentage??"not applicable"}; overdue {summary.overdueInvoiceCount} / {summary.overdueInvoiceAmount}</p></article>}
  </section>;
}

const unitDimensions=["length","area","volume","mass","time","count","packaging","custom"] as const,unitSystems=["metric","imperial","universal","custom"] as const;
export const nextUnitSort=(current:string,order:"asc"|"desc",column:string)=>current===column?{sortBy:column,sortOrder:order==="asc"?"desc" as const:"asc" as const}:{sortBy:column,sortOrder:"asc" as const};
function MeasurementUnitsPage({session}:{session:Session}){
 const requestNo=useRef(0);
 const [items,setItems]=useState<MeasurementUnitContract[]>([]),[pagination,setPagination]=useState({page:1,pageSize:10,total:0,totalPages:0}),[search,setSearch]=useState(""),[dimension,setDimension]=useState(""),[unitSystem,setUnitSystem]=useState(""),[active,setActive]=useState(""),[sortBy,setSortBy]=useState("code"),[sortOrder,setSortOrder]=useState<"asc"|"desc">("asc"),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const [code,setCode]=useState(""),[symbol,setSymbol]=useState(""),[displayName,setDisplayName]=useState(""),[createDimension,setCreateDimension]=useState<(typeof unitDimensions)[number]>("custom"),[createSystem,setCreateSystem]=useState<(typeof unitSystems)[number]>("custom"),[precision,setPrecision]=useState(2),[selected,setSelected]=useState<MeasurementUnitContract|null>(null),[editName,setEditName]=useState("");
 const [conversionUnits,setConversionUnits]=useState<MeasurementUnitContract[]>([]),[fromId,setFromId]=useState(""),[toId,setToId]=useState(""),[quantity,setQuantity]=useState("1"),[conversion,setConversion]=useState("");
 const query=()=>{const p=new URLSearchParams({page:String(pagination.page),pageSize:String(pagination.pageSize),sortBy,sortOrder});if(search)p.set("search",search);if(dimension)p.set("dimension",dimension);if(unitSystem)p.set("unitSystem",unitSystem);if(active)p.set("active",active);return p.toString();};
 const load=async()=>{const current=++requestNo.current,setQuery=query();setLoading(true);try{const r=await api.measurementUnits(setQuery);if(current!==requestNo.current)return;setItems(r.data);setPagination(x=>({...x,...r.pagination}));setError("");}catch(x){if(current===requestNo.current)setError(apiErrorMessage(x));}finally{if(current===requestNo.current)setLoading(false);}};
 useEffect(()=>{void load();},[pagination.page,pagination.pageSize,search,dimension,unitSystem,active,sortBy,sortOrder]);
 useEffect(()=>{void api.measurementUnits("page=1&pageSize=100&active=true&sortBy=code&sortOrder=asc").then(r=>{setConversionUnits(r.data);setFromId(r.data.find(u=>u.code==="M")?.id??"");setToId(r.data.find(u=>u.code==="CM")?.id??"");}).catch(x=>setError(apiErrorMessage(x)));},[]);
 const reset=()=>setPagination(x=>({...x,page:1})),sort=(column:string)=>{const n=nextUnitSort(sortBy,sortOrder,column);setSortBy(n.sortBy);setSortOrder(n.sortOrder);reset();};
 const create=async(e:React.FormEvent)=>{e.preventDefault();try{const created=await api.createMeasurementUnit({code,symbol,displayName,dimension:createDimension,unitSystem:createSystem,decimalPrecision:precision});setCode("");setSymbol("");setDisplayName("");setSearch(created.code);reset();}catch(x){setError(apiErrorMessage(x));}};
 const edit=async(e:React.FormEvent)=>{e.preventDefault();if(!selected)return;try{const x=await api.updateMeasurementUnit(selected.id,{expectedVersion:selected.version,displayName:editName});setSelected(x);await load();}catch(problem){setError(apiErrorMessage(problem));}};
 const state=async(unit:MeasurementUnitContract)=>{try{await api.measurementUnitStatus(unit.id,unit.status==="active"?"deactivate":"activate",unit.version);await load();}catch(x){setError(apiErrorMessage(x));}};
 const convert=async(e:React.FormEvent)=>{e.preventDefault();try{const x=await api.convertMeasurementUnit({fromUnitId:fromId,toUnitId:toId,quantity});setConversion(`${x.quantity} = ${x.result}`);setError("");}catch(x){setError(apiErrorMessage(x));}};
 const writable=can(session,"measurement_units.update");
 return <section><h2>Measurement Units</h2>{error&&<p role="alert">{error}</p>}<div className="toolbar"><label>Search units<input value={search} onChange={e=>{setSearch(e.target.value);reset();}}/></label><label>Dimension<select value={dimension} onChange={e=>{setDimension(e.target.value);reset();}}><option value="">All dimensions</option>{unitDimensions.map(x=><option key={x}>{x}</option>)}</select></label><label>Unit system<select value={unitSystem} onChange={e=>{setUnitSystem(e.target.value);reset();}}><option value="">All systems</option>{unitSystems.map(x=><option key={x}>{x}</option>)}</select></label><label>Active status<select value={active} onChange={e=>{setActive(e.target.value);reset();}}><option value="">All statuses</option><option value="true">Active</option><option value="false">Inactive</option></select></label><button onClick={()=>{setSearch("");setDimension("");setUnitSystem("");setActive("");reset();}}>Clear filters</button></div>
 {loading?<p>Loading measurement units…</p>:items.length===0?<p>No measurement units found.</p>:<table><thead><tr>{[["code","Code"],["symbol","Symbol"],["displayName","Name"],["dimension","Dimension"],["unitSystem","System"],["status","Status"]].map(([key,label])=><th key={key}><button className="sort-button" aria-pressed={sortBy===key} onClick={()=>sort(key)}>{label}{sortBy===key?(sortOrder==="asc"?" ↑":" ↓"):""}</button></th>)}<th>Default</th><th>Conversion base</th><th>Actions</th></tr></thead><tbody>{items.map(u=><tr key={u.id}><td>{u.code}</td><td>{u.symbol}</td><td>{u.displayName}</td><td>{u.dimension}</td><td>{u.unitSystem}</td><td>{u.status}</td><td>{u.isSystem?"System default":"Tenant custom"}</td><td>{u.baseMultiplier?`${u.baseMultiplier} × ${u.canonicalBaseCode}`:"Not convertible"}</td><td>{writable&&<><button onClick={()=>{setSelected(u);setEditName(u.displayName);}}>Edit</button><button onClick={()=>void state(u)}>{u.status==="active"?"Deactivate":"Activate"}</button></>}</td></tr>)}</tbody></table>}
 {pagination.total>0&&<nav className="pagination" aria-label="Measurement unit pagination"><button disabled={loading||pagination.page<=1} onClick={()=>setPagination(x=>({...x,page:x.page-1}))}>Previous</button><span>Page {pagination.page} of {pagination.totalPages} · {pagination.total} units</span><button disabled={loading||pagination.page>=pagination.totalPages} onClick={()=>setPagination(x=>({...x,page:x.page+1}))}>Next</button><label>Rows per page<select value={pagination.pageSize} onChange={e=>setPagination(x=>({...x,page:1,pageSize:Number(e.target.value)}))}>{[5,10,25,50].map(x=><option key={x}>{x}</option>)}</select></label></nav>}
 {can(session,"measurement_units.create")&&<form onSubmit={create}><h3>Create custom unit</h3><label>Stable code<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} required/></label><label>Symbol<input value={symbol} onChange={e=>setSymbol(e.target.value)} required/></label><label>Display name<input value={displayName} onChange={e=>setDisplayName(e.target.value)} required/></label><label>Dimension<select value={createDimension} onChange={e=>setCreateDimension(e.target.value as any)}>{unitDimensions.map(x=><option key={x}>{x}</option>)}</select></label><label>Unit system<select value={createSystem} onChange={e=>setCreateSystem(e.target.value as any)}>{unitSystems.map(x=><option key={x}>{x}</option>)}</select></label><label>Decimal precision<input type="number" min="0" max="12" value={precision} onChange={e=>setPrecision(Number(e.target.value))}/></label><button>Create unit</button></form>}
 {selected&&<form onSubmit={edit}><h3>Edit {selected.code}</h3><label>Display name<input value={editName} onChange={e=>setEditName(e.target.value)} required/></label><button>Save unit</button></form>}
 <form onSubmit={convert}><h3>Convert quantity</h3><label>Quantity<input value={quantity} onChange={e=>setQuantity(e.target.value)} required/></label><label>From unit<select value={fromId} onChange={e=>setFromId(e.target.value)}>{conversionUnits.map(x=><option key={x.id} value={x.id}>{x.code} — {x.displayName}</option>)}</select></label><label>To unit<select value={toId} onChange={e=>setToId(e.target.value)}>{conversionUnits.map(x=><option key={x.id} value={x.id}>{x.code} — {x.displayName}</option>)}</select></label><button>Convert</button>{conversion&&<output aria-live="polite">{conversion}</output>}</form></section>;
}

export const flattenCategoryTree=(nodes:WorkCategoryNodeContract[]):WorkCategoryContract[]=>nodes.flatMap(node=>[node,...flattenCategoryTree(node.children)]);
export const nextWorkItemSort=(current:string,order:"asc"|"desc",column:string)=>current===column?{sortBy:column,sortOrder:order==="asc"?"desc" as const:"asc" as const}:{sortBy:column,sortOrder:"asc" as const};
function WorkCatalogPage({session}:{session:Session}){
 const [tree,setTree]=useState<WorkCategoryNodeContract[]>([]),[expanded,setExpanded]=useState<Set<string>>(new Set()),[categories,setCategories]=useState<WorkCategoryContract[]>([]),[units,setUnits]=useState<MeasurementUnitContract[]>([]),[items,setItems]=useState<WorkItemContract[]>([]),[pagination,setPagination]=useState({page:1,pageSize:10,total:0,totalPages:0}),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const [categoryCode,setCategoryCode]=useState(""),[categoryName,setCategoryName]=useState(""),[parentId,setParentId]=useState(""),[selectedCategory,setSelectedCategory]=useState<WorkCategoryContract|null>(null),[moveParent,setMoveParent]=useState("");
 const [search,setSearch]=useState(""),[filterCategory,setFilterCategory]=useState(""),[filterUnit,setFilterUnit]=useState(""),[active,setActive]=useState(""),[sortBy,setSortBy]=useState("code"),[sortOrder,setSortOrder]=useState<"asc"|"desc">("asc"),[itemCode,setItemCode]=useState(""),[itemName,setItemName]=useState(""),[itemCategory,setItemCategory]=useState(""),[itemUnit,setItemUnit]=useState(""),[selectedItem,setSelectedItem]=useState<WorkItemContract|null>(null),[editItemName,setEditItemName]=useState("");
 const fail=(x:unknown)=>setError(apiErrorMessage(x)),reset=()=>setPagination(x=>({...x,page:1}));
 const loadReferences=async()=>{try{const [t,c,u]=await Promise.all([api.workCategoryTree(),api.workCategories("page=1&pageSize=100&sortBy=sortOrder&sortOrder=asc"),api.measurementUnits("page=1&pageSize=100&active=true&sortBy=code&sortOrder=asc")]);setTree(t);setCategories(c.data);setUnits(u.data);setItemCategory(x=>x||c.data.find(v=>v.status==="active")?.id||"");setItemUnit(x=>x||u.data[0]?.id||"");setError("");}catch(x){fail(x);}};
 const itemQuery=()=>{const p=new URLSearchParams({page:String(pagination.page),pageSize:String(pagination.pageSize),sortBy,sortOrder});if(search)p.set("search",search);if(filterCategory)p.set("categoryId",filterCategory);if(filterUnit)p.set("measurementUnitId",filterUnit);if(active)p.set("active",active);return p.toString();};
 const loadItems=async()=>{setLoading(true);try{const r=await api.workItems(itemQuery());setItems(r.data);setPagination(x=>({...x,...r.pagination}));setError("");}catch(x){fail(x);}finally{setLoading(false);}};
 useEffect(()=>{void loadReferences();},[]);useEffect(()=>{void loadItems();},[pagination.page,pagination.pageSize,search,filterCategory,filterUnit,active,sortBy,sortOrder]);
 const createCategory=async(e:React.FormEvent)=>{e.preventDefault();try{const x=await api.createWorkCategory({code:categoryCode,displayName:categoryName,parentId:parentId||null,sortOrder:100});setCategoryCode("");setCategoryName("");setSelectedCategory(x);await loadReferences();}catch(v){fail(v);}};
 const saveCategory=async(e:React.FormEvent)=>{e.preventDefault();if(!selectedCategory)return;try{const x=await api.updateWorkCategory(selectedCategory.id,{expectedVersion:selectedCategory.version,displayName:categoryName||selectedCategory.displayName});setSelectedCategory(x);await loadReferences();}catch(v){fail(v);}};
 const moveCategory=async()=>{if(!selectedCategory)return;try{const x=await api.moveWorkCategory(selectedCategory.id,{expectedVersion:selectedCategory.version,parentId:moveParent||null});setSelectedCategory(x);await loadReferences();}catch(v){fail(v);}};
 const categoryState=async(x:WorkCategoryContract)=>{try{const changed=await api.workCategoryStatus(x.id,x.status==="active"?"deactivate":"activate",x.version);setSelectedCategory(changed);await loadReferences();}catch(v){fail(v);}};
 const createItem=async(e:React.FormEvent)=>{e.preventDefault();try{const x=await api.createWorkItem({code:itemCode,displayName:itemName,categoryId:itemCategory,measurementUnitId:itemUnit,quantityPrecision:2});setItemCode("");setItemName("");setSelectedItem(x);setSearch(x.code);reset();}catch(v){fail(v);}};
 const saveItem=async(e:React.FormEvent)=>{e.preventDefault();if(!selectedItem)return;try{const x=await api.updateWorkItem(selectedItem.id,{expectedVersion:selectedItem.version,displayName:editItemName,categoryId:itemCategory,measurementUnitId:itemUnit});setSelectedItem(x);await loadItems();}catch(v){fail(v);}};
 const itemState=async(x:WorkItemContract)=>{try{const changed=await api.workItemStatus(x.id,x.status==="active"?"deactivate":"activate",x.version);setSelectedItem(changed);await loadItems();}catch(v){fail(v);}};
 const sort=(column:string)=>{const x=nextWorkItemSort(sortBy,sortOrder,column);setSortBy(x.sortBy);setSortOrder(x.sortOrder);reset();},writable=can(session,"work_catalog.update");
 const nodes=(values:WorkCategoryNodeContract[])=>values.map(node=><li key={node.id}><div style={{paddingLeft:`${node.hierarchyLevel*1.25}rem`}}>{node.children.length>0&&<button aria-expanded={expanded.has(node.id)} aria-label={`${expanded.has(node.id)?"Collapse":"Expand"} ${node.displayName}`} onClick={()=>setExpanded(current=>{const n=new Set(current);if(n.has(node.id))n.delete(node.id);else n.add(node.id);return n;})}>{expanded.has(node.id)?"−":"+"}</button>}<button className="link-button" onClick={()=>{setSelectedCategory(node);setCategoryName(node.displayName);setMoveParent(node.parentId??"");}}>{node.code} — {node.displayName}</button> · {node.status} · {node.isSystem?"System default":"Tenant custom"} {writable&&<button onClick={()=>void categoryState(node)}>{node.status==="active"?"Deactivate category":"Activate category"}</button>}</div>{expanded.has(node.id)&&node.children.length>0&&<ul>{nodes(node.children)}</ul>}</li>);
 return <section><h2>Construction Work Catalog</h2>{error&&<p role="alert">{error}</p>}<div className="split"><section><h3>Work Categories</h3>{tree.length?<ul aria-label="Work category tree">{nodes(tree)}</ul>:<p>No work categories found.</p>}{can(session,"work_catalog.create")&&<form onSubmit={createCategory}><h4>Create category</h4><label>Category code<input value={categoryCode} onChange={e=>setCategoryCode(e.target.value.toUpperCase())} required/></label><label>Category name<input value={categoryName} onChange={e=>setCategoryName(e.target.value)} required/></label><label>Parent category<select value={parentId} onChange={e=>setParentId(e.target.value)}><option value="">Root category</option>{categories.filter(x=>x.status==="active"&&x.hierarchyLevel<3).map(x=><option key={x.id} value={x.id}>{x.code} — {x.displayName}</option>)}</select></label><button>Create category</button></form>}
 {selectedCategory&&writable&&<form onSubmit={saveCategory}><h4>Edit category {selectedCategory.code}</h4><label>Edit category name<input value={categoryName} onChange={e=>setCategoryName(e.target.value)} required/></label><button>Save category</button><label>Move category<select value={moveParent} onChange={e=>setMoveParent(e.target.value)}><option value="">Root category</option>{categories.filter(x=>x.id!==selectedCategory.id&&x.status==="active"&&x.hierarchyLevel<3).map(x=><option key={x.id} value={x.id}>{x.code} — {x.displayName}</option>)}</select></label><button type="button" onClick={()=>void moveCategory()}>Move category</button></form>}</section>
 <section><h3>Work Items</h3><div className="toolbar"><label>Search work items<input value={search} onChange={e=>{setSearch(e.target.value);reset();}}/></label><label>Work item category filter<select value={filterCategory} onChange={e=>{setFilterCategory(e.target.value);reset();}}><option value="">All categories</option>{categories.map(x=><option key={x.id} value={x.id}>{x.displayName}</option>)}</select></label><label>Work item unit filter<select value={filterUnit} onChange={e=>{setFilterUnit(e.target.value);reset();}}><option value="">All units</option>{units.map(x=><option key={x.id} value={x.id}>{x.code}</option>)}</select></label><label>Work item status<select value={active} onChange={e=>{setActive(e.target.value);reset();}}><option value="">All statuses</option><option value="true">Active</option><option value="false">Inactive</option></select></label></div>
 {loading?<p>Loading work items…</p>:items.length===0?<p>No work items found.</p>:<table><thead><tr>{[["code","Code"],["displayName","Name"],["category","Category"],["measurementUnit","Unit"],["status","Status"]].map(([key,label])=><th key={key}><button className="sort-button" aria-label={`Sort by ${label.toLowerCase()}`} onClick={()=>sort(key)}>{label}{sortBy===key?(sortOrder==="asc"?" ↑":" ↓"):""}</button></th>)}<th>Default</th><th>Actions</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.code}</td><td>{x.displayName}</td><td>{x.categoryName}</td><td>{x.measurementUnitCode}</td><td>{x.status}</td><td>{x.isSystem?"System default":"Tenant custom"}</td><td>{writable&&<><button onClick={()=>{setSelectedItem(x);setEditItemName(x.displayName);setItemCategory(x.categoryId);setItemUnit(x.measurementUnitId);}}>Edit work item</button><button onClick={()=>void itemState(x)}>{x.status==="active"?"Deactivate work item":"Activate work item"}</button></>}</td></tr>)}</tbody></table>}
 {pagination.total>0&&<nav className="pagination" aria-label="Work item pagination"><button disabled={pagination.page<=1} onClick={()=>setPagination(x=>({...x,page:x.page-1}))}>Previous</button><span>Page {pagination.page} of {pagination.totalPages} · {pagination.total} work items</span><button disabled={pagination.page>=pagination.totalPages} onClick={()=>setPagination(x=>({...x,page:x.page+1}))}>Next</button><label>Work item rows per page<select value={pagination.pageSize} onChange={e=>setPagination(x=>({...x,page:1,pageSize:Number(e.target.value)}))}>{[5,10,25,50].map(x=><option key={x}>{x}</option>)}</select></label></nav>}
 {can(session,"work_catalog.create")&&<form onSubmit={createItem}><h4>Create work item</h4><label>Work item code<input value={itemCode} onChange={e=>setItemCode(e.target.value.toUpperCase())} required/></label><label>Work item name<input value={itemName} onChange={e=>setItemName(e.target.value)} required/></label><label>Work item category<select aria-label="Create work item category" value={itemCategory} onChange={e=>setItemCategory(e.target.value)} required>{categories.filter(x=>x.status==="active").map(x=><option key={x.id} value={x.id}>{x.code} — {x.displayName}</option>)}</select></label><label>Work item measurement unit<select aria-label="Create work item measurement unit" value={itemUnit} onChange={e=>setItemUnit(e.target.value)} required>{units.map(x=><option key={x.id} value={x.id}>{x.code} — {x.displayName}</option>)}</select></label><button>Create work item</button></form>}
 {selectedItem&&writable&&<form onSubmit={saveItem}><h4>Edit work item {selectedItem.code}</h4><label>Edit work item name<input value={editItemName} onChange={e=>setEditItemName(e.target.value)} required/></label><label>Edit work item category<select value={itemCategory} onChange={e=>setItemCategory(e.target.value)}>{categories.filter(x=>x.status==="active").map(x=><option key={x.id} value={x.id}>{x.displayName}</option>)}</select></label><label>Edit work item measurement unit<select value={itemUnit} onChange={e=>setItemUnit(e.target.value)}>{units.map(x=><option key={x.id} value={x.id}>{x.code}</option>)}</select></label><button>Save work item</button></form>}</section></div></section>;
}

export const flattenMaterialCategoryTree=(nodes:MaterialCategoryNodeContract[]):MaterialCategoryContract[]=>nodes.flatMap(node=>[node,...flattenMaterialCategoryTree(node.children)]);
export const parseTechnicalData=(value:string):Record<string,unknown>=>{const parsed:unknown=JSON.parse(value||"{}");if(parsed===null||Array.isArray(parsed)||typeof parsed!=="object")throw new Error("Technical data must be a JSON object");return parsed as Record<string,unknown>;};
function MaterialCatalogPage({session}:{session:Session}){
 const [tree,setTree]=useState<MaterialCategoryNodeContract[]>([]),[categories,setCategories]=useState<MaterialCategoryContract[]>([]),[units,setUnits]=useState<MeasurementUnitContract[]>([]),[items,setItems]=useState<MaterialContract[]>([]),[pageInfo,setPageInfo]=useState({page:1,pageSize:10,total:0,totalPages:0}),[error,setError]=useState("");
 const [categoryCode,setCategoryCode]=useState(""),[categoryName,setCategoryName]=useState(""),[parentId,setParentId]=useState(""),[selectedCategory,setSelectedCategory]=useState<MaterialCategoryContract|null>(null),[moveParent,setMoveParent]=useState("");
 const [search,setSearch]=useState(""),[categoryFilter,setCategoryFilter]=useState(""),[unitFilter,setUnitFilter]=useState(""),[manufacturerFilter,setManufacturerFilter]=useState(""),[brandFilter,setBrandFilter]=useState(""),[active,setActive]=useState("");
 const [code,setCode]=useState(""),[name,setName]=useState(""),[categoryId,setCategoryId]=useState(""),[unitId,setUnitId]=useState(""),[manufacturer,setManufacturer]=useState(""),[brand,setBrand]=useState(""),[technicalData,setTechnicalData]=useState("{}"),[selected,setSelected]=useState<MaterialContract|null>(null);
 const fail=(x:unknown)=>setError(x instanceof Error?x.message:apiErrorMessage(x)),reset=()=>setPageInfo(x=>({...x,page:1}));
 const loadReferences=async()=>{try{const[t,c,u]=await Promise.all([api.materialCategoryTree(),api.materialCategories("page=1&pageSize=100&sortBy=sortOrder&sortOrder=asc"),api.measurementUnits("page=1&pageSize=100&active=true&sortBy=code&sortOrder=asc")]);setTree(t);setCategories(c.data);setUnits(u.data);setCategoryId(x=>x||c.data.find(v=>v.status==="active")?.id||"");setUnitId(x=>x||u.data[0]?.id||"");setError("");}catch(x){fail(x);}};
 const query=()=>{const p=new URLSearchParams({page:String(pageInfo.page),pageSize:String(pageInfo.pageSize),sortBy:"code",sortOrder:"asc"});if(search)p.set("search",search);if(categoryFilter)p.set("categoryId",categoryFilter);if(unitFilter)p.set("measurementUnitId",unitFilter);if(manufacturerFilter)p.set("manufacturerName",manufacturerFilter);if(brandFilter)p.set("brandName",brandFilter);if(active)p.set("active",active);return p.toString();};
 const load=async()=>{try{const r=await api.materials(query());setItems(r.data);setPageInfo(x=>({...x,...r.pagination}));setError("");}catch(x){fail(x);}};
 useEffect(()=>{void loadReferences();},[]);useEffect(()=>{void load();},[pageInfo.page,pageInfo.pageSize,search,categoryFilter,unitFilter,manufacturerFilter,brandFilter,active]);
 const createCategory=async(e:React.FormEvent)=>{e.preventDefault();try{await api.createMaterialCategory({code:categoryCode,displayName:categoryName,parentId:parentId||null,sortOrder:100});setCategoryCode("");setCategoryName("");await loadReferences();}catch(x){fail(x);}};
 const saveCategory=async(e:React.FormEvent)=>{e.preventDefault();if(!selectedCategory)return;try{await api.updateMaterialCategory(selectedCategory.id,{expectedVersion:selectedCategory.version,displayName:categoryName});setSelectedCategory(null);await loadReferences();}catch(x){fail(x);}};
 const moveCategory=async()=>{if(!selectedCategory)return;try{await api.moveMaterialCategory(selectedCategory.id,{expectedVersion:selectedCategory.version,parentId:moveParent||null});setSelectedCategory(null);await loadReferences();}catch(x){fail(x);}};
 const categoryState=async(x:MaterialCategoryContract)=>{try{await api.materialCategoryStatus(x.id,x.status==="active"?"deactivate":"activate",x.version);await loadReferences();}catch(v){fail(v);}};
 const create=async(e:React.FormEvent)=>{e.preventDefault();try{const x=await api.createMaterial({code,displayName:name,categoryId,measurementUnitId:unitId,manufacturerName:manufacturer||undefined,brandName:brand||undefined,technicalData:parseTechnicalData(technicalData)});setCode("");setName("");setSearch(x.code);reset();}catch(v){fail(v);}};
 const edit=async(e:React.FormEvent)=>{e.preventDefault();if(!selected)return;try{await api.updateMaterial(selected.id,{expectedVersion:selected.version,displayName:name,categoryId,measurementUnitId:unitId,manufacturerName:manufacturer||null,brandName:brand||null,technicalData:parseTechnicalData(technicalData)});setSelected(null);await load();}catch(v){fail(v);}};
 const state=async(x:MaterialContract)=>{try{await api.materialStatus(x.id,x.status==="active"?"deactivate":"activate",x.version);await load();}catch(v){fail(v);}};
 const writable=can(session,"material_catalog.update"),selectMaterial=(x:MaterialContract)=>{setSelected(x);setName(x.displayName);setCategoryId(x.categoryId);setUnitId(x.measurementUnitId);setManufacturer(x.manufacturerName??"");setBrand(x.brandName??"");setTechnicalData(JSON.stringify(x.technicalData,null,2));};
 const nodes=(values:MaterialCategoryNodeContract[])=>values.map(x=><li key={x.id} style={{marginLeft:`${x.hierarchyLevel}rem`}}><button className="link-button" onClick={()=>{setSelectedCategory(x);setCategoryName(x.displayName);setMoveParent(x.parentId??"");}}>{x.code} — {x.displayName}</button> · {x.status} · {x.isSystem?"System default":"Tenant custom"} {writable&&<button onClick={()=>void categoryState(x)}>{x.status==="active"?"Deactivate category":"Activate category"}</button>}{x.children.length>0&&<ul>{nodes(x.children)}</ul>}</li>);
 return <section><h2>Material Catalog</h2>{error&&<p role="alert">{error}</p>}<div className="split"><section><h3>Material Categories</h3>{tree.length?<ul aria-label="Material category tree">{nodes(tree)}</ul>:<p>No material categories found.</p>}{can(session,"material_catalog.create")&&<form onSubmit={createCategory}><h4>Create material category</h4><label>Material category code<input value={categoryCode} onChange={e=>setCategoryCode(e.target.value.toUpperCase())} required/></label><label>Material category name<input value={categoryName} onChange={e=>setCategoryName(e.target.value)} required/></label><label>Material parent category<select value={parentId} onChange={e=>setParentId(e.target.value)}><option value="">Root category</option>{categories.filter(x=>x.status==="active"&&x.hierarchyLevel<3).map(x=><option key={x.id} value={x.id}>{x.code} — {x.displayName}</option>)}</select></label><button>Create material category</button></form>}
 {selectedCategory&&writable&&<form onSubmit={saveCategory}><h4>Edit material category {selectedCategory.code}</h4><label>Edit material category name<input value={categoryName} onChange={e=>setCategoryName(e.target.value)} required/></label><button>Save material category</button><label>Move material category<select value={moveParent} onChange={e=>setMoveParent(e.target.value)}><option value="">Root category</option>{categories.filter(x=>x.id!==selectedCategory.id&&x.status==="active"&&x.hierarchyLevel<3).map(x=><option key={x.id} value={x.id}>{x.displayName}</option>)}</select></label><button type="button" onClick={()=>void moveCategory()}>Move material category</button></form>}</section>
 <section><h3>Materials</h3><div className="toolbar"><label>Search materials<input value={search} onChange={e=>{setSearch(e.target.value);reset();}}/></label><label>Material category filter<select value={categoryFilter} onChange={e=>{setCategoryFilter(e.target.value);reset();}}><option value="">All categories</option>{categories.map(x=><option key={x.id} value={x.id}>{x.displayName}</option>)}</select></label><label>Material unit filter<select value={unitFilter} onChange={e=>{setUnitFilter(e.target.value);reset();}}><option value="">All units</option>{units.map(x=><option key={x.id} value={x.id}>{x.code}</option>)}</select></label><label>Manufacturer filter<input value={manufacturerFilter} onChange={e=>{setManufacturerFilter(e.target.value);reset();}}/></label><label>Brand filter<input value={brandFilter} onChange={e=>{setBrandFilter(e.target.value);reset();}}/></label><label>Material status<select value={active} onChange={e=>{setActive(e.target.value);reset();}}><option value="">All statuses</option><option value="true">Active</option><option value="false">Inactive</option></select></label></div>
 {items.length?<table><thead><tr><th>Code</th><th>Name</th><th>Category</th><th>Unit</th><th>Manufacturer</th><th>Brand</th><th>Status</th><th>Actions</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.code}</td><td>{x.displayName}</td><td>{x.categoryName}</td><td>{x.measurementUnitCode}</td><td>{x.manufacturerName}</td><td>{x.brandName}</td><td>{x.status}</td><td>{writable&&<><button onClick={()=>selectMaterial(x)}>Edit material</button><button onClick={()=>void state(x)}>{x.status==="active"?"Deactivate material":"Activate material"}</button></>}</td></tr>)}</tbody></table>:<p>No materials found.</p>}
 {pageInfo.total>0&&<nav className="pagination" aria-label="Material pagination"><button disabled={pageInfo.page<=1} onClick={()=>setPageInfo(x=>({...x,page:x.page-1}))}>Previous</button><span>Page {pageInfo.page} of {pageInfo.totalPages} · {pageInfo.total} materials</span><button disabled={pageInfo.page>=pageInfo.totalPages} onClick={()=>setPageInfo(x=>({...x,page:x.page+1}))}>Next</button></nav>}
 {can(session,"material_catalog.create")&&<form onSubmit={create}><h4>Create material</h4><label>Material code<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} required/></label><label>Material name<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>Create material category<select value={categoryId} onChange={e=>setCategoryId(e.target.value)} required>{categories.filter(x=>x.status==="active").map(x=><option key={x.id} value={x.id}>{x.code} — {x.displayName}</option>)}</select></label><label>Create material measurement unit<select value={unitId} onChange={e=>setUnitId(e.target.value)} required>{units.map(x=><option key={x.id} value={x.id}>{x.code} — {x.displayName}</option>)}</select></label><label>Manufacturer<input value={manufacturer} onChange={e=>setManufacturer(e.target.value)}/></label><label>Brand<input value={brand} onChange={e=>setBrand(e.target.value)}/></label><label>Technical data JSON<textarea value={technicalData} onChange={e=>setTechnicalData(e.target.value)}/></label><button>Create material</button></form>}
 {selected&&writable&&<form onSubmit={edit}><h4>Edit material {selected.code}</h4><label>Edit material name<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>Edit material category<select value={categoryId} onChange={e=>setCategoryId(e.target.value)}>{categories.filter(x=>x.status==="active").map(x=><option key={x.id} value={x.id}>{x.displayName}</option>)}</select></label><label>Edit material measurement unit<select value={unitId} onChange={e=>setUnitId(e.target.value)}>{units.map(x=><option key={x.id} value={x.id}>{x.code}</option>)}</select></label><label>Edit manufacturer<input value={manufacturer} onChange={e=>setManufacturer(e.target.value)}/></label><label>Edit brand<input value={brand} onChange={e=>setBrand(e.target.value)}/></label><label>Edit technical data JSON<textarea value={technicalData} onChange={e=>setTechnicalData(e.target.value)}/></label><button>Save material</button></form>}</section></div></section>;
}

export function App():JSX.Element{
  const [session,setSession]=useState<Session|null>(auth.get()),[page,setPage]=useState<Page>("dashboard"),[focusId,setFocusId]=useState<string|undefined>(),[unread,setUnread]=useState(0),[sidebarCollapsed,setSidebarCollapsed]=useState(false);
  const navigate=(next:Page,id?:string)=>{setFocusId(id);setPage(next);};
  useEffect(()=>{if(session)void api.me().catch(()=>{auth.set(null);setSession(null);});},[session]);
  useEffect(()=>{if(!session)return;let active=true;const refresh=()=>void api.unreadCount().then(x=>active&&setUnread(x.count)).catch(()=>undefined);refresh();const timer=window.setInterval(refresh,Math.max(5000,Number(import.meta.env.VITE_NOTIFICATION_POLL_MS??15000)));return()=>{active=false;window.clearInterval(timer);};},[session]);
  if(!session)return <Login onLogin={setSession}/>;
  const visibleNav=nav.filter(([,key])=>key!=="reports"||can(session,"reports.read")).filter(([,key])=>key!=="dashboard"||can(session,"dashboard.read")).filter(([,key])=>key!=="measurement-units"||can(session,"measurement_units.read")).filter(([,key])=>key!=="work-catalog"||can(session,"work_catalog.read")).filter(([,key])=>key!=="material-catalog"||can(session,"material_catalog.read")).filter(([,key])=>key!=="price-lists"||can(session,"price_list.read"));
  return <div className={`shell ${sidebarCollapsed?"sidebar-collapsed":""}`}><aside><Brand surface="dark" compact={sidebarCollapsed}/><button className="sidebar-toggle" aria-expanded={!sidebarCollapsed} aria-label={sidebarCollapsed?"Expand navigation":"Collapse navigation"} onClick={()=>setSidebarCollapsed(x=>!x)}>{sidebarCollapsed?"›":"‹"}<span className="nav-label">{sidebarCollapsed?"Expand":"Collapse"}</span></button><button aria-label={`Notifications, ${unread} unread`} title={sidebarCollapsed?"Notifications":undefined} onClick={()=>navigate("notifications")}><span className="nav-label">Notifications</span> {unread>0&&<span className="badge">{unread}</span>}</button>{visibleNav.map(([label,key])=><button key={key} aria-label={label} title={sidebarCollapsed?label:undefined} onClick={()=>navigate(key)}><span className="nav-label">{label}</span></button>)}<button aria-label="Logout" title={sidebarCollapsed?"Logout":undefined} onClick={async()=>{await api.logout();auth.set(null);setSession(null);}}><span className="nav-label">Logout</span></button></aside><main><header><span>OMNIRA · AI Business Operating System</span><span>{session.user.displayName} · {session.user.email}</span></header>{page==="dashboard"?<Dashboard session={session}/>:page==="reports"?<Reports session={session} onNavigate={navigate}/>:page==="measurement-units"?<MeasurementUnitsPage session={session}/>:page==="work-catalog"?<WorkCatalogPage session={session}/>:page==="material-catalog"?<MaterialCatalogPage session={session}/>:page==="price-lists"?<PriceListsPage session={session}/>:page==="finance"?<FinancePage session={session} focusId={focusId}/>:page==="documents"?<DocumentsPage session={session} focusId={focusId}/>:page==="notifications"?<NotificationCenter onNavigate={navigate} onUnread={setUnread}/>:<ResourcePage key={page} resource={page} session={session} focusId={focusId}/>}</main></div>;
}
