import {useEffect,useMemo,useState,type JSX} from "react";
import type {ExpenseContract,InvoiceContract,PaymentContract,ProjectContract,ProjectFinancialSummary,TaskContract} from "@odls/contracts";
import {api,apiErrorMessage,auth,type EntityByResource,type ProjectAction,type Resource,type Session,type TaskAction} from "./api.js";

const nav:Array<[string,Resource|"dashboard"|"finance"]>=[["Dashboard","dashboard"],["Clients","clients"],["Properties","properties"],["Projects","projects"],["Tasks","tasks"],["Finance","finance"]];
const can=(session:Session|null,permission:string)=>Boolean(session?.permissions.includes(permission));
const projectActions:Record<ProjectContract["status"],ProjectAction[]>={draft:["plan","cancel"],planned:["start","cancel"],active:["pause","complete","cancel"],paused:["resume","cancel"],completed:[],cancelled:[],archived:[]};
const taskActions:Record<TaskContract["status"],TaskAction[]>={todo:["start","block","cancel"],in_progress:["block","complete","cancel"],blocked:["resume","cancel"],completed:[],cancelled:[],archived:[]};
const titleCase=(value:string)=>value.charAt(0).toUpperCase()+value.slice(1);
const singular:Record<Resource,string>={clients:"client",properties:"property",projects:"project",tasks:"task"};

function Login({onLogin}:{onLogin:(session:Session)=>void}){
  const [tenant,setTenant]=useState("demo"),[email,setEmail]=useState("admin@demo.odls"),[password,setPassword]=useState("DemoPassword!2026"),[error,setError]=useState("");
  const submit=async(event:React.FormEvent)=>{event.preventDefault();try{const result=await api.login(tenant,email,password);auth.set(result);onLogin(result);}catch{setError("Sign-in failed. Check tenant, email, and password.");}};
  return <main className="login"><form onSubmit={submit}><h1>ODLS Platform</h1><label>Tenant<input value={tenant} onChange={event=>setTenant(event.target.value)} required/></label><label>Email<input type="email" value={email} onChange={event=>setEmail(event.target.value)} required/></label><label>Password<input type="password" value={password} onChange={event=>setPassword(event.target.value)} required/></label>{error&&<p role="alert">{error}</p>}<button>Sign in</button></form></main>;
}

function ResourcePage<R extends Resource>({resource,session}:{resource:R;session:Session}){
  const [items,setItems]=useState<EntityByResource[R][]>([]),[search,setSearch]=useState(""),[error,setError]=useState(""),[name,setName]=useState(""),[editValue,setEditValue]=useState(""),[assigneeId,setAssigneeId]=useState("00000000-0000-4000-8000-000000000012");
  const load=async()=>{try{setItems(await api.list(resource,search));setError("");}catch(problem){setError(apiErrorMessage(problem));}};
  useEffect(()=>{void load();},[resource]);
  const replace=(entity:EntityByResource[R])=>{setItems(current=>current.map(item=>item.id===entity.id?entity:item));setError("");};
  const fail=(problem:unknown)=>setError(apiErrorMessage(problem));
  const create=async(event:React.FormEvent)=>{event.preventDefault();try{
    let created:EntityByResource[R];
    if(resource==="clients")created=await api.create("clients",{name}) as EntityByResource[R];
    else if(resource==="properties")created=await api.create("properties",{name,clientId:"00000000-0000-4000-8000-000000000041",propertyType:"commercial",address:{line1:"New address",city:"Warsaw",countryCode:"PL"}}) as EntityByResource[R];
    else if(resource==="projects")created=await api.create("projects",{projectNumber:`WEB-${Date.now()}`,name,clientId:"00000000-0000-4000-8000-000000000041",propertyId:"00000000-0000-4000-8000-000000000061",financialOwnerLegalEntityId:"00000000-0000-4000-8000-000000000021",currencyCode:"EUR"}) as EntityByResource[R];
    else created=await api.create("tasks",{title:name,projectId:"00000000-0000-4000-8000-000000000071"}) as EntityByResource[R];
    setItems(current=>[created,...current]);setName("");setError("");
  }catch(problem){fail(problem);}};
  const edit=async(item:EntityByResource[R])=>{const next=editValue.trim();if(!next){setError("Enter a new value before editing.");return;}try{
    if(resource==="clients")replace(await api.update("clients",item.id,{expectedVersion:item.version,name:next}) as EntityByResource[R]);
    else if(resource==="properties")replace(await api.update("properties",item.id,{expectedVersion:item.version,name:next}) as EntityByResource[R]);
    else if(resource==="projects")replace(await api.update("projects",item.id,{expectedVersion:item.version,name:next}) as EntityByResource[R]);
    else replace(await api.update("tasks",item.id,{expectedVersion:item.version,title:next}) as EntityByResource[R]);
    setEditValue("");
  }catch(problem){fail(problem);}};
  const archive=async(item:EntityByResource[R])=>{try{replace(await api.archive(resource,item.id,item.version));}catch(problem){fail(problem);}};
  const projectLifecycle=async(item:ProjectContract,action:ProjectAction)=>{try{replace(await api.projectLifecycle(item.id,action,item.version) as EntityByResource[R]);}catch(problem){fail(problem);}};
  const taskLifecycle=async(item:TaskContract,action:TaskAction)=>{try{replace(await api.taskLifecycle(item.id,action,item.version) as EntityByResource[R]);}catch(problem){fail(problem);}};
  const assign=async(item:TaskContract)=>{try{replace(await api.assign(item.id,assigneeId,item.version) as EntityByResource[R]);}catch(problem){fail(problem);}};
  const unassign=async(item:TaskContract,userId:string)=>{try{replace(await api.unassign(item.id,userId,item.version) as EntityByResource[R]);}catch(problem){fail(problem);}};
  return <section><h2>{titleCase(resource)}</h2><div className="toolbar"><input aria-label={`Search ${resource}`} placeholder="Search" value={search} onChange={event=>setSearch(event.target.value)}/><button onClick={()=>void load()}>Search</button><button onClick={()=>void load()}>Reload</button>{can(session,`${resource}.update`)&&<input aria-label="Edit value" placeholder="New name or title" value={editValue} onChange={event=>setEditValue(event.target.value)}/>} {resource==="tasks"&&can(session,"tasks.assign")&&<input aria-label="Assignee user ID" value={assigneeId} onChange={event=>setAssigneeId(event.target.value)}/>}</div>
    {can(session,`${resource}.create`)&&<form onSubmit={create}><label>New {singular[resource]}<input value={name} onChange={event=>setName(event.target.value)} required/></label><button>Create</button></form>}
    {error&&<p role="alert">{error}</p>}
    {items.length===0?<p>No {resource} found.</p>:<ul>{items.map(item=><li key={item.id} data-version={item.version}><div><strong>{"title" in item?item.title:item.name}</strong> — {item.status} <small>version {item.version}</small></div><div className="actions">
      {item.status!=="archived"&&can(session,`${resource}.update`)&&<button onClick={()=>void edit(item)}>Edit</button>}
      {resource==="projects"&&can(session,"projects.update")&&projectActions[(item as ProjectContract).status].map(action=><button key={action} onClick={()=>void projectLifecycle(item as ProjectContract,action)}>{titleCase(action)} Project</button>)}
      {resource==="tasks"&&can(session,"tasks.update")&&taskActions[(item as TaskContract).status].map(action=><button key={action} onClick={()=>void taskLifecycle(item as TaskContract,action)}>{titleCase(action)} Task</button>)}
      {resource==="tasks"&&["todo","in_progress","blocked"].includes(item.status)&&can(session,"tasks.update")&&can(session,"tasks.assign")&&<button onClick={()=>void assign(item as TaskContract)}>Assign Task</button>}
      {resource==="tasks"&&["todo","in_progress","blocked"].includes(item.status)&&can(session,"tasks.update")&&can(session,"tasks.assign")&&(item as TaskContract).assignees?.map(assignee=><button key={assignee.userId} onClick={()=>void unassign(item as TaskContract,assignee.userId)}>Unassign {assignee.displayName}</button>)}
      {item.status!=="archived"&&can(session,`${resource}.delete`)&&<button onClick={()=>void archive(item)}>Archive</button>}
    </div></li>)}</ul>}
  </section>;
}

function Dashboard({session}:{session:Session}){
  const [data,setData]=useState<{clients:EntityByResource["clients"][];projects:EntityByResource["projects"][];tasks:EntityByResource["tasks"][]}>({clients:[],projects:[],tasks:[]});
  useEffect(()=>{void Promise.all([api.list("clients"),api.list("projects"),api.list("tasks")]).then(([clients,projects,tasks])=>setData({clients,projects,tasks}));},[]);
  const overdue=useMemo(()=>data.tasks.filter(task=>task.isOverdue).length,[data.tasks]);
  return <section><h2>Dashboard</h2><div className="cards"><p>Active clients: {data.clients.filter(client=>client.status==="active").length}</p><p>Active projects: {data.projects.filter(project=>project.status==="active").length}</p><p>Overdue tasks: {overdue}</p><p>Signed in as: {session.user.displayName}</p></div></section>;
}

function FinancePage({session}:{session:Session}){
  const [invoices,setInvoices]=useState<InvoiceContract[]>([]),[payments,setPayments]=useState<PaymentContract[]>([]),[expenses,setExpenses]=useState<ExpenseContract[]>([]),[clients,setClients]=useState<EntityByResource["clients"][]>([]),[projects,setProjects]=useState<ProjectContract[]>([]);
  const [clientId,setClientId]=useState(""),[projectId,setProjectId]=useState(""),[number,setNumber]=useState(""),[net,setNet]=useState("0.0000"),[vat,setVat]=useState("23.0000"),[error,setError]=useState(""),[selectedInvoice,setSelectedInvoice]=useState(""),[selectedPayment,setSelectedPayment]=useState(""),[selectedExpense,setSelectedExpense]=useState(""),[reference,setReference]=useState(""),[paymentAmount,setPaymentAmount]=useState("0.0000"),[allocationAmount,setAllocationAmount]=useState("0.0000"),[supplier,setSupplier]=useState(""),[category,setCategory]=useState("materials"),[summary,setSummary]=useState<ProjectFinancialSummary|null>(null);
  const load=async()=>{try{const [i,pay,e,c,p]=await Promise.all([api.invoices(),api.payments(),api.expenses(),api.list("clients"),api.list("projects")]);setInvoices(i);setPayments(pay);setExpenses(e);setClients(c);setProjects(p);setClientId(x=>x||c[0]?.id||"");setProjectId(x=>x||p[0]?.id||"");setError("");}catch(e){setError(apiErrorMessage(e));}};
  useEffect(()=>{void load();},[]);
  const fail=(x:unknown)=>setError(apiErrorMessage(x)),replaceInvoice=(x:InvoiceContract)=>{setInvoices(v=>v.map(i=>i.id===x.id?x:i));setSelectedInvoice(x.id);setError("");},replacePayment=(x:PaymentContract)=>{setPayments(v=>v.map(i=>i.id===x.id?x:i));setSelectedPayment(x.id);setError("");},replaceExpense=(x:ExpenseContract)=>{setExpenses(v=>v.map(i=>i.id===x.id?x:i));setSelectedExpense(x.id);setError("");};
  const currency=projects.find(p=>p.id===projectId)?.currencyCode??"EUR",today=new Date().toISOString().slice(0,10);
  const createInvoice=async(e:React.FormEvent)=>{e.preventDefault();try{const x=await api.createInvoice({clientId,projectId:projectId||null,invoiceNumber:number,currencyCode:currency,issueDate:today,dueDate:new Date(Date.now()+1209600000).toISOString().slice(0,10),netAmount:net,vatRate:vat});setInvoices(v=>[x,...v]);setNumber("");setSelectedInvoice(x.id);}catch(x){fail(x);}};
  const createPayment=async(e:React.FormEvent)=>{e.preventDefault();try{const x=await api.createPayment({clientId,reference,currencyCode:currency,amount:paymentAmount,paymentDate:today});setPayments(v=>[x,...v]);setReference("");setSelectedPayment(x.id);}catch(x){fail(x);}};
  const createExpense=async(e:React.FormEvent)=>{e.preventDefault();try{const x=await api.createExpense({projectId:projectId||null,supplier,category,expenseDate:today,currencyCode:currency,netAmount:net,vatRate:vat});setExpenses(v=>[x,...v]);setSupplier("");setSelectedExpense(x.id);}catch(x){fail(x);}};
  const invoice=invoices.find(x=>x.id===selectedInvoice),payment=payments.find(x=>x.id===selectedPayment),expense=expenses.find(x=>x.id===selectedExpense);
  return <section><h2>Finance</h2>{error&&<p role="alert">{error}</p>}<div className="toolbar"><button onClick={()=>void load()}>Reload Finance</button><label>Client selector<select aria-label="Finance client" value={clientId} onChange={e=>setClientId(e.target.value)}>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Project selector<select aria-label="Finance project" value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">No project</option>{projects.filter(p=>!clientId||p.clientId===clientId).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div>
    <h3>Invoices</h3>{can(session,"finance.create")&&<form onSubmit={createInvoice}><label>Invoice number<input value={number} onChange={e=>setNumber(e.target.value)} required/></label><label>Invoice net amount<input value={net} onChange={e=>setNet(e.target.value)} required/></label><label>Invoice VAT rate<input value={vat} onChange={e=>setVat(e.target.value)} required/></label><button>Create invoice</button></form>}<ul>{invoices.map(i=><li key={i.id}><button onClick={()=>setSelectedInvoice(i.id)}>{i.invoiceNumber}</button> — {i.status} — paid {i.paidAmount}, outstanding {i.outstandingAmount}</li>)}</ul>
    {invoice&&<article><h4>Invoice detail {invoice.invoiceNumber}</h4><p>Status {invoice.status}; net {invoice.netAmount}; VAT {invoice.vatAmount}; gross {invoice.grossAmount}; paid {invoice.paidAmount}; outstanding {invoice.outstandingAmount}; version {invoice.version}</p>{invoice.status==="draft"&&can(session,"finance.update")&&<><button onClick={()=>void api.updateInvoice(invoice.id,{expectedVersion:invoice.version,notes:"Edited in Web"}).then(replaceInvoice).catch(fail)}>Edit invoice</button><button onClick={()=>void api.invoiceAction(invoice.id,"issue",invoice.version).then(replaceInvoice).catch(fail)}>Issue invoice</button></>}{["draft","issued"].includes(invoice.status)&&can(session,"finance.update")&&<button onClick={()=>void api.invoiceAction(invoice.id,"cancel",invoice.version).then(replaceInvoice).catch(fail)}>Cancel invoice</button>}{invoice.status!=="archived"&&can(session,"finance.delete")&&<button onClick={()=>void api.archiveInvoice(invoice.id,invoice.version).then(replaceInvoice).catch(fail)}>Archive invoice</button>}</article>}
    <h3>Payments</h3>{can(session,"finance.create")&&<form onSubmit={createPayment}><label>Payment reference<input value={reference} onChange={e=>setReference(e.target.value)} required/></label><label>Payment amount<input value={paymentAmount} onChange={e=>setPaymentAmount(e.target.value)} required/></label><button>Create payment</button></form>}<ul>{payments.map(p=><li key={p.id}><button onClick={()=>setSelectedPayment(p.id)}>{p.reference}</button> — {p.status} — allocated {p.allocatedAmount}, available {p.unallocatedAmount}</li>)}</ul>
    {payment&&<article><h4>Payment detail {payment.reference}</h4><p>Status {payment.status}; amount {payment.amount}; allocated {payment.allocatedAmount}; available {payment.unallocatedAmount}; version {payment.version}</p>{payment.status==="received"&&can(session,"finance.update")&&<><label>Invoice allocation<select aria-label="Allocation invoice" value={selectedInvoice} onChange={e=>setSelectedInvoice(e.target.value)}>{invoices.filter(i=>i.clientId===payment.clientId&&i.currencyCode===payment.currencyCode&&["issued","partially_paid"].includes(i.status)).map(i=><option key={i.id} value={i.id}>{i.invoiceNumber}</option>)}</select></label><label>Allocation amount<input value={allocationAmount} onChange={e=>setAllocationAmount(e.target.value)}/></label><button onClick={()=>selectedInvoice&&void api.allocatePayment(payment.id,selectedInvoice,allocationAmount,payment.version).then(replacePayment).then(()=>void load()).catch(fail)}>Allocate payment</button><button onClick={()=>void api.reversePayment(payment.id,payment.version).then(replacePayment).then(()=>void load()).catch(fail)}>Reverse payment</button></>}{payment.status!=="archived"&&can(session,"finance.delete")&&<button onClick={()=>void api.archivePayment(payment.id,payment.version).then(replacePayment).catch(fail)}>Archive payment</button>}</article>}
    <h3>Expenses</h3>{can(session,"finance.create")&&<form onSubmit={createExpense}><label>Expense supplier<input value={supplier} onChange={e=>setSupplier(e.target.value)} required/></label><label>Expense category<input value={category} onChange={e=>setCategory(e.target.value)} required/></label><button>Create expense</button></form>}<ul>{expenses.map(e=><li key={e.id}><button onClick={()=>setSelectedExpense(e.id)}>{e.supplier}</button> — {e.status} — {e.grossAmount} {e.currencyCode}</li>)}</ul>
    {expense&&<article><h4>Expense detail {expense.supplier}</h4><p>Status {expense.status}; category {expense.category}; gross {expense.grossAmount}; version {expense.version}</p>{expense.status==="draft"&&can(session,"finance.update")&&<><button onClick={()=>void api.updateExpense(expense.id,{expectedVersion:expense.version,notes:"Edited in Web"}).then(replaceExpense).catch(fail)}>Edit expense</button><button onClick={()=>void api.expenseAction(expense.id,"approve",expense.version).then(replaceExpense).catch(fail)}>Approve expense</button><button onClick={()=>void api.expenseAction(expense.id,"reject",expense.version).then(replaceExpense).catch(fail)}>Reject expense</button></>}{expense.status!=="archived"&&can(session,"finance.delete")&&<button onClick={()=>void api.archiveExpense(expense.id,expense.version).then(replaceExpense).catch(fail)}>Archive expense</button>}</article>}
    <h3>Project financial summary</h3><button disabled={!projectId} onClick={()=>projectId&&void api.projectFinancialSummary(projectId).then(setSummary).catch(fail)}>Load financial summary</button>{summary&&<article><p>Budget {summary.budget??"not set"} {summary.currencyCode}</p><p>Invoiced {summary.invoicedGross}; paid {summary.paid}; outstanding {summary.outstanding}; expenses {summary.expenses}</p><p>Margin amount {summary.grossMarginAmount}; margin percentage {summary.grossMarginPercentage??"not applicable"}; overdue {summary.overdueInvoiceCount} / {summary.overdueInvoiceAmount}</p></article>}
  </section>;
}

export function App():JSX.Element{
  const [session,setSession]=useState<Session|null>(auth.get()),[page,setPage]=useState<Resource|"dashboard"|"finance">("dashboard");
  useEffect(()=>{if(session)void api.me().catch(()=>{auth.set(null);setSession(null);});},[session]);
  if(!session)return <Login onLogin={setSession}/>;
  return <div className="shell"><aside><h1>ODLS</h1>{nav.map(([label,key])=><button key={key} onClick={()=>setPage(key)}>{label}</button>)}<button onClick={async()=>{await api.logout();auth.set(null);setSession(null);}}>Logout</button></aside><main><header>{session.user.displayName} · {session.user.email}</header>{page==="dashboard"?<Dashboard session={session}/>:page==="finance"?<FinancePage session={session}/>:<ResourcePage key={page} resource={page} session={session}/>}</main></div>;
}
