import {useEffect,useState,type JSX} from "react";
import type {DocumentContract,ExpenseContract,InvoiceContract,NotificationContract,NotificationPreferencesContract,PaymentContract,ProjectContract,ProjectFinancialSummary,TaskContract} from "@odls/contracts";
import {api,apiErrorMessage,auth,mergeNotifications,type EntityByResource,type ProjectAction,type ReportName,type Resource,type Session,type TaskAction} from "./api.js";

type Page=Resource|"dashboard"|"reports"|"finance"|"documents"|"notifications";
const nav:Array<[string,Page]>=[["Dashboard","dashboard"],["Reports","reports"],["Clients","clients"],["Properties","properties"],["Projects","projects"],["Tasks","tasks"],["Finance","finance"],["Documents","documents"]];
const can=(session:Session|null,permission:string)=>Boolean(session?.permissions.includes(permission));
const projectActions:Record<ProjectContract["status"],ProjectAction[]>={draft:["plan","cancel"],planned:["start","cancel"],active:["pause","complete","cancel"],paused:["resume","cancel"],completed:[],cancelled:[],archived:[]};
const taskActions:Record<TaskContract["status"],TaskAction[]>={todo:["start","block","cancel"],in_progress:["block","complete","cancel"],blocked:["resume","cancel"],completed:[],cancelled:[],archived:[]};
const titleCase=(value:string)=>value.charAt(0).toUpperCase()+value.slice(1);
const singular:Record<Resource,string>={clients:"client",properties:"property",projects:"project",tasks:"task"};

function Login({onLogin}:{onLogin:(session:Session)=>void}){
  const [tenant,setTenant]=useState("demo"),[email,setEmail]=useState("admin@demo.odls"),[password,setPassword]=useState("DemoPassword!2026"),[error,setError]=useState("");
  const submit=async(event:React.FormEvent)=>{event.preventDefault();try{const result=await api.login(tenant,email,password);auth.set(result);onLogin(result);}catch{setError("Sign-in failed. Check tenant, email, and password.");}};
  return <main className="login"><form onSubmit={submit}><h1>ODLS Platform</h1><label>Tenant<input value={tenant} onChange={event=>setTenant(event.target.value)} required/></label><label>Email<input type="email" value={email} onChange={event=>setEmail(event.target.value)} required/></label><label>Password<input type="password" value={password} onChange={event=>setPassword(event.target.value)} required/></label>{error&&<p role="alert">{error}</p>}<button>Sign in</button></form></main>;
}

function ResourcePage<R extends Resource>({resource,session}:{resource:R;session:Session}){
  const [items,setItems]=useState<EntityByResource[R][]>([]),[search,setSearch]=useState(""),[error,setError]=useState(""),[name,setName]=useState(""),[editValue,setEditValue]=useState(""),[assigneeId,setAssigneeId]=useState("00000000-0000-4000-8000-000000000012");
  const load=async()=>{try{setItems(await api.list(resource,search));setError("");}catch(problem){setError(apiErrorMessage(problem));}};
  useEffect(()=>{void load();},[resource]);
  const replace=(entity:EntityByResource[R])=>{setItems(current=>current.map(item=>item.id===entity.id?entity:item));setError("");};
  const fail=(problem:unknown)=>setError(apiErrorMessage(problem));
  const create=async(event:React.FormEvent)=>{event.preventDefault();try{
    let created:EntityByResource[R];
    if(resource==="clients")created=await api.create("clients",{name}) as EntityByResource[R];
    else if(resource==="properties")created=await api.create("properties",{name,clientId:"00000000-0000-4000-8000-000000000041",propertyType:"commercial",address:{line1:"New address",city:"Warsaw",countryCode:"PL"}}) as EntityByResource[R];
    else if(resource==="projects")created=await api.create("projects",{projectNumber:`WEB-${Date.now()}`,name,clientId:"00000000-0000-4000-8000-000000000041",propertyId:"00000000-0000-4000-8000-000000000061",financialOwnerLegalEntityId:"00000000-0000-4000-8000-000000000021",currencyCode:"EUR"}) as EntityByResource[R];
    else created=await api.create("tasks",{title:name,projectId:"00000000-0000-4000-8000-000000000071"}) as EntityByResource[R];
    setItems(current=>[created,...current]);setName("");setError("");
  }catch(problem){fail(problem);}};
  const edit=async(item:EntityByResource[R])=>{const next=editValue.trim();if(!next){setError("Enter a new value before editing.");return;}try{
    if(resource==="clients")replace(await api.update("clients",item.id,{expectedVersion:item.version,name:next}) as EntityByResource[R]);
    else if(resource==="properties")replace(await api.update("properties",item.id,{expectedVersion:item.version,name:next}) as EntityByResource[R]);
    else if(resource==="projects")replace(await api.update("projects",item.id,{expectedVersion:item.version,name:next}) as EntityByResource[R]);
    else replace(await api.update("tasks",item.id,{expectedVersion:item.version,title:next}) as EntityByResource[R]);
    setEditValue("");
  }catch(problem){fail(problem);}};
  const archive=async(item:EntityByResource[R])=>{try{replace(await api.archive(resource,item.id,item.version));}catch(problem){fail(problem);}};
  const projectLifecycle=async(item:ProjectContract,action:ProjectAction)=>{try{replace(await api.projectLifecycle(item.id,action,item.version) as EntityByResource[R]);}catch(problem){fail(problem);}};
  const taskLifecycle=async(item:TaskContract,action:TaskAction)=>{try{replace(await api.taskLifecycle(item.id,action,item.version) as EntityByResource[R]);}catch(problem){fail(problem);}};
  const assign=async(item:TaskContract)=>{try{replace(await api.assign(item.id,assigneeId,item.version) as EntityByResource[R]);}catch(problem){fail(problem);}};
  const unassign=async(item:TaskContract,userId:string)=>{try{replace(await api.unassign(item.id,userId,item.version) as EntityByResource[R]);}catch(problem){fail(problem);}};
  return <section><h2>{titleCase(resource)}</h2><div className="toolbar"><input aria-label={`Search ${resource}`} placeholder="Search" value={search} onChange={event=>setSearch(event.target.value)}/><button onClick={()=>void load()}>Search</button><button onClick={()=>void load()}>Reload</button>{can(session,`${resource}.update`)&&<input aria-label="Edit value" placeholder="New name or title" value={editValue} onChange={event=>setEditValue(event.target.value)}/>} {resource==="tasks"&&can(session,"tasks.assign")&&<input aria-label="Assignee user ID" value={assigneeId} onChange={event=>setAssigneeId(event.target.value)}/>}</div>
    {can(session,`${resource}.create`)&&<form onSubmit={create}><label>New {singular[resource]}<input value={name} onChange={event=>setName(event.target.value)} required/></label><button>Create</button></form>}
    {error&&<p role="alert">{error}</p>}
    {items.length===0?<p>No {resource} found.</p>:<ul>{items.map(item=><li key={item.id} data-version={item.version}><div><strong>{"title" in item?item.title:item.name}</strong> — {item.status} <small>version {item.version}</small></div><div className="actions">
      {item.status!=="archived"&&can(session,`${resource}.update`)&&<button onClick={()=>void edit(item)}>Edit</button>}
      {resource==="projects"&&can(session,"projects.update")&&projectActions[(item as ProjectContract).status].map(action=><button key={action} onClick={()=>void projectLifecycle(item as ProjectContract,action)}>{titleCase(action)} Project</button>)}
      {resource==="tasks"&&can(session,"tasks.update")&&taskActions[(item as TaskContract).status].map(action=><button key={action} onClick={()=>void taskLifecycle(item as TaskContract,action)}>{titleCase(action)} Task</button>)}
      {resource==="tasks"&&["todo","in_progress","blocked"].includes(item.status)&&can(session,"tasks.update")&&can(session,"tasks.assign")&&<button onClick={()=>void assign(item as TaskContract)}>Assign Task</button>}
      {resource==="tasks"&&["todo","in_progress","blocked"].includes(item.status)&&can(session,"tasks.update")&&can(session,"tasks.assign")&&(item as TaskContract).assignees?.map(assignee=><button key={assignee.userId} onClick={()=>void unassign(item as TaskContract,assignee.userId)}>Unassign {assignee.displayName}</button>)}
      {item.status!=="archived"&&can(session,`${resource}.delete`)&&<button onClick={()=>void archive(item)}>Archive</button>}
    </div></li>)}</ul>}
  </section>;
}

function Dashboard({session}:{session:Session}){
  const [range,setRange]=useState(30),[data,setData]=useState<any>(null),[health,setHealth]=useState<any[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true);
  const load=async()=>{setLoading(true);try{const [summary,projects]=await Promise.all([api.dashboard(range),can(session,"projects.read")?api.projectHealth():Promise.resolve([])]);setData(summary);setHealth(projects);setError("");}catch(x){setError(apiErrorMessage(x));}finally{setLoading(false);}};
  useEffect(()=>{void load();},[range]);
  return <section><h2>Executive Dashboard</h2><div className="toolbar"><label>Date range<select aria-label="Dashboard date range" value={range} onChange={e=>setRange(Number(e.target.value))}>{[7,30,90].map(x=><option key={x} value={x}>{x} days</option>)}</select></label><button onClick={()=>void load()}>Refresh dashboard</button></div>{error&&<p role="alert">{error}</p>}{loading?<p>Loading dashboard…</p>:!data?<p>No dashboard data.</p>:<><p>UTC reporting period: {data.range.start} to {data.range.endExclusive} (exclusive)</p><div className="cards">{data.projects&&<><p>Active projects: {data.projects.active}</p><p>Overdue projects: {data.projects.overdue}</p></>}{data.tasks&&<><p>Open tasks: {data.tasks.open}</p><p>Blocked tasks: {data.tasks.blocked}</p><p>Overdue tasks: {data.tasks.overdue}</p></>}<p>Unread notifications: {data.unread_notifications}</p></div>{data.finance&&<><h3>Finance by currency</h3>{data.finance.length===0?<p>No finance activity.</p>:<table><thead><tr><th>Currency</th><th>Invoiced</th><th>Paid</th><th>Outstanding</th><th>Margin</th></tr></thead><tbody>{data.finance.map((x:any)=><tr key={x.currencyCode}><td>{x.currencyCode}</td><td>{x.invoicedGross}</td><td>{x.paid}</td><td>{x.outstanding}</td><td>{x.grossMargin}</td></tr>)}</tbody></table>}</>}<h3>Project health</h3>{health.length===0?<p>No authorized projects.</p>:<table><thead><tr><th>Project</th><th>State</th><th>Score</th><th>Reasons</th></tr></thead><tbody>{health.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.health.state}</td><td>{x.health.score}</td><td>{x.health.reasons.join(", ")}</td></tr>)}</tbody></table>}{data.documents&&<><h3>Documents and operations</h3><p>Recent uploads: {data.documents.recent}; created in period: {data.documents.created}</p></>}{data.operations&&<p>Operational warnings: {data.operations.dead_letters} dead letters, {data.operations.failed} failed deliveries.</p>}</>}</section>;
}

function Reports({session}:{session:Session}){
 const available:ReportName[]=[...(can(session,"finance.read")?["accounts-receivable","profitability"] as ReportName[]:[]),...(can(session,"tasks.read")?["deadlines","workload"] as ReportName[]:[]),...(can(session,"documents.read")?["documents"] as ReportName[]:[]),...(can(session,"operational_metrics.read")?["activity" as const]:[])],[name,setName]=useState<ReportName>(available[0]),[range,setRange]=useState(30),[overdue,setOverdue]=useState(false),[rows,setRows]=useState<any[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(false);
 const load=async()=>{setLoading(true);try{setRows(await api.report(name,`range=${range}&pageSize=100${name==="accounts-receivable"&&overdue?"&overdue=true":""}`));setError("");}catch(x){setError(apiErrorMessage(x));setRows([]);}finally{setLoading(false);}};
 useEffect(()=>{void load();},[name,range,overdue]);
 const download=async()=>{try{const x=await api.exportReport(name,`range=${range}${overdue?"&overdue=true":""}`),url=URL.createObjectURL(x.blob),a=document.createElement("a");a.href=url;a.download=x.disposition?.match(/filename="([^"]+)"/)?.[1]??`${name}.csv`;a.click();URL.revokeObjectURL(url);}catch(x){setError(apiErrorMessage(x));}};
 const columns=rows[0]?Object.keys(rows[0]).filter(x=>!x.endsWith("Id")||x==="userId"):[];
 return <section><h2>Operational Reports</h2><div className="toolbar"><label>Report<select aria-label="Report selector" value={name} onChange={e=>setName(e.target.value as ReportName)}>{available.map(x=><option key={x} value={x}>{x}</option>)}</select></label><label>Period<select aria-label="Report date range" value={range} onChange={e=>setRange(Number(e.target.value))}>{[7,30,90].map(x=><option key={x} value={x}>{x} days</option>)}</select></label>{name==="accounts-receivable"&&<label><input type="checkbox" checked={overdue} onChange={e=>setOverdue(e.target.checked)}/>Overdue only</label>}<button onClick={()=>void load()}>Refresh report</button>{can(session,"reports.export")&&name!=="activity"&&<button onClick={()=>void download()}>Download CSV</button>}</div>{error&&<p role="alert">{error}</p>}{loading?<p>Loading report…</p>:rows.length===0?<p>No report rows.</p>:<table><thead><tr>{columns.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={row.id??row.projectId??row.userId??i}>{columns.map(x=><td key={x}>{row[x]===null?"—":String(row[x])}</td>)}</tr>)}</tbody></table>}</section>;
}

function NotificationCenter({onNavigate,onUnread}:{onNavigate:(page:Page)=>void;onUnread:(count:number)=>void}){
 const [items,setItems]=useState<NotificationContract[]>([]),[status,setStatus]=useState(""),[severity,setSeverity]=useState(""),[error,setError]=useState(""),[preferences,setPreferences]=useState<NotificationPreferencesContract|null>(null);
 const query=`archived=${status==="archived"?"true":"false"}${status&&status!=="archived"?`&status=${status}`:""}${severity?`&severity=${severity}`:""}&pageSize=100`;
 const load=async(silent=false)=>{try{const [next,count,prefs]=await Promise.all([api.notifications(query),api.unreadCount(),preferences?Promise.resolve(preferences):api.notificationPreferences()]);setItems(current=>mergeNotifications(current.filter(x=>next.some(n=>n.id===x.id)),next));onUnread(count.count);setPreferences(prefs);setError("");}catch(problem){setError(`${silent?"Notification refresh failed. ":""}${apiErrorMessage(problem)}`);}};
 useEffect(()=>{void load();const interval=window.setInterval(()=>void load(true),Math.max(5000,Number(import.meta.env.VITE_NOTIFICATION_POLL_MS??15000)));return()=>window.clearInterval(interval);},[query]);
 const replace=(item:NotificationContract)=>{setItems(current=>current.map(x=>x.id===item.id?item:x).filter(x=>status==="archived"?x.status==="archived":x.status!=="archived"));void api.unreadCount().then(x=>onUnread(x.count));setError("");},change=(item:NotificationContract,state:"read"|"unread"|"archive")=>api.notificationState(item.id,state,item.version).then(replace).catch(x=>setError(apiErrorMessage(x)));
 const savePreferences=async()=>{if(!preferences)return;try{setPreferences(await api.updateNotificationPreferences({...preferences,expectedVersion:preferences.version}));setError("");}catch(x){setError(apiErrorMessage(x));}};
 return <section><h2>Notifications</h2>{error&&<p role="alert">{error}</p>}<div className="toolbar"><label>Status<select aria-label="Notification status filter" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Active</option><option value="unread">Unread</option><option value="read">Read</option><option value="archived">Archived</option></select></label><label>Severity<select aria-label="Notification severity filter" value={severity} onChange={e=>setSeverity(e.target.value)}><option value="">All</option>{["info","success","warning","critical"].map(x=><option key={x}>{x}</option>)}</select></label><button onClick={()=>void load()}>Refresh notifications</button><button onClick={()=>void api.markAllNotificationsRead().then(()=>load())}>Mark all read</button></div>
 {items.length===0?<p>No notifications found.</p>:<ul className="notifications">{items.map(item=><li key={item.id} className={item.status==="unread"?"notification-unread":""}><strong>{item.title}</strong><span>{item.body}</span><small>{item.eventType} · {item.severity} · {new Date(item.createdAt).toLocaleString()}</small><div className="actions">{item.status==="unread"?<button onClick={()=>void change(item,"read")}>Mark read</button>:item.status==="read"?<button onClick={()=>void change(item,"unread")}>Mark unread</button>:null}{item.status!=="archived"&&<button onClick={()=>void change(item,"archive")}>Archive</button>}<button onClick={()=>onNavigate((item.entityType==="invoice"||item.entityType==="payment"||item.entityType==="expense")?"finance":item.entityType==="document"?"documents":item.entityType==="task"?"tasks":"projects")}>Open related {item.entityType}</button></div></li>)}</ul>}
 {preferences&&<article><h3>Notification preferences</h3>{([["inAppEnabled","In-app notifications"],["taskEventsEnabled","Task events"],["projectEventsEnabled","Project events"],["financeEventsEnabled","Finance events"],["documentEventsEnabled","Document events"],["dueSoonEnabled","Due-soon reminders"],["overdueEnabled","Overdue reminders"],["selfNotificationsEnabled","Notify me about my own actions"]] as const).map(([key,label])=><label key={key}><input type="checkbox" checked={preferences[key]} onChange={e=>setPreferences({...preferences,[key]:e.target.checked})}/>{label}</label>)}<button onClick={()=>void savePreferences()}>Save notification preferences</button></article>}
 </section>;
}

function DocumentsPage({session}:{session:Session}){
 const [items,setItems]=useState<DocumentContract[]>([]),[targets,setTargets]=useState<Record<string,Array<{id:string;label:string}>>>({}),[versions,setVersions]=useState<Array<{id:string;versionNo:number}>>([]),[selected,setSelected]=useState(""),[entityType,setEntityType]=useState("project"),[entityId,setEntityId]=useState(""),[category,setCategory]=useState("other"),[description,setDescription]=useState(""),[file,setFile]=useState<File|null>(null),[replacement,setReplacement]=useState<File|null>(null),[error,setError]=useState("");
 const load=async()=>{try{const [d,c,p,pr,t,i,pay,e]=await Promise.all([api.documents(),api.list("clients"),api.list("properties"),api.list("projects"),api.list("tasks"),api.invoices(),api.payments(),api.expenses()]),next={client:c.map(x=>({id:x.id,label:x.name})),property:p.map(x=>({id:x.id,label:x.name})),project:pr.map(x=>({id:x.id,label:x.name})),task:t.map(x=>({id:x.id,label:x.title})),invoice:i.map(x=>({id:x.id,label:x.invoiceNumber})),payment:pay.map(x=>({id:x.id,label:x.reference})),expense:e.map(x=>({id:x.id,label:x.supplier}))};setItems(d);setTargets(next);setEntityId(x=>x||next.project[0]?.id||"");setError("");}catch(e){setError(apiErrorMessage(e));}};
 useEffect(()=>{void load();},[]);const document=items.find(x=>x.id===selected),replace=(x:DocumentContract)=>{setItems(v=>v.map(d=>d.id===x.id?x:d));setSelected(x.id);setError("");},fail=(e:unknown)=>setError(apiErrorMessage(e));
 const upload=async(e:React.FormEvent)=>{e.preventDefault();if(!file){setError("Choose a file.");return;}try{const x=await api.uploadDocument(file,{category,description,entityType,entityId});setItems(v=>[x,...v]);setSelected(x.id);setVersions([{id:x.currentVersion.id,versionNo:1}]);setFile(null);setError("");}catch(x){fail(x);}};
 const download=async(versionId?:string)=>{try{const x=await api.downloadDocument(document!.id,versionId),url=URL.createObjectURL(x.blob),a=window.document.createElement("a");a.href=url;a.download=document!.currentVersion.originalFilename;a.click();URL.revokeObjectURL(url);}catch(x){fail(x);}};
 return <section><h2>Documents</h2>{error&&<p role="alert">{error}</p>}<button onClick={()=>void load()}>Reload Documents</button>{can(session,"documents.create")&&<form onSubmit={upload}><label>Target type<select aria-label="Document target type" value={entityType} onChange={e=>{setEntityType(e.target.value);setEntityId(targets[e.target.value]?.[0]?.id??"");}}>{["client","property","project","task","invoice","payment","expense"].map(x=><option key={x}>{x}</option>)}</select></label><label>Target entity<select aria-label="Document target" value={entityId} onChange={e=>setEntityId(e.target.value)}>{(targets[entityType]??[]).map(x=><option value={x.id} key={x.id}>{x.label}</option>)}</select></label><label>Document category<select value={category} onChange={e=>setCategory(e.target.value)}>{["contract","offer","invoice","receipt","project_plan","photo","protocol","permit","correspondence","other"].map(x=><option key={x}>{x}</option>)}</select></label><label>Document description<input value={description} onChange={e=>setDescription(e.target.value)}/></label><label>Document file<input aria-label="Document file" type="file" accept=".pdf,.png,.jpg,.jpeg" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><button disabled={!file||!entityId}>Upload document</button></form>}<ul>{items.map(d=><li key={d.id}><button onClick={()=>{setSelected(d.id);void api.documentVersions(d.id).then(setVersions).catch(fail);}}>{d.currentVersion.originalFilename}</button> — {d.category} — version {d.version}</li>)}</ul>{document&&<article><h3>Document detail {document.currentVersion.originalFilename}</h3><p>Category {document.category}; description {document.description??"none"}; file version {document.currentVersionNo}; record version {document.version}; checksum {document.currentVersion.checksum}</p><button onClick={()=>void download()}>Download document</button>{!document.archivedAt&&can(session,"documents.update")&&<><button onClick={()=>void api.updateDocument(document.id,{expectedVersion:document.version,description:"Edited in Web"}).then(replace).catch(fail)}>Edit document metadata</button><label>New document version<input aria-label="New document version" type="file" accept=".pdf,.png,.jpg,.jpeg" onChange={e=>setReplacement(e.target.files?.[0]??null)}/></label><button disabled={!replacement} onClick={()=>replacement&&void api.uploadDocumentVersion(document.id,replacement,document.version).then(x=>{replace(x);return api.documentVersions(x.id);}).then(setVersions).catch(fail)}>Upload new version</button></>}{!document.archivedAt&&can(session,"documents.delete")&&<button onClick={()=>void api.archiveDocument(document.id,document.version).then(replace).catch(fail)}>Archive document</button>}<h4>Versions</h4><ul>{versions.map(v=><li key={v.id}>Version {v.versionNo} <button onClick={()=>void download(v.id)}>Download version {v.versionNo}</button></li>)}</ul></article>}</section>;
}

function FinancePage({session}:{session:Session}){
  const [invoices,setInvoices]=useState<InvoiceContract[]>([]),[payments,setPayments]=useState<PaymentContract[]>([]),[expenses,setExpenses]=useState<ExpenseContract[]>([]),[clients,setClients]=useState<EntityByResource["clients"][]>([]),[projects,setProjects]=useState<ProjectContract[]>([]);
  const [clientId,setClientId]=useState(""),[projectId,setProjectId]=useState(""),[number,setNumber]=useState(""),[net,setNet]=useState("0.0000"),[vat,setVat]=useState("23.0000"),[error,setError]=useState(""),[selectedInvoice,setSelectedInvoice]=useState(""),[selectedPayment,setSelectedPayment]=useState(""),[selectedExpense,setSelectedExpense]=useState(""),[reference,setReference]=useState(""),[paymentAmount,setPaymentAmount]=useState("0.0000"),[allocationAmount,setAllocationAmount]=useState("0.0000"),[supplier,setSupplier]=useState(""),[category,setCategory]=useState("materials"),[summary,setSummary]=useState<ProjectFinancialSummary|null>(null);
  const load=async()=>{try{const [i,pay,e,c,p]=await Promise.all([api.invoices(),api.payments(),api.expenses(),api.list("clients"),api.list("projects")]);setInvoices(i);setPayments(pay);setExpenses(e);setClients(c);setProjects(p);setClientId(x=>x||c[0]?.id||"");setProjectId(x=>x||p[0]?.id||"");setError("");}catch(e){setError(apiErrorMessage(e));}};
  useEffect(()=>{void load();},[]);
  const fail=(x:unknown)=>setError(apiErrorMessage(x)),replaceInvoice=(x:InvoiceContract)=>{setInvoices(v=>v.map(i=>i.id===x.id?x:i));setSelectedInvoice(x.id);setError("");},replacePayment=(x:PaymentContract)=>{setPayments(v=>v.map(i=>i.id===x.id?x:i));setSelectedPayment(x.id);setError("");},replaceExpense=(x:ExpenseContract)=>{setExpenses(v=>v.map(i=>i.id===x.id?x:i));setSelectedExpense(x.id);setError("");};
  const currency=projects.find(p=>p.id===projectId)?.currencyCode??"EUR",today=new Date().toISOString().slice(0,10);
  const createInvoice=async(e:React.FormEvent)=>{e.preventDefault();try{const x=await api.createInvoice({clientId,projectId:projectId||null,invoiceNumber:number,currencyCode:currency,issueDate:today,dueDate:new Date(Date.now()+1209600000).toISOString().slice(0,10),netAmount:net,vatRate:vat});setInvoices(v=>[x,...v]);setNumber("");setSelectedInvoice(x.id);}catch(x){fail(x);}};
  const createPayment=async(e:React.FormEvent)=>{e.preventDefault();try{const x=await api.createPayment({clientId,reference,currencyCode:currency,amount:paymentAmount,paymentDate:today});setPayments(v=>[x,...v]);setReference("");setSelectedPayment(x.id);}catch(x){fail(x);}};
  const createExpense=async(e:React.FormEvent)=>{e.preventDefault();try{const x=await api.createExpense({projectId:projectId||null,supplier,category,expenseDate:today,currencyCode:currency,netAmount:net,vatRate:vat});setExpenses(v=>[x,...v]);setSupplier("");setSelectedExpense(x.id);}catch(x){fail(x);}};
  const invoice=invoices.find(x=>x.id===selectedInvoice),payment=payments.find(x=>x.id===selectedPayment),expense=expenses.find(x=>x.id===selectedExpense);
  return <section><h2>Finance</h2>{error&&<p role="alert">{error}</p>}<div className="toolbar"><button onClick={()=>void load()}>Reload Finance</button><label>Client selector<select aria-label="Finance client" value={clientId} onChange={e=>setClientId(e.target.value)}>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Project selector<select aria-label="Finance project" value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">No project</option>{projects.filter(p=>!clientId||p.clientId===clientId).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div>
    <h3>Invoices</h3>{can(session,"finance.create")&&<form onSubmit={createInvoice}><label>Invoice number<input value={number} onChange={e=>setNumber(e.target.value)} required/></label><label>Invoice net amount<input value={net} onChange={e=>setNet(e.target.value)} required/></label><label>Invoice VAT rate<input value={vat} onChange={e=>setVat(e.target.value)} required/></label><button>Create invoice</button></form>}<ul>{invoices.map(i=><li key={i.id}><button onClick={()=>setSelectedInvoice(i.id)}>{i.invoiceNumber}</button> — {i.status} — paid {i.paidAmount}, outstanding {i.outstandingAmount}</li>)}</ul>
    {invoice&&<article><h4>Invoice detail {invoice.invoiceNumber}</h4><p>Status {invoice.status}; net {invoice.netAmount}; VAT {invoice.vatAmount}; gross {invoice.grossAmount}; paid {invoice.paidAmount}; outstanding {invoice.outstandingAmount}; version {invoice.version}</p>{invoice.status==="draft"&&can(session,"finance.update")&&<><button onClick={()=>void api.updateInvoice(invoice.id,{expectedVersion:invoice.version,notes:"Edited in Web"}).then(replaceInvoice).catch(fail)}>Edit invoice</button><button onClick={()=>void api.invoiceAction(invoice.id,"issue",invoice.version).then(replaceInvoice).catch(fail)}>Issue invoice</button></>}{["draft","issued"].includes(invoice.status)&&can(session,"finance.update")&&<button onClick={()=>void api.invoiceAction(invoice.id,"cancel",invoice.version).then(replaceInvoice).catch(fail)}>Cancel invoice</button>}{invoice.status!=="archived"&&can(session,"finance.delete")&&<button onClick={()=>void api.archiveInvoice(invoice.id,invoice.version).then(replaceInvoice).catch(fail)}>Archive invoice</button>}</article>}
    <h3>Payments</h3>{can(session,"finance.create")&&<form onSubmit={createPayment}><label>Payment reference<input value={reference} onChange={e=>setReference(e.target.value)} required/></label><label>Payment amount<input value={paymentAmount} onChange={e=>setPaymentAmount(e.target.value)} required/></label><button>Create payment</button></form>}<ul>{payments.map(p=><li key={p.id}><button onClick={()=>setSelectedPayment(p.id)}>{p.reference}</button> — {p.status} — allocated {p.allocatedAmount}, available {p.unallocatedAmount}</li>)}</ul>
    {payment&&<article><h4>Payment detail {payment.reference}</h4><p>Status {payment.status}; amount {payment.amount}; allocated {payment.allocatedAmount}; available {payment.unallocatedAmount}; version {payment.version}</p>{payment.status==="received"&&can(session,"finance.update")&&<><label>Invoice allocation<select aria-label="Allocation invoice" value={selectedInvoice} onChange={e=>setSelectedInvoice(e.target.value)}>{invoices.filter(i=>i.clientId===payment.clientId&&i.currencyCode===payment.currencyCode&&["issued","partially_paid"].includes(i.status)).map(i=><option key={i.id} value={i.id}>{i.invoiceNumber}</option>)}</select></label><label>Allocation amount<input value={allocationAmount} onChange={e=>setAllocationAmount(e.target.value)}/></label><button onClick={()=>selectedInvoice&&void api.allocatePayment(payment.id,selectedInvoice,allocationAmount,payment.version).then(replacePayment).then(()=>void load()).catch(fail)}>Allocate payment</button><button onClick={()=>void api.reversePayment(payment.id,payment.version).then(replacePayment).then(()=>void load()).catch(fail)}>Reverse payment</button></>}{payment.status!=="archived"&&can(session,"finance.delete")&&<button onClick={()=>void api.archivePayment(payment.id,payment.version).then(replacePayment).catch(fail)}>Archive payment</button>}</article>}
    <h3>Expenses</h3>{can(session,"finance.create")&&<form onSubmit={createExpense}><label>Expense supplier<input value={supplier} onChange={e=>setSupplier(e.target.value)} required/></label><label>Expense category<input value={category} onChange={e=>setCategory(e.target.value)} required/></label><button>Create expense</button></form>}<ul>{expenses.map(e=><li key={e.id}><button onClick={()=>setSelectedExpense(e.id)}>{e.supplier}</button> — {e.status} — {e.grossAmount} {e.currencyCode}</li>)}</ul>
    {expense&&<article><h4>Expense detail {expense.supplier}</h4><p>Status {expense.status}; category {expense.category}; gross {expense.grossAmount}; version {expense.version}</p>{expense.status==="draft"&&can(session,"finance.update")&&<><button onClick={()=>void api.updateExpense(expense.id,{expectedVersion:expense.version,notes:"Edited in Web"}).then(replaceExpense).catch(fail)}>Edit expense</button><button onClick={()=>void api.expenseAction(expense.id,"approve",expense.version).then(replaceExpense).catch(fail)}>Approve expense</button><button onClick={()=>void api.expenseAction(expense.id,"reject",expense.version).then(replaceExpense).catch(fail)}>Reject expense</button></>}{expense.status!=="archived"&&can(session,"finance.delete")&&<button onClick={()=>void api.archiveExpense(expense.id,expense.version).then(replaceExpense).catch(fail)}>Archive expense</button>}</article>}
    <h3>Project financial summary</h3><button disabled={!projectId} onClick={()=>projectId&&void api.projectFinancialSummary(projectId).then(setSummary).catch(fail)}>Load financial summary</button>{summary&&<article><p>Budget {summary.budget??"not set"} {summary.currencyCode}</p><p>Invoiced {summary.invoicedGross}; paid {summary.paid}; outstanding {summary.outstanding}; expenses {summary.expenses}</p><p>Margin amount {summary.grossMarginAmount}; margin percentage {summary.grossMarginPercentage??"not applicable"}; overdue {summary.overdueInvoiceCount} / {summary.overdueInvoiceAmount}</p></article>}
  </section>;
}

export function App():JSX.Element{
  const [session,setSession]=useState<Session|null>(auth.get()),[page,setPage]=useState<Page>("dashboard"),[unread,setUnread]=useState(0);
  useEffect(()=>{if(session)void api.me().catch(()=>{auth.set(null);setSession(null);});},[session]);
  useEffect(()=>{if(!session)return;let active=true;const refresh=()=>void api.unreadCount().then(x=>active&&setUnread(x.count)).catch(()=>undefined);refresh();const timer=window.setInterval(refresh,Math.max(5000,Number(import.meta.env.VITE_NOTIFICATION_POLL_MS??15000)));return()=>{active=false;window.clearInterval(timer);};},[session]);
  if(!session)return <Login onLogin={setSession}/>;
  return <div className="shell"><aside><h1>ODLS</h1><button aria-label={`Notifications, ${unread} unread`} onClick={()=>setPage("notifications")}>Notifications {unread>0&&<span className="badge">{unread}</span>}</button>{nav.filter(([,key])=>key!=="reports"||can(session,"reports.read")).filter(([,key])=>key!=="dashboard"||can(session,"dashboard.read")).map(([label,key])=><button key={key} onClick={()=>setPage(key)}>{label}</button>)}<button onClick={async()=>{await api.logout();auth.set(null);setSession(null);}}>Logout</button></aside><main><header>{session.user.displayName} · {session.user.email}</header>{page==="dashboard"?<Dashboard session={session}/>:page==="reports"?<Reports session={session}/>:page==="finance"?<FinancePage session={session}/>:page==="documents"?<DocumentsPage session={session}/>:page==="notifications"?<NotificationCenter onNavigate={setPage} onUnread={setUnread}/>:<ResourcePage key={page} resource={page} session={session}/>}</main></div>;
}
