import{renderToStaticMarkup}from"react-dom/server";import{afterEach,beforeEach,describe,expect,it,vi}from"vitest";import{EmptyState,FingerprintDisplay,LoadingState,OptimisticConflict,SnapshotCard,StatusBadge,hasPermission,statusLabel}from"./construction-ui.js";import{ApiError,api,apiErrorMessage,auth}from"./api.js";
const session={accessToken:"access",refreshToken:"refresh",user:{id:"u",email:"u@example.com",displayName:"User"},permissions:["projects.read","design_projects.read"]};
describe("construction UI foundation",()=>{
 beforeEach(()=>auth.set(session));afterEach(()=>{auth.set(null);vi.unstubAllGlobals()});
 it("renders semantic lifecycle status with text",()=>{const html=renderToStaticMarkup(<StatusBadge status="ready_for_approval"/>);expect(html).toContain("Ready For Approval");expect(html).toContain("status-ready_for_approval")});
 it("renders intentional loading and empty states",()=>{expect(renderToStaticMarkup(<LoadingState label="Loading project"/>)).toContain('role="status"');expect(renderToStaticMarkup(<EmptyState title="No records" detail="Start here"/>)).toContain("No records")});
 it("renders immutable snapshot metadata without raw content",()=>{const html=renderToStaticMarkup(<SnapshotCard title="Approved design" snapshot={{id:"s",contentFingerprint:"a".repeat(64),schemaVersion:"design-project-v1",approvedAt:"2026-01-01T00:00:00Z",content:{secret:"not-rendered"}}}/>);expect(html).toContain("Immutable snapshot");expect(html).toContain("design-project-v1");expect(html).not.toContain("not-rendered")});
 it("truncates fingerprints visually while preserving the full title",()=>{const value="b".repeat(64),html=renderToStaticMarkup(<FingerprintDisplay value={value}/>);expect(html).toContain(`title="${value}"`);expect(html).not.toContain(`>${value}<`)});
 it("provides a clear optimistic conflict recovery action",()=>{const html=renderToStaticMarkup(<OptimisticConflict onReload={()=>undefined}/>);expect(html).toContain("changed by another user");expect(html).toContain("Reload authoritative data")});
 it("uses exact backend permissions",()=>{expect(hasPermission(session,"design_projects.read")).toBe(true);expect(hasPermission(session,"design_projects.approve")).toBe(false);expect(statusLabel("review_required")).toBe("Review Required")});
 it("normalizes forbidden and conflict API errors",()=>{expect(apiErrorMessage(new ApiError(403,"FORBIDDEN"))).toContain("permission");expect(apiErrorMessage(new ApiError(409,"VERSION_CONFLICT"))).toContain("Reload")});
 it("uses server-side project pagination and project-scoped workflow reads",async()=>{vi.stubGlobal("fetch",vi.fn(async input=>new Response(JSON.stringify(String(input).includes("/projects?")?{data:[],pagination:{page:2,pageSize:10,total:11,totalPages:2}}:{data:[]}),{status:200,headers:{"content-type":"application/json"}})));await api.projectsPage("page=2&pageSize=10&sortBy=updatedAt&sortOrder=desc");await api.technicalAssignments("00000000-0000-4000-8000-000000000071");await api.designProjects("00000000-0000-4000-8000-000000000071");const urls=vi.mocked(fetch).mock.calls.map(x=>String(x[0]));expect(urls[0]).toContain("page=2&pageSize=10");expect(urls[1]).toContain("technical-assignments?projectId=");expect(urls[2]).toContain("design-projects?projectId=")});
 it("sends optimistic versions and never retries mutations",async()=>{vi.stubGlobal("fetch",vi.fn(async()=>new Response(JSON.stringify({data:{id:"x"}}),{status:200,headers:{"content-type":"application/json"}})));await api.updateDesignDecision("design","decision",{expectedVersion:7,title:"Revised"});const call=vi.mocked(fetch).mock.calls[0],body=JSON.parse(String((call[1]as RequestInit).body));expect(body).toEqual({expectedVersion:7,title:"Revised"});expect(call[1]?.method).toBe("PATCH");expect(fetch).toHaveBeenCalledTimes(1)});
});
