import{describe,expect,it}from"vitest";
import type{CommercialEstimateDto,CompanyPriceBookDto,MaterialConsumptionDto,RegionalPricingDto,Session}from"./api.js";
import{commercialEstimateAdapter,companyPriceBookAdapter,companyPriceBookApproval}from"./omniro-building-adapters.js";
import{buildingFlowDefinitions}from"./omniro-building-flows.js";
import{buildingModuleRegistry}from"./omniro-building-modules.js";
import{buildingWorkspaceRegistry}from"./omniro-building-workspaces.js";

const session:Session={accessToken:"x",refreshToken:"x",user:{id:"u",email:"u@example.test",displayName:"Reviewer"},permissions:["company_price_books.read","company_price_books.approve"]};
const snapshot={id:"cpbs",contentFingerprint:"a".repeat(64),revisionNumber:1};
const book:CompanyPriceBookDto={id:"cpb",code:"CPB-1",title:"Company prices",purpose:null,revisionId:"cpbr",revisionNumber:1,status:"ready_for_approval",currency:"PLN",effectiveFrom:"2026-01-01",effectiveTo:null,version:3,entries:[]};
const regional:RegionalPricingDto={id:"rp",code:"RP-1",title:"Regional reference",revisionId:"rpr",revisionNumber:1,status:"approved",currency:"PLN",countryCode:"PL",regionCode:"MAZ",effectiveFrom:"2026-01-01",version:2,customerCategory:"standard",commercialProfile:"standard",priceSource:"quoted",overheadRules:[],marginRules:[],discountRules:[],adjustmentRules:[],calculationVersion:"v1",entries:[],approvedSnapshot:{id:"rps",contentFingerprint:"b".repeat(64)}};
const consumption={id:"mc",projectId:"p",code:"MC",title:"Approved quantities",revisionNumber:1,status:"approved",version:2,workScopeSnapshotId:"scope",normSnapshotId:"norm",knowledgeVersionId:"knowledge",technologyVersionId:"technology",workItemId:"scope-item",evaluatedParameters:{},workQuantity:10,workQuantityUnit:"M2",revisionId:"mc-revision",lines:[],approvedSnapshot:{id:"mc-snapshot",contentFingerprint:"c".repeat(64)}}as MaterialConsumptionDto;
const estimate={id:"ce",projectId:"p",code:"CE",title:"Company offer",revisionId:"ce-revision",revisionNumber:1,status:"draft",mode:"tender",currency:"PLN",version:1,pricingAuthority:"company_price_book_v1",companyPriceBookAuthority:{priceBookId:"cpb",revisionId:"cpbr",revisionNumber:1,snapshotId:"cpbs",fingerprint:"a".repeat(64)},regionalPricingReference:{snapshotId:"rps",role:"comparison_only"},totals:{laborCost:180,materialCost:80,equipmentCost:0,otherCost:0,overhead:0,internalCost:260,unitPrice:42,netTotal:420,discountAmount:0,vatAmount:0,grossTotal:420,profit:160,marginPercent:38.0952,currency:"PLN"},lines:[],analysis:{estimateId:"ce",status:"draft",complete:true,pricingAuthority:"company_price_book_v1",profitability:{profit:160,marginPercent:38.0952,negativeProfit:false},sourceSnapshots:{materialConsumptionSnapshotId:"mc-snapshot",pricingSnapshotId:"rps",regionalPricingRole:"comparison_only",companyPriceBookId:"cpb",companyPriceBookRevisionId:"cpbr",companyPriceBookRevisionNumber:1,companyPriceBookSnapshotId:"cpbs",companyPriceBookFingerprint:"a".repeat(64)},recommendations:[],mutatedData:false,approvedDataChanged:false}}as CommercialEstimateDto;
const sources=(books:CompanyPriceBookDto[]=[],failures:string[]=[],estimates:CommercialEstimateDto[]=[])=>({project:{id:"p"},scans:[],assignments:[],designs:[],technologies:[],workScopes:[],engineeringNorms:[],materialConsumptions:[consumption],regionalPricings:[regional],companyPriceBooks:books,commercialEstimates:estimates,sourceFailures:failures});

describe("Company Price Book Command Center runtime",()=>{
 it("is unavailable without company_price_books.read",()=>{expect(companyPriceBookAdapter.resolve({projectId:"p",session:{...session,permissions:[]},sources:sources()as never})).toMatchObject({truth:"UNAVAILABLE",availability:"unavailable"})});
 it("is REAL with a grounded not-started state when the backend list is empty",()=>{expect(companyPriceBookAdapter.resolve({projectId:"p",session,sources:sources()as never})).toMatchObject({truth:"REAL",availability:"available",status:"not_started",reason:expect.stringContaining("has not invented")})});
 it("is PARTIAL when the authoritative API source fails",()=>{expect(companyPriceBookAdapter.resolve({projectId:"p",session,sources:sources([],['company-price-book'])as never})).toMatchObject({truth:"PARTIAL",availability:"partial"})});
 it("maps ready_for_approval to an independent human authority gate",()=>{const state=companyPriceBookAdapter.resolve({projectId:"p",session,sources:sources([book])as never});expect(state).toMatchObject({truth:"REAL",lifecycle:"APPROVAL_REQUIRED",record:{entityId:"cpb",version:3}});expect(companyPriceBookApproval.detect(state,session)).toMatchObject({permitted:true,permission:"company_price_books.approve",openWorkspaceId:"company-price-book",downstreamModuleId:"commercial-estimate"});expect(companyPriceBookApproval.detect(state,session)?.consequence).toContain("explicitly select")});
 it("adds immutable snapshot evidence for an approved authority",()=>{const approved={...book,status:"approved"as const,approvedSnapshot:snapshot},state=companyPriceBookAdapter.resolve({projectId:"p",session,sources:sources([approved])as never});expect(state.evidence).toContainEqual(expect.objectContaining({entityType:"approved-company-price-book-snapshot",entityId:"cpbs"}))});
 it("registers a REAL lazy deep-link workspace",()=>{expect(buildingModuleRegistry.require("company-price-book")).toMatchObject({defaultTruth:"REAL",workspace:{routeSegment:"company-price-book"}});expect(buildingWorkspaceRegistry.get("company-price-book")).toMatchObject({routeSegment:"company-price-book",requiredPermissions:["company_price_books.read"]})});
 it("registers Regional Pricing comparison and explicit Company Price Book authority flows",()=>{expect(buildingFlowDefinitions.find(x=>x.id==="regional-pricing:company-price-book")).toMatchObject({relation:"context",payloadType:"approved-regional-pricing-snapshot"});expect(buildingFlowDefinitions.find(x=>x.id==="company-price-book:commercial-estimate")).toMatchObject({relation:"authority",payloadType:"approved-company-price-book-snapshot",approvalBoundary:{moduleId:"company-price-book"}})});
 it("activates the comparison flow only with both readable approved snapshots",()=>{const approved={...book,status:"approved"as const,approvedSnapshot:snapshot},bookState=companyPriceBookAdapter.resolve({projectId:"p",session,sources:sources([approved])as never}),flow=buildingFlowDefinitions.find(x=>x.id==="regional-pricing:company-price-book")!,runtime={projectId:"p",modules:new Map([["company-price-book",bookState]]),loadedAt:"2026-01-01"};expect(flow.resolve({projectId:"p",session,sources:sources([approved])as never},runtime)).toMatchObject({truth:"DERIVED",state:"available",reason:expect.stringContaining("No price inheritance")});expect(flow.resolve({projectId:"p",session,sources:sources([])as never},{...runtime,modules:new Map([["company-price-book",companyPriceBookAdapter.resolve({projectId:"p",session,sources:sources()as never})]])})).toMatchObject({truth:"UNAVAILABLE",state:"blocked"})});
 it("activates Company Price Book → Commercial Estimate only from the exact persisted snapshot relationship",()=>{const approved={...book,status:"approved"as const,approvedSnapshot:snapshot},allSources=sources([approved],[],[estimate]),modules=new Map<string,any>([["company-price-book",companyPriceBookAdapter.resolve({projectId:"p",session,sources:allSources as never})],["commercial-estimate",commercialEstimateAdapter.resolve({projectId:"p",session:{...session,permissions:[...session.permissions,"commercial_estimates.read"]},sources:allSources as never})]]),flow=buildingFlowDefinitions.find(x=>x.id==="company-price-book:commercial-estimate")!,runtime={projectId:"p",modules,loadedAt:"2026-01-01"};expect(flow.resolve({projectId:"p",session,sources:allSources as never},runtime)).toMatchObject({truth:"DERIVED",state:"available",evidence:expect.arrayContaining([expect.objectContaining({entityId:"cpbs"}),expect.objectContaining({entityId:"mc-snapshot"})])});const mismatched=sources([{...approved,approvedSnapshot:{...snapshot,id:"other"}}],[],[estimate]);expect(flow.resolve({projectId:"p",session,sources:mismatched as never},runtime)).toMatchObject({truth:"UNAVAILABLE",state:"blocked"})});
});
