import type{DocumentContract,ExpenseContract,InvoiceContract,NotificationContract,ProjectContract,ProjectFinancialSummary,TaskContract}from"@odls/contracts";
import type{CommercialEstimateDto,Session,UserSummary}from"./api.js";
import{buildingModuleRegistry}from"./omniro-building-modules.js";
import type{OmniroLifecycle,OmniroRuntimeSnapshot,OmniroTruth}from"./omniro-module-contract.js";

export type DirectorSourceKey="tasks"|"documents"|"notifications"|"users"|"finance";
export type DirectorSourceState={truth:OmniroTruth;reason:string};
export type DirectorSources={tasks:TaskContract[];documents:DocumentContract[];notifications:NotificationContract[];users:UserSummary[];invoices:InvoiceContract[];expenses:ExpenseContract[];financialSummaries:ProjectFinancialSummary[];sourceState:Record<DirectorSourceKey,DirectorSourceState>};
export type DirectorTarget={kind:"module"|"workspace"|"project"|"task"|"document"|"finance"|"notifications"|"reports";moduleId?:string;projectId?:string;entityId?:string};
export type DirectorPriorityAction={id:string;truth:"REAL"|"DERIVED";source:string;title:string;reason:string;urgency:"critical"|"high"|"normal";status:string;projectId?:string;responsiblePerson?:string;responsibleRole?:string;target:DirectorTarget;provenance:readonly string[]};
export type DirectorMetric={id:string;label:string;value:string;truth:OmniroTruth;reason:string};
export type DirectorBriefingItem={id:string;label:string;reason:string;target:DirectorTarget;provenance:readonly string[]};
export type DirectorPerson={id:string;displayName:string;email:string;active:boolean;responsibilities:readonly string[];truth:"REAL"|"DERIVED"};
export type DirectorProjection={metrics:DirectorMetric[];priorityActions:DirectorPriorityAction[];decisions:DirectorPriorityAction[];briefing:DirectorBriefingItem[];people:DirectorPerson[];currentFinancial?:ProjectFinancialSummary;commercialAnalysis?:{estimateId:string;code:string;marginPercent:number|null;profit:number|null;currency:string;truth:"REAL";reason:string};calendar:{truth:"PARTIAL";items:Array<{id:string;label:string;date:string;target:DirectorTarget;provenance:string}>;reason:string};legal:{truth:"PARTIAL";documents:number;auditTruth:"PARTIAL";reason:string}};

const attentionLifecycles=new Set<OmniroLifecycle>(["WAIT","APPROVAL_REQUIRED","CONFLICT","BLOCKED"]);
const urgencyFor=(lifecycle:OmniroLifecycle):DirectorPriorityAction["urgency"]=>lifecycle==="CONFLICT"||lifecycle==="BLOCKED"?"critical":lifecycle==="APPROVAL_REQUIRED"?"high":"normal";
const projectName=(projects:readonly ProjectContract[],id?:string)=>projects.find(item=>item.id===id)?.name;
const assignee=(task:TaskContract)=>task.assignees[0]?.displayName;
const responsibleRole=(task:TaskContract)=>task.assignees.length?"Task assignee":"No authoritative assignment";

export function buildDirectorProjection(session:Session,projects:readonly ProjectContract[],runtimes:ReadonlyMap<string,OmniroRuntimeSnapshot>,sources:DirectorSources,currentProjectId=projects[0]?.id):DirectorProjection{
 const actions:DirectorPriorityAction[]=[];
 for(const[projectId,runtime]of runtimes)for(const state of runtime.modules.values())if(attentionLifecycles.has(state.lifecycle)){const definition=buildingModuleRegistry.get(state.moduleId),approval=definition?.approval?.detect(state,session);actions.push({id:`module:${projectId}:${state.moduleId}:${state.record?.entityId??state.status}`,truth:"REAL",source:definition?.label??state.moduleId,title:`${definition?.label??state.moduleId} · ${projectName(projects,projectId)??projectId}`,reason:state.reason,urgency:urgencyFor(state.lifecycle),status:state.lifecycle,responsibleRole:"No authoritative assignment",projectId,target:{kind:approval?.permitted?"workspace":"module",moduleId:approval?.openWorkspaceId??state.moduleId,projectId,entityId:state.record?.entityId},provenance:state.evidence.map(item=>`${item.entityType}:${item.entityId}${item.version?`:v${item.version}`:""}`)})}
 for(const task of sources.tasks)if(task.isOverdue||task.status==="blocked")actions.push({id:`task:${task.id}`,truth:"REAL",source:"Tasks",title:task.title,reason:task.isOverdue?`Task deadline ${task.dueDate} is overdue.`:"Task lifecycle is blocked.",urgency:task.priority==="urgent"||task.isOverdue?"critical":"high",status:task.status,responsiblePerson:assignee(task),responsibleRole:responsibleRole(task),projectId:task.projectId,target:{kind:"task",entityId:task.id,projectId:task.projectId},provenance:[`task:${task.id}:v${task.version}`,`project:${task.projectId}`]});
 for(const document of sources.documents)if(document.ocrStatus==="failed"||document.aiProcessingStatus==="failed")actions.push({id:`document:${document.id}`,truth:"REAL",source:"Documents",title:document.title,reason:`Document processing requires attention: OCR ${document.ocrStatus}, analysis ${document.aiProcessingStatus}.`,urgency:"high",status:"processing_failed",responsiblePerson:sources.users.find(user=>user.id===document.updatedBy)?.displayName,responsibleRole:"Last document actor",target:{kind:"document",entityId:document.id},provenance:[`document:${document.id}:v${document.version}`,`file:${document.currentVersion.id}:v${document.currentVersionNo}`]});
 for(const notification of sources.notifications)if(notification.status==="unread"&&["critical","warning"].includes(notification.severity))actions.push({id:`notification:${notification.id}`,truth:"REAL",source:"Notifications",title:notification.title,reason:notification.body,urgency:notification.severity==="critical"?"critical":"high",status:notification.eventType,projectId:notification.entityType==="project"?notification.entityId:undefined,target:{kind:notification.entityType==="task"?"task":notification.entityType==="document"?"document":["invoice","payment","expense"].includes(notification.entityType)?"finance":"notifications",entityId:notification.entityId},provenance:[`notification:${notification.id}:v${notification.version}`,`${notification.entityType}:${notification.entityId}`,`event:${notification.sourceEventId}`]});
 actions.sort((a,b)=>({critical:0,high:1,normal:2}[a.urgency]-{critical:0,high:1,normal:2}[b.urgency])||a.title.localeCompare(b.title));
 const decisions=actions.filter(action=>action.target.kind==="workspace");
 const activeProjects=projects.filter(project=>["planned","active","paused"].includes(project.status));
 const attentionProjects=new Set(actions.map(action=>action.projectId).filter(Boolean));
 const approvedEstimates=[...runtimes.values()].flatMap(runtime=>{const observed=runtime.modules.get("commercial-estimate")?.observed;return Array.isArray(observed)?observed as CommercialEstimateDto[]:[]}).filter(item=>item.status==="approved");
 const currentFinancial=sources.financialSummaries.find(item=>item.projectId===currentProjectId);
 const currentRuntime=runtimes.get(currentProjectId??"");
 const estimates=currentRuntime?.modules.get("commercial-estimate")?.observed;
 const commercial=Array.isArray(estimates)?(estimates as CommercialEstimateDto[]).find(item=>item.analysis?.complete)??(estimates as CommercialEstimateDto[])[0]:undefined;
 const users=sources.users.map(user=>{const responsibilities=[...projects.filter(project=>project.projectManagerId===user.id).map(project=>`Project manager · ${project.projectNumber}`),...sources.tasks.filter(task=>task.assignees.some(item=>item.userId===user.id)&&!["completed","cancelled","archived"].includes(task.status)).map(task=>`Task · ${task.title}`)];return{id:user.id,displayName:user.displayName,email:user.email,active:!user.isDisabled,responsibilities,truth:responsibilities.length?"DERIVED"as const:"REAL"as const}});
 const calendar=[...sources.tasks.filter(task=>Boolean(task.dueDate)&&!["completed","cancelled","archived"].includes(task.status)).map(task=>({id:`task:${task.id}`,label:task.title,date:task.dueDate!,target:{kind:"task"as const,entityId:task.id,projectId:task.projectId},provenance:`task:${task.id}:v${task.version}`})),...projects.filter(project=>Boolean(project.expectedCompletionDate)&&!["completed","cancelled","archived"].includes(project.status)).map(project=>({id:`project:${project.id}`,label:`${project.projectNumber} expected completion`,date:project.expectedCompletionDate!,target:{kind:"project"as const,projectId:project.id},provenance:`project:${project.id}:v${project.version}`}))].sort((a,b)=>a.date.localeCompare(b.date));
 const legalDocuments=sources.documents.filter(document=>["contract","permit"].includes(document.category));
 return{metrics:[{id:"active-projects",label:"Active projects",value:String(activeProjects.length),truth:"REAL",reason:"Projects API lifecycle records."},{id:"attention-projects",label:"Projects requiring attention",value:String(attentionProjects.size),truth:"DERIVED",reason:"Projects with grounded priority actions."},{id:"pending-decisions",label:"Pending domain decisions",value:String(decisions.length),truth:"DERIVED",reason:"Existing Module Registry approval adapters."},{id:"overdue-items",label:"Overdue tasks",value:String(sources.tasks.filter(task=>task.isOverdue).length),truth:sources.sourceState.tasks.truth,reason:sources.sourceState.tasks.reason},{id:"approved-estimates",label:"Approved estimates",value:String(approvedEstimates.length),truth:"DERIVED",reason:"Approved Commercial Estimate authority records."}],priorityActions:actions,decisions,briefing:actions.slice(0,5).map(action=>({id:action.id,label:action.title,reason:action.reason,target:action.target,provenance:action.provenance})),people:users,currentFinancial,commercialAnalysis:commercial?{estimateId:commercial.id,code:commercial.code,marginPercent:commercial.analysis?.profitability.marginPercent??commercial.totals.marginPercent,profit:commercial.analysis?.profitability.profit??commercial.totals.profit,currency:commercial.currency,truth:"REAL",reason:"Project Commercial Estimate calculation; not company accounting profit."}:undefined,calendar:{truth:"PARTIAL",items:calendar.slice(0,8),reason:"Task and project deadlines are connected; a complete calendar service is not available."},legal:{truth:"PARTIAL",documents:legalDocuments.length,auditTruth:"PARTIAL",reason:"Contract/permit documents are readable. Audit is enforced by backend services, but no Director audit-log reader API is available."}};
}
