import type{DocumentContract,ProjectContract,TaskContract}from"@odls/contracts";
import type{MaterialConsumptionDto,Session,UserSummary,WorkScopeDto}from"./api.js";
import{buildingModuleRegistry}from"./omniro-building-modules.js";
import type{DirectorSources,DirectorTarget}from"./omniro-director-workspace-model.js";
import type{OmniroLifecycle,OmniroRuntimeSnapshot,OmniroTruth}from"./omniro-module-contract.js";

export type ProjectManagerAttention={id:string;title:string;why:string;location:string;responsibility:string;deadline:string;status:string;urgency:"critical"|"high"|"normal";truth:"REAL"|"DERIVED";target:DirectorTarget;provenance:readonly string[];directorDecision:boolean};
export type ProjectManagerProjection={project:ProjectContract;manager?:UserSummary;metrics:Array<{id:string;label:string;value:string;truth:OmniroTruth;reason:string}>;attention:ProjectManagerAttention[];briefing:ProjectManagerAttention[];tasks:TaskContract[];documents:DocumentContract[];scope?:WorkScopeDto;materials?:MaterialConsumptionDto;financial:DirectorSources["financialSummaries"][number]|undefined;moduleStates:Array<{id:string;label:string;truth:OmniroTruth;lifecycle:OmniroLifecycle;status:string;reason:string;target:DirectorTarget;provenance:readonly string[]}>;drawingIntelligence:{truth:"UNAVAILABLE";reason:string};changeAwareness:{truth:"PARTIAL";reason:string}};

const attentionLifecycles=new Set<OmniroLifecycle>(["WAIT","APPROVAL_REQUIRED","CONFLICT","BLOCKED"]);
const terminalTasks=new Set(["accepted","completed","cancelled","archived"]);
const provenance=(state:ReturnType<OmniroRuntimeSnapshot["modules"]["get"]>)=>state?.evidence.map(item=>`${item.entityType}:${item.entityId}${item.version?`:v${item.version}`:""}`)??[];
const urgency=(lifecycle:OmniroLifecycle):ProjectManagerAttention["urgency"]=>lifecycle==="CONFLICT"||lifecycle==="BLOCKED"?"critical":lifecycle==="APPROVAL_REQUIRED"?"high":"normal";
const assigned=(task:TaskContract)=>task.assignees[0]?.displayName??"UNASSIGNED";

export function buildProjectManagerProjection(session:Session,projects:readonly ProjectContract[],runtimes:ReadonlyMap<string,OmniroRuntimeSnapshot>,sources:DirectorSources,projectId:string):ProjectManagerProjection{
 const project=projects.find(item=>item.id===projectId)??projects[0];if(!project)throw new Error("Project Manager Workspace requires an authoritative project context.");
 const runtime=runtimes.get(project.id),tasks=sources.tasks.filter(item=>item.projectId===project.id),documents=sources.documents.filter(document=>document.links.some(link=>link.entityType==="project"&&link.entityId===project.id)),manager=project.projectManagerId?sources.users.find(user=>user.id===project.projectManagerId):undefined;
 const attention:ProjectManagerAttention[]=[];
 for(const task of tasks)if(task.isOverdue||task.status==="blocked")attention.push({id:`task:${task.id}`,title:task.title,why:task.isOverdue?`Deadline ${task.dueDate} is overdue.`:"Task lifecycle is blocked.",location:"Project task",responsibility:assigned(task),deadline:task.dueDate??"Not available",status:task.status,urgency:task.isOverdue||task.priority==="urgent"?"critical":"high",truth:"REAL",target:{kind:"task",entityId:task.id,projectId:project.id},provenance:[`task:${task.id}:v${task.version}`,`project:${project.id}:v${project.version}`],directorDecision:false});
 for(const state of runtime?.modules.values()??[])if(attentionLifecycles.has(state.lifecycle)){const definition=buildingModuleRegistry.get(state.moduleId),approval=definition?.approval?.detect(state,session),directorDecision=state.lifecycle==="APPROVAL_REQUIRED"&&!approval?.permitted;attention.push({id:`module:${project.id}:${state.moduleId}:${state.record?.entityId??state.status}`,title:definition?.label??state.moduleId,why:state.reason,location:project.name,responsibility:directorDecision?"DIRECTOR DECISION REQUIRED":"Existing domain authority",deadline:"Not available",status:state.lifecycle,urgency:urgency(state.lifecycle),truth:"REAL",target:{kind:approval?.permitted?"workspace":"module",moduleId:approval?.openWorkspaceId??state.moduleId,projectId:project.id,entityId:state.record?.entityId},provenance:provenance(state),directorDecision});}
 for(const document of documents)if(document.ocrStatus==="failed"||document.aiProcessingStatus==="failed")attention.push({id:`document:${document.id}`,title:document.title,why:`Document processing requires attention: OCR ${document.ocrStatus}, analysis ${document.aiProcessingStatus}.`,location:"Explicit project document link",responsibility:sources.users.find(user=>user.id===document.updatedBy)?.displayName??"UNASSIGNED",deadline:"Not available",status:"processing_failed",urgency:"high",truth:"REAL",target:{kind:"document",entityId:document.id,projectId:project.id},provenance:[`document:${document.id}:v${document.version}`,`file:${document.currentVersion.id}:v${document.currentVersionNo}`,`project:${project.id}`],directorDecision:false});
 attention.sort((a,b)=>({critical:0,high:1,normal:2}[a.urgency]-{critical:0,high:1,normal:2}[b.urgency])||a.title.localeCompare(b.title));
 const stateFor=(id:string)=>runtime?.modules.get(id),scopeObserved=stateFor("work-scope")?.observed,materialObserved=stateFor("material-consumption")?.observed;
 const scope=Array.isArray(scopeObserved)?(scopeObserved as WorkScopeDto[])[0]:scopeObserved as WorkScopeDto|undefined,materials=Array.isArray(materialObserved)?(materialObserved as MaterialConsumptionDto[])[0]:materialObserved as MaterialConsumptionDto|undefined;
 const moduleStates=["room-scanner","work-scope","engineering-norms","material-consumption","regional-pricing","company-price-book","commercial-estimate"].flatMap(id=>{const state=stateFor(id),definition=buildingModuleRegistry.get(id);return state&&definition?[{id,label:definition.label,truth:state.truth,lifecycle:state.lifecycle,status:state.status,reason:state.reason,target:{kind:"workspace"as const,moduleId:id,projectId:project.id,entityId:state.record?.entityId},provenance:provenance(state)}]:[]});
 const activeTasks=tasks.filter(item=>!terminalTasks.has(item.status)),financial=sources.financialSummaries.find(item=>item.projectId===project.id);
 return{project,manager,metrics:[{id:"active-tasks",label:"Active tasks",value:String(activeTasks.length),truth:sources.sourceState.tasks.truth,reason:"Project-scoped Tasks API records."},{id:"overdue",label:"Overdue tasks",value:String(tasks.filter(item=>item.isOverdue).length),truth:sources.sourceState.tasks.truth,reason:"Task isOverdue contract."},{id:"blocked",label:"Blocked tasks",value:String(tasks.filter(item=>item.status==="blocked").length),truth:sources.sourceState.tasks.truth,reason:"Task lifecycle records."},{id:"attention",label:"Attention items",value:String(attention.length),truth:"DERIVED",reason:"Deterministic projection of task, document and module lifecycle state."},{id:"documents",label:"Linked documents",value:String(documents.length),truth:sources.sourceState.documents.truth,reason:"Only explicit project document links."}],attention,briefing:attention.slice(0,5),tasks:activeTasks.sort((a,b)=>(a.dueDate??"9999").localeCompare(b.dueDate??"9999")),documents,scope,materials,financial,moduleStates,drawingIntelligence:{truth:"UNAVAILABLE",reason:"Drawing comparison and cross-project learning have no connected authority. Files remain tenant-scoped and permission-scoped."},changeAwareness:{truth:"PARTIAL",reason:"Record versions and updated timestamps are visible; no complete project change-event reader is connected."}};
}
