import{useEffect,useMemo,useState}from"react";
import{livingSequence}from"./omniro-living-sequence.js";
import{flowStateLabel,stageFlows,type StageFlow}from"./omniro-stage-flow.js";
import{OmniroStageScene,stageNodes,type StageNode}from"./omniro-stage-scene.js";
const icons:Record<string,string>={scanner:"⌗",passport:"◇",estimate:"∑",orchestrator:"◎",norms:"§",analytics:"⌁"};
const destinations:Record<string,string>={scanner:"Room Scanner",passport:"Room Scanner",estimate:"Estimate Engine",orchestrator:"OMNIRO Command Center",norms:"Norm Catalog",analytics:"Reports"};
const points:Record<string,[number,number]>={photo:[15,220],OMNIRO:[500,350],scanner:[120,220],passport:[105,335],estimate:[135,495],orchestrator:[885,220],norms:[900,335],analytics:[870,495]};
const routePath=(origin:string,destination:string)=>{const[a,b]=points[origin]??points.OMNIRO,[c,d]=points[destination]??points.OMNIRO;return`M ${a} ${b} C ${(a+c)/2} ${b-58}, ${(a+c)/2} ${d+58}, ${c} ${d}`};
const flowFor=(origin:string,destination:string):StageFlow=>stageFlows.find(item=>item.origin===origin&&item.destination===destination)??{id:`${origin}-${destination}`,origin,destination,semanticType:origin==="estimate"?"Estimate result":"Governed payload",state:"processing",explanation:`The visible ${origin} payload is routed to ${destination} by the Stage 1 demonstration contract.`,capabilitySource:"OMNIRO visual flow contract",demonstration:true};
function FunctionGlyph({id,mode}:{id:string;mode:string}){return <span className={`function-glyph glyph-${id} mode-${mode}`} aria-hidden="true"><b>{icons[id]}</b>{id==="scanner"&&<><i className="scan-document"><u/><u/><u/></i><i className="scan-sweep"/><i className="scan-geometry"><u/><u/><u/><u/></i><em className="scan-fragments">▪ ▫ ▪</em></>}{id==="passport"&&<><i className="passport-frame"/><em>✓</em></>}{id==="norms"&&<><i/><i/><i/><u className="norm-match"/><em>✓</em></>}{id==="estimate"&&<><em>12 × 4</em><i>€48</i><u>Σ</u><span className="estimate-inputs">12 · 4 · ×</span><span className="estimate-result">48</span></>}{id==="analytics"&&<><i/><i/><i/><u className="analytics-trend"/><em>↗</em></>}{id==="orchestrator"&&<><i/><i/><i/></>}</span>}
function OrchestratorPanel({flow,onClose}:{flow:StageFlow;onClose:()=>void}){return <aside className="stage-orchestrator" aria-label="Orchestrator explanation panel"><header><div><small>OMNIRO · GROUNDED ROUTING CONTRACT</small><strong>Why did this flow go to Norms?</strong></div><button aria-label="Close explanation" onClick={onClose}>×</button></header><p>{flow.explanation}</p><dl><div><dt>Input</dt><dd>Verified room evidence</dd></div><div><dt>Reason</dt><dd>Material and work classification requires normative validation.</dd></div><div><dt>Destination</dt><dd>Norms</dd></div><div><dt>Next</dt><dd>Estimate after validation</dd></div><div><dt>Human control</dt><dd>Approval is required before a committed result.</dd></div></dl><small>DEMONSTRATION · describes the visible semantic route · no live project connected</small></aside>}
export function OmniroStageHero({staticMode,onEnter,onReplay,summary}:{staticMode:boolean;onEnter:()=>void;onReplay:()=>void;summary:string}){
 const[stepIndex,setStepIndex]=useState(0),[running,setRunning]=useState(false),[focused,setFocused]=useState(false),[explain,setExplain]=useState(false);const step=livingSequence[stepIndex],active=step.active,path=routePath(step.origin,step.destination),flow=flowFor(step.origin,step.destination),gate=["gate","suspended"].includes(step.mode),approved=step.state==="confirmed";
 useEffect(()=>{if(!running||staticMode||step.duration===0)return;const timer=window.setTimeout(()=>setStepIndex(value=>Math.min(value+1,livingSequence.length-1)),step.duration);return()=>clearTimeout(timer)},[running,staticMode,step.duration,stepIndex]);
 useEffect(()=>{if(step.mode==="explain")setExplain(true);if(step.mode==="workspace"||step.mode==="workspace_ready")setFocused(true)},[step.mode]);
 const related=useMemo(()=>new Set([step.origin,step.destination]),[step]);
 const select=(node:StageNode)=>{setRunning(false);const index=livingSequence.findIndex(item=>item.active===node.id&&item.mode!=="transport");setStepIndex(index>=0?index:0)};
 const start=()=>{setFocused(false);setExplain(false);setStepIndex(0);setRunning(true)};
 return <section className={`stage-one-hero living-mode-${step.mode} ${focused?"stage-focused":""}`} aria-labelledby="stage-one-title" data-living-step={step.id} data-active-module={active} data-flow-state={step.state}>
  <div className="stage-atmosphere" aria-hidden="true"/><header className="stage-copy"><p className="stage-product">OMNIRO</p><p className="stage-kicker">AI operating system · demonstration</p><h1 id="stage-one-title">Intelligence<br/>that builds<br/><em>the future</em></h1><p>{summary}</p><div className="stage-actions"><button onClick={start}>Run living system <span>▶</span></button><button onClick={onReplay}>Watch birth <span>✦</span></button></div><small>One core. Governed flow. Human authority preserved.</small></header>
  <div className="stage-system" aria-label="Interactive OMNIRO living functional system"><OmniroStageScene staticMode={staticMode} phase={7} activity={step.state}/><div className={`stage-core-label core-${step.state}`}><strong>OMNIRO</strong><small>{step.mode==="route"?"routing intelligence":["compute","validate","scan"].includes(step.mode)?"computing governed state":"living intelligence core"}</small><i/><i/><i/></div>
   {step.origin!==step.destination&&<svg className="semantic-flow-map" viewBox="0 0 1000 700" aria-hidden="true"><path className={`flow-path state-${step.state}`} d={path}/><g className={`payload-cluster state-${step.state} payload-${step.mode}`}><ellipse className="payload-halo" rx="22" ry="15"/><rect className="payload-body" x="-13" y="-8" width="25" height="16" rx="7"/><path className="payload-front" d="M18 0 7 -8 7 8Z"/><circle className="payload-core" r="4"/>{[-20,-25,-31,-37,-44,-52,-61,-71,-82].map((x,index)=><circle className={`payload-particle p${index+1}`} key={x} r={Math.max(1.1,3.8-index*.32)} cx={x} cy={(index%3-1)*(index*.48)}/>)}{[-30,-48,-67].map((x,index)=><rect className={`payload-fragment f${index+1}`} key={x} x={x} y={index%2?5:-7} width={5-index} height="1.5" rx=".5"/>)}<animateMotion dur={step.mode==="created"?"0s":["gate","suspended"].includes(step.mode)?"0s":step.mode==="resume"?"1.1s":step.mode==="receive"?"1.25s":"2.2s"} repeatCount={["created","gate","suspended"].includes(step.mode)?"1":"indefinite"} path={path} rotate="auto" keyPoints={step.mode==="created"?"0.03":["gate","suspended"].includes(step.mode)?"0.56":step.mode==="receive"?"0.68;1":"0;1"} keyTimes={["created","gate","suspended"].includes(step.mode)?"0":"0;1"} calcMode={step.mode==="transport"?"spline":"linear"} keySplines={step.mode==="transport"?".32 0 .18 1":"0 0 1 1"}/></g></svg>}
   {stageNodes.map(node=><button className={`stage-node node-${node.id} ${active===node.id?"is-active is-processing":""} ${!related.has(node.id)&&active!=="OMNIRO"?"is-muted":""}`} key={node.id} onPointerEnter={()=>select(node)} onFocus={()=>select(node)} onClick={()=>{if(active===node.id){setRunning(false);setFocused(true)}else select(node);if(node.id==="orchestrator")setExplain(true)}} aria-pressed={active===node.id}><FunctionGlyph id={node.id} mode={active===node.id?step.mode:"idle"}/><span><strong>{node.label}</strong><small>{active===node.id?step.label:node.detail}</small><b>{active===node.id?flowStateLabel[step.state]:node.status}</b></span></button>)}
   <div className="living-step" role="status" aria-label="Current living system state"><span>{step.id}</span><small>DEMONSTRATION · {flow.semanticType}</small><strong>{step.label}</strong><i>{step.origin} → {step.destination}</i></div>
   {gate&&<div className={`approval-gate suspended ${approved?"approved":""}`}><span>{approved?"✓":"Ⅱ"}</span><strong>{approved?"Human approved":"Human approval required"}</strong><small>{approved?"Gate unlocked · payload ready":"Verified payload suspended · system remains alive"}</small><i className="suspended-payload" aria-hidden="true"><b/><b/><b/></i><button disabled={approved} onClick={()=>{setStepIndex(14);setRunning(false)}}>{approved?"Approved":"Approve and open gate"}</button></div>}
   {step.mode==="route"&&<div className="orchestrator-routing" aria-label="Orchestrator routing"><span>verified evidence</span><b>◎</b><i>Norms</i><i>Estimate</i></div>}
   {focused&&<div className="workspace-transition" role="dialog" aria-label={`${destinations[active]??"Room Scanner"} functional transition`}><FunctionGlyph id={active==="OMNIRO"?"scanner":active} mode="scan"/><button onClick={()=>setFocused(false)}>← Return to living system</button><small>SAME OBJECT · FUNCTIONAL DESTINATION</small><h2>{destinations[active]??"Room Scanner"}</h2><p>The selected orbital object becomes the anchor for the existing secure workspace. Authentication, permissions, browser history and authoritative behavior remain unchanged.</p><button className="enter-workspace" onClick={onEnter}>Continue to secure sign in →</button></div>}
   {explain&&<OrchestratorPanel flow={flowFor("orchestrator","norms")} onClose={()=>{setExplain(false);setStepIndex(17);setRunning(false)}}/>}
  </div>
  <div className="living-timeline" aria-label="Living system sequence">{livingSequence.map((item,index)=><button key={item.id} title={item.label} aria-label={`${item.id} ${item.label}`} aria-pressed={index===stepIndex} onClick={()=>{setRunning(false);setStepIndex(index)}}>{item.id}</button>)}</div>
  <dl className="stage-metrics" aria-label="Living system characteristics"><div><dt>30</dt><dd>Observable states</dd></div><div><dt>DATA</dt><dd>Traveling payload</dd></div><div><dt>100%</dt><dd>Human authority</dd></div><div><dt>Real-time</dt><dd>WebGL system</dd></div><div><dt>Grounded</dt><dd>Visible routing</dd></div></dl>
 </section>}
