import{useEffect,useMemo,useState}from"react";import{api,apiErrorMessage,type Session}from"./api.js";import{roleWorkspaceRegistry}from"./omniro-role-workspace-registry.js";
type Props={session:Session;onBack?:()=>void;onNotifications?:()=>void};
const truth=(value:string)=><span className={`oe-truth truth-${value.toLowerCase()}`}>{value}</span>;
export function derivedProgress(project:any){return project.taskCount>0?Math.round(project.completedTaskCount/project.taskCount*100):null}
export function OmniroClientWorkspace({session,onBack,onNotifications}:Props){const[projects,setProjects]=useState<any[]>([]),[projectId,setProjectId]=useState(""),[data,setData]=useState<any>(),[error,setError]=useState(""),[type,setType]=useState("question"),[subject,setSubject]=useState(""),[description,setDescription]=useState("");const resolved=roleWorkspaceRegistry.resolve("client",session),project=projects.find(item=>item.id===projectId)??projects[0],progress=useMemo(()=>project?derivedProgress(project):null,[project]);
 const loadProjects=async()=>{try{const items=await api.clientProjects();setProjects(items);setProjectId(current=>items.some(item=>item.id===current)?current:items[0]?.id??"");setError("")}catch(problem){setError(apiErrorMessage(problem))}};useEffect(()=>{void loadProjects()},[]);useEffect(()=>{if(project?.id)void api.clientProject(project.id).then(setData).catch(problem=>setError(apiErrorMessage(problem)))},[project?.id]);
 const submit=async(event:React.FormEvent)=>{event.preventDefault();if(!project)return;try{await api.createClientRequest({projectId:project.id,requestType:type,subject,description});setSubject("");setDescription("");setData(await api.clientProject(project.id));setError("")}catch(problem){setError(apiErrorMessage(problem))}};
 const decide=async(item:any,decision:"approved"|"rejected"|"clarification_requested")=>{try{await api.decideClientApproval(item.id,{expectedVersion:item.version,decision});setData(await api.clientProject(project.id));setError("")}catch(problem){setError(apiErrorMessage(problem))}};
 return <main className="oe-client-v1" aria-labelledby="client-title"><header><div>{onBack&&<button onClick={onBack}>← Product World</button>}<small>OMNIRO BUILDING · CLIENT PROJECT CONTEXT</small><h1 id="client-title">Client Workspace</h1><p>Role ≠ actor · {session.user.displayName} · assigned projects only</p></div>{truth(resolved.truth)}</header>{error&&<p role="alert" className="client-error">{error}</p>}
  <nav aria-label="Client workspace sections">{["Overview","Progress","Photos / Evidence","Documents","Estimates / Offers","Changes","Approvals","Invoices","Requests","Contacts","Support"].map(label=><a key={label} href={`#client-${label.toLowerCase().replaceAll(/[^a-z]+/g,"-")}`}>{label}</a>)}</nav>
  <section className="client-project"><label>My projects {truth("REAL")}<select value={project?.id??""} onChange={event=>setProjectId(event.target.value)}>{projects.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{project?<dl><div><dt>Project</dt><dd>{project.name} · {project.projectNumber}</dd></div><div><dt>Object</dt><dd>{project.propertyName} · {project.line1}, {project.city}</dd></div><div><dt>Status</dt><dd>{project.status}</dd></div><div><dt>Project Manager</dt><dd>{project.projectManager??"Not assigned"}</dd></div><div><dt>Expected completion</dt><dd>{project.expectedCompletionDate??"Not specified"}</dd></div></dl>:<p>No project membership is assigned to this actor.</p>}</section>
  {project&&<><section id="client-overview" className="client-grid"><article><h2>Progress {truth(progress===null?"PARTIAL":"DERIVED")}</h2><b>{progress===null?"No task basis":`${progress}%`}</b><p>Derived only from completed versus visible project tasks.</p></article><article><h2>Actions required {truth("REAL")}</h2><b>{data?.approvals?.length??0}</b><p>Only explicit client decisions in this project.</p></article><article><h2>Payment status {truth("REAL")}</h2><b>{project.paymentStatus.replaceAll("_"," ")}</b><p>Online payment provider: UNAVAILABLE.</p></article></section>
   <section id="client-progress" className="client-card"><header><h2>Project progress</h2>{truth("DERIVED")}</header><div className="client-list">{data?.tasks?.length?data.tasks.map((item:any)=><article key={item.id}><b>{item.title}</b><span>{item.status.replaceAll("_"," ")} · {item.dueDate??"no due date"}</span></article>):<p>No task state is available.</p>}</div></section>
   <section id="client-documents" className="client-card"><header><h2>Published documents / evidence</h2>{truth("REAL")}</header><div className="client-list">{data?.documents?.length?data.documents.map((item:any)=><article key={item.id}><b>{item.title}</b><span>{item.category} · published {new Date(item.publishedAt).toLocaleDateString()}</span></article>):<p>No documents have been published for client viewing.</p>}</div><p>Scanner is a shared platform service; access is provided only through permitted project deep links.</p></section>
   <section id="client-estimates-offers" className="client-card"><header><h2>Client estimates / offers</h2>{truth("REAL")}</header>{data?.estimates?.length?data.estimates.map((item:any)=><article key={item.revisionId}><b>{item.title}</b><span>{item.totals?.grossTotal??"Total unavailable"} {item.currency} · revision {item.revisionNumber} · approved snapshot {item.snapshotId}</span></article>):<p>No approved client-version estimate is available.</p>}</section>
   <section id="client-approvals" className="client-card"><header><h2>My approvals</h2>{truth("REAL")}</header>{data?.approvals?.map((item:any)=><article key={item.id}><div><b>{item.title}</b><p>{item.summary}</p></div><div><button onClick={()=>void decide(item,"approved")}>Approve</button><button onClick={()=>void decide(item,"rejected")}>Reject</button><button onClick={()=>void decide(item,"clarification_requested")}>Request clarification</button></div></article>)||<p>No decision requires this client.</p>}</section>
   <section id="client-invoices" className="client-card"><header><h2>Invoices</h2>{truth("REAL")}</header>{data?.invoices?.length?data.invoices.map((item:any)=><article key={item.id}><b>{item.invoiceNumber}</b><span>{item.amount} {item.currency} · due {item.dueDate??"not specified"} · {item.status}</span></article>):<p>No client-visible invoices.</p>}<p>Payment execution provider: UNAVAILABLE.</p></section>
   <section id="client-requests" className="client-card"><header><h2>Requests / changes / issues</h2>{truth("REAL")}</header><form onSubmit={event=>void submit(event)}><select value={type} onChange={event=>setType(event.target.value)}>{["question","issue","change","meeting","document","clarification"].map(item=><option key={item}>{item}</option>)}</select><input aria-label="Request subject" required maxLength={300} value={subject} onChange={event=>setSubject(event.target.value)}/><textarea aria-label="Request description" required maxLength={5000} value={description} onChange={event=>setDescription(event.target.value)}/><button>Submit to project authority</button></form>{data?.requests?.map((item:any)=><article key={item.id}><b>{item.subject}</b><span>{item.requestType} · {item.status} · version {item.version}</span></article>)}</section>
   <section id="client-contacts" className="client-card"><header><h2>Project contacts</h2>{truth("REAL")}</header><p>Project Manager: {project.projectManager??"Not assigned"}</p><p>Site contact visibility: {project.canViewSiteContact?"permitted, no assigned contact returned":"not permitted by project policy"}.</p></section>
   <section className="client-card"><h2>Platform integration states</h2><ul><li>Internal notifications: REAL <button onClick={onNotifications}>Open</button></li><li>AI Secretary / Orchestrator: PARTIAL — permitted-object integration point only.</li><li>Correspondence, Calendar, Notes, Weather, external channels and ephemeral Voice Bridge: UNAVAILABLE.</li><li>Voice conversations are never recorded, stored or archived.</li></ul></section></>}
  <footer><strong>FINAL VISUAL = OWNER APPROVAL REQUIRED</strong></footer></main>}
