import type{ProjectContract,TaskContract}from"@odls/contracts";
import{renderToStaticMarkup}from"react-dom/server";
import{describe,expect,it}from"vitest";
import type{Session}from"./api.js";
import{OmniroDirectorWorkspace}from"./omniro-director-workspace.js";
import{buildDirectorProjection,type DirectorSources}from"./omniro-director-workspace-model.js";
import type{OmniroModuleRuntimeState,OmniroRuntimeSnapshot}from"./omniro-module-contract.js";
import{OmniroRoleWorkspaceRegistry,roleWorkspaceRegistry,type RoleWorkspaceDefinition}from"./omniro-role-workspace-registry.js";

const project:ProjectContract={id:"10000000-0000-4000-8000-000000000001",tenantId:"10000000-0000-4000-8000-000000000002",clientId:"10000000-0000-4000-8000-000000000003",propertyId:"10000000-0000-4000-8000-000000000004",financialOwnerLegalEntityId:"10000000-0000-4000-8000-000000000005",projectManagerId:"10000000-0000-4000-8000-000000000006",projectNumber:"PRJ-024",name:"Office Complex",description:null,status:"active",startDate:"2026-01-01",expectedCompletionDate:"2026-09-30",actualCompletionDate:null,currencyCode:"PLN",estimatedBudget:null,approvedBudget:null,contractValue:null,paymentStatus:"not_required",billingCustomerReference:null,externalPaymentCustomerReference:null,version:4,createdAt:"2026-01-01",updatedAt:"2026-08-01",archivedAt:null};
const permissions=["projects.read","tasks.read","documents.read","notifications.read","users.read","finance.read","reports.read","room_scans.read","company_price_books.read","company_price_books.approve","commercial_estimates.read"];
const session:Session={accessToken:"access",refreshToken:"refresh",user:{id:"10000000-0000-4000-8000-000000000006",email:"director@example.com",displayName:"Director Actor"},permissions};
const task={id:"10000000-0000-4000-8000-000000000007",tenantId:project.tenantId,projectId:project.id,title:"Resolve delivery delay",description:null,status:"blocked",priority:"urgent",dueDate:"2026-08-01",startedAt:null,completedAt:null,isOverdue:true,assignees:[{userId:session.user.id,displayName:session.user.displayName,assignedAt:"2026-07-01"}],version:3,createdAt:"2026-07-01",updatedAt:"2026-08-01",archivedAt:null} satisfies TaskContract;
const approvalState:OmniroModuleRuntimeState={moduleId:"company-price-book",projectId:project.id,truth:"REAL",lifecycle:"APPROVAL_REQUIRED",availability:"available",status:"ready_for_approval",reason:"Company-owned revision requires human approval.",record:{entityType:"company-price-book",entityId:"10000000-0000-4000-8000-000000000008",version:2},evidence:[{entityType:"company-price-book",entityId:"10000000-0000-4000-8000-000000000008",version:2,label:"Revision 2"}]};
const runtime:OmniroRuntimeSnapshot={projectId:project.id,loadedAt:"2026-08-14",modules:new Map([[approvalState.moduleId,approvalState]])};
const sources:DirectorSources={tasks:[task],documents:[],notifications:[],users:[{id:session.user.id,email:session.user.email,displayName:session.user.displayName,isDisabled:false,version:1}],invoices:[],payments:[],expenses:[],financialSummaries:[],sourceState:{tasks:{truth:"REAL",reason:"Authoritative task records loaded."},documents:{truth:"REAL",reason:"Authoritative document records loaded."},notifications:{truth:"REAL",reason:"Authoritative notification records loaded."},users:{truth:"REAL",reason:"Authoritative user records loaded."},finance:{truth:"PARTIAL",reason:"Financial summaries are incomplete."}}};
const props={session,projects:[project],project,runtimes:new Map([[project.id,runtime]]),sources,flows:[],onBack:()=>undefined,onRole:()=>undefined,onProject:()=>undefined,onModule:()=>undefined,onWorkspace:()=>undefined,onContext:()=>undefined};

describe("OMNIRO Director Owner workspace V1",()=>{
 it("resolves the role from permissions while preserving the authenticated actor",()=>{const resolved=roleWorkspaceRegistry.resolve("director",session);expect(resolved).toMatchObject({truth:"REAL",actualActorId:session.user.id,actualActorName:session.user.displayName});expect(roleWorkspaceRegistry.resolve("director",{...session,permissions:[]})).toMatchObject({truth:"UNAVAILABLE",actualActorId:session.user.id})});
 it("keeps active roles permission grounded and future roles unavailable",()=>{expect(roleWorkspaceRegistry.get("accountant")?.status).toBe("active");expect(roleWorkspaceRegistry.resolve("accountant",session).truth).toBe("REAL");expect(roleWorkspaceRegistry.resolve("accountant",{...session,permissions:permissions.filter(item=>item!=="finance.read")}).truth).toBe("UNAVAILABLE");expect(roleWorkspaceRegistry.resolve("project-manager",session).truth).toBe("REAL");expect(roleWorkspaceRegistry.resolve("site-manager",session).truth).toBe("REAL");expect(roleWorkspaceRegistry.resolve("worker",session).truth).toBe("UNAVAILABLE")});
 it("provides a reusable typed role registration extension point",()=>{const fixture:RoleWorkspaceDefinition={roleId:"fixture",label:"Fixture",category:"operations",requiredPermissions:["projects.read"],availableModules:["project"],primaryActions:["open-project"],attentionSources:["projects"],assistantCapabilities:[],communicationCapabilities:[],temporaryAssignmentSupport:false,status:"active"};const registry=new OmniroRoleWorkspaceRegistry([fixture]);expect(registry.resolve("fixture",session).truth).toBe("REAL");expect(()=>new OmniroRoleWorkspaceRegistry([fixture,fixture])).toThrow(/Duplicate OMNIRO role workspace/)});
 it("derives priority actions from authority lifecycle and task records with provenance",()=>{const projection=buildDirectorProjection(session,[project],props.runtimes,sources,project.id);expect(projection.priorityActions.map(item=>item.id)).toEqual([`task:${task.id}`,`module:${project.id}:company-price-book:${approvalState.record?.entityId}`]);expect(projection.priorityActions[0]).toMatchObject({truth:"REAL",responsiblePerson:"Director Actor",urgency:"critical"});expect(projection.priorityActions[0].provenance).toContain(`task:${task.id}:v3`)});
 it("exposes only existing permitted approval adapters in the decision center",()=>{const projection=buildDirectorProjection(session,[project],props.runtimes,sources,project.id);expect(projection.decisions).toHaveLength(1);expect(projection.decisions[0].target).toMatchObject({kind:"workspace",moduleId:"company-price-book",projectId:project.id});const denied=buildDirectorProjection({...session,permissions:permissions.filter(item=>item!=="company_price_books.approve")},[project],props.runtimes,sources,project.id);expect(denied.decisions).toHaveLength(0)});
 it("keeps calendar partial and company accounting analytics unavailable",()=>{const projection=buildDirectorProjection(session,[project],props.runtimes,sources,project.id);expect(projection.calendar.truth).toBe("PARTIAL");expect(projection.calendar.items.map(item=>item.provenance)).toContain(`task:${task.id}:v3`);expect(projection.commercialAnalysis).toBeUndefined()});
 it("shows only project accounting values returned by the Finance authority",()=>{const financial={projectId:project.id,currencyCode:"PLN"as const,budget:"1000.0000",invoicedNet:"500.0000",invoicedVat:"115.0000",invoicedGross:"615.0000",paid:"300.0000",outstanding:"315.0000",expenses:"200.0000",grossMarginAmount:"300.0000",grossMarginPercentage:"60.0000",overdueInvoiceCount:1,overdueInvoiceAmount:"315.0000"},financialSources={...sources,financialSummaries:[financial]};const projection=buildDirectorProjection(session,[project],props.runtimes,financialSources,project.id);expect(projection.currentFinancial).toEqual(financial);const html=renderToStaticMarkup(<OmniroDirectorWorkspace {...props} sources={financialSources}/>);expect(html).toContain("Project accounting summary");expect(html).toContain("project-financial-summary:");expect(html).toContain("615.0000")});
 it("renders grounded limitations instead of synthetic executive KPIs",()=>{const html=renderToStaticMarkup(<OmniroDirectorWorkspace {...props}/>);expect(html).toContain("Director / Owner Workspace");expect(html).toContain(`actor ${session.user.id}`);expect(html).toContain("Resolve delivery delay");expect(html).toContain("Task and project deadlines are connected");expect(html).toContain("No email provider is connected");expect(html).toContain("Company accounting profit is not inferred");expect(html).not.toContain("12.45M");expect(html).not.toContain("18.7%")});
 it("honors missing source permissions and declares temporary assignment unavailable",()=>{const restricted={...session,permissions:["projects.read"]},restrictedSources={...sources,tasks:[],users:[],sourceState:{...sources.sourceState,tasks:{truth:"UNAVAILABLE"as const,reason:"Permission required for tasks source."},users:{truth:"UNAVAILABLE"as const,reason:"Permission required for users source."}}};const html=renderToStaticMarkup(<OmniroDirectorWorkspace {...props} session={restricted} sources={restrictedSources}/>);expect(html).toContain("Temporary access");expect(html).toContain("future backend authority");expect(html).toContain("Permission required for users source.");expect(html).toContain("disabled")});
});
