import type{ProjectContract}from"@odls/contracts";
import type{Session}from"./api.js";
import{OmniroDataFlowLegend,type DataFlowProjection}from"./omniro-data-flow-renderer.js";
import{buildAccountantProjection,type AccountantInboxItem}from"./omniro-accountant-workspace-model.js";
import type{DirectorContextPage}from"./omniro-director-workspace.js";
import type{DirectorSources,DirectorTarget}from"./omniro-director-workspace-model.js";
import type{OmniroRuntimeSnapshot}from"./omniro-module-contract.js";
import{roleWorkspaceRegistry}from"./omniro-role-workspace-registry.js";

type Props={session:Session;projects:ProjectContract[];project:ProjectContract;runtimes:ReadonlyMap<string,OmniroRuntimeSnapshot>;sources:DirectorSources;flows:readonly DataFlowProjection[];onBack:()=>void;onRole:(id:string)=>void;onProject:(id:string)=>void;onModule:(id:string,projectId?:string)=>void;onWorkspace:(id:string,projectId?:string)=>void;onContext:(page:DirectorContextPage,id?:string)=>void};
const truth=(value:string)=><span className={`oe-truth truth-${value.toLowerCase()}`}>{value}</span>;

export function OmniroAccountantWorkspace({session,projects,project,runtimes,sources,flows,onBack,onRole,onModule,onWorkspace,onContext}:Props){
 const resolved=roleWorkspaceRegistry.resolve("accountant",session),projection=buildAccountantProjection(session,projects,runtimes,sources,project.id),can=(permission:string)=>session.permissions.includes(permission);
 const open=(target:DirectorTarget)=>{if(target.kind==="workspace"&&target.moduleId)return onWorkspace(target.moduleId,target.projectId);if(target.kind==="module"&&target.moduleId)return onModule(target.moduleId,target.projectId);if(target.kind==="project")return onContext("project-workspace",target.projectId);if(target.kind==="task")return onContext("tasks",target.entityId);if(target.kind==="document")return onContext("documents",target.entityId);if(target.kind==="finance")return onContext("finance",target.entityId);return onContext("notifications")};
 const item=(entry:AccountantInboxItem)=><button key={entry.id} onClick={()=>open(entry.target)} data-kind={entry.kind}><span><strong>{entry.title}</strong><small>{entry.counterparty}{entry.projectName?` · ${entry.projectName}`:""}</small><em>{entry.reason}</em><em>{entry.responsibility}</em></span><b>{entry.amount?`${entry.amount} ${entry.currency}`:entry.date}<small className={`urgency-${entry.urgency}`}>{entry.status.replaceAll("_"," ")}</small></b><i>{entry.provenance.join(" · ")}</i></button>;
 return <main className="oe-role oe-director-v1 oe-accountant-v1" aria-labelledby="oe-role-title">
  <aside className="oe-role-rail"><small>LAYER 3 · ROLE WORKSPACE</small><button onClick={onBack}>← Back to Product World</button><h2>Role workspaces</h2>{roleWorkspaceRegistry.definitions.map(definition=>{const state=roleWorkspaceRegistry.resolve(definition.roleId,session);return <button key={definition.roleId} disabled={state.truth==="UNAVAILABLE"} className={definition.roleId==="accountant"?"is-current":""} onClick={()=>state.truth!=="UNAVAILABLE"&&onRole(definition.roleId)}>{definition.label}<small>{state.truth}</small></button>})}<h3>Accounting sources</h3><button disabled={!can("finance.read")} onClick={()=>onContext("finance")}>Finance records<small>{sources.sourceState.finance.truth}</small></button><button disabled={!can("documents.read")} onClick={()=>onContext("documents")}>Documents / OCR<small>{sources.sourceState.documents.truth}</small></button><button disabled={!can("notifications.read")} onClick={()=>onContext("notifications")}>Internal notifications<small>{sources.sourceState.notifications.truth}</small></button><section className="oe-temporary-access"><strong>Authority boundary</strong>{truth("REAL")}<p>The workspace never changes the authenticated actor. Mutations remain controlled by existing Finance and module permissions.</p></section></aside>
  <section className="oe-director oe-accountant" aria-label="Accountant organizational workspace"><header><div><small>AUTHENTICATED ACTOR · ROLE ≠ ACTOR</small><h1 id="oe-role-title">Accountant Workspace</h1><p>{session.user.displayName} · actions remain attributed to actor {session.user.id}</p></div>{truth(resolved.truth)}</header><OmniroDataFlowLegend flows={flows} compact/>
   <section className="oe-director-metrics" aria-label="Grounded accounting overview">{projection.metrics.map(metric=><article key={metric.id}><small>{metric.label}</small><strong>{metric.value}</strong><span>{metric.reason}</span>{truth(metric.truth)}</article>)}</section>
   <section className="oe-director-grid oe-accountant-grid">
    <article className="oe-priority-actions oe-accounting-inbox"><header><h2>Accounting inbox</h2><small>WHAT · COUNTERPARTY · PROJECT · DATE · VALUE · STATUS</small></header>{projection.inbox.length?projection.inbox.slice(0,12).map(item):<p>No loaded accounting source reports an actionable state.</p>}</article>
    <article className="oe-financial-summary"><header><h2>Current project finance</h2>{truth(sources.sourceState.finance.truth)}</header>{projection.currentFinancial?<><dl><div><dt>Invoiced</dt><dd>{projection.currentFinancial.invoicedGross} {projection.currentFinancial.currencyCode}</dd></div><div><dt>Paid</dt><dd>{projection.currentFinancial.paid} {projection.currentFinancial.currencyCode}</dd></div><div><dt>Outstanding</dt><dd>{projection.currentFinancial.outstanding} {projection.currentFinancial.currencyCode}</dd></div><div><dt>Expenses</dt><dd>{projection.currentFinancial.expenses} {projection.currentFinancial.currencyCode}</dd></div><div><dt>Overdue invoices</dt><dd>{projection.currentFinancial.overdueInvoiceCount}</dd></div><div><dt>Accounting margin</dt><dd>{projection.currentFinancial.grossMarginAmount} {projection.currentFinancial.currencyCode}</dd></div></dl><small>project-financial-summary:{projection.currentFinancial.projectId}</small><button onClick={()=>onContext("finance",project.id)}>Open Finance</button></>:<p>{sources.sourceState.finance.reason} No company balance, cash position or tax position is inferred.</p>}</article>
    <article className="oe-accounting-register"><header><h2>Operational registers</h2><small>Existing REST authorities</small></header><dl><div><dt>Invoices</dt><dd>{projection.sourceCounts.invoices}<small>{projection.sourceCounts.processedInvoices} processed</small></dd></div><div><dt>Payments</dt><dd>{projection.sourceCounts.payments}<small>{projection.sourceCounts.allocatedPayments} fully allocated</small></dd></div><div><dt>Expenses</dt><dd>{projection.sourceCounts.expenses}<small>{projection.sourceCounts.processedExpenses} approved</small></dd></div><div><dt>Accounting documents</dt><dd>{projection.sourceCounts.documents}<small>{projection.unresolvedDocuments.length} unresolved</small></dd></div></dl><button onClick={()=>onContext("finance")}>Open invoices, payments & expenses</button><p>{projection.bank.reason}</p>{truth(projection.bank.truth)}</article>
    <article className="oe-calendar"><header><h2>Accounting deadlines</h2><small>Invoice and task dates</small></header>{projection.deadlines.length?projection.deadlines.slice(0,10).map(deadline=><button key={deadline.id} onClick={()=>open(deadline.target)}><span>{deadline.label}</span><b>{deadline.date}</b><small>{deadline.status} · {deadline.provenance}</small></button>):<p>No loaded due dates.</p>}</article>
    <article className="oe-document-matches"><header><h2>Document matching</h2>{truth(sources.sourceState.documents.truth)}</header>{projection.documentMatches.map(match=><button key={`${match.document.id}:${match.linkedId}`} onClick={()=>onContext("documents",match.document.id)}><span><strong>{match.document.title}</strong><small>{match.linkedKind}:{match.linkedId}</small></span>{truth(match.truth)}</button>)}{projection.unresolvedDocuments.map(document=><button key={document.id} onClick={()=>onContext("documents",document.id)}><span><strong>{document.title}</strong><small>Unresolved · no explicit finance entity link</small></span>{truth("PARTIAL")}</button>)}{!projection.documentMatches.length&&!projection.unresolvedDocuments.length&&<p>No accounting document relationship is loaded. No match is inferred from filenames.</p>}<button disabled={!can("documents.read")} onClick={()=>onContext("documents")}>Open Documents / OCR review</button></article>
    <article className="oe-decision-center"><header><h2>Human authority</h2><small>Existing approval adapters only</small></header>{projection.inbox.filter(entry=>entry.kind==="approval").length?projection.inbox.filter(entry=>entry.kind==="approval").map(entry=><button key={entry.id} onClick={()=>open(entry.target)}><span><strong>{entry.title}</strong><small>{entry.reason}</small></span><b>Open authority →</b></button>):<p>No existing permitted domain approval currently requires this actor.</p>}<footer>Invoice, payment and expense actions use existing Finance RBAC and optimistic locking. The role view adds no approval bypass.</footer></article>
    <article className="oe-quick-access"><header><h2>Grounded quick access</h2><small>Existing permissions</small></header><div><button disabled={!can("finance.read")} onClick={()=>onContext("finance")}>Invoices · Expenses · Payments</button><button disabled={!can("documents.read")} onClick={()=>onContext("documents")}>Documents</button><button disabled={!can("room_scans.read")} onClick={()=>onWorkspace("room-scanner",project.id)}>Scanner</button><button disabled={!can("projects.read")} onClick={()=>onContext("project-workspace",project.id)}>Projects</button><button disabled={!can("tasks.read")} onClick={()=>onContext("tasks")}>Tasks & deadlines</button><button disabled={!can("company_price_books.read")} onClick={()=>onWorkspace("company-price-book",project.id)}>Company Price Book</button><button disabled={!can("commercial_estimates.read")} onClick={()=>onWorkspace("commercial-estimate",project.id)}>Commercial Estimate</button><button disabled={!can("reports.read")} onClick={()=>onContext("reports")}>Reports</button><button disabled={!can("notifications.read")} onClick={()=>onContext("notifications")}>OMNIRO Internal</button></div></article>
   </section>
  </section>
  <aside className="oe-intelligence oe-director-intelligence oe-accountant-intelligence"><small>ACCOUNTING INTELLIGENCE</small><h2>Grounded assistance</h2><article><header><strong>Orchestrator</strong>{truth("DERIVED")}</header><p>{projection.inbox.length?`${projection.inbox.length} grounded accounting item${projection.inbox.length===1?"":"s"} require attention.`:"No loaded accounting authority declares an attention state."}</p><small>Derived only from loaded records, lifecycle state and provenance.</small></article><article><header><strong>Accounting Assistant</strong>{truth("PARTIAL")}</header>{projection.briefing.length?projection.briefing.map(entry=><button key={entry.id} onClick={()=>open(entry.target)}><b>{entry.title}</b><small>{entry.reason}</small><i>{entry.provenance.join(" · ")}</i></button>):<p>No grounded briefing item is available.</p>}<small>No autonomous posting, approval or tax advice.</small></article><article><header><strong>KSeF</strong>{truth(projection.ksef.truth)}</header><p>{projection.ksef.reason}</p></article><article><header><strong>Tax / Legal</strong>{truth("UNAVAILABLE")}</header><p>No verified tax-law or legal intelligence source is connected. No filing or compliance conclusion is generated.</p></article><section><h3>Communication truth</h3>{resolved.definition.communicationCapabilities.map(capability=>{const allowed=capability.requiredPermissions.every(permission=>can(permission)),state=capability.truth==="REAL"&&!allowed?"UNAVAILABLE":capability.truth;return <p key={capability.id}><b>{capability.label}</b>{truth(state)}<small>{state==="REAL"?`${sources.notifications.filter(notification=>notification.status==="unread").length} unread recipient-scoped notifications.`:capability.reason}</small></p>})}</section></aside>
 </main>;
}
