import type{TechnologyDto}from"./api.js";import type{OmniroFlowDefinition,OmniroFlowRuntimeState}from"./omniro-flow-contract.js";import{OmniroFlowRegistry}from"./omniro-flow-registry.js";import{buildingModuleRegistry}from"./omniro-building-modules.js";
const state=(flowId:string,reason:string,evidence:OmniroFlowRuntimeState["evidence"],available:boolean,payloadType:string):OmniroFlowRuntimeState=>({flowId,truth:available?"DERIVED":"UNAVAILABLE",state:available?"available":"blocked",reason,evidence,payload:available?{type:payloadType,recordRefs:evidence}:undefined});
export const buildingFlowDefinitions:readonly OmniroFlowDefinition[]=[
 {id:"room-scanner:technical-assignment",source:{moduleId:"room-scanner",output:"snapshot"},destination:{moduleId:"technical-assignment",input:"scan"},relation:"authority",payloadType:"approved-scan-snapshot",defaultTruth:"DERIVED",approvalBoundary:{moduleId:"room-scanner"},resolve:(_,x)=>{const a=x.modules.get("room-scanner"),b=x.modules.get("technical-assignment"),ok=a?.truth==="REAL"&&b?.truth==="REAL";return state("room-scanner:technical-assignment",ok?"Authoritative Scanner evidence is available to Technical Assignment.":"Scanner authority is not available.",[...(a?.evidence??[])],ok,"approved-scan-snapshot")}},
 {id:"technical-assignment:design-project",source:{moduleId:"technical-assignment",output:"assignment"},destination:{moduleId:"design-project",input:"assignment"},relation:"authority",payloadType:"technical-assignment",defaultTruth:"DERIVED",resolve:(_,x)=>{const a=x.modules.get("technical-assignment"),b=x.modules.get("design-project"),ok=a?.truth==="REAL"&&b?.truth==="REAL";return state("technical-assignment:design-project",ok?"Technical intent is available as Design Project authority.":"Technical intent authority is not available.",[...(a?.evidence??[])],ok,"technical-assignment")}},
 {id:"design-project:work-scope-context",source:{moduleId:"design-project",output:"design"},destination:{moduleId:"work-scope",input:"design-context"},relation:"context",payloadType:"design-project-context",defaultTruth:"DERIVED",resolve:(_,x)=>{const a=x.modules.get("design-project"),b=x.modules.get("work-scope"),ok=a?.truth==="REAL"&&b?.truth==="REAL";return state("design-project:work-scope-context","Design Project is lifecycle context only; it is not an authoritative Work Scope source.",[...(a?.evidence??[])],ok,"design-project-context")}},
 {id:"room-scanner:work-scope-source",source:{moduleId:"room-scanner",output:"snapshot"},destination:{moduleId:"work-scope",input:"scanner-source"},relation:"authority",payloadType:"approved-spatial-room-snapshot-set",defaultTruth:"DERIVED",resolve:(_,x)=>{const scope=x.modules.get("work-scope"),evidence=(scope?.evidence??[]).filter(e=>e.entityType==="approved-spatial-room-snapshot"),ok=scope?.truth==="REAL"&&evidence.length>0;return state("room-scanner:work-scope-source",ok?"Approved Scanner spatial snapshots are bound as physical evidence sources.":"No approved Scanner spatial snapshot is bound to this Work Scope.",evidence,ok,"approved-spatial-room-snapshot-set")}},
 {id:"technology:work-scope-reference",source:{moduleId:"technology",output:"approved-version"},destination:{moduleId:"work-scope",input:"technology-reference"},relation:"dependency",payloadType:"approved-execution-technology-version-reference",defaultTruth:"DERIVED",approvalBoundary:{moduleId:"technology"},resolve:(input,x)=>{const approved=((input.sources.technologies??[])as TechnologyDto[]).filter(t=>t.status==="approved"),evidence=approved.map(t=>({entityType:"execution-technology-version",entityId:t.versionId,version:t.technologyVersion,label:`${t.code} version ${t.versionNumber} · approved`})),ok=x.modules.get("work-scope")?.truth==="REAL"&&approved.length>0;return state("technology:work-scope-reference",ok?`${approved.length} approved immutable Technology reference${approved.length===1?" is":"s are"} available for item-level attachment.`:"A Work Scope item requires an approved Technology version reference.",evidence,ok,"approved-execution-technology-version-reference")}},
 {id:"work-scope:engineering-norms",source:{moduleId:"work-scope",output:"approved-snapshot"},destination:{moduleId:"engineering-norms",input:"input"},relation:"authority",payloadType:"approved-work-scope-snapshot",defaultTruth:"UNAVAILABLE",approvalBoundary:{moduleId:"work-scope"},resolve:(_,x)=>{const scope=x.modules.get("work-scope"),ok=scope?.status==="approved";return{...state("work-scope:engineering-norms",ok?"Approved Work Scope authority exists; Engineering Norms remain unavailable in this slice.":"Work Scope approval is required before downstream authority exists.",scope?.evidence??[],false,"approved-work-scope-snapshot"),truth:"UNAVAILABLE"}}},
 ...[["engineering-norms","material-consumption"],["material-consumption","regional-pricing"],["regional-pricing","commercial-estimate"]].map(([source,destination]):OmniroFlowDefinition=>({id:`${source}:${destination}`,source:{moduleId:source,output:"output"},destination:{moduleId:destination,input:"input"},relation:"dependency",payloadType:"registered-payload",defaultTruth:"UNAVAILABLE",resolve:()=>state(`${source}:${destination}`,"This later-chain connection is unavailable in Stage 2B.",[],false,"registered-payload")}))
];
export const buildingFlowRegistry=new OmniroFlowRegistry(buildingFlowDefinitions,buildingModuleRegistry);
