import{useEffect,useRef,useState}from"react";
import*as THREE from"three";

export type StageNode={id:string;label:string;detail:string;status:"available"|"foundation";angle:number;color:number;activation:number};

export const stageNodes:StageNode[]=[
 {id:"scanner",label:"Scanner",detail:"Capture reality",status:"foundation",angle:200,color:0x46a9ff,activation:3},
 {id:"passport",label:"Passport",detail:"Verified digital twin",status:"foundation",angle:158,color:0xa56cff,activation:4},
 {id:"estimate",label:"Estimate",detail:"Smart calculation",status:"available",angle:112,color:0xffae37,activation:4},
 {id:"orchestrator",label:"Orchestrator",detail:"Governed direction",status:"foundation",angle:340,color:0xb26cff,activation:4},
 {id:"norms",label:"Norms",detail:"Built-in standards",status:"available",angle:20,color:0x58d991,activation:4},
 {id:"analytics",label:"Analytics",detail:"Verified insight",status:"available",angle:68,color:0x4bdcff,activation:4},
];

type SceneProps={staticMode?:boolean;phase?:number;quality?:"auto"|"high"};
type MovingPulse={mesh:THREE.Sprite;curve:THREE.Curve<THREE.Vector3>;offset:number;speed:number};
const gold=new THREE.Color(0xffa83b),blue=new THREE.Color(0x399eff),violet=new THREE.Color(0xa568ff);

export function OmniroStageScene({staticMode=false,phase=7,quality="auto"}:SceneProps){
 const mount=useRef<HTMLDivElement>(null),[failed,setFailed]=useState(false);
 useEffect(()=>{const host=mount.current;if(!host)return;let renderer:THREE.WebGLRenderer;
 try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:"high-performance"})}catch{setFailed(true);return}
 setFailed(false);renderer.setPixelRatio(Math.min(devicePixelRatio,quality==="high"?2:innerWidth<760?1.2:1.65));renderer.setClearColor(0x000000,0);renderer.outputColorSpace=THREE.SRGBColorSpace;host.appendChild(renderer.domElement);
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,1,.1,100);camera.position.set(0,.05,11.8);const root=new THREE.Group();root.scale.setScalar(phase<2?.08:phase===2?.64:1);scene.add(root);
 const glowTexture=createGlow(),sparkTexture=createSpark();
 const halo=new THREE.Sprite(new THREE.SpriteMaterial({map:glowTexture,color:0xff9f2c,transparent:true,opacity:phase<1?.08:.7,blending:THREE.AdditiveBlending,depthWrite:false}));halo.scale.set(7.4,7.4,1);root.add(halo);
 const nucleus=new THREE.Mesh(new THREE.SphereGeometry(.54,48,32),new THREE.MeshBasicMaterial({color:0xffd28a,transparent:true,opacity:.75,blending:THREE.AdditiveBlending}));root.add(nucleus);
 const innerShell=new THREE.Mesh(new THREE.IcosahedronGeometry(1.28,3),new THREE.MeshBasicMaterial({color:0xffb54d,wireframe:true,transparent:true,opacity:.48,blending:THREE.AdditiveBlending}));root.add(innerShell);
 const outerShell=new THREE.Mesh(new THREE.IcosahedronGeometry(2.05,4),new THREE.MeshBasicMaterial({color:gold,wireframe:true,transparent:true,opacity:.34,blending:THREE.AdditiveBlending,depthWrite:false}));root.add(outerShell);
 const network=new THREE.Group();root.add(network);const networkPoints:THREE.Vector3[]=[];for(let i=0;i<34;i++){const v=new THREE.Vector3().randomDirection().multiplyScalar(1.62+Math.random()*.34);networkPoints.push(v);const dot=new THREE.Sprite(new THREE.SpriteMaterial({map:sparkTexture,color:i%5?0xffbd62:0xffffff,transparent:true,opacity:.9,blending:THREE.AdditiveBlending,depthWrite:false}));dot.scale.setScalar(i%6===0?.13:.07);dot.position.copy(v);network.add(dot)}for(let i=0;i<66;i++){const a=networkPoints[i%networkPoints.length],b=networkPoints[(i*7+5)%networkPoints.length];if(a.distanceTo(b)>2.8)continue;const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints([a,b]),new THREE.LineBasicMaterial({color:i%4?0xf5a642:0x99c9ff,transparent:true,opacity:.32,blending:THREE.AdditiveBlending}));network.add(line)}
 const rings:THREE.LineLoop[]=[];[[2.55,.68,.1],[3.1,.52,.72],[3.62,.42,-.48],[4.05,.32,1.02]].forEach(([radius,squash,tilt],index)=>{const points=[];for(let i=0;i<220;i++){const a=i/220*Math.PI*2;points.push(new THREE.Vector3(Math.cos(a)*radius,Math.sin(a)*radius*squash,0))}const ring=new THREE.LineLoop(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:index===1?blue:index===2?violet:gold,transparent:true,opacity:.24,blending:THREE.AdditiveBlending}));ring.rotation.set(index*.18,tilt*.32,tilt);root.add(ring);rings.push(ring)});
 const nodeGroup=new THREE.Group(),flowGroup=new THREE.Group(),pulses:MovingPulse[]=[];root.add(nodeGroup,flowGroup);stageNodes.forEach((node,index)=>{if(phase<node.activation)return;const a=node.angle*Math.PI/180,x=Math.cos(a)*3.47,y=Math.sin(a)*2.42,z=index%2?.28:-.18;const nodeHalo=new THREE.Sprite(new THREE.SpriteMaterial({map:glowTexture,color:node.color,transparent:true,opacity:.72,blending:THREE.AdditiveBlending,depthWrite:false}));nodeHalo.scale.set(1.05,1.05,1);nodeHalo.position.set(x,y,z);nodeGroup.add(nodeHalo);const nodeCore=new THREE.Mesh(new THREE.IcosahedronGeometry(.22,1),new THREE.MeshBasicMaterial({color:node.color,wireframe:true,transparent:true,opacity:.95}));nodeCore.position.set(x,y,z+.02);nodeGroup.add(nodeCore);const start=new THREE.Vector3(x,y,z),bend=new THREE.Vector3(x*.5,y*.12,index%2?.7:-.65),end=new THREE.Vector3(0,0,0),curve=new THREE.QuadraticBezierCurve3(start,bend,end);const flow=new THREE.Line(new THREE.BufferGeometry().setFromPoints(curve.getPoints(80)),new THREE.LineBasicMaterial({color:node.color,transparent:true,opacity:.38,blending:THREE.AdditiveBlending}));flowGroup.add(flow);for(let p=0;p<2;p++){const pulse=new THREE.Sprite(new THREE.SpriteMaterial({map:sparkTexture,color:node.color,transparent:true,opacity:1,blending:THREE.AdditiveBlending,depthWrite:false}));pulse.scale.setScalar(.13);flowGroup.add(pulse);pulses.push({mesh:pulse,curve,offset:p*.47+index*.11,speed:.000055+index*.000004})}});
 const particleCount=quality==="high"?1900:innerWidth<760?580:1250,positions=new Float32Array(particleCount*3),colors=new Float32Array(particleCount*3);for(let i=0;i<particleCount;i++){const radius=1.7+Math.pow(Math.random(),.72)*4.4,a=Math.random()*Math.PI*2,depth=(Math.random()-.5)*3;positions[i*3]=Math.cos(a)*radius;positions[i*3+1]=Math.sin(a)*radius*.58;positions[i*3+2]=depth;const color=Math.random()>.2?gold:Math.random()>.5?blue:violet;colors.set([color.r,color.g,color.b],i*3)}const particleGeometry=new THREE.BufferGeometry();particleGeometry.setAttribute("position",new THREE.BufferAttribute(positions,3));particleGeometry.setAttribute("color",new THREE.BufferAttribute(colors,3));const particles=new THREE.Points(particleGeometry,new THREE.PointsMaterial({map:sparkTexture,size:.045,vertexColors:true,transparent:true,opacity:.8,blending:THREE.AdditiveBlending,depthWrite:false}));root.add(particles);
 const base=new THREE.Group();root.add(base);for(let i=0;i<5;i++){const radius=1.35+i*.42,points=[];for(let j=0;j<160;j++){const a=j/160*Math.PI*2;points.push(new THREE.Vector3(Math.cos(a)*radius,-2.62+Math.sin(a)*radius*.12,Math.sin(a)*.35))}const line=new THREE.LineLoop(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:i%2?0x3a86db:0xe7a145,transparent:true,opacity:.28}));base.add(line)}const beam=new THREE.Sprite(new THREE.SpriteMaterial({map:createBeam(),color:0xffb34c,transparent:true,opacity:.45,blending:THREE.AdditiveBlending,depthWrite:false}));beam.position.y=-1.7;beam.scale.set(1.2,3.2,1);base.add(beam);
 const resize=()=>{const width=host.clientWidth,height=host.clientHeight;renderer.setSize(width,height,false);camera.aspect=width/Math.max(height,1);camera.updateProjectionMatrix()};const observer=new ResizeObserver(resize);observer.observe(host);resize();let frame=0,active=!document.hidden;const visibility=()=>{active=!document.hidden};document.addEventListener("visibilitychange",visibility);
 const render=(time=0)=>{const t=time*.001;if(!staticMode){outerShell.rotation.y=t*.13;outerShell.rotation.x=Math.sin(t*.12)*.12;innerShell.rotation.y=-t*.22;innerShell.rotation.z=t*.08;network.rotation.y=t*.1;network.rotation.z=-t*.045;rings.forEach((ring,index)=>{ring.rotation.z+=(index%2?-.00032:.00024);ring.rotation.y+=index%2?.00011:-.00008});particles.rotation.z=-t*.025;particles.rotation.y=t*.018;nucleus.scale.setScalar(1+Math.sin(t*1.65)*.08);halo.material.opacity=.57+Math.sin(t*1.2)*.1;pulses.forEach(item=>item.mesh.position.copy(item.curve.getPoint((item.offset+time*item.speed)%1)))}renderer.render(scene,camera)};
 const animate=(time:number)=>{frame=requestAnimationFrame(animate);if(active)render(time)};render();frame=requestAnimationFrame(animate);
 return()=>{cancelAnimationFrame(frame);document.removeEventListener("visibilitychange",visibility);observer.disconnect();scene.traverse(object=>{if(object instanceof THREE.Mesh||object instanceof THREE.Line||object instanceof THREE.Points){object.geometry.dispose();const material=object.material;if(Array.isArray(material))material.forEach(item=>item.dispose());else material.dispose()}if(object instanceof THREE.Sprite)object.material.dispose()});glowTexture.dispose();sparkTexture.dispose();renderer.dispose();renderer.domElement.remove()};},[phase,quality,staticMode]);
 return <div className={`omniro-stage-scene ${failed?"scene-failed":""}`} ref={mount} aria-hidden="true">{failed&&<div className="omniro-fallback"><span/><i/><b>OMNIRO</b></div>}</div>;
}

function radialTexture(stops:Array<[number,string]>){const canvas=document.createElement("canvas");canvas.width=canvas.height=256;const context=canvas.getContext("2d")!,gradient=context.createRadialGradient(128,128,0,128,128,128);stops.forEach(([at,color])=>gradient.addColorStop(at,color));context.fillStyle=gradient;context.fillRect(0,0,256,256);return new THREE.CanvasTexture(canvas)}
function createGlow(){return radialTexture([[0,"rgba(255,239,190,1)"],[.08,"rgba(255,174,55,.95)"],[.34,"rgba(255,115,18,.3)"],[1,"rgba(0,0,0,0)"]])}
function createSpark(){return radialTexture([[0,"rgba(255,255,255,1)"],[.2,"rgba(255,205,118,.9)"],[1,"rgba(0,0,0,0)"]])}
function createBeam(){const canvas=document.createElement("canvas");canvas.width=128;canvas.height=512;const context=canvas.getContext("2d")!,gradient=context.createLinearGradient(0,0,0,512);gradient.addColorStop(0,"rgba(255,176,60,0)");gradient.addColorStop(.45,"rgba(255,190,80,.85)");gradient.addColorStop(1,"rgba(255,176,60,0)");context.fillStyle=gradient;context.fillRect(52,0,24,512);return new THREE.CanvasTexture(canvas)}
