import{renderToStaticMarkup}from"react-dom/server";
import{describe,expect,it}from"vitest";
import type{MaterialContract,WorkItemContract}from"@odls/contracts";
import type{ApprovedSnapshotDto,CompanyPriceBookDto,CompanyPriceRegionalComparisonDto,Session}from"./api.js";
import{CompanyPriceBookWorkspaceView}from"./omniro-company-price-book-workspace.js";

const reader:Session={accessToken:"x",refreshToken:"x",user:{id:"reader",email:"reader@example.test",displayName:"Reader"},permissions:["company_price_books.read"]};
const editor:Session={...reader,permissions:[...reader.permissions,"company_price_books.create","company_price_books.edit","company_price_books.review","company_price_books.approve","company_price_books.snapshots.read","work_catalog.read","material_catalog.read"]};
const work={id:"work-1",code:"PAINT-WALL",displayName:"Wall painting",measurementUnitId:"unit-m2",measurementUnitCode:"M2",status:"active"}as WorkItemContract;
const material={id:"material-1",code:"PAINT-WHITE",displayName:"Interior white paint",measurementUnitId:"unit-l",measurementUnitCode:"L",status:"active"}as MaterialContract;
const book:CompanyPriceBookDto={id:"book-1",code:"CPB-PL-2026",title:"Company prices Poland",purpose:"Approved sales authority",revisionId:"revision-2",revisionNumber:2,status:"draft",currency:"PLN",effectiveFrom:"2026-01-01",effectiveTo:"2026-12-31",version:7,entries:[{id:"labor-1",entryKind:"labor",workItemId:work.id,materialId:null,measurementUnitId:"unit-m2",unitCode:"M2",internalCost:18,sellingPrice:30,currency:"PLN",effectiveFrom:"2026-01-01",effectiveTo:"2026-12-31",sourceReference:"Board decision FIN-42",notes:"Skilled crew",version:2},{id:"material-entry-1",entryKind:"material",workItemId:null,materialId:material.id,measurementUnitId:"unit-l",unitCode:"L",internalCost:80,sellingPrice:100,currency:"PLN",effectiveFrom:"2026-01-01",effectiveTo:null,sourceReference:"Supplier agreement SUP-9",notes:null,version:1}]};
const snapshot:ApprovedSnapshotDto={id:"snapshot-1",contentFingerprint:"a".repeat(64),schemaVersion:"company-price-book-v1",revisionNumber:1,approvedAt:"2026-01-10T12:00:00.000Z",approvedBy:"approver-1",content:{entries:[{...book.entries[0],sellingPrice:28,marginAmount:10,marginPercent:35.7143}]}};
const comparison:CompanyPriceRegionalComparisonDto={available:true,companySellingPrice:30,regionalReference:26,companyInternalCost:18,marginAmount:12,marginPercent:40,regionalVariance:4,regionalVariancePercent:15.3846,currency:"PLN",unitCode:"M2",companySnapshotId:"snapshot-1",companyFingerprint:"a".repeat(64),regionalSnapshotId:"regional-1",regionalFingerprint:"b".repeat(64),mutated:false};
const render=(options:Partial<Parameters<typeof CompanyPriceBookWorkspaceView>[0]>={})=>renderToStaticMarkup(<CompanyPriceBookWorkspaceView session={reader} book={book} works={[work]} materials={[material]} snapshot={undefined} comparisons={{}} busy={false} onCreate={async()=>{}} onSaveEntry={async()=>{}} onStartEdit={()=>{}} onReview={()=>{}} onApprove={()=>{}} onRevise={()=>{}} onCancel={()=>{}} onCompare={()=>{}} onClose={()=>{}} {...options}/>);

describe("Company Price Book Command Center workspace",()=>{
 it("shows a truthful empty state without invented commercial values",()=>{const html=render({book:undefined,works:[],materials:[]});expect(html).toContain("No Company Price Book exists yet");expect(html).toContain("has not invented prices, margins, currency, or catalog entries");expect(html).not.toContain("CPB-PL-2026")});
 it("offers creation only to a user with create authority",()=>{expect(render({book:undefined,session:editor})).toContain("CREATE COMPANY PRICE BOOK");expect(render({book:undefined})).toContain("company_price_books.create is required")});
 it("requires explicit currency and effective dates in the create form",()=>{const html=render({book:undefined,session:editor});expect(html).toContain("Currency");expect(html).toContain("Effective from");expect(html).toContain("have no commercial defaults")});
 it("renders the exact labor price and Work Catalog identity",()=>{const html=render();expect(html).toContain("Wall painting");expect(html).toContain("18.00");expect(html).toContain("30.00");expect(html).toContain("Board decision FIN-42")});
 it("renders the exact material price and Material Catalog identity",()=>{const html=render();expect(html).toContain("Interior white paint");expect(html).toContain("80.00");expect(html).toContain("100.00");expect(html).toContain("Supplier agreement SUP-9")});
 it("keeps internal cost and selling client price visibly separate",()=>{const html=render();expect(html).toContain("Internal cost");expect(html).toContain("Selling / client price")});
 it("displays deterministic margin but never an editable margin field",()=>{const html=render();expect(html).toContain("12.00");expect(html).toContain("40%");expect(html).toContain("NOT EDITABLE");expect(html).not.toMatch(/<input[^>]+margin/i)});
 it("shows manual add and edit controls only for editable lifecycle and permission",()=>{const html=render({session:editor});expect(html).toContain("MANUAL PRICE ENTRY");expect(html).toContain("Edit draft entry");expect(render()).not.toContain("Edit draft entry")});
 it("renders the draft edit form with optimistic source values",()=>{const html=render({session:editor,editing:book.entries[0]});expect(html).toContain("EDIT DRAFT ENTRY");expect(html).toContain('value="18"');expect(html).toContain("SAVE DRAFT ENTRY")});
 it("makes an approved revision read-only",()=>{const html=render({session:editor,book:{...book,status:"approved"},snapshot});expect(html).not.toContain("MANUAL PRICE ENTRY");expect(html).not.toContain("Edit draft entry");expect(html).toContain("CREATE NEXT DRAFT REVISION")});
 it("exposes review separately from approval",()=>{expect(render({session:editor})).toContain("CHECK PRICE BOOK READINESS");expect(render({session:editor,book:{...book,status:"ready_for_approval"}})).toContain("HUMAN APPROVAL · COMPANY PRICE BOOK")});
 it("shows the human approval authority to a reader without granting the action",()=>{const html=render({book:{...book,status:"ready_for_approval"}});expect(html).toContain("Company prices become authoritative only after human approval");expect(html).toContain("does not have company_price_books.approve")});
 it("shows approved immutable snapshot only when supplied by the authorized API path",()=>{const html=render({book:{...book,status:"approved"},snapshot});expect(html).toContain("Approved immutable Company Price Book snapshot");expect(html).toContain("snapshot-1");expect(html).toContain("approver-1")});
 it("explains snapshot permission when content is hidden",()=>{expect(render({book:{...book,status:"approved"}})).toContain("company_price_books.snapshots.read is required")});
 it("shows current and prior approved revision history",()=>{const html=render({session:editor,snapshot});expect(html).toContain("Price Book Revision 2");expect(html).toContain("Price Book Revision 1");expect(html).toContain("APPROVED · IMMUTABLE")});
 it("presents Regional Pricing as read-only comparison with exact variance",()=>{const html=render({snapshot,comparisons:{"labor-1":comparison}});expect(html).toContain("REFERENCE / COMPARISON ONLY");expect(html).toContain("15.3846%");expect(html).toContain("Mutation performed");expect(html).toContain("cannot replace, inherit, synchronize, or approve")});
 it("handles a missing regional reference truthfully",()=>{const html=render({snapshot,comparisons:{"labor-1":{available:false,reason:"NO_COMPATIBLE_REGIONAL_REFERENCE",mutated:false}}});expect(html).toContain("No compatible regional reference exists");expect(html).toContain("Company price was not changed")});
 it("keeps Commercial Estimate outside this integration",()=>{const html=render({snapshot});expect(html).toContain("Commercial Estimate integration is not connected in this slice");expect(html).toContain("No Commercial Estimate is created or repriced")});
 it("surfaces API errors without fallback demo data",()=>{const html=render({book:undefined,error:"Request failed: SERVICE_UNAVAILABLE"});expect(html).toContain('role="alert"');expect(html).toContain("SERVICE_UNAVAILABLE");expect(html).not.toContain("Wall painting")});
 it("renders period, lifecycle and optimistic version from the backend model",()=>{const html=render();expect(html).toContain("2026-01-01 → 2026-12-31");expect(html).toContain("version 7");expect(html).toContain("Not authoritative yet")});
});
