import type{DocumentContract,ExpenseContract,InvoiceContract,PaymentContract,ProjectContract}from"@odls/contracts";
import{renderToStaticMarkup}from"react-dom/server";
import{describe,expect,it}from"vitest";
import type{Session}from"./api.js";
import{OmniroAccountantWorkspace}from"./omniro-accountant-workspace.js";
import{buildAccountantProjection}from"./omniro-accountant-workspace-model.js";
import type{DirectorSources}from"./omniro-director-workspace-model.js";
import type{OmniroModuleRuntimeState,OmniroRuntimeSnapshot}from"./omniro-module-contract.js";
import{roleWorkspaceRegistry}from"./omniro-role-workspace-registry.js";

const id=(suffix:string)=>`10000000-0000-4000-8000-${suffix.padStart(12,"0")}`;
const project:ProjectContract={id:id("1"),tenantId:id("2"),clientId:id("3"),propertyId:id("4"),financialOwnerLegalEntityId:id("5"),projectManagerId:id("6"),projectNumber:"PRJ-ACC",name:"Grounded Office",description:null,status:"active",startDate:"2026-01-01",expectedCompletionDate:"2026-09-30",actualCompletionDate:null,currencyCode:"PLN",estimatedBudget:null,approvedBudget:null,contractValue:null,paymentStatus:"not_required",billingCustomerReference:null,externalPaymentCustomerReference:null,version:2,createdAt:"2026-01-01",updatedAt:"2026-08-01",archivedAt:null};
const permissions=["projects.read","finance.read","finance.update","documents.read","tasks.read","notifications.read","company_price_books.read","company_price_books.approve","commercial_estimates.read"];
const session:Session={accessToken:"access",refreshToken:"refresh",user:{id:id("6"),email:"accountant@example.com",displayName:"Real Accounting Actor"},permissions};
const base={tenantId:project.tenantId,currencyCode:"PLN",version:2,createdAt:"2026-07-01",updatedAt:"2026-08-10",archivedAt:null};
const invoice:InvoiceContract={...base,id:id("10"),clientId:project.clientId,projectId:project.id,invoiceNumber:"INV-2026-10",status:"issued",issueDate:"2026-07-01",dueDate:"2026-08-01",netAmount:"1000.0000",vatRate:"23.0000",vatAmount:"230.0000",grossAmount:"1230.0000",paidAmount:"230.0000",outstandingAmount:"1000.0000",notes:null};
const payment:PaymentContract={...base,id:id("11"),clientId:project.clientId,reference:"PAY-11",status:"received",amount:"500.0000",allocatedAmount:"100.0000",unallocatedAmount:"400.0000",paymentDate:"2026-08-10"};
const expense:ExpenseContract={...base,id:id("12"),projectId:project.id,supplier:"Grounded Supplier",category:"materials",expenseDate:"2026-08-11",status:"draft",netAmount:"200.0000",vatRate:"23.0000",vatAmount:"46.0000",grossAmount:"246.0000",notes:null};
const document:DocumentContract={id:id("13"),tenantId:project.tenantId,title:"Supplier receipt",documentType:"receipt",sourceType:"upload",status:"active",category:"receipt",description:null,currentVersionNo:2,pageCount:1,ocrStatus:"failed",aiProcessingStatus:"not_requested",version:3,createdAt:"2026-08-11",createdBy:session.user.id,updatedAt:"2026-08-12",updatedBy:session.user.id,archivedAt:null,currentVersion:{id:id("14"),versionNo:2,originalFilename:"receipt.pdf",mimeType:"application/pdf",extension:"pdf",fileSize:100,checksum:"a".repeat(64),uploadedBy:session.user.id,createdAt:"2026-08-12"},links:[{id:id("15"),entityType:"expense",entityId:expense.id}]};
const approval:OmniroModuleRuntimeState={moduleId:"company-price-book",projectId:project.id,truth:"REAL",lifecycle:"APPROVAL_REQUIRED",availability:"available",status:"ready_for_approval",reason:"Price book revision requires an existing human authority.",record:{entityType:"company-price-book",entityId:id("16"),version:4},evidence:[{entityType:"company-price-book",entityId:id("16"),version:4,label:"Revision 4"}]};
const runtime:OmniroRuntimeSnapshot={projectId:project.id,loadedAt:"2026-08-14T09:00:00.000Z",modules:new Map([[approval.moduleId,approval]])};
const sources:DirectorSources={tasks:[],documents:[document],notifications:[],users:[],invoices:[invoice],payments:[payment],expenses:[expense],financialSummaries:[{projectId:project.id,currencyCode:"PLN",budget:null,invoicedNet:"1000.0000",invoicedVat:"230.0000",invoicedGross:"1230.0000",paid:"230.0000",outstanding:"1000.0000",expenses:"246.0000",grossMarginAmount:"754.0000",grossMarginPercentage:"75.4000",overdueInvoiceCount:1,overdueInvoiceAmount:"1000.0000"}],sourceState:{tasks:{truth:"REAL",reason:"Tasks loaded."},documents:{truth:"REAL",reason:"Documents loaded."},notifications:{truth:"REAL",reason:"Notifications loaded."},users:{truth:"UNAVAILABLE",reason:"Users not required."},finance:{truth:"REAL",reason:"Finance loaded."}}};
const runtimes=new Map([[project.id,runtime]]),props={session,projects:[project],project,runtimes,sources,flows:[],onBack:()=>undefined,onRole:()=>undefined,onProject:()=>undefined,onModule:()=>undefined,onWorkspace:()=>undefined,onContext:()=>undefined};

describe("OMNIRO Accountant Workspace V1",()=>{
 it("resolves finance.read without replacing the authenticated actor",()=>{expect(roleWorkspaceRegistry.resolve("accountant",session)).toMatchObject({truth:"REAL",actualActorId:session.user.id,actualActorName:session.user.displayName});expect(roleWorkspaceRegistry.resolve("accountant",{...session,permissions:[]})).toMatchObject({truth:"UNAVAILABLE",actualActorId:session.user.id})});
 it("builds a deterministic accounting inbox from real lifecycle records",()=>{const projection=buildAccountantProjection(session,[project],runtimes,sources,project.id,"2026-08-14");expect(projection.inbox.map(item=>item.id)).toEqual([`invoice:${invoice.id}`,`payment:${payment.id}`,`document:${document.id}`,`module:${project.id}:company-price-book:${approval.record?.entityId}`,`expense:${expense.id}`]);expect(projection.inbox[0]).toMatchObject({amount:"1000.0000",currency:"PLN",status:"issued",projectName:project.name,responsibility:"Finance authority · existing invoice permissions"});expect(projection.inbox[0].provenance).toContain(`invoice:${invoice.id}:v2`);expect(projection.sourceCounts).toEqual({invoices:1,payments:1,expenses:1,documents:1,processedInvoices:1,processedExpenses:0,allocatedPayments:0})});
 it("matches accounting documents only through explicit entity links",()=>{const projection=buildAccountantProjection(session,[project],runtimes,sources,project.id,"2026-08-14");expect(projection.documentMatches).toHaveLength(1);expect(projection.documentMatches[0]).toMatchObject({linkedKind:"expense",linkedId:expense.id,projectId:project.id,truth:"REAL"});const unlinked={...document,id:id("17"),title:"INV-looking filename",links:[]},unresolved=buildAccountantProjection(session,[project],runtimes,{...sources,documents:[unlinked]},project.id,"2026-08-14");expect(unresolved.documentMatches).toEqual([]);expect(unresolved.unresolvedDocuments).toEqual([unlinked])});
 it("keeps dates, source records and existing approval authority traceable",()=>{const projection=buildAccountantProjection(session,[project],runtimes,sources,project.id,"2026-08-14");expect(projection.deadlines[0]).toMatchObject({id:`invoice:${invoice.id}`,date:"2026-08-01",status:"overdue"});expect(projection.inbox.find(item=>item.kind==="approval")?.target).toMatchObject({kind:"workspace",moduleId:"company-price-book",projectId:project.id});expect(projection.currentFinancial).toBe(sources.financialSummaries[0])});
 it("surfaces the same approval evidence without granting missing authority",()=>{const directorItem=`module:${project.id}:company-price-book:${approval.record?.entityId}`,restricted={...session,permissions:permissions.filter(permission=>permission!=="company_price_books.approve")},projection=buildAccountantProjection(restricted,[project],runtimes,sources,project.id,"2026-08-14"),item=projection.inbox.find(entry=>entry.id===directorItem);expect(item).toMatchObject({id:directorItem,responsibility:"Escalation requires company_price_books.approve",target:{kind:"module",moduleId:"company-price-book",projectId:project.id}});expect(item?.provenance).toEqual([`company-price-book:${approval.record?.entityId}:v4`])});
 it("renders real values and declares external accounting boundaries",()=>{const html=renderToStaticMarkup(<OmniroAccountantWorkspace {...props}/>);expect(html).toContain("Accountant Workspace");expect(html).toContain(`actor ${session.user.id}`);expect(html).toContain("INV-2026-10");expect(html).toContain("1000.0000 PLN");expect(html).toContain("Grounded Supplier");expect(html).toContain("No KSeF provider");expect(html).toContain("no bank account or bank-feed integration");expect(html).toContain("No autonomous posting, approval or tax advice");expect(html).not.toContain("12.45M");expect(html).not.toContain("18.7%")});
 it("preserves unavailable providers and permissions instead of fabricating capability",()=>{const restricted={...session,permissions:["projects.read"]};expect(roleWorkspaceRegistry.resolve("accountant",restricted).truth).toBe("UNAVAILABLE");const html=renderToStaticMarkup(<OmniroAccountantWorkspace {...props} session={restricted}/>);expect(html).toContain("UNAVAILABLE");expect(html).toContain("No email provider is connected");expect(html).toContain("No KSeF provider or submission authority is connected")});
});
