import type{DocumentContract,ProjectContract,TaskContract}from"@odls/contracts";
import{renderToStaticMarkup}from"react-dom/server";
import{describe,expect,it}from"vitest";
import type{Session}from"./api.js";
import type{DirectorSources}from"./omniro-director-workspace-model.js";
import type{OmniroRuntimeSnapshot}from"./omniro-module-contract.js";
import{environmentHash,parseEnvironmentRoute,dataFlowVisualRegistry}from"./omniro-operating-environment-model.js";
import{roleWorkspaceRegistry}from"./omniro-role-workspace-registry.js";
import{buildProjectManagerProjection}from"./omniro-project-manager-workspace-model.js";
import{buildSiteManagerProjection}from"./omniro-site-manager-workspace-model.js";
import{OmniroSiteManagerWorkspace}from"./omniro-site-manager-workspace.js";

const id=(n:string)=>`20000000-0000-4000-8000-${n.padStart(12,"0")}`;
const project:ProjectContract={id:id("1"),tenantId:id("2"),clientId:id("3"),propertyId:id("4"),financialOwnerLegalEntityId:id("5"),projectManagerId:id("6"),projectNumber:"SITE-01",name:"Field Project",description:null,status:"active",startDate:"2026-01-01",expectedCompletionDate:"2026-12-01",actualCompletionDate:null,currencyCode:"PLN",estimatedBudget:null,approvedBudget:null,contractValue:null,paymentStatus:"not_required",billingCustomerReference:null,externalPaymentCustomerReference:null,version:4,createdAt:"2026-01-01",updatedAt:"2026-08-14",archivedAt:null};
const other={...project,id:id("20"),projectNumber:"OTHER"};
const permissions=["projects.read","tasks.read","documents.read","notifications.read","users.read","room_scans.read","work_scopes.read","engineering_norms.read","material_consumption.read"];
const session:Session={accessToken:"a",refreshToken:"r",user:{id:id("9"),email:"director@example.com",displayName:"Actual Director"},permissions};
const makeTask=(n:string,status:TaskContract["status"],dueDate:string|null,assignees:TaskContract["assignees"]=[],isOverdue=false):TaskContract=>({id:id(n),tenantId:project.tenantId,projectId:project.id,title:`Task ${n}`,description:n==="7"?"Location: Room 204. Prepare surface.":null,status,priority:status==="blocked"?"urgent":"normal",dueDate,startedAt:null,completedAt:status==="completed"?"2026-08-14":null,isOverdue,assignees,version:Number(n),createdAt:"2026-08-01",updatedAt:"2026-08-14",archivedAt:null});
const assignee={userId:id("30"),displayName:"Real Foreman",assignedAt:"2026-08-01"},todayTask=makeTask("7","todo","2026-08-14",[assignee]),overdue=makeTask("8","in_progress","2026-08-10",[],true),blocked=makeTask("9","blocked",null),done=makeTask("10","completed","2026-08-13");
const document:DocumentContract={id:id("11"),tenantId:project.tenantId,title:"Drawing A",documentType:"drawing",sourceType:"upload",status:"active",category:"project_plan",description:null,currentVersionNo:3,pageCount:2,ocrStatus:"failed",aiProcessingStatus:"completed",version:5,createdAt:"2026-01-01",createdBy:id("6"),updatedAt:"2026-08-14",updatedBy:id("30"),archivedAt:null,currentVersion:{id:id("12"),versionNo:3,originalFilename:"drawing-a.pdf",mimeType:"application/pdf",extension:"pdf",fileSize:100,checksum:"b".repeat(64),uploadedBy:id("30"),createdAt:"2026-08-14"},links:[{id:id("13"),entityType:"project",entityId:project.id}]};
const scope={id:id("14"),projectId:project.id,code:"WS-SITE",name:"Site works",revisionId:id("15"),revisionNumber:2,status:"approved",version:2,items:[{id:id("16"),workType:"painting",description:"Task 7",status:"ready",priority:"normal",sequence:1,targetType:"room",targetReference:"Room 204",technologyVersionId:id("17"),reviewState:"confirmed",version:2}],mappings:[{id:id("18"),workItemId:id("16"),spatialSnapshotId:id("19"),scannerQuantityType:"wall_area",scannerQuantityValue:42,scannerUnit:"m2",scannerFormulaId:"wall-area",scannerCalculatorVersion:"1.0"}],sources:[{spatialSnapshotId:id("19"),snapshotFingerprint:"fp"}]};
const materials={id:id("21"),projectId:project.id,code:"MC-SITE",title:"Required materials",revisionNumber:2,status:"approved",version:2,workScopeSnapshotId:id("22"),normSnapshotId:id("23"),knowledgeVersionId:id("24"),technologyVersionId:id("17"),workItemId:id("16"),evaluatedParameters:{},workQuantity:42,workQuantityUnit:"m2",revisionId:id("25"),lines:[{id:id("26"),requirementCode:"PAINT",engineeringRequirements:{},environmentalRequirements:{},formula:{},normRevisionNumber:1,technologyVersionId:id("17"),netQuantity:8,unitCode:"L",selectionState:"unselected",wastePolicy:{},wasteQuantity:1,reserveQuantity:1,totalQuantity:10,packageCount:2,packageRemainder:0,availableQuantity:0,remainingQuantity:10,version:2}]};
const moduleState=(moduleId:string,lifecycle:"APPROVED"|"APPROVAL_REQUIRED",observed:unknown)=>({moduleId,projectId:project.id,truth:"REAL"as const,lifecycle,availability:"available"as const,status:lifecycle==="APPROVED"?"approved":"ready_for_approval",reason:lifecycle==="APPROVED"?"Existing authority is ready.":"Human approval is required.",record:{entityType:moduleId,entityId:id(moduleId==="work-scope"?"14":moduleId==="material-consumption"?"21":"27"),version:2},evidence:[{entityType:moduleId,entityId:id(moduleId==="work-scope"?"14":moduleId==="material-consumption"?"21":"27"),version:2,label:"Authority"}],observed});
const runtime:OmniroRuntimeSnapshot={projectId:project.id,loadedAt:"2026-08-14",modules:new Map([["work-scope",moduleState("work-scope","APPROVED",[scope])],["material-consumption",moduleState("material-consumption","APPROVED",[materials])],["room-scanner",moduleState("room-scanner","APPROVAL_REQUIRED",[]) ]])};
const sources:DirectorSources={tasks:[todayTask,overdue,blocked,done,{...todayTask,id:id("40"),projectId:other.id}],documents:[document,{...document,id:id("41"),links:[{id:id("42"),entityType:"project",entityId:other.id}]}],notifications:[],users:[{id:id("6"),email:"pm@example.com",displayName:"Project Manager",isDisabled:false,version:1},{id:id("30"),email:"foreman@example.com",displayName:"Real Foreman",isDisabled:false,version:1}],invoices:[],payments:[],expenses:[],financialSummaries:[],sourceState:{tasks:{truth:"REAL",reason:"Tasks loaded."},documents:{truth:"REAL",reason:"Documents loaded."},notifications:{truth:"REAL",reason:"Notifications loaded."},users:{truth:"REAL",reason:"Users loaded."},finance:{truth:"PARTIAL",reason:"Finance incomplete."}}};
const runtimes=new Map([[project.id,runtime],[other.id,{...runtime,projectId:other.id,modules:new Map()}]]),props={session,projects:[project,other],project,runtimes,sources,flows:[],onBack:()=>undefined,onRole:()=>undefined,onProject:()=>undefined,onModule:()=>undefined,onWorkspace:()=>undefined,onContext:()=>undefined};

describe("OMNIRO Site Manager Foreman Workspace V1",()=>{
 it("registers a permission-grounded workspace without replacing the actor",()=>{expect(roleWorkspaceRegistry.resolve("site-manager",session)).toMatchObject({truth:"REAL",actualActorId:session.user.id,actualActorName:"Actual Director"});expect(roleWorkspaceRegistry.resolve("site-manager",{...session,permissions:[]})).toMatchObject({truth:"UNAVAILABLE",actualActorId:session.user.id});expect(roleWorkspaceRegistry.resolve("worker",session).truth).toBe("UNAVAILABLE")});
 it("preserves project-aware deep links",()=>{const hash=environmentHash({layer:"role",roleId:"site-manager",projectId:project.id});expect(parseEnvironmentRoute(hash)).toEqual({layer:"role",roleId:"site-manager",projectId:project.id})});
 it("groups only real project tasks into honest field states",()=>{const projection=buildSiteManagerProjection(session,[project,other],runtimes,sources,project.id,"2026-08-14");expect(projection.taskGroups.TODAY.map(item=>item.task.id)).toEqual([todayTask.id]);expect(projection.taskGroups.OVERDUE.map(item=>item.task.id)).toEqual([overdue.id]);expect(projection.taskGroups.BLOCKED.map(item=>item.task.id)).toEqual([blocked.id]);expect(projection.taskGroups.DONE.map(item=>item.task.id)).toEqual([done.id]);expect(projection.tasks).toHaveLength(4);expect(projection.tasks[0]).toMatchObject({location:"Room 204",responsibility:"Real Foreman"});expect(projection.unassigned).toBe(2)});
 it("reuses Work Scope quantities and Material Consumption semantics",()=>{const projection=buildSiteManagerProjection(session,[project],runtimes,sources,project.id,"2026-08-14");expect(projection.work[0]).toMatchObject({quantity:42,unit:"m2",relatedTask:{id:todayTask.id}});expect(projection.work[0].provenance).toContain(`spatial-snapshot:${id("19")}`);expect(projection.materials?.lines[0]).toMatchObject({netQuantity:8,wasteQuantity:1,reserveQuantity:1,totalQuantity:10,selectionState:"unselected"})});
 it("keeps documents explicit, Scanner unchanged and escalation on the same provenance",()=>{const projection=buildSiteManagerProjection(session,[project,other],runtimes,sources,project.id,"2026-08-14"),projectManager=buildProjectManagerProjection(session,[project,other],runtimes,sources,project.id);expect(projection.documents.map(item=>item.id)).toEqual([document.id]);expect(projection.scanner).toMatchObject({target:{kind:"workspace",moduleId:"room-scanner",projectId:project.id}});const scanner=projection.attention.find(item=>item.id.includes("room-scanner")),managerScanner=projectManager.attention.find(item=>item.id.includes("room-scanner"));expect(scanner).toMatchObject({escalation:"DIRECTOR",target:{kind:"module",moduleId:"room-scanner"}});expect(scanner?.provenance).toEqual([`room-scanner:${id("27")}:v2`]);expect(managerScanner?.provenance).toEqual(scanner?.provenance);expect(projectManager.attention.filter(item=>item.id===scanner?.id)).toHaveLength(1);expect(projection.briefing).toMatchObject({overdue:1,blocked:1,documentFailures:1})});
 it("keeps people, communication, weather, drawing intelligence and canonical flows truthful",()=>{const projection=buildSiteManagerProjection(session,[project],runtimes,sources,project.id,"2026-08-14");expect(projection.people.map(item=>item.displayName)).toEqual(["Real Foreman","Project Manager"]);expect(projection.weather.truth).toBe("UNAVAILABLE");expect(projection.drawingIntelligence.truth).toBe("UNAVAILABLE");expect(dataFlowVisualRegistry.definitions.map(item=>item.id)).toEqual(["01","02","03","04","05","06","07","08"]);const html=renderToStaticMarkup(<OmniroSiteManagerWorkspace {...props}/>);expect(html).toContain("Role ≠ actor");expect(html).toContain("Voice Bridge");expect(html).toContain("No provider is connected");expect(html).not.toContain("87%");expect(html).not.toContain("18.7%")});
});
