import type{DocumentContract,ProjectContract,TaskContract}from"@odls/contracts";
import{renderToStaticMarkup}from"react-dom/server";
import{describe,expect,it}from"vitest";
import type{Session}from"./api.js";
import type{DirectorSources}from"./omniro-director-workspace-model.js";
import{OmniroProjectManagerWorkspace}from"./omniro-project-manager-workspace.js";
import{buildProjectManagerProjection}from"./omniro-project-manager-workspace-model.js";
import type{OmniroRuntimeSnapshot}from"./omniro-module-contract.js";
import{environmentHash,parseEnvironmentRoute}from"./omniro-operating-environment-model.js";
import{roleWorkspaceRegistry}from"./omniro-role-workspace-registry.js";

const id=(n:string)=>`10000000-0000-4000-8000-${n.padStart(12,"0")}`;
const project:ProjectContract={id:id("1"),tenantId:id("2"),clientId:id("3"),propertyId:id("4"),financialOwnerLegalEntityId:id("5"),projectManagerId:id("6"),projectNumber:"PRJ-024",name:"Office Complex",description:null,status:"active",startDate:"2026-01-01",expectedCompletionDate:"2026-09-30",actualCompletionDate:null,currencyCode:"PLN",estimatedBudget:null,approvedBudget:null,contractValue:null,paymentStatus:"not_required",billingCustomerReference:null,externalPaymentCustomerReference:null,version:4,createdAt:"2026-01-01",updatedAt:"2026-08-01",archivedAt:null};
const other={...project,id:id("20"),projectNumber:"PRJ-025",name:"Other Project"};
const permissions=["projects.read","tasks.read","documents.read","notifications.read","users.read","finance.read","reports.read","room_scans.read","work_scopes.read","engineering_norms.read","material_consumption.read","regional_pricing.read","company_price_books.read","commercial_estimates.read"];
const session:Session={accessToken:"a",refreshToken:"r",user:{id:id("9"),email:"director@example.com",displayName:"Director Actor"},permissions};
const task:TaskContract={id:id("7"),tenantId:project.tenantId,projectId:project.id,title:"Resolve blocked handover",description:null,status:"blocked",priority:"urgent",dueDate:"2026-08-01",startedAt:null,completedAt:null,isOverdue:true,assignees:[],version:3,createdAt:"2026-07-01",updatedAt:"2026-08-01",archivedAt:null};
const document:DocumentContract={id:id("8"),tenantId:project.tenantId,title:"Approved drawing source",documentType:"drawing",sourceType:"upload",status:"active",category:"project_plan",description:null,currentVersionNo:2,pageCount:1,ocrStatus:"failed",aiProcessingStatus:"completed",version:4,createdAt:"2026-01-01",createdBy:id("6"),updatedAt:"2026-08-01",updatedBy:id("6"),archivedAt:null,currentVersion:{id:id("10"),versionNo:2,originalFilename:"drawing.pdf",mimeType:"application/pdf",extension:"pdf",fileSize:100,checksum:"a".repeat(64),uploadedBy:id("6"),createdAt:"2026-08-01"},links:[{id:id("11"),entityType:"project",entityId:project.id}]};
const state={moduleId:"work-scope",projectId:project.id,truth:"REAL"as const,lifecycle:"APPROVAL_REQUIRED"as const,availability:"available"as const,status:"ready_for_approval",reason:"Approved authority requires a human decision.",record:{entityType:"work-scope",entityId:id("12"),version:2},evidence:[{entityType:"work-scope",entityId:id("12"),version:2,label:"Scope revision"}],observed:[{id:id("12"),projectId:project.id,code:"WS-024",name:"Office scope",revisionId:id("13"),revisionNumber:2,status:"ready_for_approval",version:2,items:[],mappings:[],sources:[]}]};
const runtime:OmniroRuntimeSnapshot={projectId:project.id,loadedAt:"2026-08-14",modules:new Map([[state.moduleId,state]])};
const sources:DirectorSources={tasks:[task,{...task,id:id("21"),projectId:other.id,title:"Other task"}],documents:[document,{...document,id:id("22"),links:[{id:id("23"),entityType:"project",entityId:other.id}]}],notifications:[],users:[{id:id("6"),email:"manager@example.com",displayName:"Real Project Manager",isDisabled:false,version:1}],invoices:[],payments:[],expenses:[],financialSummaries:[],sourceState:{tasks:{truth:"REAL",reason:"Tasks loaded."},documents:{truth:"REAL",reason:"Documents loaded."},notifications:{truth:"REAL",reason:"Notifications loaded."},users:{truth:"REAL",reason:"Users loaded."},finance:{truth:"PARTIAL",reason:"Finance incomplete."}}};
const runtimes=new Map([[project.id,runtime],[other.id,{...runtime,projectId:other.id,modules:new Map()}]]);
const props={session,projects:[project,other],project,runtimes,sources,flows:[],onBack:()=>undefined,onRole:()=>undefined,onProject:()=>undefined,onModule:()=>undefined,onWorkspace:()=>undefined,onContext:()=>undefined};

describe("OMNIRO Project Manager Workspace V1",()=>{
 it("activates the registered workspace by permission without replacing the actor",()=>{expect(roleWorkspaceRegistry.resolve("project-manager",session)).toMatchObject({truth:"REAL",actualActorId:session.user.id});expect(roleWorkspaceRegistry.resolve("project-manager",{...session,permissions:[]})).toMatchObject({truth:"UNAVAILABLE",actualActorId:session.user.id});expect(roleWorkspaceRegistry.resolve("site-manager",session).truth).toBe("REAL")});
 it("filters every operational source to the selected project",()=>{const projection=buildProjectManagerProjection(session,[project,other],runtimes,sources,project.id);expect(projection.tasks.map(item=>item.title)).toEqual([task.title]);expect(projection.documents.map(item=>item.id)).toEqual([document.id]);expect(projection.manager?.displayName).toBe("Real Project Manager")});
 it("keeps deterministic task, module and document attention with exact provenance",()=>{const projection=buildProjectManagerProjection(session,[project,other],runtimes,sources,project.id);expect(projection.attention.map(item=>item.id)).toEqual([`task:${task.id}`,`document:${document.id}`,`module:${project.id}:work-scope:${id("12")}`]);expect(projection.attention[0]).toMatchObject({responsibility:"UNASSIGNED",deadline:"2026-08-01",truth:"REAL"});expect(projection.attention[2].provenance).toEqual([`work-scope:${id("12")}:v2`])});
 it("escalates the same authority item when the actor lacks approval permission",()=>{const item=buildProjectManagerProjection(session,[project],runtimes,sources,project.id).attention.find(entry=>entry.id.startsWith("module:"));expect(item).toMatchObject({directorDecision:true,responsibility:"DIRECTOR DECISION REQUIRED",target:{kind:"module",moduleId:"work-scope"}})});
 it("preserves project-aware role deep links",()=>{const hash=environmentHash({layer:"role",roleId:"project-manager",projectId:project.id});expect(hash).toBe(`#omniro/role/project-manager?project=${project.id}`);expect(parseEnvironmentRoute(hash)).toEqual({layer:"role",roleId:"project-manager",projectId:project.id})});
 it("renders explicit truth boundaries without synthetic progress or profit",()=>{const html=renderToStaticMarkup(<OmniroProjectManagerWorkspace {...props}/>);expect(html).toContain("Project Manager Workspace");expect(html).toContain("Role ≠ actor");expect(html).toContain("DIRECTOR DECISION REQUIRED");expect(html).toContain("Drawing intelligence");expect(html).toContain("UNAVAILABLE");expect(html).toContain("No project financial summary is available");expect(html).not.toContain("87%");expect(html).not.toContain("18.7%")});
});
