import{renderToStaticMarkup}from"react-dom/server";
import{describe,expect,it}from"vitest";
import type{ProjectContract}from"@odls/contracts";
import{composeOmniroContext}from"./omniro-model.js";
import{LocalOrchestratorInterpreter}from"./omniro-interpreter.js";
import{BrowserSpeechRecognitionAdapter,BrowserSpeechSynthesisAdapter}from"./omniro-speech.js";
import{OmniroCommandCenter}from"./omniro-command-center.js";
import{deriveCompanyBrief,deriveEarthState,derivePresentation,rendererMode,semanticFlows,transitionPresence}from"./omniro-scene-model.js";
import{LivingEarth,OmniroPresence}from"./living-earth.js";

const project=(id:string,name:string):ProjectContract=>({id,tenantId:"00000000-0000-4000-8000-000000000001",clientId:"00000000-0000-4000-8000-000000000002",propertyId:"00000000-0000-4000-8000-000000000003",financialOwnerLegalEntityId:"00000000-0000-4000-8000-000000000004",projectManagerId:null,projectNumber:`P-${id.slice(-2)}`,name,description:null,status:"active",startDate:null,expectedCompletionDate:null,actualCompletionDate:null,currencyCode:"EUR",estimatedBudget:null,approvedBudget:null,contractValue:null,paymentStatus:"not_required",billingCustomerReference:null,externalPaymentCustomerReference:null,version:1,createdAt:"2026-01-01",updatedAt:"2026-01-01",archivedAt:null});
const projects=[project("00000000-0000-4000-8000-000000000071","Demo Apartment"),project("00000000-0000-4000-8000-000000000072","Office")];
const context=composeOmniroContext(projects,[{id:"s",propertyId:"p",projectId:projects[0].id,status:"approved",revision:1,version:1,createdAt:"2026",updatedAt:"2026"}],[{id:"t",projectId:projects[0].id,code:"TA",displayName:"Assignment",revisionId:"r",revisionNumber:1,status:"review_required",version:1}],[{id:"d",projectId:projects[0].id,code:"DP",displayName:"Design",revisionId:"r",revisionNumber:1,status:"draft",version:1}]);
describe("OMNIRO deterministic foundation",()=>{
 it("builds stable graph identifiers, ordering and planned unavailable stages",()=>{const again=composeOmniroContext([...projects].reverse(),[],[],[]);expect(context.projects.map(x=>x.name)).toEqual(["Demo Apartment","Office"]);expect(context.projects[0].stages[0].id).toBe(`project:${projects[0].id}:stage:room-scan`);expect(context.projects[0].stages.slice(3).every(x=>!x.available&&x.status==="unavailable")).toBe(true);expect(again.projects.map(x=>x.name)).toEqual(["Demo Apartment","Office"])});
 it("derives attention explicitly from lifecycle and incomplete records",()=>{expect(context.projects[0].attentionReasons).toHaveLength(2);expect(context.projects[1].attentionReasons).toHaveLength(3);expect(context.insights[0].priority).toBe(3);expect(context.insights[0].explanation.toLowerCase()).toContain("authoritative")});
 it("interprets supported English and Polish commands deterministically",async()=>{const i=new LocalOrchestratorInterpreter();expect((await i.interpret("What requires attention?",context)).intent).toBe("show_attention");expect((await i.interpret("Pokaż projekty",context)).intent).toBe("show_projects");expect((await i.interpret("Open project Demo Apartment",context)).projectId).toBe(projects[0].id);expect((await i.interpret("Show Technical Assignment",context)).stage).toBe("technical-assignment")});
 it("rejects unsupported and ambiguous commands without pretending to execute",async()=>{const i=new LocalOrchestratorInterpreter(),ambiguous=composeOmniroContext([project("00000000-0000-4000-8000-000000000073","Demo Apartment North"),project("00000000-0000-4000-8000-000000000074","Demo Apartment South")],[],[],[]);expect((await i.interpret("Calculate estimate",context)).supported).toBe(false);expect((await i.interpret("Open project Demo Apartment",ambiguous)).explanation).toContain("More than one")});
 it("detects unsupported browser speech capabilities behind adapters",()=>{const scope={}as Window;expect(new BrowserSpeechRecognitionAdapter(scope).supported).toBe(false);expect(new BrowserSpeechSynthesisAdapter(scope).supported).toBe(false)});
 it("renders an accessible loading state before authoritative REST composition",()=>{const session={accessToken:"a",refreshToken:"r",user:{id:"u",email:"u@example.com",displayName:"User"},permissions:["projects.read"]};const speech={supported:false,start:()=>undefined,stop:()=>undefined};const synthesis={supported:false,speak:()=>undefined,cancel:()=>undefined};const html=renderToStaticMarkup(<OmniroCommandCenter session={session} navigate={()=>undefined} recognition={speech} synthesis={synthesis}/>);expect(html).toContain("Composing authoritative business state");expect(html).toContain('role=\"status\"')});
 it("uses an explicit deterministic orchestrator state machine",()=>{expect(transitionPresence("present","listen")).toBe("listening");expect(transitionPresence("listening","interpret")).toBe("interpreting");expect(transitionPresence("interpreting","show-attention")).toBe("directing-attention");expect(transitionPresence("interpreting","focus-project")).toBe("focusing-project");expect(transitionPresence("error","reset")).toBe("present")});
 it("derives Earth states and renderer fallback without animation timing",()=>{expect(deriveEarthState("listening","",false,false,false,false)).toBe("listening");expect(deriveEarthState("present",projects[0].id,false,false,false,false)).toBe("project-focus");expect(deriveEarthState("present","",false,false,true,false)).toBe("reduced-motion");expect(rendererMode("enhanced",true,false)).toBe("fallback");expect(rendererMode("enhanced",false,true)).toBe("static")});
 it("maps authoritative lifecycle records to stable semantic flows",()=>{const flows=semanticFlows(context.projects,projects[0].id);expect(flows[0]).toMatchObject({id:`flow:project:${projects[0].id}`,kind:"assistant-focus"});expect(flows.some(x=>x.kind==="room-scan"&&x.state==="completed")).toBe(true);expect(flows.filter(x=>x.kind==="unavailable")).toHaveLength(10)});
 it("derives a truthful company brief without time or event claims",()=>{const brief=deriveCompanyBrief(context);expect(brief).toContain("currently loaded authoritative state");expect(brief).toContain("2 projects require workflow attention");expect(brief).not.toMatch(/overnight|real-time|analyzed/)});
 it("returns structured explainability and honest unsupported capabilities",async()=>{const interpreted=await new LocalOrchestratorInterpreter().interpret("Рассчитай смету",context),presentation=derivePresentation(interpreted,context);expect(presentation.mutatedData).toBe(false);expect(presentation.unsupportedCapability).toBe("Estimate");expect(presentation.verification).toContain("workspace")});
 it("renders a recognizable semantic Earth and non-human presence",()=>{const earth=renderToStaticMarkup(<LivingEarth state="company-attention" flowCount={4}/>),presence=renderToStaticMarkup(<OmniroPresence state="directing-attention"/>);expect(earth).toContain("digital Earth");expect(earth).toContain("conceptual, not geographic");expect(earth).toContain("<path");expect(presence).toContain("orchestrator state: directing-attention")});
});
