import{useEffect,useMemo,useState}from"react";
import type{DocumentContract,ProjectContract,TaskContract,TaskProblemContract}from"@odls/contracts";
import{api,apiErrorMessage,type Session}from"./api.js";
import{roleWorkspaceRegistry}from"./omniro-role-workspace-registry.js";

export type WorkerCapabilityState="REAL"|"DERIVED"|"PARTIAL"|"UNAVAILABLE";
export const workerCapabilityStates={today:"DERIVED",tasks:"REAL",object:"PARTIAL",proof:"REAL",review:"REAL",problems:"REAL",materials:"PARTIAL",documents:"REAL",correspondence:"UNAVAILABLE",notes:"UNAVAILABLE",qr:"UNAVAILABLE",voice:"UNAVAILABLE"}satisfies Record<string,WorkerCapabilityState>;
export const isAssignedTo=(task:TaskContract,userId:string)=>task.assignees.some(item=>item.userId===userId);
export const dueToday=(task:TaskContract,today=new Date())=>task.dueDate===today.toISOString().slice(0,10);
export const workerAction=(status:TaskContract["status"])=>status==="todo"||status==="returned"?"start":status==="in_progress"?"submit":null;
const truth=(value:WorkerCapabilityState)=><span className={`oe-truth truth-${value.toLowerCase()}`}>{value}</span>,date=(value:string|null)=>value?new Intl.DateTimeFormat(undefined,{dateStyle:"medium"}).format(new Date(`${value}T12:00:00`)):"Not specified",location=(task?:TaskContract)=>task?.description?.match(/(?:location|area|room|zone|surface):\s*([^\n.;]+)/i)?.[1]?.trim()??"Not available in the current task authority";
const categories=["missing_material","blocker","defect","damage","unsafe_condition","needs_foreman_answer","other"]as const;

type Props={session:Session;project?:ProjectContract;onScanner?:()=>void;onNotifications?:()=>void;onBack?:()=>void};
export function OmniroWorkerWorkspace({session,project,onScanner,onNotifications,onBack}:Props){
 const [tasks,setTasks]=useState<TaskContract[]>([]),[documents,setDocuments]=useState<DocumentContract[]>([]),[problems,setProblems]=useState<TaskProblemContract[]>([]),[selectedId,setSelectedId]=useState(""),[busy,setBusy]=useState(true),[error,setError]=useState(""),[comment,setComment]=useState(""),[category,setCategory]=useState<typeof categories[number]>("blocker"),[problemText,setProblemText]=useState(""),[uploading,setUploading]=useState(false);
 const selected=tasks.find(item=>item.id===selectedId)??tasks[0],resolved=roleWorkspaceRegistry.resolve("worker",session),can=(permission:string)=>session.permissions.includes(permission);
 const load=async()=>{setBusy(true);try{const assigned=(await api.assignedTasks(session.user.id)).filter(item=>isAssignedTo(item,session.user.id));setTasks(assigned);setSelectedId(current=>assigned.some(item=>item.id===current)?current:assigned[0]?.id??"");setError("")}catch(problem){setError(apiErrorMessage(problem))}finally{setBusy(false)}};
 useEffect(()=>{void load()},[session.user.id]);
 useEffect(()=>{if(!selected)return;const requests:Promise<unknown>[]=[];if(can("documents.read"))requests.push(api.taskDocuments(selected.id).then(setDocuments));if(can("task_problems.read"))requests.push(api.taskProblems(selected.id).then(setProblems));void Promise.all(requests).catch(problem=>setError(apiErrorMessage(problem)))},[selected?.id]);
 const today=useMemo(()=>tasks.filter(item=>dueToday(item)),[tasks]),open=tasks.filter(item=>!["accepted","completed","cancelled","archived"].includes(item.status));
 const replace=(task:TaskContract)=>setTasks(current=>current.map(item=>item.id===task.id?task:item));
 const transition=async()=>{if(!selected)return;const action=workerAction(selected.status);if(!action)return;try{const updated=action==="submit"?await api.taskReview(selected.id,"submit",selected.version,comment):await api.taskLifecycle(selected.id,"start",selected.version);replace(updated);setComment("");setError("")}catch(problem){setError(apiErrorMessage(problem))}};
 const upload=async(file:File|null)=>{if(!file||!selected)return;setUploading(true);try{await api.uploadDocument(file,{category:"photo",description:`Worker proof for task ${selected.title}${comment?`: ${comment}`:""}`,entityType:"task",entityId:selected.id});setDocuments(await api.taskDocuments(selected.id));setError("")}catch(problem){setError(apiErrorMessage(problem))}finally{setUploading(false)}};
 const report=async(event:React.FormEvent)=>{event.preventDefault();if(!selected)return;try{const created=await api.createTaskProblem(selected.id,{category,description:problemText,location:location(selected).startsWith("Not available")?undefined:location(selected)});setProblems(current=>[created,...current]);setProblemText("");setError("")}catch(problem){setError(apiErrorMessage(problem))}};
 return <main className="oe-worker-v1" aria-labelledby="worker-title"><header><div>{onBack&&<button onClick={onBack}>← Product World</button>}<small>OMNIRO BUILDING · FIELD EXECUTION</small><h1 id="worker-title">Worker Workspace</h1><p>Role ≠ actor · {session.user.displayName} · assigned work only</p></div>{truth(resolved.truth)}</header>{error&&<p role="alert" className="worker-error">{error}</p>}
  <nav aria-label="Worker workspace sections">{["Today","My Tasks","Object","Proof","Report Problem","Materials","Documents","Correspondence"].map(label=><a key={label} href={`#worker-${label.toLowerCase().replaceAll(" ","-")}`}>{label}</a>)}</nav>
  <section id="worker-today" className="worker-metrics"><article><span>Due today {truth("DERIVED")}</span><b>{today.length}</b></article><article><span>Open assigned {truth("REAL")}</span><b>{open.length}</b></article><article><span>Review queue {truth("REAL")}</span><b>{tasks.filter(item=>item.status==="submitted_for_review").length}</b></article></section>
  <div className="worker-columns"><section id="worker-my-tasks" className="worker-card"><header><h2>My Tasks</h2>{truth("REAL")}</header>{busy?<p>Loading assigned tasks…</p>:tasks.length?<div className="worker-task-list">{tasks.map(task=><button key={task.id} className={selected?.id===task.id?"selected":""} onClick={()=>setSelectedId(task.id)}><span><strong>{task.title}</strong><small>{task.status.replaceAll("_"," ")} · {task.priority}</small></span><b>{date(task.dueDate)}</b></button>)}</div>:<p>No tasks are assigned to this actor.</p>}</section>
   <section id="worker-object" className="worker-card worker-object"><header><h2>Object / instruction</h2>{truth("PARTIAL")}</header>{selected?<><dl><div><dt>Project</dt><dd>{project?.name??selected.projectId}</dd></div><div><dt>Location / zone</dt><dd>{location(selected)}</dd></div><div><dt>Instruction</dt><dd>{selected.description||"No instruction provided."}</dd></div><div><dt>Deadline</dt><dd>{date(selected.dueDate)}</dd></div></dl>{selected.lastReview?.action==="returned"&&<p className="worker-return"><b>Returned by foreman:</b> {selected.lastReview.comment}</p>}<label>Completion comment<textarea value={comment} maxLength={2000} onChange={event=>setComment(event.target.value)}/></label><button disabled={!workerAction(selected.status)||!can("tasks.self_update")} onClick={()=>void transition()}>{workerAction(selected.status)==="start"?"Start assigned task":workerAction(selected.status)==="submit"?"Submit for foreman review":selected.status==="submitted_for_review"?"Awaiting human review":selected.status==="accepted"?"Accepted":"No worker transition available"}</button></>:<p>Select an assigned task.</p>}</section></div>
  <section id="worker-proof" className="worker-card"><header><h2>Proof / Documents</h2>{truth(can("documents.read")?"REAL":"UNAVAILABLE")}</header>{selected&&can("documents.create")?<label className="worker-upload">Attach task evidence<input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" disabled={uploading} onChange={event=>void upload(event.target.files?.[0]??null)}/><small>{uploading?"Uploading…":"Existing Documents flow · task-linked · tenant-authorized"}</small></label>:<p>Evidence requires an assigned task and document permission.</p>}<div className="worker-documents">{documents.map(document=><article key={document.id}><strong>{document.title}</strong><span>{document.category} · v{document.currentVersionNo}</span><small>document:{document.id}:v{document.version}</small></article>)}{selected&&can("documents.read")&&!documents.length&&<p>No task evidence attached.</p>}</div></section>
  <section id="worker-report-problem" className="worker-card"><header><h2>Report Problem</h2>{truth(can("task_problems.create")?"REAL":"UNAVAILABLE")}</header>{selected&&can("task_problems.create")?<form onSubmit={report}><label>Type<select value={category} onChange={event=>setCategory(event.target.value as typeof category)}>{categories.map(item=><option key={item} value={item}>{item.replaceAll("_"," ")}</option>)}</select></label><label>What happened<textarea required maxLength={4000} value={problemText} onChange={event=>setProblemText(event.target.value)}/></label><button>Notify responsible foreman</button></form>:<p>Problem reporting is unavailable for this actor/task.</p>}<div className="worker-problems">{problems.map(problem=><article key={problem.id}><b>{problem.category.replaceAll("_"," ")}</b><span>{problem.status}</span><p>{problem.description}</p><small>{problem.location??"Location not provided"} · v{problem.version}</small></article>)}</div></section>
  <section className="worker-capabilities"><article id="worker-materials"><h2>Materials {truth("PARTIAL")}</h2><p>Project Material Consumption exists, but task-to-requirement assignment and issue/receipt authority do not. No prices, margin, supplier terms or invented issue state are shown.</p><button onClick={()=>{setCategory("missing_material");document.getElementById("worker-report-problem")?.scrollIntoView()}}>Report missing material</button></article><article><h2>Scanner {truth(can("room_scans.read")?"REAL":"UNAVAILABLE")}</h2><p>The shared OMNIRO Scanner remains the authority. No Worker-specific scanner is created.</p><button disabled={!can("room_scans.read")||!onScanner} onClick={onScanner}>Open existing Scanner</button></article><article id="worker-correspondence"><h2>Correspondence {truth("UNAVAILABLE")}</h2><p>No assignment-scoped communication provider is connected. Personal OMNIRO notifications remain available.</p><button disabled={!onNotifications} onClick={onNotifications}>Open notifications</button></article><article><h2>Notes / QR / Voice {truth("UNAVAILABLE")}</h2><p>No shared Notes authority, QR/barcode decoder or ephemeral multilingual Voice Bridge is connected. Nothing is simulated or stored locally.</p></article></section>
  <footer><b>Human authority:</b> only Site Manager / Foreman can accept or return submitted work. AI Secretary remains deterministic guidance and cannot approve.</footer>
 </main>;
}
