import React from"react";
import{renderToStaticMarkup}from"react-dom/server";
import{describe,expect,it,vi}from"vitest";
import type{CommercialEstimateDto,Session}from"./api.js";
import{CommercialEstimateWorkspaceView}from"./omniro-commercial-estimate-workspace.js";

const session:Session={accessToken:"x",refreshToken:"x",user:{id:"u",email:"u@example.test",displayName:"Reviewer"},permissions:["commercial_estimates.read","commercial_estimates.review","commercial_estimates.approve","commercial_estimates.snapshots.read"]};
const estimate:CommercialEstimateDto={id:"estimate-1",projectId:"project-1",code:"CE-001",title:"Apartment commercial offer",revisionId:"revision-1",revisionNumber:2,status:"ready_for_approval",mode:"tender",currency:"PLN",version:3,totals:{laborCost:200,materialCost:80,equipmentCost:40,otherCost:57.4,overhead:37.74,internalCost:415.14,unitPrice:49.29788,netTotal:492.9788,discountAmount:0,vatAmount:113.3851,grossTotal:606.3639,profit:77.8388,marginPercent:15.7895,currency:"PLN"},lines:[{id:"line-1",work_code:"PAINT",localized_description:"Paint apartment walls",target_element:"scope-item-1",quantity:10,unit_code:"M2",labor_cost:200,material_cost:80,equipment_cost:40,other_cost:57.4,overhead:37.74,internal_cost:415.14,unit_price:49.29788,net_total:492.9788,discount_amount:0,vat_amount:113.3851,gross_total:606.3639,profit:77.8388,margin_percent:15.7895,currency:"PLN",price_source:"Warsaw verified rates",calculation_trace:{schemaVersion:"commercial-calculation-v1",formula:"source-driven"},engineering_references:{workScopeSnapshotId:"scope-snapshot",normSnapshotId:"norm-snapshot",knowledgeVersionId:"knowledge-v1",technologyVersionId:"technology-v1",materialConsumptionSnapshotId:"consumption-snapshot",materialConsumptionFingerprint:"mc-fingerprint",regionalPricingSnapshotId:"pricing-snapshot",regionalPricingFingerprint:"rp-fingerprint",normFingerprint:"norm-fingerprint"},norm_revision_number:4,technology_version_id:"technology-v1"}],analysis:{estimateId:"estimate-1",status:"ready_for_approval",complete:true,profitability:{profit:77.8388,marginPercent:15.7895,negativeProfit:false},sourceSnapshots:{materialConsumptionSnapshotId:"consumption-snapshot",pricingSnapshotId:"pricing-snapshot"},recommendations:[],mutatedData:false,approvedDataChanged:false}};

describe("Commercial Estimate workspace",()=>{it("renders exact backend costs, client price, authorities, provenance, and human approval",()=>{const html=renderToStaticMarkup(<CommercialEstimateWorkspaceView session={session} estimate={estimate} analysis={estimate.analysis} busy={false} onReview={vi.fn()} onApprove={vi.fn()} onClose={vi.fn()}/>);expect(html).toContain('aria-label="Commercial Estimate Agent Workspace"');expect(html).toContain("REAL BACKEND VALUES");expect(html).toContain("PLN");expect(html).toContain("606.36");expect(html).toContain("consumption-snapshot");expect(html).toContain("pricing-snapshot");expect(html).toContain("Warsaw verified rates");expect(html).toContain("HUMAN APPROVAL · COMMERCIAL ESTIMATE");expect(html).toContain("engineeringReferences")});it("renders truthful empty and read-only approval states",()=>{const empty=renderToStaticMarkup(<CommercialEstimateWorkspaceView session={{...session,permissions:["commercial_estimates.read"]}} busy={false} onReview={vi.fn()} onApprove={vi.fn()} onClose={vi.fn()}/>);expect(empty).toContain("No Commercial Estimate exists");const readonly=renderToStaticMarkup(<CommercialEstimateWorkspaceView session={{...session,permissions:["commercial_estimates.read"]}} estimate={estimate} analysis={estimate.analysis} busy={false} onReview={vi.fn()} onApprove={vi.fn()} onClose={vi.fn()}/>);expect(readonly).toContain("does not have commercial_estimates.approve")});it("shows approved immutable snapshot without claiming downstream execution",()=>{const approved={...estimate,status:"approved"as const},html=renderToStaticMarkup(<CommercialEstimateWorkspaceView session={session} estimate={approved} analysis={{...estimate.analysis!,status:"approved"}} snapshot={{id:"estimate-snapshot",contentFingerprint:"fingerprint",schemaVersion:"commercial-estimate-v1",revisionNumber:2}} busy={false} onReview={vi.fn()} onApprove={vi.fn()} onClose={vi.fn()}/>);expect(html).toContain("Approved immutable commercial snapshot");expect(html).toContain("estimate-snapshot");expect(html).toContain("Downstream execution not started")})});
