import type{ProjectContract}from"@odls/contracts";
import type{Session}from"./api.js";
import{OmniroDataFlowLegend,type DataFlowProjection}from"./omniro-data-flow-renderer.js";
import{buildDirectorProjection,type DirectorSources,type DirectorTarget}from"./omniro-director-workspace-model.js";
import type{OmniroRuntimeSnapshot}from"./omniro-module-contract.js";
import{roleWorkspaceRegistry}from"./omniro-role-workspace-registry.js";

export type DirectorContextPage="project-workspace"|"tasks"|"documents"|"finance"|"reports"|"notifications";
type Props={session:Session;projects:ProjectContract[];project:ProjectContract;runtimes:ReadonlyMap<string,OmniroRuntimeSnapshot>;sources:DirectorSources;flows:readonly DataFlowProjection[];onBack:()=>void;onRole:(id:string)=>void;onProject:(id:string)=>void;onModule:(id:string,projectId?:string)=>void;onWorkspace:(id:string,projectId?:string)=>void;onContext:(page:DirectorContextPage,id?:string)=>void};
const truth=(value:string)=><span className={`oe-truth truth-${value.toLowerCase()}`}>{value}</span>;

export function OmniroDirectorWorkspace({session,projects,project,runtimes,sources,flows,onBack,onRole,onProject,onModule,onWorkspace,onContext}:Props){
 const resolved=roleWorkspaceRegistry.resolve("director",session),projection=buildDirectorProjection(session,projects,runtimes,sources,project.id);
 const open=(target:DirectorTarget)=>{if(target.kind==="workspace"&&target.moduleId)return onWorkspace(target.moduleId,target.projectId);if(target.kind==="module"&&target.moduleId)return onModule(target.moduleId,target.projectId);if(target.kind==="project")return onContext("project-workspace",target.projectId);if(target.kind==="task")return onContext("tasks",target.entityId);if(target.kind==="document")return onContext("documents",target.entityId);if(target.kind==="finance")return onContext("finance",target.entityId);if(target.kind==="reports")return onContext("reports");return onContext("notifications")};
 const can=(permission:string)=>session.permissions.includes(permission);
 const organizationWorkspaces=[{id:"projects",label:"Projects",real:can("projects.read"),open:()=>onContext("project-workspace",project.id)},{id:"tasks",label:"Tasks & deadlines",real:can("tasks.read"),open:()=>onContext("tasks")},{id:"documents",label:"Documents",real:can("documents.read"),open:()=>onContext("documents")},{id:"finance",label:"Finance",real:can("finance.read"),open:()=>onContext("finance")},{id:"company-price-book",label:"Company Price Book",real:can("company_price_books.read"),open:()=>onWorkspace("company-price-book",project.id)},{id:"commercial-estimate",label:"Commercial Estimate",real:can("commercial_estimates.read"),open:()=>onWorkspace("commercial-estimate",project.id)}];
 return <main className="oe-role oe-director-v1" aria-labelledby="oe-role-title">
  <aside className="oe-role-rail"><small>LAYER 3 · ROLE WORKSPACE</small><button onClick={onBack}>← Back to Product World</button><h2>Role workspaces</h2>{roleWorkspaceRegistry.definitions.map(definition=>{const state=roleWorkspaceRegistry.resolve(definition.roleId,session);return <button key={definition.roleId} disabled={state.truth==="UNAVAILABLE"} className={definition.roleId==="director"?"is-current":""} onClick={()=>state.truth!=="UNAVAILABLE"&&onRole(definition.roleId)}>{definition.label}<small>{state.truth}</small></button>})}<h3>Organizational workspaces</h3>{organizationWorkspaces.map(item=><button key={item.id} disabled={!item.real} onClick={item.open}>{item.label}<small>{item.real?"AVAILABLE":"UNAVAILABLE"}</small></button>)}<section className="oe-temporary-access"><strong>Temporary access</strong>{truth("UNAVAILABLE")}<p>Project/workspace/time-bound external assignments require a future backend authority. No second authorization system is created.</p></section></aside>
  <section className="oe-director" aria-label="Director Owner organizational super-workspace"><header><div><small>AUTHENTICATED ACTOR · ROLE ≠ ACTOR</small><h1 id="oe-role-title">Director / Owner Workspace</h1><p>{session.user.displayName} · actions remain attributed to actor {session.user.id}</p></div>{truth(resolved.truth)}</header><OmniroDataFlowLegend flows={flows} compact/>
   <section className="oe-director-metrics" aria-label="Grounded Director overview">{projection.metrics.map(metric=><article key={metric.id}><small>{metric.label}</small><strong>{metric.value}</strong><span>{metric.reason}</span>{truth(metric.truth)}</article>)}</section>
   <section className="oe-director-grid">
    <article className="oe-priority-actions"><header><h2>Priority actions</h2><small>WHAT · WHY · WHERE · WHO · URGENCY</small></header>{projection.priorityActions.length?projection.priorityActions.slice(0,8).map(action=><button key={action.id} onClick={()=>open(action.target)} data-source={action.source}><span><strong>{action.title}</strong><small>{action.reason}</small><em>{action.responsiblePerson??action.responsibleRole??"No authoritative assignment"}</em></span><b className={`urgency-${action.urgency}`}>{action.urgency}<small>{action.status.replaceAll("_"," ")}</small></b><i>{action.provenance.join(" · ")}</i></button>):<p>No loaded source reports an actionable state.</p>}</article>
    <article className="oe-decision-center"><header><h2>Decision center</h2><small>Existing domain authorities only</small></header>{projection.decisions.length?projection.decisions.map(action=><button key={action.id} onClick={()=>open(action.target)}><span><strong>{action.title}</strong><small>{action.reason}</small></span><b>Open evidence & decision →</b></button>):<p>No existing approval adapter currently requires the Director.</p>}<footer>Approvals call existing module workspaces. No generic bypass or impersonation is available.</footer></article>
    <article className="oe-project-portfolio"><header><h2>Project responsibility</h2><small>{projects.length} readable projects</small></header>{projects.map(item=><button key={item.id} className={item.id===project.id?"is-current":""} onClick={()=>onProject(item.id)}><span><strong>{item.projectNumber} · {item.name}</strong><small>{item.status} · manager {projection.people.find(person=>person.id===item.projectManagerId)?.displayName??"not authoritatively assigned"}</small></span><b>{item.expectedCompletionDate??"No deadline"}</b></button>)}</article>
    <article className="oe-calendar"><header><h2>Deadlines</h2>{truth(projection.calendar.truth)}</header><p>{projection.calendar.reason}</p>{projection.calendar.items.map(item=><button key={item.id} onClick={()=>open(item.target)}><span>{item.label}</span><b>{item.date}</b><small>{item.provenance}</small></button>)}</article>
    <article className="oe-financial-summary"><header><h2>Project accounting summary</h2>{truth(sources.sourceState.finance.truth)}</header>{projection.currentFinancial?<><dl><div><dt>Budget</dt><dd>{projection.currentFinancial.budget??"not set"} {projection.currentFinancial.currencyCode}</dd></div><div><dt>Invoiced</dt><dd>{projection.currentFinancial.invoicedGross} {projection.currentFinancial.currencyCode}</dd></div><div><dt>Paid</dt><dd>{projection.currentFinancial.paid} {projection.currentFinancial.currencyCode}</dd></div><div><dt>Outstanding</dt><dd>{projection.currentFinancial.outstanding} {projection.currentFinancial.currencyCode}</dd></div><div><dt>Expenses</dt><dd>{projection.currentFinancial.expenses} {projection.currentFinancial.currencyCode}</dd></div><div><dt>Accounting gross margin</dt><dd>{projection.currentFinancial.grossMarginAmount} {projection.currentFinancial.currencyCode}{projection.currentFinancial.grossMarginPercentage===null?"":` · ${projection.currentFinancial.grossMarginPercentage}%`}</dd></div></dl><small>project-financial-summary:{projection.currentFinancial.projectId}</small><button onClick={()=>onContext("finance",project.id)}>Open Finance</button></>:<p>{sources.sourceState.finance.reason} No accounting value is inferred.</p>}</article>
    <article className="oe-people"><header><h2>Organization & people</h2>{truth(sources.sourceState.users.truth)}</header>{projection.people.length?projection.people.map(person=><section key={person.id}><strong>{person.displayName}</strong><small>{person.email} · {person.active?"active user":"disabled user"}</small>{person.responsibilities.length?<ul>{person.responsibilities.map(item=><li key={item}>{item}</li>)}</ul>:<p>No authoritative project/task responsibility.</p>}</section>):<p>{sources.sourceState.users.reason}</p>}<footer>Employment type and temporary/external status are not inferred.</footer></article>
    <article className="oe-quick-access"><header><h2>Grounded quick access</h2><small>Existing permissions</small></header><div><button disabled={!can("projects.read")} onClick={()=>onContext("project-workspace",project.id)}>Projects</button><button disabled={!can("documents.read")} onClick={()=>onContext("documents")}>Documents</button><button disabled={!can("room_scans.read")} onClick={()=>onWorkspace("room-scanner",project.id)}>Scanner</button><button disabled={!can("company_price_books.read")} onClick={()=>onWorkspace("company-price-book",project.id)}>Company Price Book</button><button disabled={!can("commercial_estimates.read")} onClick={()=>onWorkspace("commercial-estimate",project.id)}>Commercial Estimate</button><button disabled={!can("reports.read")} onClick={()=>onContext("reports")}>Reports</button><button disabled={!can("notifications.read")} onClick={()=>onContext("notifications")}>OMNIRO Internal</button></div></article>
   </section>
  </section>
  <aside className="oe-intelligence oe-director-intelligence"><small>INTELLIGENCE RAIL</small><h2>Grounded assistance</h2><article><header><strong>Orchestrator</strong>{truth("DERIVED")}</header><p>{projection.priorityActions.length?`${projection.priorityActions.length} grounded item${projection.priorityActions.length===1?"":"s"} require attention across loaded authorities.`:"No loaded authority declares an attention state."}</p></article><article><header><strong>AI Secretary</strong>{truth("PARTIAL")}</header><p>{projection.briefing.length?`${projection.briefing.length} item${projection.briefing.length===1?"":"s"} require your attention.`:"No grounded briefing item is available."}</p>{projection.briefing.map(item=><button key={item.id} onClick={()=>open(item.target)}><b>{item.label}</b><small>{item.reason}</small><i>{item.provenance.join(" · ")}</i></button>)}</article><article><header><strong>Economic Analyst</strong>{truth(projection.commercialAnalysis?"PARTIAL":"UNAVAILABLE")}</header>{projection.commercialAnalysis?<><p><b>{projection.commercialAnalysis.code}</b> · project estimate margin {projection.commercialAnalysis.marginPercent??"unavailable"}% · calculated profit {projection.commercialAnalysis.profit??"unavailable"} {projection.commercialAnalysis.currency}</p><small>{projection.commercialAnalysis.reason}</small><button onClick={()=>onWorkspace("commercial-estimate",project.id)}>Open Commercial Estimate</button></>:<p>No complete project commercial calculation is loaded. Company accounting profit is not inferred.</p>}</article><article><header><strong>Legal / Compliance</strong>{truth(projection.legal.truth)}</header><p>{projection.legal.documents} contract/permit document records are visible. {projection.legal.reason}</p><small>No law-change claim is generated.</small></article><section><h3>Communication hub</h3>{resolved.definition.communicationCapabilities.map(capability=>{const allowed=capability.requiredPermissions.every(permission=>can(permission)),state=capability.truth==="REAL"&&!allowed?"UNAVAILABLE":capability.truth;return <p key={capability.id}><b>{capability.label}</b>{truth(state)}<small>{state==="REAL"?`${sources.notifications.filter(item=>item.status==="unread").length} unread authenticated-recipient notifications.`:capability.reason}</small></p>})}</section><section><h3>Document inbox</h3><p>{sources.documents.length} readable documents · Scanner and browser upload remain available through existing workspaces.</p><button disabled={!can("documents.read")} onClick={()=>onContext("documents")}>Open Documents</button><button disabled={!can("room_scans.read")} onClick={()=>onWorkspace("room-scanner",project.id)}>Open Scanner</button></section></aside>
 </main>;
}
