import type{ProjectContract}from"@odls/contracts";
import type{OmniroFlowRuntimeState}from"./omniro-flow-contract.js";
import type{OmniroExplanationProjection,OmniroRuntimeSnapshot}from"./omniro-module-contract.js";
import type{OmniroRoute}from"./omniro-command-center-route.js";
import type{OmniroQuality}from"./omniro-operational-scene.js";
import type{Session}from"./api.js";
import{buildingModuleRegistry}from"./omniro-building-modules.js";
import{buildingWorkspaceRegistry}from"./omniro-building-workspaces.js";
import{OmniroOperationalScene}from"./omniro-operational-scene.js";
import{OmniroOperationalGraph}from"./omniro-operational-graph.js";
import{OmniroProjectNucleus}from"./omniro-project-nucleus.js";
import{OmniroAuthorityBoundary}from"./omniro-authority-boundary.js";
import{OmniroOrchestratorLayer}from"./omniro-orchestrator-layer.js";
import{OmniroFocusFrame}from"./omniro-focus-frame.js";

type Props={session:Session;projects:ProjectContract[];project:ProjectContract;runtime:OmniroRuntimeSnapshot;flows:readonly OmniroFlowRuntimeState[];route:OmniroRoute;quality:OmniroQuality;forceFallback:boolean;explanation?:OmniroExplanationProjection;explanationOpen:boolean;onProject:(id:string)=>void;onFocus:(id:string)=>void;onWorkspace:(id:string)=>void;onCloseWorkspace:()=>void;onToggleExplanation:()=>void;onQuality:(quality:OmniroQuality)=>void;onNavigateContext:(page:"documents"|"tasks")=>void;onUniverse:()=>void};

export function OmniroCommandCenterShell({session,projects,project,runtime,flows,route,quality,forceFallback,explanation,explanationOpen,onProject,onFocus,onWorkspace,onCloseWorkspace,onToggleExplanation,onQuality,onNavigateContext,onUniverse}:Props){
 const selectedId=route.moduleId??"project",selected=runtime.modules.get(selectedId)??runtime.modules.get("project")!,definition=buildingModuleRegistry.get(selectedId)??buildingModuleRegistry.require("project"),approval=definition.approval?.detect(selected,session),highlight=new Set([...(explanation?.highlight.moduleIds??[]),...(explanation?.highlight.flowIds??[])]),focus=route.level!=="operational",attention=[...runtime.modules.values()].filter(item=>["WAIT","APPROVAL_REQUIRED","CONFLICT","BLOCKED"].includes(item.lifecycle));
 return <section className={`oc-shell view-${route.level} lifecycle-${selected.lifecycle.toLowerCase()}`} aria-labelledby="oc-title">
  <header className="oc-command-band"><button className="oc-brand" onClick={onUniverse} aria-label="Open OMNIRO Universe"><i aria-hidden="true"/><strong>OMNIRO</strong></button><label>Operational project<select aria-label="Operational project" value={project.id} onChange={event=>onProject(event.target.value)}>{projects.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><div><span className="oc-attention">{attention.length} require attention</span><label className="oc-quality">Render<select aria-label="Rendering mode" value={quality} onChange={event=>onQuality(event.target.value as OmniroQuality)}><option value="enhanced">Enhanced</option><option value="balanced">Balanced</option><option value="reduced">Reduced</option></select></label><span>{session.user.displayName}</span></div></header>
  <aside className="oc-project-rail"><small>PROJECT CONTEXT</small><h1 id="oc-title">{project.name}</h1><strong>{project.projectNumber}</strong><dl><dt>Lifecycle</dt><dd>{project.status}</dd><dt>Currency</dt><dd>{project.currencyCode}</dd><dt>Authority</dt><dd>{runtime.modules.get("room-scanner")?.record?`Scanner v${runtime.modules.get("room-scanner")?.record?.version??"—"}`:"No approved context"}</dd></dl><nav aria-label="Project context"><button onClick={()=>onNavigateContext("tasks")}>▤ Tasks</button><button onClick={()=>onNavigateContext("documents")}>▱ Documents</button></nav></aside>
  <main className="oc-space"><OmniroOperationalScene modules={[...runtime.modules.values()]} selectedId={selectedId} lifecycle={selected.lifecycle} quality={quality} forceFallback={forceFallback}/><OmniroProjectNucleus project={project} scanner={runtime.modules.get("room-scanner")}/><OmniroOperationalGraph definitions={buildingModuleRegistry.definitions} runtime={runtime.modules} flows={flows} selectedId={selectedId} highlight={highlight} onFocus={onFocus} onEnter={onWorkspace}/>{focus&&route.level==="focus"&&<section className="oc-focus-summary" aria-label={`${definition.label} focus view`}><small>FOCUS / SYSTEM VIEW · {selected.truth}</small><h2>{definition.label}</h2><p>{selected.reason}</p>{definition.workspace&&selected.availability!=="unavailable"&&<button onClick={()=>onWorkspace(definition.id)}>ENTER AGENT WORKSPACE →</button>}</section>}{route.level==="workspace"&&<OmniroFocusFrame definition={definition} runtime={selected} session={session} projectId={project.id} registry={buildingWorkspaceRegistry} onClose={onCloseWorkspace}/>}</main>
  <aside className="oc-attention-rail"><small>WHAT NEEDS HUMAN ATTENTION NOW?</small><h2>Operational attention</h2>{approval?<OmniroAuthorityBoundary approval={approval} onOpen={()=>onWorkspace(definition.id)}/>:<><article><strong>{selected.label??definition.label}</strong><p>{selected.reason}</p><span>{selected.truth}</span></article><ul>{attention.slice(0,4).map(item=><li key={item.moduleId}><button onClick={()=>onFocus(item.moduleId)}>{buildingModuleRegistry.get(item.moduleId)?.label}<small>{item.status.replaceAll("_"," ")}</small></button></li>)}</ul></>}</aside>
  <OmniroOrchestratorLayer open={explanationOpen} projection={explanation} onToggle={onToggleExplanation}/>
 </section>
}
