import{useEffect,useState}from"react";import type{ProjectContract,TaskContract,TaskProblemContract}from"@odls/contracts";
import{api,apiErrorMessage,type Session}from"./api.js";
import{OmniroDataFlowLegend,type DataFlowProjection}from"./omniro-data-flow-renderer.js";
import type{DirectorContextPage}from"./omniro-director-workspace.js";
import type{DirectorSources,DirectorTarget}from"./omniro-director-workspace-model.js";
import type{OmniroRuntimeSnapshot}from"./omniro-module-contract.js";
import{buildSiteManagerProjection}from"./omniro-site-manager-workspace-model.js";
import{roleWorkspaceRegistry}from"./omniro-role-workspace-registry.js";

type Props={session:Session;projects:ProjectContract[];project:ProjectContract;runtimes:ReadonlyMap<string,OmniroRuntimeSnapshot>;sources:DirectorSources;flows:readonly DataFlowProjection[];onBack:()=>void;onRole:(id:string)=>void;onProject:(id:string)=>void;onModule:(id:string,projectId?:string)=>void;onWorkspace:(id:string,projectId?:string)=>void;onContext:(page:DirectorContextPage,id?:string)=>void};
const truth=(value:string)=><span className={`oe-truth truth-${value.toLowerCase()}`}>{value}</span>;

export function OmniroSiteManagerWorkspace({session,projects,project,runtimes,sources,flows,onBack,onRole,onProject,onModule,onWorkspace,onContext}:Props){
 const projection=buildSiteManagerProjection(session,projects,runtimes,sources,project.id),resolved=roleWorkspaceRegistry.resolve("site-manager",session),can=(permission:string)=>session.permissions.includes(permission);
 const [reviewed,setReviewed]=useState<Record<string,TaskContract>>({}),[comments,setComments]=useState<Record<string,string>>({}),[problems,setProblems]=useState<TaskProblemContract[]>([]),[reviewError,setReviewError]=useState("");
 useEffect(()=>{if(can("task_problems.read"))void api.taskProblems().catch(()=>[]).then(items=>setProblems(items.filter(item=>item.projectId===project.id)))},[project.id]);
 const reviewQueue=sources.tasks.map(task=>reviewed[task.id]??task).filter(task=>task.projectId===project.id&&task.status==="submitted_for_review");
 const review=async(task:TaskContract,action:"accept"|"return")=>{try{const updated=await api.taskReview(task.id,action,task.version,comments[task.id]);setReviewed(current=>({...current,[task.id]:updated}));setReviewError("")}catch(problem){setReviewError(apiErrorMessage(problem))}};
 const open=(target:DirectorTarget)=>{if(target.kind==="workspace"&&target.moduleId)return onWorkspace(target.moduleId,target.projectId);if(target.kind==="module"&&target.moduleId)return onModule(target.moduleId,target.projectId);if(target.kind==="task")return onContext("tasks",target.entityId);if(target.kind==="document")return onContext("documents",target.entityId);return onContext("project-workspace",target.projectId)};
 return <main className="oe-role oe-director-v1 oe-site-manager-v1" aria-labelledby="oe-role-title">
  <aside className="oe-role-rail"><small>LAYER 3 · FIELD OPERATIONS</small><button onClick={onBack}>← Back to Product World</button><h2>Role workspaces</h2>{roleWorkspaceRegistry.definitions.map(definition=>{const state=roleWorkspaceRegistry.resolve(definition.roleId,session);return <button key={definition.roleId} disabled={state.truth==="UNAVAILABLE"} className={definition.roleId==="site-manager"?"is-current":""} onClick={()=>state.truth!=="UNAVAILABLE"&&onRole(definition.roleId)}>{definition.label}<small>{state.truth}</small></button>})}<label>Project context<select aria-label="Project context" value={project.id} onChange={event=>onProject(event.target.value)}>{projects.map(item=><option key={item.id} value={item.id}>{item.projectNumber} · {item.name}</option>)}</select></label><section className="oe-temporary-access"><strong>Authenticated authority</strong>{truth("REAL")}<p>Role ≠ actor. Every action remains attributed to {session.user.displayName} ({session.user.id}).</p></section></aside>
  <section className="oe-director oe-site-manager" aria-label="Site Manager field workspace"><header><div><small>SELECTED PROJECT · FIELD CONTEXT</small><h1 id="oe-role-title">Site Manager / Foreman Workspace</h1><p>{project.projectNumber} · {project.name} · {project.status} · version {project.version}</p></div>{truth(resolved.truth)}</header><OmniroDataFlowLegend flows={flows.filter(flow=>["02","03","04","05","07","08"].includes(flow.id))} compact/>
   <section className="oe-site-today" aria-label="Today field plan"><header><div><small>{projection.today}</small><h2>TODAY</h2></div><strong>{projection.taskGroups.TODAY.length} due today</strong></header><div className="oe-site-groups">{(["TODAY","OVERDUE","BLOCKED","DONE"]as const).map(group=><section key={group} data-group={group.toLowerCase()}><h3>{group}<b>{projection.taskGroups[group].length}</b></h3>{projection.taskGroups[group].map(item=><button key={item.task.id} onClick={()=>onContext("tasks",item.task.id)}><span><strong>{item.task.title}</strong><small>{item.location} · {item.responsibility}</small></span><b>{item.task.dueDate??"No deadline"}</b><em>{item.requiredAction}</em><i>{item.provenance.join(" · ")}</i></button>)}{!projection.taskGroups[group].length&&<p>No grounded items.</p>}</section>)}</div></section>
   <section className="oe-director-grid oe-site-grid">
    <article className="oe-priority-actions"><header><h2>Worker review</h2>{truth(can("tasks.review")?"REAL":"UNAVAILABLE")}</header>{reviewError&&<p role="alert">{reviewError}</p>}{reviewQueue.map(task=><section key={task.id}><strong>{task.title}</strong><small>{task.assignees.map(item=>item.displayName).join(", ")} · task:{task.id}:v{task.version}</small><label>Foreman comment<textarea value={comments[task.id]??""} onChange={event=>setComments(current=>({...current,[task.id]:event.target.value}))}/></label><div><button disabled={!can("tasks.review")} onClick={()=>void review(task,"accept")}>Accept work</button><button disabled={!can("tasks.review")||!(comments[task.id]?.trim())} onClick={()=>void review(task,"return")}>Return with comment</button></div></section>)}{!reviewQueue.length&&<p>No submitted worker tasks await review.</p>}</article>
    <article className="oe-priority-actions"><header><h2>Worker problems</h2>{truth(can("task_problems.read")?"REAL":"UNAVAILABLE")}</header>{problems.map(problem=><button key={problem.id} onClick={()=>onContext("tasks",problem.taskId)}><strong>{problem.category.replaceAll("_"," ")}</strong><small>{problem.description}</small><b>{problem.status}</b><i>task-problem:{problem.id}:v{problem.version}</i></button>)}{!problems.length&&<p>No visible field problems for this project.</p>}</article>
    <article className="oe-priority-actions oe-site-attention"><header><h2>Site attention</h2><small>same entity · version · provenance</small></header>{projection.attention.length?projection.attention.map(item=><button key={item.id} onClick={()=>open(item.target)} data-urgency={item.urgency}><span><strong>{item.title}</strong><small>{item.why}</small><em>{item.responsibility}</em></span><b>{item.status.replaceAll("_"," ")}</b><i>{item.provenance.join(" · ")}</i>{item.escalation&&<mark>ESCALATE → {item.escalation}</mark>}</button>):<p>No loaded site source declares an attention state.</p>}</article>
    <article className="oe-site-work"><header><h2>Work Scope</h2>{truth(projection.scope?"REAL":"UNAVAILABLE")}</header>{projection.work.slice(0,10).map(row=><button key={row.item.id} onClick={()=>onWorkspace("work-scope",project.id)}><span><strong>{row.item.description}</strong><small>{row.item.targetReference||"Location not available"} · {row.item.status}</small></span><b>{row.quantity===undefined?"Quantity not mapped":`${row.quantity} ${row.unit}`}</b><em>{row.relatedTask?`Task: ${row.relatedTask.title}`:"Related task not available"}</em><i>{row.provenance.join(" · ")}</i></button>)}{!projection.work.length&&<p>No Work Scope items are loaded for this project.</p>}</article>
    <article className="oe-site-documents"><header><h2>Documents / drawings</h2>{truth(sources.sourceState.documents.truth)}</header>{projection.documents.slice(0,8).map(document=><button key={document.id} onClick={()=>onContext("documents",document.id)}><span><strong>{document.title}</strong><small>{document.currentVersion.originalFilename} · OCR {document.ocrStatus}</small></span><b>v{document.currentVersionNo}</b><i>checksum:{document.currentVersion.checksum}</i></button>)}{!projection.documents.length&&<p>No explicitly project-linked documents are loaded.</p>}<footer>Approval for construction is UNAVAILABLE unless an existing authority proves it. Drawing AI is not implemented.</footer></article>
    <article className="oe-site-materials"><header><h2>Required materials</h2>{truth(projection.materials?"REAL":"UNAVAILABLE")}</header>{projection.materials?.lines.slice(0,8).map(line=><button key={line.id} onClick={()=>onWorkspace("material-consumption",project.id)}><span><strong>{line.requirementCode}</strong><small>{line.selectionState} · {line.materialId??"Material not selected"}</small></span><b>{line.totalQuantity} {line.unitCode}</b><em>Net {line.netQuantity} · waste {line.wasteQuantity} · reserve {line.reserveQuantity}</em><i>material-line:{line.id}:v{line.version}</i></button>)}{!projection.materials&&<p>No Material Consumption authority is loaded.</p>}<footer>Material Consumption remains quantity authority. Site Manager does not procure.</footer></article>
    <article className="oe-site-people"><header><h2>People / crews</h2>{truth(sources.sourceState.users.truth)}</header>{projection.people.map(person=><section key={person.id}><strong>{person.displayName}</strong>{truth(person.truth)}<small>{person.responsibilities.join(" · ")}</small></section>)}<p><b>{projection.unassigned}</b> active project tasks are UNASSIGNED.</p><footer>Worker Workspace is REAL for actors with assignment-scoped task authority.</footer></article>
    <article className="oe-site-evidence"><header><h2>Scanner / site evidence</h2>{truth(projection.scanner?.truth??"UNAVAILABLE")}</header>{projection.scanner?<><p>{projection.scanner.status} · {projection.scanner.reason}</p><i>{projection.scanner.provenance.join(" · ")||"No approved evidence reference loaded"}</i><button disabled={!can("room_scans.read")} onClick={()=>open(projection.scanner!.target)}>Open existing Scanner</button></>:<p>No Scanner authority is loaded for this project.</p>}<footer>Phone photos, LiDAR extensions, external scanners and drawing comparison are not added by this workspace.</footer></article>
    <article className="oe-quick-access"><header><h2>Field quick access</h2><small>existing permissions and routes</small></header><div><button disabled={!can("tasks.read")} onClick={()=>onContext("tasks")}>Tasks</button><button disabled={!can("room_scans.read")} onClick={()=>onWorkspace("room-scanner",project.id)}>Scanner</button><button disabled={!can("documents.read")} onClick={()=>onContext("documents")}>Documents / drawings</button><button disabled={!can("work_scopes.read")} onClick={()=>onWorkspace("work-scope",project.id)}>Work Scope</button><button disabled={!can("engineering_norms.read")} onClick={()=>onWorkspace("engineering-norms",project.id)}>Engineering</button><button disabled={!can("material_consumption.read")} onClick={()=>onWorkspace("material-consumption",project.id)}>Materials</button><button disabled={!can("users.read")} onClick={()=>onContext("project-workspace",project.id)}>People</button></div></article>
   </section>
  </section>
  <aside className="oe-intelligence oe-director-intelligence oe-site-intelligence"><small>SITE INTELLIGENCE RAIL</small><h2>Grounded field briefing</h2><article><header><strong>Orchestrator</strong>{truth("DERIVED")}</header><p>TODAY — {projection.briefing.total} items require attention: {projection.briefing.overdue} overdue, {projection.briefing.blocked} blocked, {projection.briefing.documentFailures} document processing failures.</p>{projection.briefing.items.map(item=><button key={item.id} onClick={()=>open(item.target)}><b>{item.title}</b><small>{item.why}</small><i>{item.provenance.join(" · ")}</i></button>)}</article><article><header><strong>Site Assistant</strong>{truth("PARTIAL")}</header><p>Grouping and explanation use loaded tasks and authority states. No site event or execution is invented.</p></article><article><header><strong>Engineering Assistant</strong>{truth(can("engineering_norms.read")?"PARTIAL":"UNAVAILABLE")}</header><p>Existing Engineering authority can be opened. Drawing intelligence remains unavailable.</p></article><article><header><strong>Weather intelligence</strong>{truth(projection.weather.truth)}</header><p>{projection.weather.reason}</p></article><section><h3>Communication truth</h3><p><b>OMNIRO Internal</b>{truth(can("notifications.read")?"REAL":"UNAVAILABLE")}<small>Recipient-scoped notifications only.</small></p>{["Email","WhatsApp Business","Telegram","Voice Bridge"].map(label=><p key={label}><b>{label}</b>{truth("UNAVAILABLE")}<small>No provider is connected.</small></p>)}</section></aside>
 </main>;
}
