import type{DocumentContract,ExpenseContract,InvoiceContract,PaymentContract,ProjectContract,ProjectFinancialSummary,TaskContract}from"@odls/contracts";
import type{Session}from"./api.js";
import{buildingModuleRegistry}from"./omniro-building-modules.js";
import type{DirectorSources,DirectorTarget}from"./omniro-director-workspace-model.js";
import type{OmniroRuntimeSnapshot,OmniroTruth}from"./omniro-module-contract.js";

export type AccountantInboxKind="invoice"|"payment"|"expense"|"document"|"notification"|"approval";
export type AccountantInboxItem={id:string;kind:AccountantInboxKind;title:string;counterparty:string;responsibility:string;projectId?:string;projectName?:string;date:string;amount?:string;currency?:string;status:string;reason:string;urgency:"critical"|"high"|"normal";target:DirectorTarget;provenance:readonly string[]};
export type AccountantDeadline={id:string;label:string;date:string;status:string;target:DirectorTarget;provenance:string};
export type AccountantDocumentMatch={document:DocumentContract;linkedKind:string;linkedId:string;projectId?:string;truth:"REAL"};
export type AccountantMetric={id:string;label:string;value:string;truth:OmniroTruth;reason:string};
export type AccountantProjection={metrics:AccountantMetric[];inbox:AccountantInboxItem[];deadlines:AccountantDeadline[];documentMatches:AccountantDocumentMatch[];unresolvedDocuments:DocumentContract[];currentFinancial?:ProjectFinancialSummary;briefing:AccountantInboxItem[];sourceCounts:{invoices:number;payments:number;expenses:number;documents:number;processedInvoices:number;processedExpenses:number;allocatedPayments:number};ksef:{truth:"UNAVAILABLE";reason:string};bank:{truth:"UNAVAILABLE";reason:string}};

const projectName=(projects:readonly ProjectContract[],id?:string)=>projects.find(project=>project.id===id)?.name;
const dateValue=(value:string|Date|null)=>value instanceof Date?value.toISOString().slice(0,10):value??"No date";
const financeTarget=(entityId:string):DirectorTarget=>({kind:"finance",entityId});
const invoiceAction=(invoice:InvoiceContract,today:string)=>invoice.status==="draft"||(["issued","partially_paid"].includes(invoice.status)&&invoice.dueDate!==null&&dateValue(invoice.dueDate)<today);
const invoiceReason=(invoice:InvoiceContract,today:string)=>invoice.status==="draft"?"Draft invoice requires review before the existing issue action.":invoice.dueDate!==null&&dateValue(invoice.dueDate)<today?`Outstanding invoice passed its due date ${dateValue(invoice.dueDate)}.`:`Invoice status is ${invoice.status}.`;
const accountingDocument=(document:DocumentContract)=>["invoice","receipt"].includes(document.category)||["invoice","receipt"].includes(document.documentType)||document.links.some(link=>["invoice","payment","expense"].includes(link.entityType));

export function buildAccountantProjection(session:Session,projects:readonly ProjectContract[],runtimes:ReadonlyMap<string,OmniroRuntimeSnapshot>,sources:DirectorSources,currentProjectId=projects[0]?.id,today=new Date().toISOString().slice(0,10)):AccountantProjection{
 const inbox:AccountantInboxItem[]=[];
 for(const invoice of sources.invoices)if(invoiceAction(invoice,today))inbox.push({id:`invoice:${invoice.id}`,kind:"invoice",title:`Invoice ${invoice.invoiceNumber}`,counterparty:`Client ${invoice.clientId}`,responsibility:"Finance authority · existing invoice permissions",projectId:invoice.projectId??undefined,projectName:projectName(projects,invoice.projectId??undefined),date:dateValue(invoice.dueDate??invoice.issueDate),amount:invoice.outstandingAmount,currency:invoice.currencyCode,status:invoice.status,reason:invoiceReason(invoice,today),urgency:invoice.status==="draft"?"normal":"critical",target:financeTarget(invoice.id),provenance:[`invoice:${invoice.id}:v${invoice.version}`,invoice.projectId?`project:${invoice.projectId}`:`client:${invoice.clientId}`]});
 for(const payment of sources.payments)if(payment.status==="received"&&Number(payment.unallocatedAmount)>0)inbox.push({id:`payment:${payment.id}`,kind:"payment",title:`Payment ${payment.reference}`,counterparty:`Client ${payment.clientId}`,responsibility:"Finance authority · existing payment permissions",date:dateValue(payment.paymentDate),amount:payment.unallocatedAmount,currency:payment.currencyCode,status:"unallocated",reason:"Received payment has an authoritative unallocated balance.",urgency:"high",target:financeTarget(payment.id),provenance:[`payment:${payment.id}:v${payment.version}`,`client:${payment.clientId}`]});
 for(const expense of sources.expenses)if(expense.status==="draft")inbox.push({id:`expense:${expense.id}`,kind:"expense",title:`Expense · ${expense.supplier}`,counterparty:expense.supplier,responsibility:"Finance authority · existing expense permissions",projectId:expense.projectId??undefined,projectName:projectName(projects,expense.projectId??undefined),date:dateValue(expense.expenseDate),amount:expense.grossAmount,currency:expense.currencyCode,status:expense.status,reason:"Draft expense requires review through the existing Finance authority.",urgency:"normal",target:financeTarget(expense.id),provenance:[`expense:${expense.id}:v${expense.version}`,expense.projectId?`project:${expense.projectId}`:`supplier:${expense.supplier}`]});
 for(const document of sources.documents)if(accountingDocument(document)&&(document.ocrStatus==="failed"||document.aiProcessingStatus==="failed"))inbox.push({id:`document:${document.id}`,kind:"document",title:document.title,counterparty:"Not available from the document contract",responsibility:"Documents / OCR authority",date:dateValue(document.updatedAt),status:"processing_failed",reason:`Accounting document processing requires review: OCR ${document.ocrStatus}, analysis ${document.aiProcessingStatus}.`,urgency:"high",target:{kind:"document",entityId:document.id},provenance:[`document:${document.id}:v${document.version}`,`file:${document.currentVersion.id}:v${document.currentVersionNo}`]});
 for(const notification of sources.notifications)if(notification.status==="unread"&&["invoice","payment","expense"].includes(notification.entityType))inbox.push({id:`notification:${notification.id}`,kind:"notification",title:notification.title,counterparty:"Not available from the notification contract",responsibility:`Recipient ${notification.recipientUserId}`,date:dateValue(notification.createdAt),status:notification.eventType,reason:notification.body,urgency:notification.severity==="critical"?"critical":notification.severity==="warning"?"high":"normal",target:financeTarget(notification.entityId),provenance:[`notification:${notification.id}:v${notification.version}`,`${notification.entityType}:${notification.entityId}`,`event:${notification.sourceEventId}`]});
 for(const[projectId,runtime]of runtimes)for(const state of runtime.modules.values())if(["APPROVAL_REQUIRED","CONFLICT","BLOCKED"].includes(state.lifecycle)){const definition=buildingModuleRegistry.get(state.moduleId),approval=definition?.approval?.detect(state,session);if(approval)inbox.push({id:`module:${projectId}:${state.moduleId}:${state.record?.entityId??state.status}`,kind:"approval",title:`${definition?.label??state.moduleId} · ${projectName(projects,projectId)??projectId}`,counterparty:"Existing domain authority",responsibility:approval.permitted?`Authenticated actor holds ${approval.permission}`:`Escalation requires ${approval.permission}`,projectId,projectName:projectName(projects,projectId),date:runtime.loadedAt.slice(0,10),status:state.lifecycle,reason:state.reason,urgency:state.lifecycle==="BLOCKED"||state.lifecycle==="CONFLICT"?"critical":"high",target:{kind:approval.permitted?"workspace":"module",moduleId:approval.permitted?approval.openWorkspaceId:state.moduleId,projectId,entityId:state.record?.entityId},provenance:state.evidence.map(evidence=>`${evidence.entityType}:${evidence.entityId}${evidence.version?`:v${evidence.version}`:""}`)})}
 inbox.sort((left,right)=>({critical:0,high:1,normal:2}[left.urgency]-{critical:0,high:1,normal:2}[right.urgency])||left.date.localeCompare(right.date)||left.id.localeCompare(right.id));
 const deadlines:AccountantDeadline[]=[...sources.invoices.filter(invoice=>["issued","partially_paid"].includes(invoice.status)&&invoice.dueDate!==null).map(invoice=>({id:`invoice:${invoice.id}`,label:`Invoice ${invoice.invoiceNumber}`,date:dateValue(invoice.dueDate),status:dateValue(invoice.dueDate)<today?"overdue":"due",target:financeTarget(invoice.id),provenance:`invoice:${invoice.id}:v${invoice.version}`})),...sources.tasks.filter(task=>task.dueDate!==null&&!['completed','cancelled','archived'].includes(task.status)).map((task:TaskContract)=>({id:`task:${task.id}`,label:task.title,date:dateValue(task.dueDate),status:task.isOverdue?"overdue":task.status,target:{kind:"task"as const,entityId:task.id,projectId:task.projectId},provenance:`task:${task.id}:v${task.version}`}))].sort((left,right)=>left.date.localeCompare(right.date));
 const matches:AccountantDocumentMatch[]=sources.documents.flatMap(document=>document.links.filter(link=>["invoice","payment","expense"].includes(link.entityType)).map(link=>({document,linkedKind:link.entityType,linkedId:link.entityId,projectId:link.entityType==="invoice"?sources.invoices.find(invoice=>invoice.id===link.entityId)?.projectId??undefined:link.entityType==="expense"?sources.expenses.find(expense=>expense.id===link.entityId)?.projectId??undefined:undefined,truth:"REAL"as const})));
 const unresolvedDocuments=sources.documents.filter(document=>accountingDocument(document)&&!document.links.some(link=>["invoice","payment","expense"].includes(link.entityType))),currentFinancial=sources.financialSummaries.find(summary=>summary.projectId===currentProjectId);
 const draftInvoices=sources.invoices.filter(invoice=>invoice.status==="draft").length,overdueInvoices=sources.invoices.filter(invoice=>["issued","partially_paid"].includes(invoice.status)&&invoice.dueDate!==null&&dateValue(invoice.dueDate)<today).length,draftExpenses=sources.expenses.filter(expense=>expense.status==="draft").length,unallocatedPayments=sources.payments.filter(payment=>payment.status==="received"&&Number(payment.unallocatedAmount)>0).length,failedDocuments=sources.documents.filter(document=>accountingDocument(document)&&(document.ocrStatus==="failed"||document.aiProcessingStatus==="failed")).length;
 const metrics:AccountantMetric[]=[{id:"accounting-inbox",label:"Accounting inbox",value:String(inbox.length),truth:sources.sourceState.finance.truth,reason:"Actionable records from loaded Finance, Documents and registered approval authorities."},{id:"draft-invoices",label:"Draft invoices",value:String(draftInvoices),truth:sources.sourceState.finance.truth,reason:"Invoice lifecycle records."},{id:"overdue-invoices",label:"Overdue invoices",value:String(overdueInvoices),truth:sources.sourceState.finance.truth,reason:"Issued or partially paid invoices whose due date has passed."},{id:"draft-expenses",label:"Draft expenses",value:String(draftExpenses),truth:sources.sourceState.finance.truth,reason:"Expense lifecycle records."},{id:"unallocated-payments",label:"Unallocated payments",value:String(unallocatedPayments),truth:sources.sourceState.finance.truth,reason:"Received payments with non-zero unallocated amount."},{id:"document-review",label:"Document review",value:String(failedDocuments),truth:sources.sourceState.documents.truth,reason:"Accounting documents with failed OCR or analysis."}];
 return{metrics,inbox,deadlines,documentMatches:matches,unresolvedDocuments,currentFinancial,briefing:inbox.slice(0,6),sourceCounts:{invoices:sources.invoices.length,payments:sources.payments.length,expenses:sources.expenses.length,documents:sources.documents.filter(accountingDocument).length,processedInvoices:sources.invoices.filter(invoice=>["issued","partially_paid","paid"].includes(invoice.status)).length,processedExpenses:sources.expenses.filter(expense=>expense.status==="approved").length,allocatedPayments:sources.payments.filter(payment=>payment.status==="received"&&Number(payment.unallocatedAmount)===0).length},ksef:{truth:"UNAVAILABLE",reason:"No KSeF provider, credential or submission authority is connected."},bank:{truth:"UNAVAILABLE",reason:"Payments are real internal Finance records; no bank account or bank-feed integration is connected."}};
}
