import type{OmniroModuleDefinition,OmniroModuleRuntimeAdapter,OmniroVisualIdentity}from"./omniro-module-contract.js";
import{OmniroModuleRegistry}from"./omniro-module-registry.js";
import{assignmentAdapter,designAdapter,explanationAdapter,projectAdapter,scannerAdapter,scannerApproval,unavailableAdapter}from"./omniro-building-adapters.js";

const port=(id:string,payloadType:string,label:string)=>({id,payloadType,label});
const visual=(glyph:string,geometry:OmniroVisualIdentity["geometry"],accent:OmniroVisualIdentity["accent"]):OmniroVisualIdentity=>({glyph,geometry,accent});
const module=(id:string,label:string,adapter:OmniroModuleRuntimeAdapter,options:Partial<OmniroModuleDefinition>={}):OmniroModuleDefinition=>({id,label,entityType:id,kind:"authority",defaultTruth:"UNAVAILABLE",visual:visual("○","layers","silver"),permissions:{read:[]},inputs:[port("input","registered-payload","Registered input")],outputs:[port("output","registered-payload","Registered output")],dependencies:[],runtime:adapter,explain:explanationAdapter,processingVisual:"dormant",mobile:{priority:50,compactLabel:label},accessibility:{label,description:`${label} operational module.`,unavailableDescription:`${label} is not connected in Stage 2A.`},...options});
export const buildingModuleDefinitions:readonly OmniroModuleDefinition[]=[
 module("project","Project",projectAdapter,{kind:"nucleus",defaultTruth:"REAL",visual:visual("◎","core","cyan"),outputs:[port("context","project-context","Project context")],mobile:{priority:0,compactLabel:"Project"}}),
 module("room-scanner","Room Scanner",scannerAdapter,{defaultTruth:"REAL",visual:visual("⌗","scanner","cyan"),permissions:{read:["room_scans.read"],enter:["room_scans.read"],approve:["room_scans.approve"]},inputs:[port("project","project-context","Project")],outputs:[port("snapshot","approved-scan-snapshot","Approved scan snapshot")],dependencies:["project"],workspace:{id:"room-scanner",routeSegment:"room-scanner"},approval:scannerApproval,processingVisual:"scanner-evidence-sweep",mobile:{priority:1,compactLabel:"Scanner"}}),
 module("technical-assignment","Technical Assignment",assignmentAdapter,{defaultTruth:"REAL",visual:visual("≡","layers","green"),permissions:{read:["technical_assignments.read"],enter:["technical_assignments.read"]},inputs:[port("project","project-context","Project"),port("scan","approved-scan-snapshot","Scanner evidence")],outputs:[port("assignment","technical-assignment","Approved intent")],dependencies:["project","room-scanner"],workspace:{id:"technical-assignment",routeSegment:"technical-assignment"},processingVisual:"intent-review",mobile:{priority:2,compactLabel:"Assignment"}}),
 module("design-project","Design Project",designAdapter,{defaultTruth:"REAL",visual:visual("◇","decisions","green"),permissions:{read:["design_projects.read"],enter:["design_projects.read"]},inputs:[port("project","project-context","Project"),port("assignment","technical-assignment","Technical intent")],outputs:[port("design","design-project","Design decisions")],dependencies:["project","technical-assignment"],workspace:{id:"design-project",routeSegment:"design-project"},processingVisual:"design-formation",mobile:{priority:3,compactLabel:"Design"}}),
 ...[["work-scope","Work Scope","scope"],["technology","Technology","technology"],["engineering-norms","Engineering Norms","norms"],["material-consumption","Material Consumption","consumption"],["regional-pricing","Regional Pricing","pricing"],["commercial-estimate","Commercial Estimate","estimate"]].map(([id,label,geometry],index)=>module(id,label,unavailableAdapter(id,label),{visual:visual(index===5?"∑":"○",geometry as OmniroVisualIdentity["geometry"],index===5?"amber":"silver"),dependencies:index?[(["work-scope","technology","engineering-norms","material-consumption","regional-pricing"])[index-1]]:["design-project"],mobile:{priority:10+index,compactLabel:label}})),
 module("documents","Documents",unavailableAdapter("documents","Documents context"),{kind:"context",visual:visual("▱","context","silver"),accessibility:{label:"Documents",description:"Open existing project documents context.",unavailableDescription:"No project document relationship is loaded."}}),
 module("tasks","Tasks",unavailableAdapter("tasks","Tasks context"),{kind:"context",visual:visual("▤","context","silver"),accessibility:{label:"Tasks",description:"Open existing project tasks context.",unavailableDescription:"No project task relationship is loaded."}})
];
export const buildingModuleRegistry=new OmniroModuleRegistry(buildingModuleDefinitions);
