export type StageFlowState="idle"|"processing"|"waiting"|"human_approval_required"|"confirmed"|"conflict"|"complete";
export type StageFlow={id:string;origin:string;destination:string;semanticType:string;state:StageFlowState;explanation:string;capabilitySource:string;demonstration:boolean};
export const stageFlows:StageFlow[]=[
 {id:"system-idle",origin:"OMNIRO",destination:"scanner",semanticType:"No data in transit",state:"idle",explanation:"The system is ready and no public demonstration payload is moving.",capabilitySource:"Public scene state",demonstration:true},
 {id:"photo-scanner",origin:"photo",destination:"scanner",semanticType:"Input photographs",state:"processing",explanation:"Demonstration photographs enter the implemented Room Scanner capture workflow.",capabilitySource:"Room Scanner foundation",demonstration:true},
 {id:"scanner-passport",origin:"scanner",destination:"passport",semanticType:"Verified room geometry",state:"human_approval_required",explanation:"Reviewed geometry stops at a human approval gate before an immutable room passport can exist.",capabilitySource:"Approved room scan snapshot",demonstration:true},
 {id:"passport-norms",origin:"passport",destination:"norms",semanticType:"Normative requirement",state:"confirmed",explanation:"Approved quantities can be mapped through governed work scope and engineering norms.",capabilitySource:"Scanner boundary and Norm Catalog",demonstration:true},
 {id:"norms-estimate",origin:"norms",destination:"estimate",semanticType:"Material demand",state:"processing",explanation:"Versioned norms produce material demand for the implemented Estimate workflow.",capabilitySource:"Material Consumption and Estimate Engine",demonstration:true},
 {id:"estimate-analytics",origin:"estimate",destination:"analytics",semanticType:"Estimate result",state:"complete",explanation:"Approved commercial outputs can be inspected through existing reports and analytics.",capabilitySource:"Estimate Engine and Analytics",demonstration:true},
 {id:"system-orchestrator",origin:"scanner",destination:"orchestrator",semanticType:"Governed transition",state:"waiting",explanation:"The public scene exposes the orchestration UI contract; grounded conversational explanation is available after authentication in Command Center.",capabilitySource:"OMNIRO Orchestrator foundation",demonstration:true},
 {id:"routing-conflict",origin:"passport",destination:"orchestrator",semanticType:"Conflicting evidence",state:"conflict",explanation:"A conflicting signal branches toward Orchestrator and waits for a human decision; no resolution is fabricated.",capabilitySource:"Orchestrator UI contract",demonstration:true},
];
export const flowStateLabel:Record<StageFlowState,string>={idle:"Idle",processing:"Processing",waiting:"Waiting",human_approval_required:"Human approval required",confirmed:"Confirmed",conflict:"Conflict",complete:"Complete"};
