import{useEffect,useRef,useState}from"react";
export type VoiceUiState="idle"|"requesting_permission"|"listening"|"translating"|"speaking"|"provider_unavailable"|"permission_denied"|"connection_lost";
export type VoiceApi={start(input:{mode:"conversation_translation"|"voice_command";participants:{userId:string;speakingLanguage?:string;listeningLanguage:string}[]}):Promise<{id:string;providerTruth:string}>;chunk(id:string,input:{audioBase64:string;contentType:string;speakingLanguage?:string;listeningLanguage:string;projectId?:string}):Promise<{audioBase64?:string;contentType?:string;recognizedText:string;translatedText?:string}>;end(id:string):Promise<void>};
export function createVoiceApi(fetcher:typeof fetch=fetch):VoiceApi{const json=async(response:Response)=>{if(!response.ok)throw new Error(response.status===403?"PERMISSION_DENIED":"VOICE_REQUEST_FAILED");return(await response.json()).data};return{start:x=>fetcher("/api/v1/voice/sessions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(x)}).then(json),chunk:(id,x)=>fetcher(`/api/v1/voice/sessions/${id}/chunks`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(x)}).then(json),end:id=>fetcher(`/api/v1/voice/sessions/${id}/end`,{method:"POST"}).then(async r=>{await json(r)})}}
const base64=async(blob:Blob)=>{const bytes=new Uint8Array(await blob.arrayBuffer());let value="";for(const byte of bytes)value+=String.fromCharCode(byte);return btoa(value)};
export function VoiceBridgePanel({api=createVoiceApi(),userId,projectId}:{api?:VoiceApi;userId:string;projectId?:string}){const[mode,setMode]=useState<"conversation_translation"|"voice_command">("conversation_translation"),[speaking,setSpeaking]=useState("pl-PL"),[listening,setListening]=useState("ru-RU"),[state,setState]=useState<VoiceUiState>("idle"),[muted,setMuted]=useState(false),[text,setText]=useState("");const recorder=useRef<MediaRecorder|undefined>(undefined),session=useRef<string|undefined>(undefined),stream=useRef<MediaStream|undefined>(undefined);
 useEffect(()=>()=>{recorder.current?.stop();stream.current?.getTracks().forEach(x=>x.stop())},[]);
 const start=async()=>{if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==="undefined"){setState("provider_unavailable");return}try{setState("requesting_permission");stream.current=await navigator.mediaDevices.getUserMedia({audio:true});const started=await api.start({mode,participants:[{userId,speakingLanguage:speaking,listeningLanguage:listening}]});if(started.providerTruth!=="REAL"){stream.current.getTracks().forEach(x=>x.stop());setState("provider_unavailable");return}session.current=started.id;const value=new MediaRecorder(stream.current);recorder.current=value;value.ondataavailable=async event=>{if(!event.data.size||muted||!session.current)return;try{setState(mode==="voice_command"?"listening":"translating");const result=await api.chunk(session.current,{audioBase64:await base64(event.data),contentType:event.data.type||"audio/webm",speakingLanguage:speaking,listeningLanguage:listening,projectId});setText(result.translatedText??result.recognizedText);if(result.audioBase64&&result.contentType){setState("speaking");const audio=new Audio(`data:${result.contentType};base64,${result.audioBase64}`);audio.onended=()=>setState("listening");await audio.play()}else setState("listening")}catch{setState("connection_lost")}};value.start(1500);setState("listening")}catch(error){setState(error instanceof DOMException&&error.name==="NotAllowedError"?"permission_denied":"connection_lost")}};
 const stop=async()=>{recorder.current?.stop();stream.current?.getTracks().forEach(x=>x.stop());if(session.current)await api.end(session.current);session.current=undefined;setState("idle")};
 return <section aria-label="OMNIRO Voice Bridge"><h2>Voice Bridge</h2><p>Live audio is never recorded or stored.</p><label>Mode<select value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="conversation_translation">Conversation Translation</option><option value="voice_command">Voice Command</option></select></label><label>Speaking language<input value={speaking} onChange={e=>setSpeaking(e.target.value)}/></label><label>Listening language<input value={listening} onChange={e=>setListening(e.target.value)}/></label><output aria-live="polite">{state}</output>{text&&<p>{text}</p>}<button onClick={state==="idle"?start:stop}>{state==="idle"?"Start":"Stop"}</button><button type="button" aria-pressed={muted} onClick={()=>setMuted(x=>!x)}>Mute</button></section>}
