import{useEffect,useMemo,useRef,useState}from"react";
import{api,type DesignProjectDto,type RoomScanDto,type Session,type TechnicalAssignmentDto}from"./api.js";
import{EmptyState,ErrorState,LoadingState,StatusBadge,hasPermission,type WorkspaceTab}from"./construction-ui.js";
import{LocalOrchestratorInterpreter,type OrchestratorInterpretation}from"./omniro-interpreter.js";
import{composeOmniroContext,type OmniroProject,type OmniroStage}from"./omniro-model.js";
import{BrowserSpeechRecognitionAdapter,BrowserSpeechSynthesisAdapter,type SpeechRecognitionAdapter,type SpeechSynthesisAdapter}from"./omniro-speech.js";
import type{ProjectContract}from"@odls/contracts";
import{EarthRendererBoundary,LivingEarth,OmniroPresence,SemanticFlowLayer}from"./living-earth.js";
import{deriveCompanyBrief,deriveEarthState,derivePresentation,rendererMode,semanticFlows,transitionPresence,type OmniroPresenceState}from"./omniro-scene-model.js";
import{ConstructionAssistantPanel}from"./construction-assistant-panel.js";

type Navigate=(page:"omniro"|"overview"|"construction-projects"|"project-workspace",projectId?:string,tab?:WorkspaceTab)=>void;
type RenderMode="enhanced"|"balanced"|"reduced";
const workspaceStage:Partial<Record<OmniroStage,WorkspaceTab>>={"room-scan":"room-scan","technical-assignment":"technical-assignment","design-project":"design-project"};
const defaultMode=():RenderMode=>typeof matchMedia!=="undefined"&&matchMedia("(prefers-reduced-motion: reduce)").matches?"reduced":typeof navigator!=="undefined"&&((navigator.hardwareConcurrency??8)<=4||navigator.maxTouchPoints>0)?"balanced":"enhanced";

export function OmniroCommandCenter({session,navigate,recognition,synthesis,forceRendererFailure=false}:{session:Session;navigate:Navigate;recognition?:SpeechRecognitionAdapter;synthesis?:SpeechSynthesisAdapter;forceRendererFailure?:boolean}){
 const[data,setData]=useState<{projects:ProjectContract[];scans:RoomScanDto[];assignments:TechnicalAssignmentDto[];designs:DesignProjectDto[]}>(),[error,setError]=useState<unknown>(),[partial,setPartial]=useState<string[]>([]);
 const[selectedId,setSelectedId]=useState(()=>typeof location==="undefined"?"":new URLSearchParams(location.search).get("project")??""),[attentionOnly,setAttentionOnly]=useState(false),[focusedStage,setFocusedStage]=useState<OmniroStage>(),[mode,setMode]=useState<RenderMode>(defaultMode),[input,setInput]=useState(""),[transcript,setTranscript]=useState(""),[listening,setListening]=useState(false),[assistantError,setAssistantError]=useState(""),[response,setResponse]=useState<OrchestratorInterpretation>(),[announcement,setAnnouncement]=useState(""),[presence,setPresence]=useState<OmniroPresenceState>("dormant"),[rendererFailed,setRendererFailed]=useState(forceRendererFailure),[documentHidden,setDocumentHidden]=useState(false);
 const interpreter=useMemo(()=>new LocalOrchestratorInterpreter(),[]),recognizer=useMemo(()=>recognition??new BrowserSpeechRecognitionAdapter(),[recognition]),speaker=useMemo(()=>synthesis??new BrowserSpeechSynthesisAdapter(),[synthesis]),inputRef=useRef<HTMLInputElement>(null);
 const load=()=>{setError(undefined);setPartial([]);const fallback=<T,>(name:string,promise:Promise<T>,value:T)=>promise.catch(()=>{setPartial(x=>[...x,name]);return value});void Promise.all([api.projectsPage("page=1&pageSize=100&sortBy=name&sortOrder=asc"),fallback("Room Scanner",hasPermission(session,"room_scans.read")?api.roomScans():Promise.resolve({data:[],pagination:{page:1,pageSize:25,total:0,totalPages:0}}),{data:[],pagination:{page:1,pageSize:25,total:0,totalPages:0}}),fallback("Technical Assignment",hasPermission(session,"technical_assignments.read")?api.technicalAssignments():Promise.resolve([]),[] as TechnicalAssignmentDto[]),fallback("Design Project",hasPermission(session,"design_projects.read")?api.designProjects():Promise.resolve([]),[] as DesignProjectDto[])]).then(([p,s,t,d])=>setData({projects:p.data,scans:s.data,assignments:t,designs:d})).catch(setError);};
 useEffect(load,[]);useEffect(()=>()=>{recognizer.stop();speaker.cancel()},[recognizer,speaker]);useEffect(()=>{const changed=()=>setDocumentHidden(document.hidden);document.addEventListener("visibilitychange",changed);return()=>document.removeEventListener("visibilitychange",changed)},[]);
 const context=useMemo(()=>data?composeOmniroContext(data.projects,data.scans,data.assignments,data.designs):{projects:[],insights:[]},[data]),selected=context.projects.find(x=>x.id===selectedId);
 useEffect(()=>setPresence(x=>transitionPresence(x,partial.length?"unavailable":"data-ready")),[data,partial.length]);useEffect(()=>{const restore=()=>setSelectedId(new URLSearchParams(location.search).get("project")??"");addEventListener("popstate",restore);return()=>removeEventListener("popstate",restore)},[]);
 const updateProject=(id:string,push=true)=>{setSelectedId(id);if(typeof location==="undefined")return;const url=new URL(location.href);if(id)url.searchParams.set("project",id);else url.searchParams.delete("project");history[push?"pushState":"replaceState"]({omniro:true},"",`${url.pathname}${url.search}#omniro`)};
 const visible=context.projects.filter(x=>!attentionOnly||x.attentionReasons.length>0),insights=context.insights.filter(x=>(!selectedId||x.projectId===selectedId)&&(!attentionOnly||x.priority<=4)),flows=useMemo(()=>semanticFlows(selected?[selected]:visible,selectedId),[selected,visible,selectedId]),brief=useMemo(()=>deriveCompanyBrief(context),[context]),earthState=deriveEarthState(presence,selectedId,attentionOnly,partial.length>0,mode==="reduced",rendererFailed),effectiveRenderer=rendererMode(mode,rendererFailed,documentHidden);
 const execute=async(value=input)=>{const text=value.trim();if(!text)return;setAssistantError("");setPresence(x=>transitionPresence(x,"interpret"));const interpreted=await interpreter.interpret(text,context);setResponse(interpreted);if(interpreted.intent==="show_attention"){setAttentionOnly(true);updateProject("");setFocusedStage(undefined);setPresence(x=>transitionPresence(x,"show-attention"))}else if(interpreted.intent==="show_projects"||interpreted.intent==="company_view"){setAttentionOnly(false);updateProject("");setFocusedStage(undefined);setPresence(x=>transitionPresence(x,"present"))}else if(interpreted.intent==="open_project"&&interpreted.projectId){updateProject(interpreted.projectId);setAttentionOnly(false);setPresence(x=>transitionPresence(x,"focus-project"))}else if(interpreted.intent==="show_stage"&&interpreted.stage){setFocusedStage(interpreted.stage);setPresence(x=>transitionPresence(x,"present"))}else setPresence(x=>transitionPresence(x,"present"));const count=interpreted.intent==="show_attention"?context.projects.filter(x=>x.attentionReasons.length).length:interpreted.intent==="open_project"?1:context.projects.length;setAnnouncement(`${interpreted.explanation} ${count} project${count===1?"":"s"} displayed. No project data was modified.`);setInput("");setTranscript("");};
 const startVoice=()=>{setAssistantError("");setListening(true);setPresence(x=>transitionPresence(x,"listen"));recognizer.start(event=>{setTranscript(event.transcript);if(event.final){setInput(event.transcript);void execute(event.transcript)}},message=>{setAssistantError(message);setListening(false);setPresence(x=>transitionPresence(x,"fail"))},()=>setListening(false));};
 const stopVoice=()=>{recognizer.stop();setListening(false);setTranscript("");setPresence(x=>transitionPresence(x,"reset"));inputRef.current?.focus()};
 const openStage=(project:OmniroProject,stage:OmniroStage)=>{const tab=workspaceStage[stage];if(tab)navigate("project-workspace",project.id,tab)};
 if(error)return <section className="omniro"><ErrorState error={error} onRetry={load}/></section>;if(!data)return <section className="omniro"><LoadingState label="Composing authoritative business state"/></section>;
 return <section className={`omniro omniro-${mode} renderer-${effectiveRenderer} ${listening?"omniro-listening":""}`} aria-labelledby="omniro-title" data-presence-state={presence} data-earth-state={earthState}>
  <header className="omniro-header"><div><span className="eyebrow">Visual intelligence · authoritative navigation</span><h1 id="omniro-title">OMNIRO Command Center</h1><p>A living, explainable view of the tenant’s real construction workflow.</p></div><label>Rendering mode<select aria-label="Rendering mode" value={mode} onChange={e=>setMode(e.target.value as RenderMode)}><option value="enhanced">Enhanced</option><option value="balanced">Balanced</option><option value="reduced">Reduced</option></select></label></header>
  {partial.length>0&&<div className="omniro-warning" role="status"><strong>Partially unavailable</strong><span>{partial.join(", ")} could not be loaded. Available sources remain visible; missing state is not inferred.</span><button onClick={load}>Retry</button></div>}
  <section className="company-brief" aria-labelledby="brief-title"><span className="eyebrow">Current authoritative state</span><h2 id="brief-title">Company Brief</h2><p>{brief}</p></section>
  <div className="omniro-layout"><div className="omniro-scene" data-mode={selected?"project":"company"}><div className="omniro-scene-title"><span>{selected?"Project Universe":"Company Universe"}</span>{selected&&<button onClick={()=>{updateProject("");setFocusedStage(undefined);setPresence(x=>transitionPresence(x,"present"))}}>Return to company view</button>}</div><div className="universe-layer"><EarthRendererBoundary onFailure={()=>setRendererFailed(true)}>{forceRendererFailure?<BrokenRenderer/>:<LivingEarth state={earthState} flowCount={flows.length}/>}</EarthRendererBoundary><OmniroPresence state={presence}/>{selected?<ProjectFocus project={selected} focusedStage={focusedStage} openStage={openStage}/>:<CompanyGraph projects={visible} onSelect={id=>{updateProject(id);setPresence(x=>transitionPresence(x,"focus-project"))}}/>}</div><SemanticFlowLayer flows={flows}/><SemanticGraph projects={selected?[selected]:visible} onSelect={id=>updateProject(id)} openStage={openStage}/></div>
   <aside className="understanding" aria-labelledby="understanding-title"><span className="eyebrow">Explainable state</span><h2 id="understanding-title">What is happening?</h2><p>{attentionOnly?"Showing workflow records requiring attention.":"Prioritized with explicit lifecycle rules; no hidden score is used."}</p>{insights.length?<ol>{insights.slice(0,8).map(x=><li key={x.id}><StatusBadge status={x.status}/><strong>{x.statement}</strong><small>{x.explanation}</small><button onClick={()=>{updateProject(x.projectId);if(x.stage)setFocusedStage(x.stage)}}>Inspect source</button></li>)}</ol>:<EmptyState title="No workflow signals" detail="No project-linked authoritative records are visible."/ >}</aside>
  </div>
  {selected&&hasPermission(session,"construction_assistant.read")&&<ConstructionAssistantPanel session={session} projectId={selected.id}/>}
  <form className="omniro-command" onSubmit={e=>{e.preventDefault();void execute()}}><div><span className="eyebrow">Safe local orchestration</span><h2>Ask OMNIRO</h2></div><label className="sr-only" htmlFor="omniro-input">Text command</label><input ref={inputRef} id="omniro-input" value={input} onChange={e=>setInput(e.target.value)} placeholder="What requires attention?" autoComplete="off"/><button className="primary">Interpret command</button>{recognizer.supported?<button type="button" aria-pressed={listening} aria-label={listening?"Stop voice input":"Start voice input"} onClick={listening?stopVoice:startVoice}>{listening?"■ Stop listening":"● Voice"}</button>:<button type="button" disabled title="Browser speech recognition is unavailable">Voice unavailable</button>}{transcript&&<output aria-label="Transcript preview">{transcript}</output>}{assistantError&&<p role="alert">{assistantError}</p>}{response&&<OrchestratorResponse response={response} presentation={derivePresentation(response,context)} announcement={announcement} canSpeak={speaker.supported} onSpeak={()=>speaker.speak(announcement)}/>}<p className="sr-only" aria-live="polite">{announcement}</p></form>
 </section>;
}
function CompanyGraph({projects,onSelect}:{projects:OmniroProject[];onSelect:(id:string)=>void}){return <div className="company-graph" aria-hidden="true"><div className="omniro-core"><span>OMNIRO</span><small>Operational core</small></div>{projects.map((p,index)=><button key={p.id} className={`project-orb state-${p.visualState} orbit-${index%6}`} tabIndex={-1} onClick={()=>onSelect(p.id)}><span>{p.name}</span><small>{p.attentionReasons.length?`${p.attentionReasons.length} attention signal${p.attentionReasons.length===1?"":"s"}`:p.status}</small></button>)}</div>}
function ProjectFocus({project,focusedStage,openStage}:{project:OmniroProject;focusedStage?:OmniroStage;openStage:(p:OmniroProject,s:OmniroStage)=>void}){return <div className="project-focus-graph" aria-hidden="true"><div className="project-nucleus"><span>{project.name}</span><small>{project.number}</small></div>{project.stages.map((stage,index)=><button key={stage.id} className={`stage-orb stage-${index} state-${stage.visualState} ${focusedStage===stage.stage?"is-focused":""}`} tabIndex={-1} disabled={!stage.available} onClick={()=>openStage(project,stage.stage)}><span>{stage.label}</span><small>{stage.status.replaceAll("_"," ")}</small></button>)}</div>}
function SemanticGraph({projects,onSelect,openStage}:{projects:OmniroProject[];onSelect:(id:string)=>void;openStage:(p:OmniroProject,s:OmniroStage)=>void}){return <div className="semantic-graph" aria-label="Authoritative workflow graph"><h2 className="sr-only">Workflow entities</h2>{projects.map(project=><article key={project.id}><button className="semantic-project" onClick={()=>onSelect(project.id)} aria-label={`${project.name}, ${project.status}, ${project.attentionReasons.length} attention signals`}>{project.name} · {project.status}</button><ul>{project.stages.map(stage=><li key={stage.id} data-state={stage.visualState}><span><strong>{stage.label}</strong><small>{stage.explanation}</small></span><button disabled={!stage.available} onClick={()=>openStage(project,stage.stage)}>{stage.available?"Open workspace":"Unavailable"}</button></li>)}</ul></article>)}</div>}
function OrchestratorResponse({response,presentation,announcement,canSpeak,onSpeak}:{response:OrchestratorInterpretation;presentation:ReturnType<typeof derivePresentation>;announcement:string;canSpeak:boolean;onSpeak:()=>void}){return <section className="orchestrator-response" aria-label="OMNIRO response"><strong>Understood: {response.trace.normalizedInput||"empty command"}</strong><span>{response.explanation}</span><span>Visual transition: {presentation.visualTransition}.</span>{presentation.unsupportedCapability&&<span>Unavailable capability: {presentation.unsupportedCapability}. No operation was performed.</span>}<small>Source: loaded REST workflow contracts · Focused entities: {presentation.focusedEntities.map(x=>x.label).join(", ")||"none"} · No project data was modified. {presentation.verification}</small>{canSpeak&&<button type="button" onClick={onSpeak}>Read response aloud</button>}{announcement&&<span className="sr-only">{announcement}</span>}</section>}
function BrokenRenderer():never{throw new Error("Renderer unavailable")}
