import type{DocumentContract,ProjectContract,TaskContract}from"@odls/contracts";
import type{MaterialConsumptionDto,Session,UserSummary,WorkScopeDto,WorkScopeItemDto}from"./api.js";
import{buildingModuleRegistry}from"./omniro-building-modules.js";
import type{DirectorSources,DirectorTarget}from"./omniro-director-workspace-model.js";
import type{OmniroLifecycle,OmniroRuntimeSnapshot,OmniroTruth}from"./omniro-module-contract.js";

export type SiteTaskGroup="TODAY"|"OVERDUE"|"BLOCKED"|"DONE"|"UPCOMING";
export type SiteTask={task:TaskContract;group:SiteTaskGroup;location:string;responsibility:string;source:string;requiredAction:string;provenance:readonly string[]};
export type SiteAttention={id:string;title:string;why:string;status:string;urgency:"critical"|"high"|"normal";responsibility:string;target:DirectorTarget;provenance:readonly string[];escalation?:"PROJECT MANAGER"|"DIRECTOR"};
export type SiteWorkRow={item:WorkScopeItemDto;quantity?:number;unit?:string;relatedTask?:TaskContract;provenance:readonly string[]};
export type SitePerson={id:string;displayName:string;responsibilities:readonly string[];truth:"REAL"|"DERIVED"};
export type SiteManagerProjection={project:ProjectContract;projectManager?:UserSummary;today:string;taskGroups:Record<SiteTaskGroup,SiteTask[]>;tasks:SiteTask[];attention:SiteAttention[];briefing:{total:number;overdue:number;blocked:number;documentFailures:number;items:SiteAttention[]};scope?:WorkScopeDto;work:SiteWorkRow[];documents:DocumentContract[];materials?:MaterialConsumptionDto;people:SitePerson[];unassigned:number;scanner?:{truth:OmniroTruth;lifecycle:OmniroLifecycle;status:string;reason:string;target:DirectorTarget;provenance:readonly string[]};weather:{truth:"UNAVAILABLE";reason:string};drawingIntelligence:{truth:"UNAVAILABLE";reason:string}};

const terminal=new Set(["accepted","completed","cancelled","archived"]),attentionLifecycles=new Set<OmniroLifecycle>(["WAIT","APPROVAL_REQUIRED","CONFLICT","BLOCKED"]);
const evidence=(state:ReturnType<OmniroRuntimeSnapshot["modules"]["get"]>)=>state?.evidence.map(item=>`${item.entityType}:${item.entityId}${item.version?`:v${item.version}`:""}`)??[];
const taskGroup=(task:TaskContract,today:string):SiteTaskGroup=>task.status==="completed"||task.status==="accepted"?"DONE":task.status==="blocked"?"BLOCKED":task.isOverdue?"OVERDUE":task.dueDate===today?"TODAY":"UPCOMING";
const location=(task:TaskContract)=>task.description?.match(/(?:location|area|room):\s*([^\n.;]+)/i)?.[1]?.trim()??"Not available";
const urgency=(lifecycle:OmniroLifecycle):SiteAttention["urgency"]=>lifecycle==="CONFLICT"||lifecycle==="BLOCKED"?"critical":lifecycle==="APPROVAL_REQUIRED"?"high":"normal";

export function buildSiteManagerProjection(session:Session,projects:readonly ProjectContract[],runtimes:ReadonlyMap<string,OmniroRuntimeSnapshot>,sources:DirectorSources,projectId:string,today=new Date().toISOString().slice(0,10)):SiteManagerProjection{
 const project=projects.find(item=>item.id===projectId)??projects[0];if(!project)throw new Error("Site Manager Workspace requires an authoritative project context.");
 const runtime=runtimes.get(project.id),projectTasks=sources.tasks.filter(item=>item.projectId===project.id),documents=sources.documents.filter(document=>document.links.some(link=>link.entityType==="project"&&link.entityId===project.id)),projectManager=project.projectManagerId?sources.users.find(user=>user.id===project.projectManagerId):undefined;
 const tasks=projectTasks.map(task=>({task,group:taskGroup(task,today),location:location(task),responsibility:task.assignees[0]?.displayName??"UNASSIGNED",source:`task:${task.id}:v${task.version}`,requiredAction:task.status==="submitted_for_review"?"Foreman review required":task.status==="blocked"?"Resolve blocker":task.isOverdue?"Update or complete overdue work":terminal.has(task.status)?"No action required":task.dueDate===today?"Execute today":"Monitor planned work",provenance:[`task:${task.id}:v${task.version}`,`project:${project.id}:v${project.version}`]}));
 const groups:Record<SiteTaskGroup,SiteTask[]>={TODAY:tasks.filter(item=>item.group==="TODAY"),OVERDUE:tasks.filter(item=>item.group==="OVERDUE"),BLOCKED:tasks.filter(item=>item.group==="BLOCKED"),DONE:tasks.filter(item=>item.group==="DONE"),UPCOMING:tasks.filter(item=>item.group==="UPCOMING")};
 const attention:SiteAttention[]=[];
 for(const item of tasks)if(item.group==="OVERDUE"||item.group==="BLOCKED")attention.push({id:`task:${item.task.id}`,title:item.task.title,why:item.group==="BLOCKED"?"Task lifecycle is blocked.":`Deadline ${item.task.dueDate} is overdue.`,status:item.task.status,urgency:item.group==="BLOCKED"||item.task.priority==="urgent"?"critical":"high",responsibility:item.responsibility,target:{kind:"task",entityId:item.task.id,projectId:project.id},provenance:item.provenance,escalation:"PROJECT MANAGER"});
 for(const document of documents)if(document.ocrStatus==="failed"||document.aiProcessingStatus==="failed")attention.push({id:`document:${document.id}`,title:document.title,why:`Document processing requires attention: OCR ${document.ocrStatus}, analysis ${document.aiProcessingStatus}.`,status:"processing_failed",urgency:"high",responsibility:sources.users.find(user=>user.id===document.updatedBy)?.displayName??"UNASSIGNED",target:{kind:"document",entityId:document.id,projectId:project.id},provenance:[`document:${document.id}:v${document.version}`,`file:${document.currentVersion.id}:v${document.currentVersionNo}`,`project:${project.id}`],escalation:"PROJECT MANAGER"});
 for(const state of runtime?.modules.values()??[])if(attentionLifecycles.has(state.lifecycle)){const definition=buildingModuleRegistry.get(state.moduleId),approval=definition?.approval?.detect(state,session),requiresDirector=state.lifecycle==="APPROVAL_REQUIRED"&&!approval?.permitted;attention.push({id:`module:${project.id}:${state.moduleId}:${state.record?.entityId??state.status}`,title:definition?.label??state.moduleId,why:state.reason,status:state.lifecycle,urgency:urgency(state.lifecycle),responsibility:requiresDirector?"DIRECTOR AUTHORITY REQUIRED":"PROJECT MANAGER AUTHORITY REQUIRED",target:{kind:approval?.permitted?"workspace":"module",moduleId:approval?.openWorkspaceId??state.moduleId,projectId:project.id,entityId:state.record?.entityId},provenance:evidence(state),escalation:requiresDirector?"DIRECTOR":"PROJECT MANAGER"});}
 attention.sort((a,b)=>({critical:0,high:1,normal:2}[a.urgency]-{critical:0,high:1,normal:2}[b.urgency])||a.title.localeCompare(b.title));
 const stateFor=(id:string)=>runtime?.modules.get(id),scopeObserved=stateFor("work-scope")?.observed,materialObserved=stateFor("material-consumption")?.observed,scope=Array.isArray(scopeObserved)?(scopeObserved as WorkScopeDto[])[0]:scopeObserved as WorkScopeDto|undefined,materials=Array.isArray(materialObserved)?(materialObserved as MaterialConsumptionDto[])[0]:materialObserved as MaterialConsumptionDto|undefined;
 const work=(scope?.items??[]).map(item=>{const mapping=scope?.mappings?.find(candidate=>candidate.workItemId===item.id),relatedTask=projectTasks.find(task=>task.title.toLowerCase().includes(item.description.toLowerCase())||item.description.toLowerCase().includes(task.title.toLowerCase()));return{item,quantity:mapping?.scannerQuantityValue,unit:mapping?.scannerUnit,relatedTask,provenance:[`work-scope:${scope!.id}:v${scope!.version}`,`work-item:${item.id}:v${item.version}`,...(mapping?[`spatial-snapshot:${mapping.spatialSnapshotId}`,`formula:${mapping.scannerFormulaId}:${mapping.scannerCalculatorVersion}`]:[])]}});
 const peopleById=new Map<string,SitePerson>();for(const task of projectTasks)for(const assignee of task.assignees){const current=peopleById.get(assignee.userId);peopleById.set(assignee.userId,{id:assignee.userId,displayName:assignee.displayName,responsibilities:[...(current?.responsibilities??[]),task.title],truth:"REAL"})}if(projectManager)peopleById.set(projectManager.id,{id:projectManager.id,displayName:projectManager.displayName,responsibilities:[`Project Manager · ${project.projectNumber}`],truth:"DERIVED"});
 const scannerState=stateFor("room-scanner"),documentFailures=documents.filter(item=>item.ocrStatus==="failed"||item.aiProcessingStatus==="failed").length;
 return{project,projectManager,today,taskGroups:groups,tasks,attention,briefing:{total:attention.length,overdue:groups.OVERDUE.length,blocked:groups.BLOCKED.length,documentFailures,items:attention.slice(0,5)},scope,work,documents,materials,people:[...peopleById.values()],unassigned:projectTasks.filter(task=>!terminal.has(task.status)&&!task.assignees.length).length,scanner:scannerState?{truth:scannerState.truth,lifecycle:scannerState.lifecycle,status:scannerState.status,reason:scannerState.reason,target:{kind:"workspace",moduleId:"room-scanner",projectId:project.id,entityId:scannerState.record?.entityId},provenance:evidence(scannerState)}:undefined,weather:{truth:"UNAVAILABLE",reason:"No operational weather provider or weather-to-work rule authority is connected."},drawingIntelligence:{truth:"UNAVAILABLE",reason:"Drawing comparison and approval-for-construction authority are not connected."}};
}
