import{lazy,Suspense}from"react";
import type{ProjectContract}from"@odls/contracts";
import type{Session}from"./api.js";
import{LivingEarth}from"./living-earth.js";
import{buildingModuleRegistry}from"./omniro-building-modules.js";
import type{OmniroFlowRuntimeState}from"./omniro-flow-contract.js";
import type{OmniroRuntimeSnapshot}from"./omniro-module-contract.js";
import{OmniroDataFlowLanes,OmniroDataFlowLegend}from"./omniro-data-flow-renderer.js";
import{OmniroDirectorWorkspace,type DirectorContextPage}from"./omniro-director-workspace.js";
import type{DirectorSources}from"./omniro-director-workspace-model.js";
import{dataFlowVisualRegistry,productRegistry,type OmniroEnvironmentLayer}from"./omniro-operating-environment-model.js";

const OmniroAccountantWorkspace=lazy(()=>import("./omniro-accountant-workspace.js").then(module=>({default:module.OmniroAccountantWorkspace})));
const OmniroProjectManagerWorkspace=lazy(()=>import("./omniro-project-manager-workspace.js").then(module=>({default:module.OmniroProjectManagerWorkspace})));
const OmniroSiteManagerWorkspace=lazy(()=>import("./omniro-site-manager-workspace.js").then(module=>({default:module.OmniroSiteManagerWorkspace})));
const OmniroWorkerWorkspace=lazy(()=>import("./omniro-worker-workspace.js").then(module=>({default:module.OmniroWorkerWorkspace})));
const OmniroClientWorkspace=lazy(()=>import("./omniro-client-workspace.js").then(module=>({default:module.OmniroClientWorkspace})));
type Props={session:Session;projects:ProjectContract[];project:ProjectContract;runtime:OmniroRuntimeSnapshot;runtimes:ReadonlyMap<string,OmniroRuntimeSnapshot>;directorSources:DirectorSources;flows:readonly OmniroFlowRuntimeState[];layer:OmniroEnvironmentLayer;roleId?:string;onLayer:(layer:OmniroEnvironmentLayer)=>void;onRole:(id:string)=>void;onProject:(id:string)=>void;onModule:(id:string,projectId?:string)=>void;onWorkspace:(id:string,projectId?:string)=>void;onContext:(page:DirectorContextPage,id?:string)=>void};
const truthLabel=(truth:string)=><span className={`oe-truth truth-${truth.toLowerCase()}`}>{truth}</span>;

function EnvironmentHeader({session,layer,onLayer}:{session:Session;layer:OmniroEnvironmentLayer;onLayer:(layer:OmniroEnvironmentLayer)=>void}){
 return <header className="oe-header"><button className="oe-brand" onClick={()=>onLayer("universe")} aria-label="Open OMNIRO Universe"><i aria-hidden="true"/>OMNIRO</button><nav aria-label="Operating environment layers">{(["universe","building","role"]as const).map((item,index)=><button key={item} className={layer===item?"is-current":""} aria-current={layer===item?"page":undefined} onClick={()=>onLayer(item)}><b>0{index+1}</b>{item==="role"?"Role Workspace":item==="building"?"Product World":"Universe"}</button>)}</nav><div className="oe-actor"><span>AI Secretary <small>Grounded guidance</small></span><b>{session.user.displayName}</b></div></header>;
}

function Universe({projects,onLayer}:{projects:ProjectContract[];onLayer:(layer:OmniroEnvironmentLayer)=>void}){
 const products=productRegistry.definitions.map(item=>({...item,...item.resolve(projects)})),attention=projects.filter(project=>["paused","cancelled"].includes(project.status)).length;
 return <main className="oe-universe" aria-labelledby="oe-universe-title"><section className="oe-layer-copy"><small>LAYER 1</small><h1 id="oe-universe-title">OMNIRO Universe</h1><p>The universe of solutions. Earth represents the authenticated company environment; it is conceptual, not geographic.</p><ul><li>Orchestrator connects registered products and data.</li><li>Only grounded Product Worlds are enterable.</li><li>Human authority remains outside automated flows.</li></ul></section><section className="oe-earth-system"><div className="oe-orchestrator" role="status"><i aria-hidden="true">◉</i><strong>ORCHESTRATOR</strong><small>{attention?`${attention} project contexts require attention`:"No critical project state is inferred"}</small></div><LivingEarth state={attention?"company-attention":"idle"} flowCount={products.filter(item=>item.truth==="REAL").length}/><div className="oe-product-orbit">{products.map((product,index)=><button key={product.id} className={`oe-product-node truth-${product.truth.toLowerCase()}`} style={{"--product-index":index}as React.CSSProperties} disabled={!product.route} aria-label={`${product.label}. ${product.truth}. ${product.reason}`} onClick={()=>product.route&&onLayer(product.route.layer)}><i>{product.glyph}</i><span><strong>{product.label}</strong><small>{product.description}</small>{truthLabel(product.truth)}</span></button>)}</div></section><aside className="oe-intelligence"><small>UNIVERSE INTELLIGENCE</small><h2>Truthful system state</h2>{products.map(product=><article key={product.id}><strong>{product.label}</strong>{truthLabel(product.truth)}<p>{product.reason}</p></article>)}</aside></main>;
}

function BuildingWorld({projects,project,runtime,flows,onProject,onModule,onWorkspace,onLayer}:{projects:ProjectContract[];project:ProjectContract;runtime:OmniroRuntimeSnapshot;flows:readonly OmniroFlowRuntimeState[];onProject:(id:string)=>void;onModule:(id:string,projectId?:string)=>void;onWorkspace:(id:string,projectId?:string)=>void;onLayer:(layer:OmniroEnvironmentLayer)=>void}){
 const modules=buildingModuleRegistry.definitions.filter(item=>item.kind==="authority"),projectedFlows=dataFlowVisualRegistry.project(runtime,flows),attention=[...runtime.modules.values()].filter(item=>["WAIT","APPROVAL_REQUIRED","CONFLICT","BLOCKED"].includes(item.lifecycle));
 return <main className="oe-building" aria-labelledby="oe-building-title"><aside className="oe-world-rail"><small>LAYER 2 · PRODUCT WORLD</small><button onClick={()=>onLayer("universe")}>← Back to Universe</button><h1 id="oe-building-title">OMNIRO Building</h1><p>The connected construction operating environment.</p><label>Project context<select value={project.id} onChange={event=>onProject(event.target.value)}>{projects.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><nav aria-label="Building capabilities">{modules.map(module=>{const state=runtime.modules.get(module.id);return <button key={module.id} onClick={()=>onModule(module.id)} disabled={state?.availability==="unavailable"}>{module.label}<small>{state?.truth??module.defaultTruth}</small></button>})}</nav></aside><section className="oe-building-map"><header><div><small>REAL PRODUCT WORLD</small><h2>{project.name}</h2><p>{project.projectNumber} · {project.status} · {project.currencyCode}</p></div><button onClick={()=>onLayer("role")}>Open Director Workspace →</button></header><div className="oe-city-core" aria-label="OMNIRO Building capability map"><div className="oe-city" aria-hidden="true"><i/><i/><i/><i/><b>BUILDING</b></div><OmniroDataFlowLanes flows={projectedFlows} variant="radial"/>{modules.map((module,index)=>{const state=runtime.modules.get(module.id);return <button key={module.id} className={`oe-capability truth-${state?.truth.toLowerCase()}`} style={{"--cap-index":index}as React.CSSProperties} onClick={()=>state?.availability!=="unavailable"&&onWorkspace(module.id)} disabled={state?.availability==="unavailable"} aria-label={`${module.label}. ${state?.truth}. ${state?.reason}`}><i>{module.visual.glyph}</i><strong>{module.label}</strong><small>{state?.status.replaceAll("_"," ")}</small></button>})}</div><OmniroDataFlowLegend flows={projectedFlows}/></section><aside className="oe-intelligence"><small>BUILDING INTELLIGENCE</small><h2>Current authority state</h2>{attention.length?<>{attention.slice(0,5).map(item=><button key={item.moduleId} onClick={()=>onModule(item.moduleId)}><strong>{buildingModuleRegistry.get(item.moduleId)?.label}</strong><small>{item.status.replaceAll("_"," ")}</small><p>{item.reason}</p></button>)}</>:<p>No loaded module currently declares an attention lifecycle.</p>}<section><h3>Orchestrator</h3><p>Explanations are derived from the selected module, its evidence and registered flows. No AI execution is simulated here.</p></section></aside></main>;
}

export function OmniroOperatingEnvironment(props:Props){
 const projectedFlows=dataFlowVisualRegistry.project(props.runtime,props.flows);
 const workspaceProps={session:props.session,projects:props.projects,project:props.project,runtimes:props.runtimes,sources:props.directorSources,flows:projectedFlows,onBack:()=>props.onLayer("building"),onRole:props.onRole,onProject:props.onProject,onModule:props.onModule,onWorkspace:props.onWorkspace,onContext:props.onContext};
 const role=props.roleId==="accountant"?<Suspense fallback={<section className="oc-load">Loading Accountant Workspace</section>}><OmniroAccountantWorkspace {...workspaceProps}/></Suspense>:props.roleId==="project-manager"?<Suspense fallback={<section className="oc-load">Loading Project Manager Workspace</section>}><OmniroProjectManagerWorkspace {...workspaceProps}/></Suspense>:props.roleId==="site-manager"?<Suspense fallback={<section className="oc-load">Loading Site Manager Workspace</section>}><OmniroSiteManagerWorkspace {...workspaceProps}/></Suspense>:props.roleId==="worker"?<Suspense fallback={<section className="oc-load">Loading Worker Workspace</section>}><OmniroWorkerWorkspace session={props.session} project={props.project} onBack={()=>props.onLayer("building")} onScanner={()=>props.onWorkspace("room-scanner",props.project.id)} onNotifications={()=>props.onContext("notifications")}/></Suspense>:props.roleId==="client"?<Suspense fallback={<section className="oc-load">Loading Client Workspace</section>}><OmniroClientWorkspace session={props.session} onBack={()=>props.onLayer("building")} onNotifications={()=>props.onContext("notifications")}/></Suspense>:<OmniroDirectorWorkspace {...workspaceProps}/>;
 return <section className={`oe-shell layer-${props.layer}`}><EnvironmentHeader session={props.session} layer={props.layer} onLayer={props.onLayer}/>{props.layer==="universe"?<Universe projects={props.projects} onLayer={props.onLayer}/>:props.layer==="building"?<BuildingWorld {...props}/>:role}<footer className="oe-constitution"><span><b>Unified data model</b>Single source of truth</span><span><b>Secure & compliant</b>RLS · Audit · Permissions</span><span><b>AI assisted</b>Explain · Recommend · Alert</span><span><b>Human authority</b>You decide · You approve</span><strong>Operating Environment, Not a Website</strong></footer></section>;
}
