import{afterEach,describe,expect,it,vi}from"vitest";
import{api,type MaterialConsumptionDto,type RegionalPricingDto,type Session}from"./api.js";
import{regionalPricingAdapter,resolveRuntime}from"./omniro-building-adapters.js";
import{buildingFlowDefinitions}from"./omniro-building-flows.js";
import{loadOmniroData}from"./omniro-command-center-data.js";

const session:Session={accessToken:"x",refreshToken:"x",user:{id:"u",email:"u@example.test",displayName:"User"},permissions:["projects.read","material_consumption.read","material_consumption.snapshots.read","regional_pricing.read","regional_pricing.snapshots.read"]};
const consumption:MaterialConsumptionDto={id:"run-1",projectId:"project-1",code:"MC-1",title:"Demand",revisionId:"mc-revision",revisionNumber:1,status:"approved",version:3,workScopeSnapshotId:"scope-1",normSnapshotId:"norm-1",knowledgeVersionId:"knowledge-1",technologyVersionId:"technology-1",workItemId:"item-1",evaluatedParameters:{},workQuantity:12,workQuantityUnit:"m2",lines:[]};
const pricing:RegionalPricingDto={id:"pricing-1",code:"PL-WAW",title:"Warsaw rates",revisionId:"pricing-revision",revisionNumber:1,status:"approved",version:3,currency:"PLN",countryCode:"PL",regionCode:"mazowieckie",city:"Warsaw",effectiveFrom:"2026-01-01",effectiveTo:"2026-12-31",customerCategory:"commercial",commercialProfile:"standard",priceSource:"Verified quotes",overheadRules:[],marginRules:[],discountRules:[],adjustmentRules:[],calculationVersion:"regional-pricing-v1",entries:[]};
const snapshot=(id:string)=>({id,contentFingerprint:"a".repeat(64),schemaVersion:id.startsWith("mc")?"material-consumption-v1":"regional-pricing-v1",revisionNumber:1});

function mockBase(){
 vi.spyOn(api,"projectsPage").mockResolvedValue({data:[{id:"project-1",name:"Project",projectNumber:"P-1",status:"active",currencyCode:"PLN",version:1}],pagination:{page:1,pageSize:100,total:1,totalPages:1}}as never);
 vi.spyOn(api,"roomScans").mockResolvedValue({data:[],pagination:{page:1,pageSize:25,total:0,totalPages:0}});vi.spyOn(api,"technicalAssignments").mockResolvedValue([]);vi.spyOn(api,"designProjects").mockResolvedValue([]);vi.spyOn(api,"technologies").mockResolvedValue([]);vi.spyOn(api,"workScopes").mockResolvedValue([]);vi.spyOn(api,"engineeringNorms").mockResolvedValue([]);
}

describe("Regional Pricing Command Center integration",()=>{
 afterEach(()=>vi.restoreAllMocks());
 it("loads list, detail, and approved snapshots from existing APIs",async()=>{mockBase();vi.spyOn(api,"materialConsumptions").mockResolvedValue([consumption]);vi.spyOn(api,"materialConsumption").mockResolvedValue(consumption);vi.spyOn(api,"materialConsumptionSnapshot").mockResolvedValue(snapshot("mc-snapshot"));const list=vi.spyOn(api,"regionalPricings").mockResolvedValue([pricing]),detail=vi.spyOn(api,"regionalPricing").mockResolvedValue(pricing),approved=vi.spyOn(api,"regionalPricingSnapshot").mockResolvedValue(snapshot("pricing-snapshot"));const loaded=await loadOmniroData(session),source=loaded.byProject.get("project-1");expect(list).toHaveBeenCalledOnce();expect(detail).toHaveBeenCalledWith("pricing-1");expect(approved).toHaveBeenCalledWith("pricing-1");expect(source?.regionalPricings[0]).toMatchObject({id:"pricing-1",approvedSnapshot:{id:"pricing-snapshot"}});expect(source?.materialConsumptions[0]).toMatchObject({approvedSnapshot:{id:"mc-snapshot"}});expect(loaded.partial).toEqual([])});
 it("reports a pricing API failure as PARTIAL without fabricating data",async()=>{mockBase();vi.spyOn(api,"materialConsumptions").mockResolvedValue([]);vi.spyOn(api,"regionalPricings").mockRejectedValue(new Error("offline"));const loaded=await loadOmniroData(session),source=loaded.byProject.get("project-1");expect(source?.regionalPricings).toEqual([]);expect(source?.sourceFailures).toContain("regional-pricing");expect(regionalPricingAdapter.resolve({projectId:"project-1",session,sources:source as never})).toMatchObject({truth:"PARTIAL",availability:"partial"})});
 it("activates the dependency only from readable approved snapshots and never enables Commercial Estimate",()=>{const project={id:"project-1",currencyCode:"PLN"},sources={project,scans:[],assignments:[],designs:[],technologies:[],workScopes:[],engineeringNorms:[],materialConsumptions:[{...consumption,approvedSnapshot:snapshot("mc-snapshot")}],regionalPricings:[{...pricing,approvedSnapshot:snapshot("pricing-snapshot")}],sourceFailures:[]},adapters=new Map<string,any>([["material-consumption",{resolve:(input:any)=>{const item=input.sources.materialConsumptions[0];return{moduleId:"material-consumption",projectId:input.projectId,truth:"REAL",availability:"available",lifecycle:"APPROVED",status:"approved",reason:"approved",evidence:item.approvedSnapshot?[{entityType:"approved-material-consumption-snapshot",entityId:item.approvedSnapshot.id,label:"Approved consumption"}]:[]}}}],["regional-pricing",regionalPricingAdapter],["commercial-estimate",{resolve:(input:any)=>({moduleId:"commercial-estimate",projectId:input.projectId,truth:"UNAVAILABLE",availability:"unavailable",lifecycle:"IDLE",status:"unavailable",reason:"not connected",evidence:[]})}]]),runtime=resolveRuntime("project-1",session,sources as never,adapters),flow=buildingFlowDefinitions.find(x=>x.id==="material-consumption:regional-pricing")!,state=flow.resolve({projectId:"project-1",session,sources}as never,runtime);expect(state).toMatchObject({truth:"DERIVED",state:"available"});expect(state.reason).toContain("No price has been applied");expect(runtime.modules.get("commercial-estimate")).toMatchObject({truth:"UNAVAILABLE"});const blockedSources={...sources,materialConsumptions:[consumption]},blockedRuntime=resolveRuntime("project-1",session,blockedSources as never,adapters),blocked=flow.resolve({projectId:"project-1",session,sources:blockedSources}as never,blockedRuntime);expect(blocked).toMatchObject({truth:"UNAVAILABLE",state:"blocked"})});
});
