import type{StageFlowState}from"./omniro-stage-flow.js";
export type LivingMode="idle"|"settle"|"approach"|"identity"|"evidence"|"scan"|"created"|"depart"|"transport"|"receive"|"gate"|"suspended"|"resume"|"validate"|"compute"|"result"|"insight"|"route"|"explain"|"workspace"|"workspace_ready";
export type LivingStep={id:string;label:string;active:string;origin:string;destination:string;state:StageFlowState;mode:LivingMode;duration:number};
const s=(id:number,label:string,active:string,origin:string,destination:string,state:StageFlowState,mode:LivingMode,duration=900):LivingStep=>({id:String(id).padStart(2,"0"),label,active,origin,destination,state,mode,duration});
export const livingSequence:LivingStep[]=[
 s(0,"Cinematic idle Core close-up","OMNIRO","OMNIRO","OMNIRO","idle","idle",1600),s(1,"Full system settles","OMNIRO","OMNIRO","OMNIRO","idle","settle",1200),
 s(2,"Cursor approaches Scanner","scanner","OMNIRO","scanner","processing","approach"),s(3,"Scanner grows toward 110%","scanner","OMNIRO","scanner","processing","approach"),s(4,"Scanner identity resolves","scanner","scanner","scanner","processing","identity"),s(5,"Demonstration evidence appears","scanner","scanner","scanner","processing","evidence",1200),s(6,"Scanner analyzes evidence","scanner","scanner","scanner","processing","scan",1700),s(7,"Structured payload created","scanner","scanner","passport","processing","created",1100),s(8,"Payload departs Scanner","scanner","scanner","passport","processing","depart",900),s(9,"Payload travels through space","passport","scanner","passport","processing","transport",1800),s(10,"Passport reacts to approach","passport","scanner","passport","waiting","receive",1000),s(11,"Payload enters Passport","passport","scanner","passport","waiting","receive",900),
 s(12,"Approval Gate stops payload","passport","scanner","passport","human_approval_required","gate",0),s(13,"Payload remains suspended","passport","scanner","passport","human_approval_required","suspended",0),s(14,"Human approves","passport","scanner","passport","confirmed","gate",0),s(15,"Gate opens; payload resumes","passport","passport","norms","confirmed","resume",1200),
 s(16,"Norms validates against rule layers","norms","passport","norms","processing","validate",1700),s(17,"Verified payload moves to Estimate","estimate","norms","estimate","processing","transport",1500),s(18,"Estimate calculates quantities and context","estimate","norms","estimate","processing","compute",1800),s(19,"Estimate result payload created","estimate","estimate","analytics","processing","created",1100),s(20,"Result travels to Analytics","analytics","estimate","analytics","processing","transport",1700),s(21,"Analytics receives result","analytics","estimate","analytics","waiting","receive",900),s(22,"Analytics transforms data into insight","analytics","estimate","analytics","complete","insight",1600),
 s(23,"Payload reaches Orchestrator","orchestrator","passport","orchestrator","processing","transport",1400),s(24,"Orchestrator reroutes information","orchestrator","orchestrator","norms","processing","route",1800),s(25,"Ask Orchestrator explanation","orchestrator","orchestrator","norms","waiting","explain",0),s(26,"Complete living system","OMNIRO","analytics","OMNIRO","complete","settle",1400),s(27,"Scanner selected","scanner","OMNIRO","scanner","confirmed","approach",900),s(28,"Scanner becomes workspace anchor","scanner","scanner","scanner","confirmed","workspace",900),s(29,"Functional workspace ready","scanner","scanner","scanner","complete","workspace_ready",0),
];
