import{useEffect,useMemo,useState}from"react";
import{api,apiErrorMessage,type ApprovedSnapshotDto,type EngineeringNormAnalysisDto,type EngineeringNormDto,type EngineeringNormEvaluationDto,type WorkScopeDto}from"./api.js";
import type{OmniroWorkspaceProps}from"./omniro-module-contract.js";
import"./omniro-stage-2c.css";

export type NormScopeMatch={itemId:string;description:string;quantity:number;unit:string;workScopeId:string;workScopeCode:string};
export function matchApprovedScope(norm:EngineeringNormDto,scopes:WorkScopeDto[]):NormScopeMatch[]{return scopes.filter(s=>s.status==="approved").flatMap(s=>(s.items??[]).filter(i=>i.reviewState==="confirmed"&&i.workType===norm.workType&&i.technologyVersionId===norm.technologyVersionId).flatMap(i=>{const mappings=(s.mappings??[]).filter(m=>m.workItemId===i.id);return mappings.length?[{itemId:i.id,description:i.description,quantity:mappings.reduce((n,m)=>n+Number(m.scannerQuantityValue),0),unit:[...new Set(mappings.map(m=>m.scannerUnit))].join(" / "),workScopeId:s.id,workScopeCode:s.code}]:[]}))}
export function evaluationParameters(norm:EngineeringNormDto){return Object.fromEntries((norm.parameters??[]).map(p=>[p.code,(p.defaultValue??p.minimumValue??(p.dataType==="boolean"?false:p.dataType==="enum"?p.allowedValues[0]:undefined))]).filter(([,v])=>v!==undefined))as Record<string,string|number|boolean>}

export default function EngineeringNormWorkspace({session,projectId,runtime,onClose}:OmniroWorkspaceProps){
 const observed=(runtime.observed??[])as EngineeringNormDto[];
 const[norms,setNorms]=useState<EngineeringNormDto[]>(observed),[selectedId,setSelectedId]=useState(observed[0]?.id??""),[scopes,setScopes]=useState<WorkScopeDto[]>([]),[analysis,setAnalysis]=useState<EngineeringNormAnalysisDto>(),[snapshot,setSnapshot]=useState<ApprovedSnapshotDto>(),[evaluation,setEvaluation]=useState<EngineeringNormEvaluationDto>(),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const selected=norms.find(n=>n.id===selectedId)||norms[0],matches=useMemo(()=>selected?matchApprovedScope(selected,scopes):[],[selected,scopes]);
 const reload=async(id=selected?.id)=>{if(!id)return;const detail=await api.engineeringNorm(id);setNorms(xs=>xs.map(x=>x.id===id?detail:x));setAnalysis(await api.engineeringNormAnalysis(id));if(detail.status==="approved")setSnapshot(await api.engineeringNormSnapshot(id).catch(()=>undefined));};
 useEffect(()=>{let active=true;(async()=>{try{const scopeList=await api.workScopes(projectId),detailed=await Promise.all(scopeList.map(s=>api.workScope(s.id)));if(active)setScopes(detailed);if(selected?.id)await reload(selected.id)}catch(e){if(active)setError(apiErrorMessage(e))}})();return()=>{active=false}},[projectId,selectedId]);
 const run=async(action:()=>Promise<unknown>)=>{setBusy(true);setError("");try{await action();await reload()}catch(e){setError(apiErrorMessage(e))}finally{setBusy(false)}};
 const readiness=()=>selected&&run(()=>api.engineeringNormReadiness(selected.id,selected.version));
 const approve=()=>selected&&run(async()=>setSnapshot(await api.engineeringNormApprove(selected.id,selected.version)));
 const evaluate=()=>selected&&matches[0]&&run(async()=>setEvaluation(await api.engineeringNormEvaluate(selected.id,{workQuantity:matches[0].quantity,parameters:evaluationParameters(selected),effectiveOn:new Date().toISOString().slice(0,10)})));
 return <section className="s2c-workspace" aria-label="Engineering Norms Agent Workspace">
  <header><button type="button" onClick={onClose}>← Return to system</button><p>AGENT WORKSPACE · ENGINEERING AUTHORITY</p><h1>Engineering Norms</h1><span className="s2c-truth">REAL</span><p>{runtime.reason}</p></header>
  {error&&<p role="alert" className="s2c-error">{error}</p>}
  {!selected?<div className="s2c-empty"><h2>No Engineering Norm authority</h2><p>Approved Technology and Construction Knowledge must be created through their existing governed contracts. OMNIRO made no mutation.</p></div>:<>
   <label>Engineering Norm<select value={selected.id} onChange={e=>{setSelectedId(e.target.value);setSnapshot(undefined);setEvaluation(undefined)}}>{norms.map(n=><option key={n.id} value={n.id}>{n.code} · revision {n.revisionNumber} · {n.status}</option>)}</select></label>
   <div className="s2c-authorities" aria-label="Engineering Norm authority inputs"><article><p>REFERENCE AUTHORITY</p><h2>Approved Technology</h2><code>{selected.technologyVersionId}</code><small>Independent immutable version reference</small></article><article><p>KNOWLEDGE AUTHORITY</p><h2>Construction Knowledge</h2><code>{selected.knowledgeVersionId}</code><small>Independent approved engineering rules</small></article><article><p>PROJECT EVALUATION CONTEXT</p><h2>Approved Work Scope</h2><strong>{matches.length} matching item{matches.length===1?"":"s"}</strong><small>Context only — no authority is mutated</small></article></div>
   <section className="s2c-model"><div><p>ENGINEERING MODEL</p><h2>{selected.title}</h2><dl><dt>Work type</dt><dd>{selected.workType}</dd><dt>Region</dt><dd>{selected.countryCode}{selected.regionCode?` / ${selected.regionCode}`:""}</dd><dt>Effective</dt><dd>{selected.effectiveFrom??"—"} → {selected.effectiveTo??"open"}</dd><dt>Lifecycle</dt><dd>{selected.status}</dd></dl></div><div><p>READINESS</p><strong>{analysis?.ready?"READY":"HUMAN REVIEW"}</strong><ul>{analysis?.issues.map(x=><li key={`${x.code}-${x.detail}`}>{x.code}{x.detail?` · ${x.detail}`:""}</li>)}</ul>{selected.status==="draft"&&session.permissions.includes("engineering_norms.review")&&<button disabled={busy} onClick={readiness}>CHECK READINESS →</button>}{selected.status==="ready_for_approval"&&<button disabled={busy||!session.permissions.includes("engineering_norms.approve")} onClick={approve}>HUMAN APPROVAL · ENGINEERING NORM →</button>}</div></section>
   <section><p>PARAMETERS · LAYERS · DEMANDS</p><div className="s2c-grid"><article><strong>{selected.parameters?.length??0}</strong><span>Parameters</span></article><article><strong>{selected.layers?.length??0}</strong><span>Execution layers</span></article><article><strong>{selected.demands?.length??0}</strong><span>Requirement demands</span></article></div><ul className="s2c-demands">{selected.demands?.map(d=><li key={`${d.demandKind}-${d.requirementCode}`}><b>{d.demandKind.replaceAll("_"," ")}</b><span>{d.requirementCode}</span><small>{d.description}</small></li>)}</ul></section>
   <section aria-label="Approved Work Scope matching"><p>APPROVED WORK SCOPE → NORM EVALUATION</p>{matches.length?matches.map(m=><article className="s2c-match" key={m.itemId}><div><strong>{m.description}</strong><small>{m.workScopeCode} · immutable approved context</small></div><code>{m.quantity} {m.unit}</code></article>):<p>No approved Work Scope item matches both work type and exact Technology version.</p>}{selected.status==="approved"&&matches.length>0&&<button disabled={busy||!session.permissions.includes("engineering_norms.evaluate")} onClick={evaluate}>EVALUATE APPROVED NORM →</button>}</section>
   {snapshot&&<section className="s2c-snapshot" aria-label="Approved immutable Engineering Norm snapshot"><p>AUTHORITATIVE OUTPUT</p><h2>Immutable Engineering Norm snapshot</h2><code>{snapshot.id}</code><code>{snapshot.contentFingerprint}</code><p>Commercial data: excluded · Product selection: excluded · Supplier data: excluded</p></section>}
   {evaluation&&<section aria-label="Grounded Engineering Norm evaluation"><p>DETERMINISTIC EVALUATION · NO COMMERCIAL CALCULATION</p><h2>{evaluation.workQuantity} work units</h2><ul>{evaluation.demands.map(d=><li key={`${d.demandKind}-${d.requirementCode}`}>{d.requirementCode}: <b>{d.quantity} {d.unitCode}</b></li>)}</ul></section>}
  </>}
 </section>
}
