import type{ProjectContract}from"@odls/contracts";
import type{Session}from"./api.js";
import{OmniroDataFlowLegend,type DataFlowProjection}from"./omniro-data-flow-renderer.js";
import type{DirectorContextPage}from"./omniro-director-workspace.js";
import type{DirectorSources,DirectorTarget}from"./omniro-director-workspace-model.js";
import{buildProjectManagerProjection}from"./omniro-project-manager-workspace-model.js";
import type{OmniroRuntimeSnapshot}from"./omniro-module-contract.js";
import{roleWorkspaceRegistry}from"./omniro-role-workspace-registry.js";

type Props={session:Session;projects:ProjectContract[];project:ProjectContract;runtimes:ReadonlyMap<string,OmniroRuntimeSnapshot>;sources:DirectorSources;flows:readonly DataFlowProjection[];onBack:()=>void;onRole:(id:string)=>void;onProject:(id:string)=>void;onModule:(id:string,projectId?:string)=>void;onWorkspace:(id:string,projectId?:string)=>void;onContext:(page:DirectorContextPage,id?:string)=>void};
const truth=(value:string)=><span className={`oe-truth truth-${value.toLowerCase()}`}>{value}</span>;

export function OmniroProjectManagerWorkspace({session,projects,project,runtimes,sources,flows,onBack,onRole,onProject,onModule,onWorkspace,onContext}:Props){
 const projection=buildProjectManagerProjection(session,projects,runtimes,sources,project.id),resolved=roleWorkspaceRegistry.resolve("project-manager",session),can=(permission:string)=>session.permissions.includes(permission);
 const open=(target:DirectorTarget)=>{if(target.kind==="workspace"&&target.moduleId)return onWorkspace(target.moduleId,target.projectId);if(target.kind==="module"&&target.moduleId)return onModule(target.moduleId,target.projectId);if(target.kind==="task")return onContext("tasks",target.entityId);if(target.kind==="document")return onContext("documents",target.entityId);if(target.kind==="finance")return onContext("finance",target.entityId);return onContext("project-workspace",target.projectId)};
 return <main className="oe-role oe-director-v1 oe-project-manager-v1" aria-labelledby="oe-role-title">
  <aside className="oe-role-rail"><small>LAYER 3 · PROJECT OPERATIONS</small><button onClick={onBack}>← Back to Product World</button><h2>Role workspaces</h2>{roleWorkspaceRegistry.definitions.map(definition=>{const state=roleWorkspaceRegistry.resolve(definition.roleId,session);return <button key={definition.roleId} disabled={state.truth==="UNAVAILABLE"} className={definition.roleId==="project-manager"?"is-current":""} onClick={()=>state.truth!=="UNAVAILABLE"&&onRole(definition.roleId)}>{definition.label}<small>{state.truth}</small></button>})}<label>Project context<select aria-label="Project context" value={project.id} onChange={event=>onProject(event.target.value)}>{projects.map(item=><option key={item.id} value={item.id}>{item.projectNumber} · {item.name}</option>)}</select></label><section className="oe-temporary-access"><strong>Authenticated authority</strong>{truth("REAL")}<p>Role ≠ actor. Every action remains attributed to {session.user.displayName} ({session.user.id}).</p></section></aside>
  <section className="oe-director oe-project-manager" aria-label="Project Manager operational workspace"><header><div><small>SELECTED PROJECT · AUTHORITATIVE CONTEXT</small><h1 id="oe-role-title">Project Manager Workspace</h1><p>{project.projectNumber} · {project.name} · {project.status} · version {project.version}</p></div>{truth(resolved.truth)}</header><OmniroDataFlowLegend flows={flows} compact/>
   <section className="oe-director-metrics" aria-label="Grounded project operations overview">{projection.metrics.map(metric=><article key={metric.id}><small>{metric.label}</small><strong>{metric.value}</strong><span>{metric.reason}</span>{truth(metric.truth)}</article>)}</section>
   <section className="oe-director-grid oe-project-manager-grid">
    <article className="oe-priority-actions oe-project-attention"><header><h2>WHAT needs attention</h2><small>WHY · WHERE · WHO · DEADLINE</small></header>{projection.attention.length?projection.attention.map(item=><button key={item.id} onClick={()=>open(item.target)} data-urgency={item.urgency}><span><strong>{item.title}</strong><small>{item.why}</small><em>{item.location} · {item.responsibility}</em></span><b>{item.deadline}<small>{item.status.replaceAll("_"," ")}</small></b><i>{item.provenance.join(" · ")||"No evidence reference loaded"}</i>{item.directorDecision&&<mark>DIRECTOR DECISION REQUIRED</mark>}</button>):<p>No loaded project authority declares an attention state.</p>}</article>
    <article className="oe-project-scope"><header><h2>Work Scope & execution</h2>{truth(projection.scope?"REAL":"UNAVAILABLE")}</header>{projection.scope?<><dl><div><dt>Scope</dt><dd>{projection.scope.code}</dd></div><div><dt>Status</dt><dd>{projection.scope.status}</dd></div><div><dt>Revision</dt><dd>{projection.scope.revisionNumber}</dd></div><div><dt>Work items</dt><dd>{projection.scope.items?.length??0}</dd></div><div><dt>Mapped quantities</dt><dd>{projection.scope.mappings?.length??0}</dd></div></dl><small>work-scope:{projection.scope.id}:v{projection.scope.version}</small><button onClick={()=>onWorkspace("work-scope",project.id)}>Open Work Scope authority</button></>:<p>No Work Scope record is loaded for this project.</p>}</article>
    <article className="oe-project-modules"><header><h2>Project authority chain</h2><small>Existing registry/runtime state</small></header>{projection.moduleStates.map(state=><button key={state.id} onClick={()=>open(state.target)}><span><strong>{state.label}</strong><small>{state.reason}</small></span><b>{state.status.replaceAll("_"," ")}</b>{truth(state.truth)}<i>{state.provenance.join(" · ")}</i></button>)}</article>
    <article className="oe-project-materials"><header><h2>Materials & readiness</h2>{truth(projection.materials?"REAL":"UNAVAILABLE")}</header>{projection.materials?<><dl><div><dt>List</dt><dd>{projection.materials.code}</dd></div><div><dt>Status</dt><dd>{projection.materials.status}</dd></div><div><dt>Lines</dt><dd>{projection.materials.lines.length}</dd></div><div><dt>Approved snapshot</dt><dd>{projection.materials.approvedSnapshot?.id??"Not available"}</dd></div></dl><p>Quantities, waste, reserve, packaging and selection remain owned by Material Consumption.</p><button onClick={()=>onWorkspace("material-consumption",project.id)}>Open Material Consumption</button></>:<p>No project Material Consumption authority is loaded.</p>}</article>
    <article className="oe-project-tasks"><header><h2>Task execution</h2>{truth(sources.sourceState.tasks.truth)}</header>{projection.tasks.slice(0,10).map(task=><button key={task.id} onClick={()=>onContext("tasks",task.id)}><span><strong>{task.title}</strong><small>{task.status} · {task.priority} · {task.assignees[0]?.displayName??"UNASSIGNED"}</small></span><b>{task.dueDate??"No deadline"}</b></button>)}{!projection.tasks.length&&<p>No active project tasks are loaded.</p>}</article>
    <article className="oe-project-documents"><header><h2>Document authority</h2>{truth(sources.sourceState.documents.truth)}</header>{projection.documents.slice(0,8).map(document=><button key={document.id} onClick={()=>onContext("documents",document.id)}><span><strong>{document.title}</strong><small>{document.documentType} · OCR {document.ocrStatus}</small></span><b>v{document.currentVersionNo}</b><i>checksum:{document.currentVersion.checksum.slice(0,12)}…</i></button>)}{!projection.documents.length&&<p>No explicit project document links are loaded. Filename matching is not used.</p>}<footer>Document approval-for-construction is UNAVAILABLE: the current Document contract exposes version and processing state, not that authority.</footer></article>
    <article className="oe-financial-summary"><header><h2>Project financial summary</h2>{truth(projection.financial?"REAL":sources.sourceState.finance.truth)}</header>{projection.financial?<dl><div><dt>Budget</dt><dd>{projection.financial.budget??"Not available"} {projection.financial.currencyCode}</dd></div><div><dt>Invoiced</dt><dd>{projection.financial.invoicedGross} {projection.financial.currencyCode}</dd></div><div><dt>Paid</dt><dd>{projection.financial.paid} {projection.financial.currencyCode}</dd></div><div><dt>Outstanding</dt><dd>{projection.financial.outstanding} {projection.financial.currencyCode}</dd></div><div><dt>Expenses</dt><dd>{projection.financial.expenses} {projection.financial.currencyCode}</dd></div><div><dt>Overdue invoices</dt><dd>{projection.financial.overdueInvoiceCount}</dd></div></dl>:<p>No project financial summary is available. No budget, profit or cash KPI is inferred.</p>}<small>{projection.financial?`project-financial-summary:${project.id}`:sources.sourceState.finance.reason}</small></article>
    <article className="oe-quick-access"><header><h2>Grounded project access</h2><small>Existing permissions and workspaces</small></header><div><button disabled={!can("projects.read")} onClick={()=>onContext("project-workspace",project.id)}>Project record</button><button disabled={!can("tasks.read")} onClick={()=>onContext("tasks")}>Tasks</button><button disabled={!can("documents.read")} onClick={()=>onContext("documents")}>Documents / OCR</button><button disabled={!can("room_scans.read")} onClick={()=>onWorkspace("room-scanner",project.id)}>Scanner</button><button disabled={!can("engineering_norms.read")} onClick={()=>onWorkspace("engineering-norms",project.id)}>Engineering Norms</button><button disabled={!can("company_price_books.read")} onClick={()=>onWorkspace("company-price-book",project.id)}>Company Price Book</button><button disabled={!can("commercial_estimates.read")} onClick={()=>onWorkspace("commercial-estimate",project.id)}>Commercial Estimate</button></div></article>
   </section>
  </section>
  <aside className="oe-intelligence oe-director-intelligence oe-project-intelligence"><small>PROJECT INTELLIGENCE RAIL</small><h2>Grounded assistance</h2><article><header><strong>Orchestrator</strong>{truth("DERIVED")}</header><p>{projection.briefing.length?`${projection.briefing.length} deterministic project attention items are grounded in current records.`:"No loaded project source declares an attention state."}</p>{projection.briefing.map(item=><button key={item.id} onClick={()=>open(item.target)}><b>{item.title}</b><small>{item.why}</small><i>{item.provenance.join(" · ")}</i></button>)}</article><article><header><strong>Project Assistant</strong>{truth("PARTIAL")}</header><p>Briefing and prioritization use loaded lifecycle, deadline and provenance. No execution or AI reasoning is fabricated.</p></article><article><header><strong>Change awareness</strong>{truth(projection.changeAwareness.truth)}</header><p>{projection.changeAwareness.reason}</p></article><article><header><strong>Drawing intelligence</strong>{truth(projection.drawingIntelligence.truth)}</header><p>{projection.drawingIntelligence.reason}</p></article><section><h3>Communication truth</h3><p><b>OMNIRO Internal</b>{truth(can("notifications.read")?"REAL":"UNAVAILABLE")}<small>Recipient-scoped notifications only.</small></p>{["Email","WhatsApp Business","Telegram","Voice"].map(label=><p key={label}><b>{label}</b>{truth("UNAVAILABLE")}<small>No provider is connected.</small></p>)}</section></aside>
 </main>;
}
