import{renderToStaticMarkup}from"react-dom/server";
import{describe,expect,it}from"vitest";
import type{MaterialContract}from"@odls/contracts";
import type{MaterialConsumptionAnalysisDto,MaterialConsumptionDto,Session}from"./api.js";
import{MaterialConsumptionWorkspaceView}from"./omniro-material-consumption-workspace.js";

const reader:Session={accessToken:"x",refreshToken:"x",user:{id:"reader",email:"reader@example.test",displayName:"Reader"},permissions:["material_consumption.read","material_consumption.snapshots.read"]};
const editor:Session={...reader,permissions:[...reader.permissions,"material_consumption.edit","material_consumption.review","material_consumption.approve","material_catalog.read"]};
const run:MaterialConsumptionDto={id:"run-1",projectId:"project-1",code:"MC-001",title:"Bathroom tile material demand",revisionId:"revision-1",revisionNumber:2,status:"draft",version:4,workScopeSnapshotId:"scope-snapshot-1",normSnapshotId:"norm-snapshot-1",knowledgeVersionId:"knowledge-version-1",technologyVersionId:"technology-version-1",workItemId:"work-item-1",evaluatedParameters:{thickness_mm:12},workQuantity:20,workQuantityUnit:"m2",lines:[{id:"line-1",requirementCode:"TILE_ADHESIVE",engineeringRequirements:{classification:"C2"},environmentalRequirements:{countryCode:"PL"},formula:{kind:"linear",base:0,perWorkUnit:true,terms:[{parameter:"coverage",coefficient:8}]},normRevisionNumber:3,technologyVersionId:"technology-version-1",netQuantity:160,unitCode:"KG",selectionState:"unselected",wastePolicy:{},wasteQuantity:0,reserveQuantity:0,totalQuantity:160,packageCount:0,packageRemainder:0,availableQuantity:0,remainingQuantity:160,version:1}]};
const analysis:MaterialConsumptionAnalysisDto={runId:run.id,status:"draft",materialReady:false,missingRequirements:["TILE_ADHESIVE"],wasteQuantity:0,reserveQuantity:0,recommendations:[{code:"PRODUCT_SELECTION_REQUIRED",requirementCode:"TILE_ADHESIVE",recommendation:"Human selection is required; OMNIRO made no mutation."}],availabilityRisks:[{lineId:"line-1",remainingQuantity:160,unitCode:"KG"}],mutatedData:false,priceCalculationPerformed:false};
const material={id:"material-1",code:"ADH-C2",displayName:"Verified adhesive",measurementUnitCode:"KG",status:"active"}as MaterialContract;
const render=(options:Partial<Parameters<typeof MaterialConsumptionWorkspaceView>[0]>={})=>renderToStaticMarkup(<MaterialConsumptionWorkspaceView session={reader} run={run} materials={[]} analysis={analysis} busy={false} onSelect={async()=>{}} onReadiness={()=>{}} onApprove={()=>{}} onClose={()=>{}} {...options}/>);

describe("Material Consumption Command Center workspace",()=>{
 it("shows a truthful empty state without creating inferred data",()=>{const html=render({run:undefined,analysis:undefined});expect(html).toContain("No Material Consumption run exists for this project yet");expect(html).toContain("has not created or inferred a run")});
 it("renders exact backend quantities and source authority provenance",()=>{const html=render();expect(html).toContain("160 KG");expect(html).toContain("20 m2");expect(html).toContain("scope-snapshot-1");expect(html).toContain("norm-snapshot-1");expect(html).toContain("technology-version-1");expect(html).toContain("TILE_ADHESIVE")});
 it("keeps a reader read-only and states the missing authorities",()=>{const html=render();expect(html).not.toContain("SUBMIT HUMAN SELECTION");expect(html).not.toContain("CHECK AUTHORITATIVE READINESS");expect(html).toContain("material_consumption.edit is required");expect(html).toContain("material_consumption.review is required")});
 it("shows only backend-authorized selection and review controls",()=>{const html=render({session:editor,materials:[material]});expect(html).toContain("SUBMIT HUMAN SELECTION");expect(html).toContain("CHECK AUTHORITATIVE READINESS");expect(html).toContain("Verified adhesive");expect(html).toContain("backend validates product compatibility")});
 it("presents an approved immutable snapshot without commercial claims",()=>{const approved={...run,status:"approved"as const,lines:[{...run.lines[0],materialId:"material-1",selectionState:"selected"as const}]},html=render({run:approved,materials:[material],analysis:{...analysis,status:"approved",materialReady:true,missingRequirements:[],recommendations:[]},snapshot:{id:"snapshot-1",contentFingerprint:"a".repeat(64),schemaVersion:"material-consumption-v1",revisionNumber:2}});expect(html).toContain("Approved immutable quantity snapshot");expect(html).toContain("snapshot-1");expect(html).toContain("Price data: excluded");expect(html).toContain("Automatic product selection: not performed")});
 it("surfaces API errors without replacing them with demo data",()=>{const html=render({run:undefined,analysis:undefined,error:"Request failed: SERVICE_UNAVAILABLE"});expect(html).toContain('role="alert"');expect(html).toContain("SERVICE_UNAVAILABLE");expect(html).not.toContain("TILE_ADHESIVE")});
 it("shows the explicit approval boundary only to an approving human",()=>{const ready={...run,status:"ready_for_approval"as const,lines:[{...run.lines[0],materialId:"material-1",selectionState:"selected"as const}]};expect(render({run:ready,session:reader})).toContain("does not have material_consumption.approve");expect(render({run:ready,session:editor})).toContain("HUMAN APPROVAL · MATERIAL CONSUMPTION")});
});
