import type{ProjectContract}from"@odls/contracts";
import type{DesignProjectDto,RoomScanDto,Session,TechnicalAssignmentDto}from"./api.js";
import type{OmniroApprovalAdapter,OmniroEvidenceRef,OmniroExplanationAdapter,OmniroLifecycle,OmniroModuleRuntimeAdapter,OmniroModuleRuntimeState,OmniroRuntimeInput,OmniroRuntimeSnapshot}from"./omniro-module-contract.js";

export type BuildingSources={project:ProjectContract;scans:RoomScanDto[];assignments:TechnicalAssignmentDto[];designs:DesignProjectDto[];sourceFailures:string[]};
const current=<T extends{updatedAt?:string;id:string}>(items:T[])=>[...items].sort((a,b)=>(b.updatedAt??"").localeCompare(a.updatedAt??"")||b.id.localeCompare(a.id))[0];
const currentActionable=<T extends{updatedAt?:string;id:string;status:string}>(items:T[])=>[...items].sort((a,b)=>Number(b.status==="ready_for_approval")-Number(a.status==="ready_for_approval")||(b.updatedAt??"").localeCompare(a.updatedAt??"")||b.id.localeCompare(a.id))[0];
export const lifecycleFor=(status:string):OmniroLifecycle=>status==="approved"?"APPROVED":status==="completed"?"COMPLETE":status==="ready_for_approval"?"APPROVAL_REQUIRED":status==="review_required"?"WAIT":["rejected","failed"].includes(status)?"CONFLICT":["blocked","cancelled"].includes(status)?"BLOCKED":["capturing","collecting_information","in_review"].includes(status)?"PROCESS":"IDLE";
const evidence=(entityType:string,item:{id:string;version?:number},label:string):OmniroEvidenceRef=>({entityType,entityId:item.id,version:item.version,label});
const unavailable=(moduleId:string,projectId:string,reason:string):OmniroModuleRuntimeState=>({moduleId,projectId,truth:"UNAVAILABLE",lifecycle:"IDLE",availability:"unavailable",status:"unavailable",reason,evidence:[]});
const permitted=(session:Session,permission:string)=>session.permissions.includes(permission);

export const projectAdapter:OmniroModuleRuntimeAdapter<ProjectContract>={resolve(input){const project=(input.sources as BuildingSources).project;return{moduleId:"project",projectId:input.projectId,truth:"REAL",lifecycle:"FOCUS",availability:"available",status:project.status,reason:`Authoritative project record is ${project.status}.`,record:{entityType:"project",entityId:project.id,version:project.version},evidence:[evidence("project",project,project.projectNumber)],observed:project,updatedAt:String(project.updatedAt)}}};
const recordAdapter=<T extends{id:string;projectId?:string;status:string;version:number;updatedAt?:string}>(moduleId:string,key:keyof BuildingSources,permission:string,entityType:string,prioritizeApproval=false):OmniroModuleRuntimeAdapter<T>=>({resolve(input){if(!permitted(input.session,permission))return unavailable(moduleId,input.projectId,`Permission ${permission} is not available.`)as OmniroModuleRuntimeState<T>;const sources=input.sources as BuildingSources;if(sources.sourceFailures.includes(moduleId))return{...unavailable(moduleId,input.projectId,"The authoritative source could not be loaded."),truth:"PARTIAL",availability:"partial"}as OmniroModuleRuntimeState<T>;const candidates=((sources[key]as unknown)as T[]).filter(x=>x.projectId===input.projectId),item=prioritizeApproval?currentActionable(candidates):current(candidates);if(!item)return{moduleId,projectId:input.projectId,truth:"REAL",lifecycle:"IDLE",availability:"available",status:"not_started",reason:`No project-linked ${entityType} record exists.`,evidence:[]};return{moduleId,projectId:input.projectId,truth:"REAL",lifecycle:lifecycleFor(item.status),availability:"available",status:item.status,reason:`Authoritative ${entityType} record is ${item.status.replaceAll("_"," ")}.`,record:{entityType,entityId:item.id,version:item.version},evidence:[evidence(entityType,item,`${entityType} version ${item.version}`)],observed:item,updatedAt:item.updatedAt}}});
export const scannerAdapter=recordAdapter<RoomScanDto>("room-scanner","scans","room_scans.read","Room Scan",true);
export const assignmentAdapter=recordAdapter<TechnicalAssignmentDto>("technical-assignment","assignments","technical_assignments.read","Technical Assignment");
export const designAdapter=recordAdapter<DesignProjectDto>("design-project","designs","design_projects.read","Design Project");
export const unavailableAdapter=(moduleId:string,label:string):OmniroModuleRuntimeAdapter=>({resolve(input){return unavailable(moduleId,input.projectId,`${label} is not connected in Stage 2A.`)}});
export const explanationAdapter:OmniroExplanationAdapter={explain(state,snapshot){const downstream=state.moduleId==="room-scanner"?"technical-assignment":state.moduleId==="technical-assignment"?"design-project":undefined;return{currentModuleId:state.moduleId,source:state.evidence[0],destinationModuleId:downstream,reason:state.reason,evidence:state.evidence,waitingReason:["WAIT","APPROVAL_REQUIRED","BLOCKED"].includes(state.lifecycle)?state.reason:undefined,humanAction:state.lifecycle==="APPROVAL_REQUIRED"?"Open the authoritative workspace to review or approve.":undefined,nextAction:downstream?`Inspect ${snapshot.modules.get(downstream)?.status??"availability"}.`:undefined,classification:state.truth==="REAL"?"authoritative":state.truth==="DERIVED"?"derived":"unavailable",highlight:{moduleIds:[state.moduleId,...downstream?[downstream]:[]],flowIds:downstream?[`${state.moduleId}:${downstream}`]:[]}}}};
export const scannerApproval:OmniroApprovalAdapter={detect(state,session){if(state.lifecycle!=="APPROVAL_REQUIRED"||!state.evidence[0])return;return{source:state.evidence[0],readiness:"Ready for human approval",consequence:"The approved Scanner snapshot becomes authoritative for permitted downstream use.",permitted:session.permissions.includes("room_scans.approve"),permission:"room_scans.approve",downstreamModuleId:"technical-assignment",openWorkspaceId:"room-scanner",conflictPolicy:"reload-in-workspace"}}};
export const resolveRuntime=(projectId:string,session:Session,sources:BuildingSources,adapters:ReadonlyMap<string,OmniroModuleRuntimeAdapter>):OmniroRuntimeSnapshot=>{const input:OmniroRuntimeInput={projectId,session,sources: sources as unknown as Record<string,unknown>},modules=new Map<string,OmniroModuleRuntimeState>();for(const[id,adapter]of adapters)modules.set(id,adapter.resolve(input));return{projectId,modules,loadedAt:new Date().toISOString()}};
