import type{Session}from"./api.js";
import type{OmniroTruth}from"./omniro-module-contract.js";

export type RoleWorkspaceCategory="executive"|"finance"|"commercial"|"operations"|"project"|"engineering"|"compliance"|"people";
export type RoleWorkspaceStatus="active"|"registered";
export type RoleWorkspaceCapability={id:string;label:string;requiredPermissions:readonly string[];truth:OmniroTruth;reason:string};
export type RoleWorkspaceDefinition={
 roleId:string;
 label:string;
 category:RoleWorkspaceCategory;
 requiredPermissions:readonly string[];
 availableModules:readonly string[];
 primaryActions:readonly string[];
 attentionSources:readonly string[];
 assistantCapabilities:readonly RoleWorkspaceCapability[];
 communicationCapabilities:readonly RoleWorkspaceCapability[];
 temporaryAssignmentSupport:boolean;
 status:RoleWorkspaceStatus;
};
export type ResolvedRoleWorkspace={definition:RoleWorkspaceDefinition;truth:OmniroTruth;reason:string;actualActorId:string;actualActorName:string};

export class OmniroRoleWorkspaceRegistry{
 readonly definitions:readonly RoleWorkspaceDefinition[];
 readonly byId:ReadonlyMap<string,RoleWorkspaceDefinition>;
 constructor(items:readonly RoleWorkspaceDefinition[]){const map=new Map<string,RoleWorkspaceDefinition>();for(const item of items){if(map.has(item.roleId))throw new Error(`Duplicate OMNIRO role workspace: ${item.roleId}`);map.set(item.roleId,Object.freeze({...item}))}this.definitions=Object.freeze([...map.values()]);this.byId=map}
 get(roleId:string){return this.byId.get(roleId)}
 resolve(roleId:string,session:Session):ResolvedRoleWorkspace{const definition=this.get(roleId);if(!definition){const unavailable:RoleWorkspaceDefinition={roleId,label:"Unknown workspace",category:"operations",requiredPermissions:[],availableModules:[],primaryActions:[],attentionSources:[],assistantCapabilities:[],communicationCapabilities:[],temporaryAssignmentSupport:false,status:"registered"};return{definition:unavailable,truth:"UNAVAILABLE",reason:"Unknown role workspace.",actualActorId:session.user.id,actualActorName:session.user.displayName}}const allowed=definition.status==="active"&&definition.requiredPermissions.every(permission=>session.permissions.includes(permission));return{definition,truth:allowed?"REAL":"UNAVAILABLE",reason:allowed?"Workspace is projected for the authenticated actor from existing permissions.":definition.status!=="active"?"Role workspace is registered for future implementation.":"The authenticated actor does not hold the required base permission.",actualActorId:session.user.id,actualActorName:session.user.displayName}}
}

const unavailableAssistant=(id:string,label:string,reason:string):RoleWorkspaceCapability=>({id,label,requiredPermissions:[],truth:"UNAVAILABLE",reason});
const future=(roleId:string,label:string,category:RoleWorkspaceCategory):RoleWorkspaceDefinition=>({roleId,label,category,requiredPermissions:[],availableModules:[],primaryActions:[],attentionSources:[],assistantCapabilities:[],communicationCapabilities:[],temporaryAssignmentSupport:false,status:"registered"});

export const roleWorkspaceRegistry=new OmniroRoleWorkspaceRegistry([
 {roleId:"director",label:"Director / Owner",category:"executive",requiredPermissions:["projects.read"],availableModules:["project","room-scanner","technical-assignment","design-project","technology","work-scope","engineering-norms","material-consumption","regional-pricing","company-price-book","commercial-estimate"],primaryActions:["review-priority-actions","open-domain-approval","open-source-evidence","switch-project-context"],attentionSources:["module-lifecycle","tasks","documents","notifications","finance"],assistantCapabilities:[{id:"orchestrator",label:"Orchestrator",requiredPermissions:["projects.read"],truth:"DERIVED",reason:"Deterministic explanation from registered authorities and evidence."},{id:"ai-secretary",label:"AI Secretary",requiredPermissions:["projects.read"],truth:"PARTIAL",reason:"Deterministic briefing is available; free-form company reasoning is not connected."},{id:"economic-analyst",label:"Economic Analyst",requiredPermissions:["commercial_estimates.read"],truth:"PARTIAL",reason:"Project commercial calculations are available; company accounting conclusions are not inferred."},unavailableAssistant("legal-advisor","Legal Advisor","No verified external legal intelligence source is connected.")],communicationCapabilities:[{id:"internal",label:"OMNIRO Internal",requiredPermissions:["notifications.read"],truth:"REAL",reason:"Existing in-app notifications are connected."},unavailableAssistant("email","Email","No email provider is connected."),unavailableAssistant("whatsapp","WhatsApp Business","No WhatsApp provider is connected."),unavailableAssistant("telegram","Telegram","No Telegram provider is connected."),unavailableAssistant("voice","Voice","No voice communication provider is connected.")],temporaryAssignmentSupport:false,status:"active"},
 future("executive-assistant","Executive Assistant","executive"),
 {roleId:"accountant",label:"Accountant",category:"finance",requiredPermissions:["finance.read"],availableModules:["project","company-price-book","commercial-estimate"],primaryActions:["review-accounting-inbox","open-finance-record","open-source-document","open-existing-domain-approval"],attentionSources:["finance","documents","notifications","tasks","module-lifecycle"],assistantCapabilities:[{id:"orchestrator",label:"Orchestrator",requiredPermissions:["finance.read"],truth:"DERIVED",reason:"Deterministic explanation from loaded accounting records and registered authorities."},{id:"accounting-assistant",label:"Accounting Assistant",requiredPermissions:["finance.read"],truth:"PARTIAL",reason:"Grounded prioritization is available; autonomous accounting decisions are not connected."},{id:"economic-analyst",label:"Economic Analyst",requiredPermissions:["commercial_estimates.read"],truth:"PARTIAL",reason:"Project Commercial Estimate calculations can be opened; company accounting conclusions are not inferred."},unavailableAssistant("tax-advisor","Tax / Legal Advisor","No verified tax-law or legal intelligence source is connected.")],communicationCapabilities:[{id:"internal",label:"OMNIRO Internal",requiredPermissions:["notifications.read"],truth:"REAL",reason:"Existing recipient-scoped in-app notifications are connected."},unavailableAssistant("email","Email","No email provider is connected."),unavailableAssistant("ksef","KSeF","No KSeF provider or submission authority is connected."),unavailableAssistant("bank","Bank feed","No bank provider is connected."),unavailableAssistant("voice","Voice","No voice communication provider is connected.")],temporaryAssignmentSupport:false,status:"active"},
 future("finance-manager","Finance Manager","finance"),future("tax-specialist","Tax Specialist","finance"),future("economic-analyst","Economic Analyst","commercial"),future("legal-counsel","Legal Counsel","compliance"),future("sales-manager","Sales Manager","commercial"),future("marketing-manager","Marketing Manager","commercial"),future("hr-manager","HR Manager","people"),future("procurement-manager","Procurement Manager","operations"),future("operations-manager","Operations Manager","operations"),
 {roleId:"project-manager",label:"Project Manager",category:"project",requiredPermissions:["projects.read"],availableModules:["project","room-scanner","work-scope","engineering-norms","material-consumption","regional-pricing","company-price-book","commercial-estimate"],primaryActions:["review-project-attention","open-project-task","open-existing-domain-approval","switch-project-context"],attentionSources:["module-lifecycle","tasks","documents","notifications","finance"],assistantCapabilities:[{id:"orchestrator",label:"Orchestrator",requiredPermissions:["projects.read"],truth:"DERIVED",reason:"Deterministic project explanation from registered authorities and provenance."},{id:"project-assistant",label:"Project Assistant",requiredPermissions:["projects.read"],truth:"PARTIAL",reason:"Grounded briefing and prioritization are available; autonomous execution is not connected."},{id:"engineering-assistant",label:"Engineering Assistant",requiredPermissions:["engineering_norms.read"],truth:"PARTIAL",reason:"Existing Engineering Norm authority can be opened; drawing intelligence is not connected."}],communicationCapabilities:[{id:"internal",label:"OMNIRO Internal",requiredPermissions:["notifications.read"],truth:"REAL",reason:"Existing recipient-scoped in-app notifications are connected."},unavailableAssistant("email","Email","No email provider is connected."),unavailableAssistant("whatsapp","WhatsApp Business","No WhatsApp provider is connected."),unavailableAssistant("telegram","Telegram","No Telegram provider is connected."),unavailableAssistant("voice","Voice","No voice communication provider is connected.")],temporaryAssignmentSupport:false,status:"active"},
 {roleId:"site-manager",label:"Site Manager / Foreman",category:"project",requiredPermissions:["projects.read"],availableModules:["project","room-scanner","work-scope","engineering-norms","material-consumption"],primaryActions:["review-site-today","open-project-task","open-source-evidence","escalate-existing-authority","switch-project-context"],attentionSources:["module-lifecycle","tasks","documents","notifications"],assistantCapabilities:[{id:"orchestrator",label:"Orchestrator",requiredPermissions:["projects.read"],truth:"DERIVED",reason:"Deterministic site briefing from loaded tasks, authority lifecycle and provenance."},{id:"site-assistant",label:"Site Assistant",requiredPermissions:["tasks.read"],truth:"PARTIAL",reason:"Grounded grouping and briefing are available; autonomous site execution is not connected."},{id:"engineering-assistant",label:"Engineering Assistant",requiredPermissions:["engineering_norms.read"],truth:"PARTIAL",reason:"Existing Engineering Norm authority can be opened; drawing intelligence is not connected."},unavailableAssistant("communication-agent","Communication Agent","Only recipient-scoped internal notifications are connected; external channels are unavailable.")],communicationCapabilities:[{id:"internal",label:"OMNIRO Internal",requiredPermissions:["notifications.read"],truth:"REAL",reason:"Existing recipient-scoped in-app notifications are connected."},unavailableAssistant("email","Email","No email provider is connected."),unavailableAssistant("whatsapp","WhatsApp Business","No WhatsApp provider is connected."),unavailableAssistant("telegram","Telegram","No Telegram provider is connected."),unavailableAssistant("voice","Voice Bridge","No multilingual voice provider is connected; calls are not implemented or stored.")],temporaryAssignmentSupport:false,status:"active"},future("engineer","Engineer","engineering"),future("architect","Architect","engineering"),future("estimator","Estimator","commercial"),future("hse","HSE","compliance"),future("quality-control","Quality Control","compliance"),
 {roleId:"worker",label:"Worker",category:"operations",requiredPermissions:["tasks.read","tasks.self_update"],availableModules:["project","room-scanner"],primaryActions:["review-assigned-today","start-assigned-task","attach-task-proof","submit-for-human-review","report-task-problem"],attentionSources:["tasks","documents","notifications","task-problems"],assistantCapabilities:[{id:"orchestrator",label:"Orchestrator",requiredPermissions:["tasks.read"],truth:"DERIVED",reason:"Deterministic task explanation from assigned task state, evidence and provenance."},{id:"ai-secretary",label:"AI Secretary",requiredPermissions:["tasks.read"],truth:"PARTIAL",reason:"Grounded task guidance is available; approval, schedule and commercial authority remain human."}],communicationCapabilities:[{id:"internal",label:"OMNIRO Internal",requiredPermissions:["notifications.read"],truth:"REAL",reason:"Recipient-scoped notifications are connected."},unavailableAssistant("correspondence","Project correspondence","No assignment-scoped communication provider is connected."),unavailableAssistant("voice","Voice translator","No ephemeral multilingual voice provider is connected; calls are not recorded or stored.")],temporaryAssignmentSupport:false,status:"active"},
 {roleId:"client",label:"Client",category:"project",requiredPermissions:["client_workspace.read"],availableModules:["project","room-scanner","commercial-estimate"],primaryActions:["review-client-project","open-published-document","review-client-estimate","submit-client-request","decide-client-approval"],attentionSources:["client-approvals","client-requests","documents","invoices","notifications"],assistantCapabilities:[{id:"orchestrator",label:"Orchestrator",requiredPermissions:["client_workspace.read"],truth:"DERIVED",reason:"Deterministic explanation from the client's permitted project records."},{id:"ai-secretary",label:"AI Secretary",requiredPermissions:["client_workspace.read"],truth:"PARTIAL",reason:"Integration point can open permitted objects; free-form and voice command execution are not connected."}],communicationCapabilities:[{id:"internal",label:"OMNIRO Internal",requiredPermissions:["notifications.read"],truth:"REAL",reason:"Existing recipient-scoped notifications are connected."},unavailableAssistant("correspondence","Project correspondence","No verified project correspondence backend is connected."),unavailableAssistant("voice","Voice Bridge","Ephemeral translation provider is unavailable; voice is never recorded or stored."),unavailableAssistant("external","External channels","Email, WhatsApp and Telegram providers are not connected.")],temporaryAssignmentSupport:false,status:"active"}
]);
