import{renderToStaticMarkup}from"react-dom/server";
import{describe,expect,it}from"vitest";
import type{ProjectContract}from"@odls/contracts";
import type{Session}from"./api.js";
import{OmniroOperatingEnvironment}from"./omniro-operating-environment.js";
import{OmniroDataFlowVisualRegistry,dataFlowVisualRegistry,environmentHash,parseEnvironmentRoute,productRegistry,roleRegistry}from"./omniro-operating-environment-model.js";
import type{OmniroRuntimeSnapshot}from"./omniro-module-contract.js";

const project:ProjectContract={id:"p1",tenantId:"t1",clientId:"c1",propertyId:"pr1",financialOwnerLegalEntityId:"l1",projectManagerId:null,projectNumber:"PRJ-1",name:"Verified Project",description:null,status:"active",startDate:null,expectedCompletionDate:null,actualCompletionDate:null,currencyCode:"EUR",estimatedBudget:null,approvedBudget:null,contractValue:null,paymentStatus:"not_required",billingCustomerReference:null,externalPaymentCustomerReference:null,version:1,createdAt:"2026-01-01",updatedAt:"2026-01-01",archivedAt:null};
const session:Session={accessToken:"a",refreshToken:"r",user:{id:"u1",email:"director@example.com",displayName:"Real Director"},permissions:["projects.read"]};
const state=(moduleId:string,truth:"REAL"|"UNAVAILABLE"="REAL")=>({moduleId,projectId:project.id,truth,lifecycle:"IDLE"as const,availability:truth==="REAL"?"available"as const:"unavailable"as const,status:truth==="REAL"?"ready":"unavailable",reason:truth==="REAL"?"Registered authority is loaded.":"Authority is unavailable.",evidence:[]});
const runtime:OmniroRuntimeSnapshot={projectId:project.id,loadedAt:"2026-01-01",modules:new Map([["project",state("project")],["room-scanner",state("room-scanner")],["engineering-norms",state("engineering-norms")],["material-consumption",state("material-consumption")],["regional-pricing",state("regional-pricing")],["company-price-book",state("company-price-book")],["commercial-estimate",state("commercial-estimate")]])};
const callbacks={onLayer:()=>undefined,onProject:()=>undefined,onModule:()=>undefined,onWorkspace:()=>undefined};

describe("OMNIRO three-layer operating environment",()=>{
 it("keeps new layer routes separate from protected project deep links",()=>{expect(parseEnvironmentRoute("#omniro/universe")).toEqual({layer:"universe"});expect(parseEnvironmentRoute("#omniro/building")).toEqual({layer:"building"});expect(parseEnvironmentRoute("#omniro/role/director")).toEqual({layer:"role",roleId:"director"});expect(parseEnvironmentRoute("#omniro/project/p1/focus/project")).toBeUndefined();expect(environmentHash({layer:"role",roleId:"director"})).toBe("#omniro/role/director")});
 it("registers one real Product World without fabricating future products",()=>{expect(productRegistry.get("building")?.resolve([project]).truth).toBe("REAL");expect(productRegistry.get("finance")?.resolve([project]).truth).toBe("UNAVAILABLE")});
 it("projects a role from actor permissions while keeping future roles unavailable",()=>{expect(roleRegistry.resolve("director",session).truth).toBe("REAL");expect(roleRegistry.resolve("director",{...session,permissions:[]}).truth).toBe("UNAVAILABLE");expect(roleRegistry.resolve("accountant",session).truth).toBe("UNAVAILABLE")});
 it("locks canonical flow numbers and colors",()=>{expect(dataFlowVisualRegistry.definitions.map(item=>item.id)).toEqual(["01","02","03","04","05","06","07","08"]);expect(new Set(dataFlowVisualRegistry.definitions.map(item=>item.color)).size).toBe(8);expect(()=>new OmniroDataFlowVisualRegistry([dataFlowVisualRegistry.definitions[0],dataFlowVisualRegistry.definitions[0]])).toThrow(/Duplicate data flow number/)});
 it("activates flow lanes from runtime authorities rather than presentation labels",()=>{const projected=dataFlowVisualRegistry.project(runtime,[]);expect(projected.find(item=>item.id==="02")?.active).toBe(true);expect(projected.find(item=>item.id==="04")?.active).toBe(false);expect(projected.find(item=>item.id==="08")?.truth).toBe("UNAVAILABLE")});
 it.each(["universe","building","role"]as const)("renders the %s layer with truthful semantics",layer=>{const html=renderToStaticMarkup(<OmniroOperatingEnvironment session={session} projects={[project]} project={project} runtime={runtime} flows={[]} layer={layer} {...callbacks}/>);expect(html).toContain("Operating Environment, Not a Website");expect(html).toContain("Real Director");expect(html).toContain(layer==="universe"?"OMNIRO Universe":layer==="building"?"OMNIRO Building":"Director Workspace")});
 it("exposes unavailable communication and assistant limitations",()=>{const html=renderToStaticMarkup(<OmniroOperatingEnvironment session={session} projects={[project]} project={project} runtime={runtime} flows={[]} layer="role" {...callbacks}/>);expect(html).toContain("No external communication provider is connected");expect(html).toContain("WhatsApp · UNAVAILABLE");expect(html).toContain("Voice secretary · UNAVAILABLE")});
});
