import{useEffect,useMemo,useState}from"react";
import{capabilities,copy,demonstratedCapabilities,stateLabel,type PublicLocale}from"./public-registry.js";

const sections=["building","why","learning","galaxy","platform","vision"] as const;
const lineage=[
 ["Final estimate","€4,620.00","Approved estimate · revision 3"],
 ["Paint material","€1,284.40","Regional price list PL-2026 · valid 2026"],
 ["Material quantity","45.07 L","126.42 m² × 0.34 L/m² × 1.048 waste"],
 ["Consumption norm","0.34 L/m²","Interior paint · two coats · Norm v4.2"],
 ["Wall area","126.42 m²","Approved Room Passport snapshot"],
 ["Original evidence","18 measurements","Scanner records and referenced photos"],
] as const;

function Brand(){return <a className="public-brand" href="#public-top" aria-label="OMNIRA home"><img src="/brand/omnira-logo-dark.svg" alt="OMNIRA"/></a>}
function Status({state}:{state:(typeof capabilities)[number]["state"]}){return <span className={`public-status status-${state}`}>{stateLabel[state]}</span>}

function Birth({onComplete,locale}:{onComplete:()=>void;locale:PublicLocale}){
 const [step,setStep]=useState(0),[sound,setSound]=useState(false);const text=copy[locale];
 useEffect(()=>{const timer=window.setInterval(()=>setStep(current=>{if(current>=5){window.clearInterval(timer);onComplete();return current}return current+1}),900);return()=>window.clearInterval(timer)},[onComplete]);
 const inviteSound=()=>{setSound(true);const AudioContextClass=window.AudioContext; if(!AudioContextClass)return;const ctx=new AudioContextClass();[220,277,330].forEach((frequency,index)=>{const oscillator=ctx.createOscillator(),gain=ctx.createGain();oscillator.frequency.value=frequency;gain.gain.setValueAtTime(.0001,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.035,ctx.currentTime+.05+index*.12);gain.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+.9+index*.14);oscillator.connect(gain).connect(ctx.destination);oscillator.start(ctx.currentTime+index*.12);oscillator.stop(ctx.currentTime+1.2+index*.14)});};
 return <div className="birth" role="dialog" aria-modal="true" aria-label="OMNIRA introduction"><button className="skip" onClick={onComplete}>{text.skip}</button><div className="birth-stage" data-step={step}><span className="birth-point"/><div className="birth-mark" aria-hidden="true">O</div><p aria-live="polite">{text.birth[Math.min(2,Math.floor(step/2))]}</p><small>{sound?"Symbolic soundscape playing":"The experience starts silently."}</small></div><button className="sound-invite" aria-pressed={sound} onClick={inviteSound}>◉ {sound?"Sound on":"Play symbolic soundscape"}</button></div>
}

function OmniroPresence(){return <div className="public-omniro" role="img" aria-label="OMNIRO, the orchestrating intelligence"><span className="presence-orbit"/><span className="presence-core">O</span><small>OMNIRO · present, not autonomous</small></div>}

function Explainability({locale}:{locale:PublicLocale}){const[open,setOpen]=useState(0);return <section id="why" className="public-section explain"><header><p className="eyebrow">Engineering causality chain</p><h2>{copy[locale].why}</h2><p>Explore an illustrative painting estimate. The values demonstrate the implemented lineage model; they are not a customer quote.</p></header><div className="lineage"><div className="lineage-value"><strong>{lineage[0][1]}</strong><span>Illustrative painting estimate</span></div>{lineage.map((item,index)=><article key={item[0]} className={index<=open?"revealed":""}><button aria-expanded={index<=open} onClick={()=>setOpen(index===open&&open>0?open-1:Math.min(lineage.length-1,index+1))}><span><small>0{index+1}</small>{item[0]}</span><strong>{item[1]}</strong></button>{index<=open&&<p>{item[2]}</p>}</article>)}</div><p className="demo-note">Illustrative data · not connected to a live project · formulas and source types mirror implemented causality contracts.</p></section>}

function Building(){const steps=demonstratedCapabilities.filter(item=>["room-scanner","technical-assignment","design-project","work-catalog","materials","regional-pricing","estimate"].includes(item.id));return <section id="building" className="public-section building"><header><p className="eyebrow">A building becomes knowledge</p><h2>From captured room to explainable commercial decision.</h2></header><div className="building-story"><div className="room-model" aria-label="Conceptual wireframe room"><span/><span/><span/><i>126.42 m²</i></div><ol>{steps.map((item,index)=><li key={item.id}><span>{String(index+1).padStart(2,"0")}</span><div><h3>{item.name}</h3><p>{item.summary}</p></div><Status state={item.state}/></li>)}</ol></div></section>}

function Learning({locale}:{locale:PublicLocale}){return <section id="learning" className="public-section learning"><header><p className="eyebrow">How OMNIRA learns</p><h2>{copy[locale].learning}</h2></header><div className="learning-grid">{[["Documents","OCR and extraction remain reviewable."],["Experts","Approval records preserve human accountability."],["Norms","Versioned rules make knowledge reproducible."],["Projects","Snapshots prevent history from being silently rewritten."]].map(([title,body])=><article key={title}><span className="knowledge-node"/><h3>{title}</h3><p>{body}</p></article>)}</div><div className="learning-flow"><span>Evidence</span><i>→</i><span>Review</span><i>→</i><span>Approved knowledge</span><i>→</i><span>Explainable output</span></div></section>}

function Galaxy(){const groups=["construction","knowledge","finance","operations","future"] as const;return <section id="galaxy" className="public-section galaxy"><header><p className="eyebrow">One platform · governed domains</p><h2>The galaxy shows both what exists and what does not.</h2></header><div className="galaxy-map"><div className="galaxy-core"><strong>OMNIRA</strong><small>shared identity · evidence · approvals</small></div>{groups.map(group=><article className={`galaxy-group galaxy-${group}`} key={group}><h3>{group}</h3>{capabilities.filter(item=>item.galaxy===group).map(item=><details key={item.id}><summary><span>{item.name}</span><Status state={item.state}/></summary><p>{item.summary}</p>{item.evidence.length>0?<ul>{item.evidence.map(e=><li key={e}>{e}</li>)}</ul>:<p>No operational evidence is claimed.</p>}</details>)}</article>)}</div></section>}

function Platform(){return <section id="platform" className="public-section platform"><header><p className="eyebrow">For operators and investors</p><h2>A platform boundary you can inspect.</h2></header><div className="platform-grid"><article><h3>Operational foundation</h3><p>Tenant boundaries, permissions, approval lifecycles, immutable snapshots and audit events support governed work.</p></article><article><h3>Economic model</h3><p>Catalogs, norms, regional pricing and estimate versions create reusable construction knowledge without presenting invented traction.</p></article><article><h3>Trust boundary</h3><p>Public demonstrations use illustrative data. Operational records stay behind authenticated, permission-aware routes.</p></article><article><h3>Current limit</h3><p>Scheduling, live weather risk and robotics are not represented as operational capabilities.</p></article></div></section>}

function Privacy({onClose}:{onClose:()=>void}){const[analytics,setAnalytics]=useState(()=>localStorage.getItem("omnira.public.analytics")==="true");return <div className="privacy-panel" role="dialog" aria-modal="true" aria-labelledby="privacy-title"><h2 id="privacy-title">Privacy choices</h2><p>Essential preferences keep your language and introduction choice on this device. Optional analytics are off by default and no analytics provider is connected.</p><label><input type="checkbox" checked disabled/> Essential preferences</label><label><input type="checkbox" checked={analytics} onChange={event=>{setAnalytics(event.target.checked);localStorage.setItem("omnira.public.analytics",String(event.target.checked))}}/> Allow optional analytics if a provider is connected later</label><button onClick={onClose}>Save choices</button></div>}

export function PublicExperience({onSignIn}:{onSignIn:()=>void}){
 const[locale,setLocale]=useState<PublicLocale>(()=>typeof localStorage==="undefined"?"en":(localStorage.getItem("omnira.public.locale")as PublicLocale)||"en"),[introduced,setIntroduced]=useState(()=>typeof localStorage!=="undefined"&&localStorage.getItem("omnira.public.intro")==="seen"),[privacy,setPrivacy]=useState(false),[menu,setMenu]=useState(false);const text=copy[locale];
 const complete=useMemo(()=>()=>{localStorage.setItem("omnira.public.intro","seen");setIntroduced(true)},[]);
 useEffect(()=>{document.documentElement.lang=locale;document.title="OMNIRA — Explainable AI for real-world engineering"},[locale]);
 return <div className="public-site" id="public-top">{!introduced&&<Birth onComplete={complete} locale={locale}/>}<a className="skip-link" href="#public-main">Skip to content</a><header className="public-nav"><Brand/><button className="menu-button" aria-expanded={menu} onClick={()=>setMenu(x=>!x)}>Menu</button><nav aria-label="Public navigation" className={menu?"is-open":""}>{sections.map((id,index)=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{text.nav[index]}</a>)}</nav><label className="locale"><span className="sr-only">Language</span><select aria-label="Language" value={locale} onChange={event=>{const next=event.target.value as PublicLocale;localStorage.setItem("omnira.public.locale",next);setLocale(next)}}>{(["en","nl","de","pl","ru","uk"]as const).map(code=><option value={code} key={code}>{code.toUpperCase()}</option>)}</select></label><button className="nav-signin" onClick={onSignIn}>Sign in</button></header><main id="public-main"><section className="public-hero"><div className="star-field" aria-hidden="true"/><OmniroPresence/><div className="hero-copy"><p className="eyebrow">OMNIRA · AI Business Operating System</p><h1>{text.hero}</h1><p>{text.sub}</p><div className="hero-actions"><a className="primary-action" href="#building">{text.enter}</a><button onClick={onSignIn}>Open operational platform</button></div><small>Public experience · illustrative demonstrations are explicitly marked</small></div><div className="energy-streams" aria-hidden="true"><span/><span/><span/></div></section><Building/><Explainability locale={locale}/><Learning locale={locale}/><Galaxy/><Platform/><section id="vision" className="public-section closing"><OmniroPresence/><p className="eyebrow">Vision, stated as vision</p><h2>Every engineering decision should be explainable.</h2><p>OMNIRA is building toward a future where every euro, kilogram, square metre, labour hour and recommendation can be traced to verified evidence.</p><button className="primary-action" onClick={onSignIn}>Sign in to the operational platform</button></section></main><footer><Brand/><p>OMNIRA · AI Business Operating System</p><nav aria-label="Legal and trust"><button onClick={()=>setPrivacy(true)}>{text.privacy}</button><a href="#platform">Platform boundary</a><a href="mailto:hello@omnira.example">Contact</a></nav><small>© 2026 OMNIRA. Product states on this site are derived from the public capability registry.</small></footer>{privacy&&<Privacy onClose={()=>setPrivacy(false)}/>}</div>
}
