import {afterAll,beforeAll,describe,expect,it} from "vitest";
import {buildServer} from "../src/server.js";

const enabled=Boolean(process.env.DATABASE_URL);
describe.skipIf(!enabled)("analytics PostgreSQL integration",()=>{
 const app=buildServer();let admin="",employee="",second="";
 beforeAll(async()=>{const login=async(tenantSlug:string,email:string)=>(await app.inject({method:"POST",url:"/api/v1/auth/login",payload:{tenantSlug,email,password:"DemoPassword!2026"}})).json().data.accessToken;admin=await login("demo","admin@demo.odls");employee=await login("demo","employee@demo.odls");second=await login("second","admin@second.odls");});
 afterAll(()=>app.close());
 const get=(url:string,token=admin)=>app.inject({method:"GET",url,headers:{authorization:`Bearer ${token}`}});
 it("returns executive, health and all report models without 5xx",async()=>{for(const url of ["/api/v1/dashboard/executive?range=7","/api/v1/dashboard/project-health","/api/v1/reports/accounts-receivable?overdue=true","/api/v1/reports/revenue?groupBy=client","/api/v1/reports/expenses?groupBy=project","/api/v1/reports/profitability","/api/v1/reports/tasks","/api/v1/reports/deadlines","/api/v1/reports/workload","/api/v1/reports/documents","/api/v1/reports/activity"]){const response=await get(url);expect(response.statusCode,url).toBe(200);}});
 it("enforces underlying role visibility and export authorization",async()=>{expect((await get("/api/v1/reports/documents",employee)).statusCode).toBe(200);expect((await get("/api/v1/reports/accounts-receivable",employee)).statusCode).toBe(403);expect((await get("/api/v1/reports/documents/export",employee)).statusCode).toBe(403);const exportResponse=await get("/api/v1/reports/workload/export");expect(exportResponse.statusCode).toBe(200);expect(exportResponse.headers["content-type"]).toContain("text/csv");expect(exportResponse.body.charCodeAt(0)).toBe(0xfeff);});
 it("keeps tenant report rows isolated",async()=>{const demo=(await get("/api/v1/dashboard/project-health")).json().data,other=(await get("/api/v1/dashboard/project-health",second)).json().data,ids=new Set(demo.map((x:any)=>x.id));expect(other.some((x:any)=>ids.has(x.id))).toBe(false);});
 it("applies AR filters, sorting and stable pagination",async()=>{const first=(await get("/api/v1/reports/accounts-receivable?range=90&pageSize=2&sortBy=outstanding&sortOrder=desc")).json();expect(first.data.length).toBeLessThanOrEqual(2);expect(first.pagination.pageSize).toBe(2);if(first.data.length>1)expect(Number(first.data[0].outstanding)).toBeGreaterThanOrEqual(Number(first.data[1].outstanding));const row=first.data[0];if(row){for(const filter of [`clientId=${row.clientId}`,`projectId=${row.projectId}`,`currencyCode=${row.currencyCode}`])if(!filter.endsWith("=null"))expect((await get(`/api/v1/reports/accounts-receivable?range=90&${filter}`)).json().data.every((x:any)=>filter.startsWith("client")?x.clientId===row.clientId:filter.startsWith("project")?x.projectId===row.projectId:x.currencyCode===row.currencyCode)).toBe(true);}expect((await get("/api/v1/reports/accounts-receivable?sortBy=title")).statusCode).toBe(400);});
 it("applies profitability, deadline, workload and document filters",async()=>{const profit=(await get("/api/v1/reports/profitability?range=90&pageSize=1&sortBy=margin&sortOrder=asc")).json();expect(profit.pagination.pageSize).toBe(1);if(profit.data[0])expect((await get(`/api/v1/reports/profitability?range=90&projectId=${profit.data[0].projectId}&currencyCode=${profit.data[0].currencyCode}`)).json().data.every((x:any)=>x.projectId===profit.data[0].projectId)).toBe(true);const deadlines=(await get("/api/v1/reports/deadlines?range=90&pageSize=1&sortBy=dueDate&sortOrder=asc")).json();if(deadlines.data[0])expect((await get(`/api/v1/reports/deadlines?range=90&projectId=${deadlines.data[0].projectId}`)).json().data.every((x:any)=>x.projectId===deadlines.data[0].projectId)).toBe(true);const workload=(await get("/api/v1/reports/workload?range=90&pageSize=2&sortBy=openCount&sortOrder=desc")).json();expect(workload.data.length).toBeLessThanOrEqual(2);const docs=(await get("/api/v1/reports/documents?range=90&pageSize=1&sortBy=filename&sortOrder=asc")).json();if(docs.data[0])expect((await get(`/api/v1/reports/documents?range=90&category=${docs.data[0].category}`)).json().data.every((x:any)=>x.category===docs.data[0].category)).toBe(true);});
 it("applies every advertised grouping and activity filter",async()=>{for(const groupBy of ["month","client","project"])expect((await get(`/api/v1/reports/revenue?range=90&groupBy=${groupBy}`)).statusCode).toBe(200);for(const groupBy of ["month","category","project"])expect((await get(`/api/v1/reports/expenses?range=90&groupBy=${groupBy}`)).statusCode).toBe(200);const activity=(await get("/api/v1/reports/activity?range=90&pageSize=1")).json(),row=activity.data[0];if(row){const filtered=(await get(`/api/v1/reports/activity?range=90&actorId=${row.actorId}&domain=${row.entityType}`)).json().data;expect(filtered.every((x:any)=>x.actorId===row.actorId&&x.entityType===row.entityType)).toBe(true);}});
 it("keeps CSV filters and ordering aligned with visible rows",async()=>{const report=(await get("/api/v1/reports/accounts-receivable?range=90&overdue=true&sortBy=outstanding&sortOrder=desc&pageSize=1")).json(),csvResponse=await get("/api/v1/reports/accounts-receivable/export?range=90&overdue=true&sortBy=outstanding&sortOrder=desc");expect(csvResponse.statusCode).toBe(200);expect(csvResponse.body).toContain('"invoiceNumber","clientName","projectName"');if(report.data[0])expect(csvResponse.body).toContain(`"${report.data[0].invoiceNumber}"`);});
});
