import{describe,expect,it}from"vitest";import{analyseConstructionProject,projectHealth,type AssistantAnalysisInput}from"../src/domain/construction-assistant/construction-assistant-rules.js";
const base=(patch:Partial<AssistantAnalysisInput>={}):AssistantAnalysisInput=>({today:"2026-08-06",project:{id:"p",status:"active",expectedCompletionDate:"2026-09-01"},tasks:[],approvedScan:{id:"snapshot",content:{measurements:[{id:"m",confidence:1}],attachments:[{id:"a"}],observations:[{id:"o"}]}},weather:[],photoTags:[],...patch});
describe("construction assistant deterministic rules",()=>{
 it("reports only verified overdue facts and never mutates input",()=>{const input=base({tasks:[{id:"t",title:"Critical path",status:"blocked",dueDate:"2026-08-05"}]});const before=structuredClone(input),signals=analyseConstructionProject(input);expect(signals[0]).toMatchObject({key:"tasks-overdue",severity:"critical",probability:1,confidence:1});expect(signals[0].evidence[0]).toMatchObject({source:"task",id:"t"});expect(input).toEqual(before)});
 it("recommends protection when rain conflicts with verified exterior work",()=>{const signals=analyseConstructionProject(base({tasks:[{id:"t",title:"Facade preparation",status:"todo",dueDate:"2026-08-08"}],weather:[{id:"w",forecastAt:"2026-08-07T09:00:00.000Z",precipitationProbability:.92,condition:"Rain",source:"verified-provider"}]}));expect(signals.find(x=>x.key==="rain-exterior")).toMatchObject({riskType:"weather_conflict",severity:"high",probability:.92});expect(signals.find(x=>x.key==="rain-exterior")?.reason).toContain("verified forecast")});
 it("combines manual wet-wall evidence and humidity without image recognition",()=>{const signals=analyseConstructionProject(base({tasks:[{id:"t",title:"Painting",status:"todo"}],weather:[{id:"w",forecastAt:"2026-08-07T09:00:00.000Z",humidityPercent:92,source:"verified-provider"}],photoTags:[{id:"tag",condition:"wet_wall",markedAt:"2026-08-06T10:00:00.000Z"}]})),risk=signals.find(x=>x.key==="humidity-drying");expect(risk?.recommendation).toContain("dehumidifier");expect(risk?.evidence.some(x=>x.source==="manual_photo_tag")).toBe(true)});
 it("warns about frost for curing work",()=>{const risk=analyseConstructionProject(base({tasks:[{id:"t",title:"Concrete slab",status:"todo"}],weather:[{id:"w",forecastAt:"2026-08-07T02:00:00.000Z",temperatureC:-2,source:"verified-provider"}]})).find(x=>x.key==="frost-curing");expect(risk).toMatchObject({severity:"critical",confidence:.9})});
 it("does not invent weather risks when no forecast exists",()=>expect(analyseConstructionProject(base({tasks:[{id:"t",title:"Facade painting",status:"todo"}]})).some(x=>x.riskType==="weather_conflict")).toBe(false));
 it("requires an approved snapshot and derives explainable health",()=>{const signals=analyseConstructionProject(base({approvedScan:undefined,project:{id:"p",status:"active",expectedCompletionDate:"2026-08-01"}}));expect(signals.map(x=>x.key)).toEqual(["project-late","approved-scan-missing"]);expect(projectHealth(signals)).toBe("red");expect(projectHealth([])).toBe("green")});
});
