import{describe,expect,it}from"vitest";import{assertApprovable,assertReviewTransition,effectiveReviewResult,validateReviewValue}from"../src/domain/document-review/document-review-rules.js";import type{ExtractedField}from"../src/domain/document-analysis/analysis-types.js";
const field=(name:string,value:string,status:"valid"|"invalid"|"unverified"="valid"):ExtractedField=>({name,value,normalizedValue:value,confidence:.8,source:"ocr_text",pageId:"p",startOffset:0,endOffset:value.length,extractionRule:"test",validationStatus:status});
describe("document review domain",()=>{
 it.each([["not_started","in_review"],["in_review","changes_requested"],["in_review","approved"],["in_review","rejected"],["changes_requested","in_review"]]as const)("allows %s to %s",(a,b)=>expect(()=>assertReviewTransition(a,b)).not.toThrow());
 it.each([["approved","in_review"],["approved","rejected"],["rejected","approved"],["not_started","approved"]]as const)("rejects %s to %s",(a,b)=>expect(()=>assertReviewTransition(a,b)).toThrow());
 it("sets fields and preserves manual provenance",()=>{const r=effectiveReviewResult("invoice",[field("currency","PLN")],[{id:"1",fieldName:"currency",operation:"set",previousValue:"PLN",proposedValue:"EUR",normalizedValue:"EUR",source:"manual",pageId:null,startOffset:null,endOffset:null,validationStatus:"valid",createdAt:"2026-01-01"}],[],10);expect(r.fields[0]).toMatchObject({value:"EUR",source:"manual",extractionRule:"manual-review"});});
 it("removes fields explicitly",()=>expect(effectiveReviewResult("invoice",[field("iban","x")],[{id:"1",fieldName:"iban",operation:"remove",previousValue:"x",proposedValue:null,normalizedValue:null,source:"manual",pageId:null,startOffset:null,endOffset:null,validationStatus:"valid",createdAt:"2026-01-01"}],[],10).fields).toHaveLength(0));
 it("applies ordered corrections with last winning",()=>{const changes:any[]=[{id:"b",fieldName:"currency",operation:"set",proposedValue:"USD",normalizedValue:"USD",source:"manual",pageId:null,startOffset:null,endOffset:null,validationStatus:"valid",createdAt:"2026-01-01"},{id:"a",fieldName:"currency",operation:"set",proposedValue:"EUR",normalizedValue:"EUR",source:"manual",pageId:null,startOffset:null,endOffset:null,validationStatus:"valid",createdAt:"2026-01-01"}];expect(effectiveReviewResult("invoice",[],changes,[],10).fields[0].value).toBe("USD");});
 it("applies classification corrections",()=>expect(effectiveReviewResult("invoice",[],[],[{id:"1",previousDocumentType:"invoice",proposedDocumentType:"contract",createdAt:"2026-01-01"}],10).documentType).toBe("contract"));
 it("blocks invalid approval",()=>expect(()=>assertApprovable({documentType:"invoice",fields:[field("issueDate","bad","invalid")]})).toThrow());
 it("rejects unknown field names",()=>expect(()=>validateReviewValue("secretField","x")).toThrow());
 it("validates dates amounts currencies NIP and IBAN using extraction rules",()=>{expect(validateReviewValue("issueDate","31.12.2026").normalizedValue).toBe("2026-12-31");expect(validateReviewValue("totalAmount","1.234,56").normalizedValue).toBe("1234.56");expect(validateReviewValue("currency","eur").normalizedValue).toBe("EUR");expect(validateReviewValue("sellerTaxId","856-734-62-15").validationStatus).toBe("valid");expect(validateReviewValue("iban","PL61 1090 1014 0000 0712 1981 2874").validationStatus).toBe("valid");});
 it("marks invalid manual values",()=>{expect(validateReviewValue("issueDate","31.02.2026").validationStatus).toBe("invalid");expect(validateReviewValue("currency","CAD").validationStatus).toBe("invalid");});
 it("enforces maximum fields",()=>expect(()=>effectiveReviewResult("invoice",[field("currency","PLN"),field("iban","x")],[],[],1)).toThrow());
 it("handles duplicate original names deterministically",()=>expect(effectiveReviewResult("invoice",[field("currency","PLN"),field("currency","EUR")],[],[],10).fields[0].value).toBe("EUR"));
});
