import{describe,expect,it}from"vitest";import{DeterministicDocumentClassifier}from"../src/infrastructure/document-analysis/deterministic-classifier.js";import{extractFields,normalizeAmount,normalizeDate,schemaFor,validIban,validNip}from"../src/domain/document-analysis/extraction-rules.js";
describe("document analysis rules",()=>{const c=new DeterministicDocumentClassifier(),classify=(text:string,threshold=.45)=>c.classify({text,pages:[],language:null,threshold});
 for(const [type,text]of[["invoice","FAKTURA VAT NIP termin płatności"],["invoice","INVOICE VAT invoice number"],["invoice","РАХУНОК VAT NIP"],["receipt","PARAGON suma"],["contract","UMOWA strony postanowienia"],["estimate","KOSZTORYS quantity unit price"],["work_acceptance_act","PROTOKÓŁ ODBIORU"]]as const)it(`classifies ${type}`,async()=>expect((await classify(text)).documentType).toBe(type));
 it("handles unknown, conflict, threshold, empty and determinism",async()=>{expect((await classify("random words")).documentType).toBe("unknown");expect((await classify("invoice contract")).documentType).toBe("unknown");expect((await classify("invoice",.9)).documentType).toBe("unknown");expect((await classify("")).documentType).toBe("unknown");expect(await classify("FAKTURA VAT NIP")).toEqual(await classify("FAKTURA VAT NIP"));});
 it("normalizes dates and decimal amounts without float arithmetic",()=>{expect(normalizeDate("31.12.2026")).toBe("2026-12-31");expect(normalizeDate("2026-02-29")).toBeNull();expect(normalizeAmount("1 234,56")).toBe("1234.56");expect(normalizeAmount("1.234,56")).toBe("1234.56");expect(normalizeAmount("1,234.56")).toBe("1234.56");});
 it("validates tax IDs and IBAN checksum",()=>{expect(validNip("856-734-62-15")).toBe(true);expect(validNip("1234567890")).toBe(false);expect(validIban("PL61 1090 1014 0000 0712 1981 2874")).toBe(true);expect(validIban("PL00 1090 1014 0000 0712 1981 2874")).toBe(false);});
 it("extracts schema-versioned fields with offsets and page provenance",()=>{const text="FAKTURA nr FV/12/2026\nData wystawienia: 31.12.2026\nTermin płatności: 15.01.2027\nNIP sprzedawcy: 8567346215\nIBAN PL61 1090 1014 0000 0712 1981 2874\nRazem 1.234,56 EUR",fields=extractFields("invoice",text,[{pageId:"00000000-0000-4000-8000-000000000001",text,startOffset:0,endOffset:text.length}],100,2000);expect(schemaFor("invoice")).toBe("invoice:v1");expect(fields.find(x=>x.name==="invoiceNumber")?.value).toBe("FV/12/2026");expect(fields.find(x=>x.name==="issueDate")?.normalizedValue).toBe("2026-12-31");expect(fields.find(x=>x.name==="totalAmount")?.normalizedValue).toBe("1234.56");expect(fields.find(x=>x.name==="iban")?.validationStatus).toBe("valid");expect(fields.every(x=>x.pageId&&x.startOffset!==null&&x.extractionRule)).toBe(true);});
 it("marks invalid values and enforces field/length limits",()=>{const text="INVOICE nr ABCDEFG issue date: 31.02.2026 total 123.45 EUR";const fields=extractFields("invoice",text,[{pageId:"p",text,startOffset:0,endOffset:text.length}],2,4);expect(fields).toHaveLength(2);expect(fields[0].value.length).toBeLessThanOrEqual(4);expect(fields.find(x=>x.name==="issueDate")?.validationStatus).toBe("invalid");});
});
