import {mkdtemp,readdir,rm} from "node:fs/promises";import {tmpdir} from "node:os";import {join} from "node:path";import {randomUUID} from "node:crypto";import {Pool} from "pg";import {afterAll,beforeAll,describe,expect,it} from "vitest";
import {DocumentService} from "../src/application/document/document-service.js";import {LocalDocumentStorage} from "../src/infrastructure/document/local-document-storage.js";
const url=process.env.DATABASE_URL,run=url?describe:describe.skip;
run("Documents PostgreSQL integration",()=>{const pool=new Pool({connectionString:url});let root="",service:DocumentService;const actor={id:"00000000-0000-4000-8000-000000000011",tenantId:"00000000-0000-4000-8000-000000000001",permissions:["documents.read","documents.create","documents.update","documents.delete"],correlationId:randomUUID()},second={...actor,id:"00000000-0000-4000-8000-000000000015",tenantId:"00000000-0000-4000-8000-000000000002"};const bytes=Buffer.from("%PDF-1.4\nintegration");
 beforeAll(async()=>{root=await mkdtemp(join(tmpdir(),"odls-doc-test-"));service=new DocumentService(pool,new LocalDocumentStorage(root),1000);});afterAll(async()=>{await pool.end();await rm(root,{recursive:true,force:true});});
 it("uploads, links, lists, versions, downloads, conflicts and archives without tenant leakage",async()=>{let d=await service.upload(actor,{category:"contract",description:"initial",entityType:"project",entityId:"00000000-0000-4000-8000-000000000071"},{filename:"contract.pdf",mimetype:"application/pdf",bytes});expect(d.currentVersion.checksum).toHaveLength(64);expect((await service.list(actor,{page:1,pageSize:25,sortBy:"updatedAt",sortOrder:"desc"})).items.some((x:any)=>x.id===d.id)).toBe(true);await expect(service.get(second,d.id)).rejects.toMatchObject({code:"NOT_FOUND"});d=await service.update(actor,d.id,{expectedVersion:d.version,description:"changed"});await expect(service.update(actor,d.id,{expectedVersion:1,description:"stale"})).rejects.toMatchObject({code:"VERSION_CONFLICT"});d=await service.addLink(actor,d.id,{entityType:"client",entityId:"00000000-0000-4000-8000-000000000041",expectedVersion:d.version});expect(d.links).toHaveLength(2);d=await service.removeLink(actor,d.id,d.links[0].id,d.version);expect(d.links).toHaveLength(1);d=await service.addVersion(actor,d.id,d.version,{filename:"contract.pdf",mimetype:"application/pdf",bytes:Buffer.from("%PDF-1.4\nversion two")});expect((await service.versions(actor,d.id)).map((x:any)=>x.versionNo)).toEqual([2,1]);expect((await service.download(actor,d.id)).bytes.toString()).toContain("version two");d=await service.archive(actor,d.id,d.version);await expect(service.addVersion(actor,d.id,d.version,{filename:"contract.pdf",mimetype:"application/pdf",bytes})).rejects.toMatchObject({code:"ENTITY_ARCHIVED"});});
 it("rejects cross-tenant links and cleans stored upload",async()=>{await expect(service.upload(actor,{category:"other",entityType:"project",entityId:"00000000-0000-4000-8000-000000000072"},{filename:"x.pdf",mimetype:"application/pdf",bytes})).rejects.toMatchObject({code:"NOT_FOUND"});});
 it("rolls back metadata and removes the orphan file when mandatory audit fails",async()=>{await pool.query(`CREATE OR REPLACE FUNCTION document_test_fail_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.action='document.uploaded' AND NEW.metadata->>'filename'='FAIL_AUDIT.pdf' THEN RAISE EXCEPTION 'forced document audit failure'; END IF; RETURN NEW; END $$; DROP TRIGGER IF EXISTS document_test_fail_audit ON audit_logs; CREATE TRIGGER document_test_fail_audit BEFORE INSERT ON audit_logs FOR EACH ROW EXECUTE FUNCTION document_test_fail_audit()`);try{await expect(service.upload(actor,{category:"other",entityType:"project",entityId:"00000000-0000-4000-8000-000000000071"},{filename:"FAIL_AUDIT.pdf",mimetype:"application/pdf",bytes})).rejects.toThrow("forced document audit failure");expect((await readdir(root,{recursive:true})).some(x=>x==="FAIL_AUDIT.pdf")).toBe(false);}finally{await pool.query("DROP TRIGGER IF EXISTS document_test_fail_audit ON audit_logs; DROP FUNCTION IF EXISTS document_test_fail_audit()");}});
});
