import {Pool} from "pg";
import {beforeAll,afterAll,describe,expect,it} from "vitest";
const url=process.env.DATABASE_URL;
const run=url?describe:describe.skip;
run("Finance forced RLS",()=>{
  const owner=new Pool({connectionString:url}),roleUrl=new URL(url!);roleUrl.username="finance_rls_test";roleUrl.password="finance_rls_test";const restricted=new Pool({connectionString:roleUrl.toString()});
  const tenant="00000000-0000-4000-8000-000000000001",other="00000000-0000-4000-8000-000000000002";
  beforeAll(async()=>{await owner.query("DO $$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname='finance_rls_test') THEN CREATE ROLE finance_rls_test LOGIN PASSWORD 'finance_rls_test'; END IF; END $$");await owner.query("ALTER ROLE finance_rls_test PASSWORD 'finance_rls_test'");await owner.query("GRANT USAGE ON SCHEMA public TO finance_rls_test");await owner.query("GRANT SELECT,INSERT,UPDATE,DELETE ON invoices,payments,payment_allocations,expenses TO finance_rls_test");});
  afterAll(async()=>{await restricted.end();await owner.end();});
  async function tx<T>(tenantId:string,fn:(c:any)=>Promise<T>){const c=await restricted.connect();try{await c.query("BEGIN");await c.query("SELECT set_config('app.tenant_id',$1,true)",[tenantId]);const x=await fn(c);await c.query("ROLLBACK");return x;}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}}
  for(const table of ["invoices","payments","payment_allocations","expenses"])it(`${table}: same tenant visible and cross tenant hidden`,async()=>{const same=await tx(tenant,c=>c.query(`SELECT count(*)::int count FROM ${table}`).then((r:any)=>r.rows[0].count));const hidden=await tx(other,c=>c.query(`SELECT count(*)::int count FROM ${table} WHERE tenant_id=$1`,[tenant]).then((r:any)=>r.rows[0].count));expect(same).toBeGreaterThanOrEqual(0);expect(hidden).toBe(0);});
  it("allows same-tenant Invoice insert/update but blocks cross-tenant insert",async()=>{await tx(tenant,async c=>{const r=await c.query("INSERT INTO invoices(tenant_id,client_id,invoice_number,currency_code,net_amount,vat_rate,vat_amount,gross_amount) VALUES($1,'00000000-0000-4000-8000-000000000041',$2,'EUR',1,0,0,1) RETURNING id",[tenant,`RLS-${Date.now()}`]);expect((await c.query("UPDATE invoices SET notes='ok' WHERE id=$1 RETURNING id",[r.rows[0].id])).rowCount).toBe(1);});await expect(tx(tenant,c=>c.query("INSERT INTO payments(tenant_id,client_id,reference,currency_code,amount,payment_date) VALUES($1,'00000000-0000-4000-8000-000000000042','cross','EUR',1,current_date)",[other]))).rejects.toMatchObject({code:"42501"});});
  it("prevents an allocation from bridging tenants",async()=>{const records=await owner.query<any>("SELECT (SELECT id FROM payments WHERE tenant_id=$1 LIMIT 1) payment,(SELECT id FROM invoices WHERE tenant_id=$2 LIMIT 1) invoice",[tenant,other]);if(records.rows[0].payment&&records.rows[0].invoice)await expect(tx(tenant,c=>c.query("INSERT INTO payment_allocations(tenant_id,payment_id,invoice_id,amount) VALUES($1,$2,$3,1)",[tenant,records.rows[0].payment,records.rows[0].invoice]))).rejects.toBeTruthy();});
  it("keeps FORCE RLS enabled for every Finance table",async()=>{const rows=(await owner.query<{relname:string;relrowsecurity:boolean;relforcerowsecurity:boolean}>("SELECT relname,relrowsecurity,relforcerowsecurity FROM pg_class WHERE relname=ANY($1)",[["invoices","payments","payment_allocations","expenses"]])).rows;expect(rows).toHaveLength(4);expect(rows.every(r=>r.relrowsecurity&&r.relforcerowsecurity)).toBe(true);});
});
