import {afterAll,beforeAll,describe,expect,it} from "vitest";
import {buildServer} from "../src/server.js";
const run=process.env.DATABASE_URL?describe:describe.skip;
run("measurement unit API",()=>{
 const app=buildServer();let admin="",employee="",second="",created:any;
 beforeAll(async()=>{const login=async(tenantSlug:string,email:string)=>(await app.inject({method:"POST",url:"/api/v1/auth/login",payload:{tenantSlug,email,password:"DemoPassword!2026"}})).json().data.accessToken;admin=await login("demo","admin@demo.odls");employee=await login("demo","employee@demo.odls");second=await login("second","admin@second.odls");});
 afterAll(()=>app.close());const request=(method:any,url:string,token=admin,payload?:any):any=>app.inject({method,url,headers:{authorization:`Bearer ${token}`},payload});
 it("reads, filters, searches, sorts and paginates deterministic seeded units",async()=>{const r=await request("GET","/api/v1/measurement-units?dimension=length&unitSystem=metric&active=true&search=m&sortBy=code&sortOrder=asc&page=1&pageSize=5");expect(r.statusCode).toBe(200);const b=r.json();expect(b.data.length).toBeLessThanOrEqual(5);expect(b.data.every((x:any)=>x.dimension==="length"&&x.unitSystem==="metric"&&x.status==="active")).toBe(true);expect(b.pagination.pageSize).toBe(5);expect((await request("GET","/api/v1/measurement-units?sortBy=bad")).statusCode).toBe(400);});
 it("creates, gets, updates with concurrency, deactivates and audits a custom unit",async()=>{const code=`E2E_${Date.now()}`;let r=await request("POST","/api/v1/measurement-units",admin,{code,symbol:"eu",displayName:"Example unit",dimension:"custom",unitSystem:"custom",decimalPrecision:2});expect(r.statusCode).toBe(201);created=r.json().data;expect((await request("GET",`/api/v1/measurement-units/${created.id}`)).json().data.code).toBe(code);r=await request("PATCH",`/api/v1/measurement-units/${created.id}`,admin,{expectedVersion:created.version,displayName:"Edited unit"});expect(r.statusCode).toBe(200);const updated=r.json().data;expect((await request("PATCH",`/api/v1/measurement-units/${created.id}`,admin,{expectedVersion:created.version,displayName:"Stale"})).statusCode).toBe(409);r=await request("POST",`/api/v1/measurement-units/${created.id}/deactivate`,admin,{expectedVersion:updated.version});expect(r.json().data.status).toBe("inactive");});
 it("enforces duplicate codes per tenant but permits tenant ownership",async()=>{const code=`TENANT_${Date.now()}`,payload={code,symbol:"tu",displayName:"Tenant unit",dimension:"custom",unitSystem:"custom",decimalPrecision:2};const own=await request("POST","/api/v1/measurement-units",admin,payload);expect(own.statusCode).toBe(201);expect((await request("POST","/api/v1/measurement-units",admin,payload)).statusCode).toBe(409);const other=await request("POST","/api/v1/measurement-units",second,payload);expect(other.statusCode).toBe(201);expect((await request("GET",`/api/v1/measurement-units/${own.json().data.id}`,second)).statusCode).toBe(404);});
 it("converts metric, imperial and time quantities with decimal rounding",async()=>{const rows=(await request("GET","/api/v1/measurement-units?pageSize=100")).json().data,by=(code:string)=>rows.find((x:any)=>x.code===code).id;expect((await request("POST","/api/v1/measurement-units/convert",admin,{fromUnitId:by("M"),toUnitId:by("CM"),quantity:"1.25",precision:2})).json().data.result).toBe("125.00");expect((await request("POST","/api/v1/measurement-units/convert",admin,{fromUnitId:by("M2"),toUnitId:by("FT2"),quantity:"1",precision:4})).json().data.result).toBe("10.7639");expect((await request("POST","/api/v1/measurement-units/convert",admin,{fromUnitId:by("DAY"),toUnitId:by("H"),quantity:"2"})).json().data.result).toBe("48.00");expect((await request("POST","/api/v1/measurement-units/convert",admin,{fromUnitId:by("M"),toUnitId:by("KG"),quantity:"1"})).statusCode).toBe(422);expect((await request("POST","/api/v1/measurement-units/convert",admin,{fromUnitId:by("PACKAGE"),toUnitId:by("PALLET"),quantity:"1"})).statusCode).toBe(400);expect((await request("POST","/api/v1/measurement-units/convert",admin,{fromUnitId:by("M"),toUnitId:by("CM"),quantity:"-1"})).statusCode).toBe(400);});
 it("allows operational read/conversion but forbids mutation",async()=>{expect((await request("GET","/api/v1/measurement-units",employee)).statusCode).toBe(200);expect((await request("POST","/api/v1/measurement-units",employee,{code:"NO",symbol:"n",displayName:"No",dimension:"custom",unitSystem:"custom",decimalPrecision:1})).statusCode).toBe(403);});
});
