import {randomUUID} from "node:crypto";
import {Pool} from "pg";
import {afterAll,beforeAll,describe,expect,it} from "vitest";
import {TaskService} from "../src/application/task/task-service.js";
import {NotificationWorker} from "../src/application/notification/notification-worker.js";
import {NotificationService,type NotificationActor} from "../src/application/notification/notification-service.js";
const url=process.env.DATABASE_URL,run=url?describe:describe.skip;
run("Notifications PostgreSQL integration",()=>{
 const pool=new Pool({connectionString:url}),worker=new NotificationWorker(pool,{clock:()=>new Date("2026-07-26T23:59:00Z"),batchSize:500}),notifications=new NotificationService(pool);
 const admin={id:"00000000-0000-4000-8000-000000000011",tenantId:"00000000-0000-4000-8000-000000000001",permissions:["tasks.read","tasks.create","tasks.update","tasks.assign"],correlationId:randomUUID()};
 const recipient:NotificationActor={id:"00000000-0000-4000-8000-000000000012",tenantId:admin.tenantId,permissions:["notifications.read","notifications.update"],correlationId:randomUUID()},other={...recipient,id:"00000000-0000-4000-8000-000000000015",tenantId:"00000000-0000-4000-8000-000000000002"};
 beforeAll(async()=>{await pool.query("SELECT 1");});afterAll(()=>pool.end());
 it("atomically enqueues assignment, creates one recipient notification, and survives duplicate consumption/restart",async()=>{const tasks=new TaskService(pool),task=await tasks.createTask(admin,{projectId:"00000000-0000-4000-8000-000000000071",title:`Notify ${randomUUID()}`,dueDate:"2026-07-27"}),assigned=await tasks.assignTask(admin,task.id,recipient.id,task.version);const outbox=(await pool.query<{count:number;nextAttemptAt:Date}>("SELECT count(*)::int count,max(next_attempt_at) AS \"nextAttemptAt\" FROM outbox_events WHERE entity_id=$1 AND event_type='task.assigned'",[task.id])).rows[0];expect(outbox.count).toBe(1);const claimClock=new Date(outbox.nextAttemptAt.getTime()+1),assignmentWorker=new NotificationWorker(pool,{clock:()=>claimClock,batchSize:500});await assignmentWorker.processTenant(admin.tenantId);await assignmentWorker.processTenant(admin.tenantId);const list=await notifications.list(recipient,{page:1,pageSize:25,eventType:"task.assigned",sortBy:"createdAt",sortOrder:"desc"});expect(list.items.filter(x=>x.entityId===task.id)).toHaveLength(1);await expect(notifications.get(other,list.items[0].id)).rejects.toMatchObject({code:"NOT_FOUND"});expect(assigned.assignees.some(x=>x.userId===recipient.id)).toBe(true);});
 it("supports unread count, optimistic state, mark-all-read, archive and own preferences",async()=>{const list=await notifications.list(recipient,{page:1,pageSize:25,sortBy:"createdAt",sortOrder:"desc"}),item=list.items[0];expect(await notifications.unreadCount(recipient)).toBeGreaterThan(0);const read=await notifications.state(recipient,item.id,"read",item.version);await expect(notifications.state(recipient,item.id,"unread",item.version)).rejects.toMatchObject({code:"VERSION_CONFLICT"});const unread=await notifications.state(recipient,item.id,"unread",read.version);const archived=await notifications.state(recipient,item.id,"archived",unread.version);await expect(notifications.state(recipient,item.id,"read",archived.version)).rejects.toMatchObject({code:"ENTITY_ARCHIVED"});expect(await notifications.markAllRead(recipient)).toBeGreaterThanOrEqual(0);const p=await notifications.preferences(recipient),updated=await notifications.updatePreferences(recipient,{expectedVersion:p.version,dueSoonEnabled:false});expect(updated.dueSoonEnabled).toBe(false);await expect(notifications.updatePreferences(recipient,{expectedVersion:p.version,overdueEnabled:false})).rejects.toMatchObject({code:"VERSION_CONFLICT"});});
 it("generates due-soon reminders once, excludes completed tasks, and honors preferences",async()=>{const before=Number((await pool.query("SELECT count(*) FROM reminder_executions WHERE tenant_id=$1",[admin.tenantId])).rows[0].count),first=await worker.generateReminders(admin.tenantId),second=await worker.generateReminders(admin.tenantId);expect(first).toBeGreaterThanOrEqual(0);expect(second).toBe(0);expect(Number((await pool.query("SELECT count(*) FROM reminder_executions WHERE tenant_id=$1",[admin.tenantId])).rows[0].count)).toBeGreaterThanOrEqual(before);await worker.processTenant(admin.tenantId);const reminders=await notifications.list(recipient,{page:1,pageSize:100,eventType:"task.due_soon",sortBy:"createdAt",sortOrder:"desc"});expect(reminders.items.every(x=>x.recipientUserId===recipient.id)).toBe(true);});
});
