import {Pool} from "pg";
import {afterAll,beforeAll,describe,expect,it} from "vitest";
const url=process.env.DATABASE_URL,run=url?describe:describe.skip;
run("Notification FORCE RLS",()=>{
 const owner=new Pool({connectionString:url}),roleUrl=new URL(url!);roleUrl.username="notification_rls_test";roleUrl.password="notification_rls_test";const restricted=new Pool({connectionString:roleUrl.toString()}),tenant="00000000-0000-4000-8000-000000000001",user="00000000-0000-4000-8000-000000000012",otherUser="00000000-0000-4000-8000-000000000013";
 beforeAll(async()=>{await owner.query("DO $$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname='notification_rls_test') THEN CREATE ROLE notification_rls_test LOGIN PASSWORD 'notification_rls_test'; END IF; END $$");await owner.query("ALTER ROLE notification_rls_test PASSWORD 'notification_rls_test'");await owner.query("GRANT USAGE ON SCHEMA public TO notification_rls_test");await owner.query("GRANT SELECT,INSERT,UPDATE,DELETE ON notifications,notification_preferences,outbox_events,notification_deliveries,reminder_executions TO notification_rls_test");});afterAll(async()=>{await restricted.end();await owner.end();});
 async function tx<T>(userId:string,worker:boolean,fn:(c:any)=>Promise<T>){const c=await restricted.connect();try{await c.query("BEGIN");await c.query("SELECT set_config('app.tenant_id',$1,true),set_config('app.user_id',$2,true),set_config('app.worker',$3,true)",[tenant,userId,String(worker)]);const x=await fn(c);await c.query("ROLLBACK");return x;}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}}
 it("recipient sees only own rows and cannot update another recipient",async()=>{const visible=await tx(user,false,c=>c.query("SELECT count(*)::int count FROM notifications").then((r:any)=>r.rows[0].count)),hidden=await tx(otherUser,false,c=>c.query("SELECT count(*)::int count FROM notifications WHERE recipient_user_id=$1",[user]).then((r:any)=>r.rows[0].count));expect(visible).toBeGreaterThanOrEqual(0);expect(hidden).toBe(0);});
 for(const table of ["notifications","notification_preferences","outbox_events","notification_deliveries","reminder_executions"])it(`${table} has FORCE RLS`,async()=>{const x=(await owner.query("SELECT relrowsecurity,relforcerowsecurity FROM pg_class WHERE relname=$1",[table])).rows[0];expect(x).toEqual({relrowsecurity:true,relforcerowsecurity:true});});
 it("outbox is hidden without explicit worker context",async()=>{expect(await tx(user,false,c=>c.query("SELECT count(*)::int count FROM outbox_events").then((r:any)=>r.rows[0].count))).toBe(0);expect(await tx(user,true,c=>c.query("SELECT count(*)::int count FROM outbox_events").then((r:any)=>r.rows[0].count))).toBeGreaterThanOrEqual(0);});
});
