import {describe,expect,it} from "vitest";
import {daysBetweenUtc,deduplicationKey,notificationCopy,preferenceAllows,reminderKind,retryDecision} from "../src/domain/notification/notification-rules.js";
const preferences={tenantId:"t",userId:"u",inAppEnabled:true,taskEventsEnabled:true,projectEventsEnabled:true,financeEventsEnabled:true,documentEventsEnabled:true,dueSoonEnabled:true,overdueEnabled:true,selfNotificationsEnabled:false,version:1,createdAt:"",updatedAt:""};
describe("notification rules",()=>{
 it("creates stable, recipient-specific deduplication keys",()=>{expect(deduplicationKey("task.assigned","task","user","event")).toBe(deduplicationKey("task.assigned","task","user","event"));expect(deduplicationKey("task.assigned","task","other","event")).not.toBe(deduplicationKey("task.assigned","task","user","event"));});
 it("maps every supported event to user-facing copy",()=>{expect(notificationCopy("invoice.overdue")).toEqual({title:"Invoice overdue",body:"An issued invoice is overdue.",severity:"critical"});expect(notificationCopy("task.completed").severity).toBe("success");});
 it("filters categories, reminders, global delivery and actor self-notifications",()=>{expect(preferenceAllows(preferences,"task.assigned",false)).toBe(true);expect(preferenceAllows(preferences,"task.assigned",true)).toBe(false);expect(preferenceAllows({...preferences,dueSoonEnabled:false},"task.due_soon",false)).toBe(false);expect(preferenceAllows({...preferences,financeEventsEnabled:false},"invoice.paid",false)).toBe(false);expect(preferenceAllows({...preferences,inAppEnabled:false},"document.uploaded",false)).toBe(false);});
 it("uses UTC calendar dates for due-soon and overdue boundaries",()=>{expect(reminderKind("2026-08-03",new Date("2026-07-31T23:59:59-05:00"),3)).toBe("due_soon");expect(reminderKind("2026-07-30",new Date("2026-07-31T00:00:00Z"),3)).toBe("overdue");expect(daysBetweenUtc("2026-03-28","2026-03-29")).toBe(1);});
 it("bounds exponential retries and dead-letters at the configured attempt",()=>{const now=new Date("2026-01-01T00:00:00Z");expect(retryDecision(0,3,now)).toMatchObject({attemptCount:1,deadLetter:false,nextAttemptAt:new Date("2026-01-01T00:00:02Z")});expect(retryDecision(2,3,now)).toMatchObject({attemptCount:3,deadLetter:true});expect(retryDecision(20,30,now).nextAttemptAt).toEqual(new Date("2026-01-01T00:01:00Z"));});
});
