import{describe,expect,it}from"vitest";
import{calculateCommercialEstimate}from"../src/domain/regional-pricing-estimate/regional-pricing-estimate-rules.js";

const base={currency:"PLN",workQuantity:10,workUnit:"M2",demands:[{demandKind:"labor",requirementCode:"PAINTER",quantity:5,unitCode:"H"},{demandKind:"machine",requirementCode:"SPRAYER",quantity:2,unitCode:"H"}],materials:[{materialId:"11111111-1111-4111-8111-111111111111",requirementCode:"PAINT",remainingQuantity:8,packageCount:2,unitCode:"L"}],entries:[{id:"l",priceKind:"labor"as const,referenceCode:"PAINTER",unitCode:"H",unitPrice:40,sourceReference:"union-2026"},{id:"e",priceKind:"equipment"as const,referenceCode:"SPRAYER",unitCode:"H",unitPrice:20,sourceReference:"rental-2026"},{id:"m",priceKind:"material"as const,referenceCode:"11111111-1111-4111-8111-111111111111",unitCode:"L",unitPrice:10,sourceReference:"supplier-quote"},{id:"t",priceKind:"transport"as const,referenceCode:"DELIVERY",unitCode:"EA",unitPrice:50,rateType:"fixed"as const,sourceReference:"carrier-quote"}],overheadRules:[{code:"OH",percent:10}],taxRule:{code:"VAT",percent:23,mode:"standard"as const},marginRules:[{code:"STANDARD",percent:20}],discountRules:[{code:"FRAMEWORK",percent:5}],adjustmentRules:[{code:"CENTER",percent:2,condition:"CITY_CENTER"}],conditions:["CITY_CENTER"]};
describe("regional pricing estimate rules",()=>{
 it("builds every monetary component from a traceable approved-source entry",()=>{const x=calculateCommercialEstimate(base);expect(x.laborCost).toBe(200);expect(x.materialCost).toBe(80);expect(x.equipmentCost).toBe(40);expect(x.otherCost).toBe(57.4);expect(x.overhead).toBe(37.74);expect(x.internalCost).toBe(415.14);expect(x.netTotal).toBe(492.9788);expect(x.vatAmount).toBe(113.3851);expect(x.grossTotal).toBe(606.3639);expect(x.trace.components).toHaveLength(4);expect(x.trace.components.every((t:any)=>t.sourceReference)).toBe(true)});
 it("supports zero and reverse-charge tax without losing the tax decision trace",()=>{for(const mode of ["zero","reverse_charge"]as const){const x=calculateCommercialEstimate({...base,taxRule:{code:mode,percent:23,mode}});expect(x.vatAmount).toBe(0);expect(x.grossTotal).toBe(x.netTotal);expect(x.trace.tax.mode).toBe(mode)}});
 it("rejects missing or ambiguous authority and unreasoned manual overrides",()=>{expect(()=>calculateCommercialEstimate({...base,entries:base.entries.filter(x=>x.priceKind!=="labor")})).toThrow();expect(()=>calculateCommercialEstimate({...base,entries:[...base.entries,base.entries[0]]})).toThrow();expect(()=>calculateCommercialEstimate({...base,manualMarginPercent:15})).toThrow()});
});
