import{afterAll,beforeAll,describe,expect,it}from"vitest";
import{Pool}from"pg";
const run=process.env.DATABASE_URL?describe:describe.skip;
run("room scanner PostgreSQL security and atomicity",()=>{
 const pool=new Pool({connectionString:process.env.DATABASE_URL}),url=new URL(process.env.DATABASE_URL!),restrictedUrl=new URL(url);
 restrictedUrl.username="room_scan_rls_test";restrictedUrl.password="room_scan_rls_test";
 const restricted=new Pool({connectionString:restrictedUrl.toString()}),tables=["room_scan_sessions","room_scan_rooms","room_scan_surfaces","room_scan_measurements","room_scan_openings","room_scan_observations","room_scan_quantities","room_scan_quantity_dependencies","room_scan_quantity_history","room_scan_flatness_observations","room_scan_flatness_samples","room_scan_defect_observations","room_scan_corner_observations","approved_room_scan_snapshots","room_scan_attachments","room_scan_processing_requests"];
 beforeAll(async()=>{
  await pool.query("DO $$BEGIN IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname='room_scan_rls_test')THEN CREATE ROLE room_scan_rls_test LOGIN PASSWORD 'room_scan_rls_test';END IF;END$$");
  await pool.query("ALTER ROLE room_scan_rls_test PASSWORD 'room_scan_rls_test'");await pool.query("GRANT USAGE ON SCHEMA public TO room_scan_rls_test");await pool.query(`GRANT SELECT,UPDATE ON ${tables.join(",")} TO room_scan_rls_test`);
  const f=(await pool.query("SELECT t.id tenant_id,u.id user_id,p.id property_id FROM tenants t JOIN users u ON u.tenant_id=t.id JOIN properties p ON p.tenant_id=t.id WHERE t.slug='demo' ORDER BY u.created_at,p.created_at LIMIT 1")).rows[0],scanId="00000000-0000-4000-8000-000000000823",roomId="00000000-0000-4000-8000-000000000826",measurementId="00000000-0000-4000-8000-000000000827",quantityId="00000000-0000-4000-8000-000000000828",snapshotId="00000000-0000-4000-8000-000000000824",correlationId="00000000-0000-4000-8000-000000000825";
  await pool.query("INSERT INTO room_scan_sessions(id,tenant_id,property_id,status,version,created_by,updated_by)VALUES($1,$2,$3,'ready_for_approval',2,$4,$4)ON CONFLICT(id)DO NOTHING",[scanId,f.tenant_id,f.property_id,f.user_id]);
  await pool.query("INSERT INTO room_scan_rooms(id,tenant_id,scan_id,name,created_by,updated_by)VALUES($1,$2,$3,'Fixture',$4,$4)ON CONFLICT(id)DO NOTHING",[roomId,f.tenant_id,scanId,f.user_id]);
  await pool.query("INSERT INTO room_scan_measurements(id,tenant_id,scan_id,room_id,measurement_type,source,original_value,original_unit,si_value,si_unit,verification_status,captured_at,captured_by,created_by,updated_by)VALUES($1,$2,$3,$4,'length','human_correction',1,'m',1,'m','verified',now(),$5,$5,$5)ON CONFLICT(id)DO NOTHING",[measurementId,f.tenant_id,scanId,roomId,f.user_id]);
  const deps=[{id:measurementId,entityType:"measurement",version:1}];
  await pool.query("INSERT INTO room_scan_quantities(id,tenant_id,scan_id,room_id,quantity_type,value,unit,formula_id,input_references,source_versions,calculation_version,created_by,updated_by)VALUES($1,$2,$3,$4,'room_perimeter',1,'m','fixture.formula',$5,$5,'room-geometry-v1',$6,$6)ON CONFLICT(id)DO NOTHING",[quantityId,f.tenant_id,scanId,roomId,JSON.stringify(deps),f.user_id]);
  const quantity={id:quantityId,roomId,type:"room_perimeter",value:1,unit:"m",formulaId:"fixture.formula",inputReferences:deps,calculationVersion:"room-geometry-v1"};
  await pool.query("UPDATE room_scan_sessions SET status='ready_for_approval'WHERE id=$1",[scanId]);
  await pool.query("INSERT INTO approved_room_scan_snapshots(id,tenant_id,scan_id,property_id,scan_version,content,content_fingerprint,calculation_version,approved_by)VALUES($1,$2,$3,$4,1,$5,repeat('a',64),'room-geometry-v1',$6)ON CONFLICT(id)DO NOTHING",[snapshotId,f.tenant_id,scanId,f.property_id,JSON.stringify({quantities:[quantity]}),f.user_id]);
  await pool.query("UPDATE room_scan_sessions SET status='approved'WHERE id=$1",[scanId]);
  await pool.query("DELETE FROM audit_logs WHERE tenant_id=$1 AND entity_id=$2 AND action IN('room_scan.approved','room_scan.snapshot_created')",[f.tenant_id,scanId]);await pool.query("DELETE FROM outbox_events WHERE tenant_id=$1 AND entity_id=$2 AND event_type IN('room_scan.approved','room_scan.quantities_ready')",[f.tenant_id,scanId]);
  for(const action of["room_scan.approved","room_scan.snapshot_created"])await pool.query("INSERT INTO audit_logs(tenant_id,actor_id,action,entity_type,entity_id,correlation_id,metadata)VALUES($1,$2,$3,'room_scan',$4,$5,'{}')",[f.tenant_id,f.user_id,action,scanId,correlationId]);
  for(const event of["room_scan.approved","room_scan.quantities_ready"])await pool.query("INSERT INTO outbox_events(tenant_id,event_type,entity_type,entity_id,actor_user_id,correlation_id)VALUES($1,$2,'room_scan',$3,$4,$5)",[f.tenant_id,event,scanId,f.user_id,correlationId]);
 });
 afterAll(async()=>{await restricted.end();await pool.end();});
 it("enables and forces RLS on every scanner table",async()=>{const rows=(await pool.query("SELECT relname,relrowsecurity,relforcerowsecurity FROM pg_class WHERE relname=ANY($1)",[tables])).rows;expect(rows).toHaveLength(tables.length);for(const x of rows){expect(x.relrowsecurity).toBe(true);expect(x.relforcerowsecurity).toBe(true);}});
 it("returns no rows without tenant context and isolates another tenant",async()=>{const client=await restricted.connect();try{await client.query("BEGIN");expect(Number((await client.query("SELECT count(*) FROM room_scan_sessions")).rows[0].count)).toBe(0);const tenants=(await pool.query("SELECT id FROM tenants ORDER BY slug")).rows;await client.query("SELECT set_config('app.tenant_id',$1,true)",[tenants[0].id]);const owned=(await client.query("SELECT id FROM room_scan_sessions LIMIT 1")).rows[0];expect(owned).toBeTruthy();await client.query("SELECT set_config('app.tenant_id',$1,true)",[tenants[1].id]);expect((await client.query("SELECT 1 FROM room_scan_sessions WHERE id=$1",[owned.id])).rowCount).toBe(0);expect((await client.query("UPDATE room_scan_sessions SET notes='cross tenant'WHERE id=$1",[owned.id])).rowCount).toBe(0);await client.query("ROLLBACK");}finally{client.release();}});
 it("stores safe audit/outbox atomically and rejects snapshot mutation",async()=>{const tenant=(await pool.query("SELECT id FROM tenants WHERE slug='demo'")).rows[0],client=await pool.connect();try{await client.query("BEGIN");await client.query("SELECT set_config('app.tenant_id',$1,true)",[tenant.id]);const scan=(await client.query("SELECT id FROM room_scan_sessions WHERE id='00000000-0000-4000-8000-000000000823'")).rows[0];expect(scan).toBeTruthy();expect(Number((await client.query("SELECT count(*) FROM audit_logs WHERE tenant_id=$1 AND entity_id=$2 AND action IN('room_scan.approved','room_scan.snapshot_created')",[tenant.id,scan.id])).rows[0].count)).toBe(2);expect(Number((await client.query("SELECT count(*) FROM outbox_events WHERE tenant_id=$1 AND entity_id=$2 AND event_type IN('room_scan.approved','room_scan.quantities_ready')",[tenant.id,scan.id])).rows[0].count)).toBeGreaterThanOrEqual(2);await expect(client.query("UPDATE approved_room_scan_snapshots SET content_fingerprint=repeat('0',64)WHERE scan_id=$1",[scan.id])).rejects.toThrow(/immutable/);await client.query("ROLLBACK");}finally{client.release();}});
});
