import{afterAll,beforeAll,describe,expect,it}from"vitest";import{buildServer}from"../src/server.js";
const run=process.env.DATABASE_URL?describe:describe.skip;
run("room scanner REST foundation",()=>{const app=buildServer();let admin="",second="",scan:any,roomId="",surfaceId="";const req=(method:any,url:string,token=admin,payload?:any):any=>app.inject({method,url,headers:{authorization:`Bearer ${token}`},payload});
 beforeAll(async()=>{const login=async(t:string,e:string)=>(await app.inject({method:"POST",url:"/api/v1/auth/login",payload:{tenantSlug:t,email:e,password:"DemoPassword!2026"}})).json().data.accessToken;admin=await login("demo","admin@demo.odls");second=await login("second","admin@second.odls");});afterAll(()=>app.close());
 it("validates strictly and creates idempotently",async()=>{expect((await req("POST","/api/v1/room-scans",admin,{propertyId:"bad",unknown:true})).statusCode).toBe(400);const property=(await req("GET","/api/v1/properties?pageSize=1")).json().data[0],body={propertyId:property.id,ingestionKey:`room-${Date.now()}`};let r=await req("POST","/api/v1/room-scans",admin,body);expect(r.statusCode).toBe(201);scan=r.json().data;r=await req("POST","/api/v1/room-scans",admin,body);expect(r.statusCode).toBe(201);expect(r.json().data.id).toBe(scan.id);});
 it("enforces permissions, tenant isolation and optimistic lifecycle",async()=>{expect((await req("GET",`/api/v1/room-scans/${scan.id}`,second)).statusCode).toBe(404);expect((await req("POST",`/api/v1/room-scans/${scan.id}/start-capture`,admin,{expectedVersion:999})).statusCode).toBe(409);const r=await req("POST",`/api/v1/room-scans/${scan.id}/start-capture`,admin,{expectedVersion:scan.version});expect(r.statusCode).toBe(200);scan=r.json().data;});
 it("captures normalized measurements and calculates quantities",async()=>{let r=await req("POST",`/api/v1/room-scans/${scan.id}/rooms`,admin,{name:"Living room",roomType:"living_room",floorNumber:1,expectedVersion:scan.version});expect(r.statusCode).toBe(201);roomId=r.json().data.id;scan=(await req("GET",`/api/v1/room-scans/${scan.id}`)).json().data;r=await req("POST",`/api/v1/room-scans/${scan.id}/surfaces`,admin,{roomId,surfaceType:"wall",label:"W-01",polygon:[{x:0,y:0},{x:4,y:0},{x:4,y:2.7},{x:0,y:2.7}],expectedVersion:scan.version});expect(r.statusCode).toBe(201);surfaceId=r.json().data.id;for(const[type,value]of[["width",4],["length",5],["height",2.7]]as const){scan=(await req("GET",`/api/v1/room-scans/${scan.id}`)).json().data;r=await req("POST",`/api/v1/room-scans/${scan.id}/measurements`,admin,{roomId,surfaceId,measurementType:type,source:"human_correction",originalValue:value,originalUnit:"m",capturedAt:"2026-07-28T12:00:00.000Z",idempotencyKey:`${scan.id}-${type}`,expectedVersion:scan.version});expect(r.statusCode).toBe(201);}scan=(await req("GET",`/api/v1/room-scans/${scan.id}`)).json().data;r=await req("POST",`/api/v1/room-scans/${scan.id}/complete-capture`,admin,{expectedVersion:scan.version});expect(r.statusCode).toBe(200);expect(r.json().data.completeness.status).toBe("complete");expect((await req("GET",`/api/v1/room-scans/${scan.id}/quantities`)).json().data.find((x:any)=>x.type==="floor_area").value).toBe(20);});
 it("requires human review, approves, and exposes immutable snapshot boundary",async()=>{scan=(await req("GET",`/api/v1/room-scans/${scan.id}`)).json().data;let r=await req("POST",`/api/v1/room-scans/${scan.id}/submit-review`,admin,{expectedVersion:scan.version});expect(r.statusCode).toBe(400);expect(r.json().error.code).toBe("VALIDATION_ERROR");r=await req("POST",`/api/v1/room-scans/${scan.id}/review-entity`,admin,{entityType:"surface",entityId:surfaceId,decision:"confirmed",expectedVersion:scan.version});expect(r.statusCode).toBe(200);scan=r.json().data;r=await req("POST",`/api/v1/room-scans/${scan.id}/submit-review`,admin,{expectedVersion:scan.version});expect(r.statusCode).toBe(200);scan=r.json().data;r=await req("POST",`/api/v1/room-scans/${scan.id}/approve`,admin,{expectedVersion:scan.version});expect(r.statusCode).toBe(200);expect(r.json().data.contentFingerprint).toMatch(/^[a-f0-9]{64}$/);r=await req("GET",`/api/v1/room-scans/${scan.id}/approved-snapshot`);expect(r.statusCode).toBe(200);expect(r.json().data.content.quantities.length).toBeGreaterThan(0);});
});
