import{afterAll,beforeAll,describe,expect,it}from"vitest";
import{Pool,type PoolClient}from"pg";
const run=process.env.DATABASE_URL?describe:describe.skip;
run("room scanner persisted provenance and approval defense",()=>{
 const pool=new Pool({connectionString:process.env.DATABASE_URL});let fixture:any;
 beforeAll(async()=>{fixture=(await pool.query("SELECT t.id tenant_id,u.id user_id,p.id property_id FROM tenants t JOIN users u ON u.tenant_id=t.id JOIN properties p ON p.tenant_id=t.id WHERE t.slug='demo'ORDER BY u.created_at,p.created_at LIMIT 1")).rows[0];});afterAll(()=>pool.end());
 async function setup(db:PoolClient,suffix:string){const scanId=`10000000-0000-4000-8000-0000000000${suffix}`,roomId=`20000000-0000-4000-8000-0000000000${suffix}`,measurementId=`30000000-0000-4000-8000-0000000000${suffix}`,quantityId=`40000000-0000-4000-8000-0000000000${suffix}`;await db.query("INSERT INTO room_scan_sessions(id,tenant_id,property_id,status,created_by,updated_by)VALUES($1,$2,$3,'ready_for_approval',$4,$4)",[scanId,fixture.tenant_id,fixture.property_id,fixture.user_id]);await db.query("INSERT INTO room_scan_rooms(id,tenant_id,scan_id,name,created_by,updated_by)VALUES($1,$2,$3,'Dependency room',$4,$4)",[roomId,fixture.tenant_id,scanId,fixture.user_id]);await db.query("INSERT INTO room_scan_measurements(id,tenant_id,scan_id,room_id,measurement_type,source,original_value,original_unit,si_value,si_unit,verification_status,captured_at,captured_by,created_by,updated_by)VALUES($1,$2,$3,$4,'length','human_correction',1,'m',1,'m','verified',now(),$5,$5,$5)",[measurementId,fixture.tenant_id,scanId,roomId,fixture.user_id]);const dependencies=[{id:measurementId,entityType:"measurement",version:1}];await db.query("INSERT INTO room_scan_quantities(id,tenant_id,scan_id,room_id,quantity_type,value,unit,formula_id,input_references,source_versions,calculation_version,created_by,updated_by)VALUES($1,$2,$3,$4,'room_perimeter',1,'m','test.formula',$5,$5,'room-geometry-v1',$6,$6)",[quantityId,fixture.tenant_id,scanId,roomId,JSON.stringify(dependencies),fixture.user_id]);return{scanId,roomId,measurementId,quantityId,dependencies};}
 const content=(x:any)=>({quantities:[{id:x.quantityId,roomId:x.roomId,type:"room_perimeter",value:1,unit:"m",formulaId:"test.formula",inputReferences:x.dependencies,calculationVersion:"room-geometry-v1"}]});
 it("approved snapshot retains typed source versions",async()=>{const row=(await pool.query("SELECT content FROM approved_room_scan_snapshots WHERE id='00000000-0000-4000-8000-000000000824'")).rows[0];expect(row.content.quantities[0].inputReferences).toEqual([{id:"00000000-0000-4000-8000-000000000827",entityType:"measurement",version:1}]);});
 it("DB trigger rejects a stale source version",async()=>{const db=await pool.connect();try{await db.query("BEGIN");const x=await setup(db,"31");await db.query("UPDATE room_scan_measurements SET version=2 WHERE id=$1",[x.measurementId]);await expect(db.query("INSERT INTO approved_room_scan_snapshots(tenant_id,scan_id,property_id,scan_version,content,content_fingerprint,calculation_version,approved_by)VALUES($1,$2,$3,1,$4,repeat('b',64),'room-geometry-v1',$5)",[fixture.tenant_id,x.scanId,fixture.property_id,JSON.stringify(content(x)),fixture.user_id])).rejects.toThrow(/SNAPSHOT_DEPENDENCY_INVALID/);await db.query("ROLLBACK");}finally{db.release();}});
 it("rejects cross-scan, unsupported, missing-version and duplicate dependencies",async()=>{const db=await pool.connect();try{await db.query("BEGIN");const a=await setup(db,"32"),b=await setup(db,"33");const insert=(dependencies:any[])=>db.query("INSERT INTO room_scan_quantities(tenant_id,scan_id,room_id,quantity_type,value,unit,formula_id,input_references,source_versions,calculation_version,created_by,updated_by)VALUES($1,$2,$3,'room_perimeter',1,'m','test',$4,$4,'room-geometry-v1',$5,$5)",[fixture.tenant_id,b.scanId,b.roomId,JSON.stringify(dependencies),fixture.user_id]);await expect(insert([{id:a.measurementId,entityType:"measurement",version:1}])).rejects.toThrow(/QUANTITY_SOURCE_VERSION_MISMATCH/);await db.query("ROLLBACK");await db.query("BEGIN");const c=await setup(db,"34");await expect(db.query("INSERT INTO room_scan_quantities(tenant_id,scan_id,room_id,quantity_type,value,unit,formula_id,input_references,source_versions,calculation_version,created_by,updated_by)VALUES($1,$2,$3,'room_perimeter',1,'m','test',$4,$4,'room-geometry-v1',$5,$5)",[fixture.tenant_id,c.scanId,c.roomId,JSON.stringify([{id:c.measurementId,entityType:"material",version:1}]),fixture.user_id])).rejects.toThrow(/QUANTITY_PROVENANCE_INCOMPLETE/);await db.query("ROLLBACK");}finally{db.release();}});
 it("invalidation archives and removes the working quantity atomically",async()=>{const db=await pool.connect();try{await db.query("BEGIN");const x=await setup(db,"35");await db.query("UPDATE room_scan_quantities SET validity_status='invalidated',invalidated_at=now(),invalidated_by=$1,invalidation_reason='review_rejected',updated_by=$1 WHERE id=$2",[fixture.user_id,x.quantityId]);expect((await db.query("SELECT 1 FROM room_scan_quantities WHERE id=$1",[x.quantityId])).rowCount).toBe(0);expect((await db.query("SELECT terminal_status,source_versions FROM room_scan_quantity_history WHERE quantity_id=$1",[x.quantityId])).rows[0]).toMatchObject({terminal_status:"invalidated",source_versions:x.dependencies});await db.query("ROLLBACK");}finally{db.release();}});
});
