import{describe,expect,it}from"vitest";import{normalizeSpatialProposal,spatialCapabilities,spatialRoomGeometry,validateSpatialContour,verifiedWorkQuantities,type SpatialPoint}from"../src/domain/room-scanner/spatial-geometry.js";
const points:SpatialPoint[]=[{id:"a",x:0,y:0,z:0,state:"confirmed",coordinateSystem:"room-local-m",version:1},{id:"b",x:4,y:0,z:0,state:"confirmed",coordinateSystem:"room-local-m",version:1},{id:"c",x:4,y:3,z:0,state:"confirmed",coordinateSystem:"room-local-m",version:1},{id:"d",x:0,y:3,z:0,state:"confirmed",coordinateSystem:"room-local-m",version:1}];
describe("Spatial Room Scanner geometry",()=>{
 it("normalizes point-to-point distance without invented precision",()=>expect(normalizeSpatialProposal({providerType:"test_adapter",coordinateSystem:"room-local-m",start:{x:0,y:0,z:0},end:{x:3,y:4,z:0},uncertaintyM:.02,confidence:.95,trackingQuality:"stable",calibrationState:"complete",capturedAt:"2026-08-06T10:00:00.000Z"})).toMatchObject({measuredDistanceM:5,accuracyClass:"spatial_standard",requiresHumanConfirmation:true}));
 it("rejects missing calibration, lost tracking and implausible distance",()=>{const p:any={providerType:"calibrated_camera",coordinateSystem:"x",start:{x:0,y:0,z:0},end:{x:1,y:0,z:0},uncertaintyM:.1,confidence:.5,trackingQuality:"stable",calibrationState:"failed",capturedAt:"2026-08-06T10:00:00.000Z"};expect(()=>normalizeSpatialProposal(p)).toThrow(/CALIBRATION/);expect(()=>normalizeSpatialProposal({...p,calibrationState:"complete",trackingQuality:"lost"})).toThrow(/TRACKING/);expect(()=>normalizeSpatialProposal({...p,calibrationState:"complete",trackingQuality:"stable",end:{x:0,y:0,z:0}})).toThrow(/DISTANCE/)});
 it("validates closed simple contours and rejects duplicate, unconfirmed and self-intersecting points",()=>{expect(validateSpatialContour(points,2.7)).toEqual({valid:true,issues:[]});expect(validateSpatialContour([...points.slice(0,3),{...points[0],id:"duplicate"}],2.7).issues.some(x=>x.code==="SPATIAL_DUPLICATE_POINT")).toBe(true);expect(validateSpatialContour(points.map((x,i)=>i?x:{...x,state:"proposed"}),2.7).issues.some(x=>x.code==="SPATIAL_POINT_UNCONFIRMED")).toBe(true);const bow=[points[0],points[2],points[1],points[3]];expect(validateSpatialContour(bow,2.7).issues.some(x=>x.code==="SPATIAL_SELF_INTERSECTION")).toBe(true)});
 it("calculates walls, floor, ceiling, perimeter, volume and gross/net areas",()=>{const g=spatialRoomGeometry(points,2.5,[{id:"door",wallId:"wall-1",type:"door",offsetM:1,widthM:1,heightM:2,sillHeightM:0,revealDepthM:.2,version:1},{id:"window",wallId:"wall-2",type:"window",offsetM:.5,widthM:1,heightM:1,sillHeightM:1,revealDepthM:.2,version:1}]);expect(g.walls.map(x=>x.lengthM)).toEqual([4,3,4,3]);expect(g.quantities).toMatchObject({floorAreaM2:12,ceilingAreaM2:12,perimeterM:14,volumeM3:30,grossWallAreaM2:35,openingAreaM2:3,netWallAreaM2:32,revealAreaM2:2,skirtingLengthM:13,internalCornerLengthM:10,externalCornerLengthM:0})});
 it("blocks openings outside a wall and overlapping openings",()=>{expect(()=>spatialRoomGeometry(points,2.5,[{id:"x",wallId:"wall-1",type:"door",offsetM:3.5,widthM:1,heightM:2,sillHeightM:0,version:1}])).toThrow(/OUTSIDE/);expect(()=>spatialRoomGeometry(points,2.5,[{id:"x",wallId:"wall-1",type:"door",offsetM:.5,widthM:1,heightM:2,sillHeightM:0,version:1},{id:"y",wallId:"wall-1",type:"window",offsetM:1,widthM:1,heightM:1,sillHeightM:1,version:1}])).toThrow(/OVERLAP/)});
 it("emits work quantities only, with provenance and no material or price fields",()=>{const q=verifiedWorkQuantities(spatialRoomGeometry(points,2.5),points.map(x=>x.id));expect(q).toHaveLength(21);expect(q.find(x=>x.type==="plastering_net_wall_area")).toMatchObject({value:35,unit:"m2",formulaId:"spatial.plastering_net_wall_area",calculatorVersion:"spatial-geometry-v1"});expect(q.every(x=>!["price","product","brand","bagCount","consumptionCoefficient"].some(field=>field in x))).toBe(true)});
 it("reports all native/browser spatial modes honestly unavailable",()=>{const c=spatialCapabilities({platform:"ios",camera:true,webXrDepth:true,nativeProvider:false});expect(c.modes.filter(x=>["manual","external_laser"].includes(x.mode)).every(x=>x.supported)).toBe(true);expect(c.modes.filter(x=>!["manual","external_laser"].includes(x.mode)).every(x=>!x.supported&&x.unsupportedReason)).toBe(true);expect(c.realDeviceVerified).toBe(false)});
});
