import{describe,expect,it,vi}from"vitest";import{TelegramBotProvider}from"../src/infrastructure/communication/telegram-bot-provider.js";import{InvalidTelegramWebhookSecretError,TelegramWebhookService}from"../src/application/communication/telegram-webhook-service.js";
const update={update_id:42,message:{message_id:7,date:1_700_000_000,text:"Hello",from:{id:101},chat:{id:202}}};
describe("Telegram Bot API provider",()=>{
 it("stays PARTIAL until credentials and owner verification are complete",()=>{expect(new TelegramBotProvider({verified:false}).truth).toBe("PARTIAL");expect(new TelegramBotProvider({botToken:"token",webhookSecret:"secret",verified:true},vi.fn()as any).truth).toBe("REAL")});
 it("maps Telegram update identity, thread and timestamp without inventing context",async()=>{const provider=new TelegramBotProvider({botToken:"token",webhookSecret:"secret",verified:true},vi.fn()as any),result=await provider.mapInbound(update);expect(result).toMatchObject({providerEventId:"42",providerMessageId:"7",providerThreadId:"202",channel:"telegram",from:"101",to:["202"],body:"Hello",attachmentReferences:[]});expect(result).not.toHaveProperty("projectId")});
 it("uses a real Bot API message_id as the outbound acceptance authority",async()=>{const fetcher=vi.fn().mockResolvedValue({ok:true,json:async()=>({ok:true,result:{message_id:88}})}),provider=new TelegramBotProvider({botToken:"token",webhookSecret:"secret",verified:true},fetcher as any),result=await provider.send({idempotencyKey:"id",channel:"telegram",to:["202"],cc:[],body:"Hello",attachments:[],tenantId:"tenant",messageId:"message"});expect(result.providerMessageId).toBe("88");expect(fetcher).toHaveBeenCalledWith(expect.stringContaining("/sendMessage"),expect.objectContaining({method:"POST"}))});
 it("rejects an invalid webhook secret before identity resolution",async()=>{const provider=new TelegramBotProvider({botToken:"token",webhookSecret:"secret",verified:true},vi.fn()as any),identities={resolve:vi.fn()},communications={ingest:vi.fn()},service=new TelegramWebhookService(provider,communications as any,identities as any);await expect(service.handle(update,"wrong")).rejects.toBeInstanceOf(InvalidTelegramWebhookSecretError);expect(identities.resolve).not.toHaveBeenCalled()});
 it("does not ingest unresolved identities and ingests a verified mapping once",async()=>{const provider=new TelegramBotProvider({botToken:"token",webhookSecret:"secret",verified:true},vi.fn()as any),communications={ingest:vi.fn().mockResolvedValue({duplicate:false})},unresolved=new TelegramWebhookService(provider,communications as any,{resolve:vi.fn().mockResolvedValue({status:"unresolved"})}as any);expect(await unresolved.handle(update,"secret")).toMatchObject({resolutionStatus:"unresolved",humanResolutionRequired:true});expect(communications.ingest).not.toHaveBeenCalled();const identity={id:"identity",tenantId:"tenant",managedBy:"actor",externalUserId:"101",externalChatId:"202",projectId:"project",clientId:"client",verificationState:"verified"},resolved=new TelegramWebhookService(provider,communications as any,{resolve:vi.fn().mockResolvedValue({status:"resolved",identity})}as any);expect(await resolved.handle(update,"secret")).toMatchObject({resolutionStatus:"resolved",duplicate:false});expect(communications.ingest).toHaveBeenCalledWith(expect.objectContaining({tenantId:"tenant"}),"telegram",expect.objectContaining({providerEventId:"42"}),expect.objectContaining({providerIdentityId:"identity",projectId:"project",clientId:"client"}))});
});
