import{describe,expect,it,vi}from"vitest";
import{VoiceBridgeService}from"../src/application/voice-bridge/voice-bridge-service.js";
import{VoiceProviderRegistry,unavailableVoiceRegistry}from"../src/application/voice-bridge/voice-provider.js";
import{AzureVoiceProvider}from"../src/infrastructure/voice-bridge/azure-speech-provider.js";

const actor={id:"00000000-0000-4000-8000-000000000001",tenantId:"00000000-0000-4000-8000-000000000002",permissions:["voice.use","voice.translate","voice.command","ai_secretary.use"],correlationId:"00000000-0000-4000-8000-000000000003"};
const secondUser="00000000-0000-4000-8000-000000000099";
const providers=(failure?:Error)=>new VoiceProviderRegistry({
  recognition:{id:"test",truth:"REAL",reason:"test",recognize:failure?vi.fn().mockRejectedValue(failure):vi.fn().mockResolvedValue({text:"Dzień dobry",detectedLanguage:"pl-PL",providerReference:"r"})},
  translation:{id:"test",truth:"REAL",reason:"test",translate:vi.fn().mockResolvedValue({text:"Добрый день",sourceLanguage:"pl",targetLanguage:"ru",providerReference:"t",machineTranslation:true})},
  synthesis:{id:"test",truth:"REAL",reason:"test",synthesize:vi.fn().mockResolvedValue({audio:Buffer.from("speech"),contentType:"audio/mpeg",providerReference:"s"})}
});

describe("OMNIRO Voice Bridge",()=>{
  it("reports unavailable and credential-pending providers truthfully",()=>{expect(unavailableVoiceRegistry().status()).toEqual(expect.arrayContaining([expect.objectContaining({truth:"UNAVAILABLE"})]));expect(new AzureVoiceProvider({verified:false}).truth).toBe("PARTIAL")});
  it("processes recognition translation and synthesis without persisting audio content",async()=>{const audit={record:vi.fn()},commands={execute:vi.fn()},service=new VoiceBridgeService(providers(),audit,commands),session=await service.start(actor,{mode:"conversation_translation",participants:[{userId:actor.id,speakingLanguage:"pl-PL",listeningLanguage:"ru-RU"}]}),result=await service.process(actor,session.id,{audioBase64:Buffer.from("ephemeral").toString("base64"),contentType:"audio/wav",speakingLanguage:"pl-PL",listeningLanguage:"ru-RU"});expect(result).toMatchObject({translatedText:"Добрый день",machineTranslation:true,recording:"PROHIBITED_BY_ARCHITECTURE"});expect(JSON.stringify(audit.record.mock.calls)).not.toContain("ephemeral");await service.end(actor,session.id);await expect(service.process(actor,session.id,{audioBase64:"eA==",contentType:"audio/wav",listeningLanguage:"ru-RU"})).rejects.toThrow()});
  it("honors a manual speaking-language override",async()=>{const registry=providers(),service=new VoiceBridgeService(registry,{record:vi.fn()},{execute:vi.fn()}),session=await service.start(actor,{mode:"conversation_translation",participants:[{userId:actor.id,listeningLanguage:"ru-RU"}]});await service.process(actor,session.id,{audioBase64:"eA==",contentType:"audio/wav",speakingLanguage:"de-DE",listeningLanguage:"ru-RU"});expect(registry.get().translation.translate).toHaveBeenCalledWith(expect.objectContaining({sourceLanguage:"de",targetLanguage:"ru"}))});
  it("allows verified same-tenant participants and rejects unverified participants",async()=>{const allowed={allBelongToTenant:vi.fn().mockResolvedValue(true)},denied={allBelongToTenant:vi.fn().mockResolvedValue(false)},input={mode:"conversation_translation"as const,participants:[{userId:actor.id,listeningLanguage:"pl-PL"},{userId:secondUser,listeningLanguage:"ru-RU"}]};await expect(new VoiceBridgeService(providers(),{record:vi.fn()},{execute:vi.fn()},undefined,allowed).start(actor,input)).resolves.toMatchObject({participants:input.participants});await expect(new VoiceBridgeService(providers(),{record:vi.fn()},{execute:vi.fn()},undefined,denied).start(actor,input)).rejects.toThrow()});
  it("forwards recognized text to the existing AI Secretary command port",async()=>{const audit={record:vi.fn()},commands={execute:vi.fn().mockResolvedValue({status:"completed",requiredHumanAction:"preserved"})},service=new VoiceBridgeService(providers(),audit,commands),session=await service.start(actor,{mode:"voice_command",participants:[{userId:actor.id,listeningLanguage:"pl-PL"}]});await service.process(actor,session.id,{audioBase64:"eA==",contentType:"audio/wav",listeningLanguage:"pl-PL",projectId:"00000000-0000-4000-8000-000000000004"});expect(commands.execute).toHaveBeenCalledWith(actor,expect.objectContaining({text:"Dzień dobry",inputMode:"voice"}))});
  it("preserves permission and entitlement boundaries",async()=>{await expect(new VoiceBridgeService(providers(),{record:vi.fn()},{execute:vi.fn()}).start({...actor,permissions:["voice.use"]},{mode:"conversation_translation",participants:[{userId:actor.id,listeningLanguage:"ru-RU"}]})).rejects.toThrow();const disabled={enabled:vi.fn().mockResolvedValue(false)};await expect(new VoiceBridgeService(providers(),{record:vi.fn()},{execute:vi.fn()},disabled).start(actor,{mode:"voice_command",participants:[{userId:actor.id,listeningLanguage:"pl-PL"}]})).rejects.toThrow()});
  it("fails closed when the provider or language contract fails",async()=>{const service=new VoiceBridgeService(providers(new Error("NETWORK_INTERRUPTED")),{record:vi.fn()},{execute:vi.fn()}),session=await service.start(actor,{mode:"conversation_translation",participants:[{userId:actor.id,listeningLanguage:"ru-RU"}]});await expect(service.process(actor,session.id,{audioBase64:"eA==",contentType:"audio/wav",listeningLanguage:"ru-RU"})).rejects.toThrow("NETWORK_INTERRUPTED");await expect(service.process(actor,session.id,{audioBase64:"eA==",contentType:"audio/wav",listeningLanguage:"not-a-language"})).rejects.toThrow()});
  it("expires sessions and enforces a technical chunk limit",async()=>{const expired=new VoiceBridgeService(providers(),{record:vi.fn()},{execute:vi.fn()},undefined,undefined,2_000_000,1,-1),session=await expired.start(actor,{mode:"voice_command",participants:[{userId:actor.id,listeningLanguage:"pl-PL"}]});await expect(expired.process(actor,session.id,{audioBase64:"eA==",contentType:"audio/wav",listeningLanguage:"pl-PL"})).rejects.toThrow("SESSION_EXPIRED");const limited=new VoiceBridgeService(providers(),{record:vi.fn()},{execute:vi.fn().mockResolvedValue({})},undefined,undefined,2_000_000,1),active=await limited.start(actor,{mode:"voice_command",participants:[{userId:actor.id,listeningLanguage:"pl-PL"}]});await limited.process(actor,active.id,{audioBase64:"eA==",contentType:"audio/wav",listeningLanguage:"pl-PL"});await expect(limited.process(actor,active.id,{audioBase64:"eA==",contentType:"audio/wav",listeningLanguage:"pl-PL"})).rejects.toThrow("PROVIDER_RATE_LIMIT")});
});
