import {afterAll,beforeAll,describe,expect,it} from "vitest";
import {buildServer} from "../src/server.js";
const run=process.env.DATABASE_URL?describe:describe.skip;
run("construction work catalog API",()=>{
 const app=buildServer();let admin="",employee="",second="",root:any,child:any,item:any,unitId="";
 beforeAll(async()=>{const login=async(tenantSlug:string,email:string)=>(await app.inject({method:"POST",url:"/api/v1/auth/login",payload:{tenantSlug,email,password:"DemoPassword!2026"}})).json().data.accessToken;admin=await login("demo","admin@demo.odls");employee=await login("demo","employee@demo.odls");second=await login("second","admin@second.odls");const units=(await req("GET","/api/v1/measurement-units?pageSize=100",admin)).json().data;unitId=units.find((x:any)=>x.code==="M2").id;});
 afterAll(()=>app.close());const req=(method:any,url:string,token=admin,payload?:any):any=>app.inject({method,url,headers:{authorization:`Bearer ${token}`},payload});
 it("reads seeded hierarchy and deterministically filters items",async()=>{const tree=await req("GET","/api/v1/work-categories/tree");expect(tree.statusCode).toBe(200);expect(tree.json().data.length).toBeGreaterThanOrEqual(4);const list=await req("GET","/api/v1/work-items?search=wall&dimension=area&active=true&sortBy=code&sortOrder=asc&page=1&pageSize=5");expect(list.statusCode).toBe(200);expect(list.json().data.every((x:any)=>x.measurementDimension==="area"&&x.status==="active")).toBe(true);expect((await req("GET","/api/v1/work-items?sortBy=bad")).statusCode).toBe(400);});
 it("creates, updates, moves and protects category hierarchy",async()=>{const suffix=Date.now();let r=await req("POST","/api/v1/work-categories",admin,{code:`ROOT_${suffix}`,displayName:"Custom root",parentId:null,sortOrder:500});expect(r.statusCode).toBe(201);root=r.json().data;r=await req("POST","/api/v1/work-categories",admin,{code:`CHILD_${suffix}`,displayName:"Custom child",parentId:root.id,sortOrder:1});expect(r.statusCode).toBe(201);child=r.json().data;expect((await req("POST",`/api/v1/work-categories/${root.id}/move`,admin,{expectedVersion:root.version,parentId:child.id})).statusCode).toBe(422);r=await req("PATCH",`/api/v1/work-categories/${child.id}`,admin,{expectedVersion:child.version,displayName:"Edited child"});expect(r.statusCode).toBe(200);child=r.json().data;expect((await req("PATCH",`/api/v1/work-categories/${child.id}`,admin,{expectedVersion:1,displayName:"Stale"})).statusCode).toBe(409);});
 it("enforces category duplicate codes per tenant",async()=>{const code=`SHARED_${Date.now()}`,payload={code,displayName:"Shared",parentId:null,sortOrder:700};expect((await req("POST","/api/v1/work-categories",admin,payload)).statusCode).toBe(201);expect((await req("POST","/api/v1/work-categories",admin,payload)).statusCode).toBe(409);expect((await req("POST","/api/v1/work-categories",second,payload)).statusCode).toBe(201);});
 it("enforces the four-level hierarchy maximum",async()=>{let parent:string|null=null;for(let level=0;level<4;level++){const r=await req("POST","/api/v1/work-categories",admin,{code:`DEPTH_${Date.now()}_${level}`,displayName:`Depth ${level}`,parentId:parent,sortOrder:800+level});expect(r.statusCode).toBe(201);parent=r.json().data.id;}expect((await req("POST","/api/v1/work-categories",admin,{code:`DEPTH_${Date.now()}_4`,displayName:"Too deep",parentId:parent,sortOrder:805})).statusCode).toBe(400);});
 it("creates and updates a work item using a live unit",async()=>{const code=`WORK_${Date.now()}`;let r=await req("POST","/api/v1/work-items",admin,{code,displayName:"Custom work",categoryId:child.id,measurementUnitId:unitId,quantityPrecision:3});expect(r.statusCode).toBe(201);item=r.json().data;expect((await req("GET",`/api/v1/work-items/${item.id}`)).statusCode).toBe(200);r=await req("PATCH",`/api/v1/work-items/${item.id}`,admin,{expectedVersion:item.version,displayName:"Edited work"});expect(r.statusCode).toBe(200);item=r.json().data;expect((await req("PATCH",`/api/v1/work-items/${item.id}`,admin,{expectedVersion:1,displayName:"Stale"})).statusCode).toBe(409);});
 it("protects active relationships and status transitions",async()=>{expect((await req("POST",`/api/v1/work-categories/${child.id}/deactivate`,admin,{expectedVersion:child.version})).statusCode).toBe(422);let r=await req("POST",`/api/v1/work-items/${item.id}/deactivate`,admin,{expectedVersion:item.version});expect(r.statusCode).toBe(200);item=r.json().data;r=await req("POST",`/api/v1/work-categories/${child.id}/deactivate`,admin,{expectedVersion:child.version});expect(r.statusCode).toBe(200);child=r.json().data;expect((await req("POST",`/api/v1/work-items/${item.id}/activate`,admin,{expectedVersion:item.version})).statusCode).toBe(422);});
 it("rejects inactive measurement units for new work items",async()=>{let r=await req("POST","/api/v1/measurement-units",admin,{code:`INACTIVE_${Date.now()}`,symbol:"iu",displayName:"Inactive unit",dimension:"custom",unitSystem:"custom",decimalPrecision:2});expect(r.statusCode).toBe(201);const unit=r.json().data;r=await req("POST",`/api/v1/measurement-units/${unit.id}/deactivate`,admin,{expectedVersion:unit.version});expect(r.statusCode).toBe(200);expect((await req("POST","/api/v1/work-items",admin,{code:`INACTIVE_WORK_${Date.now()}`,displayName:"Invalid unit work",categoryId:root.id,measurementUnitId:unit.id,quantityPrecision:2})).statusCode).toBe(422);});
 it("hides cross-tenant IDs and rejects cross-tenant references",async()=>{expect((await req("GET",`/api/v1/work-categories/${root.id}`,second)).statusCode).toBe(404);expect((await req("POST","/api/v1/work-items",second,{code:`CROSS_${Date.now()}`,displayName:"Cross",categoryId:root.id,measurementUnitId:unitId,quantityPrecision:2})).statusCode).toBe(404);});
 it("allows operational reads but forbids mutations",async()=>{expect((await req("GET","/api/v1/work-items",employee)).statusCode).toBe(200);expect((await req("POST","/api/v1/work-categories",employee,{code:"NO_WRITE",displayName:"No",parentId:null,sortOrder:1})).statusCode).toBe(403);});
});
