import type {Pool} from "pg";
import {randomUUID} from "node:crypto";
import type {DocumentEntityType} from "@odls/contracts";
import {inTenantTransaction} from "../../infrastructure/transaction.js";
import {DocumentRepository} from "../../infrastructure/document/document-repository.js";
import {LocalDocumentStorage} from "../../infrastructure/document/local-document-storage.js";
import {S3CompatibleDocumentStorage} from "../../infrastructure/document/s3-compatible-document-storage.js";
import type {FileStorage} from "./file-storage.js";
import {requireDocument,type DocumentActor} from "../../authorization/document-policy.js";
import {domainErrors} from "../../domain/errors.js";
import {sanitizeScannerFilename,validateCategory,validateDocumentType,validateScannerFile} from "../../domain/document/document-rules.js";
export class DocumentService{
 private repo=new DocumentRepository();
 constructor(private pool:Pool,private storage:FileStorage=process.env.OBJECT_STORAGE_ENDPOINT?new S3CompatibleDocumentStorage():new LocalDocumentStorage(),private maxBytes=Number(process.env.SCANNER_MAX_UPLOAD_BYTES??25*1024*1024),private compensationFailure:(event:{event:string;errorName:string})=>void=event=>console.warn(event)){}
 private async compensate(key:string){try{await this.storage.deleteObject({key});}catch(error){this.compensationFailure({event:"document.storage_compensation_failed",errorName:error instanceof Error?error.name:"UnknownError"});}}
 private async failure(a:DocumentActor,e:unknown,id?:string){if(!(e instanceof Error)||!("code" in e))return;const map:any={FORBIDDEN:"document.permission_denied",VERSION_CONFLICT:"document.version_conflict",ENTITY_ARCHIVED:"document.archived_mutation_denied",INVALID_RELATIONSHIP:"document.invalid_relationship",VALIDATION_ERROR:"document.file_rejected"};const action=map[(e as any).code];if(action)await inTenantTransaction(this.pool,a.tenantId,db=>this.repo.audit(db,a,action,id??randomUUID(),{code:(e as any).code}));}
 private async run<T>(a:DocumentActor,id:string|undefined,fn:()=>Promise<T>){try{return await fn();}catch(e){await this.failure(a,e,id);throw e;}}
 upload(a:DocumentActor,meta:{title?:string;documentType?:string;sourceType?:"upload"|"scanner"|"import";category?:string;description?:string;entityType?:DocumentEntityType;entityId?:string},file:{filename:string;mimetype:string;bytes:Buffer}){return this.run(a,undefined,async()=>{requireDocument(a,"upload");const info=validateScannerFile(file.filename,file.mimetype,file.bytes,this.maxBytes),id=randomUUID(),versionId=randomUUID(),fileObjectId=randomUUID(),key=`tenants/${a.tenantId}/documents/${id}/versions/${versionId}/${sanitizeScannerFilename(info.originalFilename)}`,stored=await this.storage.putObject({key,body:file.bytes,contentType:info.mimeType,checksumSha256:info.checksum});try{return await inTenantTransaction(this.pool,a.tenantId,async db=>{if(meta.entityType&&meta.entityId&&!await this.repo.targetExists(db,a.tenantId,meta.entityType,meta.entityId))throw domainErrors.notFound();const documentType=validateDocumentType(meta.documentType??"unknown"),category=validateCategory(meta.category??(documentType==="contract"||documentType==="invoice"||documentType==="receipt"||documentType==="photo"?documentType:"other"));await db.query(`INSERT INTO file_objects(id,tenant_id,storage_provider,storage_bucket,storage_key,original_filename,mime_type,size_bytes,checksum_sha256,status,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'available',$10)`,[fileObjectId,a.tenantId,stored.provider,stored.bucket,stored.key,info.originalFilename,info.mimeType,info.fileSize,info.checksum,a.id]);await db.query(`INSERT INTO documents(id,tenant_id,title,document_type,source_type,status,category,description,current_version_no,current_version_id,ocr_status,ai_processing_status,created_by,updated_by) VALUES($1,$2,$3,$4,$5,'active',$6,$7,1,NULL,'not_requested','not_requested',$8,$8)`,[id,a.tenantId,meta.title?.trim()||info.originalFilename,documentType,meta.sourceType??"upload",category,meta.description??null,a.id]);await db.query(`INSERT INTO document_versions(id,tenant_id,document_id,version_no,original_filename,storage_key,mime_type,extension,file_size,checksum,uploaded_by,file_object_id) VALUES($1,$2,$3,1,$4,$5,$6,$7,$8,$9,$10,$11)`,[versionId,a.tenantId,id,info.originalFilename,key,info.mimeType,info.extension,info.fileSize,info.checksum,a.id,fileObjectId]);await db.query(`UPDATE documents SET current_version_id=$1 WHERE tenant_id=$2 AND id=$3`,[versionId,a.tenantId,id]);if(meta.entityType&&meta.entityId)await db.query(`INSERT INTO document_links(tenant_id,document_id,entity_type,entity_id,created_by) VALUES($1,$2,$3,$4,$5)`,[a.tenantId,id,meta.entityType,meta.entityId,a.id]);const row=await this.repo.document(db,a.tenantId,id);await this.repo.audit(db,a,"document.uploaded",id,{versionId,documentVersion:1,filename:info.originalFilename,mimeType:info.mimeType,size:info.fileSize,checksum:info.checksum,documentType});return row;});}catch(e){await this.compensate(key);throw e;}});}
 get(a:DocumentActor,id:string){return this.run(a,id,async()=>{requireDocument(a,"read");return inTenantTransaction(this.pool,a.tenantId,async db=>{const row=await this.repo.document(db,a.tenantId,id);if(!row)throw domainErrors.notFound();return row;});});}
 list(a:DocumentActor,q:any){return this.run(a,undefined,async()=>{requireDocument(a,"read");return inTenantTransaction(this.pool,a.tenantId,db=>this.repo.list(db,a.tenantId,q));});}
 update(a:DocumentActor,id:string,input:any){return this.run(a,id,async()=>{requireDocument(a,"update");return inTenantTransaction(this.pool,a.tenantId,async db=>{const old=await this.repo.document(db,a.tenantId,id);if(!old)throw domainErrors.notFound();if(old.archivedAt)throw domainErrors.archived();if(old.version!==input.expectedVersion)throw domainErrors.conflict();const category=input.category?validateCategory(input.category):old.category,documentType=input.documentType?validateDocumentType(input.documentType):old.documentType;const changed=await db.query(`UPDATE documents SET title=$1,document_type=$2,category=$3,description=$4,updated_by=$5,updated_at=now(),version=version+1 WHERE tenant_id=$6 AND id=$7 AND version=$8`,[input.title??old.title,documentType,category,input.description===undefined?old.description:input.description,a.id,a.tenantId,id,input.expectedVersion]);if(!changed.rowCount)throw domainErrors.conflict();const row=await this.repo.document(db,a.tenantId,id);await this.repo.audit(db,a,"document.updated",id,{beforeVersion:old.version,afterVersion:row!.version,documentType});return row;});});}
 addVersion(a:DocumentActor,id:string,expectedVersion:number,file:{filename:string;mimetype:string;bytes:Buffer}){return this.run(a,id,async()=>{requireDocument(a,"upload");const info=validateScannerFile(file.filename,file.mimetype,file.bytes,this.maxBytes),versionId=randomUUID(),fileObjectId=randomUUID(),key=`tenants/${a.tenantId}/documents/${id}/versions/${versionId}/${sanitizeScannerFilename(info.originalFilename)}`,stored=await this.storage.putObject({key,body:file.bytes,contentType:info.mimeType,checksumSha256:info.checksum});try{return await inTenantTransaction(this.pool,a.tenantId,async db=>{const old=await this.repo.document(db,a.tenantId,id);if(!old)throw domainErrors.notFound();if(old.archivedAt)throw domainErrors.archived();if(old.version!==expectedVersion)throw domainErrors.conflict();const n=old.currentVersionNo+1;await db.query(`INSERT INTO file_objects(id,tenant_id,storage_provider,storage_bucket,storage_key,original_filename,mime_type,size_bytes,checksum_sha256,status,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'available',$10)`,[fileObjectId,a.tenantId,stored.provider,stored.bucket,key,info.originalFilename,info.mimeType,info.fileSize,info.checksum,a.id]);await db.query(`INSERT INTO document_versions(id,tenant_id,document_id,version_no,original_filename,storage_key,mime_type,extension,file_size,checksum,uploaded_by,file_object_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)`,[versionId,a.tenantId,id,n,info.originalFilename,key,info.mimeType,info.extension,info.fileSize,info.checksum,a.id,fileObjectId]);const changed=await db.query(`UPDATE documents SET current_version_no=$1,current_version_id=$2,version=version+1,updated_at=now(),updated_by=$3 WHERE tenant_id=$4 AND id=$5 AND version=$6`,[n,versionId,a.id,a.tenantId,id,expectedVersion]);if(!changed.rowCount)throw domainErrors.conflict();const row=await this.repo.document(db,a.tenantId,id);await this.repo.audit(db,a,"document.version_created",id,{versionId,documentVersion:n,filename:info.originalFilename,mimeType:info.mimeType,size:info.fileSize,checksum:info.checksum});return row;});}catch(e){await this.compensate(key);throw e;}});}
 versions(a:DocumentActor,id:string){return this.run(a,id,async()=>{requireDocument(a,"read");return inTenantTransaction(this.pool,a.tenantId,async db=>{if(!await this.repo.document(db,a.tenantId,id))throw domainErrors.notFound();return this.repo.versions(db,a.tenantId,id);});});}
 download(a:DocumentActor,id:string,versionId?:string){return this.run(a,id,async()=>{requireDocument(a,"download");const file=await inTenantTransaction(this.pool,a.tenantId,async db=>{const d=await this.repo.document(db,a.tenantId,id);if(!d)throw domainErrors.notFound();const versions=await this.repo.versions(db,a.tenantId,id),v=versionId?versions.find(x=>x.id===versionId):versions.find(x=>x.id===d.currentVersionId)??versions[0];if(!v)throw domainErrors.notFound();return v;});try{return {...file,bytes:await this.storage.getObject({key:file.storageKey})};}catch{throw domainErrors.notFound();}});}
 archive(a:DocumentActor,id:string,expectedVersion:number){return this.run(a,id,async()=>{requireDocument(a,"delete");return inTenantTransaction(this.pool,a.tenantId,async db=>{const old=await this.repo.document(db,a.tenantId,id);if(!old)throw domainErrors.notFound();if(old.archivedAt)throw domainErrors.archived();if(old.version!==expectedVersion)throw domainErrors.conflict();const changed=await db.query(`UPDATE documents SET status='archived',deleted_at=now(),deleted_by=$1,updated_by=$1,updated_at=now(),version=version+1 WHERE tenant_id=$2 AND id=$3 AND version=$4`,[a.id,a.tenantId,id,expectedVersion]);if(!changed.rowCount)throw domainErrors.conflict();const row=await this.repo.document(db,a.tenantId,id);await this.repo.audit(db,a,"document.archived",id,{beforeVersion:old.version,afterVersion:row!.version});return row;});});}
 addLink(a:DocumentActor,id:string,input:{entityType:DocumentEntityType;entityId:string;expectedVersion:number}){return this.run(a,id,async()=>{requireDocument(a,"update");return inTenantTransaction(this.pool,a.tenantId,async db=>{const old=await this.repo.document(db,a.tenantId,id);if(!old)throw domainErrors.notFound();if(old.archivedAt)throw domainErrors.archived();if(old.version!==input.expectedVersion)throw domainErrors.conflict();if(!await this.repo.targetExists(db,a.tenantId,input.entityType,input.entityId))throw domainErrors.notFound();await db.query(`INSERT INTO document_links(tenant_id,document_id,entity_type,entity_id,created_by) VALUES($1,$2,$3,$4,$5)`,[a.tenantId,id,input.entityType,input.entityId,a.id]);await db.query(`UPDATE documents SET version=version+1,updated_at=now(),updated_by=$1 WHERE tenant_id=$2 AND id=$3`,[a.id,a.tenantId,id]);const row=await this.repo.document(db,a.tenantId,id);await this.repo.audit(db,a,"document.metadata_updated",id,{before:old,after:row});return row;});});}
 removeLink(a:DocumentActor,id:string,linkId:string,expectedVersion:number){return this.run(a,id,async()=>{requireDocument(a,"update");return inTenantTransaction(this.pool,a.tenantId,async db=>{const old=await this.repo.document(db,a.tenantId,id);if(!old)throw domainErrors.notFound();if(old.archivedAt)throw domainErrors.archived();if(old.version!==expectedVersion)throw domainErrors.conflict();if(old.links.length<=1)throw domainErrors.validation("A document must retain at least one entity link");if(!(await db.query(`DELETE FROM document_links WHERE tenant_id=$1 AND document_id=$2 AND id=$3`,[a.tenantId,id,linkId])).rowCount)throw domainErrors.notFound();await db.query(`UPDATE documents SET version=version+1,updated_at=now(),updated_by=$1 WHERE tenant_id=$2 AND id=$3`,[a.id,a.tenantId,id]);const row=await this.repo.document(db,a.tenantId,id);await this.repo.audit(db,a,"document.metadata_updated",id,{before:old,after:row});return row;});});}
}
