import type {Pool} from "pg";
import {randomUUID} from "node:crypto";
import type {DocumentEntityType} from "@odls/contracts";
import {inTenantTransaction} from "../../infrastructure/transaction.js";
import {DocumentRepository} from "../../infrastructure/document/document-repository.js";
import {LocalDocumentStorage} from "../../infrastructure/document/local-document-storage.js";
import {requireDocument,type DocumentActor} from "../../authorization/document-policy.js";
import {domainErrors} from "../../domain/errors.js";
import {validateCategory,validateFile} from "../../domain/document/document-rules.js";
export class DocumentService{
 private repo=new DocumentRepository();
 constructor(private pool:Pool,private storage=new LocalDocumentStorage(),private maxBytes=Number(process.env.DOCUMENT_MAX_BYTES??10_485_760)){}
 private async failure(a:DocumentActor,e:unknown,id?:string){if(!(e instanceof Error)||!("code" in e))return;const map:any={FORBIDDEN:"document.permission_denied",VERSION_CONFLICT:"document.version_conflict",ENTITY_ARCHIVED:"document.archived_mutation_denied",INVALID_RELATIONSHIP:"document.invalid_relationship",VALIDATION_ERROR:"document.file_rejected"};const action=map[(e as any).code];if(action)await inTenantTransaction(this.pool,a.tenantId,db=>this.repo.audit(db,a,action,id??randomUUID(),{code:(e as any).code}));}
 private async run<T>(a:DocumentActor,id:string|undefined,fn:()=>Promise<T>){try{return await fn();}catch(e){await this.failure(a,e,id);throw e;}}
 upload(a:DocumentActor,meta:{category:string;description?:string;entityType:DocumentEntityType;entityId:string},file:{filename:string;mimetype:string;bytes:Buffer}){return this.run(a,undefined,async()=>{requireDocument(a,"create");const info=validateFile(file.filename,file.mimetype,file.bytes,this.maxBytes),key=await this.storage.write(a.tenantId,file.bytes),id=randomUUID();try{return await inTenantTransaction(this.pool,a.tenantId,async db=>{if(!await this.repo.targetExists(db,a.tenantId,meta.entityType,meta.entityId))throw domainErrors.notFound();const category=validateCategory(meta.category);await db.query(`INSERT INTO documents(id,tenant_id,category,description,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$5)`,[id,a.tenantId,category,meta.description??null,a.id]);await db.query(`INSERT INTO document_versions(tenant_id,document_id,version_no,original_filename,storage_key,mime_type,extension,file_size,checksum,uploaded_by) VALUES($1,$2,1,$3,$4,$5,$6,$7,$8,$9)`,[a.tenantId,id,info.originalFilename,key,info.mimeType,info.extension,info.fileSize,info.checksum,a.id]);await db.query(`INSERT INTO document_links(tenant_id,document_id,entity_type,entity_id,created_by) VALUES($1,$2,$3,$4,$5)`,[a.tenantId,id,meta.entityType,meta.entityId,a.id]);const row=await this.repo.document(db,a.tenantId,id);await this.repo.audit(db,a,"document.uploaded",id,{documentVersion:1,links:row!.links,filename:info.originalFilename,mimeType:info.mimeType,size:info.fileSize,checksum:info.checksum});return row;});}catch(e){await this.storage.remove(a.tenantId,key);throw e;}});}
 get(a:DocumentActor,id:string){return this.run(a,id,async()=>{requireDocument(a,"read");return inTenantTransaction(this.pool,a.tenantId,async db=>{const row=await this.repo.document(db,a.tenantId,id);if(!row)throw domainErrors.notFound();return row;});});}
 list(a:DocumentActor,q:any){return this.run(a,undefined,async()=>{requireDocument(a,"read");return inTenantTransaction(this.pool,a.tenantId,db=>this.repo.list(db,a.tenantId,q));});}
 update(a:DocumentActor,id:string,input:any){return this.run(a,id,async()=>{requireDocument(a,"update");return inTenantTransaction(this.pool,a.tenantId,async db=>{const old=await this.repo.document(db,a.tenantId,id);if(!old)throw domainErrors.notFound();if(old.archivedAt)throw domainErrors.archived();if(old.version!==input.expectedVersion)throw domainErrors.conflict();const category=input.category?validateCategory(input.category):old.category;await db.query(`UPDATE documents SET category=$1,description=$2,updated_by=$3,updated_at=now(),version=version+1 WHERE tenant_id=$4 AND id=$5`,[category,input.description===undefined?old.description:input.description,a.id,a.tenantId,id]);const row=await this.repo.document(db,a.tenantId,id);await this.repo.audit(db,a,"document.metadata_updated",id,{before:old,after:row});return row;});});}
 addVersion(a:DocumentActor,id:string,expectedVersion:number,file:{filename:string;mimetype:string;bytes:Buffer}){return this.run(a,id,async()=>{requireDocument(a,"update");const info=validateFile(file.filename,file.mimetype,file.bytes,this.maxBytes),key=await this.storage.write(a.tenantId,file.bytes);try{return await inTenantTransaction(this.pool,a.tenantId,async db=>{const old=await this.repo.document(db,a.tenantId,id);if(!old)throw domainErrors.notFound();if(old.archivedAt)throw domainErrors.archived();if(old.version!==expectedVersion)throw domainErrors.conflict();const n=old.currentVersionNo+1;await db.query(`INSERT INTO document_versions(tenant_id,document_id,version_no,original_filename,storage_key,mime_type,extension,file_size,checksum,uploaded_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[a.tenantId,id,n,info.originalFilename,key,info.mimeType,info.extension,info.fileSize,info.checksum,a.id]);await db.query(`UPDATE documents SET current_version_no=$1,version=version+1,updated_at=now(),updated_by=$2 WHERE tenant_id=$3 AND id=$4`,[n,a.id,a.tenantId,id]);const row=await this.repo.document(db,a.tenantId,id);await this.repo.audit(db,a,"document.version_created",id,{documentVersion:n,filename:info.originalFilename,mimeType:info.mimeType,size:info.fileSize,checksum:info.checksum});return row;});}catch(e){await this.storage.remove(a.tenantId,key);throw e;}});}
 versions(a:DocumentActor,id:string){return this.run(a,id,async()=>{requireDocument(a,"read");return inTenantTransaction(this.pool,a.tenantId,async db=>{if(!await this.repo.document(db,a.tenantId,id))throw domainErrors.notFound();return this.repo.versions(db,a.tenantId,id);});});}
 download(a:DocumentActor,id:string,versionId?:string){return this.run(a,id,async()=>{requireDocument(a,"read");return inTenantTransaction(this.pool,a.tenantId,async db=>{const d=await this.repo.document(db,a.tenantId,id);if(!d)throw domainErrors.notFound();const versions=await this.repo.versions(db,a.tenantId,id),v=versionId?versions.find(x=>x.id===versionId):versions[0];if(!v)throw domainErrors.notFound();return {...v,bytes:await this.storage.read(a.tenantId,v.storageKey)};});});}
 archive(a:DocumentActor,id:string,expectedVersion:number){return this.run(a,id,async()=>{requireDocument(a,"delete");return inTenantTransaction(this.pool,a.tenantId,async db=>{const old=await this.repo.document(db,a.tenantId,id);if(!old)throw domainErrors.notFound();if(old.archivedAt)throw domainErrors.archived();if(old.version!==expectedVersion)throw domainErrors.conflict();await db.query(`UPDATE documents SET deleted_at=now(),deleted_by=$1,updated_by=$1,updated_at=now(),version=version+1 WHERE tenant_id=$2 AND id=$3`,[a.id,a.tenantId,id]);const row=await this.repo.document(db,a.tenantId,id);await this.repo.audit(db,a,"document.archived",id,{before:old,after:row});return row;});});}
 addLink(a:DocumentActor,id:string,input:{entityType:DocumentEntityType;entityId:string;expectedVersion:number}){return this.run(a,id,async()=>{requireDocument(a,"update");return inTenantTransaction(this.pool,a.tenantId,async db=>{const old=await this.repo.document(db,a.tenantId,id);if(!old)throw domainErrors.notFound();if(old.archivedAt)throw domainErrors.archived();if(old.version!==input.expectedVersion)throw domainErrors.conflict();if(!await this.repo.targetExists(db,a.tenantId,input.entityType,input.entityId))throw domainErrors.notFound();await db.query(`INSERT INTO document_links(tenant_id,document_id,entity_type,entity_id,created_by) VALUES($1,$2,$3,$4,$5)`,[a.tenantId,id,input.entityType,input.entityId,a.id]);await db.query(`UPDATE documents SET version=version+1,updated_at=now(),updated_by=$1 WHERE tenant_id=$2 AND id=$3`,[a.id,a.tenantId,id]);const row=await this.repo.document(db,a.tenantId,id);await this.repo.audit(db,a,"document.metadata_updated",id,{before:old,after:row});return row;});});}
 removeLink(a:DocumentActor,id:string,linkId:string,expectedVersion:number){return this.run(a,id,async()=>{requireDocument(a,"update");return inTenantTransaction(this.pool,a.tenantId,async db=>{const old=await this.repo.document(db,a.tenantId,id);if(!old)throw domainErrors.notFound();if(old.archivedAt)throw domainErrors.archived();if(old.version!==expectedVersion)throw domainErrors.conflict();if(old.links.length<=1)throw domainErrors.validation("A document must retain at least one entity link");if(!(await db.query(`DELETE FROM document_links WHERE tenant_id=$1 AND document_id=$2 AND id=$3`,[a.tenantId,id,linkId])).rowCount)throw domainErrors.notFound();await db.query(`UPDATE documents SET version=version+1,updated_at=now(),updated_by=$1 WHERE tenant_id=$2 AND id=$3`,[a.id,a.tenantId,id]);const row=await this.repo.document(db,a.tenantId,id);await this.repo.audit(db,a,"document.metadata_updated",id,{before:old,after:row});return row;});});}
}
