import {domainErrors} from "../errors.js";
const codePattern=/^[A-Z][A-Z0-9_]{0,59}$/;
const text=(value:string,name:string,max:number)=>{const normalized=value.trim();if(!normalized)throw domainErrors.validation(`${name} is required`);if(normalized.length>max)throw domainErrors.validation(`${name} must not exceed ${max} characters`);return normalized;};
const optional=(value:string|null|undefined,name:string,max:number)=>{if(value==null)return value;if(!value.trim())return null;if(value.trim().length>max)throw domainErrors.validation(`${name} must not exceed ${max} characters`);return value.trim();};
const order=(value:number)=>{if(!Number.isInteger(value)||value<0||value>1_000_000)throw domainErrors.validation("sortOrder must be between 0 and 1000000");return value;};
const record=(value:Record<string,unknown>|undefined,name:string)=>{if(value===undefined)return {};if(value===null||Array.isArray(value)||typeof value!=="object")throw domainErrors.validation(`${name} must be a JSON object`);return value;};
export const normalizeMaterialCode=(value:string)=>value.trim().toUpperCase();
const code=(value:string)=>{const normalized=normalizeMaterialCode(value);if(!codePattern.test(normalized))throw domainErrors.validation("Code must be a stable uppercase identifier");return normalized;};
export function validateMaterialCategoryCreate<T extends {code:string;displayName:string;description?:string;sortOrder:number}>(x:T){return {...x,code:code(x.code),displayName:text(x.displayName,"Display name",300),description:optional(x.description,"Description",5000)??undefined,sortOrder:order(x.sortOrder)};}
export function validateMaterialCategoryUpdate<T extends {displayName?:string;description?:string|null;sortOrder?:number}>(x:T){return {...x,displayName:x.displayName===undefined?undefined:text(x.displayName,"Display name",300),description:x.description===undefined?undefined:optional(x.description,"Description",5000),sortOrder:x.sortOrder===undefined?undefined:order(x.sortOrder)};}
export function validateMaterialCreate<T extends {code:string;displayName:string;shortDescription?:string;detailedDescription?:string;manufacturerName?:string;brandName?:string;technicalData?:Record<string,unknown>;aiMetadata?:Record<string,unknown>}>(x:T){return {...x,code:code(x.code),displayName:text(x.displayName,"Display name",300),shortDescription:optional(x.shortDescription,"Short description",1000)??undefined,detailedDescription:optional(x.detailedDescription,"Detailed description",10000)??undefined,manufacturerName:optional(x.manufacturerName,"Manufacturer name",300)??undefined,brandName:optional(x.brandName,"Brand name",300)??undefined,technicalData:record(x.technicalData,"technicalData"),aiMetadata:record(x.aiMetadata,"aiMetadata")};}
export function validateMaterialUpdate<T extends {displayName?:string;shortDescription?:string|null;detailedDescription?:string|null;manufacturerName?:string|null;brandName?:string|null;technicalData?:Record<string,unknown>;aiMetadata?:Record<string,unknown>}>(x:T){return {...x,displayName:x.displayName===undefined?undefined:text(x.displayName,"Display name",300),shortDescription:x.shortDescription===undefined?undefined:optional(x.shortDescription,"Short description",1000),detailedDescription:x.detailedDescription===undefined?undefined:optional(x.detailedDescription,"Detailed description",10000),manufacturerName:x.manufacturerName===undefined?undefined:optional(x.manufacturerName,"Manufacturer name",300),brandName:x.brandName===undefined?undefined:optional(x.brandName,"Brand name",300),technicalData:x.technicalData===undefined?undefined:record(x.technicalData,"technicalData"),aiMetadata:x.aiMetadata===undefined?undefined:record(x.aiMetadata,"aiMetadata")};}
