import Fastify, { type FastifyInstance } from "fastify";
import helmet from "@fastify/helmet";
import jwt from "@fastify/jwt";
import multipart from "@fastify/multipart";
import bcrypt from "bcryptjs";
import { Pool } from "pg";
import { randomUUID, createHash } from "node:crypto";
import { join } from "node:path";
import dotenv from "dotenv";
import { createLogger, loadPlatformConfiguration } from "@odls/platform";
import { AddDocumentLinkRequestSchema,AllocatePaymentRequestSchema,ArchiveClientRequestSchema,ArchivePropertyRequestSchema,AssignTaskRequestSchema,ClientIdParamsSchema,ClientListQuerySchema,CreateClientRequestSchema,CreateExpenseRequestSchema,CreateInvoiceRequestSchema,CreatePaymentRequestSchema,CreateProjectRequestSchema,CreatePropertyRequestSchema,CreateTaskRequestSchema,DocumentIdParamsSchema,DocumentLinkParamsSchema,DocumentListQuerySchema,DocumentUploadMetadataSchema,DocumentVersionParamsSchema,DocumentVersionRequestSchema,DocumentVersionUploadMetadataSchema,ExpenseListQuerySchema,FinanceIdParamsSchema,FinanceVersionRequestSchema,InvoiceListQuerySchema,PaymentListQuerySchema,ProjectIdParamsSchema,ProjectListQuerySchema,ProjectVersionRequestSchema,PropertyIdParamsSchema,PropertyListQuerySchema,TaskAssigneeParamsSchema,TaskIdParamsSchema,TaskListQuerySchema,TaskVersionRequestSchema,UpdateClientRequestSchema,UpdateDocumentRequestSchema,UpdateExpenseRequestSchema,UpdateInvoiceRequestSchema,UpdateProjectRequestSchema,UpdatePropertyRequestSchema,UpdateTaskRequestSchema } from "@odls/contracts";
import { ClientService,type ClientActor } from "./application/client/client-service.js";
import { ProjectService,type ProjectActor } from "./application/project/project-service.js";
import { PropertyService,type PropertyActor } from "./application/property/property-service.js";
import { TaskService,type TaskActor } from "./application/task/task-service.js";
import { DomainError } from "./domain/errors.js";
import {FinanceService,type FinanceActor} from "./application/finance/finance-service.js";
import {DocumentService} from "./application/document/document-service.js";

dotenv.config({ path: join(import.meta.dirname, "../../../../.env") });

type Claims = { sub: string; tenantId: string; permissions: string[]; email: string };
function required(value: unknown, name: string): string { if (typeof value !== "string" || !value.trim()) throw Object.assign(new Error(`${name} is required`), { statusCode:400, code:"validation_failed" }); return value.trim(); }
function hash(value: string): string { return createHash("sha256").update(value).digest("hex"); }
function safeBody(body: unknown): Record<string, unknown> { return body !== null && typeof body === "object" && !Array.isArray(body) ? body as Record<string,unknown> : {}; }

export function buildServer(): FastifyInstance<any, any, any, any> {
  const config = loadPlatformConfiguration();
  const app = Fastify({ loggerInstance:createLogger("core-service",config.LOG_LEVEL), requestIdHeader:"x-request-id" });
  const databaseUrl = process.env.DATABASE_URL;
  const pool = databaseUrl ? new Pool({ connectionString:databaseUrl }) : undefined;
  const clientService=pool?new ClientService(pool):undefined;
  const projectService=pool?new ProjectService(pool):undefined;
  const propertyService=pool?new PropertyService(pool):undefined;
  const taskService=pool?new TaskService(pool):undefined;
  const financeService=pool?new FinanceService(pool):undefined;
  const documentService=pool?new DocumentService(pool):undefined;
  const jwtSecret = process.env.JWT_SECRET ?? "development-only-secret-change-me-32chars";
  void app.register(helmet); void app.register(jwt, { secret:jwtSecret }); void app.register(multipart,{limits:{fileSize:Number(process.env.DOCUMENT_MAX_BYTES??10_485_760),files:1,fields:8}});
  app.decorateRequest("claims", null);
  app.addHook("onRequest", async (request) => { request.headers["x-correlation-id"] ??= request.id; });
  app.addHook("onClose", async () => { await pool?.end(); });
  async function db() { if (!pool) throw Object.assign(new Error("Database is not configured"),{statusCode:503,code:"database_unavailable"}); return pool; }
  function clients(){if(!clientService)throw Object.assign(new Error("Database is not configured"),{statusCode:503,code:"database_unavailable"});return clientService;}
  function clientActor(request:any):ClientActor{return {id:request.claims.sub,tenantId:request.claims.tenantId,permissions:request.claims.permissions,correlationId:String(request.headers["x-correlation-id"]??request.id)};}
  function properties(){if(!propertyService)throw Object.assign(new Error("Database is not configured"),{statusCode:503,code:"database_unavailable"});return propertyService;}
  function propertyActor(request:any):PropertyActor{return {id:request.claims.sub,tenantId:request.claims.tenantId,permissions:request.claims.permissions,correlationId:String(request.headers["x-correlation-id"]??request.id)};}
  function projects(){if(!projectService)throw Object.assign(new Error("Database is not configured"),{statusCode:503,code:"database_unavailable"});return projectService;}
  function projectActor(request:any):ProjectActor{return {id:request.claims.sub,tenantId:request.claims.tenantId,permissions:request.claims.permissions,correlationId:String(request.headers["x-correlation-id"]??request.id)};}
  function tasks(){if(!taskService)throw Object.assign(new Error("Database is not configured"),{statusCode:503,code:"database_unavailable"});return taskService;}
  function taskActor(request:any):TaskActor{return {id:request.claims.sub,tenantId:request.claims.tenantId,permissions:request.claims.permissions,correlationId:String(request.headers["x-correlation-id"]??request.id)};}
  function finances(){if(!financeService)throw Object.assign(new Error("Database is not configured"),{statusCode:503,code:"database_unavailable"});return financeService;}
  function financeActor(request:any):FinanceActor{return {id:request.claims.sub,tenantId:request.claims.tenantId,permissions:request.claims.permissions,correlationId:String(request.headers["x-correlation-id"]??request.id)};}
  function documents(){if(!documentService)throw Object.assign(new Error("Database is not configured"),{statusCode:503,code:"database_unavailable"});return documentService;}
  function multipartField(part:any,name:string){const value=part.fields?.[name]?.value;if(typeof value!=="string")throw Object.assign(new Error(`${name} is required`),{name:"ZodError"});return value;}
  async function clientRoute(request:any,reply:any,operation:()=>Promise<unknown>,successCode=200){try{const result=await operation();return reply.sent?result:reply.code(successCode).send(result);}catch(error){if(error instanceof DomainError){if(/^\/api\/v1\/(invoices|payments|expenses|projects\/[^/]+\/financial-summary)/.test(request.url)){const actions:Partial<Record<DomainError["code"],string>>={FORBIDDEN:"finance.permission_denied",VERSION_CONFLICT:"finance.version_conflict",ENTITY_ARCHIVED:"finance.archived_mutation_denied",INVALID_STATUS_TRANSITION:"finance.invalid_lifecycle_transition",INVALID_RELATIONSHIP:"finance.invalid_relationship"};const action=actions[error.code];if(action)await audit(request.claims?.tenantId,request.claims?.sub,action,"finance",request.params?.id,request.id,{method:request.method,url:request.url,code:error.code,details:error.details});}return reply.code(error.statusCode).send({error:{code:error.code,message:error.message,details:error.details,correlationId:String(request.headers["x-correlation-id"]??request.id)}});}if(error instanceof Error&&error.name==="ZodError")return reply.code(400).send({error:{code:"VALIDATION_ERROR",message:"Invalid request",details:{},correlationId:String(request.headers["x-correlation-id"]??request.id)}});request.log.error({err:error},"client route failed");return reply.code(500).send({error:{code:"INTERNAL_ERROR",message:"Internal server error",details:{},correlationId:String(request.headers["x-correlation-id"]??request.id)}});}}
  async function audit(tenantId:string|undefined, actorId:string|undefined, action:string, entityType:string, entityId:string|undefined, requestId:string, metadata:Record<string,unknown>={}) { if (!pool) return; const correlationId=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(requestId) ? requestId : randomUUID(); await pool.query("INSERT INTO audit_logs(tenant_id,actor_id,action,entity_type,entity_id,correlation_id,metadata) VALUES($1,$2,$3,$4,$5,$6,$7)",[tenantId,actorId,action,entityType,entityId,correlationId,metadata]); }
  async function authenticate(request:any, reply:any) { try { await request.jwtVerify(); request.claims=request.user as Claims; } catch { await audit(undefined,undefined,"auth.denied","auth",undefined,request.id); return reply.code(401).send({code:"token_invalid",requestId:request.id}); } }
  function authorize(permission:string) { return async (request:any, reply:any) => { if (!request.claims?.permissions.includes(permission)) { await audit(request.claims?.tenantId,request.claims?.sub,"permission.denied",permission,undefined,request.id); return reply.code(403).send({code:"permission_denied",requestId:request.id}); } }; }
  app.get("/health", async () => ({status:"ok",service:"core-service",timestamp:new Date().toISOString()}));
  app.get("/ready", async (_req,reply) => { try { await (await db()).query("SELECT 1"); return {status:"ok",service:"core-service",timestamp:new Date().toISOString()}; } catch { return reply.code(503).send({status:"unavailable"}); } });
  app.post("/api/v1/auth/login", async (request, reply) => { const body=safeBody(request.body); const tenantSlug=required(body.tenantSlug,"tenantSlug"), email=required(body.email,"email"), password=required(body.password,"password"); const p=await db(); const result=await p.query("SELECT u.id,u.email,u.display_name,u.password_hash,u.is_disabled,t.id tenant_id FROM users u JOIN tenants t ON t.id=u.tenant_id WHERE t.slug=$1 AND u.email=$2 AND u.deleted_at IS NULL",[tenantSlug,email]); const user=result.rows[0]; if (!user || user.is_disabled || !(await bcrypt.compare(password,user.password_hash))) { await audit(user?.tenant_id, user?.id,"auth.login_failed","user",user?.id,request.id); return reply.code(401).send({code:"invalid_credentials"}); } const permissions=(await p.query("SELECT DISTINCT p.code FROM permissions p JOIN role_permissions rp ON rp.permission_id=p.id JOIN user_roles ur ON ur.role_id=rp.role_id WHERE ur.user_id=$1 AND ur.tenant_id=$2",[user.id,user.tenant_id])).rows.map((r)=>r.code); const claims:Claims={sub:user.id,tenantId:user.tenant_id,email:user.email,permissions}; const accessToken=app.jwt.sign(claims,{expiresIn:"15m"}); const refreshToken=randomUUID()+randomUUID(); await p.query("INSERT INTO refresh_tokens(tenant_id,user_id,token_hash,expires_at) VALUES($1,$2,$3,now()+interval '30 days')",[user.tenant_id,user.id,hash(refreshToken)]); await audit(user.tenant_id,user.id,"auth.login_success","user",user.id,request.id); return {data:{accessToken,refreshToken,expiresIn:900,user:{id:user.id,email:user.email,displayName:user.display_name},permissions}}; });
  app.post("/api/v1/auth/refresh", async (request,reply) => { const token=required(safeBody(request.body).refreshToken,"refreshToken"); const p=await db(); const found=(await p.query("SELECT rt.*,u.email FROM refresh_tokens rt JOIN users u ON u.id=rt.user_id WHERE rt.token_hash=$1 AND rt.revoked_at IS NULL AND rt.expires_at>now()",[hash(token)])).rows[0]; if (!found) return reply.code(401).send({code:"invalid_refresh_token"}); const permissions=(await p.query("SELECT DISTINCT p.code FROM permissions p JOIN role_permissions rp ON rp.permission_id=p.id JOIN user_roles ur ON ur.role_id=rp.role_id WHERE ur.user_id=$1",[found.user_id])).rows.map((r)=>r.code); const next=randomUUID()+randomUUID(); await p.query("UPDATE refresh_tokens SET revoked_at=now() WHERE id=$1",[found.id]); await p.query("INSERT INTO refresh_tokens(tenant_id,user_id,token_hash,expires_at) VALUES($1,$2,$3,now()+interval '30 days')",[found.tenant_id,found.user_id,hash(next)]); return {data:{accessToken:app.jwt.sign({sub:found.user_id,tenantId:found.tenant_id,email:found.email,permissions},{expiresIn:"15m"}),refreshToken:next,expiresIn:900}}; });
  app.post("/api/v1/auth/logout",{preHandler:authenticate},async (request:any) => { const token=safeBody(request.body).refreshToken; if(typeof token==="string") await (await db()).query("UPDATE refresh_tokens SET revoked_at=now() WHERE token_hash=$1",[hash(token)]); return {data:{revoked:true}}; });
  app.get("/api/v1/auth/me",{preHandler:authenticate},async (request:any) => ({data:{id:request.claims.sub,tenantId:request.claims.tenantId,email:request.claims.email,permissions:request.claims.permissions}}));
  app.get("/api/v1/company",{preHandler:authenticate},async (request:any) => ({data:(await (await db()).query("SELECT id,name,slug FROM tenants WHERE id=$1",[request.claims.tenantId])).rows[0]}));
  app.get("/api/v1/users",{preHandler:[authenticate,authorize("users.read")]},async (request:any) => ({data:(await (await db()).query("SELECT id,email,display_name,is_disabled,version FROM users WHERE tenant_id=$1 AND deleted_at IS NULL ORDER BY display_name",[request.claims.tenantId])).rows}));
  app.get("/api/v1/users/:id",{preHandler:[authenticate,authorize("users.read")]},async (request:any,reply) => { const row=(await (await db()).query("SELECT id,email,display_name,is_disabled,version FROM users WHERE id=$1 AND tenant_id=$2 AND deleted_at IS NULL",[request.params.id,request.claims.tenantId])).rows[0]; return row?{data:row}:reply.code(404).send({code:"not_found"}); });
  app.get("/api/v1/clients",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const query=ClientListQuerySchema.parse(request.query);const result=await clients().listClients(clientActor(request),query);return {data:result.items,pagination:result.pagination};}));
  app.post("/api/v1/clients",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>({data:await clients().createClient(clientActor(request),CreateClientRequestSchema.parse(request.body))}),201));
  app.get("/api/v1/clients/:id",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const {id}=ClientIdParamsSchema.parse(request.params);return {data:await clients().getClient(clientActor(request),id)};}));
  app.patch("/api/v1/clients/:id",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const {id}=ClientIdParamsSchema.parse(request.params);return {data:await clients().updateClient(clientActor(request),id,UpdateClientRequestSchema.parse(request.body))};}));
  app.delete("/api/v1/clients/:id",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const {id}=ClientIdParamsSchema.parse(request.params);const {expectedVersion}=ArchiveClientRequestSchema.parse(request.body);return {data:await clients().archiveClient(clientActor(request),id,expectedVersion)};}));
  app.get("/api/v1/properties",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const query=PropertyListQuerySchema.parse(request.query);const result=await properties().listProperties(propertyActor(request),query);return {data:result.items,pagination:result.pagination};}));
  app.post("/api/v1/properties",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>({data:await properties().createProperty(propertyActor(request),CreatePropertyRequestSchema.parse(request.body))}),201));
  app.get("/api/v1/properties/:id",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const {id}=PropertyIdParamsSchema.parse(request.params);return {data:await properties().getProperty(propertyActor(request),id)};}));
  app.patch("/api/v1/properties/:id",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const {id}=PropertyIdParamsSchema.parse(request.params);return {data:await properties().updateProperty(propertyActor(request),id,UpdatePropertyRequestSchema.parse(request.body))};}));
  app.delete("/api/v1/properties/:id",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const {id}=PropertyIdParamsSchema.parse(request.params);const {expectedVersion}=ArchivePropertyRequestSchema.parse(request.body);return {data:await properties().archiveProperty(propertyActor(request),id,expectedVersion)};}));
  app.get("/api/v1/projects",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const query=ProjectListQuerySchema.parse(request.query);const result=await projects().listProjects(projectActor(request),query);return {data:result.items,pagination:result.pagination};}));
  app.post("/api/v1/projects",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>({data:await projects().createProject(projectActor(request),CreateProjectRequestSchema.parse(request.body))}),201));
  app.get("/api/v1/projects/:id",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const {id}=ProjectIdParamsSchema.parse(request.params);return {data:await projects().getProject(projectActor(request),id)};}));
  app.patch("/api/v1/projects/:id",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const {id}=ProjectIdParamsSchema.parse(request.params);return {data:await projects().updateProject(projectActor(request),id,UpdateProjectRequestSchema.parse(request.body))};}));
  app.delete("/api/v1/projects/:id",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const {id}=ProjectIdParamsSchema.parse(request.params);const {expectedVersion}=ProjectVersionRequestSchema.parse(request.body);return {data:await projects().archiveProject(projectActor(request),id,expectedVersion)};}));
  for(const action of ["plan","start","pause","resume","complete","cancel"] as const)app.post(`/api/v1/projects/:id/${action}`,{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const {id}=ProjectIdParamsSchema.parse(request.params);const {expectedVersion}=ProjectVersionRequestSchema.parse(request.body);return {data:await projects().transitionProject(projectActor(request),id,action,expectedVersion)};}));
  app.get("/api/v1/tasks",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const query=TaskListQuerySchema.parse(request.query);const result=await tasks().listTasks(taskActor(request),query);return {data:result.items,pagination:result.pagination};}));
  app.post("/api/v1/tasks",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>({data:await tasks().createTask(taskActor(request),CreateTaskRequestSchema.parse(request.body))}),201));
  app.get("/api/v1/tasks/:id",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const {id}=TaskIdParamsSchema.parse(request.params);return {data:await tasks().getTask(taskActor(request),id)};}));
  app.patch("/api/v1/tasks/:id",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const {id}=TaskIdParamsSchema.parse(request.params);return {data:await tasks().updateTask(taskActor(request),id,UpdateTaskRequestSchema.parse(request.body))};}));
  app.delete("/api/v1/tasks/:id",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const {id}=TaskIdParamsSchema.parse(request.params);const {expectedVersion}=TaskVersionRequestSchema.parse(request.body);return {data:await tasks().archiveTask(taskActor(request),id,expectedVersion)};}));
  for(const action of ["start","block","resume","complete","cancel"] as const)app.post(`/api/v1/tasks/:id/${action}`,{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const {id}=TaskIdParamsSchema.parse(request.params);const {expectedVersion}=TaskVersionRequestSchema.parse(request.body);return {data:await tasks().transitionTask(taskActor(request),id,action,expectedVersion)};}));
  app.post("/api/v1/tasks/:id/assignees",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const {id}=TaskIdParamsSchema.parse(request.params);const {userId,expectedVersion}=AssignTaskRequestSchema.parse(request.body);return {data:await tasks().assignTask(taskActor(request),id,userId,expectedVersion)};}));
  app.delete("/api/v1/tasks/:id/assignees/:userId",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const {id,userId}=TaskAssigneeParamsSchema.parse(request.params);const {expectedVersion}=TaskVersionRequestSchema.parse(request.body);return {data:await tasks().unassignTask(taskActor(request),id,userId,expectedVersion)};}));
  app.get("/api/v1/invoices",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const r=await finances().listInvoices(financeActor(request),InvoiceListQuerySchema.parse(request.query));return {data:r.items,pagination:r.pagination};}));
  app.post("/api/v1/invoices",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>({data:await finances().createInvoice(financeActor(request),CreateInvoiceRequestSchema.parse(request.body))}),201));
  app.get("/api/v1/invoices/:id",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>({data:await finances().getInvoice(financeActor(request),FinanceIdParamsSchema.parse(request.params).id)})));
  app.patch("/api/v1/invoices/:id",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>({data:await finances().updateInvoice(financeActor(request),FinanceIdParamsSchema.parse(request.params).id,UpdateInvoiceRequestSchema.parse(request.body))})));
  app.delete("/api/v1/invoices/:id",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const {expectedVersion}=FinanceVersionRequestSchema.parse(request.body);return {data:await finances().invoiceAction(financeActor(request),FinanceIdParamsSchema.parse(request.params).id,"archive",expectedVersion)};}));
  for(const action of ["issue","cancel"] as const)app.post(`/api/v1/invoices/:id/${action}`,{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const {expectedVersion}=FinanceVersionRequestSchema.parse(request.body);return {data:await finances().invoiceAction(financeActor(request),FinanceIdParamsSchema.parse(request.params).id,action,expectedVersion)};}));
  app.get("/api/v1/payments",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const r=await finances().listPayments(financeActor(request),PaymentListQuerySchema.parse(request.query));return {data:r.items,pagination:r.pagination};}));
  app.post("/api/v1/payments",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>({data:await finances().createPayment(financeActor(request),CreatePaymentRequestSchema.parse(request.body))}),201));
  app.get("/api/v1/payments/:id",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>({data:await finances().getPayment(financeActor(request),FinanceIdParamsSchema.parse(request.params).id)})));
  app.post("/api/v1/payments/:id/allocate",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const x=AllocatePaymentRequestSchema.parse(request.body);return {data:await finances().allocate(financeActor(request),FinanceIdParamsSchema.parse(request.params).id,x.invoiceId,x.amount,x.expectedVersion)};}));
  app.post("/api/v1/payments/:id/reverse",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const {expectedVersion}=FinanceVersionRequestSchema.parse(request.body);return {data:await finances().reversePayment(financeActor(request),FinanceIdParamsSchema.parse(request.params).id,expectedVersion)};}));
  app.delete("/api/v1/payments/:id",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const {expectedVersion}=FinanceVersionRequestSchema.parse(request.body);return {data:await finances().archivePayment(financeActor(request),FinanceIdParamsSchema.parse(request.params).id,expectedVersion)};}));
  app.get("/api/v1/expenses",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const r=await finances().listExpenses(financeActor(request),ExpenseListQuerySchema.parse(request.query));return {data:r.items,pagination:r.pagination};}));
  app.post("/api/v1/expenses",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>({data:await finances().createExpense(financeActor(request),CreateExpenseRequestSchema.parse(request.body))}),201));
  app.get("/api/v1/expenses/:id",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>({data:await finances().getExpense(financeActor(request),FinanceIdParamsSchema.parse(request.params).id)})));
  app.patch("/api/v1/expenses/:id",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>({data:await finances().updateExpense(financeActor(request),FinanceIdParamsSchema.parse(request.params).id,UpdateExpenseRequestSchema.parse(request.body))})));
  app.delete("/api/v1/expenses/:id",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const {expectedVersion}=FinanceVersionRequestSchema.parse(request.body);return {data:await finances().expenseAction(financeActor(request),FinanceIdParamsSchema.parse(request.params).id,"archive",expectedVersion)};}));
  for(const action of ["approve","reject"] as const)app.post(`/api/v1/expenses/:id/${action}`,{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const {expectedVersion}=FinanceVersionRequestSchema.parse(request.body);return {data:await finances().expenseAction(financeActor(request),FinanceIdParamsSchema.parse(request.params).id,action,expectedVersion)};}));
  app.get("/api/v1/projects/:id/financial-summary",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>({data:await finances().projectSummary(financeActor(request),FinanceIdParamsSchema.parse(request.params).id)})));
  app.get("/api/v1/documents",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const r=await documents().list(financeActor(request),DocumentListQuerySchema.parse(request.query));return {data:r.items,pagination:r.pagination};}));
  app.post("/api/v1/documents",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const part=await request.file();if(!part)throw Object.assign(new Error("file is required"),{name:"ZodError"});const bytes=await part.toBuffer(),meta=DocumentUploadMetadataSchema.parse({category:multipartField(part,"category"),description:part.fields?.description?.value,entityType:multipartField(part,"entityType"),entityId:multipartField(part,"entityId")});return {data:await documents().upload(financeActor(request),meta,{filename:part.filename,mimetype:part.mimetype,bytes})};},201));
  app.get("/api/v1/documents/:id",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>({data:await documents().get(financeActor(request),DocumentIdParamsSchema.parse(request.params).id)})));
  app.patch("/api/v1/documents/:id",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>({data:await documents().update(financeActor(request),DocumentIdParamsSchema.parse(request.params).id,UpdateDocumentRequestSchema.parse(request.body))})));
  app.delete("/api/v1/documents/:id",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const {expectedVersion}=DocumentVersionRequestSchema.parse(request.body);return {data:await documents().archive(financeActor(request),DocumentIdParamsSchema.parse(request.params).id,expectedVersion)};}));
  app.get("/api/v1/documents/:id/download",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const file=await documents().download(financeActor(request),DocumentIdParamsSchema.parse(request.params).id);return reply.header("content-type",file.mimeType).header("content-length",file.fileSize).header("content-disposition",`attachment; filename*=UTF-8''${encodeURIComponent(file.originalFilename)}`).header("x-content-type-options","nosniff").send(file.bytes);}));
  app.get("/api/v1/documents/:id/versions",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>({data:await documents().versions(financeActor(request),DocumentIdParamsSchema.parse(request.params).id)})));
  app.post("/api/v1/documents/:id/versions",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const part=await request.file();if(!part)throw Object.assign(new Error("file is required"),{name:"ZodError"});const meta=DocumentVersionUploadMetadataSchema.parse({expectedVersion:Number(multipartField(part,"expectedVersion"))});return {data:await documents().addVersion(financeActor(request),DocumentIdParamsSchema.parse(request.params).id,meta.expectedVersion,{filename:part.filename,mimetype:part.mimetype,bytes:await part.toBuffer()})};},201));
  app.get("/api/v1/documents/:id/versions/:versionId/download",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const p=DocumentVersionParamsSchema.parse(request.params),file=await documents().download(financeActor(request),p.id,p.versionId);return reply.header("content-type",file.mimeType).header("content-length",file.fileSize).header("content-disposition",`attachment; filename*=UTF-8''${encodeURIComponent(file.originalFilename)}`).header("x-content-type-options","nosniff").send(file.bytes);}));
  app.post("/api/v1/documents/:id/links",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>({data:await documents().addLink(financeActor(request),DocumentIdParamsSchema.parse(request.params).id,AddDocumentLinkRequestSchema.parse(request.body))})));
  app.delete("/api/v1/documents/:id/links/:linkId",{preHandler:authenticate},async(request:any,reply)=>clientRoute(request,reply,async()=>{const p=DocumentLinkParamsSchema.parse(request.params),v=DocumentVersionRequestSchema.parse(request.body);return {data:await documents().removeLink(financeActor(request),p.id,p.linkId,v.expectedVersion)};}));
  return app;
}
if(process.env.NODE_ENV!=="test"){const app=buildServer();void app.listen({host:"0.0.0.0",port:Number(process.env.CORE_SERVICE_PORT??3001)});}
