import type {PoolClient} from "pg";
import type {CreatePriceList,CreatePriceListItem,PriceList,PriceListItem,PriceListItemQuery,PriceListQuery,PricePage,UpdatePriceList,UpdatePriceListItem} from "../../domain/price-list/price-list-types.js";
const listSelect=`id,tenant_id "tenantId",code,display_name "displayName",description,currency,country,region,valid_from::text "validFrom",valid_to::text "validTo",status,is_system "isSystem",version::int,created_at "createdAt",updated_at "updatedAt",created_by "createdBy",updated_by "updatedBy"`;
const itemSelect=`i.id,i.tenant_id "tenantId",i.price_list_id "priceListId",p.code "priceListCode",i.material_id "materialId",m.code "materialCode",m.display_name "materialName",i.unit_price::text "unitPrice",i.vat_rate::text "vatRate",i.discount_percent::text "discountPercent",i.currency,i.valid_from::text "validFrom",i.valid_to::text "validTo",i.status,i.version::int,i.created_at "createdAt",i.updated_at "updatedAt",i.created_by "createdBy",i.updated_by "updatedBy"`;
const listSort={code:"code",displayName:"display_name",currency:"currency",country:"country",validFrom:"valid_from",status:"status",updatedAt:"updated_at"} as const;
const itemSort={material:"m.display_name",unitPrice:"i.unit_price",currency:"i.currency",validFrom:"i.valid_from",status:"i.status",updatedAt:"i.updated_at"} as const;
export class PriceListRepository{
 findList(db:PoolClient,t:string,id:string){return db.query<PriceList>(`SELECT ${listSelect} FROM price_lists WHERE tenant_id=$1 AND id=$2`,[t,id]).then(r=>r.rows[0]);}
 findItem(db:PoolClient,t:string,id:string){return db.query<PriceListItem>(`SELECT ${itemSelect} FROM price_list_items i JOIN price_lists p ON p.tenant_id=i.tenant_id AND p.id=i.price_list_id JOIN materials m ON m.tenant_id=i.tenant_id AND m.id=i.material_id WHERE i.tenant_id=$1 AND i.id=$2`,[t,id]).then(r=>r.rows[0]);}
 findMaterial(db:PoolClient,t:string,id:string){return db.query<{id:string;status:string}>("SELECT id,status FROM materials WHERE tenant_id=$1 AND id=$2",[t,id]).then(r=>r.rows[0]);}
 async list(db:PoolClient,t:string,q:PriceListQuery):Promise<PricePage<PriceList>>{const v:any[]=[t],f=["tenant_id=$1"];if(q.search){v.push(`%${q.search}%`);f.push(`(code ILIKE $${v.length} OR display_name ILIKE $${v.length} OR description ILIKE $${v.length})`);}for(const[k,c]of [["currency","currency"],["country","country"]] as const)if(q[k]){v.push(q[k]);f.push(`${c}=$${v.length}`);}if(q.active!==undefined){v.push(q.active?"active":"inactive");f.push(`status=$${v.length}`);}if(q.validOn){v.push(q.validOn);f.push(`valid_from<=$${v.length} AND(valid_to IS NULL OR valid_to>=$${v.length})`);}const where=f.join(" AND "),total=Number((await db.query<{count:string}>(`SELECT count(*) FROM price_lists WHERE ${where}`,v)).rows[0].count);v.push(q.pageSize,(q.page-1)*q.pageSize);const d=q.sortOrder==="asc"?"ASC":"DESC",items=(await db.query<PriceList>(`SELECT ${listSelect} FROM price_lists WHERE ${where} ORDER BY ${listSort[q.sortBy]} ${d},id ${d} LIMIT $${v.length-1} OFFSET $${v.length}`,v)).rows;return {items,pagination:{page:q.page,pageSize:q.pageSize,total,totalPages:Math.ceil(total/q.pageSize)}};}
 async items(db:PoolClient,t:string,q:PriceListItemQuery):Promise<PricePage<PriceListItem>>{const v:any[]=[t],f=["i.tenant_id=$1"];if(q.search){v.push(`%${q.search}%`);f.push(`(m.code ILIKE $${v.length} OR m.display_name ILIKE $${v.length} OR p.code ILIKE $${v.length})`);}for(const[k,c]of [["priceListId","i.price_list_id"],["materialId","i.material_id"],["currency","i.currency"]] as const)if(q[k]){v.push(q[k]);f.push(`${c}=$${v.length}`);}if(q.active!==undefined){v.push(q.active?"active":"inactive");f.push(`i.status=$${v.length}`);}if(q.validOn){v.push(q.validOn);f.push(`i.valid_from<=$${v.length} AND(i.valid_to IS NULL OR i.valid_to>=$${v.length})`);}const joins="price_list_items i JOIN price_lists p ON p.tenant_id=i.tenant_id AND p.id=i.price_list_id JOIN materials m ON m.tenant_id=i.tenant_id AND m.id=i.material_id",where=f.join(" AND "),total=Number((await db.query<{count:string}>(`SELECT count(*) FROM ${joins} WHERE ${where}`,v)).rows[0].count);v.push(q.pageSize,(q.page-1)*q.pageSize);const d=q.sortOrder==="asc"?"ASC":"DESC",items=(await db.query<PriceListItem>(`SELECT ${itemSelect} FROM ${joins} WHERE ${where} ORDER BY ${itemSort[q.sortBy]} ${d},i.id ${d} LIMIT $${v.length-1} OFFSET $${v.length}`,v)).rows;return {items,pagination:{page:q.page,pageSize:q.pageSize,total,totalPages:Math.ceil(total/q.pageSize)}};}
 createList(db:PoolClient,t:string,a:string,id:string,x:CreatePriceList){return db.query<PriceList>(`INSERT INTO price_lists(id,tenant_id,code,display_name,description,currency,country,region,valid_from,valid_to,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$11) RETURNING ${listSelect}`,[id,t,x.code,x.displayName,x.description??null,x.currency,x.country,x.region??null,x.validFrom,x.validTo??null,a]).then(r=>r.rows[0]);}
 updateList(db:PoolClient,t:string,a:string,id:string,x:UpdatePriceList){const m=[["displayName","display_name"],["description","description"],["currency","currency"],["country","country"],["region","region"],["validFrom","valid_from"],["validTo","valid_to"]] as const,s:string[]=[],v:any[]=[];for(const[k,c]of m)if(x[k]!==undefined){v.push(x[k]);s.push(`${c}=$${v.length}`);}if(!s.length)return this.findList(db,t,id);v.push(a,id,t,x.expectedVersion);return db.query<PriceList>(`UPDATE price_lists SET ${s.join(",")},updated_by=$${v.length-3},updated_at=now(),version=version+1 WHERE id=$${v.length-2} AND tenant_id=$${v.length-1} AND version=$${v.length} RETURNING ${listSelect}`,v).then(r=>r.rows[0]);}
 setListStatus(db:PoolClient,t:string,a:string,id:string,status:string,version:number){return db.query<PriceList>(`UPDATE price_lists SET status=$1,updated_by=$2,updated_at=now(),version=version+1 WHERE tenant_id=$3 AND id=$4 AND version=$5 RETURNING ${listSelect}`,[status,a,t,id,version]).then(r=>r.rows[0]);}
 activeItemCount(db:PoolClient,t:string,id:string){return db.query<{count:string}>("SELECT count(*) FROM price_list_items WHERE tenant_id=$1 AND price_list_id=$2 AND status='active'",[t,id]).then(r=>Number(r.rows[0].count));}
 createItem(db:PoolClient,t:string,a:string,id:string,x:CreatePriceListItem){return db.query<PriceListItem>(`WITH inserted AS (INSERT INTO price_list_items(id,tenant_id,price_list_id,material_id,unit_price,vat_rate,discount_percent,currency,valid_from,valid_to,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$11) RETURNING *) SELECT ${itemSelect} FROM inserted i JOIN price_lists p ON p.tenant_id=i.tenant_id AND p.id=i.price_list_id JOIN materials m ON m.tenant_id=i.tenant_id AND m.id=i.material_id`,[id,t,x.priceListId,x.materialId,x.unitPrice,x.vatRate,x.discountPercent,x.currency,x.validFrom,x.validTo??null,a]).then(r=>r.rows[0]);}
 updateItem(db:PoolClient,t:string,a:string,id:string,x:UpdatePriceListItem){const m=[["unitPrice","unit_price"],["vatRate","vat_rate"],["discountPercent","discount_percent"],["currency","currency"],["validFrom","valid_from"],["validTo","valid_to"]] as const,s:string[]=[],v:any[]=[];for(const[k,c]of m)if(x[k]!==undefined){v.push(x[k]);s.push(`${c}=$${v.length}`);}if(!s.length)return this.findItem(db,t,id);v.push(a,id,t,x.expectedVersion);return db.query<PriceListItem>(`WITH updated AS (UPDATE price_list_items SET ${s.join(",")},updated_by=$${v.length-3},updated_at=now(),version=version+1 WHERE id=$${v.length-2} AND tenant_id=$${v.length-1} AND version=$${v.length} RETURNING *) SELECT ${itemSelect} FROM updated i JOIN price_lists p ON p.tenant_id=i.tenant_id AND p.id=i.price_list_id JOIN materials m ON m.tenant_id=i.tenant_id AND m.id=i.material_id`,v).then(r=>r.rows[0]);}
 setItemStatus(db:PoolClient,t:string,a:string,id:string,status:string,version:number){return db.query<PriceListItem>(`WITH updated AS (UPDATE price_list_items SET status=$1,updated_by=$2,updated_at=now(),version=version+1 WHERE tenant_id=$3 AND id=$4 AND version=$5 RETURNING *) SELECT ${itemSelect} FROM updated i JOIN price_lists p ON p.tenant_id=i.tenant_id AND p.id=i.price_list_id JOIN materials m ON m.tenant_id=i.tenant_id AND m.id=i.material_id`,[status,a,t,id,version]).then(r=>r.rows[0]);}
}
