import type {PoolClient} from "pg";
import type {CreateProjectCommand,Project,ProjectListQuery,ProjectListResult,ProjectStatus,UpdateProjectCommand} from "../../domain/project/project-types.js";

const select=`id,tenant_id AS "tenantId",client_id AS "clientId",property_id AS "propertyId",financial_owner_legal_entity_id AS "financialOwnerLegalEntityId",project_manager_id AS "projectManagerId",project_number AS "projectNumber",name,description,status,start_date::text AS "startDate",expected_completion_date::text AS "expectedCompletionDate",actual_completion_date::text AS "actualCompletionDate",currency_code AS "currencyCode",estimated_budget::text AS "estimatedBudget",approved_budget::text AS "approvedBudget",contract_value::text AS "contractValue",payment_status AS "paymentStatus",billing_customer_reference AS "billingCustomerReference",external_payment_customer_reference AS "externalPaymentCustomerReference",version::int,created_at AS "createdAt",updated_at AS "updatedAt",deleted_at AS "archivedAt"`;
const sortColumns={projectNumber:"project_number",name:"name",status:"status",startDate:"start_date",expectedCompletionDate:"expected_completion_date",createdAt:"created_at",updatedAt:"updated_at"} as const;
export class ProjectRepository {
  async findById(db:PoolClient,tenantId:string,id:string):Promise<Project|undefined>{return (await db.query<Project>(`SELECT ${select} FROM projects WHERE id=$1 AND tenant_id=$2`,[id,tenantId])).rows[0];}
  async findProperty(db:PoolClient,tenantId:string,id:string){return (await db.query<{id:string;clientId:string;status:string;archivedAt:string|null}>("SELECT id,client_id AS \"clientId\",status,deleted_at AS \"archivedAt\" FROM properties WHERE id=$1 AND tenant_id=$2",[id,tenantId])).rows[0];}
  async findClient(db:PoolClient,tenantId:string,id:string){return (await db.query<{id:string}>("SELECT id FROM clients WHERE id=$1 AND tenant_id=$2",[id,tenantId])).rows[0];}
  async findLegalEntity(db:PoolClient,tenantId:string,id:string){return (await db.query<{id:string}>("SELECT id FROM legal_entities WHERE id=$1 AND tenant_id=$2 AND deleted_at IS NULL",[id,tenantId])).rows[0];}
  async findUser(db:PoolClient,tenantId:string,id:string){return (await db.query<{id:string}>("SELECT id FROM users WHERE id=$1 AND tenant_id=$2 AND deleted_at IS NULL AND is_disabled=false",[id,tenantId])).rows[0];}
  async findDuplicateNumber(db:PoolClient,tenantId:string,projectNumber:string,id?:string){return (await db.query("SELECT id FROM projects WHERE tenant_id=$1 AND lower(project_number)=lower($2) AND ($3::uuid IS NULL OR id<>$3)",[tenantId,projectNumber,id??null])).rows[0];}
  async create(db:PoolClient,tenantId:string,actorId:string,id:string,input:CreateProjectCommand):Promise<Project>{const row=await db.query<Project>(`INSERT INTO projects(id,tenant_id,client_id,property_id,financial_owner_legal_entity_id,project_manager_id,project_number,name,description,start_date,expected_completion_date,currency_code,estimated_budget,approved_budget,contract_value,payment_status,billing_customer_reference,external_payment_customer_reference,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$19) RETURNING ${select}`,[id,tenantId,input.clientId,input.propertyId,input.financialOwnerLegalEntityId,input.projectManagerId??null,input.projectNumber,input.name,input.description??null,input.startDate??null,input.expectedCompletionDate??null,input.currencyCode,input.estimatedBudget??null,input.approvedBudget??null,input.contractValue??null,input.paymentStatus??"not_required",input.billingCustomerReference??null,input.externalPaymentCustomerReference??null,actorId]);return row.rows[0];}
  async list(db:PoolClient,tenantId:string,q:ProjectListQuery):Promise<ProjectListResult>{const values:any[]=[tenantId];const filters=["tenant_id=$1"];
    if(q.search){values.push(`%${q.search}%`);filters.push(`(name ILIKE $${values.length} OR project_number ILIKE $${values.length} OR description ILIKE $${values.length})`);}
    if(q.status){values.push(q.status);filters.push(`status=$${values.length}`);}if(q.propertyId){values.push(q.propertyId);filters.push(`property_id=$${values.length}`);}if(q.clientId){values.push(q.clientId);filters.push(`client_id=$${values.length}`);}if(q.projectManagerId){values.push(q.projectManagerId);filters.push(`project_manager_id=$${values.length}`);}
    const where=filters.join(" AND ");const total=Number((await db.query<{count:string}>(`SELECT count(*) FROM projects WHERE ${where}`,values)).rows[0].count);values.push(q.pageSize,(q.page-1)*q.pageSize);
    const items=(await db.query<Project>(`SELECT ${select} FROM projects WHERE ${where} ORDER BY ${sortColumns[q.sortBy]} ${q.sortOrder==="asc"?"ASC":"DESC"} NULLS LAST LIMIT $${values.length-1} OFFSET $${values.length}`,values)).rows;
    return {items,pagination:{page:q.page,pageSize:q.pageSize,total,totalPages:Math.ceil(total/q.pageSize)}};
  }
  async update(db:PoolClient,tenantId:string,actorId:string,id:string,input:UpdateProjectCommand):Promise<Project|undefined>{const fields:{key:keyof UpdateProjectCommand;column:string}[]=[{key:"clientId",column:"client_id"},{key:"propertyId",column:"property_id"},{key:"financialOwnerLegalEntityId",column:"financial_owner_legal_entity_id"},{key:"projectManagerId",column:"project_manager_id"},{key:"projectNumber",column:"project_number"},{key:"name",column:"name"},{key:"description",column:"description"},{key:"startDate",column:"start_date"},{key:"expectedCompletionDate",column:"expected_completion_date"},{key:"currencyCode",column:"currency_code"},{key:"estimatedBudget",column:"estimated_budget"},{key:"approvedBudget",column:"approved_budget"},{key:"contractValue",column:"contract_value"},{key:"paymentStatus",column:"payment_status"},{key:"billingCustomerReference",column:"billing_customer_reference"},{key:"externalPaymentCustomerReference",column:"external_payment_customer_reference"}];const set:string[]=[];const values:any[]=[];for(const field of fields)if(input[field.key]!==undefined){values.push(input[field.key]);set.push(`${field.column}=$${values.length}`);}if(!set.length)return this.findById(db,tenantId,id);values.push(actorId,id,tenantId,input.expectedVersion);return (await db.query<Project>(`UPDATE projects SET ${set.join(",")},updated_by=$${values.length-3},updated_at=now(),version=version+1 WHERE id=$${values.length-2} AND tenant_id=$${values.length-1} AND version=$${values.length} AND deleted_at IS NULL RETURNING ${select}`,values)).rows[0];}
  async transition(db:PoolClient,tenantId:string,actorId:string,id:string,expectedVersion:number,from:ProjectStatus,to:ProjectStatus):Promise<Project|undefined>{return (await db.query<Project>(`UPDATE projects SET status=$1,start_date=CASE WHEN $1='active' AND start_date IS NULL THEN current_date ELSE start_date END,actual_completion_date=CASE WHEN $1='completed' THEN current_date ELSE actual_completion_date END,updated_by=$2,updated_at=now(),version=version+1 WHERE id=$3 AND tenant_id=$4 AND version=$5 AND status=$6 AND deleted_at IS NULL RETURNING ${select}`,[to,actorId,id,tenantId,expectedVersion,from])).rows[0];}
  async archive(db:PoolClient,tenantId:string,actorId:string,id:string,expectedVersion:number):Promise<Project|undefined>{return (await db.query<Project>(`UPDATE projects SET status='archived',deleted_at=now(),deleted_by=$1,updated_by=$1,updated_at=now(),version=version+1 WHERE id=$2 AND tenant_id=$3 AND version=$4 AND deleted_at IS NULL RETURNING ${select}`,[actorId,id,tenantId,expectedVersion])).rows[0];}
}
