import type{Pool}from"pg";import{domainErrors}from"../../domain/errors.js";import{agentRegistry}from"../../domain/ai-platform/agent-registry.js";import{documentQuery,missingPermissions,routeCommand}from"../../domain/ai-platform/orchestrator-rules.js";import{inUserTransaction}from"../../infrastructure/transaction.js";import type{AiActor,AiPlatformRepository,SourceReference}from"./ai-platform-repository.js";
type CommandInput={text:string;inputMode:"text"|"voice";projectId?:string};
export class AiSecretaryService{constructor(private pool:Pool,private repo:AiPlatformRepository){}
 registry(a:AiActor){if(!a.permissions.includes("ai_secretary.use"))throw domainErrors.forbidden();return agentRegistry.definitions.map(agent=>({...agent,available:missingPermissions(agent.requiredPermissions,a.permissions).length===0||(agent.id==="document"&&a.permissions.includes("client_workspace.read"))}))}
 history(a:AiActor){if(!a.permissions.includes("ai_audit.read"))throw domainErrors.forbidden();return inUserTransaction(this.pool,a.tenantId,a.id,db=>this.repo.history(db,a))}
 async execute(a:AiActor,input:CommandInput){if(!a.permissions.includes("ai_secretary.use"))throw domainErrors.forbidden();return inUserTransaction(this.pool,a.tenantId,a.id,async db=>{const route=routeCommand(input.text),missing=missingPermissions(route.requiredPermissions,a.permissions);let status="completed",truth=route.truth,message="",result:Record<string,unknown>={},sources:SourceReference[]=[],draft:any;
  if(input.inputMode==="voice"){status="unavailable";truth="UNAVAILABLE";message="Voice provider is not connected. The same command model is ready for ephemeral live input; audio is never stored or archived."}
  else if(missing.length&&!(route.intent==="open_document"&&a.permissions.includes("client_workspace.read"))){status="denied";truth="UNAVAILABLE";message="Permission denied for the selected authority.";result={missingPermissions:missing}}
  else if(route.intent==="calendar_notes"){status="unavailable";truth="UNAVAILABLE";message="Calendar and Notes providers are not connected."}
  else if(route.intent==="support"){truth="DERIVED";message="I can find permitted documents and invoices, explain estimates and attention items, or prepare contract/message drafts. No unsupported action was inferred."}
  else if(!input.projectId){status="insufficient_data";truth="PARTIAL";message="Insufficient data: project context is required.";result={missingData:["projectId"]}}
  else{const project=await this.repo.project(db,a,input.projectId);const projectAllowed=project&&(a.permissions.includes("projects.read")||await this.repo.clientProjectAccess(db,a,input.projectId));if(!projectAllowed)throw domainErrors.notFound();sources.push({entityType:"project",entityId:project.id,version:Number(project.version),label:project.name,status:project.status});
   if(route.intent==="open_document"){const document=await this.repo.findDocument(db,a,project.id,documentQuery(input.text));if(!document){status="insufficient_data";truth="PARTIAL";message="Insufficient data: no permitted document version matches the requested type, project and approval state.";result={missingData:["matching permitted document"]}}else{sources.push({entityType:"document",entityId:document.id,version:Number(document.version),label:document.title,status:document.status,timestamp:document.updatedAt,provenance:{sourceType:document.sourceType,documentType:document.documentType,documentVersionId:document.versionId,versionNo:document.versionNo,approvedDataId:document.approvedDataId??null,approvedAt:document.approvedAt??null}});message=`Opened ${document.title}, version ${document.versionNo}${document.approvedAt?", approved":""}.`;result={openTarget:{kind:"document",entityId:document.id,projectId:project.id},document}}
   }else if(route.intent==="list_invoices"){const invoices=await this.repo.invoices(db,a,project.id);sources.push(...invoices.map(x=>({entityType:"invoice",entityId:x.id,version:Number(x.version),label:x.invoiceNumber,status:x.status,timestamp:x.updatedAt})));message=invoices.length?`${invoices.length} permitted invoice record${invoices.length===1?"":"s"} found.`:"No permitted invoices were found for this project.";result={invoices,openTarget:{kind:"finance",projectId:project.id}};
   }else if(route.intent==="explain_estimate"){const estimate=await this.repo.estimate(db,a,project.id);if(!estimate){status="insufficient_data";truth="PARTIAL";message="Insufficient data: no Commercial Estimate revision exists for this project.";result={missingData:["commercial estimate revision"]}}else{sources.push({entityType:"commercial_estimate",entityId:estimate.id,version:Number(estimate.version),label:estimate.code,status:estimate.status,timestamp:estimate.updatedAt,provenance:{revisionNumber:estimate.revisionNumber,materialConsumptionSnapshotId:estimate.materialConsumptionSnapshotId,pricingSnapshotId:estimate.pricingSnapshotId,companyPriceBookSnapshotId:estimate.companyPriceBookSnapshotId}});truth="DERIVED";message=`Estimate ${estimate.code} revision ${estimate.revisionNumber} is grounded in its pinned material and pricing authorities.`;result={estimate,openTarget:{kind:"workspace",moduleId:"commercial-estimate",projectId:project.id,entityId:estimate.id}}}
   }else if(route.intent==="attention_summary"||route.intent==="material_delays"){const attention=await this.repo.attention(db,a,project.id);sources.push(...attention.map(x=>({entityType:x.entityType,entityId:x.id,version:Number(x.version),label:x.label,status:x.status})));truth="DERIVED";message=attention.length?`${attention.length} grounded project item${attention.length===1?" requires":"s require"} attention.`:"No loaded task authority currently declares an attention state.";result={attention};if(route.intent==="material_delays"&&attention.length===0)message="Insufficient data: no connected procurement or material-delivery authority exists; no delay was inferred.";
   }else if(route.intent==="weather_risk"){const weather=await this.repo.weather(db,a,project.id);if(!weather.length){status="unavailable";truth="UNAVAILABLE";message="Weather is unavailable because no current verified provider data is connected for this project.";result={provider:"UNAVAILABLE"}}else{sources.push(...weather.map(x=>({entityType:"weather_forecast",entityId:x.id,label:`${x.source} · ${x.locationLabel}`,timestamp:x.verifiedAt,provenance:{sourceReference:x.sourceReference,forecastAt:x.forecastAt}})));truth="DERIVED";message=`${weather.length} verified weather forecast record${weather.length===1?" is":"s are"} available for human project-risk review.`;result={weather}}
   }else if(route.intent==="draft_contract"){const client=await this.repo.findClient(db,a,project.id,"");const estimate=await this.repo.estimate(db,a,project.id),approvedEstimate=estimate?.status==="approved"?estimate:undefined,template=await this.repo.findDocument(db,a,project.id,{type:"contract",search:"",approved:true});const missingData=[!client&&"client",!approvedEstimate&&"approved estimate",!template&&"approved contract template"].filter(Boolean);if(client)sources.push({entityType:"client",entityId:client.id,version:Number(client.version),label:client.name,status:client.status});if(approvedEstimate)sources.push({entityType:"commercial_estimate",entityId:approvedEstimate.id,version:Number(approvedEstimate.version),label:approvedEstimate.code,status:approvedEstimate.status});if(template)sources.push({entityType:"document",entityId:template.id,version:Number(template.version),label:template.title,status:template.status,provenance:{versionId:template.versionId,versionNo:template.versionNo,approvedAt:template.approvedAt}});status="awaiting_human_review";truth="PARTIAL";message=missingData.length?`Contract draft prepared with missing data: ${missingData.join(", ")}. Human legal review is required.`:"Contract draft prepared from permitted project authorities. Human legal review is required before any final or sending action.";result={missingData,openTarget:{kind:"ai-draft",projectId:project.id}};
   }else if(route.intent==="draft_message"){status="awaiting_human_review";truth="PARTIAL";message="Message draft prepared. A human must review it; no external provider is connected and nothing was sent.";result={openTarget:{kind:"ai-draft",projectId:project.id},provider:"UNAVAILABLE"}}}
  const commandId=await this.repo.createCommand(db,a,{...input,intent:route.intent,agentId:route.agentId,truth,status,message,result,sources});if(status==="awaiting_human_review"&&input.projectId){draft=await this.repo.createDraft(db,a,{commandId,projectId:input.projectId,actionType:route.intent==="draft_contract"?"contract_draft":"message_draft",payload:{text:input.text,result,missingData:(result as any).missingData??[]},sources});(result as any).draft=draft}
  await this.repo.audit(db,a,"omniro_ai.command_processed",commandId,{intent:route.intent,agentId:route.agentId,status,truth,sourceReferences:sources.map(x=>({entityType:x.entityType,entityId:x.entityId,version:x.version})),draftId:draft?.id??null,humanConfirmation:false,inputMode:input.inputMode});return{id:commandId,inputMode:input.inputMode,intent:route.intent,agentId:route.agentId,truth,status,message,result,sources,requiredHumanAction:status==="awaiting_human_review"?"Review and approve through the existing authoritative UI; no action was executed.":undefined}
 })}
}
