import{expect,test}from"@playwright/test";

const projectId="00000000-0000-4000-8000-000000000071";
const assignmentId="10000000-0000-4000-8000-000000000003";
const designId="10000000-0000-4000-8000-000000000020";
const decisionId="10000000-0000-4000-8000-000000000022";

async function login(page:any,email="admin@demo.odls"){await page.goto("/#login");await page.getByLabel("Tenant").fill("demo");await page.getByLabel("Email").fill(email);await page.getByLabel("Password").fill("DemoPassword!2026");await page.getByRole("button",{name:"Sign in"}).click();await expect(page.getByRole("heading",{name:"Executive Dashboard"})).toBeVisible();}
async function workspace(page:any){await page.getByRole("button",{name:"Projects",exact:true}).click();await expect(page.getByRole("heading",{name:"Projects",exact:true})).toBeVisible();await page.getByLabel("Search projects").fill("Demo Project");await page.getByRole("button",{name:"Open workspace"}).click();await expect(page.getByRole("heading",{name:"Demo Project"})).toBeVisible();}

test.describe.serial("Construction UI project workflow",()=>{
 test("project workspace connects approved physical facts, customer intent and design intent",async({page})=>{await login(page);await workspace(page);await expect(page.getByRole("heading",{name:"Room Scanner"})).toBeVisible();await expect(page.getByRole("heading",{name:"Technical Assignment"})).toBeVisible();await expect(page.getByRole("heading",{name:"Design Project"})).toBeVisible();await page.getByRole("button",{name:"Room Scanner",exact:true}).click();await expect(page.getByText("Living room",{exact:true})).toBeVisible();await expect(page.getByText("floor_area")).toHaveCount(0);await expect(page.getByRole("heading",{name:"Approved Room Scan"})).toBeVisible();await page.getByRole("button",{name:"Technical Assignment",exact:true}).click();await page.locator(".record-selector select").selectOption(assignmentId);await expect(page.getByText("Refresh kitchen wall finish")).toBeVisible();await page.getByRole("button",{name:"Design Project",exact:true}).click();await expect(page.getByText("Room Scanner source")).toBeVisible();await expect(page.getByText("Technical Assignment source")).toBeVisible();await expect(page.getByText("Approved immutable source")).toHaveCount(2);});

 test("optimistic conflict preserves the pending design edit and never silently overwrites",async({page})=>{await login(page);await workspace(page);await page.getByRole("button",{name:"Design Project",exact:true}).click();await expect(page.getByText("Warm white wall paint")).toBeVisible();await page.getByRole("button",{name:"Edit"}).click();const input=page.getByLabel("Title or description");await input.fill("Pending designer choice");const result=await page.evaluate(async({designId,decisionId})=>{const session=JSON.parse(sessionStorage.getItem("odls.session")!);const headers={authorization:`Bearer ${session.accessToken}`,"content-type":"application/json"};const current=await fetch(`http://127.0.0.1:3100/api/v1/design-projects/${designId}`,{headers}).then(r=>r.json());return fetch(`http://127.0.0.1:3100/api/v1/design-projects/${designId}/decisions/${decisionId}`,{method:"PATCH",headers,body:JSON.stringify({expectedVersion:current.data.version,title:"Concurrent approved choice"})}).then(async r=>({status:r.status,body:await r.json()}));},{designId,decisionId});expect(result.status).toBe(200);await page.getByRole("button",{name:"Save change"}).click();await expect(page.getByText("This record was changed by another user.")).toBeVisible();await expect(input).toHaveValue("Pending designer choice");await page.getByRole("button",{name:"Reload authoritative data"}).click();await expect(page.getByText("Concurrent approved choice")).toBeVisible();});

 test("technical assignment lifecycle reaches an immutable approved snapshot",async({page})=>{await login(page);await workspace(page);await page.getByRole("button",{name:"Technical Assignment",exact:true}).click();await page.locator(".record-selector select").selectOption(assignmentId);await expect(page.getByText("Refresh kitchen wall finish")).toBeVisible();await page.getByRole("button",{name:"Edit"}).click();await page.getByLabel("Title or description").fill("Refresh kitchen walls and protect existing joinery");await page.getByRole("button",{name:"Save change"}).click();await expect(page.getByText("Refresh kitchen walls and protect existing joinery")).toBeVisible();await page.getByRole("button",{name:"Submit for review"}).click();await expect(page.getByRole("button",{name:"Accept statement"})).toBeVisible();await page.getByRole("button",{name:"Accept statement"}).click();await expect(page.getByText("Requested Work · Accepted · customer")).toBeVisible();await page.getByRole("button",{name:"Check readiness"}).click();await expect(page.getByRole("button",{name:"Approve assignment"})).toBeVisible();await page.getByRole("button",{name:"Approve assignment"}).click();await expect(page.getByRole("dialog")).toBeVisible();await page.getByRole("dialog").getByRole("button",{name:"Approve revision"}).click();await expect(page.getByRole("heading",{name:"Approved Technical Assignment"})).toBeVisible();await expect(page.getByText("technical-assignment-v1")).toBeVisible();});

 test("design lifecycle validates both source snapshots and reaches approval",async({page})=>{await login(page);await workspace(page);await page.getByRole("button",{name:"Design Project",exact:true}).click();await expect(page.getByText("room-geometry-v1")).toBeVisible();await expect(page.getByText("technical-assignment-v1")).toBeVisible();await page.getByRole("button",{name:"Submit for review"}).click();await expect(page.getByRole("button",{name:"Check readiness"})).toBeVisible();await page.getByRole("button",{name:"Check readiness"}).click();await expect(page.getByRole("button",{name:"Approve design"})).toBeVisible();await page.getByRole("button",{name:"Approve design"}).click();await expect(page.getByRole("dialog")).toBeVisible();await page.getByRole("dialog").getByRole("button",{name:"Approve revision"}).click();await expect(page.getByRole("heading",{name:"Approved Design Project"})).toBeVisible();await expect(page.getByText("design-project-v1")).toBeVisible();});

 test("read-only user can inspect the workflow but protected mutation is denied",async({page})=>{await login(page,"readonly@demo.odls");await workspace(page);await page.getByRole("button",{name:"Room Scanner",exact:true}).click();await expect(page.getByText("Living room",{exact:true})).toBeVisible();await page.getByRole("button",{name:"Technical Assignment",exact:true}).click();await expect(page.getByRole("button",{name:"Edit"})).toHaveCount(0);await page.getByRole("button",{name:"Design Project",exact:true}).click();await expect(page.getByRole("button",{name:"Approve design"})).toHaveCount(0);const status=await page.evaluate(async({designId})=>{const session=JSON.parse(sessionStorage.getItem("odls.session")!);return fetch(`http://127.0.0.1:3100/api/v1/design-projects/${designId}/transition`,{method:"POST",headers:{authorization:`Bearer ${session.accessToken}`,"content-type":"application/json"},body:JSON.stringify({status:"cancelled",expectedVersion:1})}).then(r=>r.status);},{designId});expect(status).toBe(403);});
});
