import {expect,test} from "@playwright/test";
test("Finance rendered lifecycle, concurrency, selectors and full payment",async({page,request})=>{
  const stamp=Date.now(),consoleErrors:string[]=[],serverErrors:string[]=[];
  page.on("console",m=>{if(m.type()==="error")consoleErrors.push(m.text());});page.on("pageerror",e=>consoleErrors.push(e.message));page.on("response",r=>{if(r.status()>=500)serverErrors.push(`${r.status()} ${r.url()}`);});
  const login=await request.post("http://127.0.0.1:3000/api/v1/auth/login",{data:{tenantSlug:"demo",email:"admin@demo.odls",password:"DemoPassword!2026"}}),token=(await login.json()).data.accessToken,headers={authorization:`Bearer ${token}`};
  const projectResponse=await request.post("http://127.0.0.1:3000/api/v1/projects",{headers,data:{clientId:"00000000-0000-4000-8000-000000000041",propertyId:"00000000-0000-4000-8000-000000000061",financialOwnerLegalEntityId:"00000000-0000-4000-8000-000000000021",projectNumber:`E2E-${stamp}`,name:`E2E Project ${stamp}`,currencyCode:"EUR"}}),project=(await projectResponse.json()).data;
  await page.goto("/");await page.getByLabel("Tenant").fill("demo");await page.getByLabel("Email").fill("admin@demo.odls");await page.getByLabel("Password").fill("DemoPassword!2026");await page.getByRole("button",{name:"Sign in"}).click();await page.getByRole("button",{name:"Finance"}).click();
  await expect(page.getByLabel("Finance client")).toContainText("Demo Client");await page.getByLabel("Finance client").selectOption("00000000-0000-4000-8000-000000000041");await page.getByLabel("Finance project").selectOption(project.id);
  const number=`E2E-I-${stamp}`;await page.getByLabel("Invoice number").fill(number);await page.getByLabel("Invoice net amount").fill("100.0000");await page.getByLabel("Invoice VAT rate").fill("0.0000");await page.getByRole("button",{name:"Create invoice"}).click();
  await page.getByRole("button",{name:number}).click();await page.getByRole("button",{name:"Edit invoice"}).click();await expect(page.getByText("version 2")).toBeVisible();
  const invoiceId=(await (await request.get(`http://127.0.0.1:3000/api/v1/invoices?search=${number}`,{headers})).json()).data[0].id;await request.patch(`http://127.0.0.1:3000/api/v1/invoices/${invoiceId}`,{headers,data:{expectedVersion:2,notes:"external"}});
  await page.getByRole("button",{name:"Edit invoice"}).click();await expect(page.getByRole("alert")).toContainText("changed in another session");consoleErrors.length=0;await page.getByRole("button",{name:"Reload Finance"}).click();await page.getByRole("button",{name:number}).click();await page.getByRole("button",{name:"Edit invoice"}).click();await expect(page.getByText("version 4")).toBeVisible();
  await page.getByRole("button",{name:"Issue invoice"}).click();await expect(page.getByText("Status issued")).toBeVisible();await expect(page.getByRole("button",{name:"Issue invoice"})).toHaveCount(0);
  for(const [ref,amount] of [[`E2E-P1-${stamp}`,"40.0000"],[`E2E-P2-${stamp}`,"60.0000"]]){await page.getByLabel("Payment reference").fill(ref);await page.getByLabel("Payment amount").fill(amount);await page.getByRole("button",{name:"Create payment"}).click();await page.getByLabel("Allocation invoice").selectOption(invoiceId);await page.getByLabel("Allocation amount").fill(amount);await page.getByRole("button",{name:"Allocate payment"}).click();}
  await page.getByRole("button",{name:number}).click();await expect(page.getByText("Status paid")).toBeVisible();await expect(page.getByText("Status paid; net 100.0000; VAT 0.0000; gross 100.0000; paid 100.0000; outstanding 0.0000; version 7",{exact:true})).toBeVisible();
  const cancelNumber=`E2E-CANCEL-${stamp}`;await page.getByLabel("Invoice number").fill(cancelNumber);await page.getByRole("button",{name:"Create invoice"}).click();await page.getByRole("button",{name:"Cancel invoice"}).click();await expect(page.getByText("Status cancelled")).toBeVisible();await expect(page.getByRole("button",{name:"Cancel invoice"})).toHaveCount(0);
  const archiveNumber=`E2E-ARCHIVE-${stamp}`;await page.getByLabel("Invoice number").fill(archiveNumber);await page.getByRole("button",{name:"Create invoice"}).click();await page.getByRole("button",{name:"Archive invoice"}).click();await expect(page.getByText("Status archived")).toBeVisible();await expect(page.getByRole("button",{name:"Archive invoice"})).toHaveCount(0);
  const reverseReference=`E2E-REVERSE-${stamp}`;await page.getByLabel("Payment reference").fill(reverseReference);await page.getByLabel("Payment amount").fill("5.0000");await page.getByRole("button",{name:"Create payment"}).click();await page.getByRole("button",{name:"Reverse payment"}).click();await expect(page.getByText("Status reversed")).toBeVisible();await expect(page.getByRole("button",{name:"Reverse payment"})).toHaveCount(0);await page.getByRole("button",{name:"Archive payment"}).click();await expect(page.getByText("Status archived")).toBeVisible();await expect(page.getByRole("button",{name:"Archive payment"})).toHaveCount(0);
  await page.getByLabel("Invoice net amount").fill("20.0000");await page.getByLabel("Expense supplier").fill(`E2E Supplier ${stamp}`);await page.getByLabel("Expense category").fill("materials");await page.getByRole("button",{name:"Create expense"}).click();await page.getByRole("button",{name:`E2E Supplier ${stamp}`}).click();await page.getByRole("button",{name:"Edit expense"}).click();await page.getByRole("button",{name:"Approve expense"}).click();await expect(page.getByText("Status approved")).toBeVisible();await expect(page.getByRole("button",{name:"Approve expense"})).toHaveCount(0);
  await page.getByRole("button",{name:"Load financial summary"}).click();await expect(page.getByText("Margin amount 80.0000")).toBeVisible();expect(consoleErrors).toEqual([]);expect(serverErrors).toEqual([]);
  const rejectSupplier=`E2E Reject ${stamp}`;await page.getByLabel("Expense supplier").fill(rejectSupplier);await page.getByRole("button",{name:"Create expense"}).click();await page.getByRole("button",{name:"Reject expense"}).click();await expect(page.getByText("Status rejected")).toBeVisible();await expect(page.getByRole("button",{name:"Reject expense"})).toHaveCount(0);
  const archiveSupplier=`E2E Archive ${stamp}`;await page.getByLabel("Expense supplier").fill(archiveSupplier);await page.getByRole("button",{name:"Create expense"}).click();await page.getByRole("button",{name:"Archive expense"}).click();const archivedExpense=page.getByRole("article").filter({hasText:`Expense detail ${archiveSupplier}`});await expect(archivedExpense.getByText("Status archived")).toBeVisible();await expect(archivedExpense.getByRole("button",{name:"Archive expense"})).toHaveCount(0);
  const negativeProject=await (await request.post("http://127.0.0.1:3000/api/v1/projects",{headers,data:{clientId:"00000000-0000-4000-8000-000000000041",propertyId:"00000000-0000-4000-8000-000000000061",financialOwnerLegalEntityId:"00000000-0000-4000-8000-000000000021",projectNumber:`E2E-NEG-${stamp}`,name:`E2E Negative ${stamp}`,currencyCode:"EUR"}})).json();
  const negativeInvoice=await (await request.post("http://127.0.0.1:3000/api/v1/invoices",{headers,data:{clientId:"00000000-0000-4000-8000-000000000041",projectId:negativeProject.data.id,invoiceNumber:`NEG-I-${stamp}`,currencyCode:"EUR",issueDate:"2026-01-01",dueDate:"2026-01-10",netAmount:"10.0000",vatRate:"0.0000"}})).json();await request.post(`http://127.0.0.1:3000/api/v1/invoices/${negativeInvoice.data.id}/issue`,{headers,data:{expectedVersion:negativeInvoice.data.version}});
  const negativeExpense=await (await request.post("http://127.0.0.1:3000/api/v1/expenses",{headers,data:{projectId:negativeProject.data.id,supplier:`NEG ${stamp}`,category:"materials",expenseDate:"2026-01-02",currencyCode:"EUR",netAmount:"20.0000",vatRate:"0.0000"}})).json();await request.post(`http://127.0.0.1:3000/api/v1/expenses/${negativeExpense.data.id}/approve`,{headers,data:{expectedVersion:negativeExpense.data.version}});
  const zeroProject=await (await request.post("http://127.0.0.1:3000/api/v1/projects",{headers,data:{clientId:"00000000-0000-4000-8000-000000000041",propertyId:"00000000-0000-4000-8000-000000000061",financialOwnerLegalEntityId:"00000000-0000-4000-8000-000000000021",projectNumber:`E2E-ZERO-${stamp}`,name:`E2E Zero ${stamp}`,currencyCode:"EUR"}})).json();
  await page.getByRole("button",{name:"Reload Finance"}).click();await page.getByLabel("Finance project").selectOption(negativeProject.data.id);await page.getByRole("button",{name:"Load financial summary"}).click();await expect(page.getByText("Margin amount -10.0000")).toBeVisible();
  await page.getByLabel("Finance project").selectOption(zeroProject.data.id);await page.getByRole("button",{name:"Load financial summary"}).click();await expect(page.getByText(/margin percentage not applicable/)).toBeVisible();expect(consoleErrors).toEqual([]);expect(serverErrors).toEqual([]);
});

test("Documents secure rendered upload, versioning, conflict, download and archive",async({page,request})=>{
 const stamp=Date.now(),consoleErrors:string[]=[],serverErrors:string[]=[];page.on("console",m=>{if(m.type()==="error")consoleErrors.push(m.text());});page.on("pageerror",e=>consoleErrors.push(e.message));page.on("response",r=>{if(r.status()>=500)serverErrors.push(`${r.status()} ${r.url()}`);});
 const login=await request.post("http://127.0.0.1:3000/api/v1/auth/login",{data:{tenantSlug:"demo",email:"admin@demo.odls",password:"DemoPassword!2026"}}),token=(await login.json()).data.accessToken,headers={authorization:`Bearer ${token}`};
 const project=await (await request.post("http://127.0.0.1:3000/api/v1/projects",{headers,data:{clientId:"00000000-0000-4000-8000-000000000041",propertyId:"00000000-0000-4000-8000-000000000061",financialOwnerLegalEntityId:"00000000-0000-4000-8000-000000000021",projectNumber:`DOC-${stamp}`,name:`Document Project ${stamp}`,currencyCode:"EUR"}})).json();
 await page.goto("/");await page.getByLabel("Tenant").fill("demo");await page.getByLabel("Email").fill("admin@demo.odls");await page.getByLabel("Password").fill("DemoPassword!2026");await page.getByRole("button",{name:"Sign in"}).click();await page.getByRole("button",{name:"Documents"}).click();
 await expect(page.getByLabel("Document target",{exact:true})).toContainText(`Document Project ${stamp}`);await page.getByLabel("Document target",{exact:true}).selectOption(project.data.id);await page.getByLabel("Document description").fill("E2E document");await page.getByLabel("Document file").setInputFiles({name:`document-${stamp}.pdf`,mimeType:"application/pdf",buffer:Buffer.from("%PDF-1.4\\nfirst version")});await page.getByRole("button",{name:"Upload document"}).click();await expect(page.getByRole("heading",{name:new RegExp(`Document detail document-${stamp}.pdf`)})).toBeVisible();
 const listed=await (await request.get(`http://127.0.0.1:3000/api/v1/documents?search=document-${stamp}`,{headers})).json(),id=listed.data[0].id;const download=await request.get(`http://127.0.0.1:3000/api/v1/documents/${id}/download`,{headers});expect(download.status()).toBe(200);expect(download.headers()["x-content-type-options"]).toBe("nosniff");expect(download.headers()["content-disposition"]).toContain("attachment");
 await page.getByRole("button",{name:"Edit document metadata"}).click();await expect(page.getByText(/record version 2/)).toBeVisible();await request.patch(`http://127.0.0.1:3000/api/v1/documents/${id}`,{headers,data:{expectedVersion:2,description:"external"}});await page.getByRole("button",{name:"Edit document metadata"}).click();await expect(page.getByRole("alert")).toContainText("changed in another session");consoleErrors.length=0;
 await page.getByRole("button",{name:"Reload Documents"}).click();await page.getByRole("button",{name:`document-${stamp}.pdf`}).click();await page.getByLabel("New document version").setInputFiles({name:`document-${stamp}.pdf`,mimeType:"application/pdf",buffer:Buffer.from("%PDF-1.4\\nsecond version")});await page.getByRole("button",{name:"Upload new version"}).click();await expect(page.getByRole("button",{name:"Download version 2"})).toBeVisible();await expect(page.getByRole("button",{name:"Download version 1"})).toBeVisible();
 await page.getByRole("button",{name:"Archive document"}).click();await expect(page.getByRole("button",{name:"Archive document"})).toHaveCount(0);await expect(page.getByRole("button",{name:"Upload new version"})).toHaveCount(0);expect((await request.get(`http://127.0.0.1:3000/api/v1/documents/${id}/download`,{headers})).status()).toBe(200);
 await page.getByLabel("Document file").setInputFiles({name:"blocked.js",mimeType:"application/javascript",buffer:Buffer.from("alert(1)")});await page.getByRole("button",{name:"Upload document"}).click();await expect(page.getByRole("alert")).toContainText("invalid");consoleErrors.length=0;expect(serverErrors).toEqual([]);
});
