import{expect,test,type Page}from"@playwright/test";

async function login(page:Page,target="#omniro/role/accountant"){await page.goto("/#login");await page.getByLabel("Tenant").fill("demo");await page.getByLabel("Email").fill("admin@demo.odls");await page.getByLabel("Password").fill("DemoPassword!2026");await page.getByRole("button",{name:"Sign in"}).click();await expect(page.getByRole("heading",{name:"Executive Dashboard"})).toBeVisible();await page.goto(`/${target}`);await expect(page.locator(".oe-accountant-v1")).toBeVisible()}

test.describe("OMNIRO Accountant Workspace V1",()=>{
 test("opens the permission-grounded role without changing authenticated actor",async({page})=>{await login(page);await expect(page.getByRole("heading",{name:"Accountant Workspace"})).toBeVisible();await expect(page.getByText(/actions remain attributed to actor/)).toBeVisible();await expect(page.locator(".oe-role-rail button").filter({hasText:"Accountant"})).toBeEnabled();await expect(page.locator(".oe-role-rail button").filter({hasText:"Project Manager"})).toBeDisabled();await expect(page).toHaveURL(/#omniro\/role\/accountant$/)});
 test("shows grounded accounting sources, provenance and explicit unavailable providers",async({page})=>{await login(page);await expect(page.getByRole("heading",{name:"Accounting inbox"})).toBeVisible();await expect(page.getByRole("heading",{name:"Operational registers"})).toBeVisible();await expect(page.getByText(/project-financial-summary:/)).toBeVisible();await expect(page.getByText("No KSeF provider, credential or submission authority is connected.",{exact:true})).toBeVisible();await expect(page.getByText(/no bank account or bank-feed integration/i)).toBeVisible();await expect(page.getByText(/No autonomous posting, approval or tax advice/)).toBeVisible();await expect(page.getByText("12.45M")).toHaveCount(0)});
 test("switches between real role projections while preserving the route model",async({page})=>{await login(page);await page.locator(".oe-role-rail button").filter({hasText:"Director / Owner"}).click();await expect(page).toHaveURL(/#omniro\/role\/director$/);await expect(page.getByRole("heading",{name:"Director / Owner Workspace"})).toBeVisible();await page.locator(".oe-role-rail button").filter({hasText:"Accountant"}).click();await expect(page).toHaveURL(/#omniro\/role\/accountant$/);await expect(page.getByRole("heading",{name:"Accountant Workspace"})).toBeVisible()});
 test("preserves keyboard access, reduced motion and mobile composition",async({page})=>{await page.setViewportSize({width:390,height:844});await page.emulateMedia({reducedMotion:"reduce"});await login(page);const finance=page.getByRole("button",{name:"Invoices · Expenses · Payments",exact:true});await finance.focus();await expect(finance).toBeFocused();const size=await page.locator("body").evaluate(element=>({scrollWidth:element.scrollWidth,clientWidth:element.clientWidth}));expect(size.scrollWidth).toBeLessThanOrEqual(size.clientWidth+1)});
});
