import{mkdir,copyFile}from"node:fs/promises";import{resolve}from"node:path";import{expect,test}from"@playwright/test";
const dir=resolve("artifacts/omniro-stage-1-final");test.use({video:"on"});test.beforeEach(async({page})=>{await mkdir(dir,{recursive:true});await page.addInitScript(()=>localStorage.setItem("omnira.public.intro","seen"));await page.goto("/")});
const step=async(page:any,id:string)=>{await page.getByLabel("Living system sequence").getByRole("button",{name:new RegExp(`^${id} `)}).click();await page.waitForTimeout(520);await page.evaluate(()=>scrollTo(0,0))};const shot=async(page:any,name:string)=>page.screenshot({path:resolve(dir,name),fullPage:false});
test("captures final reference-locked desktop states A through L",async({page})=>{await page.setViewportSize({width:1440,height:1000});await step(page,"00");await shot(page,"A-upgraded-omniro-core-close-up.png");await step(page,"06");await shot(page,"B-scanner-actual-scanning.png");await step(page,"09");await shot(page,"C-payload-traveling-scanner-passport.png");await step(page,"13");await shot(page,"D-payload-stopped-at-approval-gate.png");await page.getByRole("button",{name:"Approve and open gate"}).click();await step(page,"15");await shot(page,"E-payload-continuing-after-approval.png");await step(page,"16");await shot(page,"F-norms-visible-validation.png");await step(page,"18");await shot(page,"G-estimate-visible-calculation.png");await step(page,"20");await shot(page,"H-estimate-result-traveling-analytics.png");await step(page,"22");await shot(page,"I-analytics-insight-transformation.png");await step(page,"24");await shot(page,"J-orchestrator-routing.png");await step(page,"25");await shot(page,"K-ask-orchestrator.png");await page.getByRole("button",{name:"Close explanation"}).click();await step(page,"28");await shot(page,"L-scanner-workspace-transition.png")});
test("captures final mobile living system",async({page})=>{await page.setViewportSize({width:390,height:844});await step(page,"09");await page.locator(".stage-one-hero").screenshot({path:resolve(dir,"M-mobile-living-system.png")})});
test("records exact final interaction 00 through 29",async({page},testInfo)=>{test.setTimeout(150_000);await page.setViewportSize({width:1440,height:1000});for(let i=0;i<30;i++){const id=String(i).padStart(2,"0");await step(page,id);if(id==="13"){await page.waitForTimeout(1000);await page.getByRole("button",{name:"Approve and open gate"}).click()}if(id==="25"){await page.waitForTimeout(1000);await page.getByRole("button",{name:"Close explanation"}).click()}await page.waitForTimeout([0,6,9,16,18,20,22,24,28].includes(i)?1250:650)}const video=page.video();await page.close();if(video){const source=await video.path();await copyFile(source,resolve(dir,"N-full-final-interaction-00-29.webm"));await testInfo.attach("full-final-interaction",{path:source,contentType:"video/webm"})}await expect(true).toBe(true)});

const acceptanceDir=resolve("artifacts/omniro-stage-1-acceptance-fix");
test("captures surgical acceptance evidence A through F",async({page})=>{await mkdir(acceptanceDir,{recursive:true});await page.setViewportSize({width:1440,height:1000});for(const [id,name] of [["06","A-scanner-actual-scanning.png"],["09","B-scanner-passport-payload-mid-flight.png"],["16","C-norms-validation.png"],["18","D-estimate-calculation.png"],["20","E-estimate-analytics-payload-mid-flight.png"],["22","F-analytics-insight.png"]] as const){await step(page,id);await page.waitForTimeout(650);await page.screenshot({path:resolve(acceptanceDir,name),fullPage:false})}});
test("records focused surgical acceptance review",async({page},testInfo)=>{test.setTimeout(90_000);await mkdir(acceptanceDir,{recursive:true});await page.setViewportSize({width:1440,height:1000});const review=["03","06","07","09","11","13","15","16","17","18","19","20","21","22"];for(const id of review){await step(page,id);if(id==="13"){await page.waitForTimeout(700);await page.getByRole("button",{name:"Approve and open gate"}).click()}await page.waitForTimeout(["06","09","16","18","20","22"].includes(id)?1100:550)}const video=page.video();await page.close();if(video){const source=await video.path();await copyFile(source,resolve(acceptanceDir,"G-short-final-review.webm"));await testInfo.attach("surgical-acceptance-review",{path:source,contentType:"video/webm"})}await expect(true).toBe(true)});
