import{expect,test,type Page}from"@playwright/test";

async function login(page:Page,target="#omniro/role/director"){await page.goto("/#login");await page.getByLabel("Tenant").fill("demo");await page.getByLabel("Email").fill("admin@demo.odls");await page.getByLabel("Password").fill("DemoPassword!2026");await page.getByRole("button",{name:"Sign in"}).click();await expect(page.getByRole("heading",{name:"Executive Dashboard"})).toBeVisible();await page.goto(`/${target}`);await expect(page.locator(".oe-director-v1")).toBeVisible()}

test.describe("OMNIRO Director Owner Workspace V1",()=>{
 test("projects the real actor, role registry, grounded metrics and source limitations",async({page})=>{await login(page);await expect(page.getByRole("heading",{name:"Director / Owner Workspace"})).toBeVisible();await expect(page.getByText(/actions remain attributed to actor/)).toBeVisible();await expect(page.locator(".oe-role-rail button").filter({hasText:"Director / Owner"})).toBeEnabled();await expect(page.locator(".oe-role-rail button").filter({hasText:"Accountant"})).toBeEnabled();await expect(page.locator(".oe-role-rail button").filter({hasText:"Project Manager"})).toBeDisabled();await expect(page.getByText("Temporary access")).toBeVisible();await expect(page.getByText(/future backend authority/)).toBeVisible();await expect(page.getByText("12.45M")).toHaveCount(0);await expect(page.getByText("18.7%")).toHaveCount(0)});
 test("shows grounded priority provenance and uses existing approval workspaces",async({page})=>{await login(page);const actions=page.locator(".oe-priority-actions button");if(await actions.count()){await expect(actions.first().locator("i")).not.toHaveText("")}else await expect(page.getByText("No loaded source reports an actionable state.")).toBeVisible();const decision=page.locator(".oe-decision-center button").first();if(await decision.count()){await decision.click();await expect(page).toHaveURL(/#omniro\/project\/.+\/workspace\//);await expect(page.getByText("AGENT WORKSPACE · SAME OPERATIONAL SYSTEM")).toBeVisible()}else await expect(page.getByText("No existing approval adapter currently requires the Director.")).toBeVisible()});
 test("keeps assistants and communications truthful while preserving real source access",async({page})=>{await login(page);await expect(page.getByText("Company accounting profit is not inferred.")).toBeVisible();await expect(page.getByText("No law-change claim is generated.")).toBeVisible();await expect(page.getByText("No email provider is connected.")).toBeVisible();await expect(page.getByText("No WhatsApp provider is connected.")).toBeVisible();await expect(page.getByText(/Task and project deadlines are connected/)).toBeVisible();await page.getByRole("button",{name:"Documents",exact:true}).last().click();await expect(page.getByRole("heading",{name:"Documents"})).toBeVisible()});
 test("preserves mobile task-first composition, keyboard, deep links and reduced motion",async({page})=>{await page.setViewportSize({width:390,height:844});await page.emulateMedia({reducedMotion:"reduce"});await login(page);const priceBook=page.getByRole("button",{name:"Company Price Book",exact:true}).last();await priceBook.focus();await expect(priceBook).toBeFocused();const size=await page.locator("body").evaluate(element=>({scrollWidth:element.scrollWidth,clientWidth:element.clientWidth}));expect(size.scrollWidth).toBeLessThanOrEqual(size.clientWidth+1);await priceBook.click();await expect(page).toHaveURL(/#omniro\/project\/.+\/workspace\/company-price-book/);await expect(page.getByLabel("Company Price Book Agent Workspace")).toBeVisible()});
});
