import{test,expect}from"@playwright/test";

test.describe("OMNIRA public experience",()=>{
 test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem("omnira.public.intro","seen"));await page.goto("/")});

 test("desktop silent journey explains capabilities and enters existing authentication",async({page})=>{await expect(page.getByRole("heading",{level:1})).toContainText("real-world engineering");await page.getByRole("link",{name:"How it works"}).click();await expect(page.getByText(/Illustrative data · not connected/)).toBeVisible();await expect(page.getByRole("heading",{name:"This value exists because…"})).toBeVisible();await page.getByRole("banner").getByRole("button",{name:"Enter OMNIRO"}).click();await expect(page.getByRole("heading",{name:"Sign in to OMNIRA"})).toBeAttached();await page.goBack();await expect(page.getByRole("heading",{level:1})).toBeVisible()});

 test("sound requires consent and exposes pause, mute and captions",async({page})=>{await page.getByRole("complementary",{name:"Experience controls"}).getByRole("button",{name:"Replay"}).click();const dialog=page.getByRole("dialog",{name:"OMNIRO birth sequence"});await expect(dialog.getByRole("button",{name:"Start with sound"})).toBeVisible();await expect(dialog.getByText("Sound never autoplays.")).toBeVisible();await dialog.getByRole("button",{name:"Start silently"}).click();await expect(dialog.getByRole("button",{name:"Pause"})).toBeVisible();await dialog.getByRole("button",{name:"Pause"}).click();await expect(dialog.getByRole("button",{name:"Resume"})).toBeVisible();await expect(dialog.getByRole("button",{name:"Mute"})).toHaveAttribute("aria-pressed","true");await expect(dialog.getByRole("button",{name:"Captions on"})).toHaveAttribute("aria-pressed","true");await dialog.getByRole("button",{name:"Skip introduction"}).click()});

 test("investor, future galaxy and governed learning paths remain truthful",async({page})=>{await page.getByRole("link",{name:"Investor Experience"}).first().click();await expect(page.getByRole("heading",{name:"Current product, reusable core, explicit horizon."})).toBeVisible();await expect(page.getByText(/No confidential projections/)).toBeVisible();await page.getByRole("link",{name:"Explore OMNIRA"}).click();await expect(page.getByText("Healthcare",{exact:true})).toBeVisible();await expect(page.getByText(/Not yet awakened/).first()).toBeVisible();await page.getByRole("link",{name:"What OMNIRO learned"}).click();await expect(page.getByText(/OMNIRO learned to explain why/)).toBeVisible();await expect(page.getByText(/weather-related construction risks/)).toHaveCount(0)});

 test("language, static mode, install fallback and mobile layout remain controlled",async({page})=>{await page.getByLabel("Language").selectOption("pl");await expect(page.getByRole("heading",{level:1})).toContainText("rzeczywistej inżynierii");await page.getByRole("button",{name:"Use static experience"}).click();await expect(page.locator(".public-site")).toHaveClass(/public-static/);await page.getByRole("button",{name:"Install guidance"}).click();await expect(page.getByRole("status")).toContainText("no native iOS or Android app is claimed");await page.setViewportSize({width:390,height:844});const width=await page.locator("body").evaluate(el=>({scroll:el.scrollWidth,client:el.clientWidth}));expect(width.scroll).toBeLessThanOrEqual(width.client+1)});
});
