import {expect,test,type APIRequestContext} from "@playwright/test";
import {readFile} from "node:fs/promises";

async function login(page:any,email="admin@demo.odls"){
 await page.goto("/#login");await page.getByLabel("Tenant").fill("demo");await page.getByLabel("Email").fill(email);await page.getByLabel("Password").fill("DemoPassword!2026");await page.getByRole("button",{name:"Sign in"}).click();
}
async function createReportFixtures(request:APIRequestContext){
 const stamp=Date.now(),loginResponse=await request.post("http://127.0.0.1:3100/api/v1/auth/login",{data:{tenantSlug:"demo",email:"admin@demo.odls",password:"DemoPassword!2026"}}),token=(await loginResponse.json()).data.accessToken,headers={authorization:`Bearer ${token}`},date=(days:number)=>new Date(Date.now()+days*86400000).toISOString().slice(0,10);
 const projectResponse=await request.post("http://127.0.0.1:3100/api/v1/projects",{headers,data:{clientId:"00000000-0000-4000-8000-000000000041",propertyId:"00000000-0000-4000-8000-000000000061",financialOwnerLegalEntityId:"00000000-0000-4000-8000-000000000021",projectNumber:`REPORT-${stamp}`,name:`Report Fixture ${stamp}`,currencyCode:"EUR"}});expect(projectResponse.ok()).toBe(true);const project=(await projectResponse.json()).data;
 const invoiceResponse=await request.post("http://127.0.0.1:3100/api/v1/invoices",{headers,data:{clientId:"00000000-0000-4000-8000-000000000041",projectId:project.id,invoiceNumber:`REPORT-I-${stamp}`,currencyCode:"EUR",issueDate:date(-10),dueDate:date(-1),netAmount:"100.0000",vatRate:"0.0000"}});expect(invoiceResponse.ok()).toBe(true);const invoice=(await invoiceResponse.json()).data;expect((await request.post(`http://127.0.0.1:3100/api/v1/invoices/${invoice.id}/issue`,{headers,data:{expectedVersion:invoice.version}})).ok()).toBe(true);
 const expenseResponse=await request.post("http://127.0.0.1:3100/api/v1/expenses",{headers,data:{projectId:project.id,supplier:`Report Supplier ${stamp}`,category:"materials",expenseDate:date(-2),currencyCode:"EUR",netAmount:"20.0000",vatRate:"0.0000"}});expect(expenseResponse.ok()).toBe(true);const expense=(await expenseResponse.json()).data;expect((await request.post(`http://127.0.0.1:3100/api/v1/expenses/${expense.id}/approve`,{headers,data:{expectedVersion:expense.version}})).ok()).toBe(true);
 expect((await request.post("http://127.0.0.1:3100/api/v1/documents",{headers,multipart:{category:"other",description:"Reports E2E fixture",entityType:"project",entityId:project.id,file:{name:`report-${stamp}.pdf`,mimeType:"application/pdf",buffer:Buffer.from("%PDF-1.4\\nreport fixture")}}})).ok()).toBe(true);
}
test("dashboard charts and interactive report controls use live backend data",async({page,request})=>{
 const failures:string[]=[];page.on("console",message=>{if(message.type()==="error")failures.push(message.text());});page.on("response",response=>{if(response.status()>=500)failures.push(`${response.status()} ${response.url()}`);});
 await createReportFixtures(request);
 await login(page);await expect(page.getByRole("heading",{name:"Executive Dashboard"})).toBeVisible();
 await page.getByLabel("Dashboard date range").selectOption("90");await expect(page.getByText(/UTC reporting period/)).toBeVisible();await expect(page.getByRole("heading",{name:"Project health"})).toBeVisible();for(const chart of ["Task status distribution","Project health distribution","Revenue by month and currency","Expenses by month and currency"])await expect(page.getByRole("figure",{name:chart})).toBeVisible();
 await page.getByRole("button",{name:"Reports"}).click();await expect(page.getByRole("heading",{name:"Operational Reports"})).toBeVisible();
 await page.getByLabel("Report date range").selectOption("90");await page.getByLabel("Rows per page").selectOption("5");await page.getByText("Overdue only").click();await expect(page.getByRole("table")).toBeVisible();
 const reportResult=page.getByRole("table").or(page.getByText("No report rows.")),firstLinks=page.locator("tbody tr").first().locator("button.link-button"),client=await firstLinks.nth(1).getAttribute("data-entity-id");if(client){await page.getByLabel("Report client filter").selectOption(client);await expect(reportResult).toBeVisible();await page.getByLabel("Report client filter").selectOption("");}const project=await page.getByLabel("Report project filter").locator("option").nth(1).getAttribute("value");if(project){await page.getByLabel("Report project filter").selectOption(project);await expect(reportResult).toBeVisible();await page.getByLabel("Report project filter").selectOption("");}const currency=await page.getByLabel("Report currency filter").locator("option").nth(1).getAttribute("value");if(currency){await page.getByLabel("Report currency filter").selectOption(currency);await expect(reportResult).toBeVisible();await page.getByLabel("Report currency filter").selectOption("");}await expect(page.getByText(/^Page 1 of/)).toBeVisible();
 await page.getByRole("button",{name:"Sort by outstanding"}).click();await expect(page.getByRole("button",{name:"Sort by outstanding"})).toContainText("↑");await page.getByRole("button",{name:"Sort by outstanding"}).click();await expect(page.getByRole("button",{name:"Sort by outstanding"})).toContainText("↓");
 await page.getByRole("button",{name:"Clear filters"}).click();if(await page.getByRole("button",{name:"Next"}).isEnabled()){await page.getByRole("button",{name:"Next"}).click();await expect(page.getByText(/^Page 2 of/)).toBeVisible();await page.getByRole("button",{name:"Previous"}).click();await expect(page.getByText(/^Page 1 of/)).toBeVisible();}
 const downloadEvent=page.waitForEvent("download");await page.getByRole("button",{name:"Download CSV"}).click();const download=await downloadEvent,content=await readFile(await download.path()??"","utf8");expect(download.suggestedFilename()).toMatch(/^accounts-receivable(?:-.*)?\.csv$/);expect(content.charCodeAt(0)).toBe(0xfeff);expect(content).toContain('"invoiceNumber","clientName","projectName"');
 const invoiceNumber=await page.locator("button.link-button").first().innerText();await page.locator("button.link-button").first().click();await expect(page.getByRole("heading",{name:"Finance"})).toBeVisible();await expect(page.getByRole("heading",{name:`Invoice detail ${invoiceNumber}`})).toBeVisible();await page.getByRole("button",{name:"Reports"}).click();
 await page.getByLabel("Report selector").selectOption("profitability");await page.getByLabel("Report date range").selectOption("90");await page.getByRole("button",{name:"Sort by margin",exact:true}).click();await expect(page.getByRole("table")).toBeVisible();const marginText=await page.locator("tbody").innerText();expect(marginText).toMatch(/-?\d+\.\d{4}/);const profitabilityProjectId=await page.locator("button.link-button").first().getAttribute("data-entity-id");expect(profitabilityProjectId).toBeTruthy();await page.locator(`button.link-button[data-entity-id="${profitabilityProjectId}"]`).click();await expect(page.getByRole("heading",{name:"Projects"})).toBeVisible();await expect(page.locator(`li[data-entity-id="${profitabilityProjectId}"]`)).toHaveAttribute("aria-current","true");await page.getByRole("button",{name:"Reports"}).click();
 await page.getByLabel("Report selector").selectOption("deadlines");await page.getByLabel("Report date range").selectOption("90");await expect(page.getByRole("table")).toBeVisible();const deadlineLinks=page.locator("tbody tr").first().locator("button.link-button"),taskProject=await deadlineLinks.count()>1?await deadlineLinks.nth(1).getAttribute("data-entity-id"):null;if(taskProject&&await page.getByLabel("Report project filter").locator(`option[value="${taskProject}"]`).count()){await page.getByLabel("Report project filter").selectOption(taskProject);await expect(page.getByRole("table")).toBeVisible();}const taskId=await page.locator("button.link-button").first().getAttribute("data-entity-id");expect(taskId).toBeTruthy();await page.locator(`button.link-button[data-entity-id="${taskId}"]`).click();await expect(page.getByRole("heading",{name:"Tasks"})).toBeVisible();await expect(page.locator(`li[data-entity-id="${taskId}"]`)).toHaveAttribute("aria-current","true");await page.getByRole("button",{name:"Reports"}).click();
 await page.getByLabel("Report selector").selectOption("workload");await page.getByLabel("Report date range").selectOption("90");await expect(page.getByText("Unassigned")).toBeVisible();
 await page.getByLabel("Report selector").selectOption("documents");await page.getByLabel("Report date range").selectOption("90");await expect(page.getByRole("table")).toBeVisible();const documentName=await page.locator("button.link-button").first().innerText();await page.locator("button.link-button").first().click();await expect(page.getByRole("heading",{name:"Documents"})).toBeVisible();await expect(page.getByRole("heading",{name:`Document detail ${documentName}`})).toBeVisible();
 expect(failures).toEqual([]);
});

test("employee sees only underlying authorized document report and cannot export finance",async({page,request})=>{
 await login(page,"employee@demo.odls");await page.getByRole("button",{name:"Reports"}).click();await expect(page.getByLabel("Report selector").locator("option")).toHaveCount(1);await expect(page.getByLabel("Report selector")).toHaveValue("documents");await expect(page.getByRole("button",{name:"Download CSV"})).toHaveCount(0);
 const loginResponse=await request.post("http://127.0.0.1:3100/api/v1/auth/login",{data:{tenantSlug:"demo",email:"employee@demo.odls",password:"DemoPassword!2026"}}),token=(await loginResponse.json()).data.accessToken;expect((await request.get("http://127.0.0.1:3100/api/v1/reports/accounts-receivable/export",{headers:{authorization:`Bearer ${token}`}})).status()).toBe(403);
});
