import {expect,test} from "@playwright/test";
import {readFile} from "node:fs/promises";

async function login(page:any,email="admin@demo.odls"){
 await page.goto("/");await page.getByLabel("Tenant").fill("demo");await page.getByLabel("Email").fill(email);await page.getByLabel("Password").fill("DemoPassword!2026");await page.getByRole("button",{name:"Sign in"}).click();
}
test("dashboard charts and interactive report controls use live backend data",async({page})=>{
 const failures:string[]=[];page.on("console",message=>{if(message.type()==="error")failures.push(message.text());});page.on("response",response=>{if(response.status()>=500)failures.push(`${response.status()} ${response.url()}`);});
 await login(page);await expect(page.getByRole("heading",{name:"Executive Dashboard"})).toBeVisible();
 await page.getByLabel("Dashboard date range").selectOption("90");await expect(page.getByText(/UTC reporting period/)).toBeVisible();await expect(page.getByRole("heading",{name:"Project health"})).toBeVisible();for(const chart of ["Task status distribution","Project health distribution","Revenue by month and currency","Expenses by month and currency"])await expect(page.getByRole("figure",{name:chart})).toBeVisible();
 await page.getByRole("button",{name:"Reports"}).click();await expect(page.getByRole("heading",{name:"Operational Reports"})).toBeVisible();
 await page.getByLabel("Report date range").selectOption("90");await page.getByLabel("Rows per page").selectOption("5");await page.getByText("Overdue only").click();await expect(page.getByRole("table")).toBeVisible();
 const firstLinks=page.locator("tbody tr").first().locator("button.link-button"),client=await firstLinks.nth(1).getAttribute("data-entity-id"),project=await firstLinks.nth(2).getAttribute("data-entity-id"),currency=await page.getByLabel("Report currency filter").locator("option").nth(1).getAttribute("value");if(client)await page.getByLabel("Report client filter").selectOption(client);if(project)await page.getByLabel("Report project filter").selectOption(project);if(currency)await page.getByLabel("Report currency filter").selectOption(currency);await expect(page.getByText(/^Page 1 of/)).toBeVisible();
 await page.getByRole("button",{name:"Sort by outstanding"}).click();await expect(page.getByRole("button",{name:"Sort by outstanding"})).toContainText("↑");await page.getByRole("button",{name:"Sort by outstanding"}).click();await expect(page.getByRole("button",{name:"Sort by outstanding"})).toContainText("↓");
 await page.getByRole("button",{name:"Clear filters"}).click();if(await page.getByRole("button",{name:"Next"}).isEnabled()){await page.getByRole("button",{name:"Next"}).click();await expect(page.getByText(/^Page 2 of/)).toBeVisible();await page.getByRole("button",{name:"Previous"}).click();await expect(page.getByText(/^Page 1 of/)).toBeVisible();}
 const downloadEvent=page.waitForEvent("download");await page.getByRole("button",{name:"Download CSV"}).click();const download=await downloadEvent,content=await readFile(await download.path()??"","utf8");expect(download.suggestedFilename()).toMatch(/^accounts-receivable(?:-.*)?\.csv$/);expect(content.charCodeAt(0)).toBe(0xfeff);expect(content).toContain('"invoiceNumber","clientName","projectName"');
 const invoiceNumber=await page.locator("button.link-button").first().innerText();await page.locator("button.link-button").first().click();await expect(page.getByRole("heading",{name:"Finance"})).toBeVisible();await expect(page.getByRole("heading",{name:`Invoice detail ${invoiceNumber}`})).toBeVisible();await page.getByRole("button",{name:"Reports"}).click();
 await page.getByLabel("Report selector").selectOption("profitability");await page.getByLabel("Report date range").selectOption("90");await page.getByRole("button",{name:"Sort by margin",exact:true}).click();await expect(page.getByRole("table")).toBeVisible();const marginText=await page.locator("tbody").innerText();expect(marginText).toMatch(/-?\d+\.\d{4}/);const profitabilityProjectId=await page.locator("button.link-button").first().getAttribute("data-entity-id");await page.locator("button.link-button").first().click();await expect(page.getByRole("heading",{name:"Projects"})).toBeVisible();await expect(page.locator(`li[data-entity-id="${profitabilityProjectId}"]`)).toHaveAttribute("aria-current","true");await page.getByRole("button",{name:"Reports"}).click();
 await page.getByLabel("Report selector").selectOption("deadlines");await page.getByLabel("Report date range").selectOption("90");await expect(page.getByRole("table")).toBeVisible();const deadlineLinks=page.locator("tbody tr").first().locator("button.link-button"),taskProject=await deadlineLinks.count()>1?await deadlineLinks.nth(1).getAttribute("data-entity-id"):null;if(taskProject&&await page.getByLabel("Report project filter").locator(`option[value="${taskProject}"]`).count()){await page.getByLabel("Report project filter").selectOption(taskProject);await expect(page.getByRole("table")).toBeVisible();}const taskId=await page.locator("button.link-button").first().getAttribute("data-entity-id");await page.locator("button.link-button").first().click();await expect(page.getByRole("heading",{name:"Tasks"})).toBeVisible();await expect(page.locator(`li[data-entity-id="${taskId}"]`)).toHaveAttribute("aria-current","true");await page.getByRole("button",{name:"Reports"}).click();
 await page.getByLabel("Report selector").selectOption("workload");await page.getByLabel("Report date range").selectOption("90");await expect(page.getByText("Unassigned")).toBeVisible();
 await page.getByLabel("Report selector").selectOption("documents");await page.getByLabel("Report date range").selectOption("90");await expect(page.getByRole("table")).toBeVisible();const documentName=await page.locator("button.link-button").first().innerText();await page.locator("button.link-button").first().click();await expect(page.getByRole("heading",{name:"Documents"})).toBeVisible();await expect(page.getByRole("heading",{name:`Document detail ${documentName}`})).toBeVisible();
 expect(failures).toEqual([]);
});

test("employee sees only underlying authorized document report and cannot export finance",async({page,request})=>{
 await login(page,"employee@demo.odls");await page.getByRole("button",{name:"Reports"}).click();await expect(page.getByLabel("Report selector").locator("option")).toHaveCount(1);await expect(page.getByLabel("Report selector")).toHaveValue("documents");await expect(page.getByRole("button",{name:"Download CSV"})).toHaveCount(0);
 const loginResponse=await request.post("http://127.0.0.1:3100/api/v1/auth/login",{data:{tenantSlug:"demo",email:"employee@demo.odls",password:"DemoPassword!2026"}}),token=(await loginResponse.json()).data.accessToken;expect((await request.get("http://127.0.0.1:3100/api/v1/reports/accounts-receivable/export",{headers:{authorization:`Bearer ${token}`}})).status()).toBe(403);
});
