import type {Pool,PoolClient} from "pg";
import type {LaborRateAuditEvent,LaborRateCatalogRepository as LaborRateCatalogRepositoryPort,LaborRateOverlapCandidate} from "../../application/labor-rate-catalog/labor-rate-catalog-repository.js";
import {DomainError} from "../../domain/errors.js";
import type {CreateLaborRate,LaborRate,LaborRateQuery,LaborRateResolutionParams,LaborRateSourceType,UpdateLaborRate} from "../../domain/labor-rate-catalog/labor-rate-types.js";
import {inTenantTransaction} from "../transaction.js";

type LaborRateRow={id:string;tenantId:string;workId:string;workCode?:string;countryCode:string;region:string|null;currency:string;unitId:string;unitCode?:string;rateAmount:string;effectiveFrom:string;effectiveTo:string|null;sourceType:LaborRateSourceType;isActive:boolean;notes:string|null;version:number;createdAt:string;createdBy:string;updatedAt:string;updatedBy:string};
const tenantColumns=`id,tenant_id "tenantId",work_id "workId",country_code "countryCode",region,currency,unit_id "unitId",rate_amount::text "rateAmount",effective_from::text "effectiveFrom",effective_to::text "effectiveTo",source_type "sourceType",is_active "isActive",notes,version::int,created_at "createdAt",created_by "createdBy",updated_at "updatedAt",updated_by "updatedBy"`;
const systemColumns=(tenant="$1",work="w.id",unit="u.id")=>`d.id,${tenant}::uuid "tenantId",${work} "workId",d.country_code "countryCode",d.region,d.currency,${unit} "unitId",d.rate_amount::text "rateAmount",d.effective_from::text "effectiveFrom",d.effective_to::text "effectiveTo",d.source_type "sourceType",d.is_active "isActive",d.notes,d.version::int,d.created_at "createdAt",d.created_by "createdBy",d.updated_at "updatedAt",d.updated_by "updatedBy"`;
const map=(row:LaborRateRow|undefined):LaborRate|undefined=>row&&({...row,createdAt:new Date(row.createdAt).toISOString(),updatedAt:new Date(row.updatedAt).toISOString()});
const databaseError=(error:any):never=>{if(error?.code==="23P01"&&["labor_rates_active_period_exclusion","labor_rate_system_defaults_active_period_exclusion"].includes(error?.constraint))throw new DomainError("DUPLICATE_RECORD",409,"Active labor rate periods overlap",{kind:"ACTIVE_PERIOD_OVERLAP"});throw error;};

export class LaborRateCatalogRepository implements LaborRateCatalogRepositoryPort{
 constructor(private pool:Pool,private client?:PoolClient){}
 private db(){if(!this.client)throw new Error("LaborRateCatalogRepository method requires transaction context");return this.client;}
 transaction<T>(tenantId:string,operation:(repository:LaborRateCatalogRepositoryPort)=>Promise<T>,systemContext=false):Promise<T>{if(this.client)return operation(this);return inTenantTransaction(this.pool,tenantId,async client=>{if(systemContext)await client.query("SELECT set_config('app.system_context','true',true)");return operation(new LaborRateCatalogRepository(this.pool,client));});}
 async findById(tenantId:string,id:string){const tenant=(await this.db().query<LaborRateRow>(`SELECT ${tenantColumns} FROM labor_rates WHERE tenant_id=$1 AND id=$2`,[tenantId,id])).rows[0];if(tenant)return map(tenant);return map((await this.db().query<LaborRateRow>(`SELECT ${systemColumns()} FROM labor_rate_system_defaults d JOIN work_items w ON w.tenant_id=$1 AND w.code=d.work_code AND w.status='active' JOIN measurement_units u ON u.tenant_id=$1 AND u.code=d.unit_code AND u.status='active' WHERE d.id=$2`,[tenantId,id])).rows[0]);}
 async findOverlapping(tenantId:string,candidate:LaborRateOverlapCandidate,excludeId?:string){if(candidate.sourceType==="system_default"){const result=await this.db().query<LaborRateRow>(`SELECT ${systemColumns()} FROM labor_rate_system_defaults d JOIN work_items w ON w.tenant_id=$1 AND w.id=$2 AND w.code=d.work_code JOIN measurement_units u ON u.tenant_id=$1 AND u.id=$6 AND u.code=d.unit_code WHERE d.country_code=$3 AND COALESCE(d.region,'')=COALESCE($4,'') AND d.currency=$5 AND d.is_active=true AND daterange(d.effective_from,COALESCE(d.effective_to,'infinity'::date),'[]')&&daterange($7::date,COALESCE($8::date,'infinity'::date),'[]') AND($9::uuid IS NULL OR d.id<>$9) ORDER BY d.effective_from,d.id`,[tenantId,candidate.workId,candidate.countryCode,candidate.region,candidate.currency,candidate.unitId,candidate.effectiveFrom,candidate.effectiveTo??null,excludeId??null]);return result.rows.map(row=>map(row)!);}
  const result=await this.db().query<LaborRateRow>(`SELECT ${tenantColumns} FROM labor_rates WHERE tenant_id=$1 AND work_id=$2 AND country_code=$3 AND COALESCE(region,'')=COALESCE($4,'') AND currency=$5 AND unit_id=$6 AND is_active=true AND daterange(effective_from,COALESCE(effective_to,'infinity'::date),'[]')&&daterange($7::date,COALESCE($8::date,'infinity'::date),'[]') AND($9::uuid IS NULL OR id<>$9) ORDER BY effective_from,id`,[tenantId,candidate.workId,candidate.countryCode,candidate.region,candidate.currency,candidate.unitId,candidate.effectiveFrom,candidate.effectiveTo??null,excludeId??null]);return result.rows.map(row=>map(row)!);}
 async findResolutionCandidates(params:LaborRateResolutionParams){const result=await this.db().query<LaborRateRow>(`SELECT ${tenantColumns} FROM labor_rates WHERE tenant_id=$1 AND work_id=$2 AND country_code=$3 AND currency=$4 AND unit_id=$5 AND is_active=true AND effective_from<=$6::date AND(effective_to IS NULL OR effective_to>=$6::date) AND COALESCE(region,'') IN(COALESCE($7,''),'') UNION ALL SELECT ${systemColumns("$1","$2::uuid","$5::uuid")} FROM labor_rate_system_defaults d JOIN work_items w ON w.tenant_id=$1 AND w.id=$2 AND w.code=d.work_code AND w.status='active' JOIN measurement_units u ON u.tenant_id=$1 AND u.id=$5 AND u.code=d.unit_code AND u.status='active' WHERE d.country_code=$3 AND d.currency=$4 AND d.is_active=true AND d.effective_from<=$6::date AND(d.effective_to IS NULL OR d.effective_to>=$6::date) AND COALESCE(d.region,'') IN(COALESCE($7,''),'')`,[params.tenantId,params.workId,params.countryCode,params.currency,params.unitId,params.onDate,params.region??null]);return result.rows.map(row=>map(row)!);}
 async list(tenantId:string,query:LaborRateQuery,systemOnly=false){const values:any[]=[tenantId],filters:string[]=[];for(const[key,column]of [["workId",'"workId"'],["countryCode",'"countryCode"'],["currency","currency"],["unitId",'"unitId"'],["sourceType",'"sourceType"'],["isActive",'"isActive"']] as const)if(query[key]!==undefined){values.push(query[key]);filters.push(`${column}=$${values.length}`);}if(query.region!==undefined){values.push(query.region);filters.push(`COALESCE(region,'')=COALESCE($${values.length},'')`);}if(query.effectiveOn){values.push(query.effectiveOn);filters.push(`"effectiveFrom"::date<=$${values.length}::date AND("effectiveTo" IS NULL OR "effectiveTo"::date>=$${values.length}::date)`);}if(systemOnly)filters.push(`"sourceType"='system_default'`);const tenantSelect=`SELECT r.id,r.tenant_id "tenantId",r.work_id "workId",w.code "workCode",r.country_code "countryCode",r.region,r.currency,r.unit_id "unitId",u.code "unitCode",r.rate_amount::text "rateAmount",r.effective_from::text "effectiveFrom",r.effective_to::text "effectiveTo",r.source_type "sourceType",r.is_active "isActive",r.notes,r.version::int,r.created_at "createdAt",r.created_by "createdBy",r.updated_at "updatedAt",r.updated_by "updatedBy" FROM labor_rates r JOIN work_items w ON w.tenant_id=r.tenant_id AND w.id=r.work_id JOIN measurement_units u ON u.tenant_id=r.tenant_id AND u.id=r.unit_id WHERE r.tenant_id=$1`,globalSelect=`SELECT d.id,$1::uuid "tenantId",w.id "workId",w.code "workCode",d.country_code "countryCode",d.region,d.currency,u.id "unitId",u.code "unitCode",d.rate_amount::text "rateAmount",d.effective_from::text "effectiveFrom",d.effective_to::text "effectiveTo",d.source_type "sourceType",d.is_active "isActive",d.notes,d.version::int,d.created_at "createdAt",d.created_by "createdBy",d.updated_at "updatedAt",d.updated_by "updatedBy" FROM labor_rate_system_defaults d JOIN work_items w ON w.tenant_id=$1 AND w.code=d.work_code AND w.status='active' JOIN measurement_units u ON u.tenant_id=$1 AND u.code=d.unit_code AND u.status='active'`;const source=systemOnly?globalSelect:`${tenantSelect} UNION ALL ${globalSelect}`,where=filters.length?`WHERE ${filters.join(" AND ")}`:"",count=Number((await this.db().query<{count:string}>(`WITH rates AS(${source}) SELECT count(*) FROM rates ${where}`,values)).rows[0].count);values.push(query.pageSize,(query.page-1)*query.pageSize);const sorts={effectiveFrom:'"effectiveFrom"',rateAmount:'"rateAmount"::numeric',countryCode:'"countryCode"',currency:"currency",updatedAt:'"updatedAt"'} as const,direction=query.sortOrder==="asc"?"ASC":"DESC",items=(await this.db().query<LaborRateRow>(`WITH rates AS(${source}) SELECT * FROM rates ${where} ORDER BY ${sorts[query.sortBy]} ${direction},id ${direction} LIMIT $${values.length-1} OFFSET $${values.length}`,values)).rows.map(row=>map(row)!);return {items,pagination:{page:query.page,pageSize:query.pageSize,total:count,totalPages:Math.ceil(count/query.pageSize)}};}
 async isSystemActor(actorId:string){return Boolean((await this.db().query("SELECT 1 FROM labor_rate_system_actors WHERE user_id=$1",[actorId])).rowCount);}
 async resolveCatalogCodes(tenantId:string,workCode:string,unitCode:string){return (await this.db().query<{workId:string;unitId:string}>("SELECT w.id \"workId\",u.id \"unitId\" FROM work_items w JOIN measurement_units u ON u.tenant_id=w.tenant_id WHERE w.tenant_id=$1 AND w.code=$2 AND w.status='active' AND u.code=$3 AND u.status='active'",[tenantId,workCode,unitCode])).rows[0];}
 async create(tenantId:string,actorId:string,id:string,input:CreateLaborRate){try{if(input.sourceType==="system_default")return map((await this.db().query<LaborRateRow>(`WITH inserted AS(INSERT INTO labor_rate_system_defaults(id,work_code,country_code,region,currency,unit_code,rate_amount,effective_from,effective_to,notes,created_by,updated_by) SELECT $1,w.code,$4,$5,$6,u.code,$8,$9,$10,$11,$12,$12 FROM work_items w JOIN measurement_units u ON u.tenant_id=w.tenant_id WHERE w.tenant_id=$2 AND w.id=$3 AND u.id=$7 RETURNING *) SELECT ${systemColumns("$2","$3::uuid","$7::uuid")} FROM inserted d`,[id,tenantId,input.workId,input.countryCode,input.region??null,input.currency,input.unitId,input.rateAmount,input.effectiveFrom,input.effectiveTo??null,input.notes??null,actorId])).rows[0])!;
   return map((await this.db().query<LaborRateRow>(`INSERT INTO labor_rates(id,tenant_id,work_id,country_code,region,currency,unit_id,rate_amount,effective_from,effective_to,notes,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$12) RETURNING ${tenantColumns}`,[id,tenantId,input.workId,input.countryCode,input.region??null,input.currency,input.unitId,input.rateAmount,input.effectiveFrom,input.effectiveTo??null,input.notes??null,actorId])).rows[0])!;}catch(error){return databaseError(error);}}
 async update(tenantId:string,actorId:string,id:string,input:UpdateLaborRate){try{if(input.sourceType==="system_default"){const values:unknown[]=[tenantId],sets:string[]=[];for(const[key,column]of [["countryCode","country_code"],["region","region"],["currency","currency"],["rateAmount","rate_amount"],["effectiveFrom","effective_from"],["effectiveTo","effective_to"],["notes","notes"]] as const)if(input[key]!==undefined){values.push(input[key]);sets.push(`${column}=$${values.length}`);}if(input.workId!==undefined){values.push(input.workId);sets.push(`work_code=(SELECT code FROM work_items WHERE tenant_id=$1 AND id=$${values.length})`);}if(input.unitId!==undefined){values.push(input.unitId);sets.push(`unit_code=(SELECT code FROM measurement_units WHERE tenant_id=$1 AND id=$${values.length})`);}values.push(actorId,id,input.expectedVersion);return map((await this.db().query<LaborRateRow>(`UPDATE labor_rate_system_defaults d SET ${sets.length?`${sets.join(",")},`:""}updated_by=$${values.length-2},updated_at=now(),version=d.version+1 WHERE d.id=$${values.length-1} AND d.version=$${values.length} RETURNING ${systemColumns("$1","(SELECT id FROM work_items WHERE tenant_id=$1 AND code=d.work_code LIMIT 1)","(SELECT id FROM measurement_units WHERE tenant_id=$1 AND code=d.unit_code LIMIT 1)")}`,values)).rows[0]);}
   const fields=[["workId","work_id"],["countryCode","country_code"],["region","region"],["currency","currency"],["unitId","unit_id"],["rateAmount","rate_amount"],["effectiveFrom","effective_from"],["effectiveTo","effective_to"],["notes","notes"]] as const,sets:string[]=[],values:unknown[]=[];for(const[key,column]of fields)if(input[key]!==undefined){values.push(input[key]);sets.push(`${column}=$${values.length}`);}values.push(actorId,tenantId,id,input.expectedVersion);return map((await this.db().query<LaborRateRow>(`UPDATE labor_rates SET ${sets.length?`${sets.join(",")},`:""}updated_by=$${values.length-3},updated_at=now(),version=version+1 WHERE tenant_id=$${values.length-2} AND id=$${values.length-1} AND version=$${values.length} RETURNING ${tenantColumns}`,values)).rows[0]);}catch(error){return databaseError(error);}}
 async setActive(tenantId:string,actorId:string,id:string,isActive:boolean,expectedVersion:number,sourceType:LaborRateSourceType="tenant"){try{if(sourceType==="system_default")return map((await this.db().query<LaborRateRow>(`UPDATE labor_rate_system_defaults d SET is_active=$1,updated_by=$2,updated_at=now(),version=d.version+1 WHERE d.id=$3 AND d.version=$4 RETURNING ${systemColumns("$5","(SELECT id FROM work_items WHERE tenant_id=$5 AND code=d.work_code LIMIT 1)","(SELECT id FROM measurement_units WHERE tenant_id=$5 AND code=d.unit_code LIMIT 1)")}`,[isActive,actorId,id,expectedVersion,tenantId])).rows[0]);
   return map((await this.db().query<LaborRateRow>(`UPDATE labor_rates SET is_active=$1,updated_by=$2,updated_at=now(),version=version+1 WHERE tenant_id=$3 AND id=$4 AND version=$5 RETURNING ${tenantColumns}`,[isActive,actorId,tenantId,id,expectedVersion])).rows[0]);}catch(error){return databaseError(error);}}
 async audit(event:LaborRateAuditEvent){await this.db().query("INSERT INTO audit_logs(tenant_id,actor_id,action,entity_type,entity_id,correlation_id,metadata) VALUES($1,$2,$3,$4,$5,$6,$7)",[event.tenantId,event.actorId,event.action,event.entityType,event.entityId,event.correlationId,event.metadata]);}
}
