import type {PoolClient} from "pg";
import type {CreateMaterial,CreateMaterialCategory,Material,MaterialCategory,MaterialCategoryListQuery,MaterialListQuery,MaterialPageResult,MoveMaterialCategory,UpdateMaterial,UpdateMaterialCategory} from "../../domain/material-catalog/material-catalog-types.js";
const categorySelect=`id,tenant_id "tenantId",code,display_name "displayName",description,parent_id "parentId",hierarchy_level::int "hierarchyLevel",sort_order::int "sortOrder",status,is_system "isSystem",created_by "createdBy",updated_by "updatedBy",created_at "createdAt",updated_at "updatedAt",version::int`;
const materialSelect=`m.id,m.tenant_id "tenantId",m.code,m.display_name "displayName",m.short_description "shortDescription",m.detailed_description "detailedDescription",m.category_id "categoryId",c.display_name "categoryName",m.measurement_unit_id "measurementUnitId",u.code "measurementUnitCode",u.dimension "measurementDimension",m.manufacturer_name "manufacturerName",m.brand_name "brandName",m.technical_data "technicalData",m.ai_metadata "aiMetadata",m.status,m.is_system "isSystem",m.created_by "createdBy",m.updated_by "updatedBy",m.created_at "createdAt",m.updated_at "updatedAt",m.version::int`;
const categorySort={code:"code",displayName:"display_name",sortOrder:"sort_order",status:"status",createdAt:"created_at",updatedAt:"updated_at"} as const;
const materialSort={code:"m.code",displayName:"m.display_name",category:"c.display_name",measurementUnit:"u.code",manufacturer:"m.manufacturer_name",brand:"m.brand_name",status:"m.status",createdAt:"m.created_at",updatedAt:"m.updated_at"} as const;
export class MaterialCatalogRepository{
 findCategory(db:PoolClient,t:string,id:string){return db.query<MaterialCategory>(`SELECT ${categorySelect} FROM material_categories WHERE tenant_id=$1 AND id=$2`,[t,id]).then(r=>r.rows[0]);}
 findMaterial(db:PoolClient,t:string,id:string){return db.query<Material>(`SELECT ${materialSelect} FROM materials m JOIN material_categories c ON c.tenant_id=m.tenant_id AND c.id=m.category_id JOIN measurement_units u ON u.tenant_id=m.tenant_id AND u.id=m.measurement_unit_id WHERE m.tenant_id=$1 AND m.id=$2`,[t,id]).then(r=>r.rows[0]);}
 findUnit(db:PoolClient,t:string,id:string){return db.query<{id:string;status:string}>(`SELECT id,status FROM measurement_units WHERE tenant_id=$1 AND id=$2`,[t,id]).then(r=>r.rows[0]);}
 async categoryList(db:PoolClient,t:string,q:MaterialCategoryListQuery):Promise<MaterialPageResult<MaterialCategory>>{const v:any[]=[t],f=["tenant_id=$1"];if(q.search){v.push(`%${q.search}%`);f.push(`(code ILIKE $${v.length} OR display_name ILIKE $${v.length})`);}if(q.active!==undefined){v.push(q.active?"active":"inactive");f.push(`status=$${v.length}`);}if(q.parentId){v.push(q.parentId);f.push(`parent_id=$${v.length}`);}if(q.rootOnly)f.push("parent_id IS NULL");if(q.isSystem!==undefined){v.push(q.isSystem);f.push(`is_system=$${v.length}`);}const where=f.join(" AND "),total=Number((await db.query<{count:string}>(`SELECT count(*) FROM material_categories WHERE ${where}`,v)).rows[0].count);v.push(q.pageSize,(q.page-1)*q.pageSize);const d=q.sortOrder==="asc"?"ASC":"DESC",items=(await db.query<MaterialCategory>(`SELECT ${categorySelect} FROM material_categories WHERE ${where} ORDER BY ${categorySort[q.sortBy]} ${d},id ${d} LIMIT $${v.length-1} OFFSET $${v.length}`,v)).rows;return {items,pagination:{page:q.page,pageSize:q.pageSize,total,totalPages:Math.ceil(total/q.pageSize)}};}
 tree(db:PoolClient,t:string){return db.query<MaterialCategory>(`SELECT ${categorySelect} FROM material_categories WHERE tenant_id=$1 ORDER BY hierarchy_level,sort_order,code,id`,[t]).then(r=>r.rows);}
 createCategory(db:PoolClient,t:string,a:string,id:string,x:CreateMaterialCategory,level:number){return db.query<MaterialCategory>(`INSERT INTO material_categories(id,tenant_id,code,display_name,description,parent_id,hierarchy_level,sort_order,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$9) RETURNING ${categorySelect}`,[id,t,x.code,x.displayName,x.description??null,x.parentId??null,level,x.sortOrder,a]).then(r=>r.rows[0]);}
 updateCategory(db:PoolClient,t:string,a:string,id:string,x:UpdateMaterialCategory){const m=[["displayName","display_name"],["description","description"],["sortOrder","sort_order"]] as const,s:string[]=[],v:any[]=[];for(const[k,c]of m)if(x[k]!==undefined){v.push(x[k]);s.push(`${c}=$${v.length}`);}if(!s.length)return this.findCategory(db,t,id);v.push(a,id,t,x.expectedVersion);return db.query<MaterialCategory>(`UPDATE material_categories SET ${s.join(",")},updated_by=$${v.length-3},updated_at=now(),version=version+1 WHERE id=$${v.length-2} AND tenant_id=$${v.length-1} AND version=$${v.length} RETURNING ${categorySelect}`,v).then(r=>r.rows[0]);}
 descendants(db:PoolClient,t:string,id:string){return db.query<{id:string;depth:number}>(`WITH RECURSIVE d AS (SELECT id,0 depth FROM material_categories WHERE tenant_id=$1 AND id=$2 UNION ALL SELECT c.id,d.depth+1 FROM material_categories c JOIN d ON c.parent_id=d.id WHERE c.tenant_id=$1 AND d.depth<3) SELECT id,depth FROM d`,[t,id]).then(r=>r.rows);}
 moveCategory(db:PoolClient,t:string,a:string,id:string,x:MoveMaterialCategory,newLevel:number,delta:number){return db.query<MaterialCategory>(`WITH RECURSIVE d AS (SELECT id FROM material_categories WHERE tenant_id=$1 AND id=$2 UNION ALL SELECT c.id FROM material_categories c JOIN d ON c.parent_id=d.id WHERE c.tenant_id=$1),changed AS (UPDATE material_categories c SET hierarchy_level=hierarchy_level+$3,updated_by=$4,updated_at=now(),version=CASE WHEN c.id=$2 THEN version+1 ELSE version END,parent_id=CASE WHEN c.id=$2 THEN $5::uuid ELSE parent_id END,sort_order=CASE WHEN c.id=$2 THEN COALESCE($6,sort_order) ELSE sort_order END FROM d WHERE c.tenant_id=$1 AND c.id=d.id AND(c.id<>$2 OR c.version=$7) RETURNING c.*) SELECT ${categorySelect} FROM changed WHERE id=$2`,[t,id,delta,a,x.parentId,x.sortOrder??null,x.expectedVersion]).then(r=>r.rows[0]);}
 blockers(db:PoolClient,t:string,id:string){return db.query<{children:string;materials:string}>(`SELECT (SELECT count(*) FROM material_categories WHERE tenant_id=$1 AND parent_id=$2 AND status='active') children,(SELECT count(*) FROM materials WHERE tenant_id=$1 AND category_id=$2 AND status='active') materials`,[t,id]).then(r=>r.rows[0]);}
 setCategoryStatus(db:PoolClient,t:string,a:string,id:string,status:string,version:number){return db.query<MaterialCategory>(`UPDATE material_categories SET status=$1,updated_by=$2,updated_at=now(),version=version+1 WHERE tenant_id=$3 AND id=$4 AND version=$5 RETURNING ${categorySelect}`,[status,a,t,id,version]).then(r=>r.rows[0]);}
 async materialList(db:PoolClient,t:string,q:MaterialListQuery):Promise<MaterialPageResult<Material>>{const v:any[]=[t],f=["m.tenant_id=$1"];if(q.search){v.push(`%${q.search}%`);f.push(`(m.code ILIKE $${v.length} OR m.display_name ILIKE $${v.length} OR m.short_description ILIKE $${v.length})`);}for(const[k,c]of [["categoryId","m.category_id"],["measurementUnitId","m.measurement_unit_id"]] as const)if(q[k]){v.push(q[k]);f.push(`${c}=$${v.length}`);}for(const[k,c]of [["manufacturerName","m.manufacturer_name"],["brandName","m.brand_name"]] as const)if(q[k]){v.push(`%${q[k]}%`);f.push(`${c} ILIKE $${v.length}`);}if(q.active!==undefined){v.push(q.active?"active":"inactive");f.push(`m.status=$${v.length}`);}if(q.isSystem!==undefined){v.push(q.isSystem);f.push(`m.is_system=$${v.length}`);}const joins="materials m JOIN material_categories c ON c.tenant_id=m.tenant_id AND c.id=m.category_id JOIN measurement_units u ON u.tenant_id=m.tenant_id AND u.id=m.measurement_unit_id",where=f.join(" AND "),total=Number((await db.query<{count:string}>(`SELECT count(*) FROM ${joins} WHERE ${where}`,v)).rows[0].count);v.push(q.pageSize,(q.page-1)*q.pageSize);const d=q.sortOrder==="asc"?"ASC":"DESC",items=(await db.query<Material>(`SELECT ${materialSelect} FROM ${joins} WHERE ${where} ORDER BY ${materialSort[q.sortBy]} ${d} NULLS LAST,m.id ${d} LIMIT $${v.length-1} OFFSET $${v.length}`,v)).rows;return {items,pagination:{page:q.page,pageSize:q.pageSize,total,totalPages:Math.ceil(total/q.pageSize)}};}
 createMaterial(db:PoolClient,t:string,a:string,id:string,x:CreateMaterial){return db.query<Material>(`WITH inserted AS (INSERT INTO materials(id,tenant_id,code,display_name,short_description,detailed_description,category_id,measurement_unit_id,manufacturer_name,brand_name,technical_data,ai_metadata,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$13) RETURNING *) SELECT ${materialSelect} FROM inserted m JOIN material_categories c ON c.tenant_id=m.tenant_id AND c.id=m.category_id JOIN measurement_units u ON u.tenant_id=m.tenant_id AND u.id=m.measurement_unit_id`,[id,t,x.code,x.displayName,x.shortDescription??null,x.detailedDescription??null,x.categoryId,x.measurementUnitId,x.manufacturerName??null,x.brandName??null,x.technicalData??{},x.aiMetadata??{},a]).then(r=>r.rows[0]);}
 updateMaterial(db:PoolClient,t:string,a:string,id:string,x:UpdateMaterial){const m=[["displayName","display_name"],["shortDescription","short_description"],["detailedDescription","detailed_description"],["categoryId","category_id"],["measurementUnitId","measurement_unit_id"],["manufacturerName","manufacturer_name"],["brandName","brand_name"],["technicalData","technical_data"],["aiMetadata","ai_metadata"]] as const,s:string[]=[],v:any[]=[];for(const[k,c]of m)if(x[k]!==undefined){v.push(x[k]);s.push(`${c}=$${v.length}`);}if(!s.length)return this.findMaterial(db,t,id);v.push(a,id,t,x.expectedVersion);return db.query<Material>(`WITH updated AS (UPDATE materials SET ${s.join(",")},updated_by=$${v.length-3},updated_at=now(),version=version+1 WHERE id=$${v.length-2} AND tenant_id=$${v.length-1} AND version=$${v.length} RETURNING *) SELECT ${materialSelect} FROM updated m JOIN material_categories c ON c.tenant_id=m.tenant_id AND c.id=m.category_id JOIN measurement_units u ON u.tenant_id=m.tenant_id AND u.id=m.measurement_unit_id`,v).then(r=>r.rows[0]);}
 setMaterialStatus(db:PoolClient,t:string,a:string,id:string,status:string,version:number){return db.query<Material>(`WITH updated AS (UPDATE materials SET status=$1,updated_by=$2,updated_at=now(),version=version+1 WHERE tenant_id=$3 AND id=$4 AND version=$5 RETURNING *) SELECT ${materialSelect} FROM updated m JOIN material_categories c ON c.tenant_id=m.tenant_id AND c.id=m.category_id JOIN measurement_units u ON u.tenant_id=m.tenant_id AND u.id=m.measurement_unit_id`,[status,a,t,id,version]).then(r=>r.rows[0]);}
}
