import {randomUUID} from "node:crypto";
import type {Pool,PoolClient} from "pg";
import {assertCanCreateWorkCatalog,assertCanReadWorkCatalog,assertCanUpdateWorkCatalog} from "../../authorization/work-catalog-policy.js";
import {DomainError,domainErrors} from "../../domain/errors.js";
import {validateCategoryCreate,validateCategoryUpdate,validateWorkItemCreate,validateWorkItemUpdate} from "../../domain/work-catalog/work-catalog-rules.js";
import type {CategoryListQuery,CreateCategory,CreateWorkItem,MoveCategory,UpdateCategory,UpdateWorkItem,WorkCategoryNode,WorkItemListQuery} from "../../domain/work-catalog/work-catalog-types.js";
import {WorkCatalogRepository} from "../../infrastructure/work-catalog/work-catalog-repository.js";
import {inTenantTransaction} from "../../infrastructure/transaction.js";
export type WorkCatalogActor={id:string;tenantId:string;permissions:readonly string[];correlationId:string};
export class WorkCatalogService{
 constructor(private pool:Pool,private repo=new WorkCatalogRepository()){}
 private audit(db:PoolClient,a:WorkCatalogActor,entity:string,action:string,id:string,metadata:Record<string,unknown>){return db.query("INSERT INTO audit_logs(tenant_id,actor_id,action,entity_type,entity_id,correlation_id,metadata) VALUES($1,$2,$3,$4,$5,$6,$7)",[a.tenantId,a.id,action,entity,id,/^[0-9a-f-]{36}$/i.test(a.correlationId)?a.correlationId:randomUUID(),metadata]);}
 private async references(db:PoolClient,a:WorkCatalogActor,categoryId:string,unitId:string){const category=await this.repo.findCategory(db,a.tenantId,categoryId);if(!category)throw domainErrors.notFound();const unit=await this.repo.findUnit(db,a.tenantId,unitId);if(!unit)throw domainErrors.notFound();if(category.status!=="active")throw new DomainError("INVALID_RELATIONSHIP",422,"Work item category must be active");if(unit.status!=="active")throw new DomainError("INVALID_RELATIONSHIP",422,"Measurement unit must be active");return {category,unit};}
 listCategories(a:WorkCatalogActor,q:CategoryListQuery){assertCanReadWorkCatalog(a);return inTenantTransaction(this.pool,a.tenantId,db=>this.repo.categoryList(db,a.tenantId,q));}
 getCategory(a:WorkCatalogActor,id:string){assertCanReadWorkCatalog(a);return inTenantTransaction(this.pool,a.tenantId,async db=>{const x=await this.repo.findCategory(db,a.tenantId,id);if(!x)throw domainErrors.notFound();return x;});}
 tree(a:WorkCatalogActor){assertCanReadWorkCatalog(a);return inTenantTransaction(this.pool,a.tenantId,async db=>{const rows=await this.repo.tree(db,a.tenantId),nodes=new Map(rows.map(x=>[x.id,{...x,children:[]} as WorkCategoryNode])),roots:WorkCategoryNode[]=[];for(const row of rows){const node=nodes.get(row.id)!;if(row.parentId)nodes.get(row.parentId)?.children.push(node);else roots.push(node);}return roots;});}
 async createCategory(a:WorkCatalogActor,input:CreateCategory){assertCanCreateWorkCatalog(a);const x=validateCategoryCreate(input);try{return await inTenantTransaction(this.pool,a.tenantId,async db=>{let level=0;if(x.parentId){const p=await this.repo.findCategory(db,a.tenantId,x.parentId);if(!p)throw domainErrors.notFound();if(p.status!=="active")throw new DomainError("INVALID_RELATIONSHIP",422,"Parent category must be active");level=p.hierarchyLevel+1;if(level>3)throw domainErrors.validation("Category hierarchy exceeds maximum depth of 4");}const created=await this.repo.createCategory(db,a.tenantId,a.id,randomUUID(),x,level);await this.audit(db,a,"work_category","work_category.created",created.id,{code:created.code,parentId:created.parentId,newVersion:created.version});return created;});}catch(e:any){if(e?.code==="23505")throw domainErrors.duplicate("Category code already exists");throw e;}}
 updateCategory(a:WorkCatalogActor,id:string,input:UpdateCategory){assertCanUpdateWorkCatalog(a);const x=validateCategoryUpdate(input);return inTenantTransaction(this.pool,a.tenantId,async db=>{const current=await this.repo.findCategory(db,a.tenantId,id);if(!current)throw domainErrors.notFound();if(current.version!==x.expectedVersion)throw domainErrors.conflict();const updated=await this.repo.updateCategory(db,a.tenantId,a.id,id,x);if(!updated)throw domainErrors.conflict();await this.audit(db,a,"work_category","work_category.updated",id,{previousVersion:current.version,newVersion:updated.version,changes:x});return updated;});}
 moveCategory(a:WorkCatalogActor,id:string,input:MoveCategory){assertCanUpdateWorkCatalog(a);return inTenantTransaction(this.pool,a.tenantId,async db=>{const current=await this.repo.findCategory(db,a.tenantId,id);if(!current)throw domainErrors.notFound();if(current.version!==input.expectedVersion)throw domainErrors.conflict();if(input.parentId===id)throw new DomainError("INVALID_RELATIONSHIP",422,"Category cannot be its own parent");const descendants=await this.repo.descendants(db,a.tenantId,id);if(input.parentId&&descendants.some(x=>x.id===input.parentId))throw new DomainError("INVALID_RELATIONSHIP",422,"Category move would create a cycle");let level=0;if(input.parentId){const parent=await this.repo.findCategory(db,a.tenantId,input.parentId);if(!parent)throw domainErrors.notFound();if(parent.status!=="active")throw new DomainError("INVALID_RELATIONSHIP",422,"Parent category must be active");level=parent.hierarchyLevel+1;}const subtree=Math.max(...descendants.map(x=>x.depth));if(level+subtree>3)throw domainErrors.validation("Category hierarchy exceeds maximum depth of 4");const moved=await this.repo.moveCategory(db,a.tenantId,a.id,id,input,level,level-current.hierarchyLevel);if(!moved)throw domainErrors.conflict();await this.audit(db,a,"work_category","work_category.moved",id,{previousVersion:current.version,newVersion:moved.version,previousParentId:current.parentId,parentId:moved.parentId});return moved;});}
 categoryStatus(a:WorkCatalogActor,id:string,status:"active"|"inactive",version:number){assertCanUpdateWorkCatalog(a);return inTenantTransaction(this.pool,a.tenantId,async db=>{const current=await this.repo.findCategory(db,a.tenantId,id);if(!current)throw domainErrors.notFound();if(current.version!==version)throw domainErrors.conflict();if(current.status===status)throw domainErrors.transition();if(status==="inactive"){const b=await this.repo.blockers(db,a.tenantId,id);if(Number(b.children)||Number(b.items))throw new DomainError("INVALID_RELATIONSHIP",422,"Deactivate active child categories and work items first");}else if(current.parentId){const parent=await this.repo.findCategory(db,a.tenantId,current.parentId);if(!parent||parent.status!=="active")throw new DomainError("INVALID_RELATIONSHIP",422,"Parent category must be active");}const updated=await this.repo.setCategoryStatus(db,a.tenantId,a.id,id,status,version);if(!updated)throw domainErrors.conflict();await this.audit(db,a,"work_category",`work_category.${status==="active"?"activated":"deactivated"}`,id,{previousVersion:version,newVersion:updated.version});return updated;});}
 listItems(a:WorkCatalogActor,q:WorkItemListQuery){assertCanReadWorkCatalog(a);return inTenantTransaction(this.pool,a.tenantId,db=>this.repo.itemList(db,a.tenantId,q));}
 getItem(a:WorkCatalogActor,id:string){assertCanReadWorkCatalog(a);return inTenantTransaction(this.pool,a.tenantId,async db=>{const x=await this.repo.findItem(db,a.tenantId,id);if(!x)throw domainErrors.notFound();return x;});}
 async createItem(a:WorkCatalogActor,input:CreateWorkItem){assertCanCreateWorkCatalog(a);const x=validateWorkItemCreate(input);try{return await inTenantTransaction(this.pool,a.tenantId,async db=>{await this.references(db,a,x.categoryId,x.measurementUnitId);const created=await this.repo.createItem(db,a.tenantId,a.id,randomUUID(),x);await this.audit(db,a,"work_item","work_item.created",created.id,{code:created.code,categoryId:created.categoryId,measurementUnitId:created.measurementUnitId,newVersion:created.version});return created;});}catch(e:any){if(e?.code==="23505")throw domainErrors.duplicate("Work item code already exists");throw e;}}
 updateItem(a:WorkCatalogActor,id:string,input:UpdateWorkItem){assertCanUpdateWorkCatalog(a);const x=validateWorkItemUpdate(input);return inTenantTransaction(this.pool,a.tenantId,async db=>{const current=await this.repo.findItem(db,a.tenantId,id);if(!current)throw domainErrors.notFound();if(current.version!==x.expectedVersion)throw domainErrors.conflict();if(x.categoryId||x.measurementUnitId)await this.references(db,a,x.categoryId??current.categoryId,x.measurementUnitId??current.measurementUnitId);const updated=await this.repo.updateItem(db,a.tenantId,a.id,id,x);if(!updated)throw domainErrors.conflict();await this.audit(db,a,"work_item","work_item.updated",id,{previousVersion:current.version,newVersion:updated.version,previousCategoryId:current.categoryId,previousMeasurementUnitId:current.measurementUnitId,changes:x});return updated;});}
 itemStatus(a:WorkCatalogActor,id:string,status:"active"|"inactive",version:number){assertCanUpdateWorkCatalog(a);return inTenantTransaction(this.pool,a.tenantId,async db=>{const current=await this.repo.findItem(db,a.tenantId,id);if(!current)throw domainErrors.notFound();if(current.version!==version)throw domainErrors.conflict();if(current.status===status)throw domainErrors.transition();if(status==="active")await this.references(db,a,current.categoryId,current.measurementUnitId);const updated=await this.repo.setItemStatus(db,a.tenantId,a.id,id,status,version);if(!updated)throw domainErrors.conflict();await this.audit(db,a,"work_item",`work_item.${status==="active"?"activated":"deactivated"}`,id,{previousVersion:version,newVersion:updated.version});return updated;});}
}
