import {randomUUID} from "node:crypto";
import type {PoolClient} from "pg";
import {enqueueDomainEvent} from "../notification/outbox.js";
export class OcrRepository{
 async page(db:PoolClient,tenantId:string,documentId:string,pageId:string){return (await db.query<any>(`SELECT p.id,p.document_id "documentId",p.ocr_status "ocrStatus",p.version::int,p.processing_status "processingStatus",p.source_file_object_id "sourceFileObjectId",p.processed_file_object_id "processedFileObjectId",sf.mime_type "sourceMimeType",pf.mime_type "processedMimeType" FROM document_pages p JOIN documents d ON d.tenant_id=p.tenant_id AND d.id=p.document_id JOIN file_objects sf ON sf.tenant_id=p.tenant_id AND sf.id=p.source_file_object_id LEFT JOIN file_objects pf ON pf.tenant_id=p.tenant_id AND pf.id=p.processed_file_object_id WHERE p.tenant_id=$1 AND p.document_id=$2 AND p.id=$3 AND d.deleted_at IS NULL`,[tenantId,documentId,pageId])).rows[0];}
 async file(db:PoolClient,tenantId:string,id:string){return (await db.query<any>(`SELECT id,storage_key "storageKey",mime_type "mimeType",size_bytes::int "sizeBytes" FROM file_objects WHERE tenant_id=$1 AND id=$2 AND status='available'`,[tenantId,id])).rows[0];}
 async job(db:PoolClient,tenantId:string,id:string){const x=(await db.query<any>(`SELECT id,tenant_id "tenantId",document_id "documentId",document_page_id "pageId",requested_languages languages,status,provider,attempts,max_attempts "maxAttempts",requested_at "requestedAt",started_at "startedAt",completed_at "completedAt",failed_at "failedAt",next_attempt_at "nextAttemptAt",error_code "errorCode",error_message_safe "errorMessageSafe",created_by "createdBy",created_at "createdAt",updated_at "updatedAt",version::int FROM ocr_jobs WHERE tenant_id=$1 AND id=$2`,[tenantId,id])).rows[0];return x;}
 async result(db:PoolClient,tenantId:string,pageId:string){const x=(await db.query<any>(`SELECT r.id,r.ocr_job_id "jobId",r.document_id "documentId",r.document_page_id "pageId",j.status,j.requested_languages languages,r.raw_text "rawText",r.normalized_text "normalizedText",r.confidence::float8 confidence,r.detected_language "detectedLanguage",r.word_count "wordCount",r.character_count "characterCount",r.provider,r.provider_version "providerVersion",r.processing_duration_ms "processingDurationMs",r.created_at "createdAt",r.version::int FROM ocr_results r JOIN ocr_jobs j ON j.tenant_id=r.tenant_id AND j.id=r.ocr_job_id WHERE r.tenant_id=$1 AND r.document_page_id=$2 ORDER BY r.created_at DESC LIMIT 1`,[tenantId,pageId])).rows[0];return x;}
 async audit(db:PoolClient,actor:{tenantId:string;id:string;correlationId:string},action:string,documentId:string,metadata:Record<string,unknown>){const correlation=/^[0-9a-f-]{36}$/i.test(actor.correlationId)?actor.correlationId:randomUUID();await db.query(`INSERT INTO audit_logs(tenant_id,actor_id,action,entity_type,entity_id,correlation_id,metadata) VALUES($1,$2,$3,'document',$4,$5,$6)`,[actor.tenantId,actor.id,action,documentId,correlation,metadata]);await enqueueDomainEvent(db,{tenantId:actor.tenantId,actorId:actor.id,action,entityType:"document",entityId:documentId,correlationId:correlation,metadata});}
}
