import type{PoolClient}from"pg";import type{ClientApproval,ClientRequest,CreateClientRequest}from"../../domain/client-workspace/client-workspace-types.js";
const requestSelect=`r.id,r.tenant_id AS "tenantId",r.client_id AS "clientId",r.project_id AS "projectId",r.author_id AS "authorId",r.responsible_user_id AS "responsibleUserId",r.request_type AS "requestType",r.subject,r.description,r.status,r.response,r.version::int,r.created_at AS "createdAt",r.updated_at AS "updatedAt"`;
const approvalSelect=`a.id,a.tenant_id AS "tenantId",a.client_id AS "clientId",a.project_id AS "projectId",a.entity_type AS "entityType",a.entity_id AS "entityId",a.title,a.summary,a.status,a.decision_comment AS "decisionComment",a.version::int,a.created_at AS "createdAt"`;
export class ClientWorkspaceRepository{
 async membership(db:PoolClient,tenantId:string,userId:string,projectId?:string){const values=[tenantId,userId,...projectId?[projectId]:[]];return(await db.query<{clientId:string;projectId:string}>(`SELECT client_id AS "clientId",project_id AS "projectId" FROM client_project_memberships WHERE tenant_id=$1 AND user_id=$2 AND status='active'${projectId?' AND project_id=$3':''} ORDER BY created_at`,values)).rows}
 async overview(db:PoolClient,tenantId:string,userId:string){return(await db.query(`SELECT p.id,p.project_number AS "projectNumber",p.name,p.description,p.status,p.start_date AS "startDate",p.expected_completion_date AS "expectedCompletionDate",p.payment_status AS "paymentStatus",pr.name AS "propertyName",a.line1,a.city,a.postal_code AS "postalCode",u.display_name AS "projectManager",m.can_view_site_contact AS "canViewSiteContact",(SELECT count(*)::int FROM tasks t WHERE t.tenant_id=p.tenant_id AND t.project_id=p.id AND t.deleted_at IS NULL)AS "taskCount",(SELECT count(*)::int FROM tasks t WHERE t.tenant_id=p.tenant_id AND t.project_id=p.id AND t.status='completed'AND t.deleted_at IS NULL)AS "completedTaskCount" FROM client_project_memberships m JOIN projects p ON p.tenant_id=m.tenant_id AND p.id=m.project_id JOIN properties pr ON pr.tenant_id=p.tenant_id AND pr.id=p.property_id JOIN addresses a ON a.tenant_id=pr.tenant_id AND a.id=pr.address_id LEFT JOIN users u ON u.tenant_id=p.tenant_id AND u.id=p.project_manager_id WHERE m.tenant_id=$1 AND m.user_id=$2 AND m.status='active'AND p.deleted_at IS NULL ORDER BY p.updated_at DESC`,[tenantId,userId])).rows}
 async projectData(db:PoolClient,tenantId:string,userId:string,projectId:string){
  const tasks=await db.query(`SELECT id,title,status,priority,due_date AS "dueDate",version::int,updated_at AS "updatedAt" FROM tasks WHERE tenant_id=$1 AND project_id=$2 AND deleted_at IS NULL ORDER BY due_date NULLS LAST,updated_at DESC`,[tenantId,projectId]);
  const documents=await db.query(`SELECT d.id,d.title,d.category,d.description,d.status,d.version::int,cpd.published_at AS "publishedAt" FROM client_project_documents cpd JOIN documents d ON d.tenant_id=cpd.tenant_id AND d.id=cpd.document_id WHERE cpd.tenant_id=$1 AND cpd.project_id=$2 AND d.deleted_at IS NULL ORDER BY cpd.published_at DESC`,[tenantId,projectId]);
  const invoices=await db.query(`SELECT i.id,i.invoice_number AS "invoiceNumber",i.issue_date AS "issueDate",i.due_date AS "dueDate",i.currency_code AS currency,i.gross_amount::text AS amount,i.paid_amount::text AS "paidAmount",i.status,i.version::int FROM invoices i JOIN client_project_memberships m ON m.tenant_id=i.tenant_id AND m.client_id=i.client_id AND m.project_id=i.project_id WHERE i.tenant_id=$1 AND i.project_id=$2 AND m.user_id=$3 AND m.status='active'AND i.deleted_at IS NULL ORDER BY i.issue_date DESC`,[tenantId,projectId,userId]);
  const estimates=await db.query(`SELECT e.id,r.id AS "revisionId",e.code,e.title,r.revision_number AS "revisionNumber",r.status,r.currency,jsonb_build_object('netTotal',r.totals->'netTotal','discountAmount',r.totals->'discountAmount','vatAmount',r.totals->'vatAmount','grossTotal',r.totals->'grossTotal','currency',r.totals->'currency')AS totals,r.version::int,s.id AS "snapshotId",s.content_fingerprint AS "contentFingerprint" FROM commercial_estimates e JOIN commercial_estimate_revisions r ON r.tenant_id=e.tenant_id AND r.estimate_id=e.id AND r.is_current LEFT JOIN approved_commercial_estimate_snapshots s ON s.tenant_id=r.tenant_id AND s.revision_id=r.id WHERE e.tenant_id=$1 AND e.project_id=$2 AND r.mode='approved_client'AND r.status='approved' ORDER BY r.approved_at DESC`,[tenantId,projectId]);
  const requests=await db.query<ClientRequest>(`SELECT ${requestSelect} FROM client_requests r WHERE r.tenant_id=$1 AND r.project_id=$2 AND r.author_id=$3 ORDER BY r.created_at DESC`,[tenantId,projectId,userId]);
  const approvals=await db.query<ClientApproval>(`SELECT ${approvalSelect} FROM client_approval_requests a WHERE a.tenant_id=$1 AND a.project_id=$2 AND a.status IN('pending','clarification_requested') ORDER BY a.created_at DESC`,[tenantId,projectId]);
  return{tasks:tasks.rows,documents:documents.rows,invoices:invoices.rows,estimates:estimates.rows,requests:requests.rows,approvals:approvals.rows};}
 async createRequest(db:PoolClient,tenantId:string,userId:string,clientId:string,responsibleUserId:string|null,id:string,input:CreateClientRequest){return(await db.query<ClientRequest>(`INSERT INTO client_requests(id,tenant_id,client_id,project_id,author_id,responsible_user_id,request_type,subject,description,created_by,updated_by)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$5,$5)RETURNING ${requestSelect.replaceAll('r.','')}`,[id,tenantId,clientId,input.projectId,userId,responsibleUserId,input.requestType,input.subject,input.description])).rows[0]}
 async approval(db:PoolClient,tenantId:string,id:string){return(await db.query<ClientApproval>(`SELECT ${approvalSelect} FROM client_approval_requests a WHERE a.tenant_id=$1 AND a.id=$2`,[tenantId,id])).rows[0]}
 async decide(db:PoolClient,tenantId:string,userId:string,id:string,version:number,status:string,comment:string|null){return(await db.query<ClientApproval>(`UPDATE client_approval_requests a SET status=$1,decision_comment=$2,decided_at=now(),decided_by=$3,updated_by=$3,updated_at=now(),version=version+1 WHERE tenant_id=$4 AND id=$5 AND version=$6 AND status IN('pending','clarification_requested') RETURNING ${approvalSelect}`,[status,comment,userId,tenantId,id,version])).rows[0]}
}
