import {randomUUID} from "node:crypto";
import type {Pool,PoolClient} from "pg";
import {assertCanCreateEstimate,assertCanReadEstimate,assertCanUpdateEstimate} from "../../authorization/estimate-policy.js";
import {DomainError,domainErrors} from "../../domain/errors.js";
import {validateEstimateCreate,validateEstimateItemCreate,validateEstimateItemUpdate,validateEstimateMaterialUpdate,validateEstimateUpdate} from "../../domain/estimate-engine/estimate-engine-rules.js";
import type {CreateEstimate,CreateEstimateItem,EstimateChildQuery,EstimateQuery,EstimateStatus,UpdateEstimate,UpdateEstimateItem,UpdateEstimateMaterial} from "../../domain/estimate-engine/estimate-engine-types.js";
import {EstimateEngineRepository} from "../../infrastructure/estimate-engine/estimate-engine-repository.js";
import {inTenantTransaction} from "../../infrastructure/transaction.js";
import {EstimateCalculationService} from "./estimate-calculation-service.js";
export type EstimateActor={id:string;tenantId:string;permissions:readonly string[];correlationId:string};
export class EstimateEngineService{
 constructor(private pool:Pool,private repo=new EstimateEngineRepository(),private calculator=new EstimateCalculationService()){}
 private audit(db:PoolClient,a:EstimateActor,entity:string,action:string,id:string,metadata:Record<string,unknown>){return db.query("INSERT INTO audit_logs(tenant_id,actor_id,action,entity_type,entity_id,correlation_id,metadata) VALUES($1,$2,$3,$4,$5,$6,$7)",[a.tenantId,a.id,action,entity,id,/^[0-9a-f-]{36}$/i.test(a.correlationId)?a.correlationId:randomUUID(),metadata]);}
 private draft(x:{status:string}){if(x.status!=="draft")throw new DomainError("INVALID_STATUS_TRANSITION",422,"Only draft estimates can be changed");}
 private async calculateItem(db:PoolClient,a:EstimateActor,itemId:string,priceListId:string){const item=await this.repo.findItem(db,a.tenantId,itemId),estimate=item&&await this.repo.findEstimate(db,a.tenantId,item.estimateId);if(!item||!estimate)throw domainErrors.notFound();this.draft(estimate);const [consumption,normItemCount]=await Promise.all([this.repo.consumption(db,a.tenantId,item.normId,priceListId,estimate.currency),this.repo.normItemCount(db,a.tenantId,item.normId)]);if(!normItemCount||consumption.length!==normItemCount)throw new DomainError("INVALID_RELATIONSHIP",422,"A current price is required for every active norm material in the selected price list");const rows=this.calculator.calculate(item.quantity,consumption);await this.repo.replaceMaterials(db,a.tenantId,a.id,item.id,rows);return this.repo.refreshTotals(db,a.tenantId,a.id,estimate.id);}
 estimates(a:EstimateActor,q:EstimateQuery){assertCanReadEstimate(a);return inTenantTransaction(this.pool,a.tenantId,db=>this.repo.estimates(db,a.tenantId,q));}
 getEstimate(a:EstimateActor,id:string){assertCanReadEstimate(a);return inTenantTransaction(this.pool,a.tenantId,async db=>{const x=await this.repo.findEstimate(db,a.tenantId,id);if(!x)throw domainErrors.notFound();return x;});}
 async createEstimate(a:EstimateActor,input:CreateEstimate){assertCanCreateEstimate(a);const x=validateEstimateCreate(input);try{return await inTenantTransaction(this.pool,a.tenantId,async db=>{const p=await this.repo.findProject(db,a.tenantId,x.projectId);if(!p)throw domainErrors.notFound();const created=await this.repo.createEstimate(db,a.tenantId,a.id,randomUUID(),x);await this.audit(db,a,"estimate","estimate.created",created.id,{code:created.code,projectId:created.projectId,newVersion:created.version});return created;});}catch(e:any){if(e?.code==="23505")throw domainErrors.duplicate("Estimate code already exists");throw e;}}
 updateEstimate(a:EstimateActor,id:string,input:UpdateEstimate){assertCanUpdateEstimate(a);const x=validateEstimateUpdate(input);return inTenantTransaction(this.pool,a.tenantId,async db=>{const current=await this.repo.findEstimate(db,a.tenantId,id);if(!current)throw domainErrors.notFound();this.draft(current);if(current.version!==x.expectedVersion)throw domainErrors.conflict();const updated=await this.repo.updateEstimate(db,a.tenantId,a.id,id,x);if(!updated)throw domainErrors.conflict();await this.audit(db,a,"estimate","estimate.updated",id,{previousVersion:current.version,newVersion:updated.version});return updated;});}
 status(a:EstimateActor,id:string,status:EstimateStatus,version:number){assertCanUpdateEstimate(a);return inTenantTransaction(this.pool,a.tenantId,async db=>{const current=await this.repo.findEstimate(db,a.tenantId,id);if(!current)throw domainErrors.notFound();if(current.version!==version)throw domainErrors.conflict();const allowed:Record<EstimateStatus,EstimateStatus[]>={draft:["approved","archived"],approved:["archived"],archived:[]};if(!allowed[current.status].includes(status))throw domainErrors.transition();const updated=await this.repo.setStatus(db,a.tenantId,a.id,id,status,version);if(!updated)throw domainErrors.conflict();await this.audit(db,a,"estimate",`estimate.${status}`,id,{previousVersion:version,newVersion:updated.version});return updated;});}
 items(a:EstimateActor,q:EstimateChildQuery){assertCanReadEstimate(a);return inTenantTransaction(this.pool,a.tenantId,db=>this.repo.items(db,a.tenantId,q));}
 getItem(a:EstimateActor,id:string){assertCanReadEstimate(a);return inTenantTransaction(this.pool,a.tenantId,async db=>{const x=await this.repo.findItem(db,a.tenantId,id);if(!x)throw domainErrors.notFound();return x;});}
 createItem(a:EstimateActor,input:CreateEstimateItem){assertCanCreateEstimate(a);const x=validateEstimateItemCreate(input);return inTenantTransaction(this.pool,a.tenantId,async db=>{const estimate=await this.repo.findEstimate(db,a.tenantId,x.estimateId),work=await this.repo.findWork(db,a.tenantId,x.workId);if(!estimate||!work)throw domainErrors.notFound();this.draft(estimate);if(work.status!=="active"||work.measurementUnitId!==x.measurementUnitId)throw new DomainError("INVALID_RELATIONSHIP",422,"Work and its measurement unit must be active and compatible");const norm=await this.repo.findNormForWork(db,a.tenantId,x.workId);if(!norm)throw new DomainError("INVALID_RELATIONSHIP",422,"Active construction norm is required for the selected work");try{const created=await this.repo.createItem(db,a.tenantId,a.id,randomUUID(),x,norm.id);await this.calculateItem(db,a,created.id,x.priceListId);const item=await this.repo.findItem(db,a.tenantId,created.id);await this.audit(db,a,"estimate_item","estimate_item.created",created.id,{estimateId:x.estimateId,workId:x.workId,normId:norm.id,newVersion:item.version});return item;}catch(e:any){if(e?.code==="23505")throw domainErrors.duplicate("Work and norm already exist in this estimate");throw e;}});}
 updateItem(a:EstimateActor,id:string,input:UpdateEstimateItem){assertCanUpdateEstimate(a);const x=validateEstimateItemUpdate(input);return inTenantTransaction(this.pool,a.tenantId,async db=>{const current=await this.repo.findItem(db,a.tenantId,id),estimate=current&&await this.repo.findEstimate(db,a.tenantId,current.estimateId);if(!current||!estimate)throw domainErrors.notFound();this.draft(estimate);if(current.version!==x.expectedVersion)throw domainErrors.conflict();const updated=await this.repo.updateItem(db,a.tenantId,a.id,id,x);if(!updated)throw domainErrors.conflict();await this.calculateItem(db,a,id,x.priceListId);const result=await this.repo.findItem(db,a.tenantId,id);await this.audit(db,a,"estimate_item","estimate_item.updated",id,{previousVersion:current.version,newVersion:result.version});return result;});}
 deleteItem(a:EstimateActor,id:string,version:number){assertCanUpdateEstimate(a);return inTenantTransaction(this.pool,a.tenantId,async db=>{const current=await this.repo.findItem(db,a.tenantId,id),estimate=current&&await this.repo.findEstimate(db,a.tenantId,current.estimateId);if(!current||!estimate)throw domainErrors.notFound();this.draft(estimate);if(current.version!==version)throw domainErrors.conflict();if(!await this.repo.deleteItem(db,a.tenantId,id,version))throw domainErrors.conflict();await this.repo.refreshTotals(db,a.tenantId,a.id,estimate.id);await this.audit(db,a,"estimate_item","estimate_item.deleted",id,{previousVersion:version});return {id};});}
 materials(a:EstimateActor,q:EstimateChildQuery){assertCanReadEstimate(a);return inTenantTransaction(this.pool,a.tenantId,db=>this.repo.materials(db,a.tenantId,q));}
 getMaterial(a:EstimateActor,id:string){assertCanReadEstimate(a);return inTenantTransaction(this.pool,a.tenantId,async db=>{const x=await this.repo.findMaterial(db,a.tenantId,id);if(!x)throw domainErrors.notFound();return x;});}
 updateMaterial(a:EstimateActor,id:string,input:UpdateEstimateMaterial){assertCanUpdateEstimate(a);const x=validateEstimateMaterialUpdate(input);return inTenantTransaction(this.pool,a.tenantId,async db=>{const current=await this.repo.findMaterial(db,a.tenantId,id),item=current&&await this.repo.findItem(db,a.tenantId,current.estimateItemId),estimate=item&&await this.repo.findEstimate(db,a.tenantId,item.estimateId);if(!current||!item||!estimate)throw domainErrors.notFound();this.draft(estimate);if(current.version!==x.expectedVersion)throw domainErrors.conflict();const updated=await this.repo.updateMaterial(db,a.tenantId,a.id,id,x);if(!updated)throw domainErrors.conflict();await this.repo.refreshTotals(db,a.tenantId,a.id,estimate.id);await this.audit(db,a,"estimate_material","estimate_material.updated",id,{previousVersion:current.version,newVersion:updated.version});return updated;});}
 deleteMaterial(a:EstimateActor,id:string,version:number){assertCanUpdateEstimate(a);return inTenantTransaction(this.pool,a.tenantId,async db=>{const current=await this.repo.findMaterial(db,a.tenantId,id),item=current&&await this.repo.findItem(db,a.tenantId,current.estimateItemId),estimate=item&&await this.repo.findEstimate(db,a.tenantId,item.estimateId);if(!current||!item||!estimate)throw domainErrors.notFound();this.draft(estimate);if(current.version!==version)throw domainErrors.conflict();if(!await this.repo.deleteMaterial(db,a.tenantId,id,version))throw domainErrors.conflict();await this.repo.refreshTotals(db,a.tenantId,a.id,estimate.id);await this.audit(db,a,"estimate_material","estimate_material.deleted",id,{previousVersion:version});return {id};});}
 recalculate(a:EstimateActor,id:string){assertCanUpdateEstimate(a);return inTenantTransaction(this.pool,a.tenantId,async db=>{const estimate=await this.repo.findEstimate(db,a.tenantId,id);if(!estimate)throw domainErrors.notFound();this.draft(estimate);const page=await this.repo.items(db,a.tenantId,{page:1,pageSize:100,estimateId:id,sortOrder:"asc"});for(const item of page.items){const price=await this.repo.itemPriceList(db,a.tenantId,item.id);if(!price)throw new DomainError("INVALID_RELATIONSHIP",422,"Estimate item has no price list material breakdown");await this.calculateItem(db,a,item.id,price.priceListId);}const result=await this.repo.findEstimate(db,a.tenantId,id);await this.audit(db,a,"estimate","estimate.recalculated",id,{newVersion:result.version});return result;});}
}
