import {randomUUID} from "node:crypto";
import type {Pool,PoolClient} from "pg";
import {assertCanCreateMaterialCatalog,assertCanReadMaterialCatalog,assertCanUpdateMaterialCatalog} from "../../authorization/material-catalog-policy.js";
import {DomainError,domainErrors} from "../../domain/errors.js";
import {validateMaterialCategoryCreate,validateMaterialCategoryUpdate,validateMaterialCreate,validateMaterialUpdate} from "../../domain/material-catalog/material-catalog-rules.js";
import type {CreateMaterial,CreateMaterialCategory,MaterialCategoryListQuery,MaterialCategoryNode,MaterialListQuery,MoveMaterialCategory,UpdateMaterial,UpdateMaterialCategory} from "../../domain/material-catalog/material-catalog-types.js";
import {MaterialCatalogRepository} from "../../infrastructure/material-catalog/material-catalog-repository.js";
import {inTenantTransaction} from "../../infrastructure/transaction.js";
export type MaterialCatalogActor={id:string;tenantId:string;permissions:readonly string[];correlationId:string};
export class MaterialCatalogService{
 constructor(private pool:Pool,private repo=new MaterialCatalogRepository()){}
 private audit(db:PoolClient,a:MaterialCatalogActor,entity:string,action:string,id:string,metadata:Record<string,unknown>){return db.query("INSERT INTO audit_logs(tenant_id,actor_id,action,entity_type,entity_id,correlation_id,metadata) VALUES($1,$2,$3,$4,$5,$6,$7)",[a.tenantId,a.id,action,entity,id,/^[0-9a-f-]{36}$/i.test(a.correlationId)?a.correlationId:randomUUID(),metadata]);}
 private async references(db:PoolClient,a:MaterialCatalogActor,categoryId:string,unitId:string){const category=await this.repo.findCategory(db,a.tenantId,categoryId);if(!category)throw domainErrors.notFound();const unit=await this.repo.findUnit(db,a.tenantId,unitId);if(!unit)throw domainErrors.notFound();if(category.status!=="active")throw new DomainError("INVALID_RELATIONSHIP",422,"Material category must be active");if(unit.status!=="active")throw new DomainError("INVALID_RELATIONSHIP",422,"Measurement unit must be active");}
 listCategories(a:MaterialCatalogActor,q:MaterialCategoryListQuery){assertCanReadMaterialCatalog(a);return inTenantTransaction(this.pool,a.tenantId,db=>this.repo.categoryList(db,a.tenantId,q));}
 getCategory(a:MaterialCatalogActor,id:string){assertCanReadMaterialCatalog(a);return inTenantTransaction(this.pool,a.tenantId,async db=>{const x=await this.repo.findCategory(db,a.tenantId,id);if(!x)throw domainErrors.notFound();return x;});}
 tree(a:MaterialCatalogActor){assertCanReadMaterialCatalog(a);return inTenantTransaction(this.pool,a.tenantId,async db=>{const rows=await this.repo.tree(db,a.tenantId),nodes=new Map(rows.map(x=>[x.id,{...x,children:[]} as MaterialCategoryNode])),roots:MaterialCategoryNode[]=[];for(const row of rows){const node=nodes.get(row.id)!;if(row.parentId)nodes.get(row.parentId)?.children.push(node);else roots.push(node);}return roots;});}
 async createCategory(a:MaterialCatalogActor,input:CreateMaterialCategory){assertCanCreateMaterialCatalog(a);const x=validateMaterialCategoryCreate(input);try{return await inTenantTransaction(this.pool,a.tenantId,async db=>{let level=0;if(x.parentId){const p=await this.repo.findCategory(db,a.tenantId,x.parentId);if(!p)throw domainErrors.notFound();if(p.status!=="active")throw new DomainError("INVALID_RELATIONSHIP",422,"Parent category must be active");level=p.hierarchyLevel+1;if(level>3)throw domainErrors.validation("Category hierarchy exceeds maximum depth of 4");}const created=await this.repo.createCategory(db,a.tenantId,a.id,randomUUID(),x,level);await this.audit(db,a,"material_category","material_category.created",created.id,{code:created.code,parentId:created.parentId,newVersion:created.version});return created;});}catch(e:any){if(e?.code==="23505")throw domainErrors.duplicate("Material category code already exists");throw e;}}
 updateCategory(a:MaterialCatalogActor,id:string,input:UpdateMaterialCategory){assertCanUpdateMaterialCatalog(a);const x=validateMaterialCategoryUpdate(input);return inTenantTransaction(this.pool,a.tenantId,async db=>{const current=await this.repo.findCategory(db,a.tenantId,id);if(!current)throw domainErrors.notFound();if(current.version!==x.expectedVersion)throw domainErrors.conflict();const updated=await this.repo.updateCategory(db,a.tenantId,a.id,id,x);if(!updated)throw domainErrors.conflict();await this.audit(db,a,"material_category","material_category.updated",id,{previousVersion:current.version,newVersion:updated.version,changes:x});return updated;});}
 moveCategory(a:MaterialCatalogActor,id:string,input:MoveMaterialCategory){assertCanUpdateMaterialCatalog(a);return inTenantTransaction(this.pool,a.tenantId,async db=>{const current=await this.repo.findCategory(db,a.tenantId,id);if(!current)throw domainErrors.notFound();if(current.version!==input.expectedVersion)throw domainErrors.conflict();if(input.parentId===id)throw new DomainError("INVALID_RELATIONSHIP",422,"Category cannot be its own parent");const descendants=await this.repo.descendants(db,a.tenantId,id);if(input.parentId&&descendants.some(x=>x.id===input.parentId))throw new DomainError("INVALID_RELATIONSHIP",422,"Category move would create a cycle");let level=0;if(input.parentId){const p=await this.repo.findCategory(db,a.tenantId,input.parentId);if(!p)throw domainErrors.notFound();if(p.status!=="active")throw new DomainError("INVALID_RELATIONSHIP",422,"Parent category must be active");level=p.hierarchyLevel+1;}if(level+Math.max(...descendants.map(x=>x.depth))>3)throw domainErrors.validation("Category hierarchy exceeds maximum depth of 4");const moved=await this.repo.moveCategory(db,a.tenantId,a.id,id,input,level,level-current.hierarchyLevel);if(!moved)throw domainErrors.conflict();await this.audit(db,a,"material_category","material_category.moved",id,{previousVersion:current.version,newVersion:moved.version,previousParentId:current.parentId,parentId:moved.parentId});return moved;});}
 categoryStatus(a:MaterialCatalogActor,id:string,status:"active"|"inactive",version:number){assertCanUpdateMaterialCatalog(a);return inTenantTransaction(this.pool,a.tenantId,async db=>{const current=await this.repo.findCategory(db,a.tenantId,id);if(!current)throw domainErrors.notFound();if(current.version!==version)throw domainErrors.conflict();if(current.status===status)throw domainErrors.transition();if(status==="inactive"){const b=await this.repo.blockers(db,a.tenantId,id);if(Number(b.children)||Number(b.materials))throw new DomainError("INVALID_RELATIONSHIP",422,"Deactivate active child categories and materials first");}else if(current.parentId){const p=await this.repo.findCategory(db,a.tenantId,current.parentId);if(!p||p.status!=="active")throw new DomainError("INVALID_RELATIONSHIP",422,"Parent category must be active");}const updated=await this.repo.setCategoryStatus(db,a.tenantId,a.id,id,status,version);if(!updated)throw domainErrors.conflict();await this.audit(db,a,"material_category",`material_category.${status==="active"?"activated":"deactivated"}`,id,{previousVersion:version,newVersion:updated.version});return updated;});}
 listMaterials(a:MaterialCatalogActor,q:MaterialListQuery){assertCanReadMaterialCatalog(a);return inTenantTransaction(this.pool,a.tenantId,db=>this.repo.materialList(db,a.tenantId,q));}
 getMaterial(a:MaterialCatalogActor,id:string){assertCanReadMaterialCatalog(a);return inTenantTransaction(this.pool,a.tenantId,async db=>{const x=await this.repo.findMaterial(db,a.tenantId,id);if(!x)throw domainErrors.notFound();return x;});}
 async createMaterial(a:MaterialCatalogActor,input:CreateMaterial){assertCanCreateMaterialCatalog(a);const x=validateMaterialCreate(input);try{return await inTenantTransaction(this.pool,a.tenantId,async db=>{await this.references(db,a,x.categoryId,x.measurementUnitId);const created=await this.repo.createMaterial(db,a.tenantId,a.id,randomUUID(),x);await this.audit(db,a,"material","material.created",created.id,{code:created.code,categoryId:created.categoryId,measurementUnitId:created.measurementUnitId,newVersion:created.version});return created;});}catch(e:any){if(e?.code==="23505")throw domainErrors.duplicate("Material code already exists");throw e;}}
 updateMaterial(a:MaterialCatalogActor,id:string,input:UpdateMaterial){assertCanUpdateMaterialCatalog(a);const x=validateMaterialUpdate(input);return inTenantTransaction(this.pool,a.tenantId,async db=>{const current=await this.repo.findMaterial(db,a.tenantId,id);if(!current)throw domainErrors.notFound();if(current.version!==x.expectedVersion)throw domainErrors.conflict();if(x.categoryId||x.measurementUnitId)await this.references(db,a,x.categoryId??current.categoryId,x.measurementUnitId??current.measurementUnitId);const updated=await this.repo.updateMaterial(db,a.tenantId,a.id,id,x);if(!updated)throw domainErrors.conflict();await this.audit(db,a,"material","material.updated",id,{previousVersion:current.version,newVersion:updated.version,changes:x});return updated;});}
 materialStatus(a:MaterialCatalogActor,id:string,status:"active"|"inactive",version:number){assertCanUpdateMaterialCatalog(a);return inTenantTransaction(this.pool,a.tenantId,async db=>{const current=await this.repo.findMaterial(db,a.tenantId,id);if(!current)throw domainErrors.notFound();if(current.version!==version)throw domainErrors.conflict();if(current.status===status)throw domainErrors.transition();if(status==="active")await this.references(db,a,current.categoryId,current.measurementUnitId);const updated=await this.repo.setMaterialStatus(db,a.tenantId,a.id,id,status,version);if(!updated)throw domainErrors.conflict();await this.audit(db,a,"material",`material.${status==="active"?"activated":"deactivated"}`,id,{previousVersion:version,newVersion:updated.version});return updated;});}
}
