import type {PoolClient} from "pg";
import type {CreateMeasurementUnit,MeasurementUnit,MeasurementUnitListQuery,MeasurementUnitListResult,UpdateMeasurementUnit} from "../../domain/measurement-unit/measurement-unit-types.js";
const select=`id,tenant_id "tenantId",code,symbol,display_name "displayName",description,dimension,unit_system "unitSystem",status,decimal_precision::int "decimalPrecision",canonical_base_code "canonicalBaseCode",base_multiplier::text "baseMultiplier",is_system "isSystem",created_at "createdAt",updated_at "updatedAt",version::int`;
const sorts={code:"code",symbol:"symbol",displayName:"display_name",dimension:"dimension",unitSystem:"unit_system",status:"status",createdAt:"created_at",updatedAt:"updated_at"} as const;
export class MeasurementUnitRepository{
 findById(db:PoolClient,tenantId:string,id:string){return db.query<MeasurementUnit>(`SELECT ${select} FROM measurement_units WHERE tenant_id=$1 AND id=$2`,[tenantId,id]).then(r=>r.rows[0]);}
 findByCode(db:PoolClient,tenantId:string,code:string){return db.query<MeasurementUnit>(`SELECT ${select} FROM measurement_units WHERE tenant_id=$1 AND code=$2`,[tenantId,code]).then(r=>r.rows[0]);}
 async list(db:PoolClient,tenantId:string,q:MeasurementUnitListQuery):Promise<MeasurementUnitListResult>{const values:any[]=[tenantId],where=["tenant_id=$1"];if(q.search){values.push(`%${q.search}%`);where.push(`(code ILIKE $${values.length} OR symbol ILIKE $${values.length} OR display_name ILIKE $${values.length})`);}if(q.dimension){values.push(q.dimension);where.push(`dimension=$${values.length}`);}if(q.unitSystem){values.push(q.unitSystem);where.push(`unit_system=$${values.length}`);}if(q.active!==undefined){values.push(q.active?"active":"inactive");where.push(`status=$${values.length}`);}const clause=where.join(" AND "),total=Number((await db.query<{count:string}>(`SELECT count(*) FROM measurement_units WHERE ${clause}`,values)).rows[0].count);values.push(q.pageSize,(q.page-1)*q.pageSize);const direction=q.sortOrder==="asc"?"ASC":"DESC",items=(await db.query<MeasurementUnit>(`SELECT ${select} FROM measurement_units WHERE ${clause} ORDER BY ${sorts[q.sortBy]} ${direction},id ${direction} LIMIT $${values.length-1} OFFSET $${values.length}`,values)).rows;return {items,pagination:{page:q.page,pageSize:q.pageSize,total,totalPages:Math.ceil(total/q.pageSize)}};}
 async create(db:PoolClient,tenantId:string,actorId:string,id:string,x:CreateMeasurementUnit){return (await db.query<MeasurementUnit>(`INSERT INTO measurement_units(id,tenant_id,code,symbol,display_name,description,dimension,unit_system,decimal_precision,canonical_base_code,base_multiplier,is_system,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,false,$12,$12) RETURNING ${select}`,[id,tenantId,x.code,x.symbol,x.displayName,x.description??null,x.dimension,x.unitSystem,x.decimalPrecision,x.canonicalBaseCode??null,x.baseMultiplier??null,actorId])).rows[0];}
 async update(db:PoolClient,tenantId:string,actorId:string,id:string,x:UpdateMeasurementUnit){const fields=[["symbol","symbol"],["displayName","display_name"],["description","description"],["decimalPrecision","decimal_precision"],["canonicalBaseCode","canonical_base_code"],["baseMultiplier","base_multiplier"]] as const,sets:string[]=[],values:any[]=[];for(const [key,column] of fields)if(x[key]!==undefined){values.push(x[key]);sets.push(`${column}=$${values.length}`);}if(!sets.length)return this.findById(db,tenantId,id);values.push(actorId,id,tenantId,x.expectedVersion);return (await db.query<MeasurementUnit>(`UPDATE measurement_units SET ${sets.join(",")},updated_by=$${values.length-3},updated_at=now(),version=version+1 WHERE id=$${values.length-2} AND tenant_id=$${values.length-1} AND version=$${values.length} RETURNING ${select}`,values)).rows[0];}
 async setStatus(db:PoolClient,tenantId:string,actorId:string,id:string,status:"active"|"inactive",version:number){return (await db.query<MeasurementUnit>(`UPDATE measurement_units SET status=$1,updated_by=$2,updated_at=now(),version=version+1 WHERE id=$3 AND tenant_id=$4 AND version=$5 RETURNING ${select}`,[status,actorId,id,tenantId,version])).rows[0];}
 async convert(db:PoolClient,quantity:string,from:MeasurementUnit,to:MeasurementUnit,precision:number){return (await db.query<{result:string}>(`SELECT round(($1::numeric*$2::numeric/$3::numeric),$4)::text result`,[quantity,from.baseMultiplier,to.baseMultiplier,precision])).rows[0].result;}
}
