import{randomUUID}from"node:crypto";import type{Pool,PoolClient}from"pg";import type{DocumentReviewRepositoryPort}from"../../application/document-review/document-review-repository.js";import{enqueueDomainEvent}from"../notification/outbox.js";import{inTenantTransaction}from"../transaction.js";
export class DocumentReviewRepository implements DocumentReviewRepositoryPort{constructor(private pool:Pool){}transaction<T>(t:string,w:(db:PoolClient)=>Promise<T>){return inTenantTransaction(this.pool,t,w);}
 async document(db:PoolClient,t:string,id:string){return(await db.query("SELECT id FROM documents WHERE tenant_id=$1 AND id=$2 AND deleted_at IS NULL",[t,id])).rows[0];}
 async analysis(db:PoolClient,t:string,d:string){return(await db.query<any>(`SELECT c.id "classificationId",c.document_type "documentType",e.id "extractionResultId",e.fields FROM document_classifications c JOIN document_analysis_jobs j ON j.tenant_id=c.tenant_id AND j.id=c.analysis_job_id AND j.status='completed' JOIN document_extraction_results e ON e.tenant_id=c.tenant_id AND e.classification_id=c.id WHERE c.tenant_id=$1 AND c.document_id=$2 ORDER BY c.created_at DESC LIMIT 1`,[t,d])).rows[0];}
 async base(db:PoolClient,t:string,s:string){return(await db.query<any>(`SELECT c.document_type "documentType",e.fields FROM document_review_sessions r JOIN document_classifications c ON c.tenant_id=r.tenant_id AND c.id=r.classification_id JOIN document_extraction_results e ON e.tenant_id=r.tenant_id AND e.id=r.extraction_result_id WHERE r.tenant_id=$1 AND r.id=$2`,[t,s])).rows[0];}
 async session(db:PoolClient,t:string,id:string){return(await db.query<any>(`SELECT id,document_id "documentId",classification_id "classificationId",extraction_result_id "extractionResultId",status,assigned_to "assignedTo",started_at "startedAt",submitted_at "submittedAt",approved_at "approvedAt",rejected_at "rejectedAt",created_by "createdBy",created_at "createdAt",updated_at "updatedAt",version::int FROM document_review_sessions WHERE tenant_id=$1 AND id=$2`,[t,id])).rows[0];}
 async current(db:PoolClient,t:string,d:string){return(await db.query<any>(`SELECT id FROM document_review_sessions WHERE tenant_id=$1 AND document_id=$2 ORDER BY created_at DESC,id DESC LIMIT 1`,[t,d])).rows[0];}
 async fieldChanges(db:PoolClient,t:string,s:string){return(await db.query<any>(`SELECT id,field_name "fieldName",operation,previous_value "previousValue",proposed_value "proposedValue",normalized_value "normalizedValue",source,page_id "pageId",start_offset "startOffset",end_offset "endOffset",validation_status "validationStatus",change_reason "changeReason",created_by "createdBy",created_at "createdAt",version::int FROM document_review_field_changes WHERE tenant_id=$1 AND review_session_id=$2 ORDER BY created_at,id`,[t,s])).rows;}
 async classificationChanges(db:PoolClient,t:string,s:string){return(await db.query<any>(`SELECT id,previous_document_type "previousDocumentType",proposed_document_type "proposedDocumentType",change_reason "changeReason",created_by "createdBy",created_at "createdAt",version::int FROM document_review_classification_changes WHERE tenant_id=$1 AND review_session_id=$2 ORDER BY created_at,id`,[t,s])).rows;}
 async approved(db:PoolClient,t:string,d:string){return(await db.query<any>(`SELECT id,document_id "documentId",review_session_id "reviewSessionId",classification_id "classificationId",document_type "documentType",fields,approved_by "approvedBy",approved_at "approvedAt",created_at "createdAt",version::int FROM document_approved_data WHERE tenant_id=$1 AND document_id=$2`,[t,d])).rows[0];}
 async suggestions(db:PoolClient,t:string,s:string){return(await db.query<any>(`SELECT id,document_id "documentId",review_session_id "reviewSessionId",suggestion_type "suggestionType",field_name "fieldName",suggested_value "suggestedValue",suggested_document_type "suggestedDocumentType",confidence::float8,provider,provider_version "providerVersion",status,created_at "createdAt",accepted_at "acceptedAt",rejected_at "rejectedAt",accepted_by "acceptedBy",version::int FROM document_analysis_suggestions WHERE tenant_id=$1 AND review_session_id=$2 ORDER BY created_at,id`,[t,s])).rows;}
 async suggestion(db:PoolClient,t:string,id:string){return(await db.query<any>(`SELECT id,document_id "documentId",review_session_id "reviewSessionId",suggestion_type "suggestionType",field_name "fieldName",suggested_value "suggestedValue",suggested_document_type "suggestedDocumentType",confidence::float8,provider,provider_version "providerVersion",status,version::int FROM document_analysis_suggestions WHERE tenant_id=$1 AND id=$2`,[t,id])).rows[0];}
 async audit(db:PoolClient,a:{tenantId:string;id:string;correlationId:string},action:string,d:string,metadata:Record<string,unknown>){const c=/^[0-9a-f-]{36}$/i.test(a.correlationId)?a.correlationId:randomUUID();await db.query("INSERT INTO audit_logs(tenant_id,actor_id,action,entity_type,entity_id,correlation_id,metadata)VALUES($1,$2,$3,'document',$4,$5,$6)",[a.tenantId,a.id,action,d,c,metadata]);await enqueueDomainEvent(db,{tenantId:a.tenantId,actorId:a.id,action,entityType:"document",entityId:d,correlationId:c,metadata});}}
