import type {PoolClient} from "pg";
import {randomUUID} from "node:crypto";
import {enqueueDomainEvent} from "../notification/outbox.js";
import type {DocumentRepositoryPort} from "../../application/document/document-repository-port.js";
const entityTables={client:"clients",property:"properties",project:"projects",task:"tasks",invoice:"invoices",payment:"payments",expense:"expenses"} as const;
export class DocumentRepository implements DocumentRepositoryPort{
 async targetExists(db:PoolClient,tenant:string,type:keyof typeof entityTables,id:string){return Boolean((await db.query(`SELECT 1 FROM ${entityTables[type]} WHERE tenant_id=$1 AND id=$2 AND deleted_at IS NULL`,[tenant,id])).rowCount);}
 async document(db:PoolClient,tenant:string,id:string){const d=(await db.query<any>(`SELECT id,tenant_id "tenantId",title,document_type "documentType",source_type "sourceType",status,category,description,current_version_no "currentVersionNo",current_version_id "currentVersionId",page_count "pageCount",ocr_status "ocrStatus",ai_processing_status "aiProcessingStatus",version,created_at "createdAt",created_by "createdBy",updated_at "updatedAt",updated_by "updatedBy",deleted_at "archivedAt" FROM documents WHERE tenant_id=$1 AND id=$2`,[tenant,id])).rows[0];if(!d)return undefined;const versions=(await this.versions(db,tenant,id));const links=(await db.query<any>(`SELECT id,entity_type "entityType",entity_id "entityId" FROM document_links WHERE tenant_id=$1 AND document_id=$2 ORDER BY created_at`,[tenant,id])).rows;return {...d,version:Number(d.version),currentVersionNo:Number(d.currentVersionNo),pageCount:d.pageCount===null?null:Number(d.pageCount),currentVersion:versions.find(x=>x.id===d.currentVersionId)??versions[0],links};}
 async versions(db:PoolClient,tenant:string,id:string){return (await db.query<any>(`SELECT v.id,v.version_no "versionNo",f.original_filename "originalFilename",f.mime_type "mimeType",v.extension,f.size_bytes "fileSize",f.checksum_sha256 checksum,v.uploaded_by "uploadedBy",v.created_at "createdAt",f.storage_key "storageKey",f.storage_provider "storageProvider",f.storage_bucket "storageBucket",v.file_object_id "fileObjectId" FROM document_versions v JOIN file_objects f ON f.tenant_id=v.tenant_id AND f.id=v.file_object_id WHERE v.tenant_id=$1 AND v.document_id=$2 ORDER BY v.version_no DESC`,[tenant,id])).rows.map(x=>({...x,versionNo:Number(x.versionNo),fileSize:Number(x.fileSize)}));}
 async list(db:PoolClient,tenant:string,q:any){const where=["d.tenant_id=$1"],values:any[]=[tenant];if(q.archived!==true)where.push("d.deleted_at IS NULL");if(q.archived===true)where.push("d.deleted_at IS NOT NULL");if(q.search){values.push(`%${q.search}%`);where.push(`(f.original_filename ILIKE $${values.length} OR d.title ILIKE $${values.length} OR d.description ILIKE $${values.length})`);}for(const [field,column] of [["documentType","d.document_type"],["status","d.status"],["ocrStatus","d.ocr_status"],["aiProcessingStatus","d.ai_processing_status"],["category","d.category"],["mimeType","f.mime_type"],["uploaderId","v.uploaded_by"]] as const)if(q[field]){values.push(q[field]);where.push(`${column}=$${values.length}`);}if(q.createdFrom){values.push(q.createdFrom);where.push(`d.created_at>=$${values.length}`);}if(q.createdTo){values.push(q.createdTo);where.push(`d.created_at<=$${values.length}`);}if(q.entityType){values.push(q.entityType);where.push(`EXISTS(SELECT 1 FROM document_links l WHERE l.tenant_id=d.tenant_id AND l.document_id=d.id AND l.entity_type=$${values.length}${q.entityId?` AND l.entity_id=$${values.length+1}`:""})`);if(q.entityId)values.push(q.entityId);}const order={filename:"f.original_filename",title:"d.title",documentType:"d.document_type",category:"d.category",createdAt:"d.created_at",updatedAt:"d.updated_at"}[q.sortBy as string]??"d.updated_at",offset=(q.page-1)*q.pageSize;values.push(q.pageSize,offset);const from=`documents d JOIN document_versions v ON v.tenant_id=d.tenant_id AND v.id=d.current_version_id JOIN file_objects f ON f.tenant_id=v.tenant_id AND f.id=v.file_object_id`;const rows=(await db.query<any>(`SELECT d.id FROM ${from} WHERE ${where.join(" AND ")} ORDER BY ${order} ${q.sortOrder==="asc"?"ASC":"DESC"}, d.id ASC LIMIT $${values.length-1} OFFSET $${values.length}`,values)).rows;const items=[];for(const r of rows)items.push(await this.document(db,tenant,r.id));const total=Number((await db.query(`SELECT count(*) FROM ${from} WHERE ${where.join(" AND ")}`,values.slice(0,-2))).rows[0].count);return {items,pagination:{page:q.page,pageSize:q.pageSize,total,totalPages:Math.ceil(total/q.pageSize)}};}
 async audit(db:PoolClient,a:any,action:string,id:string,metadata:any){const correlation=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(a.correlationId)?a.correlationId:randomUUID();await db.query(`INSERT INTO audit_logs(tenant_id,actor_id,action,entity_type,entity_id,correlation_id,metadata) VALUES($1,$2,$3,'document',$4,$5,$6)`,[a.tenantId,a.id,action,id,correlation,metadata]);await enqueueDomainEvent(db,{tenantId:a.tenantId,actorId:a.id,action,entityType:"document",entityId:id,correlationId:correlation,metadata});}
}
