import type {PoolClient} from "pg";
import {randomUUID} from "node:crypto";
import {enqueueDomainEvent} from "../notification/outbox.js";
const entityTables={client:"clients",property:"properties",project:"projects",task:"tasks",invoice:"invoices",payment:"payments",expense:"expenses"} as const;
export class DocumentRepository{
 async targetExists(db:PoolClient,tenant:string,type:keyof typeof entityTables,id:string){return Boolean((await db.query(`SELECT 1 FROM ${entityTables[type]} WHERE tenant_id=$1 AND id=$2 AND deleted_at IS NULL`,[tenant,id])).rowCount);}
 async document(db:PoolClient,tenant:string,id:string){const d=(await db.query<any>(`SELECT id,tenant_id "tenantId",category,description,current_version_no "currentVersionNo",version,created_at "createdAt",updated_at "updatedAt",deleted_at "archivedAt" FROM documents WHERE tenant_id=$1 AND id=$2`,[tenant,id])).rows[0];if(!d)return undefined;const versions=(await this.versions(db,tenant,id));const links=(await db.query<any>(`SELECT id,entity_type "entityType",entity_id "entityId" FROM document_links WHERE tenant_id=$1 AND document_id=$2 ORDER BY created_at`,[tenant,id])).rows;return {...d,version:Number(d.version),currentVersionNo:Number(d.currentVersionNo),currentVersion:versions[0],links};}
 async versions(db:PoolClient,tenant:string,id:string){return (await db.query<any>(`SELECT id,version_no "versionNo",original_filename "originalFilename",mime_type "mimeType",extension,file_size "fileSize",checksum,uploaded_by "uploadedBy",created_at "createdAt",storage_key "storageKey" FROM document_versions WHERE tenant_id=$1 AND document_id=$2 ORDER BY version_no DESC`,[tenant,id])).rows.map(x=>({...x,versionNo:Number(x.versionNo),fileSize:Number(x.fileSize)}));}
 async list(db:PoolClient,tenant:string,q:any){const where=["d.tenant_id=$1"],values:any[]=[tenant];if(q.archived!==true)where.push("d.deleted_at IS NULL");if(q.archived===true)where.push("d.deleted_at IS NOT NULL");if(q.search){values.push(`%${q.search}%`);where.push(`(v.original_filename ILIKE $${values.length} OR d.description ILIKE $${values.length})`);}if(q.category){values.push(q.category);where.push(`d.category=$${values.length}`);}if(q.mimeType){values.push(q.mimeType);where.push(`v.mime_type=$${values.length}`);}if(q.uploaderId){values.push(q.uploaderId);where.push(`v.uploaded_by=$${values.length}`);}if(q.createdFrom){values.push(q.createdFrom);where.push(`d.created_at>=$${values.length}`);}if(q.createdTo){values.push(q.createdTo);where.push(`d.created_at<=$${values.length}`);}if(q.entityType){values.push(q.entityType);where.push(`EXISTS(SELECT 1 FROM document_links l WHERE l.document_id=d.id AND l.entity_type=$${values.length}${q.entityId?` AND l.entity_id=$${values.length+1}`:""})`);if(q.entityId)values.push(q.entityId);}const order={filename:"v.original_filename",category:"d.category",createdAt:"d.created_at",updatedAt:"d.updated_at"}[q.sortBy as string]??"d.updated_at",offset=(q.page-1)*q.pageSize;values.push(q.pageSize,offset);const rows=(await db.query<any>(`SELECT d.id FROM documents d JOIN document_versions v ON v.document_id=d.id AND v.version_no=d.current_version_no WHERE ${where.join(" AND ")} ORDER BY ${order} ${q.sortOrder==="asc"?"ASC":"DESC"} LIMIT $${values.length-1} OFFSET $${values.length}`,values)).rows;const items=[];for(const r of rows)items.push(await this.document(db,tenant,r.id));const total=Number((await db.query(`SELECT count(*) FROM documents d JOIN document_versions v ON v.document_id=d.id AND v.version_no=d.current_version_no WHERE ${where.join(" AND ")}`,values.slice(0,-2))).rows[0].count);return {items,pagination:{page:q.page,pageSize:q.pageSize,total,totalPages:Math.ceil(total/q.pageSize)}};}
 async audit(db:PoolClient,a:any,action:string,id:string,metadata:any){const correlation=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(a.correlationId)?a.correlationId:randomUUID();await db.query(`INSERT INTO audit_logs(tenant_id,actor_id,action,entity_type,entity_id,correlation_id,metadata) VALUES($1,$2,$3,'document',$4,$5,$6)`,[a.tenantId,a.id,action,id,correlation,metadata]);await enqueueDomainEvent(db,{tenantId:a.tenantId,actorId:a.id,action,entityType:"document",entityId:id,correlationId:correlation,metadata});}
}
