import type {PoolClient} from "pg";
import type {DocumentPageRepositoryPort} from "../../application/document/document-page-repository-port.js";
import {DocumentRepository} from "./document-repository.js";

export class DocumentPageRepository implements DocumentPageRepositoryPort{
 private documents=new DocumentRepository();
 document(db:PoolClient,tenantId:string,documentId:string){return this.documents.document(db,tenantId,documentId);}
 async page(db:PoolClient,tenantId:string,documentId:string,pageId:string){const row=(await db.query<any>(`SELECT p.id,p.tenant_id "tenantId",p.document_id "documentId",p.source_file_object_id "sourceFileObjectId",p.processed_file_object_id "processedFileObjectId",p.page_number "pageNumber",p.rotation_degrees "rotationDegrees",p.processing_status "processingStatus",p.processing_error_code "processingErrorCode",p.width "widthPixels",p.height "heightPixels",p.original_width "originalWidthPixels",p.original_height "originalHeightPixels",p.crop_metadata crop,p.perspective_metadata perspective,p.enhancement_preset "enhancementPreset",p.checksum,p.version,p.created_at "createdAt",p.created_by "createdBy",p.updated_at "updatedAt",p.updated_by "updatedBy",sf.mime_type "sourceMimeType" FROM document_pages p JOIN file_objects sf ON sf.tenant_id=p.tenant_id AND sf.id=p.source_file_object_id WHERE p.tenant_id=$1 AND p.document_id=$2 AND p.id=$3`,[tenantId,documentId,pageId])).rows[0];return row?{...row,pageNumber:Number(row.pageNumber),rotationDegrees:Number(row.rotationDegrees),version:Number(row.version),widthPixels:row.widthPixels===null?null:Number(row.widthPixels),heightPixels:row.heightPixels===null?null:Number(row.heightPixels),originalWidthPixels:row.originalWidthPixels===null?null:Number(row.originalWidthPixels),originalHeightPixels:row.originalHeightPixels===null?null:Number(row.originalHeightPixels)}:undefined;}
 async pages(db:PoolClient,tenantId:string,documentId:string){return (await db.query<any>(`SELECT p.id FROM document_pages p WHERE p.tenant_id=$1 AND p.document_id=$2 ORDER BY p.page_number`,[tenantId,documentId])).rows.reduce(async(acc,row)=>[...await acc,await this.page(db,tenantId,documentId,row.id)],Promise.resolve<any[]>([]));}
 async file(db:PoolClient,tenantId:string,fileObjectId:string){return (await db.query<any>(`SELECT id,storage_provider "storageProvider",storage_bucket "storageBucket",storage_key "storageKey",original_filename "originalFilename",mime_type "mimeType",size_bytes "sizeBytes",checksum_sha256 checksum,status FROM file_objects WHERE tenant_id=$1 AND id=$2 AND status='available'`,[tenantId,fileObjectId])).rows[0];}
 audit(db:PoolClient,actor:any,action:string,documentId:string,metadata:any){return this.documents.audit(db,actor,action,documentId,metadata);}
}
