import {randomUUID} from "node:crypto";
import type {Pool,PoolClient} from "pg";
import {assertCanArchiveTask,assertCanAssignTask,assertCanCreateTask,assertCanReadTask,assertCanReviewTask,assertCanTransitionTask,assertCanUpdateTask,canSelfTransitionTask} from "../../authorization/task-policy.js";
import {DomainError,domainErrors} from "../../domain/errors.js";
import {assertDueDateWithinProject,normalizeReviewComment,normalizeTask,normalizeTaskUpdate,taskLifecycleTransition} from "../../domain/task/task-rules.js";
import type {CreateTaskCommand,Task,TaskLifecycleAction,TaskListQuery,TaskListResult,UpdateTaskCommand} from "../../domain/task/task-types.js";
import {TaskRepository} from "../../infrastructure/task/task-repository.js";
import {inTenantTransaction} from "../../infrastructure/transaction.js";
import {enqueueDomainEvent} from "../../infrastructure/notification/outbox.js";

export type TaskActor={id:string;tenantId:string;permissions:readonly string[];correlationId:string};
const correlation=(value:string)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)?value:randomUUID();
export class TaskService {
  constructor(private readonly pool:Pool,private readonly repository=new TaskRepository()){}
  private async audit(db:PoolClient,actor:TaskActor,action:string,id:string|undefined,metadata:Record<string,unknown>={}){const idempotencyCorrelation=correlation(actor.correlationId);await db.query("INSERT INTO audit_logs(tenant_id,actor_id,action,entity_type,entity_id,correlation_id,metadata) VALUES($1,$2,$3,'task',$4,$5,$6)",[actor.tenantId,actor.id,action,id??null,idempotencyCorrelation,metadata]);await enqueueDomainEvent(db,{tenantId:actor.tenantId,actorId:actor.id,action,entityType:"task",entityId:id,correlationId:idempotencyCorrelation,metadata});}
  private async authorize(actor:TaskActor,assertion:(actor:TaskActor)=>void,operation:string,id?:string){try{assertion(actor);}catch(error){await inTenantTransaction(this.pool,actor.tenantId,db=>this.audit(db,actor,"task.permission_denied",id,{operation}));throw error;}}
  private async recordFailure(actor:TaskActor,error:unknown,id?:string){if(!(error instanceof DomainError))return;const actions:Partial<Record<DomainError["code"],string>>={VERSION_CONFLICT:"task.version_conflict",ENTITY_ARCHIVED:"task.archived_mutation_denied",INVALID_STATUS_TRANSITION:"task.invalid_lifecycle_transition"};const action=actions[error.code];if(action)await inTenantTransaction(this.pool,actor.tenantId,db=>this.audit(db,actor,action,id));}
  private async projectForMutation(db:PoolClient,tenantId:string,id:string){const project=await this.repository.findProject(db,tenantId,id);if(!project)throw domainErrors.notFound();if(project.archivedAt||project.status==="archived")throw domainErrors.archived();if(project.status==="completed"||project.status==="cancelled")throw new DomainError("INVALID_RELATIONSHIP",422,"Tasks cannot be changed in a terminal Project");return project;}
  async createTask(actor:TaskActor,input:CreateTaskCommand):Promise<Task>{await this.authorize(actor,assertCanCreateTask,"create");const value=normalizeTask(input);try{return await inTenantTransaction(this.pool,actor.tenantId,async db=>{const project=await this.projectForMutation(db,actor.tenantId,value.projectId);assertDueDateWithinProject(value.dueDate,project.startDate,project.expectedCompletionDate);const entity=await this.repository.create(db,actor.tenantId,actor.id,randomUUID(),value);await this.audit(db,actor,"task.created",entity.id,{projectId:entity.projectId});return entity;});}catch(error){await this.recordFailure(actor,error);throw error;}}
  async getTask(actor:TaskActor,id:string):Promise<Task>{await this.authorize(actor,assertCanReadTask,"read",id);const entity=await inTenantTransaction(this.pool,actor.tenantId,db=>this.repository.findById(db,actor.tenantId,id));if(!entity)throw domainErrors.notFound();return entity;}
  async listTasks(actor:TaskActor,query:TaskListQuery):Promise<TaskListResult>{await this.authorize(actor,assertCanReadTask,"list");if(!Number.isInteger(query.page)||query.page<1||!Number.isInteger(query.pageSize)||query.pageSize<1||query.pageSize>100)throw domainErrors.validation("Invalid pagination");if(!(["title","status","priority","dueDate","createdAt","updatedAt"] as string[]).includes(query.sortBy))throw domainErrors.validation("Invalid sort field");return inTenantTransaction(this.pool,actor.tenantId,db=>this.repository.list(db,actor.tenantId,query));}
  async updateTask(actor:TaskActor,id:string,input:UpdateTaskCommand):Promise<Task>{await this.authorize(actor,assertCanUpdateTask,"update",id);const value=normalizeTaskUpdate(input);try{return await inTenantTransaction(this.pool,actor.tenantId,async db=>{const current=await this.repository.findById(db,actor.tenantId,id);if(!current)throw domainErrors.notFound();if(current.archivedAt||current.status==="archived")throw domainErrors.archived();if(current.version!==value.expectedVersion)throw domainErrors.conflict();const project=await this.projectForMutation(db,actor.tenantId,value.projectId??current.projectId);assertDueDateWithinProject(value.dueDate===undefined?current.dueDate:value.dueDate,project.startDate,project.expectedCompletionDate);const updated=await this.repository.update(db,actor.tenantId,actor.id,id,value);if(!updated)throw domainErrors.conflict();await this.audit(db,actor,"task.updated",id,{previousVersion:current.version,newVersion:updated.version});return updated;});}catch(error){await this.recordFailure(actor,error,id);throw error;}}
  async archiveTask(actor:TaskActor,id:string,expectedVersion:number):Promise<Task>{await this.authorize(actor,assertCanArchiveTask,"archive",id);if(!Number.isInteger(expectedVersion)||expectedVersion<1)throw domainErrors.validation("expectedVersion must be a positive integer");try{return await inTenantTransaction(this.pool,actor.tenantId,async db=>{const current=await this.repository.findById(db,actor.tenantId,id);if(!current)throw domainErrors.notFound();if(current.archivedAt||current.status==="archived")throw domainErrors.archived();if(current.version!==expectedVersion)throw domainErrors.conflict();const archived=await this.repository.archive(db,actor.tenantId,actor.id,id,expectedVersion);if(!archived)throw domainErrors.conflict();await this.audit(db,actor,"task.archived",id,{previousVersion:current.version,newVersion:archived.version});return archived;});}catch(error){await this.recordFailure(actor,error,id);throw error;}}
  async transitionTask(actor:TaskActor,id:string,action:TaskLifecycleAction,expectedVersion:number,commentInput?:string):Promise<Task>{
    const selfAction=action==="start"||action==="resume"||action==="submit",reviewAction=action==="accept"||action==="return";
    const usesSelfAuthority=selfAction&&!actor.permissions.includes("tasks.update")&&canSelfTransitionTask(actor);
    if(reviewAction)await this.authorize(actor,assertCanReviewTask,action,id);else if(!usesSelfAuthority)await this.authorize(actor,assertCanTransitionTask,action,id);
    if(!Number.isInteger(expectedVersion)||expectedVersion<1)throw domainErrors.validation("expectedVersion must be a positive integer");const comment=normalizeReviewComment(action,commentInput);
    try{return await inTenantTransaction(this.pool,actor.tenantId,async db=>{const current=await this.repository.findById(db,actor.tenantId,id);if(!current)throw domainErrors.notFound();if(current.archivedAt||current.status==="archived")throw domainErrors.archived();if(current.version!==expectedVersion)throw domainErrors.conflict();if(usesSelfAuthority&&!await this.repository.hasAssignment(db,actor.tenantId,id,actor.id))throw domainErrors.forbidden();const project=await this.projectForMutation(db,actor.tenantId,current.projectId);const next=taskLifecycleTransition(action,current.status);const updated=await this.repository.transition(db,actor.tenantId,actor.id,id,expectedVersion,current.status,next);if(!updated)throw domainErrors.conflict();const reviewActionName=next==="submitted_for_review"||next==="accepted"||next==="returned"?next:null;if(reviewActionName)await this.repository.addReviewEvent(db,actor.tenantId,id,actor.id,reviewActionName,comment,updated.version);const event={start:"task.started",block:"task.blocked",resume:"task.resumed",submit:"task.submitted_for_review",accept:"task.accepted",return:"task.returned",complete:"task.completed",cancel:"task.cancelled"}[action];await this.audit(db,actor,event,id,{from:current.status,to:next,comment,recipientUserId:action==="submit"?project.projectManagerId:undefined,previousVersion:current.version,newVersion:updated.version});return (await this.repository.findById(db,actor.tenantId,id))!;});}catch(error){await this.recordFailure(actor,error,id);throw error;}}
  startTask(actor:TaskActor,id:string,expectedVersion:number){return this.transitionTask(actor,id,"start",expectedVersion);}blockTask(actor:TaskActor,id:string,expectedVersion:number){return this.transitionTask(actor,id,"block",expectedVersion);}resumeTask(actor:TaskActor,id:string,expectedVersion:number){return this.transitionTask(actor,id,"resume",expectedVersion);}completeTask(actor:TaskActor,id:string,expectedVersion:number){return this.transitionTask(actor,id,"complete",expectedVersion);}cancelTask(actor:TaskActor,id:string,expectedVersion:number){return this.transitionTask(actor,id,"cancel",expectedVersion);}
  async assignTask(actor:TaskActor,id:string,userId:string,expectedVersion:number):Promise<Task>{await this.authorize(actor,assertCanAssignTask,"assign",id);if(!Number.isInteger(expectedVersion)||expectedVersion<1)throw domainErrors.validation("expectedVersion must be a positive integer");try{return await inTenantTransaction(this.pool,actor.tenantId,async db=>{const current=await this.repository.findById(db,actor.tenantId,id);if(!current)throw domainErrors.notFound();if(current.archivedAt||current.status==="archived")throw domainErrors.archived();if(current.version!==expectedVersion)throw domainErrors.conflict();await this.projectForMutation(db,actor.tenantId,current.projectId);if(!await this.repository.findUser(db,actor.tenantId,userId))throw domainErrors.notFound();if(await this.repository.hasAssignment(db,actor.tenantId,id,userId))throw domainErrors.duplicate("User is already assigned");const updated=await this.repository.assign(db,actor.tenantId,actor.id,id,userId,expectedVersion);if(!updated)throw domainErrors.conflict();await this.audit(db,actor,"task.assigned",id,{userId,previousVersion:current.version,newVersion:updated.version});return updated;});}catch(error){await this.recordFailure(actor,error,id);throw error;}}
  async unassignTask(actor:TaskActor,id:string,userId:string,expectedVersion:number):Promise<Task>{await this.authorize(actor,assertCanAssignTask,"unassign",id);if(!Number.isInteger(expectedVersion)||expectedVersion<1)throw domainErrors.validation("expectedVersion must be a positive integer");try{return await inTenantTransaction(this.pool,actor.tenantId,async db=>{const current=await this.repository.findById(db,actor.tenantId,id);if(!current)throw domainErrors.notFound();if(current.archivedAt||current.status==="archived")throw domainErrors.archived();if(current.version!==expectedVersion)throw domainErrors.conflict();await this.projectForMutation(db,actor.tenantId,current.projectId);if(!await this.repository.hasAssignment(db,actor.tenantId,id,userId))throw domainErrors.notFound();const updated=await this.repository.unassign(db,actor.tenantId,actor.id,id,userId,expectedVersion);if(!updated)throw domainErrors.conflict();await this.audit(db,actor,"task.unassigned",id,{userId,previousVersion:current.version,newVersion:updated.version});return updated;});}catch(error){await this.recordFailure(actor,error,id);throw error;}}
}
