import{randomUUID}from"node:crypto";import type{Pool,PoolClient}from"pg";
import{domainErrors}from"../../domain/errors.js";import{normalizeTaskProblem,taskProblemTransition}from"../../domain/task/task-problem-rules.js";import type{CreateTaskProblem,TaskProblemStatus}from"../../domain/task/task-problem-types.js";import{TaskProblemRepository}from"../../infrastructure/task/task-problem-repository.js";import{inUserTransaction}from"../../infrastructure/transaction.js";import{enqueueDomainEvent}from"../../infrastructure/notification/outbox.js";import type{TaskActor}from"./task-service.js";
const need=(actor:TaskActor,permission:string)=>{if(!actor.permissions.includes(permission))throw domainErrors.forbidden()};
export class TaskProblemService{constructor(private readonly pool:Pool,private readonly repository=new TaskProblemRepository()){}
 private async audit(db:PoolClient,actor:TaskActor,action:string,id:string,taskId:string,metadata:Record<string,unknown>){const correlationId=/^[0-9a-f-]{36}$/i.test(actor.correlationId)?actor.correlationId:randomUUID();await db.query("INSERT INTO audit_logs(tenant_id,actor_id,action,entity_type,entity_id,correlation_id,metadata)VALUES($1,$2,$3,'task_problem',$4,$5,$6)",[actor.tenantId,actor.id,action,id,correlationId,metadata]);await enqueueDomainEvent(db,{tenantId:actor.tenantId,actorId:actor.id,action,entityType:"task",entityId:taskId,correlationId,metadata})}
 async create(actor:TaskActor,taskId:string,input:CreateTaskProblem){need(actor,"task_problems.create");const value=normalizeTaskProblem(input);return inUserTransaction(this.pool,actor.tenantId,actor.id,async db=>{const task=await this.repository.task(db,actor.tenantId,taskId);if(!task||task.archivedAt)throw domainErrors.notFound();if(!task.assigned&&!actor.permissions.includes("task_problems.update"))throw domainErrors.forbidden();const problem=await this.repository.create(db,actor.tenantId,actor.id,taskId,task.projectId,randomUUID(),value);await this.audit(db,actor,"task.problem_reported",problem.id,taskId,{taskId,problemId:problem.id,projectId:task.projectId,category:problem.category,recipientUserId:task.projectManagerId});return problem})}
 async list(actor:TaskActor,filters:{taskId?:string;projectId?:string;status?:TaskProblemStatus}){need(actor,"task_problems.read");return inUserTransaction(this.pool,actor.tenantId,actor.id,db=>this.repository.list(db,actor.tenantId,filters,actor.id,actor.permissions.includes("task_problems.update")))}
 async update(actor:TaskActor,id:string,expectedVersion:number,status:Exclude<TaskProblemStatus,"open">){need(actor,"task_problems.update");if(!Number.isInteger(expectedVersion)||expectedVersion<1)throw domainErrors.validation("expectedVersion must be a positive integer");return inUserTransaction(this.pool,actor.tenantId,actor.id,async db=>{const current=await this.repository.find(db,actor.tenantId,id);if(!current)throw domainErrors.notFound();if(current.version!==expectedVersion)throw domainErrors.conflict();const next=taskProblemTransition(current.status,status),updated=await this.repository.update(db,actor.tenantId,actor.id,id,expectedVersion,next);if(!updated)throw domainErrors.conflict();await this.audit(db,actor,`task.problem_${next}`,id,current.taskId,{taskId:current.taskId,problemId:id,previousVersion:current.version,newVersion:updated.version});return updated})}
}
