import { randomUUID } from "node:crypto";
import type { Pool,PoolClient } from "pg";
import { assertCanArchiveProperty,assertCanCreateProperty,assertCanReadProperty,assertCanUpdateProperty } from "../../authorization/property-policy.js";
import { DomainError,domainErrors } from "../../domain/errors.js";
import { normalizeProperty,normalizePropertyUpdate } from "../../domain/property/property-rules.js";
import type { CreatePropertyCommand,Property,PropertyListQuery,PropertyListResult,UpdatePropertyCommand } from "../../domain/property/property-types.js";
import { PropertyRepository } from "../../infrastructure/property/property-repository.js";
import { inTenantTransaction } from "../../infrastructure/transaction.js";

export type PropertyActor={id:string;tenantId:string;permissions:readonly string[];correlationId:string};
const correlation=(value:string)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)?value:randomUUID();
export class PropertyService {
  constructor(private readonly pool:Pool,private readonly repository=new PropertyRepository()){}
  private async audit(db:PoolClient,actor:PropertyActor,action:string,id:string|undefined,metadata:Record<string,unknown>={}){await db.query("INSERT INTO audit_logs(tenant_id,actor_id,action,entity_type,entity_id,correlation_id,metadata) VALUES($1,$2,$3,'property',$4,$5,$6)",[actor.tenantId,actor.id,action,id??null,correlation(actor.correlationId),metadata]);}
  private async authorize(actor:PropertyActor,assertion:(actor:PropertyActor)=>void,operation:string,id?:string){try{assertion(actor);}catch(error){await inTenantTransaction(this.pool,actor.tenantId,db=>this.audit(db,actor,"property.permission_denied",id,{operation}));throw error;}}
  private async recordFailure(actor:PropertyActor,error:unknown,id?:string){if(!(error instanceof DomainError))return;const actions:Partial<Record<DomainError["code"],string>>={VERSION_CONFLICT:"property.version_conflict",ENTITY_ARCHIVED:"property.archived_mutation_denied",INVALID_RELATIONSHIP:"property.invalid_client"};const action=actions[error.code];if(action)await inTenantTransaction(this.pool,actor.tenantId,db=>this.audit(db,actor,action,id));}
  private async assertEligibleClient(db:PoolClient,tenantId:string,id:string){const client=await this.repository.findClient(db,tenantId,id);if(!client)throw domainErrors.notFound();if(client.archivedAt||client.status==="archived")throw domainErrors.archived();}
  async createProperty(actor:PropertyActor,input:CreatePropertyCommand):Promise<Property>{await this.authorize(actor,assertCanCreateProperty,"create");const value=normalizeProperty(input);try{return await inTenantTransaction(this.pool,actor.tenantId,async db=>{await this.assertEligibleClient(db,actor.tenantId,value.clientId);const entity=await this.repository.create(db,actor.tenantId,actor.id,randomUUID(),randomUUID(),value);await this.audit(db,actor,"property.created",entity.id,{clientId:entity.clientId});return entity;});}catch(error){await this.recordFailure(actor,error);throw error;}}
  async getProperty(actor:PropertyActor,id:string):Promise<Property>{await this.authorize(actor,assertCanReadProperty,"read",id);const entity=await inTenantTransaction(this.pool,actor.tenantId,db=>this.repository.findById(db,actor.tenantId,id));if(!entity)throw domainErrors.notFound();return entity;}
  async listProperties(actor:PropertyActor,query:PropertyListQuery):Promise<PropertyListResult>{await this.authorize(actor,assertCanReadProperty,"list");if(!Number.isInteger(query.page)||query.page<1||!Number.isInteger(query.pageSize)||query.pageSize<1||query.pageSize>100)throw domainErrors.validation("Invalid pagination");if(!(["name","status","propertyType","createdAt","updatedAt"] as string[]).includes(query.sortBy))throw domainErrors.validation("Invalid sort field");return inTenantTransaction(this.pool,actor.tenantId,db=>this.repository.list(db,actor.tenantId,query));}
  async updateProperty(actor:PropertyActor,id:string,input:UpdatePropertyCommand):Promise<Property>{await this.authorize(actor,assertCanUpdateProperty,"update",id);const value=normalizePropertyUpdate(input);try{return await inTenantTransaction(this.pool,actor.tenantId,async db=>{const current=await this.repository.findById(db,actor.tenantId,id);if(!current)throw domainErrors.notFound();if(current.archivedAt||current.status==="archived")throw domainErrors.archived();if(current.version!==value.expectedVersion)throw domainErrors.conflict();if(value.clientId!==undefined)await this.assertEligibleClient(db,actor.tenantId,value.clientId);const updated=await this.repository.update(db,actor.tenantId,actor.id,id,current.addressId,value);if(!updated)throw domainErrors.conflict();await this.audit(db,actor,"property.updated",id,{previousVersion:current.version,newVersion:updated.version});return updated;});}catch(error){await this.recordFailure(actor,error,id);throw error;}}
  async archiveProperty(actor:PropertyActor,id:string,expectedVersion:number):Promise<Property>{await this.authorize(actor,assertCanArchiveProperty,"archive",id);if(!Number.isInteger(expectedVersion)||expectedVersion<1)throw domainErrors.validation("expectedVersion must be a positive integer");try{return await inTenantTransaction(this.pool,actor.tenantId,async db=>{const current=await this.repository.findById(db,actor.tenantId,id);if(!current)throw domainErrors.notFound();if(current.archivedAt||current.status==="archived")throw domainErrors.archived();if(current.version!==expectedVersion)throw domainErrors.conflict();const archived=await this.repository.archive(db,actor.tenantId,actor.id,id,expectedVersion);if(!archived)throw domainErrors.conflict();await this.audit(db,actor,"property.archived",id,{previousVersion:current.version,newVersion:archived.version});return archived;});}catch(error){await this.recordFailure(actor,error,id);throw error;}}
}
