import{createHash}from"node:crypto";import{domainErrors}from"../errors.js";
export const workTypes=["gypsum_plaster","cement_plaster","primer","painting","wallpaper","ceramic_tile","porcelain_tile","laminate","parquet","vinyl_flooring","epoxy_floor","drywall_wall","drywall_ceiling","concrete_repair","waterproofing","thermal_insulation","facade_render","facade_paint","electrical_chasing","pipe_installation","acoustic_insulation","cleaning","demolition","preparation"]as const;
export type WorkType=typeof workTypes[number];export const targetTypes=["project","building","building_floor","apartment","room","wall","ceiling","floor","door","window","opening","column","beam","custom_element"]as const;export type TargetType=typeof targetTypes[number];
export type ScopeItem={id:string;workType:WorkType;sequence:number;targetType:TargetType;targetReference:string;technologyVersionId:string;reviewState:"pending"|"confirmed"|"rejected"};export type ScopeDependency={predecessorId:string;successorId:string;kind:"finish_to_start"|"drying"|"inspection"|"safety"};
const quantityMap:Partial<Record<WorkType,readonly string[]>>={gypsum_plaster:["plastering_net_wall_area"],cement_plaster:["render_net_wall_area"],primer:["primer_wall_area","primer_ceiling_area"],painting:["painting_wall_area","painting_ceiling_area"],wallpaper:["wallpaper_area"],ceramic_tile:["tile_wall_area","tile_floor_area"],porcelain_tile:["tile_wall_area","tile_floor_area"],laminate:["flooring_area"],parquet:["flooring_area"],vinyl_flooring:["flooring_area"],epoxy_floor:["flooring_area"],drywall_wall:["drywall_wall_area"],drywall_ceiling:["suspended_ceiling_area"],waterproofing:["waterproofing_wall_area","waterproofing_floor_area"],thermal_insulation:["insulation_wall_area"],acoustic_insulation:["insulation_wall_area"]};
export function allowedScannerQuantities(type:WorkType){return quantityMap[type]??[]}
export function validateQuantityMapping(type:WorkType,quantityType:string){const allowed=allowedScannerQuantities(type);if(!allowed.includes(quantityType))throw domainErrors.validation("WORK_SCOPE_QUANTITY_MAPPING_INVALID",{workType:type,quantityType,allowed})}
export function executionSequence(items:ScopeItem[],dependencies:ScopeDependency[]){const active=items.filter(x=>x.reviewState!=="rejected"),ids=new Set(active.map(x=>x.id)),edges=new Map(active.map(x=>[x.id,[]as string[]])),indegree=new Map(active.map(x=>[x.id,0]));for(const d of dependencies){if(!ids.has(d.predecessorId)||!ids.has(d.successorId))throw domainErrors.validation("WORK_SCOPE_DEPENDENCY_TARGET_MISSING",{dependency:d});if(d.predecessorId===d.successorId)throw domainErrors.validation("WORK_SCOPE_CIRCULAR_DEPENDENCY");edges.get(d.predecessorId)!.push(d.successorId);indegree.set(d.successorId,indegree.get(d.successorId)!+1);const before=active.find(x=>x.id===d.predecessorId)!,after=active.find(x=>x.id===d.successorId)!;if(before.sequence>=after.sequence)throw domainErrors.validation("WORK_SCOPE_WRONG_SEQUENCE",{predecessorId:before.id,successorId:after.id})}const ready=active.filter(x=>indegree.get(x.id)===0).sort((a,b)=>a.sequence-b.sequence||a.id.localeCompare(b.id)),out:ScopeItem[]=[];while(ready.length){const x=ready.shift()!;out.push(x);for(const y of edges.get(x.id)!){indegree.set(y,indegree.get(y)!-1);if(indegree.get(y)===0){ready.push(active.find(i=>i.id===y)!);ready.sort((a,b)=>a.sequence-b.sequence||a.id.localeCompare(b.id))}}}if(out.length!==active.length)throw domainErrors.validation("WORK_SCOPE_CIRCULAR_DEPENDENCY");return out}
export function validateScopeReadiness(items:ScopeItem[],dependencies:ScopeDependency[],mappedItemIds:Set<string>){const issues:{code:string;itemId?:string}[]=[];if(!items.length)issues.push({code:"WORK_SCOPE_EMPTY"});for(const item of items.filter(x=>x.reviewState!=="rejected")){if(item.reviewState!=="confirmed")issues.push({code:"WORK_SCOPE_ITEM_UNCONFIRMED",itemId:item.id});if(allowedScannerQuantities(item.workType).length&&!mappedItemIds.has(item.id))issues.push({code:"WORK_SCOPE_QUANTITY_MAPPING_MISSING",itemId:item.id})}try{executionSequence(items,dependencies)}catch(e){issues.push({code:e instanceof Error?e.message:"WORK_SCOPE_SEQUENCE_INVALID"})}return issues}
export function fingerprintScope(content:unknown){return createHash("sha256").update(JSON.stringify(content)).digest("hex")}
