import{Resend}from"resend";import type{CommunicationProvider,InboundAttachment,InboundEnvelope,OutboundEnvelope,ProviderSendResult}from"../../application/communication/communication-provider.js";
type ResendClient={emails:{send:(input:any,options:any)=>Promise<any>;receiving:{get:(id:string)=>Promise<any>;attachments:{list:(input:any)=>Promise<any>}}};webhooks:{verify:(input:any)=>any}};
export type ResendWebhookEvent={type:string;created_at:string;data:any;id?:string};
export type ResendEmailConfiguration={apiKey?:string;webhookSecret?:string;fromEmail?:string;verified:boolean};
export class ResendEmailProvider implements CommunicationProvider{id="resend";channel="email"as const;truth:"REAL"|"PARTIAL";reason:string;private client:ResendClient;
 constructor(readonly configuration:ResendEmailConfiguration,client?:ResendClient,private fetcher:typeof fetch=fetch){this.client=client??new Resend(configuration.apiKey??"re_not_configured")as unknown as ResendClient;this.truth=configuration.apiKey&&configuration.webhookSecret&&configuration.fromEmail&&configuration.verified?"REAL":"PARTIAL";this.reason=this.truth==="REAL"?"Resend is authorized and owner-verified for live send, receive and delivery callbacks.":"Adapter is installed, but live provider authorization and end-to-end owner verification are incomplete."}
 verifyWebhook(payload:string,headers:{id:string;timestamp:string;signature:string}){if(!this.configuration.webhookSecret)throw new Error("RESEND_WEBHOOK_NOT_CONFIGURED");return this.client.webhooks.verify({payload,headers,webhookSecret:this.configuration.webhookSecret})as ResendWebhookEvent}
 async send(input:OutboundEnvelope):Promise<ProviderSendResult>{if(this.truth!=="REAL"||!this.configuration.fromEmail)throw new Error("PROVIDER_UNAVAILABLE:resend");const headers:Record<string,string>={};if(input.threadReference){headers["In-Reply-To"]=input.threadReference;headers.References=input.threadReference}const response=await this.client.emails.send({from:this.configuration.fromEmail,to:input.to,cc:input.cc,subject:input.subject??"OMNIRO message",text:input.body,headers,tags:[{name:"tenant_id",value:input.tenantId},{name:"communication_message_id",value:input.messageId}],attachments:input.attachments.map(x=>({filename:x.filename,content:x.content,contentType:x.contentType}))},{idempotencyKey:input.idempotencyKey});if(response.error||!response.data?.id)throw new Error(`RESEND_SEND_FAILED:${response.error?.message??"unknown"}`);return{providerMessageId:response.data.id,acceptedAt:new Date().toISOString()}}
 async mapInbound(payload:unknown):Promise<InboundEnvelope>{const event=payload as ResendWebhookEvent;if(event.type!=="email.received")throw new Error("UNSUPPORTED_RESEND_EVENT");const received=await this.client.emails.receiving.get(event.data.email_id);if(received.error||!received.data)throw new Error(`RESEND_INBOUND_FETCH_FAILED:${received.error?.message??"unknown"}`);const listed=await this.client.emails.receiving.attachments.list({emailId:event.data.email_id}),attachments:InboundAttachment[]=[];for(const item of listed.data?.data??[]){const response=await this.fetcher(item.download_url);if(!response.ok)throw new Error(`RESEND_ATTACHMENT_FETCH_FAILED:${response.status}`);attachments.push({providerAttachmentId:item.id,filename:item.filename??"attachment",contentType:item.content_type,content:Buffer.from(await response.arrayBuffer())})}return{providerEventId:String(event.id??event.data.email_id),providerMessageId:event.data.email_id,providerThreadId:received.data.message_id??event.data.message_id,channel:"email",from:received.data.from,to:received.data.to,cc:received.data.cc??[],subject:received.data.subject,body:received.data.text??received.data.html??"[Empty email]",attachmentReferences:(event.data.attachments??[]).map((x:any)=>x.id),attachments,receivedAt:event.data.created_at??event.created_at}}
}
export function createResendEmailProvider(environment:NodeJS.ProcessEnv=process.env){return new ResendEmailProvider({apiKey:environment.RESEND_API_KEY,webhookSecret:environment.RESEND_WEBHOOK_SECRET,fromEmail:environment.RESEND_FROM_EMAIL,verified:environment.RESEND_PROVIDER_VERIFIED==="true"})}
