CREATE TABLE design_projects(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,project_id uuid NOT NULL,property_id uuid,code varchar(60) NOT NULL,display_name varchar(300) NOT NULL,
 version bigint NOT NULL DEFAULT 1 CHECK(version>=1),created_at timestamptz NOT NULL DEFAULT now(),created_by uuid NOT NULL,updated_at timestamptz NOT NULL DEFAULT now(),updated_by uuid NOT NULL,
 UNIQUE(tenant_id,id),UNIQUE(tenant_id,code),FOREIGN KEY(tenant_id,project_id)REFERENCES projects(tenant_id,id),FOREIGN KEY(tenant_id,property_id)REFERENCES properties(tenant_id,id),
 FOREIGN KEY(tenant_id,created_by)REFERENCES users(tenant_id,id),FOREIGN KEY(tenant_id,updated_by)REFERENCES users(tenant_id,id)
);
CREATE TABLE design_project_revisions(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,design_project_id uuid NOT NULL,revision_number integer NOT NULL CHECK(revision_number>=1),
 status text NOT NULL DEFAULT'draft'CHECK(status IN('draft','collecting_information','review_required','changes_requested','ready_for_approval','approved','cancelled','superseded')),is_current boolean NOT NULL DEFAULT true,summary varchar(5000),
 technical_assignment_snapshot_id uuid,technical_assignment_fingerprint char(64),technical_assignment_schema_version varchar(80),room_scan_snapshot_id uuid,room_scan_fingerprint char(64),room_scan_schema_version varchar(80),
 approved_at timestamptz,approved_by uuid,superseded_at timestamptz,superseded_by_revision_id uuid,version bigint NOT NULL DEFAULT 1 CHECK(version>=1),
 created_at timestamptz NOT NULL DEFAULT now(),created_by uuid NOT NULL,updated_at timestamptz NOT NULL DEFAULT now(),updated_by uuid NOT NULL,
 UNIQUE(tenant_id,id),UNIQUE(tenant_id,design_project_id,id),UNIQUE(tenant_id,design_project_id,revision_number),FOREIGN KEY(tenant_id,design_project_id)REFERENCES design_projects(tenant_id,id)ON DELETE CASCADE,
 FOREIGN KEY(tenant_id,approved_by)REFERENCES users(tenant_id,id),FOREIGN KEY(tenant_id,created_by)REFERENCES users(tenant_id,id),FOREIGN KEY(tenant_id,updated_by)REFERENCES users(tenant_id,id),
 CHECK((technical_assignment_snapshot_id IS NULL)=(technical_assignment_fingerprint IS NULL)AND(technical_assignment_snapshot_id IS NULL)=(technical_assignment_schema_version IS NULL)),
 CHECK((room_scan_snapshot_id IS NULL)=(room_scan_fingerprint IS NULL)AND(room_scan_snapshot_id IS NULL)=(room_scan_schema_version IS NULL)),
 CHECK(technical_assignment_fingerprint IS NULL OR technical_assignment_fingerprint~'^[0-9a-f]{64}$'),CHECK(room_scan_fingerprint IS NULL OR room_scan_fingerprint~'^[0-9a-f]{64}$'),
 CHECK((status='approved'AND approved_at IS NOT NULL AND approved_by IS NOT NULL)OR status<>'approved'),CHECK((status='superseded'AND superseded_at IS NOT NULL AND NOT is_current)OR status<>'superseded')
);
ALTER TABLE design_project_revisions ADD CONSTRAINT design_project_revision_successor_fk FOREIGN KEY(tenant_id,superseded_by_revision_id)REFERENCES design_project_revisions(tenant_id,id);
CREATE UNIQUE INDEX uq_design_project_current_revision ON design_project_revisions(tenant_id,design_project_id)WHERE is_current;

CREATE TABLE design_decisions(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,design_project_id uuid NOT NULL,revision_id uuid NOT NULL,
 decision_type text NOT NULL CHECK(decision_type IN('finish_selection','material_selection','layout_decision','color_decision','fixture_selection','door_window_decision','ceiling_decision','built_in_furniture','decorative_element','design_exclusion','design_assumption')),
 category varchar(120) NOT NULL,title varchar(500) NOT NULL,review_status text NOT NULL DEFAULT'pending'CHECK(review_status IN('pending','accepted','rejected','changes_requested','superseded')),
 source_type text NOT NULL CHECK(source_type IN('designer','architect','engineer','customer','project_manager','company_employee','approved_technical_assignment','approved_room_scan','imported_document','ai_suggestion_accepted','other')),
 source_reference varchar(300),blocking boolean NOT NULL DEFAULT false,ordering_key varchar(200) NOT NULL,notes varchar(5000),supersedes_decision_id uuid,reviewed_by uuid,reviewed_at timestamptz,
 accepted_ai_by uuid,accepted_ai_at timestamptz,version bigint NOT NULL DEFAULT 1 CHECK(version>=1),created_at timestamptz NOT NULL DEFAULT now(),created_by uuid NOT NULL,updated_at timestamptz NOT NULL DEFAULT now(),updated_by uuid NOT NULL,
 UNIQUE(tenant_id,id),UNIQUE(tenant_id,revision_id,id),UNIQUE(tenant_id,design_project_id,revision_id,id),UNIQUE(tenant_id,revision_id,ordering_key),
 FOREIGN KEY(tenant_id,design_project_id)REFERENCES design_projects(tenant_id,id)ON DELETE CASCADE,FOREIGN KEY(tenant_id,design_project_id,revision_id)REFERENCES design_project_revisions(tenant_id,design_project_id,id)ON DELETE CASCADE,
 FOREIGN KEY(tenant_id,supersedes_decision_id)REFERENCES design_decisions(tenant_id,id),FOREIGN KEY(tenant_id,reviewed_by)REFERENCES users(tenant_id,id),FOREIGN KEY(tenant_id,accepted_ai_by)REFERENCES users(tenant_id,id),
 FOREIGN KEY(tenant_id,created_by)REFERENCES users(tenant_id,id),FOREIGN KEY(tenant_id,updated_by)REFERENCES users(tenant_id,id),
 CHECK((review_status='pending'AND reviewed_by IS NULL AND reviewed_at IS NULL)OR(review_status<>'pending'AND reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL)),
 CHECK((source_type='ai_suggestion_accepted'AND accepted_ai_by IS NOT NULL AND accepted_ai_at IS NOT NULL)OR source_type<>'ai_suggestion_accepted')
);
CREATE TABLE design_decision_details(
 decision_id uuid PRIMARY KEY,tenant_id uuid NOT NULL,revision_id uuid NOT NULL,design_project_id uuid NOT NULL,
 surface_category varchar(120),family varchar(160),subtype varchar(160),manufacturer varchar(200),product_line varchar(200),model varchar(200),product_code varchar(200),color_system varchar(80),color_code varchar(160),texture varchar(160),sheen varchar(80),finish varchar(160),
 nominal_width numeric(14,4),nominal_height numeric(14,4),nominal_depth numeric(14,4),nominal_unit text CHECK(nominal_unit IN('mm','cm','m')),
 quality_tier text CHECK(quality_tier IN('basic','standard','enhanced','premium','custom')),substitution_policy text CHECK(substitution_policy IN('not_allowed','equivalent_only','approved_alternative')),customer_supplied boolean,
 layout_type varchar(120),orientation text CHECK(orientation IN('horizontal','vertical','diagonal','radial','custom')),alignment varchar(160),joint_pattern varchar(160),offset_percent numeric(6,3)CHECK(offset_percent BETWEEN 0 AND 100),fixture_category varchar(120),placement_concept varchar(1000),connection_expectation varchar(1000),installation_expected boolean,
 assumption_requires_confirmation boolean,exclusion_kind varchar(120),version bigint NOT NULL DEFAULT 1 CHECK(version>=1),created_at timestamptz NOT NULL DEFAULT now(),created_by uuid NOT NULL,updated_at timestamptz NOT NULL DEFAULT now(),updated_by uuid NOT NULL,
 UNIQUE(tenant_id,decision_id),FOREIGN KEY(tenant_id,design_project_id,revision_id,decision_id)REFERENCES design_decisions(tenant_id,design_project_id,revision_id,id)ON DELETE CASCADE,FOREIGN KEY(tenant_id,design_project_id)REFERENCES design_projects(tenant_id,id)ON DELETE CASCADE,
 FOREIGN KEY(tenant_id,created_by)REFERENCES users(tenant_id,id),FOREIGN KEY(tenant_id,updated_by)REFERENCES users(tenant_id,id),
 CHECK(nominal_width IS NULL OR nominal_width>0),CHECK(nominal_height IS NULL OR nominal_height>0),CHECK(nominal_depth IS NULL OR nominal_depth>0),
 CHECK((nominal_width IS NULL AND nominal_height IS NULL AND nominal_depth IS NULL)OR nominal_unit IS NOT NULL)
);
CREATE TABLE design_decision_applicability(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,design_project_id uuid NOT NULL,revision_id uuid NOT NULL,decision_id uuid NOT NULL,
 target_type text NOT NULL CHECK(target_type IN('entire_object','entire_design_project','room','multiple_rooms','zone','scanner_element','wall','floor','ceiling','opening','fixture_location','design_zone','future_work_scope')),
 target_reference varchar(300),source_type text NOT NULL CHECK(source_type IN('design_project','approved_room_scan')),source_snapshot_id uuid,source_fingerprint char(64),source_schema_version varchar(80),element_type varchar(80),ordering_key varchar(200) NOT NULL,
 created_at timestamptz NOT NULL DEFAULT now(),created_by uuid NOT NULL,UNIQUE(tenant_id,decision_id,source_type,target_type,target_reference),UNIQUE(tenant_id,decision_id,ordering_key),
 FOREIGN KEY(tenant_id,design_project_id,revision_id,decision_id)REFERENCES design_decisions(tenant_id,design_project_id,revision_id,id)ON DELETE CASCADE,FOREIGN KEY(tenant_id,design_project_id)REFERENCES design_projects(tenant_id,id)ON DELETE CASCADE,FOREIGN KEY(tenant_id,created_by)REFERENCES users(tenant_id,id),
 CHECK((target_type IN('entire_object','entire_design_project')AND target_reference IS NULL)OR(target_type NOT IN('entire_object','entire_design_project')AND target_reference IS NOT NULL)),
 CHECK((source_type='approved_room_scan'AND source_snapshot_id IS NOT NULL AND source_fingerprint~'^[0-9a-f]{64}$'AND source_schema_version IS NOT NULL AND element_type IS NOT NULL)OR(source_type='design_project'AND source_snapshot_id IS NULL AND source_fingerprint IS NULL AND source_schema_version IS NULL))
);
CREATE TABLE design_decision_alternatives(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,design_project_id uuid NOT NULL,revision_id uuid NOT NULL,decision_id uuid NOT NULL,
 title varchar(500) NOT NULL,state text NOT NULL CHECK(state IN('pending','selected','rejected','superseded')),ordering_key varchar(200) NOT NULL,reason varchar(3000),selected_by uuid,selected_at timestamptz,
 version bigint NOT NULL DEFAULT 1 CHECK(version>=1),created_at timestamptz NOT NULL DEFAULT now(),created_by uuid NOT NULL,updated_at timestamptz NOT NULL DEFAULT now(),updated_by uuid NOT NULL,
 UNIQUE(tenant_id,id),UNIQUE(tenant_id,decision_id,ordering_key),FOREIGN KEY(tenant_id,design_project_id,revision_id,decision_id)REFERENCES design_decisions(tenant_id,design_project_id,revision_id,id)ON DELETE CASCADE,
 FOREIGN KEY(tenant_id,design_project_id)REFERENCES design_projects(tenant_id,id)ON DELETE CASCADE,FOREIGN KEY(tenant_id,selected_by)REFERENCES users(tenant_id,id),FOREIGN KEY(tenant_id,created_by)REFERENCES users(tenant_id,id),FOREIGN KEY(tenant_id,updated_by)REFERENCES users(tenant_id,id),
 CHECK((state='selected'AND selected_by IS NOT NULL AND selected_at IS NOT NULL)OR state<>'selected')
);
CREATE UNIQUE INDEX uq_design_decision_selected_alternative ON design_decision_alternatives(tenant_id,decision_id)WHERE state='selected';
CREATE TABLE design_open_items(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,design_project_id uuid NOT NULL,revision_id uuid NOT NULL,item_type text NOT NULL CHECK(item_type IN('customer_decision_required','designer_decision_required','engineer_input_required','site_verification_required','sample_approval_required','manufacturer_document_required','legal_approval_required')),
 description varchar(5000) NOT NULL,blocking boolean NOT NULL DEFAULT true,status text NOT NULL DEFAULT'open'CHECK(status IN('open','resolved','waived')),resolution varchar(5000),resolved_by uuid,resolved_at timestamptz,version bigint NOT NULL DEFAULT 1 CHECK(version>=1),
 created_at timestamptz NOT NULL DEFAULT now(),created_by uuid NOT NULL,updated_at timestamptz NOT NULL DEFAULT now(),updated_by uuid NOT NULL,UNIQUE(tenant_id,id),
 FOREIGN KEY(tenant_id,design_project_id)REFERENCES design_projects(tenant_id,id)ON DELETE CASCADE,FOREIGN KEY(tenant_id,design_project_id,revision_id)REFERENCES design_project_revisions(tenant_id,design_project_id,id)ON DELETE CASCADE,
 FOREIGN KEY(tenant_id,resolved_by)REFERENCES users(tenant_id,id),FOREIGN KEY(tenant_id,created_by)REFERENCES users(tenant_id,id),FOREIGN KEY(tenant_id,updated_by)REFERENCES users(tenant_id,id)
);
CREATE TABLE design_references(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,design_project_id uuid NOT NULL,revision_id uuid NOT NULL,decision_id uuid,
 reference_type text NOT NULL CHECK(reference_type IN('drawing','image','mood_board','product_datasheet','catalog','sample','external_document','imported_document','bim','cad','other')),
 external_id varchar(300) NOT NULL,title varchar(500) NOT NULL,reference_version varchar(100),checksum varchar(128),source varchar(200) NOT NULL,author varchar(200),locator varchar(300),review_status text NOT NULL DEFAULT'pending'CHECK(review_status IN('pending','accepted','rejected','changes_requested')),
 version bigint NOT NULL DEFAULT 1 CHECK(version>=1),created_at timestamptz NOT NULL DEFAULT now(),created_by uuid NOT NULL,updated_at timestamptz NOT NULL DEFAULT now(),updated_by uuid NOT NULL,UNIQUE(tenant_id,id),UNIQUE(tenant_id,revision_id,external_id,reference_version),
 FOREIGN KEY(tenant_id,design_project_id)REFERENCES design_projects(tenant_id,id)ON DELETE CASCADE,FOREIGN KEY(tenant_id,design_project_id,revision_id)REFERENCES design_project_revisions(tenant_id,design_project_id,id)ON DELETE CASCADE,FOREIGN KEY(tenant_id,decision_id)REFERENCES design_decisions(tenant_id,id),
 FOREIGN KEY(tenant_id,created_by)REFERENCES users(tenant_id,id),FOREIGN KEY(tenant_id,updated_by)REFERENCES users(tenant_id,id)
);
CREATE TABLE approved_design_project_snapshots(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,design_project_id uuid NOT NULL,revision_id uuid NOT NULL,revision_number integer NOT NULL,project_id uuid NOT NULL,property_id uuid,
 content jsonb NOT NULL CHECK(jsonb_typeof(content)='object'AND pg_column_size(content)<=1048576),content_fingerprint char(64) NOT NULL CHECK(content_fingerprint~'^[0-9a-f]{64}$'),schema_version varchar(80) NOT NULL CHECK(schema_version='design-project-v1'),
 approved_at timestamptz NOT NULL,approved_by uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,id),UNIQUE(tenant_id,design_project_id,revision_number),UNIQUE(tenant_id,revision_id),UNIQUE(tenant_id,content_fingerprint),
 FOREIGN KEY(tenant_id,design_project_id)REFERENCES design_projects(tenant_id,id),FOREIGN KEY(tenant_id,design_project_id,revision_id)REFERENCES design_project_revisions(tenant_id,design_project_id,id),FOREIGN KEY(tenant_id,project_id)REFERENCES projects(tenant_id,id),FOREIGN KEY(tenant_id,property_id)REFERENCES properties(tenant_id,id),FOREIGN KEY(tenant_id,approved_by)REFERENCES users(tenant_id,id)
);
CREATE FUNCTION immutable_design_project_snapshot()RETURNS trigger LANGUAGE plpgsql SET search_path=public,pg_temp AS $$BEGIN RAISE EXCEPTION 'approved design project snapshot is immutable';END$$;
CREATE TRIGGER immutable_approved_design_project_snapshot BEFORE UPDATE OR DELETE ON approved_design_project_snapshots FOR EACH ROW EXECUTE FUNCTION immutable_design_project_snapshot();
CREATE FUNCTION protect_approved_design_revision()RETURNS trigger LANGUAGE plpgsql SET search_path=public,pg_temp AS $$BEGIN IF OLD.status IN('approved','superseded')AND NOT(TG_OP='UPDATE'AND((OLD.status='approved'AND NEW.status='superseded'AND NOT NEW.is_current AND NEW.revision_number=OLD.revision_number AND NEW.design_project_id=OLD.design_project_id)OR(OLD.status='superseded'AND NEW.status='superseded'AND OLD.superseded_by_revision_id IS NULL AND NEW.superseded_by_revision_id IS NOT NULL AND NOT NEW.is_current AND NEW.revision_number=OLD.revision_number AND NEW.design_project_id=OLD.design_project_id)))THEN RAISE EXCEPTION 'approved design project revision is immutable';END IF;IF TG_OP='DELETE'THEN RETURN OLD;END IF;RETURN NEW;END$$;
CREATE TRIGGER immutable_approved_design_project_revision BEFORE UPDATE OR DELETE ON design_project_revisions FOR EACH ROW EXECUTE FUNCTION protect_approved_design_revision();
CREATE FUNCTION protect_approved_design_content()RETURNS trigger LANGUAGE plpgsql SET search_path=public,pg_temp AS $$DECLARE rid uuid;tid uuid;state text;BEGIN rid=CASE WHEN TG_OP='DELETE'THEN OLD.revision_id ELSE NEW.revision_id END;tid=CASE WHEN TG_OP='DELETE'THEN OLD.tenant_id ELSE NEW.tenant_id END;SELECT status INTO state FROM design_project_revisions WHERE tenant_id=tid AND id=rid;IF state IN('approved','superseded')THEN RAISE EXCEPTION 'approved design project content is immutable';END IF;IF TG_OP='DELETE'THEN RETURN OLD;END IF;RETURN NEW;END$$;
CREATE TRIGGER immutable_design_decisions BEFORE INSERT OR UPDATE OR DELETE ON design_decisions FOR EACH ROW EXECUTE FUNCTION protect_approved_design_content();
CREATE TRIGGER immutable_design_details BEFORE INSERT OR UPDATE OR DELETE ON design_decision_details FOR EACH ROW EXECUTE FUNCTION protect_approved_design_content();
CREATE TRIGGER immutable_design_applicability BEFORE INSERT OR UPDATE OR DELETE ON design_decision_applicability FOR EACH ROW EXECUTE FUNCTION protect_approved_design_content();
CREATE TRIGGER immutable_design_alternatives BEFORE INSERT OR UPDATE OR DELETE ON design_decision_alternatives FOR EACH ROW EXECUTE FUNCTION protect_approved_design_content();
CREATE TRIGGER immutable_design_open_items BEFORE INSERT OR UPDATE OR DELETE ON design_open_items FOR EACH ROW EXECUTE FUNCTION protect_approved_design_content();
CREATE TRIGGER immutable_design_references BEFORE INSERT OR UPDATE OR DELETE ON design_references FOR EACH ROW EXECUTE FUNCTION protect_approved_design_content();
CREATE INDEX idx_design_projects_project ON design_projects(tenant_id,project_id,updated_at DESC);CREATE INDEX idx_design_revisions_status ON design_project_revisions(tenant_id,status,updated_at DESC);
CREATE INDEX idx_design_decisions_active ON design_decisions(tenant_id,revision_id,review_status,decision_type,ordering_key);CREATE INDEX idx_design_decisions_supersession ON design_decisions(tenant_id,supersedes_decision_id);
CREATE INDEX idx_design_applicability_target ON design_decision_applicability(tenant_id,target_type,target_reference);CREATE INDEX idx_design_alternatives ON design_decision_alternatives(tenant_id,decision_id,state,ordering_key);
CREATE INDEX idx_design_open_items ON design_open_items(tenant_id,revision_id,blocking,status);CREATE INDEX idx_design_references ON design_references(tenant_id,revision_id,reference_type);CREATE INDEX idx_design_snapshots ON approved_design_project_snapshots(tenant_id,design_project_id,revision_number DESC);
ALTER TABLE design_projects ENABLE ROW LEVEL SECURITY;ALTER TABLE design_projects FORCE ROW LEVEL SECURITY;ALTER TABLE design_project_revisions ENABLE ROW LEVEL SECURITY;ALTER TABLE design_project_revisions FORCE ROW LEVEL SECURITY;
ALTER TABLE design_decisions ENABLE ROW LEVEL SECURITY;ALTER TABLE design_decisions FORCE ROW LEVEL SECURITY;ALTER TABLE design_decision_details ENABLE ROW LEVEL SECURITY;ALTER TABLE design_decision_details FORCE ROW LEVEL SECURITY;
ALTER TABLE design_decision_applicability ENABLE ROW LEVEL SECURITY;ALTER TABLE design_decision_applicability FORCE ROW LEVEL SECURITY;ALTER TABLE design_decision_alternatives ENABLE ROW LEVEL SECURITY;ALTER TABLE design_decision_alternatives FORCE ROW LEVEL SECURITY;
ALTER TABLE design_open_items ENABLE ROW LEVEL SECURITY;ALTER TABLE design_open_items FORCE ROW LEVEL SECURITY;ALTER TABLE design_references ENABLE ROW LEVEL SECURITY;ALTER TABLE design_references FORCE ROW LEVEL SECURITY;
ALTER TABLE approved_design_project_snapshots ENABLE ROW LEVEL SECURITY;ALTER TABLE approved_design_project_snapshots FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_design_projects ON design_projects USING(tenant_id=NULLIF(current_setting('app.tenant_id',true),'')::uuid)WITH CHECK(tenant_id=NULLIF(current_setting('app.tenant_id',true),'')::uuid);
CREATE POLICY tenant_design_revisions ON design_project_revisions USING(tenant_id=NULLIF(current_setting('app.tenant_id',true),'')::uuid)WITH CHECK(tenant_id=NULLIF(current_setting('app.tenant_id',true),'')::uuid);
CREATE POLICY tenant_design_decisions ON design_decisions USING(tenant_id=NULLIF(current_setting('app.tenant_id',true),'')::uuid)WITH CHECK(tenant_id=NULLIF(current_setting('app.tenant_id',true),'')::uuid);
CREATE POLICY tenant_design_details ON design_decision_details USING(tenant_id=NULLIF(current_setting('app.tenant_id',true),'')::uuid)WITH CHECK(tenant_id=NULLIF(current_setting('app.tenant_id',true),'')::uuid);
CREATE POLICY tenant_design_applicability ON design_decision_applicability USING(tenant_id=NULLIF(current_setting('app.tenant_id',true),'')::uuid)WITH CHECK(tenant_id=NULLIF(current_setting('app.tenant_id',true),'')::uuid);
CREATE POLICY tenant_design_alternatives ON design_decision_alternatives USING(tenant_id=NULLIF(current_setting('app.tenant_id',true),'')::uuid)WITH CHECK(tenant_id=NULLIF(current_setting('app.tenant_id',true),'')::uuid);
CREATE POLICY tenant_design_open_items ON design_open_items USING(tenant_id=NULLIF(current_setting('app.tenant_id',true),'')::uuid)WITH CHECK(tenant_id=NULLIF(current_setting('app.tenant_id',true),'')::uuid);
CREATE POLICY tenant_design_references ON design_references USING(tenant_id=NULLIF(current_setting('app.tenant_id',true),'')::uuid)WITH CHECK(tenant_id=NULLIF(current_setting('app.tenant_id',true),'')::uuid);
CREATE POLICY tenant_design_snapshots ON approved_design_project_snapshots USING(tenant_id=NULLIF(current_setting('app.tenant_id',true),'')::uuid)WITH CHECK(tenant_id=NULLIF(current_setting('app.tenant_id',true),'')::uuid);
ALTER TABLE notifications DROP CONSTRAINT notifications_event_type_check;
ALTER TABLE notifications ADD CONSTRAINT notifications_event_type_check CHECK(event_type IN('task.assigned','task.due_soon','task.overdue','task.completed','project.started','project.paused','project.completed','invoice.issued','invoice.due_soon','invoice.overdue','invoice.paid','payment.received','expense.approved','expense.rejected','document.uploaded','document.version_created','document.archived','document.page_ocr_requested','document.page_ocr_started','document.page_ocr_completed','document.page_ocr_failed','document.page_ocr_retried','document.page_ocr_cancelled','document.analysis_requested','document.analysis_started','document.classified','document.extraction_completed','document.analysis_failed','document.analysis_retried','document.analysis_cancelled','document.review_started','document.review_assigned','document.review_field_changed','document.review_classification_changed','document.review_submitted','document.review_changes_requested','document.review_approved','document.review_rejected','document.suggestions_requested','document.suggestion_created','document.suggestion_accepted','document.suggestion_rejected','document.suggestion_request_created','document.suggestion_request_started','document.suggestion_request_completed','document.suggestion_request_failed','document.suggestion_request_cancelled','document.suggestion_request_stale','room_scan.review_required','room_scan.approved','room_scan.rejected','room_scan.quantities_ready','technical_assignment.created','technical_assignment.lifecycle_changed','technical_assignment.statement_changed','technical_assignment.statement_reviewed','technical_assignment.open_item_changed','technical_assignment.readiness_requested','technical_assignment.approved','technical_assignment.cancelled','technical_assignment.revision_created','design_project.created','design_project.lifecycle_changed','design_project.decision_changed','design_project.decision_reviewed','design_project.open_item_changed','design_project.reference_added','design_project.readiness_requested','design_project.approved','design_project.cancelled','design_project.revision_created'));
ALTER TABLE notifications DROP CONSTRAINT notifications_entity_type_check;ALTER TABLE notifications ADD CONSTRAINT notifications_entity_type_check CHECK(entity_type IN('task','project','invoice','payment','expense','document','room_scan','technical_assignment','design_project'));
INSERT INTO permissions(code,description)VALUES('design_projects.create','Create design projects'),('design_projects.read','Read design projects'),('design_projects.edit','Edit design projects'),('design_projects.review','Review design decisions'),('design_projects.approve','Approve design projects'),('design_projects.cancel','Cancel design projects'),('design_projects.snapshots.read','Read approved design snapshots')ON CONFLICT DO NOTHING;
INSERT INTO role_permissions(role_id,permission_id)SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE(r.code IN('tenant_admin','project_manager')AND p.code LIKE'design_projects.%')OR(r.code='employee'AND p.code IN('design_projects.create','design_projects.read','design_projects.edit'))OR(r.code='read_only'AND p.code IN('design_projects.read','design_projects.snapshots.read'))ON CONFLICT DO NOTHING;
