CREATE TABLE room_scan_spatial_sessions(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,scan_id uuid NOT NULL,room_id uuid NOT NULL,
 mode text NOT NULL CHECK(mode IN('manual','calibrated_camera','web_xr','arkit','lidar','arcore','external_laser','test_adapter')),
 provider_type varchar(80) NOT NULL,coordinate_system varchar(80) NOT NULL,accuracy_class text NOT NULL CHECK(accuracy_class IN('verified_manual','verified_laser','lidar_high','spatial_standard','calibrated_camera','approximate','unsupported')),
 calibration_state text NOT NULL CHECK(calibration_state IN('not_required','required','complete','failed')),status text NOT NULL DEFAULT'active'CHECK(status IN('active','geometry_ready','review_required','completed','abandoned')),
 device_metadata jsonb NOT NULL DEFAULT'{}'CHECK(pg_column_size(device_metadata)<=8192),unsynced_count integer NOT NULL DEFAULT 0 CHECK(unsynced_count>=0),idempotency_key varchar(120) NOT NULL,
 version bigint NOT NULL DEFAULT 1 CHECK(version>0),started_at timestamptz NOT NULL DEFAULT now(),started_by uuid NOT NULL,resumed_at timestamptz,abandoned_at timestamptz,
 UNIQUE(tenant_id,id),UNIQUE(tenant_id,scan_id,id),UNIQUE(tenant_id,scan_id,idempotency_key),
 FOREIGN KEY(tenant_id,scan_id,room_id)REFERENCES room_scan_rooms(tenant_id,scan_id,id)ON DELETE CASCADE,FOREIGN KEY(tenant_id,started_by)REFERENCES users(tenant_id,id)
);
CREATE TABLE room_scan_spatial_points(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,scan_id uuid NOT NULL,room_id uuid NOT NULL,session_id uuid NOT NULL,point_order integer NOT NULL CHECK(point_order BETWEEN 0 AND 63),
 x_m numeric(20,8) NOT NULL,y_m numeric(20,8) NOT NULL,z_m numeric(20,8) NOT NULL,coordinate_system varchar(80) NOT NULL,
 uncertainty_m numeric(12,8) NOT NULL CHECK(uncertainty_m BETWEEN 0 AND 5),confidence numeric(5,4) NOT NULL CHECK(confidence BETWEEN 0 AND 1),tracking_quality text NOT NULL CHECK(tracking_quality IN('stable','limited','lost')),
 state text NOT NULL DEFAULT'proposed'CHECK(state IN('proposed','confirmed','rejected')),source_reference varchar(500),captured_at timestamptz NOT NULL,captured_by uuid NOT NULL,confirmed_at timestamptz,confirmed_by uuid,rejected_at timestamptz,rejected_by uuid,
 version bigint NOT NULL DEFAULT 1 CHECK(version>0),UNIQUE(tenant_id,id),UNIQUE(tenant_id,session_id,point_order),
 FOREIGN KEY(tenant_id,scan_id,room_id)REFERENCES room_scan_rooms(tenant_id,scan_id,id)ON DELETE CASCADE,FOREIGN KEY(tenant_id,scan_id,session_id)REFERENCES room_scan_spatial_sessions(tenant_id,scan_id,id)ON DELETE CASCADE,
 FOREIGN KEY(tenant_id,captured_by)REFERENCES users(tenant_id,id),FOREIGN KEY(tenant_id,confirmed_by)REFERENCES users(tenant_id,id),FOREIGN KEY(tenant_id,rejected_by)REFERENCES users(tenant_id,id)
);
CREATE TABLE room_scan_spatial_distances(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,scan_id uuid NOT NULL,room_id uuid NOT NULL,session_id uuid NOT NULL,start_point_id uuid NOT NULL,end_point_id uuid NOT NULL,
 purpose text NOT NULL CHECK(purpose IN('wall_length','wall_height','floor_edge','ceiling_edge','opening_width','opening_height','opening_depth','reveal_depth','custom_distance')),
 measured_distance_m numeric(20,8) NOT NULL CHECK(measured_distance_m>0),corrected_distance_m numeric(20,8) CHECK(corrected_distance_m>0),uncertainty_m numeric(12,8) NOT NULL CHECK(uncertainty_m BETWEEN 0 AND 5),
 accuracy_class text NOT NULL CHECK(accuracy_class IN('verified_manual','verified_laser','lidar_high','spatial_standard','calibrated_camera','approximate')),provider_type varchar(80) NOT NULL,
 state text NOT NULL DEFAULT'proposed'CHECK(state IN('proposed','confirmed','rejected','conflicted','superseded')),version bigint NOT NULL DEFAULT 1 CHECK(version>0),created_at timestamptz NOT NULL DEFAULT now(),created_by uuid NOT NULL,reviewed_at timestamptz,reviewed_by uuid,
 UNIQUE(tenant_id,id),FOREIGN KEY(tenant_id,scan_id,session_id)REFERENCES room_scan_spatial_sessions(tenant_id,scan_id,id)ON DELETE CASCADE,
 FOREIGN KEY(tenant_id,start_point_id)REFERENCES room_scan_spatial_points(tenant_id,id),FOREIGN KEY(tenant_id,end_point_id)REFERENCES room_scan_spatial_points(tenant_id,id),FOREIGN KEY(tenant_id,created_by)REFERENCES users(tenant_id,id),FOREIGN KEY(tenant_id,reviewed_by)REFERENCES users(tenant_id,id)
);
CREATE TABLE room_scan_geometry_revisions(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,scan_id uuid NOT NULL,room_id uuid NOT NULL,session_id uuid NOT NULL,revision_number integer NOT NULL CHECK(revision_number>0),
 coordinate_system varchar(80) NOT NULL,point_ids jsonb NOT NULL CHECK(jsonb_typeof(point_ids)='array'AND jsonb_array_length(point_ids)BETWEEN 3 AND 64),height_m numeric(12,8) NOT NULL CHECK(height_m>0),
 contour_closed boolean NOT NULL DEFAULT false,status text NOT NULL DEFAULT'draft'CHECK(status IN('draft','validated','reviewed','approved','superseded')),validation_result jsonb NOT NULL DEFAULT'{}',calculation_version varchar(80),calculated_at timestamptz,
 version bigint NOT NULL DEFAULT 1 CHECK(version>0),created_at timestamptz NOT NULL DEFAULT now(),created_by uuid NOT NULL,reviewed_at timestamptz,reviewed_by uuid,approved_at timestamptz,approved_by uuid,
 UNIQUE(tenant_id,id),UNIQUE(tenant_id,room_id,revision_number),FOREIGN KEY(tenant_id,scan_id,room_id)REFERENCES room_scan_rooms(tenant_id,scan_id,id)ON DELETE CASCADE,FOREIGN KEY(tenant_id,scan_id,session_id)REFERENCES room_scan_spatial_sessions(tenant_id,scan_id,id),
 FOREIGN KEY(tenant_id,created_by)REFERENCES users(tenant_id,id),FOREIGN KEY(tenant_id,reviewed_by)REFERENCES users(tenant_id,id),FOREIGN KEY(tenant_id,approved_by)REFERENCES users(tenant_id,id)
);
CREATE TABLE room_scan_spatial_walls(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,scan_id uuid NOT NULL,room_id uuid NOT NULL,geometry_revision_id uuid NOT NULL,wall_order integer NOT NULL CHECK(wall_order BETWEEN 0 AND 63),label varchar(120) NOT NULL,start_point_id uuid NOT NULL,end_point_id uuid NOT NULL,
 length_m numeric(20,8) NOT NULL CHECK(length_m>0),height_m numeric(20,8) NOT NULL CHECK(height_m>0),gross_area_m2 numeric(20,8) NOT NULL CHECK(gross_area_m2>0),plane jsonb NOT NULL DEFAULT'{}',review_state text NOT NULL DEFAULT'proposed'CHECK(review_state IN('proposed','confirmed','rejected')),
 version bigint NOT NULL DEFAULT 1 CHECK(version>0),UNIQUE(tenant_id,id),UNIQUE(tenant_id,geometry_revision_id,wall_order),FOREIGN KEY(tenant_id,geometry_revision_id)REFERENCES room_scan_geometry_revisions(tenant_id,id)ON DELETE CASCADE,FOREIGN KEY(tenant_id,start_point_id)REFERENCES room_scan_spatial_points(tenant_id,id),FOREIGN KEY(tenant_id,end_point_id)REFERENCES room_scan_spatial_points(tenant_id,id)
);
CREATE TABLE room_scan_spatial_openings(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,scan_id uuid NOT NULL,room_id uuid NOT NULL,geometry_revision_id uuid NOT NULL,wall_id uuid NOT NULL,
 opening_type text NOT NULL CHECK(opening_type IN('door','window','arch','technical_opening','other')),offset_m numeric(20,8) NOT NULL CHECK(offset_m>=0),width_m numeric(20,8) NOT NULL CHECK(width_m>0),height_m numeric(20,8) NOT NULL CHECK(height_m>0),sill_height_m numeric(20,8) NOT NULL DEFAULT 0 CHECK(sill_height_m>=0),reveal_depth_m numeric(20,8) CHECK(reveal_depth_m>=0),
 provider_type varchar(80) NOT NULL,uncertainty_m numeric(12,8) NOT NULL CHECK(uncertainty_m BETWEEN 0 AND 5),review_state text NOT NULL DEFAULT'proposed'CHECK(review_state IN('proposed','confirmed','rejected')),version bigint NOT NULL DEFAULT 1 CHECK(version>0),
 UNIQUE(tenant_id,id),FOREIGN KEY(tenant_id,geometry_revision_id)REFERENCES room_scan_geometry_revisions(tenant_id,id)ON DELETE CASCADE,FOREIGN KEY(tenant_id,wall_id)REFERENCES room_scan_spatial_walls(tenant_id,id)ON DELETE CASCADE
);
CREATE OR REPLACE FUNCTION validate_spatial_opening_geometry()RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE wall_length numeric;wall_height numeric;
BEGIN
 SELECT length_m,height_m INTO wall_length,wall_height FROM room_scan_spatial_walls WHERE tenant_id=NEW.tenant_id AND id=NEW.wall_id AND geometry_revision_id=NEW.geometry_revision_id;
 IF wall_length IS NULL THEN RAISE EXCEPTION'SPATIAL_OPENING_WALL_MISMATCH';END IF;
 IF NEW.offset_m+NEW.width_m>wall_length+0.001 OR NEW.sill_height_m+NEW.height_m>wall_height+0.001 THEN RAISE EXCEPTION'SPATIAL_OPENING_OUTSIDE_WALL';END IF;
 IF EXISTS(SELECT 1 FROM room_scan_spatial_openings x WHERE x.tenant_id=NEW.tenant_id AND x.geometry_revision_id=NEW.geometry_revision_id AND x.wall_id=NEW.wall_id AND x.id<>NEW.id AND x.review_state<>'rejected' AND greatest(x.offset_m,NEW.offset_m)<least(x.offset_m+x.width_m,NEW.offset_m+NEW.width_m) AND greatest(x.sill_height_m,NEW.sill_height_m)<least(x.sill_height_m+x.height_m,NEW.sill_height_m+NEW.height_m))THEN RAISE EXCEPTION'SPATIAL_OPENINGS_OVERLAP';END IF;
 RETURN NEW;
END$$;
CREATE TRIGGER validate_spatial_opening BEFORE INSERT OR UPDATE ON room_scan_spatial_openings FOR EACH ROW EXECUTE FUNCTION validate_spatial_opening_geometry();
CREATE TABLE room_scan_spatial_conflicts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,scan_id uuid NOT NULL,room_id uuid NOT NULL,session_id uuid NOT NULL,purpose text NOT NULL,candidate_ids jsonb NOT NULL CHECK(jsonb_typeof(candidate_ids)='array'),difference_m numeric(20,8) NOT NULL CHECK(difference_m>=0),tolerance_m numeric(20,8) NOT NULL CHECK(tolerance_m>=0),status text NOT NULL DEFAULT'open'CHECK(status IN('open','resolved')),resolution text CHECK(resolution IN('use_candidate','manual_correction','recapture')),selected_candidate_id uuid,resolved_at timestamptz,resolved_by uuid,version bigint NOT NULL DEFAULT 1,UNIQUE(tenant_id,id),FOREIGN KEY(tenant_id,scan_id,session_id)REFERENCES room_scan_spatial_sessions(tenant_id,scan_id,id)ON DELETE CASCADE,FOREIGN KEY(tenant_id,resolved_by)REFERENCES users(tenant_id,id));
CREATE TABLE room_scan_spatial_work_quantities(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,scan_id uuid NOT NULL,room_id uuid NOT NULL,geometry_revision_id uuid NOT NULL,quantity_type text NOT NULL,value numeric(20,8) NOT NULL CHECK(value>=0),unit text NOT NULL CHECK(unit IN('m','m2','m3')),formula_id varchar(160) NOT NULL,formula_version varchar(40) NOT NULL,input_entity_ids jsonb NOT NULL CHECK(jsonb_typeof(input_entity_ids)='array'),input_versions jsonb NOT NULL CHECK(jsonb_typeof(input_versions)='array'),calculator_version varchar(80) NOT NULL,explanation text NOT NULL,calculated_at timestamptz NOT NULL DEFAULT now(),validity_status text NOT NULL DEFAULT'valid'CHECK(validity_status IN('valid','invalidated','superseded')),version bigint NOT NULL DEFAULT 1,UNIQUE(tenant_id,id),UNIQUE(tenant_id,geometry_revision_id,quantity_type),FOREIGN KEY(tenant_id,geometry_revision_id)REFERENCES room_scan_geometry_revisions(tenant_id,id)ON DELETE CASCADE);
CREATE TABLE approved_spatial_room_snapshots(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,scan_id uuid NOT NULL,room_id uuid NOT NULL,geometry_revision_id uuid NOT NULL,content jsonb NOT NULL,content_fingerprint char(64) NOT NULL,calculation_version varchar(80) NOT NULL,approved_at timestamptz NOT NULL DEFAULT now(),approved_by uuid NOT NULL,UNIQUE(tenant_id,id),UNIQUE(tenant_id,geometry_revision_id),FOREIGN KEY(tenant_id,geometry_revision_id)REFERENCES room_scan_geometry_revisions(tenant_id,id),FOREIGN KEY(tenant_id,approved_by)REFERENCES users(tenant_id,id));
CREATE OR REPLACE FUNCTION protect_approved_spatial_snapshot()RETURNS trigger LANGUAGE plpgsql AS $$BEGIN RAISE EXCEPTION'APPROVED_SPATIAL_SNAPSHOT_IMMUTABLE';END$$;CREATE TRIGGER immutable_approved_spatial_snapshot BEFORE UPDATE OR DELETE ON approved_spatial_room_snapshots FOR EACH ROW EXECUTE FUNCTION protect_approved_spatial_snapshot();
DO $$DECLARE t text;BEGIN FOREACH t IN ARRAY ARRAY['room_scan_spatial_sessions','room_scan_spatial_points','room_scan_spatial_distances','room_scan_geometry_revisions','room_scan_spatial_walls','room_scan_spatial_openings','room_scan_spatial_conflicts','room_scan_spatial_work_quantities','approved_spatial_room_snapshots']LOOP EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',t);EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY',t);EXECUTE format('CREATE POLICY tenant_%I ON %I USING(tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)WITH CHECK(tenant_id=NULLIF(current_setting(''app.tenant_id'',true),'''')::uuid)',t,t);END LOOP;END$$;
CREATE INDEX idx_spatial_session_scan ON room_scan_spatial_sessions(tenant_id,scan_id,room_id,status);CREATE INDEX idx_spatial_point_session ON room_scan_spatial_points(tenant_id,session_id,point_order);CREATE INDEX idx_spatial_revision_room ON room_scan_geometry_revisions(tenant_id,room_id,revision_number DESC);CREATE INDEX idx_spatial_quantity_revision ON room_scan_spatial_work_quantities(tenant_id,geometry_revision_id,quantity_type);
