import type {AnalysisDocumentType,ExtractedField,TextPage} from "./analysis-types.js";
export const currencies=["PLN","EUR","USD","GBP","UAH"] as const;
export function normalizeDate(v:string){const m=v.match(/^(\d{2})[.\-/](\d{2})[.\-/](\d{4})$/),iso=v.match(/^(\d{4})-(\d{2})-(\d{2})$/);const y=Number(m?.[3]??iso?.[1]),mo=Number(m?.[2]??iso?.[2]),d=Number(m?.[1]??iso?.[3]),date=new Date(Date.UTC(y,mo-1,d));return y>=1900&&date.getUTCFullYear()===y&&date.getUTCMonth()===mo-1&&date.getUTCDate()===d?`${y}-${String(mo).padStart(2,"0")}-${String(d).padStart(2,"0")}`:null;}
export function normalizeAmount(v:string){let x=v.replace(/\s/g,"");if(/^\d{1,3}(\.\d{3})+,\d{2}$/.test(x))x=x.replace(/\./g,"").replace(",",".");else if(/^\d{1,3}(,\d{3})+\.\d{2}$/.test(x))x=x.replace(/,/g,"");else if(/^\d+,\d{2}$/.test(x))x=x.replace(",",".");return /^\d+(\.\d{1,2})?$/.test(x)?x:null;}
export function validIban(v:string){const x=v.replace(/\s/g,"").toUpperCase();if(!/^[A-Z]{2}\d{2}[A-Z0-9]{11,30}$/.test(x))return false;const moved=x.slice(4)+x.slice(0,4),digits=[...moved].map(c=>/[A-Z]/.test(c)?String(c.charCodeAt(0)-55):c).join("");let mod=0;for(const c of digits)mod=(mod*10+Number(c))%97;return mod===1;}
export function validNip(v:string){const x=v.replace(/\D/g,"");if(x.length!==10)return false;const w=[6,5,7,2,3,4,5,6,7];return w.reduce((s,n,i)=>s+n*Number(x[i]),0)%11===Number(x[9]);}
export const schemaFor=(t:AnalysisDocumentType)=>`${["invoice","contract","estimate"].includes(t)?t:"generic"}:v1`;
function provenanceAt(pages:TextPage[],start:number,end:number){const page=pages.find(p=>start>=p.startOffset&&end<=p.endOffset);return page?{pageId:page.pageId,startOffset:start-page.startOffset,endOffset:end-page.startOffset}:null;}
export function extractFields(type:AnalysisDocumentType,text:string,pages:TextPage[],maxFields:number,maxLength:number){const fields:ExtractedField[]=[];function add(name:string,m:RegExpMatchArray|null|undefined,rule:string,normalizer?:(v:string)=>string|null){if(!m||fields.length>=maxFields)return;const value=m[1].trim().slice(0,maxLength),normalized=normalizer?normalizer(value):value,start=(m.index??0)+m[0].indexOf(m[1]),provenance=provenanceAt(pages,start,start+value.length),valid=!normalizer||normalized!==null;if(!provenance)return;fields.push({name,value,normalizedValue:normalized,confidence:valid?.9:.35,source:"ocr_text",...provenance,extractionRule:rule,validationStatus:valid?"valid":"invalid"});}
 const number=text.match(/(?:invoice|faktura|contract|umowa|estimate|kosztorys|number|nr|№)\s*(?:no\.?|nr\.?|#|:)?\s*([A-Z0-9][A-Z0-9/.-]{1,40})/iu);add(type==="invoice"?"invoiceNumber":type==="contract"?"contractNumber":type==="estimate"?"estimateNumber":"documentNumber",number,"document-number-v1");
 add("issueDate",text.match(/(?:issue date|data wystawienia|дата|дата видачі)\s*:?\s*(\d{2}[.\-/]\d{2}[.\-/]\d{4}|\d{4}-\d{2}-\d{2})/iu),"issue-date-v1",normalizeDate);
 add("dueDate",text.match(/(?:due date|termin płatności|срок оплаты|термін оплати)\s*:?\s*(\d{2}[.\-/]\d{2}[.\-/]\d{4}|\d{4}-\d{2}-\d{2})/iu),"due-date-v1",normalizeDate);
 add("totalAmount",text.match(/(?:total|suma|razem|итого|всього)\s*:?\s*([0-9][0-9 .,'’]*[0-9])/iu),"total-v1",normalizeAmount);
 add("netAmount",text.match(/(?:net amount|netto|без ндс)\s*:?\s*([0-9][0-9 .,'’]*[0-9])/iu),"net-v1",normalizeAmount);
 add("taxAmount",text.match(/(?:tax amount|vat amount|kwota vat|ндс)\s*:?\s*([0-9][0-9 .,'’]*[0-9])/iu),"tax-v1",normalizeAmount);
 add("currency",text.match(/\b(PLN|EUR|USD|GBP|UAH)\b/iu),"currency-v1",v=>(currencies as readonly string[]).includes(v.toUpperCase())?v.toUpperCase():null);
 add("sellerName",text.match(/(?:seller|sprzedawca|продавец|продавець)\s*:?\s*([^\n]{1,200})/iu),"seller-name-v1");
 add("buyerName",text.match(/(?:buyer|nabywca|покупатель|покупець)\s*:?\s*([^\n]{1,200})/iu),"buyer-name-v1");
 add("sellerTaxId",text.match(/(?:seller\s+(?:nip|vat)|nip sprzedawcy)\s*:?\s*([0-9 -]{10,16})/iu),"seller-tax-v1",v=>validNip(v)?v.replace(/\D/g,""):null);
 add("buyerTaxId",text.match(/(?:buyer\s+(?:nip|vat)|nip nabywcy)\s*:?\s*([0-9 -]{10,16})/iu),"buyer-tax-v1",v=>validNip(v)?v.replace(/\D/g,""):null);
 add("iban",text.match(/\b([A-Z]{2}\d{2}(?: ?[A-Z0-9]){11,30})\b/u),"iban-v1",v=>validIban(v)?v.replace(/\s/g,"").toUpperCase():null);
 add("address",text.match(/(?:address|adres|адреса?)\s*:?\s*([^\n]{1,300})/iu),"address-v1");
 if(type==="invoice")add("paymentTerms",text.match(/(?:payment terms|warunki płatności|условия оплаты|умови оплати)\s*:?\s*([^\n]{1,200})/iu),"payment-terms-v1");
 if(type==="contract"){add("contractDate",text.match(/(?:contract date|data umowy|дата договор[ау])\s*:?\s*(\d{2}[.\-/]\d{2}[.\-/]\d{4}|\d{4}-\d{2}-\d{2})/iu),"contract-date-v1",normalizeDate);add("partyNames",text.match(/(?:parties|strony|сторони)\s*:?\s*([^\n]{1,400})/iu),"party-names-v1");add("effectiveDate",text.match(/(?:effective date|wchodzi w życie|дата набрання чинності)\s*:?\s*(\d{2}[.\-/]\d{2}[.\-/]\d{4}|\d{4}-\d{2}-\d{2})/iu),"effective-date-v1",normalizeDate);add("endDate",text.match(/(?:end date|data zakończenia|дата закінчення)\s*:?\s*(\d{2}[.\-/]\d{2}[.\-/]\d{4}|\d{4}-\d{2}-\d{2})/iu),"end-date-v1",normalizeDate);}
 if(type==="estimate")add("validUntil",text.match(/(?:valid until|ważna do|дійсна до)\s*:?\s*(\d{2}[.\-/]\d{2}[.\-/]\d{4}|\d{4}-\d{2}-\d{2})/iu),"valid-until-v1",normalizeDate);
 return fields;}
