import{createHash}from"node:crypto";
import{domainErrors}from"../errors.js";
import type{CompanyPriceResolution}from"../company-price-book/company-price-book-types.js";

export type PriceKind="labor"|"material"|"equipment"|"subcontractor"|"transport"|"disposal";
export type PriceEntry={id?:string;priceKind:PriceKind;referenceCode:string;unitCode:string;unitPrice:number;priceVariant?:string;rateType?:"unit"|"fixed"|"work_quantity";sourceReference:string;validFrom?:string|null;validTo?:string|null};
export type PercentRule={code:string;percent:number;condition?:string;mode?:"standard"|"reduced"|"zero"|"reverse_charge"};
export type Demand={demandKind:string;requirementCode:string;quantity:number;unitCode:string};
export type MaterialDemand={materialId:string;requirementCode:string;remainingQuantity:number;packageCount:number;unitCode:string;packageUnitCode?:string|null};
export type CompanyPriceComponent={entryKind:"labor"|"material";quantity:number;resolution:CompanyPriceResolution;requirementCode?:string;regionalComparison?:Record<string,unknown>};
export type CalculationInput={currency:string;workQuantity:number;workUnit:string;demands:Demand[];materials:MaterialDemand[];entries:PriceEntry[];overheadRules:PercentRule[];taxRule:PercentRule;marginRules:PercentRule[];discountRules:PercentRule[];adjustmentRules:PercentRule[];conditions?:string[];manualMarginPercent?:number;manualDiscountPercent?:number;overrideReason?:string;companyPriceComponents?:CompanyPriceComponent[]};

const money=(n:number)=>Number(n.toFixed(4));
const percent=(n:number,code:string)=>{if(!Number.isFinite(n)||n<0||n>100)throw domainErrors.validation("COMMERCIAL_RULE_PERCENT_INVALID",{code});return n/100};
function price(entries:PriceEntry[],kind:PriceKind,referenceCode:string,unitCode:string){const matches=entries.filter(x=>x.priceKind===kind&&x.referenceCode===referenceCode&&x.unitCode===unitCode);if(matches.length!==1)throw domainErrors.validation(matches.length?"REGIONAL_PRICE_AMBIGUOUS":"REGIONAL_PRICE_MISSING",{kind,referenceCode,unitCode});return matches[0]}
function component(entry:PriceEntry,quantity:number){const pricedQuantity=entry.rateType==="fixed"?1:quantity;return{amount:money(pricedQuantity*entry.unitPrice),trace:{priceEntryId:entry.id,kind:entry.priceKind,referenceCode:entry.referenceCode,unitCode:entry.unitCode,quantity:pricedQuantity,unitPrice:entry.unitPrice,rateType:entry.rateType??"unit",sourceReference:entry.sourceReference}}}
export function calculateCommercialEstimate(input:CalculationInput){
 if(!Number.isFinite(input.workQuantity)||input.workQuantity<=0)throw domainErrors.validation("ESTIMATE_WORK_QUANTITY_INVALID");
 if(input.companyPriceComponents){if(input.manualMarginPercent!==undefined||input.manualDiscountPercent!==undefined)throw domainErrors.validation("COMPANY_PRICE_ESTIMATE_OVERRIDE_UNSUPPORTED");if(!input.companyPriceComponents.length)throw domainErrors.validation("COMPANY_PRICE_NOT_FOUND");let labor=0,material=0,selling=0;const components=input.companyPriceComponents.map(component=>{if(!Number.isFinite(component.quantity)||component.quantity<=0)throw domainErrors.validation("COMPANY_PRICE_ESTIMATE_QUANTITY_INVALID");if(component.resolution.currency!==input.currency)throw domainErrors.validation("COMPANY_PRICE_CURRENCY_MISMATCH");const internalAmount=money(component.quantity*component.resolution.internalCost),sellingAmount=money(component.quantity*component.resolution.sellingPrice);if(component.entryKind==="labor")labor+=internalAmount;else material+=internalAmount;selling+=sellingAmount;return{entryKind:component.entryKind,quantity:component.quantity,internalAmount,sellingAmount,requirementCode:component.requirementCode??null,resolution:component.resolution,regionalComparison:component.regionalComparison??{available:false,reason:"NO_COMPATIBLE_REGIONAL_REFERENCE",mutated:false}}});labor=money(labor);material=money(material);const internalCost=money(labor+material),netTotal=money(selling),profit=money(netTotal-internalCost),marginPercent=netTotal?money(profit/netTotal*100):0;return{laborCost:labor,materialCost:material,equipmentCost:0,otherCost:0,overhead:0,internalCost,unitPrice:money(netTotal/input.workQuantity),netTotal,discountAmount:0,vatAmount:0,grossTotal:netTotal,profit,marginPercent,currency:input.currency,trace:{schemaVersion:"commercial-calculation-v2",pricingAuthority:"company_price_book_v1",components,regionalPricingRole:"comparison_only",tax:{code:"COMPANY_PRICE_BOOK_CLIENT_PRICE",percent:0,mode:"zero",appliedPercent:0},formula:"resolved company internal costs = internalCost; resolved company selling prices = net client price; profit = net client price - internalCost"}}}
 const traces:any[]=[];let labor=0,material=0,equipment=0,other=0;
 for(const d of input.demands){if(d.demandKind==="labor"){const c=component(price(input.entries,"labor",d.requirementCode,d.unitCode),d.quantity);labor+=c.amount;traces.push(c.trace)}else if(d.demandKind==="machine"){const c=component(price(input.entries,"equipment",d.requirementCode,d.unitCode),d.quantity);equipment+=c.amount;traces.push(c.trace)}}
 for(const m of input.materials){let e=input.entries.filter(x=>x.priceKind==="material"&&x.referenceCode===m.materialId);if(e.length!==1)throw domainErrors.validation(e.length?"REGIONAL_PRICE_AMBIGUOUS":"REGIONAL_PRICE_MISSING",{kind:"material",referenceCode:m.materialId});const entry=e[0],quantity=entry.unitCode==="PACKAGE"?m.packageCount:m.remainingQuantity;if(entry.unitCode!=="PACKAGE"&&entry.unitCode!==m.unitCode)throw domainErrors.validation("REGIONAL_PRICE_UNIT_MISMATCH",{referenceCode:m.materialId});const c=component(entry,quantity);material+=c.amount;traces.push({...c.trace,requirementCode:m.requirementCode})}
 for(const entry of input.entries.filter(x=>["subcontractor","transport","disposal"].includes(x.priceKind))){const quantity=entry.rateType==="work_quantity"?input.workQuantity:1,c=component(entry,quantity);other+=c.amount;traces.push(c.trace)}
 labor=money(labor);material=money(material);equipment=money(equipment);other=money(other);const direct=money(labor+material+equipment+other);
 const activeAdjustments=input.adjustmentRules.filter(x=>!x.condition||input.conditions?.includes(x.condition));const adjustmentAmount=money(activeAdjustments.reduce((s,r)=>s+direct*percent(r.percent,r.code),0));const overheadBase=money(direct+adjustmentAmount);const overhead=money(input.overheadRules.reduce((s,r)=>s+overheadBase*percent(r.percent,r.code),0));const internalCost=money(overheadBase+overhead);
 if((input.manualMarginPercent!==undefined||input.manualDiscountPercent!==undefined)&&!input.overrideReason?.trim())throw domainErrors.validation("COMMERCIAL_OVERRIDE_REASON_REQUIRED");
 const marginPercent=input.manualMarginPercent??input.marginRules[0]?.percent??0,discountPercent=input.manualDiscountPercent??input.discountRules.reduce((s,r)=>s+r.percent,0);if(marginPercent>=100)throw domainErrors.validation("COMMERCIAL_MARGIN_INVALID");percent(marginPercent,"margin");percent(discountPercent,"discount");const beforeDiscount=money(internalCost/(1-marginPercent/100));const discountAmount=money(beforeDiscount*discountPercent/100),netTotal=money(beforeDiscount-discountAmount);const taxPercent=["zero","reverse_charge"].includes(input.taxRule.mode??"standard")?0:input.taxRule.percent;percent(taxPercent,input.taxRule.code);const vatAmount=money(netTotal*taxPercent/100),grossTotal=money(netTotal+vatAmount),profit=money(netTotal-internalCost),actualMargin=netTotal?money(profit/netTotal*100):0;
 return{laborCost:labor,materialCost:material,equipmentCost:equipment,otherCost:money(other+adjustmentAmount),overhead,internalCost,unitPrice:money(netTotal/input.workQuantity),netTotal,discountAmount,vatAmount,grossTotal,profit,marginPercent:actualMargin,currency:input.currency,trace:{schemaVersion:"commercial-calculation-v1",components:traces,adjustments:activeAdjustments,overheadRules:input.overheadRules,margin:{percent:marginPercent,manual:input.manualMarginPercent!==undefined,overrideReason:input.overrideReason??null},discount:{percent:discountPercent,manual:input.manualDiscountPercent!==undefined,overrideReason:input.overrideReason??null},tax:{...input.taxRule,appliedPercent:taxPercent},formula:"direct + adjustments + overhead = internalCost; margin then discount = net; net + tax = gross"}};
}
export const fingerprintCommercial=(content:unknown)=>createHash("sha256").update(JSON.stringify(content)).digest("hex");
