import type {PoolClient} from "pg";
import type {CategoryListQuery,CreateCategory,CreateWorkItem,MoveCategory,PageResult,UpdateCategory,UpdateWorkItem,WorkCategory,WorkItem,WorkItemListQuery} from "../../domain/work-catalog/work-catalog-types.js";
const categorySelect=`id,tenant_id "tenantId",code,display_name "displayName",description,parent_id "parentId",hierarchy_level::int "hierarchyLevel",sort_order::int "sortOrder",status,is_system "isSystem",created_at "createdAt",updated_at "updatedAt",version::int`;
const itemSelect=`w.id,w.tenant_id "tenantId",w.code,w.display_name "displayName",w.short_description "shortDescription",w.detailed_description "detailedDescription",w.category_id "categoryId",c.display_name "categoryName",w.measurement_unit_id "measurementUnitId",u.code "measurementUnitCode",u.dimension "measurementDimension",w.status,w.is_system "isSystem",w.quantity_precision::int "quantityPrecision",w.internal_notes "internalNotes",w.created_at "createdAt",w.updated_at "updatedAt",w.version::int`;
const categorySort={code:"code",displayName:"display_name",sortOrder:"sort_order",status:"status",createdAt:"created_at",updatedAt:"updated_at"} as const;
const itemSort={code:"w.code",displayName:"w.display_name",category:"c.display_name",measurementUnit:"u.code",status:"w.status",createdAt:"w.created_at",updatedAt:"w.updated_at"} as const;
export class WorkCatalogRepository{
 findCategory(db:PoolClient,t:string,id:string){return db.query<WorkCategory>(`SELECT ${categorySelect} FROM work_categories WHERE tenant_id=$1 AND id=$2`,[t,id]).then(r=>r.rows[0]);}
 findItem(db:PoolClient,t:string,id:string){return db.query<WorkItem>(`SELECT ${itemSelect} FROM work_items w JOIN work_categories c ON c.tenant_id=w.tenant_id AND c.id=w.category_id JOIN measurement_units u ON u.tenant_id=w.tenant_id AND u.id=w.measurement_unit_id WHERE w.tenant_id=$1 AND w.id=$2`,[t,id]).then(r=>r.rows[0]);}
 findUnit(db:PoolClient,t:string,id:string){return db.query<{id:string;status:string}>(`SELECT id,status FROM measurement_units WHERE tenant_id=$1 AND id=$2`,[t,id]).then(r=>r.rows[0]);}
 async categoryList(db:PoolClient,t:string,q:CategoryListQuery):Promise<PageResult<WorkCategory>>{const v:any[]=[t],f=["tenant_id=$1"];if(q.search){v.push(`%${q.search}%`);f.push(`(code ILIKE $${v.length} OR display_name ILIKE $${v.length})`);}if(q.active!==undefined){v.push(q.active?"active":"inactive");f.push(`status=$${v.length}`);}if(q.parentId){v.push(q.parentId);f.push(`parent_id=$${v.length}`);}if(q.rootOnly)f.push("parent_id IS NULL");if(q.isSystem!==undefined){v.push(q.isSystem);f.push(`is_system=$${v.length}`);}const where=f.join(" AND "),total=Number((await db.query<{count:string}>(`SELECT count(*) FROM work_categories WHERE ${where}`,v)).rows[0].count);v.push(q.pageSize,(q.page-1)*q.pageSize);const d=q.sortOrder==="asc"?"ASC":"DESC",items=(await db.query<WorkCategory>(`SELECT ${categorySelect} FROM work_categories WHERE ${where} ORDER BY ${categorySort[q.sortBy]} ${d},id ${d} LIMIT $${v.length-1} OFFSET $${v.length}`,v)).rows;return {items,pagination:{page:q.page,pageSize:q.pageSize,total,totalPages:Math.ceil(total/q.pageSize)}};}
 tree(db:PoolClient,t:string){return db.query<WorkCategory>(`SELECT ${categorySelect} FROM work_categories WHERE tenant_id=$1 ORDER BY hierarchy_level,sort_order,code,id`,[t]).then(r=>r.rows);}
 createCategory(db:PoolClient,t:string,a:string,id:string,x:CreateCategory,level:number){return db.query<WorkCategory>(`INSERT INTO work_categories(id,tenant_id,code,display_name,description,parent_id,hierarchy_level,sort_order,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$9) RETURNING ${categorySelect}`,[id,t,x.code,x.displayName,x.description??null,x.parentId??null,level,x.sortOrder,a]).then(r=>r.rows[0]);}
 updateCategory(db:PoolClient,t:string,a:string,id:string,x:UpdateCategory){const m=[["displayName","display_name"],["description","description"],["sortOrder","sort_order"]] as const,s:string[]=[],v:any[]=[];for(const[k,c]of m)if(x[k]!==undefined){v.push(x[k]);s.push(`${c}=$${v.length}`);}if(!s.length)return this.findCategory(db,t,id);v.push(a,id,t,x.expectedVersion);return db.query<WorkCategory>(`UPDATE work_categories SET ${s.join(",")},updated_by=$${v.length-3},updated_at=now(),version=version+1 WHERE id=$${v.length-2} AND tenant_id=$${v.length-1} AND version=$${v.length} RETURNING ${categorySelect}`,v).then(r=>r.rows[0]);}
 async descendants(db:PoolClient,t:string,id:string){return (await db.query<{id:string;depth:number}>(`WITH RECURSIVE d AS (SELECT id,0 depth FROM work_categories WHERE tenant_id=$1 AND id=$2 UNION ALL SELECT c.id,d.depth+1 FROM work_categories c JOIN d ON c.parent_id=d.id WHERE c.tenant_id=$1 AND d.depth<3) SELECT id,depth FROM d`,[t,id])).rows;}
 moveCategory(db:PoolClient,t:string,a:string,id:string,x:MoveCategory,newLevel:number,delta:number){return db.query<WorkCategory>(`WITH RECURSIVE d AS (SELECT id FROM work_categories WHERE tenant_id=$1 AND id=$2 UNION ALL SELECT c.id FROM work_categories c JOIN d ON c.parent_id=d.id WHERE c.tenant_id=$1), changed AS (UPDATE work_categories c SET hierarchy_level=hierarchy_level+$3,updated_by=$4,updated_at=now(),version=CASE WHEN c.id=$2 THEN version+1 ELSE version END,parent_id=CASE WHEN c.id=$2 THEN $5::uuid ELSE parent_id END,sort_order=CASE WHEN c.id=$2 THEN COALESCE($6,sort_order) ELSE sort_order END FROM d WHERE c.tenant_id=$1 AND c.id=d.id AND (c.id<>$2 OR c.version=$7) RETURNING c.*) SELECT ${categorySelect} FROM changed WHERE id=$2`,[t,id,delta,a,x.parentId,x.sortOrder??null,x.expectedVersion]).then(r=>r.rows[0]);}
 blockers(db:PoolClient,t:string,id:string){return db.query<{children:string;items:string}>(`SELECT (SELECT count(*) FROM work_categories WHERE tenant_id=$1 AND parent_id=$2 AND status='active') children,(SELECT count(*) FROM work_items WHERE tenant_id=$1 AND category_id=$2 AND status='active') items`,[t,id]).then(r=>r.rows[0]);}
 setCategoryStatus(db:PoolClient,t:string,a:string,id:string,status:string,version:number){return db.query<WorkCategory>(`UPDATE work_categories SET status=$1,updated_by=$2,updated_at=now(),version=version+1 WHERE tenant_id=$3 AND id=$4 AND version=$5 RETURNING ${categorySelect}`,[status,a,t,id,version]).then(r=>r.rows[0]);}
 async itemList(db:PoolClient,t:string,q:WorkItemListQuery):Promise<PageResult<WorkItem>>{const v:any[]=[t],f=["w.tenant_id=$1"];if(q.search){v.push(`%${q.search}%`);f.push(`(w.code ILIKE $${v.length} OR w.display_name ILIKE $${v.length} OR w.short_description ILIKE $${v.length})`);}for(const[k,c]of [["categoryId","w.category_id"],["measurementUnitId","w.measurement_unit_id"],["dimension","u.dimension"]] as const)if(q[k]){v.push(q[k]);f.push(`${c}=$${v.length}`);}if(q.active!==undefined){v.push(q.active?"active":"inactive");f.push(`w.status=$${v.length}`);}if(q.isSystem!==undefined){v.push(q.isSystem);f.push(`w.is_system=$${v.length}`);}const joins="work_items w JOIN work_categories c ON c.tenant_id=w.tenant_id AND c.id=w.category_id JOIN measurement_units u ON u.tenant_id=w.tenant_id AND u.id=w.measurement_unit_id",where=f.join(" AND "),total=Number((await db.query<{count:string}>(`SELECT count(*) FROM ${joins} WHERE ${where}`,v)).rows[0].count);v.push(q.pageSize,(q.page-1)*q.pageSize);const d=q.sortOrder==="asc"?"ASC":"DESC",items=(await db.query<WorkItem>(`SELECT ${itemSelect} FROM ${joins} WHERE ${where} ORDER BY ${itemSort[q.sortBy]} ${d},w.id ${d} LIMIT $${v.length-1} OFFSET $${v.length}`,v)).rows;return {items,pagination:{page:q.page,pageSize:q.pageSize,total,totalPages:Math.ceil(total/q.pageSize)}};}
 createItem(db:PoolClient,t:string,a:string,id:string,x:CreateWorkItem){return db.query<WorkItem>(`WITH inserted AS (INSERT INTO work_items(id,tenant_id,code,display_name,short_description,detailed_description,category_id,measurement_unit_id,quantity_precision,internal_notes,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$11) RETURNING *) SELECT ${itemSelect} FROM inserted w JOIN work_categories c ON c.tenant_id=w.tenant_id AND c.id=w.category_id JOIN measurement_units u ON u.tenant_id=w.tenant_id AND u.id=w.measurement_unit_id`,[id,t,x.code,x.displayName,x.shortDescription??null,x.detailedDescription??null,x.categoryId,x.measurementUnitId,x.quantityPrecision,x.internalNotes??null,a]).then(r=>r.rows[0]);}
 updateItem(db:PoolClient,t:string,a:string,id:string,x:UpdateWorkItem){const m=[["displayName","display_name"],["shortDescription","short_description"],["detailedDescription","detailed_description"],["categoryId","category_id"],["measurementUnitId","measurement_unit_id"],["quantityPrecision","quantity_precision"],["internalNotes","internal_notes"]] as const,s:string[]=[],v:any[]=[];for(const[k,c]of m)if(x[k]!==undefined){v.push(x[k]);s.push(`${c}=$${v.length}`);}if(!s.length)return this.findItem(db,t,id);v.push(a,id,t,x.expectedVersion);return db.query<WorkItem>(`WITH updated AS (UPDATE work_items SET ${s.join(",")},updated_by=$${v.length-3},updated_at=now(),version=version+1 WHERE id=$${v.length-2} AND tenant_id=$${v.length-1} AND version=$${v.length} RETURNING *) SELECT ${itemSelect} FROM updated w JOIN work_categories c ON c.tenant_id=w.tenant_id AND c.id=w.category_id JOIN measurement_units u ON u.tenant_id=w.tenant_id AND u.id=w.measurement_unit_id`,v).then(r=>r.rows[0]);}
 setItemStatus(db:PoolClient,t:string,a:string,id:string,status:string,version:number){return db.query<WorkItem>(`WITH updated AS (UPDATE work_items SET status=$1,updated_by=$2,updated_at=now(),version=version+1 WHERE tenant_id=$3 AND id=$4 AND version=$5 RETURNING *) SELECT ${itemSelect} FROM updated w JOIN work_categories c ON c.tenant_id=w.tenant_id AND c.id=w.category_id JOIN measurement_units u ON u.tenant_id=w.tenant_id AND u.id=w.measurement_unit_id`,[status,a,t,id,version]).then(r=>r.rows[0]);}
}
