import type {PoolClient} from "pg";
import type {CreateTaskCommand,Task,TaskListQuery,TaskListResult,TaskStatus,UpdateTaskCommand} from "../../domain/task/task-types.js";

const select=`t.id,t.tenant_id AS "tenantId",t.project_id AS "projectId",t.title,t.description,t.status,t.priority,t.due_date::text AS "dueDate",t.started_at AS "startedAt",t.completed_at AS "completedAt",(t.due_date<current_date AND t.status NOT IN ('completed','accepted','cancelled','archived')) AS "isOverdue",COALESCE((SELECT json_agg(json_build_object('userId',ta.user_id,'displayName',u.display_name,'assignedAt',ta.assigned_at) ORDER BY u.display_name) FROM task_assignments ta JOIN users u ON u.id=ta.user_id AND u.tenant_id=ta.tenant_id WHERE ta.task_id=t.id AND ta.tenant_id=t.tenant_id),'[]'::json) AS assignees,(SELECT json_build_object('id',re.id,'action',re.action,'comment',re.comment,'taskVersion',re.task_version,'createdAt',re.created_at,'createdBy',re.created_by) FROM task_review_events re WHERE re.tenant_id=t.tenant_id AND re.task_id=t.id ORDER BY re.created_at DESC,re.id DESC LIMIT 1) AS "lastReview",t.version::int,t.created_at AS "createdAt",t.updated_at AS "updatedAt",t.deleted_at AS "archivedAt"`;
const sortColumns={title:"t.title",status:"t.status",priority:"t.priority",dueDate:"t.due_date",createdAt:"t.created_at",updatedAt:"t.updated_at"} as const;
export class TaskRepository {
  async findById(db:PoolClient,tenantId:string,id:string):Promise<Task|undefined>{return (await db.query<Task>(`SELECT ${select} FROM tasks t WHERE t.id=$1 AND t.tenant_id=$2`,[id,tenantId])).rows[0];}
  async findProject(db:PoolClient,tenantId:string,id:string){return (await db.query<{id:string;status:string;projectManagerId:string|null;startDate:string|null;expectedCompletionDate:string|null;archivedAt:string|null}>("SELECT id,status,project_manager_id AS \"projectManagerId\",start_date::text AS \"startDate\",expected_completion_date::text AS \"expectedCompletionDate\",deleted_at AS \"archivedAt\" FROM projects WHERE id=$1 AND tenant_id=$2",[id,tenantId])).rows[0];}
  async findUser(db:PoolClient,tenantId:string,id:string){return (await db.query<{id:string}>("SELECT id FROM users WHERE id=$1 AND tenant_id=$2 AND deleted_at IS NULL AND is_disabled=false",[id,tenantId])).rows[0];}
  async hasAssignment(db:PoolClient,tenantId:string,taskId:string,userId:string){return Boolean((await db.query("SELECT 1 FROM task_assignments WHERE tenant_id=$1 AND task_id=$2 AND user_id=$3",[tenantId,taskId,userId])).rowCount);}
  async create(db:PoolClient,tenantId:string,actorId:string,id:string,input:CreateTaskCommand):Promise<Task>{await db.query("INSERT INTO tasks(id,tenant_id,project_id,title,description,priority,due_date,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$8)",[id,tenantId,input.projectId,input.title,input.description??null,input.priority??"normal",input.dueDate??null,actorId]);return (await this.findById(db,tenantId,id))!;}
  async list(db:PoolClient,tenantId:string,q:TaskListQuery):Promise<TaskListResult>{const values:any[]=[tenantId];const filters=["t.tenant_id=$1"];
    if(q.search){values.push(`%${q.search}%`);filters.push(`(t.title ILIKE $${values.length} OR t.description ILIKE $${values.length})`);}if(q.status){values.push(q.status);filters.push(`t.status=$${values.length}`);}if(q.priority){values.push(q.priority);filters.push(`t.priority=$${values.length}`);}if(q.projectId){values.push(q.projectId);filters.push(`t.project_id=$${values.length}`);}if(q.propertyId){values.push(q.propertyId);filters.push(`p.property_id=$${values.length}`);}if(q.clientId){values.push(q.clientId);filters.push(`p.client_id=$${values.length}`);}if(q.assigneeId){values.push(q.assigneeId);filters.push(`EXISTS(SELECT 1 FROM task_assignments filter_ta WHERE filter_ta.task_id=t.id AND filter_ta.tenant_id=t.tenant_id AND filter_ta.user_id=$${values.length})`);}if(q.overdue!==undefined)filters.push(q.overdue?`(t.due_date<current_date AND t.status NOT IN ('completed','accepted','cancelled','archived'))`:`(t.due_date IS NULL OR t.due_date>=current_date OR t.status IN ('completed','accepted','cancelled','archived'))`);
    const where=filters.join(" AND "),from="tasks t JOIN projects p ON p.id=t.project_id AND p.tenant_id=t.tenant_id";const total=Number((await db.query<{count:string}>(`SELECT count(*) FROM ${from} WHERE ${where}`,values)).rows[0].count);values.push(q.pageSize,(q.page-1)*q.pageSize);const items=(await db.query<Task>(`SELECT ${select} FROM ${from} WHERE ${where} ORDER BY ${sortColumns[q.sortBy]} ${q.sortOrder==="asc"?"ASC":"DESC"} NULLS LAST LIMIT $${values.length-1} OFFSET $${values.length}`,values)).rows;return {items,pagination:{page:q.page,pageSize:q.pageSize,total,totalPages:Math.ceil(total/q.pageSize)}};
  }
  async update(db:PoolClient,tenantId:string,actorId:string,id:string,input:UpdateTaskCommand):Promise<Task|undefined>{const fields:{key:keyof UpdateTaskCommand;column:string}[]=[{key:"projectId",column:"project_id"},{key:"title",column:"title"},{key:"description",column:"description"},{key:"priority",column:"priority"},{key:"dueDate",column:"due_date"}];const set:string[]=[];const values:any[]=[];for(const field of fields)if(input[field.key]!==undefined){values.push(input[field.key]);set.push(`${field.column}=$${values.length}`);}if(!set.length)return this.findById(db,tenantId,id);values.push(actorId,id,tenantId,input.expectedVersion);const changed=await db.query(`UPDATE tasks SET ${set.join(",")},updated_by=$${values.length-3},updated_at=now(),version=version+1 WHERE id=$${values.length-2} AND tenant_id=$${values.length-1} AND version=$${values.length} AND deleted_at IS NULL RETURNING id`,values);if(!changed.rowCount)return undefined;return this.findById(db,tenantId,id);}
  async transition(db:PoolClient,tenantId:string,actorId:string,id:string,expectedVersion:number,from:TaskStatus,to:TaskStatus):Promise<Task|undefined>{const changed=await db.query(`UPDATE tasks SET status=$1,started_at=CASE WHEN $1='in_progress' AND started_at IS NULL THEN now() ELSE started_at END,completed_at=CASE WHEN $1 IN('completed','accepted') THEN now() ELSE NULL END,updated_by=$2,updated_at=now(),version=version+1 WHERE id=$3 AND tenant_id=$4 AND version=$5 AND status=$6 AND deleted_at IS NULL RETURNING id`,[to,actorId,id,tenantId,expectedVersion,from]);if(!changed.rowCount)return undefined;return this.findById(db,tenantId,id);}
  async addReviewEvent(db:PoolClient,tenantId:string,taskId:string,actorId:string,action:"submitted_for_review"|"accepted"|"returned",comment:string|null,taskVersion:number){await db.query("INSERT INTO task_review_events(tenant_id,task_id,action,comment,task_version,created_by)VALUES($1,$2,$3,$4,$5,$6)",[tenantId,taskId,action,comment,taskVersion,actorId]);}
  async archive(db:PoolClient,tenantId:string,actorId:string,id:string,expectedVersion:number):Promise<Task|undefined>{const changed=await db.query("UPDATE tasks SET status='archived',completed_at=NULL,deleted_at=now(),deleted_by=$1,updated_by=$1,updated_at=now(),version=version+1 WHERE id=$2 AND tenant_id=$3 AND version=$4 AND deleted_at IS NULL RETURNING id",[actorId,id,tenantId,expectedVersion]);if(!changed.rowCount)return undefined;return this.findById(db,tenantId,id);}
  async assign(db:PoolClient,tenantId:string,actorId:string,taskId:string,userId:string,expectedVersion:number):Promise<Task|undefined>{const changed=await db.query("UPDATE tasks SET updated_by=$1,updated_at=now(),version=version+1 WHERE id=$2 AND tenant_id=$3 AND version=$4 AND deleted_at IS NULL RETURNING id",[actorId,taskId,tenantId,expectedVersion]);if(!changed.rowCount)return undefined;await db.query("INSERT INTO task_assignments(tenant_id,task_id,user_id,assigned_by) VALUES($1,$2,$3,$4)",[tenantId,taskId,userId,actorId]);return this.findById(db,tenantId,taskId);}
  async unassign(db:PoolClient,tenantId:string,actorId:string,taskId:string,userId:string,expectedVersion:number):Promise<Task|undefined>{const changed=await db.query("UPDATE tasks SET updated_by=$1,updated_at=now(),version=version+1 WHERE id=$2 AND tenant_id=$3 AND version=$4 AND deleted_at IS NULL RETURNING id",[actorId,taskId,tenantId,expectedVersion]);if(!changed.rowCount)return undefined;await db.query("DELETE FROM task_assignments WHERE tenant_id=$1 AND task_id=$2 AND user_id=$3",[tenantId,taskId,userId]);return this.findById(db,tenantId,taskId);}
}
