import type{PoolClient}from"pg";
import type{CreateTaskProblem,TaskProblem,TaskProblemStatus}from"../../domain/task/task-problem-types.js";
const select=`id,tenant_id AS "tenantId",project_id AS "projectId",task_id AS "taskId",category,description,location,status,version::int,created_at AS "createdAt",created_by AS "createdBy",updated_at AS "updatedAt",updated_by AS "updatedBy"`;
const selectR=`r.id,r.tenant_id AS "tenantId",r.project_id AS "projectId",r.task_id AS "taskId",r.category,r.description,r.location,r.status,r.version::int,r.created_at AS "createdAt",r.created_by AS "createdBy",r.updated_at AS "updatedAt",r.updated_by AS "updatedBy"`;
export class TaskProblemRepository{
 async task(db:PoolClient,tenantId:string,taskId:string){return(await db.query<{id:string;projectId:string;projectManagerId:string|null;archivedAt:string|null;assigned:boolean}>(`SELECT t.id,t.project_id AS "projectId",p.project_manager_id AS "projectManagerId",t.deleted_at AS "archivedAt",EXISTS(SELECT 1 FROM task_assignments a WHERE a.tenant_id=t.tenant_id AND a.task_id=t.id AND a.user_id=NULLIF(current_setting('app.user_id',true),'')::uuid)assigned FROM tasks t JOIN projects p ON p.tenant_id=t.tenant_id AND p.id=t.project_id WHERE t.tenant_id=$1 AND t.id=$2`,[tenantId,taskId])).rows[0]}
 async create(db:PoolClient,tenantId:string,actorId:string,taskId:string,projectId:string,id:string,input:CreateTaskProblem){return(await db.query<TaskProblem>(`INSERT INTO task_field_reports(id,tenant_id,project_id,task_id,category,description,location,created_by,updated_by)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$8)RETURNING ${select}`,[id,tenantId,projectId,taskId,input.category,input.description,input.location??null,actorId])).rows[0]}
 async list(db:PoolClient,tenantId:string,filters:{taskId?:string;projectId?:string;status?:TaskProblemStatus},actorId:string,all:boolean){const values:unknown[]=[tenantId],where=["r.tenant_id=$1"];if(filters.taskId){values.push(filters.taskId);where.push(`r.task_id=$${values.length}`)}if(filters.projectId){values.push(filters.projectId);where.push(`r.project_id=$${values.length}`)}if(filters.status){values.push(filters.status);where.push(`r.status=$${values.length}`)}if(!all){values.push(actorId);where.push(`(r.created_by=$${values.length} OR EXISTS(SELECT 1 FROM task_assignments a WHERE a.tenant_id=r.tenant_id AND a.task_id=r.task_id AND a.user_id=$${values.length}))`)}return(await db.query<TaskProblem>(`SELECT ${selectR} FROM task_field_reports r WHERE ${where.join(" AND ")} ORDER BY r.created_at DESC`,values)).rows}
 async find(db:PoolClient,tenantId:string,id:string){return(await db.query<TaskProblem>(`SELECT ${select} FROM task_field_reports WHERE tenant_id=$1 AND id=$2`,[tenantId,id])).rows[0]}
 async update(db:PoolClient,tenantId:string,actorId:string,id:string,version:number,status:TaskProblemStatus){return(await db.query<TaskProblem>(`UPDATE task_field_reports SET status=$1,version=version+1,updated_at=now(),updated_by=$2 WHERE tenant_id=$3 AND id=$4 AND version=$5 RETURNING ${select}`,[status,actorId,tenantId,id,version])).rows[0]}
}
