import {randomUUID} from "node:crypto";
import type {Pool,PoolClient} from "pg";
import {assertCanCreateNormCatalog,assertCanReadNormCatalog,assertCanUpdateNormCatalog} from "../../authorization/norm-catalog-policy.js";
import {DomainError,domainErrors} from "../../domain/errors.js";
import {validateNormCreate,validateNormItemCreate,validateNormItemUpdate,validateNormUpdate} from "../../domain/norm-catalog/norm-catalog-rules.js";
import type {ConstructionNormItemQuery,ConstructionNormQuery,CreateConstructionNorm,CreateConstructionNormItem,UpdateConstructionNorm,UpdateConstructionNormItem} from "../../domain/norm-catalog/norm-catalog-types.js";
import {NormCatalogRepository} from "../../infrastructure/norm-catalog/norm-catalog-repository.js";
import {inTenantTransaction} from "../../infrastructure/transaction.js";
export type NormCatalogActor={id:string;tenantId:string;permissions:readonly string[];correlationId:string};
export class NormCatalogService{
 constructor(private pool:Pool,private repo=new NormCatalogRepository()){}
 private audit(db:PoolClient,a:NormCatalogActor,entity:string,action:string,id:string,metadata:Record<string,unknown>){return db.query("INSERT INTO audit_logs(tenant_id,actor_id,action,entity_type,entity_id,correlation_id,metadata) VALUES($1,$2,$3,$4,$5,$6,$7)",[a.tenantId,a.id,action,entity,id,/^[0-9a-f-]{36}$/i.test(a.correlationId)?a.correlationId:randomUUID(),metadata]);}
 private async work(db:PoolClient,a:NormCatalogActor,id:string){const x=await this.repo.findWork(db,a.tenantId,id);if(!x)throw domainErrors.notFound();if(x.status!=="active")throw new DomainError("INVALID_RELATIONSHIP",422,"Work item must be active");return x;}
 private async itemReferences(db:PoolClient,a:NormCatalogActor,normId:string,materialId:string,unitId:string){const norm=await this.repo.findNorm(db,a.tenantId,normId),material=await this.repo.findMaterial(db,a.tenantId,materialId),unit=await this.repo.findUnit(db,a.tenantId,unitId);if(!norm||!material||!unit)throw domainErrors.notFound();if(norm.status!=="active"||material.status!=="active"||unit.status!=="active")throw new DomainError("INVALID_RELATIONSHIP",422,"Norm, material, and measurement unit must be active");if(material.measurementUnitId!==unitId)throw new DomainError("INVALID_RELATIONSHIP",422,"Measurement unit must match the material catalog unit");}
 norms(a:NormCatalogActor,q:ConstructionNormQuery){assertCanReadNormCatalog(a);return inTenantTransaction(this.pool,a.tenantId,db=>this.repo.norms(db,a.tenantId,q));}
 getNorm(a:NormCatalogActor,id:string){assertCanReadNormCatalog(a);return inTenantTransaction(this.pool,a.tenantId,async db=>{const x=await this.repo.findNorm(db,a.tenantId,id);if(!x)throw domainErrors.notFound();return x;});}
 async createNorm(a:NormCatalogActor,input:CreateConstructionNorm){assertCanCreateNormCatalog(a);const x=validateNormCreate(input);try{return await inTenantTransaction(this.pool,a.tenantId,async db=>{await this.work(db,a,x.workId);const created=await this.repo.createNorm(db,a.tenantId,a.id,randomUUID(),x);await this.audit(db,a,"construction_norm","construction_norm.created",created.id,{code:created.code,workId:created.workId,newVersion:created.version});return created;});}catch(e:any){if(e?.code==="23505")throw domainErrors.duplicate("Construction norm code already exists");throw e;}}
 updateNorm(a:NormCatalogActor,id:string,input:UpdateConstructionNorm){assertCanUpdateNormCatalog(a);const x=validateNormUpdate(input);return inTenantTransaction(this.pool,a.tenantId,async db=>{const current=await this.repo.findNorm(db,a.tenantId,id);if(!current)throw domainErrors.notFound();if(current.version!==x.expectedVersion)throw domainErrors.conflict();if(x.workId)await this.work(db,a,x.workId);const updated=await this.repo.updateNorm(db,a.tenantId,a.id,id,x);if(!updated)throw domainErrors.conflict();await this.audit(db,a,"construction_norm","construction_norm.updated",id,{previousVersion:current.version,newVersion:updated.version,changes:x});return updated;});}
 status(a:NormCatalogActor,id:string,status:"active"|"inactive",version:number){assertCanUpdateNormCatalog(a);return inTenantTransaction(this.pool,a.tenantId,async db=>{const current=await this.repo.findNorm(db,a.tenantId,id);if(!current)throw domainErrors.notFound();if(current.version!==version)throw domainErrors.conflict();if(current.status===status)throw domainErrors.transition();if(status==="inactive"&&await this.repo.itemCount(db,a.tenantId,id))throw new DomainError("INVALID_RELATIONSHIP",422,"Delete norm items before deactivating the norm");if(status==="active")await this.work(db,a,current.workId);const updated=await this.repo.setStatus(db,a.tenantId,a.id,id,status,version);if(!updated)throw domainErrors.conflict();await this.audit(db,a,"construction_norm",`construction_norm.${status==="active"?"activated":"deactivated"}`,id,{previousVersion:version,newVersion:updated.version});return updated;});}
 items(a:NormCatalogActor,q:ConstructionNormItemQuery){assertCanReadNormCatalog(a);return inTenantTransaction(this.pool,a.tenantId,db=>this.repo.items(db,a.tenantId,q));}
 getItem(a:NormCatalogActor,id:string){assertCanReadNormCatalog(a);return inTenantTransaction(this.pool,a.tenantId,async db=>{const x=await this.repo.findItem(db,a.tenantId,id);if(!x)throw domainErrors.notFound();return x;});}
 async createItem(a:NormCatalogActor,input:CreateConstructionNormItem){assertCanCreateNormCatalog(a);const x=validateNormItemCreate(input);try{return await inTenantTransaction(this.pool,a.tenantId,async db=>{await this.itemReferences(db,a,x.normId,x.materialId,x.measurementUnitId);const created=await this.repo.createItem(db,a.tenantId,a.id,randomUUID(),x);await this.audit(db,a,"construction_norm_item","construction_norm_item.created",created.id,{normId:created.normId,materialId:created.materialId,newVersion:created.version});return created;});}catch(e:any){if(e?.code==="23505")throw domainErrors.duplicate("Material already exists in this construction norm");throw e;}}
 updateItem(a:NormCatalogActor,id:string,input:UpdateConstructionNormItem){assertCanUpdateNormCatalog(a);const x=validateNormItemUpdate(input);return inTenantTransaction(this.pool,a.tenantId,async db=>{const current=await this.repo.findItem(db,a.tenantId,id);if(!current)throw domainErrors.notFound();if(current.version!==x.expectedVersion)throw domainErrors.conflict();if(x.measurementUnitId)await this.itemReferences(db,a,current.normId,current.materialId,x.measurementUnitId);const updated=await this.repo.updateItem(db,a.tenantId,a.id,id,x);if(!updated)throw domainErrors.conflict();await this.audit(db,a,"construction_norm_item","construction_norm_item.updated",id,{previousVersion:current.version,newVersion:updated.version,changes:x});return updated;});}
 deleteItem(a:NormCatalogActor,id:string,version:number){assertCanUpdateNormCatalog(a);return inTenantTransaction(this.pool,a.tenantId,async db=>{const current=await this.repo.findItem(db,a.tenantId,id);if(!current)throw domainErrors.notFound();if(current.version!==version)throw domainErrors.conflict();const deleted=await this.repo.deleteItem(db,a.tenantId,id,version);if(!deleted)throw domainErrors.conflict();await this.audit(db,a,"construction_norm_item","construction_norm_item.deleted",id,{previousVersion:version});return {id};});}
}
