import { defineLocale } from "../types";
export default defineLocale({
  a11y:["Skip to content","OMNIRO home","Primary navigation","Mobile navigation","Open navigation","Close navigation","Language","Choose language","Platform principles","OMNIRO system connecting projects, finance, documents, building, analytics and AI agents","Specialized AI agent ecosystem","Command center presentation states","Fragmented business information converging into OMNIRO","Built operational foundation","Presentation preview of specialized AI agents coordinated by OMNIRO Core","OMNIRO AI Agents ecosystem","Reality to analytics decision chain","Abstract European expansion network","OMNIRO expansion architecture","portrait"],
  nav:["Platform","OMNIRO Building","Technology","Investors","Roadmap","Contact","Explore OMNIRO"],
  hero:["AI BUSINESS OPERATING SYSTEM","The Operating System for the","AI-Powered Business","OMNIRO connects projects, people, finance, documents, construction data and artificial intelligence into one intelligent operating system.","Explore the Platform","Investor Relations","Operational foundation","Human authority","European vision","Discover the system","Specialized intelligence","Connected","Governed","Evidence-linked","Projects","Finance","Documents","Building","Analytics","AI Agents","Financial control","Risk signals"],
  problem:["THE PROBLEM","Business is fragmented. Intelligence should not be.","Critical work is scattered across tools, inboxes, spreadsheets and individual memory. Context disappears between departments. Decisions arrive late.","CONNECTED TRUTH"],
  fragments:["Projects","Spreadsheets","Documents","Messages","Finance","Workers","Clients","Suppliers"],
  platform:["THE PLATFORM","One company. One source of truth. One intelligent system.","A shared operational layer where every module understands the same business context."],
  modules:[["Projects","Live delivery context","CONNECTED"],["Finance","Connected financial truth","GOVERNED"],["Documents","Knowledge in motion","TRACEABLE"],["People","Roles, decisions, authority","ALIGNED"],["Analytics","Signals made actionable","EXPLAINED"],["Automation","Controlled intelligent workflows","ORCHESTRATED"]],
  building:["Built in construction. Designed for business.","Our first operational vertical turns real project evidence into governed, explainable decisions — while the wider platform continues to evolve.","Operational vertical","Connected foundations","Market focus","CAPABILITY MAP","Construction Intelligence","ACTIVE FOUNDATION","Being developed","Platform architecture","Planned capability"],
  capabilities:[["Project Management","Built"],["Room Scanner","Built"],["Work Scope","Built"],["Technology & Engineering Norms","Built"],["AI Cost Estimation","Being developed"],["Materials","Platform architecture"],["Procurement","Planned capability"],["Budget Control","Planned capability"],["Client Collaboration","Planned capability"],["Risk Intelligence","Planned capability"]],
  command:["AI COMMAND CENTER","Intelligence coordinated, not fragmented.","A governed orchestration layer designed to coordinate specialized intelligence around real business state — never to invent authority.","CONCEPT PREVIEW","System architecture online","COORDINATION LAYER","ACTIVE PROJECTS","Connected context","FINANCIAL CONTROL","Governed inputs","AI INSIGHTS","Evidence-linked","Concept state","UPCOMING DEADLINES","Authority aware","No live data","RISKS & DELAYS","Review required","Presentation UI","SYSTEM HEALTH","Architecture online","Modules connected","PRESENTATION UI · NO LIVE COMPANY DATA","OMNIRO AI AGENTS","Specialized intelligence. One coordinated system.","CONCEPT ARCHITECTURE","SPECIALIZED AGENT"],
  agents:[["Contracts & Compliance","Architecture",["Contract analysis","Claims & disputes","Risk & compliance","Legal alerts"]],["Budget & Cash Flow","In Development",["Budget control","Cash flow","Cost tracking","Financial reporting"]],["Costs & Takeoff","In Development",["Quantity takeoff","Cost estimation","BOQ preparation","Margin control"]],["Schedule & Progress","Architecture",["Project planning","Progress tracking","Schedule control","Issue management"]],["Materials & Suppliers","Planned",["Material planning","Supplier coordination","Purchase control","Delivery tracking"]],["Risks & Delays","Planned",["Risk identification","Delay analysis","Impact assessment","Evidence-linked reporting"]],["OCR & Evidence","In Development",["OCR & data capture","Document classification","Search","Evidence linking"]],["Signals & Insights","Planned",["KPI monitoring","Trend detection","Forecasting","Capacity analysis"]]],
  process:["FROM REALITY TO DECISION","One continuous intelligence chain.","Every decision can trace its origin — from physical evidence to engineering context, commercial logic and operational learning.","Reality","Scanner","Work Scope","Technology","Engineering Norms","Materials","Pricing","Estimate","Execution","Analytics"],
  roleIntro:["FOR EVERY ROLE","Different responsibilities. One shared reality.","Each person sees what matters to their role, while every action remains connected to the same governed system."],
  roles:[["Owner / Director","Portfolio truth, financial control and decisions that need authority.","Strategic view",["Portfolio","Finance","Analytics","Decisions","Growth"]],["Foreman / Manager","Scope, progress, evidence and the next operational action on site.","Operational view",["Projects","Team","Progress","Problems"]],["Worker","Clear assignments, verified context and less administrative noise.","Action view",["Tasks","Reports","Photos","Voice"]],["Client","Transparent progress, documents and approvals in one shared context.","Collaboration view",["Progress","Photos","Documents","Approvals"]]],
  investors:["INVESTOR PERSPECTIVE","Building infrastructure for the next generation of business.","OMNIRO begins where operational complexity is real: construction. The architecture is designed to expand through modular, governed intelligence.","Investor Relations","Construction","Operational Data","AI Intelligence","Commercial Platform","Business OS","Construction-first strategy","Operational foundation","Modular architecture","European market focus","SaaS model potential","Multi-industry vision"],
  roadmap:[["Foundation","Built"],["Construction Intelligence","In Development"],["AI Orchestration","In Development"],["Commercial Platform","Planned"],["International Expansion","Planned"],["Business OS","Planned"]],
  final:["ROADMAP","A disciplined path from foundation to Business OS.","Direction without artificial deadlines. Each stage advances only when its authority, data and operational foundations are ready.","Built","In Development","Planned","THE NEXT OPERATING LAYER","The future of business will not be managed by disconnected software.","It will be orchestrated.","Explore OMNIRO","Become a Partner"],
  footer:[["Platform",["Overview","Intelligence","Automation"]],["Building",["Construction","Room Scanner","Engineering"]],["Technology",["Architecture","AI Agents","Security"]],["Company",["Investors","Roadmap","Contact"]]],
  legal:["AI Operating System for Construction and Business.","All rights reserved.","Privacy","Terms","Languages"]
});
