import{randomUUID}from"node:crypto";import type{PoolClient}from"pg";import type{AiActor,AiPlatformRepository}from"../../application/ai-platform/ai-platform-repository.js";
export class PostgresAiPlatformRepository implements AiPlatformRepository{
 async project(db:PoolClient,a:AiActor,id:string){return(await db.query(`SELECT id,project_number "projectNumber",name,status,version,client_id "clientId",expected_completion_date "expectedCompletionDate",currency_code "currencyCode" FROM projects WHERE tenant_id=$1 AND id=$2 AND deleted_at IS NULL`,[a.tenantId,id])).rows[0]}
 async clientProjectAccess(db:PoolClient,a:AiActor,id:string){return Boolean((await db.query(`SELECT 1 FROM client_project_memberships WHERE tenant_id=$1 AND user_id=$2 AND project_id=$3 AND status='active'`,[a.tenantId,a.id,id])).rowCount)}
 async findClient(db:PoolClient,a:AiActor,projectId:string,query:string){return(await db.query(`SELECT c.id,c.name,c.status,c.version FROM projects p JOIN clients c ON c.tenant_id=p.tenant_id AND c.id=p.client_id WHERE p.tenant_id=$1 AND p.id=$2 AND c.deleted_at IS NULL AND($3=''OR c.name ILIKE'%'||$3||'%')`,[a.tenantId,projectId,query])).rows[0]}
 async findDocument(db:PoolClient,a:AiActor,projectId:string,q:{type?:string;search:string;approved:boolean}){const clientOnly=!a.permissions.includes("documents.read")&&a.permissions.includes("client_workspace.read");return(await db.query(`SELECT d.id,d.title,d.document_type "documentType",d.source_type "sourceType",d.status,d.version,d.updated_at "updatedAt",v.id "versionId",v.version_no "versionNo",v.created_at "versionCreatedAt",v.original_filename "filename",ad.id "approvedDataId",ad.approved_at "approvedAt",ad.approved_by "approvedBy" FROM documents d JOIN document_links l ON l.tenant_id=d.tenant_id AND l.document_id=d.id AND l.entity_type='project'AND l.entity_id=$2 JOIN document_versions v ON v.tenant_id=d.tenant_id AND v.id=d.current_version_id LEFT JOIN LATERAL(SELECT x.id,x.approved_at,x.approved_by FROM document_approved_data x WHERE x.tenant_id=d.tenant_id AND x.document_id=d.id ORDER BY x.approved_at DESC LIMIT 1)ad ON true WHERE d.tenant_id=$1 AND d.deleted_at IS NULL AND($3::text IS NULL OR d.document_type=$3)AND($4=''OR d.title ILIKE'%'||$4||'%'OR v.original_filename ILIKE'%'||$4||'%')AND(NOT $5::boolean OR ad.id IS NOT NULL)AND(NOT $6::boolean OR EXISTS(SELECT 1 FROM client_project_documents cpd WHERE cpd.tenant_id=d.tenant_id AND cpd.project_id=$2 AND cpd.document_id=d.id))ORDER BY COALESCE(ad.approved_at,d.updated_at)DESC,v.version_no DESC,d.id LIMIT 1`,[a.tenantId,projectId,q.type??null,q.search,q.approved,clientOnly])).rows[0]}
 async invoices(db:PoolClient,a:AiActor,projectId:string){return(await db.query(`SELECT id,invoice_number "invoiceNumber",status,gross_amount "totalAmount",currency_code "currencyCode",due_date "dueDate",version,updated_at "updatedAt" FROM invoices WHERE tenant_id=$1 AND project_id=$2 AND deleted_at IS NULL ORDER BY issue_date DESC NULLS LAST,id LIMIT 50`,[a.tenantId,projectId])).rows}
 async estimate(db:PoolClient,a:AiActor,projectId:string){return(await db.query(`SELECT e.id,e.code,e.title,e.version,e.updated_at "updatedAt",r.revision_number "revisionNumber",r.status,r.totals,r.pricing_authority "pricingAuthority",r.material_consumption_snapshot_id "materialConsumptionSnapshotId",r.pricing_snapshot_id "pricingSnapshotId",r.company_price_book_snapshot_id "companyPriceBookSnapshotId" FROM commercial_estimates e JOIN commercial_estimate_revisions r ON r.tenant_id=e.tenant_id AND r.estimate_id=e.id WHERE e.tenant_id=$1 AND e.project_id=$2 ORDER BY r.revision_number DESC LIMIT 1`,[a.tenantId,projectId])).rows[0]}
 async attention(db:PoolClient,a:AiActor,projectId:string){return(await db.query(`SELECT id,'task'"entityType",title label,status,version,due_date "dueDate" FROM tasks WHERE tenant_id=$1 AND project_id=$2 AND deleted_at IS NULL AND(status IN('blocked','submitted_for_review')OR(due_date IS NOT NULL AND due_date<=current_date+interval'2 days'))ORDER BY due_date NULLS LAST,id LIMIT 25`,[a.tenantId,projectId])).rows}
 async weather(db:PoolClient,a:AiActor,projectId:string){return(await db.query(`SELECT id,source,source_reference "sourceReference",location_label "locationLabel",forecast_at "forecastAt",temperature_c "temperatureC",humidity_percent "humidityPercent",precipitation_probability "precipitationProbability",wind_speed_mps "windSpeedMps",condition,verified_at "verifiedAt" FROM construction_weather_forecasts WHERE tenant_id=$1 AND project_id=$2 AND verified_at>=now()-interval'7 days'AND forecast_at>=now()-interval'1 day'ORDER BY forecast_at LIMIT 100`,[a.tenantId,projectId])).rows}
 async createCommand(db:PoolClient,a:AiActor,x:any){const id=randomUUID();await db.query(`INSERT INTO omniro_ai_commands(id,tenant_id,requested_by,project_id,input_mode,request_text,intent,agent_id,truth_state,status,response_summary,result,source_references,permission_context,created_by,updated_by)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$3,$3)`,[id,a.tenantId,a.id,x.projectId??null,x.inputMode,x.text,x.intent,x.agentId,x.truth,x.status,x.message,JSON.stringify(x.result??{}),JSON.stringify(x.sources??[]),JSON.stringify(a.permissions)]);return id}
 async createDraft(db:PoolClient,a:AiActor,x:any){const draft=(await db.query(`INSERT INTO omniro_ai_action_drafts(tenant_id,command_id,project_id,action_type,payload,source_references,created_by,updated_by)VALUES($1,$2,$3,$4,$5,$6,$7,$7)RETURNING id,status,version,requires_human_approval "requiresHumanApproval"`,[a.tenantId,x.commandId,x.projectId,x.actionType,JSON.stringify(x.payload),JSON.stringify(x.sources),a.id])).rows[0];if(x.actionType==="message_draft"){const recipient=x.payload?.result?.recipient,conversation=(await db.query(`INSERT INTO communication_conversations(tenant_id,project_id,client_id,subject,related_entity_type,related_entity_id,created_by,updated_by)VALUES($1,$2,$3,'AI Secretary message draft','project',$2,$4,$4)RETURNING id`,[a.tenantId,x.projectId,recipient?.clientId??null,a.id])).rows[0],message=(await db.query(`INSERT INTO communication_messages(tenant_id,conversation_id,sender_actor_id,recipient_resolution,project_id,client_id,related_entity_type,related_entity_id,channel,direction,body,status,provenance,created_by,updated_by)VALUES($1,$2,$3,$4,$5,$6,'project',$5,'email','outbound',$7,'DRAFT',$8,$3,$3)RETURNING id,status,version::int`,[a.tenantId,conversation.id,a.id,{to:[],cc:[],...recipient},x.projectId,recipient?.clientId??null,x.payload.text,{aiCommandId:x.commandId,aiActionDraftId:draft.id,sourceReferences:x.sources,humanReviewed:false,providerTruth:"UNAVAILABLE"}])).rows[0];draft.communication={conversationId:conversation.id,messageId:message.id,status:message.status,version:message.version}}return draft}
 async history(db:PoolClient,a:AiActor){return(await db.query(`SELECT id,project_id "projectId",input_mode "inputMode",request_text "text",intent,agent_id "agentId",truth_state truth,status,response_summary message,result,source_references sources,version,created_at "createdAt" FROM omniro_ai_commands WHERE tenant_id=$1 AND requested_by=$2 ORDER BY created_at DESC LIMIT 50`,[a.tenantId,a.id])).rows}
 async audit(db:PoolClient,a:AiActor,action:string,id:string,metadata:Record<string,unknown>){const correlation=/^[0-9a-f-]{36}$/i.test(a.correlationId)?a.correlationId:randomUUID();await db.query(`INSERT INTO audit_logs(tenant_id,actor_id,action,entity_type,entity_id,correlation_id,metadata)VALUES($1,$2,$3,'omniro_ai_command',$4,$5,$6)`,[a.tenantId,a.id,action,id,correlation,metadata])}
}
